---
title: "Theory of Relation. Basic Key Concepts and Prospect"
indent: true
output:
    html_document: default
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[english=quotes]{csquotes}
---

To the question of whether a theory of relation is necessary today, we can answer yes, provided certain conditions boil down to not falling into the shortcomings that usually plague sociological approaches using a relational scheme and, instead, to deliver a comprehensive and in-depth view on actors circulations from positions to other positions through relation. Let us detail these conditions with which we would like to introduce this chapter on the key concepts and the prospect of the theory of relation [cf. for an extended outline @PapilloudSchultze2022].

The first condition sounds paradoxical for a theory that speaks about the relation: to avoid the false problem of trying to define what the relation is. It means that the relation cannot be reduced to a well-defined factual-like phenomenon because this word designates a set of very varied phenomena which bring together, link and unlink humans and non-humans, i.e. animate or inert, material or immaterial actors, symbols, ideas, representations, and other media. Considering this range and multidimensionality associated with the term _relation_, we will speak later of such phenomena as relational events, ranging from simple contacts to actions, interactions and other social relationships. Yet, a theory of relation should not only report this diversity. It must work out its modes of organisation while avoiding reducing them to the ones of individual or collective actors. The theory of relation does it by speaking of relational structures -- we distinguish later four relational structures, and we will explain why there are no less or more relational structures -- which actors differently support.

The second condition is that these relational structures do not represent either homogeneous or stable sets of relational events. Instead, they transform when interactions, actions, and relationships of all kinds take place, which is not without consequences for the existence of the humans and non-humans actors that these relational events bind and unbind. Formulating a theory of relation today means something other than recording these transformations, like a seismograph records the tremors of the earth's crust on a moving roll of paper. Such a theory should understand that these transformations are alternatives within each relational structure, alternative ways of organising relational events that each relational structure contains as one of its possible dynamics.

A direct consequence of this second condition is that any relational structure carries on its subversion because it contains alternatives to its mode of organisation. As we shall see later, these alternatives relate to the specific mode of organisation of the other relational structures. From this viewpoint, relational structures retain the general property of any relational events: they are composite -- heterogeneous or ambivalent -- which means that a single social relationship, a particular interaction or an action can express other social relationships, interactions or actions. Therefore, these relational structures do not only structure the lifestyles of individual and collective actors. They also condition the alternatives to these ways of life as so many possibilities to subvert a relational structure, to organise it according to other principles, which are nothing but the principles of other relational structures.

Here are the very basics of the theory of relation, which seeks to understand the structuring power of the interplay between relational structures and its consequences for the individual and collective actors in these structures. Or to formulate the same sentence from the viewpoint of individual and collective actors, the theory of relation analyses how ways of life that impose themselves on others reinforce or weaken the relational structure that models them, contributing to its imposition on other relational structures or, conversely, to its submission to them. The utopia of the ideal relation motivates such influences within and between relational structures. Through the variety of its individual and collective actors, each relational structure tends in its way to becoming this unique, perfectly harmonious relation, this omnipresent reference frame of all possible forms of life, infinitely constant in space and time, without borders or age, beyond the by-products of relational structures which, because they are the concrete manifestation of the practical impossibility of this utopia, nevertheless maintain its temptation. In a sense, the theory of relation shows that because this utopia fails to become concrete, social life gains in specific shapes through relation.

In our chapter, we want to get deeper into the theoretical apparatus at the bottom of the theory of relation, which models its dynamic architecture. First, we argue that the theory of relation theorises the dynamic character of relational structures with the concept of circulation. It leads to the assertion that the theory of relation rest on the primacy of circulation. To understand what circulation means and does, we have to go into more detail about relational structures. It will lead us to speak about the sequences structuring them, outlining the general circulation specific to each relational structure that supports the particular circulations of actors within and between these relational structures and their inscription in these structures.

In the second step, we detail our argument about the inscription of actors in relational structures. We introduce the two concepts of the actors' resistance on the one hand and of reciprocity in relational structures on the other. We explain why these three concepts link to each other in the theory of relation and how they contribute to the distribution and differentiation of actors and social instances in the relational structures. We further argue that the variations in the distribution and the differentiation of actors and social instances contribute to expanding or, on the opposite, to shrinking relational structures, which accordingly strengthen or weaken their circulation, the corresponding inscription of actors and collective actors in these structures and their resistive power.

Third and finally, we draw the consequences from our two first steps, which lead us to underline the general message of the theory of relation. As a sequential order of circulations, each relational structure always influences the other ones according to the same pattern, which consists in propagating the concept of reciprocity that one relational structure represents and imposing it on all other relational structures, thus becoming this ideal relation that each relational structure tends to be.

Yet, we already have relational schemes in sociology, which develop even more systematically in the context of relational sociologies and similar prospects in the social sciences of the last two decades. Therefore, why do we need another one in the form of this theory of relation?

### Why a theory of relation?

The prospect and the corresponding conceptual apparatus which the theory of relation uses to develop its analysis go beyond the framework of relational approaches in contemporary sociology and social sciences. In what follows, we will see how the theory of relation takes up concepts that these approaches use or that are familiar to sociologists working at relational schemes and how it deconstructs and reformulates them. What motivates such deconstruction and reformulation is given with the starting point of the theory of relation: to understand relation as a macro concept [@Trezzini1999, 515; @Scott1991, 38; @Granovetter1979, 501, 517; cf. also @Schultze2022, 4]. However, taking the relationship as a macro concept brings with it difficulties that sociologists have underlined speaking more generally about process concepts and similar concepts that evoke an idea of process, for example recently, Wolfgang Knöbl in his monograph _Die Soziologie vor der Geschichte. Zur Kritik der Sozialtheorie_ (Sociology before History. A Critique of Social Theory) [@Knoebl2022]. In his book, Knöbl says that the social sciences, especially sociology and sociological theory, show deficits when they use the concept of process and similar ones denoting a process. Knöbl is "mainly concerned with the question of why the modern social sciences, and especially sociology, used robust process concepts from the start to explain their respective present on the one hand [...], but on the other hand periodically criticised precisely these concepts and the corresponding statements to which they lead, because actually none knows how well they grasp past and present" [ibid., 12-13, cf. also @Hoebel2020].

Especially in chapter seven on social sciences and the philosophy of history, Knöbl makes it clear that process concepts presuppose narratives that social scientists do not always consider when using such concepts. It often leads to a misrepresented complexity of the (according to Knöbl historical) reality that such concepts should describe. Can the description of broad social contexts in time and space capture what it claims to explain? Don't we see a tendency in the social sciences to rely "all too credulously on the explanatory power or even the conciseness and selectivity of these concepts" [@Knoebl2022, 271]? The point Knöbl emphasises is not so much that of the indeterminacy of concepts, of which the social scientist would not be aware (ibid., 280). Instead, his point regards the embedding of concepts in socio-political contexts where they channel events in a specific way (ibid., 257, 269) that contribute to the meaning of such process concepts that, therefore, cannot easily be used outside of these contexts which give them their sense.

If we look at the concept of democracy and its extension to "democratisation", for example, we notice, as Knöbl points out, that such an extension is subject to questions. These questions range from the relationship between the economy and politics, between the population and the state, and between equality and inequality yesterday and today, here and elsewhere on the planet. Such questions lead to controversial discourses in the social sciences based on "narratives" that do not come to a satisfactory conclusion which would be universally valid in time and space (cf. Knöbl's discussion of Charles Tilly's analysis of democracy and democratisation, ibid., 285-288). Knöbel's critique likewise affects relational sociologies as they primarily focus on -- frequently deconstructed -- process concepts. Such concepts do not only build the starting point of relational sociologies -- the main object of relational sociologies are "processes" on the one hand and "dynamic, unfolding relations" on the other [@Selg2020, 15; cf. also the different versions of this view @Elias1977, 131; @Crossley2020a; @Emirbayer1997, 1998; Dépelteau2008, 2013b; @Papilloud2017; @Donati1995, 2013; @Bottero2011]. They also show the difference between relational sociologies depending on their specific understanding of relation [cf. @Prandini2015; cf. also @Selg2020, 30-35]. Taking into account the specific case of the theory of relation, one way to reflect on Knöbl's critique is to explain why and how it uses the concept of relation as it does and what it means for the framework that it supports [@Knoebl2022, 296]. It favours an in-depth deconstruction of this theory's starting point, providing a better understanding of its unfolding.

### Starting point of the theory of relation

The theory of relation does not rely on the assumption that its immediate object of investigation is social relations, human relationships, interactions and further such relational events [@Papilloud2017]. Referring to Knöbl, we have seen that such terms are not neutral. Instead, they are situated both historically and in our disciplines. In the particular case of sociology, they link to well-established movements and sometimes to certain good-identified theoretical traditions [regarding the expression _relational sociology_ or the word _relation_ cf. @Prandini2015]. We have learned that such process concepts like "relation" are not necessarily at the forefront of epistemological and theoretical interests in all sociological traditions [cf., for example, @monoPapilloud2002; @monoPapilloud2012a; @monoPapilloudRol2019]. In the French tradition, for example, they do not appear as the core element of theoretical frameworks, while conversely, they are critical for sociological investigations in the American sociological tradition. In the German sociological tradition, process concepts are sometimes more at the forefront of the theory. It is the example of Georg Simmel's works and his concepts of _Wechselwirkung_, _Vergesellschaftung_ and _Tausch_ [@monoPapilloud2002], of Leopold von Wiese's ontology of relation [@hgbuchPapilloud2006a], of the concept of communication and its different meanings and usages in German pragmatism, as in Jürgen Habermas' theory of modernity, or Niklas Luhmann's systems theory [@kapitelPapilloud2005; @chapterPapilloud2005b]. However, such concepts usually support a view often understood as a heuristic for the study of other more important topics for these theories such as modernity, the forms of sociability in the history of societies, social homeostasis, values, and complexity to mention a few. In other words, such process concepts remain a means to an end. In themselves, they do not represent the core of sociological enquiry.

Like these last examples, relational sociologies rely not primarily on one process concept but several process-like concepts [@Selg2020, 30-35] that they equate with or translate into _relation_. What explains these translations is the understanding of society _as a relation_. Here, the emerging point of society is the interpersonal relationships conceived _as a relation_ which leads to a corresponding sociological investigation of societies _as relation_. It is the point where the theory of relation differs from these sociologies. It does not formulate the assumption that processes in the weak and non-homogeneous sense of relations emerge between people because, from the viewpoint of the theory of relation and following other theoretical frameworks which are sensitive to relational events, they are not specific to humans beings only [@LatourStrum1986; @Pyyhtinen2010; @Kaufmann2011; @Abbott2016]. Therefore, the theory of relation assumes that the relation is more than social relations in the sense of relational events, i.e. human interactions, social relationships, and actions. It is why it conceives the relation as a macro-sociological concept to frame the organisational mode of the diversity of relational events. It gives it the advantage of not reducing relational events to human interactions only and of not describing them _as relations_. Instead, the theory of relation explains them indirectly _through relation_, following in this sense the first founding sociological insights about relational schemes. It is the starting point of the theory of relation. It makes relation not the answer to a multitude of questions but the question itself or -- in the sense of practical sociological investigations -- the problem that this theory deals with. It sees this problem as the fundamental question of social life, with which every society, every informal or formal group and every actor in these societies and groups always struggle, even if such struggle takes place in very different ways and gets therefore corresponding different meanings, as we shall see below.

The development of a macro concept and a macro understanding of relation, the corresponding macro-sociological view on relation at the core of the theory of relation rests on the insight -- here, for instance, in contrast to Pierre Bourdieu's macro-relational theory of relations _between positions_ [cf. @Bourdieu1987; @Bourdieu2019] -- that the explanation of the social _through relation_ should consider the position of actors and the relation symmetrically. It differs from other sociological theories using a relational scheme because it does not reduce position to relation and relation to position. It focuses on the dynamics between position and relation, which the theory of relation understands as a circulation between positions through relation. It is why the theory of relation argues according to the primacy of circulation, and to understand better what such primacy of circulation means and supposes, we develop the concept of relational structures.

### Primacy of circulation and relational structures

The primacy of circulation means that actors and actants circulate within and between relational structures, which shapes the general dynamics between position and relation that generates these relational structures. This circulation is not _sui generis_; it does not happen automatically. Instead, it supposes the work of actors on relational events. This circulation does not proceed circularly either, but it varies within relational structures and from one structure to another. These variations mean that the circulation paths of actors and actants turn out very differently. They are differently short or long, fast or slow, stable or vulnerable. They account for the infinite complexity of the circulation of actors and actants, which the theory of relation grasp in working out the principles that organise such circulations. These principles are nothing else than the said relational structures. Why are circulations complex?

On the one hand, circulations suppose relational events, which are events for this reason that they are not and never fully developed. Consequently, relational events have no determinable origin, have unpredictable ends, and show unexpected mutations. It is where the theory of relation differs from Knöbl's view on process concepts. Like Bruno Latour, Knöbl understands processes as an arrangement of interlinked events, which Knöbl sees bound to an apparent "beginning and end point" [@Knoebl2022, 258; cf. also @Latour2005]. In Knöbl's case, such a view on processes implies not only that events have _one_ determinable starting and end point but also that they retain their (initial) form and quality throughout time and are accordingly "closed" [@Knoebl2022, 261]. In contrast, the theory of relation captures events in their social embeddedness, in their manifold possibilities of development and connection, in their potentiality of being left behind, of being taken up again and of being (repeatedly) influenced, thus taking into account both the heterogeneous structure and the indeterminacy of events [cf. @Seyfert2019].

On the other hand, the complexity of circulations rests on the fact that relational events are _by definition_ always in becoming and, accordingly, diverge from a successful, ideal relation with a beginning, an end, with recognisable, clearly situated actors who it would connect. Therefore, the theory of relation conceives relational structures as divergent assemblages of relational events with actors, actants, instances, symbols, signs and media. As we want to avoid repeating such a succession of terms like actors, actants and so on, we speak in the following of actors and actants to differentiate human and non-human actors. Moreover, since we are primarily concerned with the basics of the theory of relation in this chapter, we will not cover the critical meaning of the media that the theory of relation formulates as mediations of relational events. Within the theory of relation, the media are connected with the symbolic operations of actors and with the formal procedures of instances that support circulations specific to relational structures. They provide a better understanding of the weakening/disruption of a relational structure and the corresponding development of alternative circulations in this relational structure [more on this in @PapilloudSchultze2022, 313-370]. Yet, let us return to the theory of relation basics.

The divergent characteristic of relational structures does not solely result from the combination of relational events with actors and actants. It also results from their specific dynamics. Relational structures develop or do not develop, which presupposes a work on relational events, even if such work does not necessarily occur all the time precisely because relational structures do not automatically and inevitably develop. If they can spread, they can shrink just as much because actors and actants do not constantly work on relational events or contribute to such work. Such work is, therefore, intrinsically nonuniform, reflecting the great diversity of relational events, actors and actants supporting such work. Here we have another important feature of the theory of relation, which we can highlight as follows. Because relational events are diverse, all possible actors can claim them and involve all possible actants. Because these actors and actants are various, they can claim all possible relational events or take part in the work on relational events. This fundamental openness of relational events to actors and actants and vice versa means that the work on relational events does not link to specific actors and actants that would develop a relational structure. It can happen here and there, and if it is not taken up here and now by these or those actors with these or those actants, it will sooner or later be taken up elsewhere by other actors with other actants. Therefore, the work on relational events performs unequally because it virtually links to all the actors and actants in relational structures. For this reason, the work on relational events is a constant of relational structures because it concretely happens if not here, then there, if not with such actors and actants, then with other ones. In its heterogeneous forms, the work on relational events plays a significant role in favouring or against the development of relational structures.

### Work on relational events

Working on relational events supports the development of relational structures, which concretely means it promotes circulation paths and possibilities for actors. Because of the fundamental openness of relational events to actors and actants and vice versa, it is unlikely that only one actor with only one actant work on only one relational event. More likely is the assembly of different actors and actants around various relational events or a heterogeneous composition of actors, actants and relational events. One cannot rule out that such an assembly takes form because actors, actants and relational events are products of history whose history brings them in contact [cf. empirically in the field of relational sociologies @Bidart2011]. It only develops further if there is further work on relational events. If it is not the case, there is no further development of relational structures and no support for the circulation of actors who evolve as if they were actants on their unstructured circulation paths until such paths dismantle. However, suppose the contact between assembled actors and actants develops further. In that case, it can lead to the mobilisation of (present as well as absent) actors and actants and the channelling of relational events supporting the development of relational structures [on the meaning of the contact as a concept denoting this area between position and relation, cf. @Papilloud2017].

As Mark Granovetter notes using the example of "weak ties", even weakly structured relationships can favour the assembly of actors without them being actively involved in relational events [@Granovetter1973, 2005]. Therefore, actors can achieve goals by investing less work in relational events. It saves personal energy, as Georg Simmel already underlines [cf. @Simmel1890, 280], even if one should put such an assumption into perspective. More or less well-structured relational structures exist because one cannot exclude that social work occurs somewhere or that someone has initiated it. Therefore, the power of "weak ties" does not only exist because actors do not necessarily have to devote themselves to work on relational events -- i.e., mobilising further actors and actants, channelling relational events and paving circulation paths, resulting in circulation possibilities. It also exists because such work has occurred at some point or because someone has already initiated it. It is a point on which the theory of relation differs from other relational approaches. It does not assume that relational events always exist because they would be always present as transcendental entities in the social world. Relational events and, therefore, relational structures exist because one can not exclude that someone, somewhere, at some point, works them out. This turn from an ontological perspective that substantiates the relation to a sociological perspective that makes the relation a collective good nevertheless asks a question. If we are not living in a social world full of relational structures, if there can also be no relational structure at some point, how can we conceive this distinction between the presence and absence of relational structures in a unified way? This question finds its answer with the primacy of circulation.

Unlike differentiation theories that insist on sharp boundaries separating social subjects, objects, and areas of activities and often substantialise differences _in abstracto_, i.e. disregarding the collective nature of social life -- what is not left is right, what is not up is down, what is not in is out, etc. [cf. paradigmatically @Bourdieu1987] --, the theory of relation does not prioritise sharp distinctions between what relational structures are and what they are not. Instead, consistently with its primacy of circulation and its conception of social work on relational events, it bases these differences on the distinction between circulation paths within relational structures on the one hand and between relational structures on the other. This distinction, in turn, comes from the conception of relational structures as divergences from an ideal relation and as divergences from such divergences, i.e., from other relational structures. As we have seen above, the theory of relation argues that, in practice, there is no perfect, ideal relation. Therefore, relational structures diverge from an ideal relation, just as circulations always diverge from an ideal circulation and just as relational structures also diverge from other relational structures.

Regarding the primacy of circulation, it means that circulation paths _within_ a relational structure differ from circulation paths _between_ relational structures or circulation paths in another relational structure. If we think about it at the level of relational structures, it means that these divergences stratify the relational structures through circulation paths and possibilities. Correspondingly, divergences stratify these circulations or represent the stratification principle attached to the primacy of circulation itself.

Similarly to Standing, who describes the numerous variations of more or less "strong" or "weak ties" [@Standing2007], the theory of relation says that there are multiple variations of the primacy of circulation in the form of diverse circulations within and between relational structures. But more concretely, how can we understand this stratification of circulations and relational structures? We can understand it sequentially.

### Divergent relational structures and sequences

Divergences are not showing up all at once, but sequentially, one divergence enabling further ones. The first divergence from an ideal relation comes from the practical idealisation of the relation itself, which shapes the dynamics of a first relational structure relying on the investment in the work at relational events. A second relational structure diverges from such an idealisation, in which the actors emphasise their representation through collectives, without which no work on relational events would be possible. A third relational structure diverges from this second one, in which the materiality or the realisation of actors stays in the foreground, without which the collectives would not exist and without which an investment in the work at relational events would not be conceivable. A fourth relational structure diverges from this last relational structure, emphasising the attractiveness of the media, i.e. of the mediations without which actors would not be able to realise themselves, build collectives and manage to work on relational events. Or more simply, what predominates when it comes to organise the work on relational events can be the relation itself, the collective it supposes, the individual actors building this collective or the mediations used to perform this work. This brings us to describe the motivations and the dynamics conditioning the divergent development of relational structures at the level of the distinction between position and relation.

The distinction between position and relation translates into the difference between actor-centred and exchange-centred relational structures. This distinction defines the first two main features corresponding to two relational structures, i.e., it leads to the first two divergences from an ideal relation corresponding to a relation-centred and position-centred relational structure. From this first distinction between two relational structures, two further relational structures emerge that diverge from an exclusively relation-centred and an exclusively position-centred relational structure. These latter divergences are "second-order divergences from first-order divergent relational structures" [@PapilloudSchultze2022, 24]. They produce two further alterations of the two main relational features of the two first relational structures. On the one hand, we have a third relational structure in which actor-centred features damp its exchange-centred features. On the other hand, we have a fourth relational structure in which the exchange-centred features balance actor-centred features.

Whether in terms of the work on relational events or the distinction between position and relation, let us underline what we said above about the development of relational structures: it is sequential. Relational structures diverge from an ideal relation, producing further divergences until such divergences are exhausted. What makes a relational structure diverge from another relational structure is the same as what makes relational structures diverge from an ideal relation, namely the divergence from the main feature of a given relational structure. This main feature gives a relational structure its unique feature compared to the other relational structures, as we have seen above. At the same time, the main feature of relational structures is the point where they differ from each other on the one hand and diversify internally on the other. This internal diversification of relational structures results from the primacy of circulation: circulations circulate differently. Second, it is a consequence of the sequential development of relational structures as divergences from an ideal relation. It, in turn, means that even within relational structures, divergences from the main feature of these relational structures take place, which are similar to the divergences between relational structures.

Therefore, in every relational structure, we find a divergence firstly from the investment in the work on relational events, secondly from the representation of actors by collectives, thirdly from the materiality of the actors and fourthly from the attractiveness of mediations involved in such work. From a general viewpoint, one could say that in the theory of relation, we always deal with the same relational structure, even if we distinguish four relational structures. Such an observation, however, only refers to a decidedly structuralist view on relational structures that do not take into account their circulation dynamics. Once we understand relational structures as structured through circulations, we see that even if these relational structures present identical sequences, i.e. the sequences structuring the social work on relational events that equally show up in all relational structures, the sequence representing their main feature differs in each. Yet, because a relational structure develops in supporting its main feature, its internal differentiation and corresponding dynamical structuration do not follow the same pattern as in another relational structure. It is valid for all four relational structures, and it means that although the sequences of investment, representation, materiality and attractiveness are present in support of every circulation within and between relational structures, they do not show up in the same order of priority. Instead, they are mobilised sequentially from the point representing a relational structure's main feature. Therefore, based on the primacy of circulation, the theory of relation distinguishes four relational structures that are not structurally different but differ from each other due to their specific circulation.

The central feature of the relational structure that first diverges from an ideal relation is the investment in the work on relational events that collectives represent, actors of these collectives materialise, and mediations used in such investment make attractive. From this relational structure diverges a second one where the representation of such investment in relational events is in the foreground that actors materialise, making its mediations attractive in support of investments in relational events that lead to underline the importance of such representations. The third divergence develops from this second relational structure highlighting the materialisation power of actors, making its mediations attractive to stimulate investments in relational events and their representation in support of the further realisation of actors. A final divergence emerges from this third relational structure, pointing out the importance of the mediations that make the investments in relational events attractive and stimulate the latter, its representation and the materialisation of this representation through the realisations of actors.

This description of relational structures from the viewpoint of their sequences does not only underlines their specific meaning as dimensions of the primacy of circulation. It also shows that relational structures are separated because their circulation diverges. Such separations mean that we have a space between relational structures -- similar to what François Dépelteau means when he speaks of transactional areas [@Depelteau2013b] -- enabling circulations from one relational structure to another, which finds its counterparts between sequences within relational structures, enabling the circulation from one sequence to the following sequence in each relational structure. These spaces favour other divergences from divergent circulations, even if such divergences cannot be repeated _ad infinitum_. Further divergences of relational structures always return to one or another of these four existing relational structures or one or another of their four sequences. It means that from the viewpoint of the theory of relation, there is no exteriority to the relation, which is an essential condition that warrants a theoretical frame entirely structured by the relation.

Circulations behave similarly to relational structures. Individual actors and actants of different natures (such as signs, symbols, media, things, bacteria) circulate, even if they circulate differently. Here, the theory of relation draws the lesson of relational schemes in sociology based on the concept of _agency_ [cf. @Somers1994; @Emirbayer1998; @White2008; @Mische2011], according to which categorical strategies in sociology can not satisfactorily capture actors' identity (using categories like, for example, gender, age, and occupation) without stigmatising the actors. Such stigmatisation or reductive view on actors contrasts with views on actors' identity based on the relational agency as sequential embeddings of cultural, social and personal features that each actor represents. Yet, the theory of relation reverses this scheme. Rather than an embedding of these features in actors, which would reflect their specific identity or _agency_, the theory of relation speaks of the inscription of these actors in circulations that provide such features to them and, therefore, singularise actors [@Thevenot1984; @Lahire2001]. Not the embedding of features but the inscription of actors in circulations, sequences and relational structures where these features circulate contribute to their identity as singular actors. Such a reformulation of the relational _agency_ supports the primacy of circulation insofar as it presupposes that differences between human actors, human and non-human actors, individual and collective actors translate into different inscriptions in circulations. More concretely, if individual human actors circulate along sequences of relational structures and relational structures, the circulations of non-human actors develop independently from sequences and relational structures within and between every sequence and relational structure. Finally, collective actors and further mediating instances that emerge from them do not circulate. They age in sequences and relational structures in which they expand or shrink. As for relational structures and sequences of relational structures, this distinction between circulating and non-circulating actors rests on the concept of inscription, which is, as we shall see later, closely related to the two concepts of resistance and reciprocity within the theory of relation.

### Inscription

The concepts of inscription, resistance and reciprocity describe what circulations concretely require to circulate, to structure sequences in relational structures and these relational structures, resulting in a differentiation of circulations, related activities and spheres of activity as well as related (collective) actors and actants in relational structures. Because relational structures formally and structurally rest on the same basic principles, they are open to all social activities and spheres of activity. It is why, conversely, we can find all conceivable activities and spheres of activity in each relational structure. However, since we subvert forms and structures through the primacy of circulation or because relational structures root in circulations, it is likely that activities and spheres of activity do not develop arbitrarily but according to how they support the sequential organisation of circulations in the corresponding relational structure. Such support results from the inscription of actors with actants and more or less formal collective actors such as institutions and organisations in such relational structures.

Therefore, the inscription's concept means what materialises the distinction between relational structures and sequences in relational structures. It clarifies the position of actors in relational structures on the one hand, while on the other hand, it informs about their performed circulations and further circulations to complete. Thus, the inscription presupposes anchoring in sequences of relational structures (from the viewpoint of the actors' position) and distribution over other sequences of relational structures and other relational structures (from the perspective of relation). It differentiates actors' circulation paths, potentiates them, and opens them up to further possible circulations. It is the general meaning of the concept of inscription, and we now look at it in more depth from the viewpoint of the work on relational events.

The concept of inscription presupposes performing social work on relational events. It means the involvement of actors with other (collective) actors and with actants in these relational events, even if such an involvement alone is insufficient if it does not mobilise these actors and actants or does not contribute to assembling them at least weakly. There are enough examples of social work that hardly motivate actors, from which actors sooner or later turn away, which proves that acts of inscription only happen sometimes. However, there is also work that one needs to do or would like to realise, activities that rob one's inner peace, illustrating that acts of inscription happen. Such involvement leaves psychological and physical traces. It sometimes drives the actors on and around for a lifetime. It changes them over time until this inscription, as severely as it may occasionally succeed, gains in recognition and leads to the legitimation of the actors involved, as modest as this legitimation may sometimes return, like, for example, in the case of the recognition of existing fundamental rights [@Thevenot2001; @Boltanski2007]. Yet, this inscription has a different meaning depending on which type of actor we consider.

Individual human actors need such an inscription to support further the readjustment of their position in sequences and relational structures or to further work on relational events. Collective actors need such inscription for further consolidation of their position. As Latour would say, collective actors warrant _obligatory passage points_ for actors [@Latour2005] that support and sanction (positively or negatively) actors' work on relational events. In the sense of non-human, material or immaterial actors, actants do not need such inscriptions because their circulation develops disregarding the sequential order of relational structures. It is why actants can affect but do not depend on actors' circulation or collective actors' position. In turn, it ensures that any human individual actor or collective actor can take them up, use them, change or discard them in any circulation. Whether actants support or inhibit the inscription of actors, they contribute to the complexity of that inscription and its divergent nature as an inscription that can never be perfect.

An inscription is thus an act of more or less successful involvement of actors in their work on relational events with collective actors and actants. It dampens the importance of the work of both actors with actants in the sense that inscription relates the activities of both parties to or anchors them in a sequence of a relational structure and, therefore, in a relational structure. Due to the divergent nature of relational structures, the multiplicity of possible circulations and the actants as instances of mediation of such circulations at the different sequential levels of relational structures, acts of inscription never occur unilaterally as if only the circulating actors would perform them. Acts of inscription always presuppose the involvement of legitimating collective actors in the actors' work on relational events. These collective actors are thus fundamentally instances that mediate circulation paths and circulation possibilities for actors in sequences of relational structures and in these relational structures [for a similar conception of collectives, see @Grossetti2018; @Grossetti2022]. They illustrate the primacy of circulation in each sequence of a relational structure in which they take place.

Or, to put it differently: they socialise the actors to an understanding of circulation, sequences, relational structures, and they sanction them positively or negatively accordingly. It is why the theory of relation speaks of a _double inscription_ of actors in the social work on relational events. Actors inscribe themselves with collective actors in their work on relational events, resulting in mutual recognition and legitimacy.

The divergent nature of relational structures, sequences of relational structures, and the correspondingly more or less successful acts of inscription mean that the double inscription does not occur once and for all. Actors must repeat it with further collective actors of sequences and relation structures during the circulations of actors. Here, the theory of relation does not reinvent the wheel. On the one hand, it supports the widespread sociological scheme, such as in socialisation theories, role theories and conflict theories, according to which circulations lead to repeated lifelong acts of inscription of actors with collective actors. On the other hand, it takes up this argument with the primacy of circulation in such a way that acts of inscription condition the circulation paths of actors.

In contrast, such determinism varies to degrees of strength or weakness depending on which actors rely on which collective actors in which solid or weak state of a sequence and a relational structure. For example, the selection function of educational institutions such as schools or universities does not remain unchanged over time. It varies not only with pupils or students and to their original milieus who enrol with such social instances. It also goes with the presence or absence of competing educational institutions in other sequences of a relational structure as well as in other relational structures. Finally, it also varies with the social meaning of education as symbolic mediation in relational structures [see @Euriat1995; @Merle2002; @Albouy2003; @Lozach2020]. These variations of the deterministic power of inscription's acts open different circulation routes and further possible circulations for actors, and they determine the actors' expectations and expectations on expectations along the development of such circulations. It has corresponding consequences for the mobility of actors within and between sequences of relation structures and within and between relation structures. It stratifies these sequences and relational structures differently and makes them grow or shrink accordingly. We will not elaborate on these last two points in the context of this chapter. Instead, we would like to underline their common element: the actors' resistance.

### Resistance

The actors' resistance is a consequence of the starting point of the theory of relation. Let us summarise its meaning: Due to the non-uniform nature of the work on relational events, the multiplicity of these events as well as the multiplicity of actors and actants in relational structures, it is impossible for individual human actors to take a position in relational structures and to keep it definitively. Actors move from one to other positions sooner or later. For example, the socialisation of actors supposes the cooperation of actors with actants on the circulation path to pave. This cooperation makes actors change, i.e. it enables them to consider and eventually move to other positions. At the same time, this change of position and the actors' ability to rely on position do not reduce them to functions of relational structures, as if they would only contribute to normalising the development of relational structures. Let us detail this last argument because, at the same time, it provides the starting point of the concept of resistance in the theory of relation.

Actors can be reduced neither to position nor to relation, or to put it differently: they can change positions in relational structure, and therefore they can change relational structures, sequences of relational structures and circulations because they resist _in favour of_ and _against_ positions, sequences of relational structures, relational structures and circulations. Paths that the actors have paved and positions taken do not lead to the complete satisfaction or the complete disappointment of actors but to experiencing the diverging nature of relational structures as a condition of their circulations. Resistance reflects this embodiment of rearrangement as the constitutive duality of every human actor who takes up positions in circulations through relation and changes positions in relation through circulation. Let us deepen this conception of the actors' resistance.

Resistance is always a resistance _in favour of_ possible circulations between position and relation that constitutes the unique feature of each human individuality as a changeable individuality whose changes are performed step by step along the various acts of inscription of the corresponding actor in relational structures. Resistance is, at the same time, always a resistance _against_ other circulation possibilities and, therefore, different circulation paths, which could make acts of inscription more difficult or even impossible. Resistance is thus the expression of an individual law as Georg Simmel puts it and develops it at the example of the concepts of reserve, scruple, pudeur, and personal intimacy. It is the first stage in the experience of contact with relational events, further (present and absent) actors and actants at the individual level. It is the first stage of the experience of one's difference, which differentiates in further circulations during each actor's career [@Simmel1913]. To use an image: if the inscription gave the direction that actors' circulation takes, resistance would be like its re-orientation. Resistance motivates reflexivity, and the expression of affects that lead to expectations and expectations on expectations in the work on relational events. Accordingly, resistance conditions either support or destabilise the actors' inscription in circulations and, therefore, in relational structures. Because resistance is the expression of the actors' law and considering that such actors are products of history, resistance is not something that actors are fully aware of. It is why concrete expressions of resistance go from testing activities with different actors, actants, and relational events to the everyday development of tactics and strategies that accompany and influence the mobilisation of other actors and the work on relational events.

The relationship between the resistance _in favour of_ and the resistance _against_ a relational structure, the weight of both aspects of the resistance on the circulation between positions through relation, informs not only about the attitude of actors towards their relational structure and the state of its general circulation. This relationship also affects the path in-dependency of actors' circulations either within a sequence of a relational structure, between sequences of a relational structure, or between relational structures. Let us contrast this last observation from Bourdieu, for example, who understands the subtle differences between actors based on path-dependencies between habitus, capitals and fields which symbolise an external social order imposed on the actors given their "_relative positions_ in a space of relations" [@Bourdieu2012a, 48]. The resistance approach enables us to understand such differences between actors as how they strongly or weakly support this work during their social work. Accordingly, it allows us to reconstruct their position more _in favour of_ or more _against_ a sequence of their relational structure and their relational structure, as well as to reconstruct the order of such positions in relational structures. It leads to a mapping of the stratification of relational structures depending on how strongly or weakly the actors support them in each of their components (sequences and circulations). This results in describing actors' distinctive features and practices, not in terms of actual, existing actors' classes in society. Instead, distinctive features and practices lead to distinctive circulation possibilities that sequences and relational structures can deliver.

Or, to put it differently: if Bourdieu's sociological question was a question of power in support of domination that keeps society as is in time, the theory of relation shows, with its concepts of inscription and resistance, that "society" moves along circulations through relation, and that such moves contribute to favour some relational structures against other ones, as well as some sequences against other ones within relational structures. It results in the unequal distribution of circulation possibilities over sequences and relational structures that directly affect actors' categories and actors in these categories from the viewpoint of the affirmation of their difference, i.e. from the perspective of their inscription and their resistance in sequences and relational structures. It, in turn, means that social differences have to be conceived in their relationship to the state of circulations within and between sequences/relational structures to understand how much unequal they are and, therefore, how they contribute to social inequality between actors and actors' categories through sequences/relational structures, which translates into inequality between sequences and between relational structures.

This view on inequality does not affect individual human actors only. It also affects collective actors mediating the circulations in sequences and relational structures. At this point, the theory of relation takes up the question of reciprocity in a new way.

### Reciprocity

The concept of reciprocity closes the basic apparatus of the theory of relation and the channelling between inscription and resistance. If the inscription is like the direction of circulations and if resistance points out its orientations, the reciprocity describes the moment where the direction and the orientation of circulations contribute to the position of collective actors that, in turn, contribute to further differentiations of such circulations and, therefore, to further circulations of actors. With the inscription, the resistance and the reciprocity, we have three steps of the differentiation of actors' work on social events, where the next step acts as a moment of differentiation of the former stage. However, as in the case of the inscription and the resistance, some particularities are unique to reciprocity, which we describe hereafter.

In every variant of relational sociologies, theorising society according to a relational approach is assumed to presuppose a conception of reciprocity. The theory of relation is no exception, even if it understands reciprocity as follows. Instead of arguing ontologically and seeing reciprocity as a permanent property, i.e. as a substance of any relational events emerging from the interpersonal flow of exchange [@Bourdieu1983, 192; @Kondylis1999, 498; on Coleman and Bourdieu's implicit conception of reciprocity cf. @Schultze2022] translating into a foundation principle of a social relation between alter and ego [see paradigmatically cf. @Gouldner1960], the theory of relation says that reciprocity only exists if there is a successful double inscription. If there is no double inscription, then there is no reciprocity. We use this sharp formulation to make clear that, according to the theory of relation, reciprocity is not a back-and-forth _sui generis_ movement immanent to relational events. It, in turn, relates to what we have already mentioned regarding relational events that do not connect to anything by themselves. But let us go further into the characterisation of reciprocity from the viewpoint of the theory of relation.

The first characteristic of reciprocity is to underline the difference between actors (in their variants as human beings, collectives and non-human actants) and between actors and relational events in the sense of their different contributions to circulations in sequences and relational structures. Second, reciprocity enables translating different times and spaces into other -- quick/slow or short/long -- circulations that expand or contract the spheres of activity in sequences and relational structures. Reciprocity should therefore be understood contextually and from the viewpoint of the stratification of sequences and relational structures. Contextually, reciprocity acts as a principle of differentiation of spheres of activity. From the perspective of stratification, it acts as a principle of (re)distribution of actors across these spheres of activity. Reciprocity legitimises the reconfigurations between position and relation, which structure the spheres of activity, sequences, and relational structures.

Or, to put it differently: reciprocity in the theory of relation does not directly links to exchange and interdependent exchange practices. It does not develop from bipolar and multipolar interactions, from linear or from circular sequences of interaction _between people_ [as, for example, in the gift, cf. @Lévi-Strauss1981, 642-643 and also @Mauss1989], because reciprocity directly links to resistance and inscription and depends on them to become concrete. Reciprocity is not a norm but the result of social work based on more or less successful acts of inscription in sequences and relational structures, given the resistance of individual and collective actors to such acts of inscription. Therefore, if the social work of the individual and collective actors diverges based on diverging resistance, then the inscription in a relational structure is weakened or disturbed. It results in weak reciprocity that threatens the circulation of the individual human actors and the position of the collective actors. The collective actors have more difficulty supporting individual human actors' circulation paths and opportunities, which weakens the relational structure in parts or as a whole, blurring the differences between the circulations in a relational structure for all individual and collective actors. As a result, collective actors in such a relational structure have difficulties maintaining their position. They shrink or dismantle, which makes such a relational structure less attractive for individual human actors who tend to leave it for another relational structure. With fewer collective actors and individual human actors in the relational structure, the remaining actors have fewer circulation possibilities. On the contrary, strengthening the double inscription based on converging resistances in relational structure strengthens reciprocity, circulations paths and opportunities in such a relational structure, and finally, this relational structure in one or more of its sequences. It makes it more attractive for circulating actors, strengthening its influence on the other relational structures.

This understanding of reciprocity as the result of the double inscription and the resistance avoids the pitfalls related to an understanding of reciprocity as the direct result of interpersonal or intergroup relationships or as a "mechanical law" of gift and return gift [for example, on the law of reciprocal exchange formulated by Lévi-Strauss, cf. @Bourdieu2009, 226], which resumes to the view that individual human actors or collective actors could directly influence reciprocity [for example cf. @Bourdieu2009, 216] and alter its meaning, i.e. strengthen or weaken it. The latter presupposes that reciprocity would be in the control of actors, _as if_ they would control the double inscription, the circulations, the sequences and the relational structures. However, such a conception of reciprocity forgets the embedding of actors in the multiple levels of relational structures whose interplay, as well as the consequences of such interplay in terms of the divergences from this interplay, they cannot overwhelm at will, let alone eliminate them. Such a conception of reciprocity would also have the disadvantage of leading to an approach that could not address unintended effects of reciprocity, such as the sense of duty towards other actors or collectives, the identification with an activity, the feeling of belonging to a collective, without reducing such unintended effects of reciprocity to conscious or intended usages of reciprocity, to strategic action developing from interpersonal ordinary everyday relationships. Such a view on reciprocity confuses the parts with the whole, taking vestiges of reciprocity from past acts of inscription of actors and collectives for reciprocity itself. This belief in reciprocity that would develop from interpersonal relations and structure the whole of society proves once more how essential inscriptions and resistance _in favour of_ or _against_ such inscription are for actors and collectives, which therefore look for such reciprocity everywhere in their work on relational events, even if it does not develop from them but, instead, from acts of inscription, and fades away with them.

Yet, this does not mean that actors do not have any influence on reciprocity. It means that they affect the reciprocity of their relational structure indirectly, based on their social work on relational events on the one hand, and on the other hand through their inscription with collective actors in this relational structure. Collective actors also indirectly affect reciprocity in a relational structure. Unlike the individual human actors, however, they exert their influence by regulating the circulations in their relational structure, which enables them to maintain and ideally expand their mediation structure across the entire relational structure. It is a consequence of the non-circulation of collective actors that we have mentioned above: to maintain their position in their relational structure, collective actors seek to extend their view on reciprocity and the related techniques, strategies, formal procedures and the symbols they develop in support of such view to each sequence and each stratum of these sequences in their relational structures. Therefore, such collective actors contribute to the maintenance and, ideally, to the ascending social mobility of the category of actors they primarily deserve, given their position in a relational structure and its sequences.

Starting with Knöbl's critique of the use of process concepts in the social sciences, to which the concept of relation certainly belongs, we have explained how the theory of relation understands relation in the light of the primacy of circulation and what are the concepts that dimension such an understanding of relation. It leads to the message of the theory of relation that we have briefly introduced at the start of this chapter and to which we come back in our conclusion.

### Conclusion

The theory of relation states that relation as an ideal, perfect relation motivates social life and the various relational events that generate social life and sequentially dimension the divergences from such an ideal relation in the form of relational structures. Accordingly, the theory of relation explains how this quest for a perfect relation constantly vanishes at the different levels of a society, from which or through which, in turn, circulations of actors, mobilisations of collective actors, acts of inscription, ascending and descending mobilities, changes in inequalities, in strategies of influence, in power struggles, and even the production of social bubbles as vulnerable meta-relation structures generate.

In this chapter, we did not go so far in describing the theory of relation and the development of its message. Instead, we wanted to make its starting position clear, to explain it along its basic concepts -- beginning with the primacy of circulation, relational events, the divergent characteristic of relational structures and their sequences, through the social work of actors, their inscription with collectives and their related resistance _in favour of_ and _against_ their relational structure. Based on this starting point, it is possible to formulate the core question that this theory asks, which is the following: How do our societies in all their components and dimensions deal with rearrangements that result in inscriptions of actors with actants in relational structures and at which price? This question is perhaps the one that structures the diversity of relational sociologies and of sociologies that argue according to a relational scheme. Within the theory of relation framework, this question receives a clear answer, which develops in its complexity at the different levels of this theory, and we can formulate it like this: according to circulation through relation.

Unlike other or former relational schemes developed in sociology to theorise society, the theory of relation avoids reducing relation to a single meaning of this word and therefore avoids identifying relationships with a specific interaction. It also avoids flattening society, i.e., equating it with a relation or considering it _as_ a relation. It, therefore, deconstructs such forms of relationism to the advantage of an analytical, diachronic and synchronic comparative view of societies in transition, that is, in their different configurations as varying relational structures characterising these societies from their instances to their actors. Thus, the theory of relation cannot only support the relativism of relational approaches, according to which social phenomena are in relation. It can problematise it. It makes it productive for sociological investigations of society through relation, and it stimulates new views on habitual sociological questions such as social inequality, recognition and legitimation, associated sociability networks and their effect on alternative forms of social life beyond established hierarchies [cf. for an extended outline @PapilloudSchultze2022, 253-312], recognised rights and usual forms of social cohesion.

### Bibliography
