---
title: "Einführung"
indent: true
output:
    html_document: default
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Die Frage, ob die soziologische Theorie eine Theorie der Relation braucht, beantworten wir mit ja, wenn folgende Bedingungen erfüllt sind, die wir näher erläutern möchten und damit wir diese Einführung in die Schlüsselbegriffe und die Grundlage der Theorie der Relation eröffnen [vgl. ausführlich @PapilloudSchultze2022].

Die erste Bedingung betrifft die Ausgangsposition der Theorie der Relation, die mit dem Begriff der Relation eine Reihe von sehr unterschiedlichen Phänomenen bezeichnet, die Menschen und Nicht-Menschen, d.h. lebendige oder nicht lebendige, materielle oder immaterielle Akteure, Symbole, Ideen, Repräsentationen und andere Medien zusammenbringen, miteinander verbinden und voneinander trennen. Diese Breite und Multidimensionalität des Begriffs der Relation bezeichnet ihre drei grundlegenden Ebenen, die den Kern dieses Kapitels ausmachen: a) die Ebene der _relationalen Ereignissen_, die von einfachen Kontakten bis hin zu Handlungen, Interaktionen und anderen Verhältnissen reichen; b) die Ebene der Zirkulation, zu der die Entwicklung von relationalen Ereignissen führt; c) die Ebene der Relationsstrukturen, die diese Zirkulation organisieren. Eine Theorie der Relation soll entsprechend nicht nur die Vielfalt besonderer Verhältnisse erfassen. Sie muss sie nach ihren Organisationsprinzipien erklären, die die Relationsstrukturen darstellen und wie Ordnungsprinzipien von Zirkulationen und daher von relationalen Ereignissen verstanden werden.

Die zweite Bedingung betrifft die Relationsstrukturen selbst, davon die Theorie der Relation spricht. Diese Relationsstrukturen stellen keine homogenen oder stabilen Mengen von Zirkulationen und relationalen Ereignissen dar, sondern es sind dynamische Strukturen, die verändert werden, wenn Verhältnisse und Zirkulationen entwickelt werden. Solche Veränderungen der Dynamik von Relationsstrukturen passieren ständig wenn auch mit variabler Intensität, weil sowohl innerhalb als auch in anderen Relationsstrukturen Verhältnisse und Zirkulationen ständig entwickelt werden, die die Stabilität von einer Relationsstruktur beeinflussen. Deshalb entstehen innerhalb von Relationsstrukturen alternative Ordnungsprinzipien bzw. alternative Organisationen von Zirkulationsmöglichkeiten für menschliche und nicht-menschliche Akteure in Relationsstrukturen, die sich von der Hauptorganisation einer Relationsstruktur unterscheiden und sich in einer Relationsstruktur mit mehr oder weniger Erfolg duchsetzen. Eine Theorie der Relation sollte deshalb solche Veränderungen von Relationsstrukturen sowie ihre Folgen auf die Entwicklung von Verhältnissen und entsprechend auf die Zirkulation von Akteuren innerhalb oder zwischen Relationsstrukturen erklären können.

Unmittelbar folgt aus dieser zweiten Bedingung, dass jede Relationsstruktur als spezifisches Ordnungsprinzip bzw. als spezifische Organisation von Zirkulationen aufgrund der Entwicklung von Verhältnissen einerseits durch ihre eigene Dynamik subvertiert wird oder, wie wir es sagen, durch die eigene Zirkulation, die sie als diese Relationsstruktur charakterisiert. Andererseits wird jede Relationsstruktur ebenfalls von der Zirkulation der anderen Relationsstruktur in ihrer eigenen Dynamik beeinflusst, weil alle Relationsstruktur im Grunde auf der selben Eigenschaft beruhen, die sie unterschiedlich aufgreifen: Die Zirkulation von Akteuren als das Ergebnis der Entwicklung und der Arbeit an der Entwicklung von Verhältnissen. Deshalb sagt die Theorie der Relation zum einen, dass sie nach einem Primat der Zirkulation argumentiert. Deshalb versteht sie zum zweiten die Relationsstrukturen auf der Grundlage der selben Merkmale, die sie identisch Strukturieren, und die die Sequenzen von Zirkulationen sind, davon die vier für Zirkulationen strukturierende die Folgenden sind: Die Investition in die Arbeit an relationalen Ereignissen, die Repräsentation von dieser Investition, die Materialisierung von dieser Repräsentation und die Attraktivierung solcher Materialisierung zwecks Unterstützung von weiteren Investitionen in die Arbeit an relationalen Ereignissen.

Die Folge daraus ist, dass alle Relationsstrukturen strukturell identisch sind bzw. von den vier selben Sequenzen -- Investition, Repräsentation, Materialität und Attraktivität -- strukturiert sind, selbst wenn in jeder Relationsstruktur diese Sequenzen unterschiedlich je nachdem organisiert werden, welche bestimmte Sequenz den Fokus hat, die die Identität der Relationsstruktur ausmacht bzw. die die Reihung der anderen Sequenzen in eine für eine bestimmte Relationsstruktur typische Zirkulation festschreibt. Daher kommt es, dass die Theorie der Relation vier Relationsstrukturen danach erkennt, wie in einer Relationsstruktur eine bestimmte Sequenz das Prinzip der Zirkulation in dieser Relationsstruktur ausmacht bzw. die Sequenzen der Zirkulation in dieser Relationsstruktur anordnet. Oder anders gesagt: Jede Relationsstruktur ist durch eine bestimmte Sequenz in ihrer allgemeinen Zirkulation gekennzeichnet, die ihr Hauptmerkmal sowie ihre spezielle Dynamik ausmacht, und die in all ihrer drei anderen Sequenzen unterschiedlich aufgegriffen wird bzw. mehr oder weniger unterstützt wird. Je nachdem, wie sich das Hauptmerkmal bzw. das Primat der Zirkulation in einer Relationsstruktur durchsetzt, gewinnt diese Relationsstruktur an Bedeutung und an Macht über die anderen Relationsstrukturen, die sie dann auf der Ebene ihrer jeweiligen Zirkulation beeinflusst.

Diese Sequenzen bilden eine vierte Ebene in der Theorie der Relation, die die drei anderen Ebenen der relationalen Ereignisse, der Zirkulationen und der Relationsstrukturen vervollständigt. Oder anders gesagt: Diese Sequenzen sind die Stufen, danach die Dynamik jeder der vier Relationsstrukturen entwickelt wird bzw. danach das Primat der Zirkulation in jeder Relationsstruktur in konkrete Zirkulationswege von menschlichen und nicht-menschlichen Akteuren und in Zirkulationsmöglichkeiten für diese Akteure auf jeder sequentiellen Ebene von einer Relationsstrukturen verwirklicht wird. Dies ist das Grundgerüst der Theorie der Relation, zu der wir in diesem Kapitel vertiefend kommen werden, um die Botschaft, die diese Theorie beschäftigt, auszuformulieren, die besagt, dass das gesellschaftliche Leben von der Utopie der idealen Relation lebt, die diesem gesellschaftlichen Leben dimensioniert. Das ist gleichzeitig der Grund dafür, wieso die Theorie der Relation nach einem Primat der Zirkulation argumentiert. Damit kann verstanden werden, wie von der Ebene der Akteure und ihrer Verhältnisse zur Ebene der Zirkulationen in Sequenzen von Relationsstrukturen immer wieder die Suche nach einer perfekten Relation unternommen wird, die gleichsam eine einzigartige, singuläre, harmonische, allgegenwärtige, stabile, erfolgreiche, jenseits von Grenzen und Alterung, gewinnbringende oder noch glückliche Relation wäre. Das diese Utopie eine Utopie bleibt, attestieren die Relationsstrukturen in ihren unterschiedlichen Ebenen und ihrer speziellen Dynamik, selbst wenn sie als Relationsstrukturen bzw. Zirkulationsordnung die Verlockung einer solchen Utopie aufrechterhalten, die in Unterstützung der Zirkulationsdynamik in jeder Relationsstruktur kommt.

In dieser Einleitung wollen wir uns mit diesem theoretischen Apparat vertiefend beschäftigen. In einem ersten Schritt greifen wir auf die Aussage zurück, dass die Theorie der Relation mit dem Begriff der Zirkulation den dynamischen Charakter von Relationsstrukturen beschreibt. Ausgegangen von diesem Primat der Zirkulation beschäftigen wir uns eingehender mit den vier Relationsstrukturen und ihren vier Sequenzen, die die Zirkulationen von Akteuren innerhalb und zwischen Relationsstrukturen stratifizieren.

In einem zweiten Schritt kommen wir zum Begriff der doppelten Einschreibung der Akteure und gesellschaftlichen Instanzen in Relationsstrukturen. In diesem Zusammenhang führen wir die beiden Begriffe des Widerstands der Akteure und der Reziprozität ein. Wir erklären, warum diese drei Begriffe in der Theorie der Relation eng miteinander verbunden sind und wie sie zur Verteilung und Differenzierung von Akteuren und sozialen Instanzen in den Relationsstrukturen beitragen. Die Variationen der Verteilung und Differenzierung von Akteuren und sozialen Instanzen führt zur Verbreitung oder im Gegenteil zur Schrumpfung von Relationsstrukturen, die ihre Zirkulation, die die Einschreibung von weiteren Akteuren und Instanzen sowie ihre Widerstandskraft entsprechend stärken oder schwächen.

In einem dritten Schritt ziehen wir die Folgen aus unseren beiden ersten Schritten: Als eine sequentielle Ordnung von Zirkulationen beeinflusst jede Relationsstruktur die anderen immer nach demselben Muster. Dieses besteht darin, die Reziprozität, die eine Relationsstruktur repräsentiert und sie charakterisiert, allen anderen relationalen Strukturen aufzuzwingen, um diese idealen Relation zu werden, die jede Relationsstruktur anstrebt.

Relationale Ansätze in der Soziologie und in den Sozialwissenschaften existieren bereits, die sich wie etwa im Rahmen der relationalen Soziologien in den letzten zwei Jahrzehnte vermehrt systematischer entwickelt haben. Warum brauchen wir also einen weiteren Ansatz wie denjenigen der Theorie der Relation?

### Wieso eine Theorie der Relation?

Das Ziel und das entsprechende konzeptuelle Instrumentarium, das die Theorie der Relation verwendet, um seine Untersuchungen durchzuführen, gehen über den Rahmen der existierenden relationalen Ansätzen in den zeitgenössischen Soziologien und Sozialwissenschaften hinaus. In dem, was folgt, erklären wir, wie die Theorie der Relation Begriffe übernimmt, die im Rahmen von Theorien verwendet werden, die nach einem relationalen Ansatz argumentieren, und wie sie sie dekonstruiert und umformuliert. Diese Dekonstruktion und Reformulation rechtfertigt die Feststellung, dass es im Bereich der relationalen Soziologien und im Allgemeinen im Bereich der soziologischen Theorie an einem strukturierten Rahmen fehlt, der vollständig durch das Problem der Relation strukturiert ist und Relation nicht auf relationale Ereignisse reduziert, sondern Relation vielmehr als Makrobegriff versteht [@Trezzini1999, 515; @Scott1991, 38; @Granovetter1979, 501, 517; vgl. auch @Schultze2022, 4]. Relation als Makrobegriff zu verstehen -- dies geht jedoch nicht ohne Schwierigkeiten, die die Soziologen hervorheben, wenn sie allgemeiner über Prozessbegriffe und ähnliche Begriffe sprechen, wie etwa neulich Wolfgang Knöbl in seinem Buch _Die Soziologie vor der Geschichte. Zur Kritik der Sozialtheorie_ [@Knoebl2022]. Darin sagt Knöbl, dass die Sozialwissenschaften und darunter besonders die Soziologie und die soziologische Theorie Defizite bei der Verwendung von Prozessbegriffen und von Begriffen zeigen, die auf eine solche Prozesshaftigkeit verweisen. Dabei geht es Knöbl "in der Hauptsache um die Frage, warum die modernen Sozialwissenschaften und hier insbesondere die Soziologie zwar einerseits von Anfang an robuste Prozessbegriffe benutzten, um ihre jeweilige Gegenwart zu erklären [...], aber andererseits genau diese Begriffe und die mit ihnen verbundenen Aussagen und Thesen periodisch immer wieder kritisierten, weil man sich offensichtlich dann doch nicht so ganz sicher war und ist, wie gut sich damit Vergangenheit und Gegenwart fassen lassen" [ebd., 12-13, vgl. auch @Hoebel2020].

Besonders in seinem siebten Kapitel zu Sozialwissenschaften und Geschichtsphilosophie macht Knöbl deutlich, dass Prozessbegriffe Erzählungsmuster voraussetzen, die Sozialwissenschaftler nicht immer berücksichtigen, wenn sie solche Begriffe verwenden. Dies führt häufig dazu, dass man der Komplexität der (nach Knöbl historischen) Realität, die anhand von solchen Begriffen beschrieben werden soll, nicht gerecht wird. Ist man sich sicher, dass die Beschreibung von breiten gesellschaftlichen Zusammenhängen in Zeit und Raum genau das erfassen kann, was sie zu beschreiben behauptet? Gibt es dabei nicht eine Tendenz in den Sozialwissenschaften, "sich allzu leichtgläubig auf die Erklärungskraft oder auch nur die Prägnanz und Trennschärfe dieser Begriffe" zu verlassen [@Knoebl2022, 271]? Der Punkt, den Knöbl mit seiner These hervorzuheben sucht, ist weniger derjenige der Unbestimmtheit von Begriffen, worüber sich der Sozialwissenschaftler nicht bewußt wäre (ebd., 280). Sein Punkt betrifft vielmehr die Einbettung von Begriffen in sozio-politische Kontexte (ebd., 257, 269), von denen ihre Bedeutung maßgeblich abhängt, weshalb sie nicht ohne Weiteres zu Prozessbegriffen umgewandelt werden können.

Wenn wir uns eingedenk dieser Ausführungen Knöbls etwa den Begriff der Demokratie und seine prozesshaftige Erweiterung auf "Demokratisierung" ansehen, dann merken wir, wie Knöbl hervorhebt, dass eine solche Erweiterung viele Fragen mit sich bringt. Diese Fragen reichen von dem Verhältnis zwischen Wirtschaft und Politik, zwischen Bevölkerung und Staat, zwischen Gleichheit und Ungleichheit usw., die in den Sozialwissenschaften anhand von "Erzählungen" kontrovers diskutiert werden, ohne dass ein Schlußwort gesagt werden kann bzw. ohne dass die Sozialwissenschaften zu einem zufriedenstellenden und zu allen Zeiten allgemein gültigen Ergebnis kommen (vgl. Knöbls Diskussion von Charles Tillys Analyse der Demokratie und der Demokratisierung, ebd., 285-288). Diese Kritik von Knöbl an den Sozialwissenschaften betrifft ebenfalls die relationalen Soziologien insofern, als sie mit einem -- häufig dekonstruierten -- Prozessansatz argumentieren, der für diese Soziologien im Vordergrund der Untersuchung steht. Dieser Ansatz bildet nicht nur die Ausgangslage aller relationalen Soziologien -- Hauptgegenstand der "relationalen" Sichtweise sind "Prozesse" einerseits und "dynamische, sich entfaltende Beziehungen" andererseits [@Selg2020, 15; vgl. auch in den unterschiedlichen Perspektivierungen @Elias1977, 131; @Crossley2020a; @Emirbayer1997, 1998; Dépelteau2008, 2013b; @Papilloud2017; @Donati1995, 2013; @Bottero2011]. Er markiert gleichzeitig auch den Punkt, ab dem sich die relationalen Soziologien voneinander unterscheiden [vgl. @Prandini2015; vgl. auch @Selg2020, 30-35]. In Anlehnung an den Vorschlag Knöbls, wonach es nicht darum gehe, die genannten Prozessbegriffe oder gar Prozessbegriffe allgemein zu verdammen, wohl aber darum, für eine reflektiertere Anwendung dieser Begriffe zu werben [@Knoebl2022, 296], soll es im Folgenden darum gehen, über diese Ausgangslage im speziellen Fall der Theorie der Relation zu reflektieren.

### Ausgangslage der Theorie der Relation

Die Theorie der Relation geht nicht von der Annahme aus, dass sie unmittelbar mit sozialen Beziehungen, sozialen Verhältnissen, Interaktionen und mit weiteren solcher relationalen Ereignissen zu tun hat [@Papilloud2017]. Wie wir unter Rekurs auf Knöbl in unserer Einleitung erwähnt haben, sind solche Begriffe sowohl historisch als auch disziplinär im Bereich der Soziologie keineswegs neutrale Begriffe, sondern sie sind mit bestimmten soziologischen Paradigmata und deren Prämissen ebenso verknüpft, wie mit bestimmten Theorietraditionen [am Beispiel des Terminus _relationale Soziologie_ bzw. _Relation_ vgl. @Prandini2015]. Aus früheren Arbeiten haben wir gelernt, dass Prozessbegriffe nicht unbedingt in jeder Soziologietradition im Vordergrund des Erkenntnisinteresses stehen [vgl. etwa @monoPapilloud2002; @monoPapilloud2012a; @monoPapilloudRol2019]. In der französischen Theorietradition stellen sie bspw. kein Kernelement dar, während ihre Bedeutung für die soziologische Untersuchung in der amerikanischen Soziologietradition umgekehrt stark ausgeprägt ist. In der deutschen Soziologietradition wird teilweise mit prozesshaften Begriffen argumentiert; so etwa in den Schriften Georg Simmels entlang der Begriffe Wechselwirkung, Vergesellschaftung und Tausch [@monoPapilloud2002], im Werk Max Webers zu den Formen der Rationalisierung in den abendländlichen Gesellschaften [@nprPapilloud2002b], in der Ontologie der Beziehungslehre Leopold von Wieses [@hgbuchPapilloud2006a], am Beispiel des Begriffes der Kommunikation und seiner inhaltlich unterschiedlichen Fassung und Verwendung im deutschen Pragmatismus, in Jürgen Habermas' Theorie der Moderne oder in der Systemtheorie Niklas Luhmanns [@kapitelPapilloud2005; @kapitelPapilloud2005b]. Jedoch unterstützen solche Begriffe meistens eine Theorie, die häufig als Heuristik zur Untersuchung eines anderen, bedeutenderen Gegenstandes wie etwa die Moderne, der Wandel von Soziabilitätsformen in der Geschichte der Gesellschaften, die gesellschaftliche Homöostasie, die Werte, die Komplexität, verstanden wird. Anders gesagt, bleiben solche prozesshaften Begriffe Mittel zum Zweck und sind nicht (Selbst)Zweck der soziologischen Untersuchung.

Ähnlich wie in diesem letzten Fall, sieht man in den relationalen Soziologien eine Verwendung nicht primär eines einzigen Prozessbegriffes, sondern eher von prozessartigen Begriffen [@Selg2020, 30-35], die gezielt mit _Relation_ gleichgesetzt werden, um Gesellschaft _als_ Relation zu verstehen. Entsprechend wird die Quelle des Gesellschaftlichen typischerweise in der Zwischenmenschlichkeit _als Relation_ situiert und soll eine entsprechende soziologische Untersuchung von Gesellschaften _als Relation_ fördern. Ab diesem Punkt der Umformulierung oder Umformung von prozessartigen Begriffen in den der Relation unterscheidet sich die Theorie der Relation von anderen relationalen Soziologien. Dass Prozesse und zwar im schwachen und nicht homogenen Sinn von relationalen Phänomenen zwischen den Menschen liegen, ist eine Annahme, die die Theorie der Relation nicht braucht, weil sie nicht vom Standpunkt eines Anthropozentrizmus argumentiert, der voraussetzt, dass relationale Phänomene spezifisch oder nur menschlich wären [@LatourStrum1986; @Pyyhtinen2010; @Kaufmann2011; @Abbott2016]. Deshalb verwendet sie den Begriff der Relation als Makrobegriff zur Kategorisierung von relationalen Phänomenen in ihrer Diversität. Dies verschafft ihr den Vorteil, gesellschaftliche Phänomene nicht auf Relation zu reduzieren bzw. sie _als Relation_ zu beschreiben, sondern sie, auch in Anlehnung an die soziologische Tradition, mittelbar und somit _durch Relation_ zu erklären. Diese Ausgangslage der Theorie der Relation macht entsprechend aus der Relation nicht die Antwort auf eine Vielzahl von Fragen, sondern die Frage selbst oder -- im Sinne der praktischen soziologischen Untersuchung -- das Problem, das eine solche Theorie zu beantworten versucht bzw. mit dem sie sich auseinandersetzt. Dieses Problem sieht die Theorie der Relation als die Grundfrage des gesellschaftlichen Lebens an, mit dem sich jede Gesellschaft, jede informelle oder formelle Gruppe und jeder Akteur dieser Gesellschaften stets auseinanderzusetzen hat, selbst wenn eine solche Auseinandersetzung sehr unterschiedlich erfolgt, wie wir im Folgenden sehen werden.

Die Entwicklung eines Makroverständnisses von Relation und damit auch eines makrosoziologischen Denkens über Relation ruht -- etwa im Unterschied zu Pierre Bourdieu, der in seinem makro-relationalen Theorieansatz hauptsächlich Relationen _zwischen Positionen_ im Blick hat [vgl. @Bourdieu1987; @Bourdieu2019] -- auf der Einsicht, dass die Erklärung des Sozialen _durch Relation_ die Berücksichtigung der Position von Akteuren und der Relation (von Akteuren) gleichermaßen zulässt, insofern die Sozialität nach dem Primat der Zirkulation entwickelt und gedacht wird. Wie die Theorie der Relation nach einem Primat der Zirkulation argumentiert, wollen wir im Folgenden erklären. Dazu führen wir den Begriff der Relationsstruktur ein, den wir dann in mehreren Schritten vertiefen.

### Primat der Zirkulation und Relationsstrukturen

Das Primat der Zirkulation bedeutet, dass Akteure und Aktanten innerhalb und zwischen Relationsstrukturen zirkulieren. Diese Zirkulation entsteht als die allgemeine Dynamik zwischen Position und Relation, die diese Relationsstrukturen generiert. Dies Zirkulation ist daher keine Phänomen _sui generis_, d. h. sie entsteht nicht automatisch, sondern sie setzt die Arbeit von Akteuren an relationalen Ereignissen voraus. Die Zirkulation verläuft auch nicht zirkulär, sondern sie variiert von einer Relationsstruktur zu einer anderen Relationsstruktur und innerhalb von Relationsstrukturen. Diese Variationen ergeben sich daraus, dass die Zirkulationswege von Akteuren sowie von Aktanten und von symbolischen und formalen Medien sehr unterschiedlich ausfallen: unterschiedlich kurz oder lang, schnell oder langsam, stabil oder brüchig. Dies macht die unendliche Komplexität der Zirkulation von Akteuren einerseits und von Aktanten und Medien andererseits aus, die die Theorie der Relation anhand der Prinzipien solcher Zirkulationen bestimmt, wobei diese Prinzipien nichts anders als die Relationsstrukturen sind. Woraus aber entsteht eine solche Komplexität von Zirkulationen?

Sie entsteht zum einen daraus, dass Zirkulationen relationale Ereignisse voraussetzen, die deshalb Ereignisse sind, weil sie nicht und niemals vollends entwickelt werden. Folglich haben relationale Ereignisse keinen bestimmbaren Ursprung, kein vorhersehbares Ende, und sie zeigen unerwartete Mutationen. Hier unterscheidet sich die Theorie der Relation von Knöbls Sicht auf Prozesse. Knöbl versteht Prozesse ähnlich wie Bruno Latour als Arrangement von miteinander verketteten Ereignissen, die er ausnahmslos an einen klaren "Anfangs- und Endpunkt" gebunden wissen möchte [@Knoebl2022, 258; vgl. auch @Latour2005]. Im Fall von Knöbl impliziert eine solche Auffassung von Prozessen nicht nur, dass Ereignisse prinzipiell über _einen_ klar zu bestimmenden Anfangs- und Endpunkt verfügen, sondern auch ihre (anfängliche) Form und Qualität durch die Zeit hindurch beibehalten und entsprechend in sich "(ab)geschlossen" wären [@Knoebl2022, 261]. Dagegen erfasst die Theorie der Relation Ereignisse in ihrer sozialen Eingebundeheit, in ihren mannigfachen Entwicklungs- und Anschlussmöglichkeiten, in ihrer stets präsenten Potentialität des Liegenlassens, der Wiederaufnahme und der (wiederholten) Einflussnahme, wodurch sowohl der heterogenen Struktur als auch der Unbestimmtheit von Ereignissen Rechnung getragen wird [vgl. @Seyfert2019].

Zum anderen entsteht die Komplexität von Zirkulationen auch daraus, dass relationale Ereignisse in Form von Interaktionen, sozialen Verhältnissen, Beziehungen, sozialen Handlungen usw. _per definitionem_ stets im Fluss sind und dementsprechend sowohl von einer gelungenen, idealen Relation mit einem Anfang, einem Ende, mit erkennbaren, klar situierten Akteuren, die sie miteinander verbinden würden, als auch von einer homogenen Entwicklung abweichen. Deshalb begreift die Theorie der Relation Relationsstrukturen als abweichende Zusammenstellungen von relationalen Ereignissen mit Akteuren, Aktanten, Instanzen, Symbolen, Zeichen und Medien, die von einer idealen Relation abweichen. Um die Lesart nicht allzu sehr mit solchen Ketten von Begriffen zu überladen, sprechen wir im Folgenden verkürzt von Akteuren und Aktanten. Da es uns im Rahmen dieses Beitrages primär um die Beschreibung der Grundlage der Theorie der Relation geht, sprechen wir hier zudem nicht von den Medien, die die Theorie der Relation im Sinne von Mediationen versteht. Im Rahmen der Theorie der Relation sind die Medien sowohl mit der Behandlung von symbolischen Akteursoperationen als auch mit formalen Verfahren von Instanzen der Vermittlung von für Relationstrukturen spezifischen Zirkulationen verbunden. Sie erlauben, die Verbreitung/Schrumpfung von Relationsstrukturen und die Entwicklung alternativer Zirkulationswege in diesen Relationsstrukturen besser zu verstehen [mehr dazu, vgl. @PapilloudSchultze2022, 313-370]. Aber kehren wir zur Grundlage der Theorie der Relation zurück.

Das abweichende Merkmal von Relationstrukturen beruht nicht allein auf der Zusammenstellung von relationalen Ereignissen mit Akteuren und Aktanten, sondern ergibt sich auch aus ihrer Dynamik. Relationsstrukturen werden entwickelt oder nicht entwickelt. Wenn eine solche Entwicklung eine Arbeit an relationalen Ereignissen voraussetzt, findet eine solche Arbeit jedoch nicht zwangsläufig statt, eben weil Relationsstrukturen nicht an sich und unvermeidlich entwickelt werden. Sie können verbreitet werden, aber sie können ebenso sehr schrumpfen, weil Akteure und Aktanten nicht ständig an relationalen Ereignissen arbeiten oder weil sie nicht stetig zu einer solchen Arbeit beitragen. Der Grund dafür besteht in der Diversität von relationalen Ereignissen, von Akteuren und Aktanten, die bei einer solchen Arbeit mobilisiert werden können. An dieser Stelle begegnet uns ein weiteres wichtiges Merkmal der Theorie der Relation, das wie folgt hervorgehoben werden kann: Weil relationale Ereignisse divers sind, können sie sowohl von allen möglichen Akteuren beansprucht werden als auch alle möglichen Aktanten einbeziehen. Weil diese Akteure und Aktanten wiederum ebenfalls divers sind, können sie alle möglichen relationalen Ereignisse beanspruchen bzw. in alle möglichen relationalen Ereignisse einbezogen werden. Diese grundsätzliche Offenheit von relationalen Ereignissen auf Akteure und Aktanten und umgekehrt gewährleistet, dass die Arbeit an relationalen Ereignissen von relativer Bedeutung für eine Relationsstruktur bleibt. Gleichzeitig bildet diese Offenheit den Hauptgrund dafür, weshalb eine solche Arbeit stets und ständig passiert, weil sie, wenn sie nicht hier und jetzt von diesen oder jenen Akteuren mit diesen oder jenen Aktanten aufgenommen wird, früher oder später von anderen Akteuren mit anderen Aktanten anderswo stattfindet. Dies begründet einerseits die heterogene Form der Arbeit an relationalen Ereignissen, während dies andererseits zugleich die bedeutende Rolle dieser Arbeit für die Entstehung von Relationsstrukturen und die damit verbundenen Stufen dieser Arbeit hervorhebt. Dazu kommen wir im Folgenden.

### Arbeit an relationalen Ereignissen

Die Arbeit an relationalen Ereignissen unterstützt die Entwicklung von Relationsstrukturen, was konkret bedeutet, dass sie Zirkulationswege und Zirkulationsmöglichkeiten für Akteure fördert. Wegen der grundsätzlichen Offenheit von relationalen Ereignissen auf Akteure und Aktanten und _visa versa_, ist es unwahrscheinlich, dass nur ein Akteur mit nur einem Aktanten an nur einem relationalen Ereignis arbeitet, dessen Exklusivität er beanspruchen würde. Wahrscheinlich ist eher die Versammlung von unterschiedlichen Akteuren und Aktanten um unterschiedliche relationale Ereignisse bzw. eine heterogene Zusammenstellung von Akteuren, Aktanten und relationalen Ereignissen. Dabei kann nicht ausgeschlossen werden, dass eine solche Versammlung Form annimmt, weil Akteure, Aktanten und relationale Ereignisse nie neu entstehen, sondern Geschichtsprodukte sind, deren Geschichte sie versammeln [vgl. empirisch dazu im Bereich der relationalen Soziologien etwa @Bidart2011]. Sie wird nur dann weiter entwickelt, wenn die Arbeit an relationalen Ereignissen weiter erfolgt. Wenn dies nicht passiert, dann gibt es keine Entwicklung von Relationsstrukturen und keine Unterstützung für die Zirkulation der Akteure. Diese Zirkulation erfolgt dann so, als ob Akteure Aktanten wären, selbst wenn im Fall von Akteuren solche Zirkulationen Spuren im Sinne der beschleunigten Alterung von Akteuren in eigenen Zirkulationswegen hinterlassen, bis jede Form von Zirkulationsmöglichkeit erschöpft ist. Findet diese Arbeit jedoch statt, dann kann sie zur Mobilisierung von (anwesenden wie abwesenden) Akteuren und Aktanten und zur Verkettung von relationalen Ereignissen in Unterstützung der Entstehung und Verbreitung von Relationsstrukturen führen [zur Bedeutung vom Kontaktbegriff als Begriff zur Beschreibung dieses Raumes zwischen Position und Relation, vgl. @Papilloud2017].

Wie Mark Granovetter am Beispiel von "weak ties" angemerkt hat, haben selbst schwach strukturierte Verhältnisse den Vorteil, dass Akteure von relationalen Ereignissen "getragen" oder "agiert" werden. Dabei erreichen sie Ziele, ohne sich aktiv der Arbeit an relationalen Ereignissen zu widmen [@Granovetter1973, 2005]. Diese Kraftersparnis, die jede Art von relationalem Ereignis mit sich bringt, wie schon Georg Simmel unterstrichen hatte [vgl. @Simmel1890, 280], muss jedoch perspektiviert werden. Eine mehr oder weniger gut strukturierte Relationsstruktur ist immer möglich, weil nicht ausgeschlossen werden kann, dass eine soziale Arbeit stattfindet. Deshalb existieren "weak ties", weil sich einerseits jeder Akteur der Arbeit an sozialen Ereignissen -- weitere Akteure und Aktanten mobilisieren, relationale Ereignisse verketten und Zirkulationswege bahnen, woraus sich wiederum Zirkulationsmöglichkeiten ergeben -- nicht zwingend widmen muss. Dies bedeutet andererseits aber nicht, wie oben erwähnt, dass eine solche Arbeit nicht irgendwann, irgendwo und irgendwie stattgefunden hat oder bereits von irgendwem geleistet worden ist. An dieser Stelle unterscheidet sich die Theorie der Relation von anderen relationalen Ansätzen dadurch, dass sie nicht etwa davon ausgeht, dass relationale Ereignisse deshalb immer existieren, weil sie immer vorhanden bzw. transzendental wären, sondern weil sie nicht ausschließt, dass sie von Akteuren und Aktanten hier wie dort, gestern wie heute mobilisiert und verkettet worden sind. Dieser Kontrast zu einer ontologischen Perspektive, die die Relation substanziert, zur einer soziologischen Perspektive, die die Relation als ein kollektives Gut versteht, stellt jedoch eine Frage: Wie ist diese Unterscheidung zwischen Relationsstrukturen und Nicht-Relationsstrukturen einheitlich zu denken? Diese Frage findet ihre Antwort im Primat der Zirkulation.

Anders als die Theorien, die das Argument der Schließung in Unterstützung der oft substantialisierten, in der Theorie allein bzw. _in abstracto_ verankerten Trennschärfe von Unterschieden verwenden -- was nicht links ist, ist rechts, was nicht oben ist, ist unten, was nicht drinnen ist, ist draußen usw. [vgl. paradigmatisch dazu @Bourdieu1987] --, priorisiert die Theorie der Relation aufgrund der Frage der Arbeit an relationalen Ereignissen keine scharfen Unterscheidungen zwischen dem, was Relationsstrukturen sind, und dem, was sie nicht sind. Weil sie konsequent mit ihrem Primat der Zirkulation umgeht, gründet sie diese Unterscheidungen auf der Unterscheidung zwischen Zirkulationswegen innerhalb von Relationsstrukturen einerseits und zwischen Relationsstrukturen andererseits. Diese Unterscheidungen entsteht wiederum selbst aus der Unterscheidung zwischen Abweichungen von einer _idealen_ Relation und Abweichungen von Abweichungen bzw. von anderen Relationsstrukturen. Dabei zieht die Theorie der Relation die Konsequenzen ihres Grundsatzes, wonach es keine perfekte, ideale Relation gibt bzw. wonach Relationsstrukturen von einer idealen Relation abweichen, wie Zirkulationen stets von einer idealen Zirkulation abweichen. Die Theorie der Relation bringt also dieses Argument auf den Punkt und sagt, dass Relationsstrukturen ebenfalls von anderen Relationsstrukturen abweichen.

In Bezug auf das Primat der Zirkulation bedeutet dies, dass sich Zirkulationswege innerhalb von Relationsstrukturen prinzipiell von Zirkulationswegen zwischen Relationsstrukturen bzw. von abweichenden Zirkulationswegen von einer bestimmten Relationsstruktur unterscheiden. Wenn wir diese Folge auf der Ebene von Relationsstrukturen zu Ende denken, dann können Abweichungen von Relationsstrukturen konstruktiv für die Theorie als Stratifikationsprinzip dieser Relationsstrukturen durch Zirkulationswege und Zirkulationsmöglichkeiten gedacht werden. Entsprechend können sie als Stratifikationsprinzip dieser Zirkulationen bzw. des Primats der Zirkulation selbst gedacht werden.

Ähnlich wie Standing in Bezug auf die zahlreichen Deklinationen von unterschiedlichen mehr oder weniger "strong" oder "weak ties" anmerkt [@Standing2007], sagt die Theorie der Relation, dass es zahlreiche Deklinationen vom Primat der Zirkulation in der Form von diversen Zirkulationen innerhalb und zwischen Relationsstrukturen. Um zu zeigen, wie diese Stratifikation von Zirkulationen und Relatiosstrukturen konkreter abgebildet werden kann, kommen wir zum Begriff der Sequenzen.

### Abweichende Realtionsstrukturen und Sequenzen

Abweichungen entstehen nicht alle auf einmal, sondern sie entstehen sequential. Eine Abweichung führt zu weiteren Abweichungen. Die erste Abweichung von einer idealen Relation entsteht aus der Idealisierung der Relation selbst, die die Dynamik einer ersten Relationsstruktur gestaltet bzw. die Grundmotivation der Investition in die Arbeit an relationalen Ereignissen darstellt. Von einer solchen Idealisierung weicht eine zweite Relationsstruktur ab, in der die Akteure ihre Repräsentation durch Kollektive hervorheben, ohne die keine Arbeit an relationalen Ereignissen möglich wäre. Von dieser zweiten Relationstruktur weicht eine dritte Relationsstruktur ab, in der die Materialität bzw. die Verwirklichung von Akteuren hervorgehoben wird, ohne die die Kollektive nicht existieren würden und eine Investition in die Arbeit an relationalen Ereignissen nicht denkbar wäre. Eine vierte Relationsstruktur weicht von dieser letzten Relationsstruktur ab, in der die Attraktivität von Medien bzw. von Mediationen hervorgehoben wird, die deshalb attraktiv sind, weil sich die Akteure ohne sie nicht verwirklichen könnten, keine Kollektive hervorbringen würden und daher die Arbeit an relationalen Ereignissen nicht bewältigen könnten. Oder anders gesagt: Was vorherrscht, wenn es darum geht, die Arbeit an relationalen Ereignissen vorzunehmen, kann die Relation selbst sein, die Kollektiven, die sie voraussetzt, die individuellen Akteure, die diese Kollektiven bilden oder die Mediationen, die bei der Arbeit an relationalen Ereignissen verwendet werden. Die Gründe und die Dynamik, die diese Abweichungen bestimmen, können ebenfalls in Bezug auf die Unterscheidung zwischen Position und Relation dargestellt werden.

Die Unterscheidung zwischen Position und Relation kann als Unterscheidung zwischen akteurzentrierten und austauschzentrierten Relationsstrukturen aufgegriffen werden. Diese Unterscheidung bildet die erste Deklination des relationalen Hauptmerkmals von Relationsstrukturen und mündet gleichsam in den ersten zwei Abweichungen von einer _idealen_ Relation. Daraus ergeben sich die zwei Hauptmerkmale von zwei ersten Relationsstrukturen, die einer relations- und einer positionsorientierten Differenzierung bezüglich der Arbeit an relationalen Ereignissen entsprechen und daraufhin entwickelt werden. Aus dieser ersten Unterscheidung in eine austausch- und eine akteurzentrierte Relationsstruktur resultieren ferner zwei weitere Abweichungen. Sie verstehen sich als Abweichungen von einer ausschließlich austausch- und einer ausschließlich akteurzentrierten Relationsstruktur. Diese Abweichungen haben wir als "Abweichungen zweiter Ordnung von abweichenden Relationsstrukturen erster Ordnung" dargestellt [@PapilloudSchultze2022, 24]. Sie bringen zwei weitere Deklinationen des relationalen Hauptmerkmals für zwei weitere Relationsstrukturen hervor: Zum einen eine Relationsstruktur, in der ihrem relationalen Hauptmerkmal entsprechend die Uneingeschränktheit der Austauschzentriertheit durch akteurzentrierte Merkmale relativiert wird; zum anderen eine Relationsstruktur, in der wiederum die Uneingeschränktheit der Akteurzentriertheit durch austauschzentrierte Merkmale gedämpft wird.

Sei es in Bezug auf die Arbeit an relationalen Ereignissen oder in Bezug auf die Unterscheidung zwischen Position und Relation, merken wir, dass Relationsstrukturen sequentiell etabliert werden. Dies kommt daher, dass sie Abweichungen sind, die weitere Abweichungen produzieren, bis diese Abweichungen erschöpft sind. An welcher Stelle eine Relationsstruktur von einer anderen Realtionsstruktur abweicht, haben wir oben mit der Erwähnung des Hauptmerkmals der jeweiligen Relationsstrukturen signalisiert. Dieses Hauptmerkmal ist der Punkt, der einer Relationsstruktur ihr Unterscheidungsmerkmal im Vergleich zu den anderen Relationsstrukturen gibt. Gleichzeitig ist das Hauptmerkmal von Relationsstrukturen aber auch der Punkt, an dem sich die Relationsstrukturen einerseits voneinander unterscheiden und andererseits intern diversifizieren. Bei diesem letzten Argument der internen Diverzifierzierung von Relationsstrukturen handelt es sich um eine weitreichende Folge aus dem Primat der Zirkulation -- Zirkulationen zirkulieren und sie zirkulieren unterschiedlich -- und gleichzeitig aus der sequentiellen Entstehung von Relationsstrukturen als Abweichungen von einer idealen Relation. Das bedeutet wiederum, dass selbst innerhalb von Relationsstrukturen Abweichungen vom Hauptmerkmal dieser Relationsstrukturen entstehen, wie sie zwischen Relationsstrukturen entstehen können. Jede Relationsstruktur stellt in diesem Sinne eine Zirkulationsordnung mit den alternativen zu dieser Zirkulationsordnung dar, die, weil sie früher oder später von Akteuren aufgegriffen werden, die Zirkulationsordnung von einer Relationsstruktur und diese Relationsstruktur selbst destabilisieren. Alle Sequenzen in allen Relationsstrukturen sind deshalb gleichzeitig Produkte von solchen Abweichungen und Ausgangspunkte von solchen Abweichungen. Sie strukturieren und destrukturieren die Zirkulation innerhalb und zwischen Relationsstrukturen.

Aus diesem Grund könnte gesagt werden, dass wir in der Theorie der Relation immer mit derselben Relationsstruktur zu tun haben, selbst wenn wir vier Relationsstrukturen unterscheiden. Eine solche Anmerkung bezieht sich jedoch nur auf eine dezidiert strukturalistische Betrachtung von Relationsstrukturen, die ihre Zirkulationsdynamik nicht berücksichtigt. Verstehen wir dagegen Relationsstrukturen dynamisch, dann sehen wir, dass, obwohl diese Relationsstrukturen nach denselben Sequenzen differenziert werden, sich eine solche Differenzierung von Zirkulationen nicht ab dem selben Abweichungspunkt von einer Relationsstruktur entwickelt. Deshalb kann eine solche Differenzierung nicht dem selben Muster in allen Relationsstrukturen gleichermaßen folgen. Obgleich also die Sequenzen Investition, Repräsentation, Materialität und Attraktivität bei jeder Zirkulation in und zwischen Relationsstrukturen anwesend und tragend sind, werden sie nicht in der gleichen Prioritätsordnung mobilisiert. Vielmehr werden sie sequentiell ab dem Punkt mobilisiert, der in einer Relationsstruktur ihr Hauptmerkmal darstellt. Deshalb unterscheidet die Theorie der Relation ab dem Primat der Zirkulation vier Relationsstrukturen, die sich nicht strukturell sondern zirkulationsbedingt voneinander unterscheiden.

Die Relationsstruktur, die ab der Sequenz Investition abweicht, zeigt eine interne Anordnung von Sequenzen, die von der Investition in die Arbeit an relationalen Ereignissen, zur Repräsentation dieser Investition, zur Materialität dieser Repräsentation und zur Attraktivität der Materialität von der Investition in die Arbeit an relationalen Ereignissen verläuft. Davon weicht eine zweite Relationsstruktur ab der Sequenz der Repräsentation, die eine interne Anordnung von Sequenzen bedingt, deren Hauptmerkmal die Repräsentation der Arbeit an relationalen Ereignissen durch Repräsentanten ist, die zur Materialität dieser Repräsentation, ihrer Attraktivität und der Investition in die Repräsentation von einer solchen Arbeit geht. Die Relationsstruktur, die von dieser letzten Relationsstruktur ab der Sequenz der Materialität abweicht, weist eine Anordnung von Sequenzen auf, die von der Materialität der Arbeit an relationalen Ereignissen zu ihrer Attraktivität, der Investition in diese Materialität und zur Repräsentation dieser Investition verläuft. Schließlich weist die letzte Relationsstruktur ab dem Punkt der Attraktivität der Arbeit an relationalen Ereignissen eine Abweichung auf, die zu einer Anordnung von Sequenzen führt, die zur Investition in eine solche Attraktivität, zu ihrer Repräsentation und zur Materialisierung ihrer Repräsentation geht. Anders formuliert, könnte gesagt werden, dass jede der vier Relationsstrukturen einen Standpunkt zur Relation darstellt, wie sie wahrgenommen und in der Form von Zirkulationen praktisiert wird, davon es in jeder Relationsstruktur unvermeidlich abgewichen wird. Zur ersten Relationsstruktur zählt die Relation an sich. In der zweiten Relationsstruktur zählt die Repräsentation von Kollektiven, die in Unterstützung der Relation mobilisiert wurden. In der dritten Relationsstruktur zählen die konkreten Akteure, die diese Kollektiven bilden, damit eine Relation zustande kommt. In der letzten Relationsstrukturen zählen die Mediationen der Relation selbst, die Kollektive und Akteure unvermeidlich in Unterstützung der Relation beziehen. Diese Bezeichnung der vier Relationsstrukturen ist gleichzeitig eine Bezeichnung der vier Sequenzen, die in jeder Relationsstruktur gleichermaßen anwesend sind. Daraus ergibt sich eine vollständige Beschreibung von Relationsstrukturen in jeder ihrer Sequenzen, die ihre formalen und strukturellen Eigenschaften vom Primat der Zirkulation subvertiert sieht und sich entsprechend in einem dynamischen Theorierahmen zur Untersuchung von gesellschaftlichen Phänomenen _durch Relation_ niederschlägt.

Jenseits von Position und Relation und jenseits von einer möglichen Arbeit an relationalen Ereignissen gibt es schließlich das, was Relationsstrukturen nicht sind. Weil Relationsstrukturen aufgrund ihrer Zirkulation voneinander abweichen, gibt es keine unmittelbare Verbindung zwischen Relationsstrukturen. Es gibt Trennungen, die zwischen diesen Relationsstrukturen sowie zwischen Sequenzen von Relationsstrukturen innerhalb jeder Relationsstruktur auftauchen. Solche Trennungen bilden einen Orientierungsraum -- auch in Anlehnung an die Transaktionsräume, von denen François Dépelteau spricht [@Depelteau2013b] -- für Zirkulationen von einer Relationsstruktur zu einer anderen Relationsstruktur bzw. von einer Sequenz in einer Relationsstruktur zur nächsten Sequenz in dieser Relationsstruktur. Das sind zusätzliche Abweichungen von abweichenden Zirkulationen, die jedoch nicht _ad infinitum_ wiederholt werden können. Weitere Abweichungen von Relationsstrukturen, die zu weiteren bzw. mehr Relationsstrukturen oder Sequenzen führen würden, existieren nicht. Oder anders gesagt: Weitere Abweichungen von Relationsstrukturen ergeben sich stets als eine von diesen vier Relationsstrukturen für eine gegebene Relationsstruktur bzw. eine Sequenz für eine gegebene Sequenz von einer Relationsstruktur.

Bei Zirkulationen geht es ähnlich wie für Relationsstrukturen. Einzelakteure und Aktanten unterschiedlicher Natur (wie Zeichen, Symbolen, Medien, Dinge, Bakterien) zirkulieren, selbst wenn sie unterschiedlich zirkulieren. Hier zieht die Theorie der Relation die Lehre der relationalen Auffassungen zur _agency_  [vgl. @Somers1994; @Emirbayer1998; @White2008; @Mische2011], nach der die Identität von Akteuren nicht zufriedenstellend anhand von Kategorien (gender, Alter, Beruf, Wohnort, Haltung) erfasst werden kann, ohne die Akteure zu stigmatisieren. Deshalb konvergieren die Unterstützer der relationalen _agency_ zu einer Problematisierung von Akteuren als sequentielle Einbettungen von kulturellen, sozialen und persönlichen Dimensionen. Die Theorie der Relation dreht dieses Erklärungsmuster um. Statt von einer Einbettung dieser Dimensionen in Einzelakteure zu sprechen, wonach das Einzelmerkmal dieser Akteure als ihre spezifische Identität bzw. als _agency_ aufgefasst wird, spricht die Theorie der Relation von einer Einschreibung dieser Akteure in Zirkulationen, die ihre Identität singularisieren [@Thevenot1984; @Lahire2001]. Nicht die Einbettung von unterschiedlichen Dimensionen tragen zum Alleinstellungsmerkmal jedes Akteurs bei, sondern die Einschreibung dieser Akteure in unterschiedliche Zirkulationen, Sequenzen und Relationsstrukturen tragen zum Alleinstellungsmerkmal ihrer Identität als Akteur bei. Diese Identität von Akteuren entsteht entsprechend als Besonderheiten ihrer Zirkulation bzw. wird entsprechend als solche hervorgehoben. Eine solche Umformulierung der relationalen _agency_ unterstützt das Primat der Zirkulation insofern, als sie voraussetzt, dass Akteure und Aktanten mehr oder weniger gut in Zirkulationen eingeschrieben werden bzw. sie als mehr oder weniger gelungene _agency_ durch Relation als Zirkulation verwirklicht werden. Deshalb führt eben diese Umformulierung dazu, den Begriff der _agency_ nach Zirkulation bzw. nach zirkulierenden und nicht zirkulierenden Akteuren wie folgt zu differenzieren. Einzelakteure und Aktanten zirkulieren, selbst wenn ihre Zirkulation unterschiedlich verläuft, wie wir es unten erklären werden. Kollektivakteure und die daraus entstandenen Vermittlungsinstanzen zirkulieren dagegen nicht. Sie altern in Sequenzen und Relationsstrukturen, in denen sie aus- und abgebaut werden. Wie für Relationsstrukturen und Sequenzen von Relationsstrukturen ruht diese Unterscheidung zwischen zirkulierenden und nicht-zirkulierenden Akteuren auf dem Begriff der Einschreibung. Weil dieser Begriff eng mit den Begriffen des Widerstandes und der Reziprozität im Rahmen der Theorie der Relation verbunden ist, werden wir uns im Folgenden mit diesen drei Begriffen beschäftigen.

### Einschreibung

Die Begriffe der Einschreibung, des Widerstandes und der Reziprozität beschreiben das, was Zirkulationen konkret brauchen, um zu zirkulieren bzw. um Sequenzen von Relationsstrukturen und diese Relationsstrukturen zu strukturieren, woraus sich unterschiedliche Zirkulationen, entsprechende Tätigkeiten und Tätigkeitsbereiche sowie (Kollektiv)Akteure und Aktanten ergeben. Weil Relationsstrukturen formal und strukturell auf den selben Grundprinzipien ruhen, sind sie grundsätzlich auf alle sozialen Tätigkeiten und Tätigkeitsbereiche offen, weshalb wir umgekehrt in jeder Relationsstruktur alle nur denkbaren Tätigkeiten und Tätigkeitsbereiche ausfindig machen können. Da wir jedoch Formen und Strukturen der Relationsstruktur durch das Primat der Zirkulation subvertieren bzw. auf der Grundlage von Zirkulationen umdenken, ist es wahrscheinlich, dass Tätigkeiten und Tätigkeitsbereiche nicht beliebig aufgebaut werden, sondern danach, wie sie die Zirkulationen bzw. die sequentielle Organisation von solchen Zirkulationen in der entsprechenden Relationsstruktur unterstützen. Eine solche Unterstützung ergibt sich aus der Einschreibung von Akteuren mit Aktanten und informellen oder formellen Kollektivakteuren wie Institutionen und Organisationen in solchen Zirkulationen von Relationsstrukturen.

Der Begriff der Einschreibung kann deshalb als die komplementäre Seite der Unterscheidung von Relationsstrukturen und von Sequenzen in Relationsstrukturen verstanden werden. Einerseits verdeutlicht die Einschreibung die Position von Akteuren in Relationsstrukturen, während sie andererseits und gleichzeitig über ihre geleistete und über ihre noch zu leistende Zirkulation informiert. Die Einschreibung setzt dann sowohl eine Verankerung in Relationsstrukturen bzw. in Sequenzen von Relationsstrukturen (Positionsansatz) als auch eine Verteilung auf Relationsstrukturen bzw. auf weitere Sequenzen von Relationsstrukturen (Relationsansatz) voraus. Sie differenziert Zirkulationswege von Akteuren, die sie potenziert bzw. die sie auf weitere Zirkulationsmöglichkeiten eröffnet. Dies ist die allgemeine Bedeutung des Begriffes der Einschreibung, die wir jetzt vertiefend vom Standpunkt der Arbeit an relationalen Ereignissen betrachten.

Der Begriff der Einschreibung setzt voraus, dass eine soziale Arbeit an relationalen Ereignissen geleistet, aus- und durchgeführt wird. Dies bedeutet eine Involvierung von Akteuren mit anderen (Kollektiv)Akteuren und mit Aktanten in diese relationalen Ereignisse, wobei eine Involvierung allein nicht ausreicht, wenn sie nicht zugleich diese Akteure und Aktanten mobilisiert bzw. wenn sie nicht ihre, wenn auch schwache, Zusammenstellung leistet. Arbeiten, die kaum begeistern und von denen sich die Akteure früher oder später abwenden, gibt es genug, was belegt, dass Einschreibungsakte nicht ständig passieren. Arbeiten, die verwirklicht werden müssen oder die man gerne verwirklichen möchte, Beschäftigungen, die einem die innere Ruhe rauben, gibt es jedoch auch in Hülle und Fülle, die verdeutlichen, dass Einschreibungsakte ebenso ständig passieren. Eine solche Involvierung hinterlässt psychische und physische Spuren. Sie treibt die Akteure manchmal ein Leben lang an und um. Sie verändert sie im Laufe der Zeit, bis diese Einschreibung, so schlecht sie manchmal auch stattfinden mag, anerkannt wird und zur Legitimation der Akteure führt, die sich involviert haben, so bescheiden diese Legitimation manchmal auch ausfallen mag, wie etwa bei der Bestätigung von vorhandenen grundsätzlichen Rechten [@Thevenot2001; @Boltanski2007]. Mit dieser Grundbetrachtung der Einschreibung wird gleichzeitig gesagt, dass sie nicht für alle Akteure dieselbe Bedeutung hat.

Einzelakteure im Sinne von menschlichen Akteuren brauchen eine solche Einschreibung zur weiteren Unterstützung der Umstellung ihrer Position in Sequenzen und Relationsstrukturen bzw. für weitere Beschäftigungen mit relationalen Ereignissen. Kollektivakteure brauchen dagegen eine solche Einschreibung zur weiteren Konsolidierung ihrer Position. Wie Latour sagen würde, sind Kollektivakteure Gewährleistungen von _obligatory passage points_ für Akteure [@Latour2005], die die vorausgesetzte Arbeit von Akteuren verdeutlichen und (positiv oder negativ) sanktionieren. Aktanten brauchen dagegen an sich keine Einschreibungen, weil ihre Zirkulation nicht in bestimmten Sequenzen oder Relationsstrukturen, sondern überall in diesen Sequenzen und Relationsstrukturen entwickelt wird. Deshalb hängen Aktanten nicht von der Zirkulation von Akteuren oder von der Position von Vermittlungsinstanzen ab, um zu zirkulieren. Dies wiederum gewährleistet, dass sie in jeder Zirkulation von jedem Akteur und von jeder Art von Vermittlungsinstanz aufgegriffen und verwendet oder demgegenüber abgelehnt und verworfen werden können. Wenn also Aktanten entweder in Unterstützung oder als Förderung der Einschreibung von Akteuren und Vermittlungsinstanzen fungieren, tragen sie gleichzeitig auch zur Komplexität dieser Einschreibung und zu ihrer abweichenden Natur als eine Einschreibung bei, die nicht und niemals ideal erfolgen kann.

Eine Einschreibung ist also ein Akt der mehr oder weniger gut gelungenen Involvierung der Akteure bei ihrer Arbeit an relationalen Ereignissen mit Kollektivakteuren und Aktanten. Sie ist ein Relativierungsfaktor der Arbeit sowohl von Akteuren als auch von Vermittlungsinstanzen in diesem Sinne, dass die Einschreibung die Tätigkeiten von beiden Parteien in ein Verhältnis setzt bzw. sie in einer Relationstruktur bzw. in einer ihrer Sequenz verankert. Aufgrund der abweichenden Natur von Relationsstrukturen, der Vielfalt von Zirkulationsmöglichkeiten und von Instanzen der Vermittlung von solchen Zirkulationen auf den unterschiedlichen sequentiellen Ebenen von Relationsstrukturen erfolgen Einschreibungsakte nie einseitig -- etwa als ob sie nur von den zirkulierenden Akteuren allein getätigt werden könnten. Einschreibungsakte setzen immer die Einschreibung von anerkennenden und legitimierenden Kollektivakteuren in die relationalen Ereignisse voraus, an denen die Akteure mit Aktanten arbeiten bzw. an denen sie gearbeitet haben. Diese Kollektivakteure, die die Theorie der Relation als die Grundlage von Vermittlungsinstanzen versteht, sind also grundsätzlich Instanzen der Vermittlung von Zirkulationswegen und Zirkulationsmöglichkeiten für Akteure in Relationsstrukturen und in deren Sequenzen [zu einer ähnlichen Auffassung von Kollektiven, siehe @Grossetti2018; @Grossetti2022]. Sie verdeutlichen das Primat der Zirkulation, wie es in jeder Sequenz einer Relationsstruktur verstanden wird, in denen wiederum diese Vermittlungsinstanzen aufgebaut wurden.

Oder anders formuliert: Sie sozialisieren die Akteure auf ein Verständnis von Zirkulation, von Sequenzen, von Relationsstrukturen und fördern wie sanktionieren sie entsprechend. Deshalb spricht die Theorie der Relation von einer _doppelten Einschreibung_ der Akteure und der Vermittlungsinstanzen in der sozialen Arbeit an relationalen Ereignissen. Akteure schreiben sich mit Vermittlungsinstanzen in die Arbeit an relationalen Ereignissen zusammen, woraus nicht nur eine Anerkennung und eine Legitimität für die Akteure resultiert, sondern auch für die Vermittlungsinstanzen.

Aus der abweichenden Natur von Relationsstrukturen und Sequenzen von Relationsstrukturen und den entsprechend mehr oder weniger gut gelungenen Einschreibungsakten ergibt sich, dass die doppelte Einschreibung nicht ein für alle Mal stattfindet. Sie muss wiederholt mit weiteren Vermittlungsinstanzen von Sequenzen und Relationsstrukturen im Laufe der Zirkulationen von Akteuren entwickelt werden. Dort erfindet die Theorie der Relation das Rad nicht neu. Einerseits unterstützt sie den weit verbreiteten soziologischen Ansatz wie etwa in den Sozialisationstheorien, Rollentheorien und Konkflikttheorien, nach denen sich die Folgen von Zirkulationswegen als wiederholte lebenslange Einschreibungsakte von Akteuren mit gesellschaftlichen Vermittlungsinstanzen ergeben. Andererseits greift sie dieses Argument in Bezug auf das Primat der Zirkulation so auf, dass Einschreibungsakte zwar für die Zirkulationswege der Akteure bestimmend sind, sie ihre Bestimmungskraft jedoch unterschiedlich stark oder schwach je nachdem entwickeln, welche Akteure auf welche Vermittlungsinstanzen in welchem starken oder schwachen Zustand von einer Relationsstruktur angewiesen sind.

Etwa die Selektionsfunktion von gesellschaftlichen Bildungsinstanzen wie Schulen oder Hochschulen bleibt in der Zeit nicht unverändert. Sie variiert nicht nur in Bezug auf Schüler bzw. Studenten (Akteure) und auf ihre Ursprungsmilieus (Kollektivakteure), die sich mit solchen Vermittlungsinstanzen einschreiben. Sie variiert ebenso in Bezug auf die Anwesenheit oder Abwesenheit von konkurrierenden Bildungsinstanzen in anderen Sequenzen von einer Relationsstruktur wie in anderen Relationsstrukturen. Schließlich verändert sie sich auch in Bezug auf die gesellschaftliche Bedeutung von Bildung als symbolische Mediation in den Relationsstrukturen [dazu vgl. @Euriat1995; @Merle2002; @Albouy2003; @Lozach2020]. Diese Variationen der Bestimmungskraft von Einschreibungsakten schlagen sich in unterschiedlichen Zirkulationswegen und Zirkulationsmöglichkeiten für die Akteure nieder, die ihre Erwartungen und Erwartungen auf Erwartungen entlang der Entwicklung von solchen Zirkulationswegen und Zirkulationsmöglichkeiten bestimmen. Dies hat entsprechende Folgen für die Mobilität der Akteure innerhalb und zwischen Sequenzen von Relationsstrukturen sowie innerhalb und zwischen Relationsstrukturen. Es stratifiziert diese Sequenzen und Relationsstrukturen unterschiedlich und lässt sie entsprechend wachsen oder schrumpfen. Diese zwei letzten Punkte werden wir im Rahmen dieses Kapitels nicht weiter ausführen. Sie haben jedoch ein Element gemein, das wir im Rahmen dieser Diskussion zur doppelten Einschreibung näher betrachten möchten. Es handelt sich um den Widerstand der Akteure.

### Widerstand

Der Widerstand der Akteure ist eine Folge der Ausgangslage der Theorie der Relation. Seine Bedeutung kann etwa mit der folgenden Aussage zusammengefasst werden: Aufgrund der Arbeit an relationalen Ereignissen, der Mannigfaltigkeit dieser Ereignisse sowie der Vielfalt sowohl von Akteuren und Aktanten als auch von Vermittlungsinstanzen in Relationsstrukturen kann keine Position in den Relationsstrukturen und ihrer Sequenzen definitiv bezogen werden. Positionen werden früher oder später umgestellt. Deshalb ist etwa die Sozialisation von Akteuren keine Selbstverständlichkeit, sondern eine Zusammenarbeit von Akteuren mit Aktanten an dem Zirkulationsweg, der in einer bestimmten Situation gebahnt werden kann. Diese Zusammenarbeit gewährleistet, dass Akteure nicht auf Positionen reifiziert werden, die sie in ihrer Laufbahn beziehen können, und dass sie nicht mit relationalen Ereignissen gleichgesetzt und daher auf bloße Funktionen oder Träger von Relation reduziert werden. Das ist die Ausgangslage des Begriffes der Widerstand in der Theorie der Relation, zu dem wir jetzt kommen.

Dass Akteure weder auf Position noch auf Relation reduziert werden können bzw. dass sie Positionen und Relationsstrukturen bzw. Sequenzen von Relationsstrukturen und Zirkulationen wechseln können, ergibt sich aus dem Widerstand der Akteure _für_ und _gegen_ sowohl Positionen als auch Sequenzen, Relationsstrukturen und Zirkulationen. Wege, die die Akteure gebahnt haben, und Positionen, die die Akteure bezogen haben, führen nicht zur vollkommenen Zufriedenheit oder zur vollkommenen Enttäuschung der Akteure, sondern zum Erleben und zum Erfahren des abweichenden Merkmals der Relationsstrukturen als Bedingung ihrer Zirkulationen. Der Widerstand spiegelt diese Verkörperung der Umstellung als konstitutive Dualität jedes menschlichen Akteurs als Akteur wider, der durch Relation Positionen in Zirkulationen bezieht und Positionen durch Zirkulation in Relation wechselt. Diese Auffassung des Widerstandes von Akteuren vertiefen wir im Folgenden.

Der Widerstand ist immer ein Widerstand _für_ Zirkulationsmöglichkeiten, die das Alleinstellungsmerkmal jeder Individualität als veränderbares distinktives Glied zwischen Position und Relation ausmachen und daher die Einschreibung vom entsprechenden Akteur unterstützen. Er ist ebenfalls immer ein Widerstand _gegen_ andere Zirkulationsmöglichkeiten und daher andere Zirkulationswege von anderen Akteuren, die die Einschreibung des entsprechenden Akteurs weniger unterstützen bzw. schwieriger machen oder gar verhindern. Der Widerstand ist somit Ausdruck eines wie von Simmel thematisierten individuellen Gesetzes, d. h. einer Reserve, eines Zurückhaltens, eines Skrupels, einer Pudeur. Er bildet die erste Stufe in der Erfahrung vom Kontakt mit relationalen Ereignissen, weiteren (an- wie abwesenden) Akteuren und Aktanten auf der individuellen Ebene und die erste Stufe des Erlebnisses der eigenen Differenz, die sich während der Laufbahn eines jeden Akteurs in weiteren Zirkulationen ausdifferenziert [@Simmel1913]. Oder bildhaft formuliert: Wenn die Einschreibung über die Richtung der Akteurszirkulation informiert, bezeichnet der Widerstand derer Orientierung. Der Widerstand ist damit die Grundlage für die Ausübung der Reflexivität und der Affizierung. Er bereitet den Boden und bildet gleichsam die Ausgangslage für die Bildung von Erwartungen und Erwartungen auf Erwartungen, die zur Arbeit an relationalen Ereignissen führen. Er trägt entsprechend zur Unterstützung bzw. zur Destabilisierung der Einschreibung von Akteuren in Zirkulationen und daher in Relationsstrukturen. Weil der Widerstand das individuelle Gesetz zum Ausdruck bringt, und weil Akteure Geschichtsprodukte sind, sind sie sich ihren Widerstand nicht vollständig bewußt. Deshalb ist der Widerstand in seiner konkreten alltäglichen Erscheinung vielfältig -- von der Erprobung von Tätigkeiten mit unterschiedlichen Akteuren, Aktanten, relationalen Ereignissen zur alltäglichen Entwicklung von Taktiken und Strategien, die die Arbeit an der Mobilisation von anderen Akteuren und an der Verkettung von relationalen Ereignissen begleiten und beeinflussen.

Das Verhältnis zwischen dem Widerstand _für_ und _gegen_, das Gewicht von beiden Aspekten des Widerstandes auf die Zirkulation zwischen Positionen durch Relation informiert nicht nur über die Haltung von Akteuren gegenüber ihrer Relationsstruktur und derer allgemeinen Zirkulation. Dieses Verhältnis zwischen dem Widerstand _für_ und _gegen_ aufseiten der Akteure entspricht auch den Zirkulationsmöglichkeiten der Akteure und deren Zirkulationswegen entweder innerhalb einer Sequenz von einer Relationsstruktur oder zu einer anderen Sequenz von derselben Relationsstruktur oder aber zu einer anderen Relationsstruktur. Diese letzte Anmerkung kann etwa im Kontrast zu Bourdieu besser verstanden werden, der mit seinem Kampfansatz die _feinen Unterschiede_ zwischen Akteuren mit dem Abhängigkeitspfad zwischen Habitus, Kapitalarten und Felder begründet, der eine soziale Ordnung symbolisiert, die den Akteuren angesichts ihre "_relative Positionen_ in einem Raum von Relationen" aufgesetzt wird [@Bourdieu2012a, 48]. Mit dem Widerstandsbegriff sagen wir dagegen, dass solche Unterschiede im Zuge der Arbeit der Akteure an relationalen Ereignissen je nachdem gebildet werden, wie stark bzw. schwach diese Arbeit unterstützt wird bzw. wie wahrscheinlich es ist, dass eine solche Unterstütung zu einer konkreten und möglichst bedeutsame Zirkulation führt. Daher kommt die Stratifikation von Sequenzen und von Relationsstrukturen nach Zirkulationsmöglichkeiten und Zirkulationswegen, die nicht ein für allemal -- etwa wie bei Bourdieu mit dem sozialen Herkunft von Akteuren -- gegeben wird, sondern je nach der Verbreitung und Schrumpfung von diesen Sequenzen und Relationsstrukturen neu verteilt werden.

Oder anders formuliert: Wenn die Fragestellung Bourdieus die Macht in Unterstützung der Herrschaft in der Gesellschaft zur Reproduktion der gesellschaftlichen Strukturen adressiert, zeigt die Theorie der Relation ab den Begriffen der Einschreibung und des Widerstandes, dass sich "Gesellschaft" in Zirkulationen durch Relation beweg und eine solche Bewegung zur Unterstützung von einer Relationsstruktur im Vergleich zu anderen Relationsstrukturen und von einer Sequenzen im Vergleich zu anderen Sequenzen beiträgt. Daher entsteht eine ungleiche Verteilung von Zirkulationsmöglichkeiten auf Sequenzen und Relationsstrukturen, die in entsprechenden Kategorien von Akteuren und entsprechenden distinktiven Akteuren in diesen Kategorien widerspiegelt werden. Dies bedeutet, dass soziale Ungleichheiten auf der individuellen und kollektiven Ebenen in Bezug auf einem gegebenen Zustand der allgemeinen Zirkulation in Sequenzen/in Relationsstrukturen als Ungleichheit von Zirkulationsmöglichkeiten gedacht werden, die deshalb zu ungleichen Zirkulationswege führen und in Akteurkategorien symbolisiert werden. Soziale Ungleichheit ist in diesem Sinne kein gegebener Zustand, sondern ein Merkmal der nach Sequenzen strukturierte und strukturierende allgemeinen Zirkulation in einer Relationsstruktur, die, je nach Einschreibung und Widerstand in Bezug auf diese Zirkulation gestärkt oder gedämpft wird.

Diese Auffassung der sozialen Ungleichheit betrifft nicht nur individuelle Akteure, sondern auch Vermittlungsinstanzen, die die Zirkulationen in Sequenzen und Relationsstrukturen fördern und sanktionieren. An dieser Stelle verwendet die Theorie der Relation den Begriff der Reziprozität.

### Reziprozität

Der Begriff der Reziprozität ist der letzte Glied der Triade Einschreibung-Widerstand-Reziprozität, und dieser Begriff vervollständigt das Grundgerüst der Theorie der Relation. Wenn die Einschreibung wie die Richtung von Zirkulationen und der Widerstand wie ihre Orientierung sind, bezeichnet die Reziprozität den Moment, an dem die Richtung und die Orientierung der Zirkulationen die Position von kollektiven Akteuren stärkt, die zu weiteren Differenzierungen von solchen Zirkulationen und zu weiteren Zirkulationen von Akteuren führen. Mit der Einschreibung, dem Widerstand und der Reziprozität haben wir drei Stufen der Differenzierung der Arbeit an sozialen Ereignissen, wo die nächste Stufe die vorherige Stufe differenziert. Jetzt sind es Merkmale die, wie für die Einschreibung und den Widerstand, der Reziprozität eigen sind, die wir im Folgenden beschreiben.

In jeder Variante der relationalen Soziologien wird davon ausgegangen, dass eine Untersuchung der Gesellschaft nach einem relationalen Ansatz notwendigerweise eine Auffassung von Reziprozität voraussetzt. Die Theorie der Relation ist keine Ausnahme, selbst wenn sie die Reziprozität wie folgt versteht. Statt ontologisch zu argumentieren und die Reziprozität in jeder Art von relationalen Ereignissen als zwischenmenschlichen Leistungszirkel [@Kondylis1999, 498; zur impliziten Reziprozitätsauffassung von Coleman und Bourdieu vgl. @Schultze2022] oder als Stiftungsprinzip einer sozialen Beziehung zwischen Alter und Ego zu sehen [dazu paradigmatisch vgl. @Gouldner1960], sagt die Theorie der Relation, dass eine Reziprozität nur dann gegeben ist, wenn eine doppelte Einschreibung stattfindet. Gibt es keine doppelte Einschreibung, die stattfindet, dann gibt es keine Reziprozität. Diese scharfe Formulierung verwenden wir, damit es verstanden wird, dass nach der Theorie der Relation die Reziprozität keine Hin- und Zurückdynamik ist, die den relationalen Ereignissen _sui generis_ immanent wäre. Dies wiederum bezieht sich auf das, was wir schon erwähnt haben, als wir darauf hinwiesen, dass relationale Ereignisse nichts von selbst verbinden.

Ein erstes Merkmal der Reziprozität besteht darin, dass sie die Unterscheidungen zwischen Akteuren (in ihren Varianten als Menschen, Kollektive und Nicht-Menschen) und zwischen Akteuren und relationalen Ereignissen im Sinne ihres unterschiedlichen Beitrages zur Zirkulation in Sequenzen und Relationsstrukturen hervorhebt. Zweitens fördert die Reziprozität die Übersetzung von unterschiedlichen Zeiten und Räumen in -- schnellen/langsamen oder kurzen/langen -- Zirkulationen, die Tätigkeitbereiche in Sequenzen und in Relationsstrukturen verbreiten oder einschränken. Die Reziprozität muss deshalb kontextbezogen und vom Standpunkt der Stratifikation von Sequenzen und Relationsstrukturen verstanden werden. Kontextbezogen entwickelt sich die Reziprozität als Differenzierungsprinzip von Tätigkeitsbereichen. Vom Standpunkt der Stratifikation entwickelt sie sich als Prinzip der (neuen) Verteilung von Akteuren auf Tätigkeitsbereiche. Die Reziprozität legitimiert die Umstellungen von Positionen durch Relation, die die Tätigkeitsbereiche, die Sequenzen und die Relationsstrukturen strukturieren.

<!--
Wenn wir oben gesagt haben, dass der Widerstand der Akteure die Art und Weise widerspiegelt, wie die Akteure über ihre Arbeit an Ketten der Form Kollektiv -- Verkettungsarbeit -- Zirkulation in einem Verhältnis zu den strukturellen und morphologischen Determinanten ihrer Relationsstruktur stehen, das zu ihrer Einschreibung in einer Relationsstruktur führt, so ist damit zugleich die Reziprozität als Verteilungsinstrument von Relationsstrukturen angesprochen. Dabei ergibt sich die Verteilungsfunktion der Reziprozität daraus, dass Akteure ab der Entwicklung ihrer sozialen Arbeit in einem bestimmten Verhältnis zu den strukturellen und morphologischen Determinanten ihrer Relationsstruktur stehen, das sich im Widerstand _für_ und _gegen_ ihre Relationsstruktur manifestiert und sie entsprechend dieses Widerstands für eine bestimmte Position innerhalb ihrer Relationsstruktur prädestiniert, auf die sie durch die Reziprozität verteilt werden. Dies erlaubt es den Akteuren in der Folge, sich ausgehend von dieser Position in ihrer Relationsstruktur einzuschreiben. Die Theorie der Relation unterscheidet diesbezüglich zwischen vier Akteurkategorien, auf die die Akteure einer Relationsstruktur entsprechend ihres Widerstands verteilt werden. Mit Blick auf die Reziprozität ergibt sich hieraus erstens, dass diejenigen Akteure, die auf Basis der Reziprozität entweder durch mehr Widerstand _für_ ihre Relationsstruktur oder durch mehr Widerstand _gegen_ ihre Relationsstruktur charakterisiert sind, auf die erste und entsprechend auf die vierte Akteurkategorie in ihrer Relationsstruktur verteilt werden. Demgegenüber ergibt sich zweitens aus dem Zusammenhang zwischen der Position der Akteure und der Zirkulation der Akteure in ihrer Relationsstruktur, dass diejenigen Akteure, die auf Basis der Reziprozität entweder durch mehr Widerstand _für_ ihre Zirkulation bzw. _gegen_ ihre Position in ihrer Relationsstruktur oder durch mehr Widerstand _gegen_ ihre Zirkulation bzw. _für_ ihre Position in ihrer Relationsstruktur charakterisiert sind, auf die zweite und entsprechend auf die dritte Akteurkategorie in ihrer Relationsstruktur verteilt werden. Daran wird jedoch nicht nur ersichtlich, dass sich die Reziprozität als Verteilungsinstrument der Akteure auf Akteurkategorien in einer Relationsstruktur zeigt, sondern auch, dass die Reziprozität den Akteuren zudem den Weg in Akteurkategorien einer Relationsstruktur, die nicht ihrem Widerstand entsprechen, versperrt. Das heißt, dass aufgrund der Reziprozität in einer Relationsstruktur die Akteure eine Position in einer Akteurkategorie nur nach ihrem Widerstand _für_ oder _gegen_ beziehen können. Daraus folgt, dass die Reziprozität gleichsam ein Instrument der Schließung von Sequenzen und von Relationsstrukturen darstellt, das die Kompatibilität zwischen der Position der Akteure und ihrem Widerstand in den Relationsstrukturen verankert und den Akteuren somit nur diejenigen Zirkulationsmöglichkeiten einräumt, die explizit mit ihrer Position verbunden sind. Anhand dieses Zusammenhangs zwischen dem Widerstand der Akteure und der Reziprozität, die die Akteure auf Positionen verteilt und ihnen dabei andere Zirkulationswege zu anderen Positionen verwehrt, wird also ersichtlich, dass der Widerstand der Akteure in seiner doppelten Dimensionalität in einem direkten Wechselwirkungsverhältnis zur Reziprozität in einer Relationsstruktur steht.
-->

Oder um es anders zu formulieren: Das Reziprozitätkonzept der Theorie der Relation ist nicht unmittelbar mit Tausch und somit auch nicht unmittelbar mit interdependenten Tauschpraktiken verbunden. Sie entwickelt sich nicht von bipolären zu multipolären oder von linearen zu zirkulären Interaktionen _zwischen Menschen_ [vgl. @Lévi-Strauss1981, 642-643; vgl. auch @Mauss1989], weil Reziprozität unmittelbar mit Einschreibung und mit Widerstand verbunden ist und aus dieser Verbindung verwirklicht wird.

_zwischen Menschen_ insofern, als weder der Einschreibungsakt von Akteuren in Vermittlungsinstanzen noch der Einschreibungsakt von Vermittlungsinstanzen in Akteure im Vollzug von Interaktionssequenzen des Austausches umgesetzt werden. Dies bedeutet auch, dass die Reziprozität der doppelten Einschreibung nicht zu solidarischen Gruppenbeziehungen [@Lévi-Strauss1981, 646-647] zwischen Akteuren und Vermittlungsinstanzen führt. Nicht zuletzt deshalb, weil es sich bei der doppelten Einschreibung prinzipiell um mittelbare Operationen der Einbettung in eine Zirkulation von einer Relationsstruktur und nicht um unmittelbare Tauschoperationen zur Herstellung einer Allianz oder _visa versa_ einer sozialen Herrschafts- bzw. Konkurrenzbeziehung handelt [vgl. @Schultze2022, 355-361, 368-370; vgl. auch @Bourdieu2014a, 196; @Bourdieu2014b, 430; @Bourdieu2009, 156]. In diesem Sinne kommt sowohl dem Einschreibungsakt von Akteuren in Vermittlungsinstanzen als auch dem Einschreibungsakt von Vermittlungsinstanzen in Akteure ein überindividueller Charakter zu. Gleichsam führen die unmittelbare Durchführung der sozialen Arbeit von Akteuren einerseits und die unmittelbare Durchführung der Sozialisations- und Förderarbeit von Vermittlungsinstanzen andererseits nur dann zu Reziprozität, wenn die jeweils geleistete Arbeit eine Relationsstruktur und die Zirkulation in dieser Relationsstruktur unterstützt bzw. bewahrt oder stärkt. Wird jedoch von der sozialen Arbeit seitens der Akteure, der Vermittlungsarbeit oder auch von beiden Seiten abgewichen, dann wird die Einschreibung in einer Relationsstruktur geschwächt bzw. gestört. Dies beeinträchtigt zugleich die Reziprozität, indem die Zirkulation der Akteure gefährdet und die Position der Vermittlungsinstanzen strukturell bedroht wird, was wiederum die Effizienz der Instanzen bei der Unterstützung von Zirkulationswegen und Zirkulationsmöglichkeiten nachhaltig beeinträchtigen kann. In diesem Fall wird die Relationsstruktur in Teilen oder insgesamt geschwächt, weil Abweichungen von der doppelten Einschreibung die Unterschiede zwischen den Zirkulationen einer Relationsstruktur sowohl für die Akteure als auch für die Vermittlungsinstanzen verwischen. Dies veranlasst eine zahlenmäßige Schrumpfung der Akteure einer Relationsstruktur, und zieht gleichsam eine zahlenmäßige Schrumpfung der Vermittlungsinstanzen einer Relationsstruktur nach sich. Akteure wechseln die Relationsstruktur und Vermittlungsinstanzen werden abgebaut. Für die übrig gebliebenen Akteure der so geschwächten Relationsstruktur bedeutet dies, dass sich ihre Zirkulationsmöglichkeiten stark minimieren. Es gibt also eine enge Verbindung zwischen der Aufrechterhaltung der Reziprozität in Relationsstrukturen und der Aufrechterhaltung der Relationsstrukturen selbst, wobei diese enge Verbindung nicht ein für alle Mal stabilisiert werden kann, sondern vielmehr ständig bestimmt werden muss.

Damit abstrahiert das Reziprozitätsverständnis der Theorie der Relation von zwischenmenschlichen Interaktions- und Praxisformen und betont stattdessen die Verbindung, die sowohl Akteure mittelbar über ihre soziale Arbeit als auch Vermittlungsinstanzen mittelbar über ihre Sozialisations- und Förderarbeit zu einer Relationsstruktur, ihrer charakteristischen Bedeutung und ihrer Zirkulation haben. Eine unmittelbare Reziprozität würde für die Theorie der Relation bedeuten, dass sowohl die Akteure in einer Relationsstruktur als auch die Vermittlungsinstanzen derselben Relationsstruktur direkt auf die Reziprozität ihrer Relationsstruktur Einfluss nehmen könnten und somit auch in der Lage wären, die Bedeutung der Reziprozität persönlich zu verändern. Dies würde bedeuten, dass die Reziprozität sowohl in der Kontrolle der Akteure als auch der Vermittlungsinstanzen stehen würde, _als ob_ sie Einschreibungsakte, Zirkulationen, Sequenzen und Relationsstrukturen kontrollieren würden. Eine solche Vorstellung der Reziprozität vergäße dabei die Einbettung von Akteuren und Vermittlungsinstanzen in die mehreren Ebenen von Relationsstrukturen, deren Wechselspiel sowie deren Folgen im Sinne der Produktion von Abweichungen aus diesem Wechselspiel sie nicht nach Belieben oder unbesehen überwältigen, geschweige denn ausschalten können. Eine solche Auffassung von Reziprozität hätte zudem den Nachteil, zu einem Ansatz zu führen, der unintendierte Wirkungen der Reziprozität wie etwa das Pflichtgefühl gegenüber anderen Akteuren oder Kollektiven, die Identifikation mit einer Tätigkeit, das Gefühl der Zugehörigkeit zu einem Kollektiv nicht adressieren könnte, ohne solche unintendierte Wirkungen der Reziprozität auf die bewusste bzw. intendierte Verwendung der Reziprozität zu reduzieren. Dabei würde die Reziprozität auf strategisches Handeln eingeschränkt und als aus interpersönlichen gewöhnlichen Alltagsverhältnissen entstanden verstanden, in denen jedoch nur ihre Spuren aus vergangenen Einschrebungsakten für Akteuren und Kollektiven wahrzunehmen sind. Dieser Glaube an eine Reziprozität, die aus der Zwischenmenschlichkeit entstehen und die ganze Gesellschaft strukturieren würde, belegt dagegen eindringlich, wie wichtig Einschreibungen für Akteure und Kollektiven sind, die deshalb nach einer solchen Reziprozität überall suchen, selbst wenn sie nur selten bzw. aus Einschreibungsakten entsteht und mit ihnen vergeht.

Deshalb sagt die Theorie der Relation, dass die Akteure einen indirekten Einfluss auf die Reziprozität ihrer Relationsstruktur ausüben, den sie einerseits auf der Grundlage ihrer sozialen Arbeit an Ketten der Form Kollektiv -- Verkettungsarbeit -- Zirkulation in einer Relationsstruktur und andererseits über ihre darüber bewerkstelligte Einschreibung mit Vermittlungsinstanzen in dieser Relationsstruktur akquirieren. Über die Möglichkeit indirekter und zugleich dauerhafter Einflussnahme auf die Reziprozität in einer Relationsstruktur verfügen auch die Vermittlungsinstanzen. Anders als die Akteure generieren sie diesen Einfluss jedoch, indem sie -- vermittelt über ihre Vermittlungsarbeit -- das Verhältnis zwischen den strukturellen und morphologischen Determinanten ihrer Relationsstruktur regulieren, um ihre Vermittlungsstruktur zu erhalten bzw. auszudehnen. Dies ist eine Konsequenz der Nicht-Zirkulation von Vermittlungsinstanzen. Wie oben erwähnt und im Unterschied zu Akteuren und Aktanten zirkulieren Vermittlungsinstanzen nicht innerhalb von Sequenzen einer Relationsstruktur oder zwischen Relationsstrukturen. Deshalb erschöpft sich ihre Vermittlungsstruktur keineswegs in der Sozialisation und Förderung von Akteuren, was wiederum bedeutet, dass Vermittlungsinstanzen nicht darauf abzielen, eine unmittelbare Wirkung auf Akteure und Aktanten zu haben, sondern ihre Vermittlungsstruktur idealerweise über die gesamte Relationsstruktur hinweg auszudehnen. Diese Verbreitung ihrer Vermittlungsstruktur erfolgt umso erfolgreicher, als durch ihren indirekten Einfluss auf die Reziprozität Vermittlungsinstanzen stets versuchen, langfristig ihre Position als Vermittlungsinstanzen einer Relationsstruktur für die Akteure derselben Relationsstruktur zu bewahren.

Angefangen mit der Ausgangslage der Theorie der Relation und in Anlehnung an den Beitrag von Knöbl zur Kritik der Verwendung von Prozessbegriffen in den Sozialwissenschaften, zu denen auch der Begriff der Relation durchaus zählt, haben wir versucht, in der Herausforderung dieser Kritik die Grundlage der Theorie der Relation sowie ihr Verständnis von Relation im Lichte des Primats der Zirkulation zu erklären. Diese Grundlage haben wir in einem anderen Kontext systematisch in ihrer Dynamik in Bezug auf die Stratifikation der Relationsstrukturen und ihrer vier Sequenzen in Akteurkategorien, die Mobilität dieser Akteure, die entsprechende Verbreitung bzw. Schrumpfung von Vermittlungsinstanzen, von Sequenzen in Relationsstrukturen und von Relationsstrukturen selbst je nachdem ausgebaut [@PapilloudSchultze2022], wie Relationsstrukturen ihr Hauptmerkmal bewahren bzw. durchsetzen können. Oder anders gesagt: Wir haben beschrieben, wie Relationsstrukturen die Bedeutung der Reziprozität auf andere Relationsstrukturen verbreiten, um die Zirkulationen in diesen Relationstrukturen unter ihre Kontrolle zu bringen. Dies führt zur Botschaft der Theorie der Relation, womit wir nun dieses Kapitel zur Ausgangslage der Theorie der Relation abschließen möchten.

### Schlusswort

Die Theorie der Relation besagt, dass Relation als ideale, perfekte Relation die Grundmotivation des sozialen Lebens und die Grundlage der Rechtfertigung der vielfältigen Verhältnisse darstellt, die das gesellschaftliche Leben generiert und die Abweichungen von einer solchen idealen Relation in Form von Relationsstrukturen sequentiell dimensionieren. Die Theorie der Relation erklärt entsprechend, wie dieses Streben nach einer idealen Relation auf den unterschiedlichen Ebenen einer Gesellschaft ständig gestört wird, woraus bzw. wodurch wiederum Zirkulationen von Akteuren, Mobilisierungen von Kollektivakteuren, Einschreibungsakte, auf- und absteigende Mobilitäten, Veränderungen von Ungleichheiten, von Einflussstrategien und Machtkämpfen sowie gesellschaftliche Blasen als verwundbare Meta-Relationsstrukturen produziert werden. Diese Botschaft ergibt sich aus der Ausgangslage der Theorie der Relation.

Diese Ausgangslage haben wir im vorliegenden Beitrag entlang der Grundbegriffe dargestellt -- angefangen bei dem Primat der Zirkulation, relationalen Ereignissen, dem abweichenden Merkmal von Relationsstrukturen und deren Sequenzen über die soziale Arbeit zur Umstellung von Positionen, die Sequenzen von Relationsstrukturen und Relationsstrukturen, den Widerstand der Akteure bis hin zur Differenzierung dieser Arbeit und der entsprechenden Einschreibung mit Vermittlungsinstanzen in Zirkulationen. Auf Basis dieser Ausgangslage der Theorie der Relation ist es möglich, die Kernfrage zu formulieren, die diese Theorie stellt und die wie folgt zusammengefasst werden kann: Wie gehen unsere Gesellschaften in allen ihrer Komponenten und Dimensionen mit Umstellungen um, die zu Einschreibungen von Akteuren, Vermittlungsinstanzen mit Aktanten und Medien in Zirkulationen von Relationsstrukturen und schließlich in diesen Relationsstrukturen ab ihren Sequenzen münden? Diese Frage ist vielleicht diejenige, die die relationalen Soziologien und die Soziologien, die nach einem relationalen Ansatz argumentieren, strukturiert und in ihrer Diversität eint. Im Rahmen der Theorie der Relation bekommt diese Frage eine eindeutige Antwort, die sich auf den unterschiedlichen Ebenen dieser Theorie in ihrer Komplexität deklinieren und dimensionieren lässt: Nach Zirkulation durch Relation.

Im Unterschied zu anderen oder ehemaligen relationalen Ansätze, die in der Soziologie entwickelt wurden, um eine Erklärung der Gesellschaft auf der Grundlage von relationalen Ansätzen zu formulieren, zielt die Theorie der Relation darauf ab, ihren Relationsansatz nicht auf einer einzigen Bedeutung von Relation und daher Relation nicht auf einer spezifischen Interaktion sowie Relation nicht auf einer Auffassung der Gesellschaft _als_ Relation zu reduzieren. Deshalb dekonstruiert sie solche Formen von Relationismus zum Vorteil einer analytischen, diachron und synchron vergleichenden Betrachtung von Gesellschaften im Wandel, das heißt, in ihrer unterschiedlichen Konfigurationen als veränderbare Verhältnisse innerhalb und zwischen Relationsstrukturen, die diese Gesellschaften von ihren Instanzen bis zu ihren Akteuren charakterisieren. Damit ist die Theorie der Relation nicht nur in der Lage, den Relativismus von relationalen Ansätzen aufzugreifen, wonach soziale Phänomene in Relation gedacht werden sollten, sondern die Bedeutung und den Preis eines solchen Relativismus im Sinne der Stärkung oder Schwächung von Relationsstrukturen, deren Sequenzen und Zirkulationen zu problematisieren. Dabei wirft sie ein neues Licht auf bekannte Fragen der Soziologie wie die Fragen der sozialen Ungleichheit, der Entwicklung von Legitimationsprozessen, der damit verbundenen Soziabilitätsnetzwerke und deren Wirkung auf die Schließung oder die Eröffnung von alternativen Formen des gesellschaftlichen Lebens [jenseits von etablierten Hierarchien, anerkannten Rechten und ausgeübten Formen des Zusammenhaltes.

<!--


Um auf diese Folgen einzugehen, ist es zuerst notwendig, die unterschiedlichen Arten von Vermittlungsinstanzen zu thematisieren. Zu diesem Zweck wenden wir uns erneut den vier Abweichungen von Relationsstrukturen zu, die in der Theorie der Relation nicht nur als Stratifikationsprinzip von Relationsstrukturen und deren Zirkulationen dienen, sondern auch als Differenzierungsprinzip der unterschiedlichen Arten von Vermittlungsinstanzen fungieren. So lässt sich einerseits sagen, dass in jeder Relationsstruktur alle Arten von Vermittlungsinstanzen vorhanden sind und zwar deshalb, weil alle Relationsstrukturen sequentiell immer nach denselben vier Sequenzen der sozialen Arbeit an relationalen Ereignissen etabliert werden (vgl. ebd., 254). Jedoch ähnlich wie die sequentielle Etablierung von Relationsstrukturen nach den Sequenzen Investition, Repräsentation, Materialität und Attraktivität _nicht_ in jeder Relationsstruktur nach derselben Prioritätsordnung erfolgt, weisen auch die unterschiedlichen Arten von Vermittlungsinstanzen je nach Relationsstruktur -- im Unterschied zur Soziologie Bourdieus, in der Institutionen und deren Subinstitutionen _konstitutiv_ wie _delegativ_ der herrschenden Klasse verpflichtet sind [@Bourdieu1977, 30] -- eine bestimmte Prioritätsordnung auf. Dies erklärt sich zum einen damit, dass jede Relationsstruktur ab einer bestimmten Sequenz -- der Abweichungs- bzw. Kernsequenz -- von den anderen Relationsstrukturen abweicht, die dann nicht nur die Anordnung von Sequenzen der sozialen Arbeit von Akteuren an relationalen Ereignissen und die nach diesen Sequenzen verlaufende Entwicklung der allgemeinen Zirkulation bestimmt, sondern sich auch in der Prioritätsreihenfolge der Arten von Vermittlungsinstanzen für jede der vier Relationsstrukturen niederschlägt. In ähnlicher Weise also, wie aus der je spezifischen sequentiellen Ordnung einer Relationsstruktur die Entwicklung der allgemeinen Zirkulation dieser Relationsstruktur resultiert, lassen sich auch die Vermittlungsinstanzen sequentiell nach der Zirkulation voneinander unterscheiden. Sie unterscheiden sich voneinander je nachdem, wie diese Zirkulation erstens in ihrer Ausgangssequenz -- die in jeder Relationsstruktur zugleich die Abweichungssequenz von einer _idealen_ Relation darstellt -- und zweitens in ihren Folgesequenzen gegeben ist [@PapilloudSchultze2022, 249]. Dies erklärt sich auch damit, dass jede Sequenz gleichsam mit einer bestimmten Ebene der Vermittlungsstruktur der Instanzen von Relationsstrukturen verknüpft ist [vgl. unser Beispiel zur Nanomedizin als Mediation der Medien orientierten Relationsstruktur vgl. @PapilloudSchultze2023, 25-50]. Deshalb ist die Bewahrung und Verbreitung dieser Ebene der Vermittlungsstruktur im Dienste des Hauptmerkmals der jeweiligen Relationsstruktur einerseits und der Ausgangssequenz der Zirkulation in dieser Relationsstruktur andererseits jeweils auch mit einer bestimmten Art von Vermittlungsinstanz assoziiert [@PapilloudSchultze2022, 253]. Nehmen wir das Beispiel der ersten Relationsstruktur, um diesen Punkt der Differenzierung zwischen Vermittlungsinstanzen zu verdeutlichen.

Wir haben gesagt, dass die erste Relationsstruktur ab dem Punkt der Investition in die soziale Arbeit an relationalen Ereignissen von einer _idealen_ Relation abweicht und die allgemeine Zirkulation in dieser Relationsstruktur entsprechend in der (Kern)Sequenz Investition beginnt, über die Folgesequenzen Repräsentation, Materialität und Attraktivität verläuft, bis sie wieder in der Sequenz Investition sowohl endet als auch von Neuem beginnt. Für die erste Relationsstruktur ergibt sich hieraus die folgende sequentielle Prioritätsreihenfolge der Arten von Vermittlungsinstanzen. So adressieren die relationsstrukturspezifischen Vermittlungsinstanzen die _Investition_ in relationale Ereignisse, wobei diese Art von Instanz gleichzeitig das Schwerkraftzentrum der ersten Relationsstruktur bildet, da ihr nicht nur die Aufrechterhaltung der allgemeinen Zirkulation in dieser Relationsstruktur obliegt, sondern auch die Bewahrung des Hauptmerkmals dieser Releationsstruktur (vgl. ebd., 232-233). Zudem liefern die relationsstrukturspezifischen Vermittlungsinstanzen als Schwerkraftzentrum ihrer Relationsstruktur zugleich die Vermittlungsstruktur, die von den anderen Instanzen aufgegriffen und entsprechend der Ebene ihrer jeweiligen Vermittlungsstruktur angepasst wird. Entsprechend adressieren die sequenzspezifischen Vermittlungsinstanzen in allen Sequenzen dieser Relationsstruktur die _Repräsentation_ von Kollektiven im Dienste kollektiver Investition in relationale Ereignisse (vgl. ebd., 236-239), die teilsequenzspezifischen Vermittlungsinstanzen adressieren die _Materialität_ von Akteuren im Dienste der kollektiven Investition in relationale Ereignisse (vgl. ebd., 241-243) und die umverteilenden Vermittlungsinstanzen adressieren schließlich die _Attraktivität_ von Mediationen, die wiederum zu neuen _Investitionen_ in relationale Ereignisse animieren soll (vgl. ebd., 245-246). Daran ist ersichtlich, dass jeder Art von Instanz eine besondere Bedeutung in Bezug auf die Förderung der Zirkulation aller Akteure in einer Relationsstruktur zukommt (vgl. ebd., 254), weshalb keine Relationsstruktur auf eine Ebene ihrer Vermittlungsstruktur verzichten kann, selbst wenn diese Ebenen der Ebene der Kernsequenz -- im Falle der ersten Relationsstruktur die Sequenz Investition -- nachgeordnet sind und sich ihre spezifische Bedeutung unter stetiger Bezugnahme auf die Kernsequenz ergibt (vgl. ebd., 263). Oder anders gesagt: Damit eine Relationsstruktur ihre spezifische Zirkulation entwickeln kann, sind ihre Vermittlungsinstanzen in ihrer Vielfalt notwendig, und daraus entsteht eine erste Folge der Theorie der Relation, die die Anpassung der Zirkulation in Relationsstrukturen betrifft.

Weil Relationsstrukturen von einer idealen Relation abweichen, verwirklichen sie Zirkulationen, die nicht perfekt laufen bzw. die von einer idealen Zirkulation in einer Relationsstruktur ebenfalls abweichen. Dies führt entweder zu einer übermäßigen Akkumulation von Akteuren in einer Relationstruktur, was die erhöhte Stratifikation dieser Relationsstruktur oder einiger ihrer Sequenzen zur Folge hat, oder zu einem unverhältnismäßigen Abstrom von Akteuren. Derartige Szenarien haben das Potential, die allgemeine Zirkulation einer Relationsstruktur zu destabilisieren, weil eine etwaige Schwächung oder Störung der (Kern)Sequenz die (Weiter)Zirkulation der Akteure in die Folgesequenzen behindert oder gar stört, was letztlich auch die Folgesequenzen in Mitleidenschaft zieht und die Existenz der gesamten Relationsstruktur gefährden kann. Um eine solche Gefahrenlage abzuwenden, stabilisieren die Vermittlungsinstanzen die Zirkulation, indem sie diese  Schritt für Schritt und zwar entsprechend der sequentiellen Ordnung der Zirkulation dieser Relationsstruktur anpassen, was von einer Kaskadenwirkung der Stärkung und Schwächung von Vermittlungsinstanzen begleitet wird (vgl. ebd., 300). Nehmen wir nochmal das Beispiel der ersten Relationsstruktur, davon die Kernsequenz die Sequenz Investition ist. Durch Schwächung oder Störung dieser Kernsequenz werden die damit verbundenen Vermittlungsinstanzen ebenfalls geschwächt oder gestört.

Diese Kaskadenwirkung ergibt sich daraus, dass mit der Schwächung oder Störung der (Kern)Sequenz auch die doppelte Einschreibung stark beeinträchtigt ist, was insbesondere diejenige Art von Vermittlungsinstanz schwächt, die explizit mit dieser Bedeutungsebene der Vermittlungsstruktur verbunden ist und den Widerstand _gegen_ diese Instanzen unter den Akteuren stärkt -- im Falle der ersten Relationsstruktur die relationsstrukturspezifischen Instanzen (vgl. ebd., 261-263) . Durch diesen Widerstand heben die Akteure gleichsam die Bedeutung der für die Ebene der Folgesequenz zuständigen Vermittlungsinstanz hervor, mit denen sie sich nun verstärkt in einer Relationsstruktur einschreiben, was wiederum eine Stärkung dieser Instanz im Vergleich zu den anderen Instanzen der betreffenden Relationsstruktur nach sich zieht -- im Falle der ersten Relationsstruktur die sequenzspezifischen Vermittlungsinstanzen der Sequenz Repräsentation (vgl. ebd., 265-267). Aber auch diese Art von Vermittlungsinstanz gerät im Verlauf der Anpassung der Zirkulation zusehends an ihre Grenzen, was die doppelte Einschreibung mit dieser Instanz beeinträchtigt, zum Widerstand der Akteure _gegen_ diese Instanz führt und gleichsam den Widerstand _für_ die mit der nächsten Folgesequenz verbundenen Vermittlungsinstanz stärkt, mit der sich die Akteure zunehmend in einer Relationsstruktur einschreiben -- im Falle der ersten Relationsstruktur die teilsequenzspezifischen Vermittlungsinstanzen in der Sequenz Materialität, deren allmählich einsetzende Schwäche wiederum mit der Stärkung der umverteilenden Vermittlungsinstanzen in der Sequenz Atraktivität einhergeht, bis schließlich auch diese Instanz zu Gunsten der relationsstrukturspezifischen Instanzen geschwächt wird und die Stabilität der allgemeinen Zirkulation in der ersten Relationsstruktur wieder hergestellt ist (vgl. ebd., 267-276). Diese Korrespondenz zwischen dem Widerstand der Akteure einerseits und der Kaskadenwirkung der Schwächung und Stärkung von Vermittlungsinstanzen andererseits spiegelt sich auch im Hierarchieprinzip wider, das von der während der sequentiellen Anpassung der Zirkulation gestärkten Vermittlungsinstanz eingeführt wird, um Zirkulationsmöglichkeiten unter den Akteuren neuzuverteilen. Diese Korrespondenz erklärt zudem auch, wie die Zirkulation in einer Relationsstruktur stabilisiert und wie die Reziprozität in einer Relationsstruktur im Zuge der Anpassung der Zirkulation auf jeder Ebene einer Relationsstruktur aufrechterhalten wird.

Dieser letzte Punkt führt uns sogleich zu der zweiten Folge, die sowohl die Bedeutung der Reziprozität in jeder Relationsstruktur betrifft als auch die Auswirkungen auf diese Bedeutung thematisiert, die durch die Schwächung des Schwerkraftzentrums einer Relationsstruktur und die dadurch verursachte Anpassung der Zirkulation auftreten. Jede Relationsstruktur verfügt über eine bestimmte Kernbedeutung der Reziprozität, die von allen Arten von Vermittlungsinstanzen in einer Relationsstruktur unterstützt wird, um das Hauptmerkmal der Relationsstruktur und ihre eigene Bedeutung für die Relationsstruktur zu bewahren. So besteht der Kern der Reziprozität in der ersten Relationsstruktur darin, die _Mobilisation von Akteuren und Kollektiven_ sicherzustellen (ebd., 301), um die Verbreitung des austauschzentrierten Merkmals dieser Relationsstruktur zu bewahren (ebd., 263). Demgegenüber besteht die Kernbedeutung der Reziprozität in der zweiten und dritten Relationsstruktur in der _Verkettungsarbeit an relationalen Ereignissen_ (ebd., 301), wobei diese in der zweiten Relationsstruktur vorwiegend der Mobilisation von Akteuren zur Einschränkung von Monopolen dient (ebd., 277), während sie in der dritten Relationsstruktur wesentlich für die Zirkulation der Akteure und die Bewahrung von Kollektiven sorgt (ebd., 282). In der vierten Relationsstruktur besteht die erstrangige Bedeutung der Reziprozität dagegen in der _Zirkulation der Akteure_  (ebd., 301), damit die Attraktivität der Akteure bewahrt und deren Zirkulation gewährleistet werden kann. Aus dieser Hauptbedeutung der Reziprozität ergibt sich überdies für jede Relationsstruktur die Bedeutung der Legitimität, welche die Akteure im Zuge der doppelten Einschreibung an der Seite der Vermittlungsinstanzen verliehen wird. Kommt es nun zu einer Anpassung der Zirkulation in den Relationsstrukturen, so stellt sich zwangsläufig eine gewisse Distanz zu dieser für jede Relationsstruktur charakteristischen Bedeutung der Reziprozität und der Legitimität an der Seite sowohl der Akteure als auch der Vermittlungsinstanzen ein. Diese Distanz ergibt sich aus der Destabilisierung der Zirkulation einer Relationsstruktur und der Anpassung dieser entlang der Kaskadenwirkung der Schwächung und Stärkung unterschiedlicher Arten von Vermittlungsinstanzen in einer Relationsstruktur, wodurch abweichende Hierarchieprinzipien in einer Relationsstruktur eingeführt und unangepasste Reziprozitätsbedeutungen begünstigt werden, deren Gestalt eigentlich für die anderen Relationsstrukturen charakteristisch ist (ebd., 301f.). Dies führt wiederum zu unangepasste Erwartungsstrukturen bei den Akteuren und unangepassten Wahrnehmungen der Kernbedeutung von Reziprozität und Legitimität bei den Akteuren und Vermittlungsinstanzen in der betreffenden Relationsstruktur, die nur mit der Zeit und sukzessiv, d. h. nach der sequentiellen Ordnung in einer Relationsstruktur, abgebaut werden können (ebd., 302).

Solche unangepassten Wahrnehmungen und Erwartungen betreffen allerdings nicht alle Akteure in allen Akteurkategorien gleichermaßen, womit wir bei der dritten Folge für soziologische Untersuchungen mit der Theorie der Relation angelangt sind: Vermittlungsinstanzen schaffen soziale Ungleichheiten zwischen Akteuren unterschiedlicher Akteurkategorien, weil sie -- anders als bei Bourdieu, wo hauptsächlich die beherrschen Klassen und Klassenfraktionen sozialer Ungleichheit auf Basis ihrer positionalen Distanzrelationen zur herrschenden Klasse ausgesetzt sind [@Bourdieu2012a] -- stets an der Bewahrung des Hauptmerkmals einer Relationsstruktur, deren entsprechender Reziprozität und deren Legitimität arbeiten [@PapilloudSchultze2022, 302]. So sind im Falle einer Anpassung der Zirkulation diejenigen Akteure am stärksten von sozialer Ungleichheit aufgrund von unangepassten Wahrnehmungen und Erwartungen hinsichtlich der Reziprozität und Legitimität einer Relationsstruktur betroffen, die auch im Falle einer stabilen Zirkulation am wenigsten von den Schwerkraftzentren der vier Relationsstrukturen sozialisiert und gefördert werden und daher ohnehin deutlich mehr Zeit und Arbeit aufwenden müssen, um überhaupt Vermittlungsinstanzen zu erreichen, mit denen sie sich in einer Relationsstruktur einschreiben können. Nun lässt sich sagen, dass eine solche Ungleichheit zwischen den Akteuren verschiedener Akteurkategorien zwar durch die sequentielle Anpassung der Zirkulation und die dadurch eingeführten Hierarchieprinzipien neu dimensioniert werden, weil die Akteurkategorien sich dann in dem Maße einander ungleich werden, wie die Zirkulation einer Relationsstruktur angepasst zirkuliert. Zugleich lässt sich aber ebenso sagen, dass die von Vermittlungsinstanzen produzierte Ungleichheit durch die Wiederherstellung der allgemeinen Zirkulation und deren Bewahrung grundsätzlich bestehen bleibt. Daraus ergibt sich ferner, dass es sich bei Vermittlungsinstanzen um konservative Instanzen einer Relationsstruktur handelt, die die sequentielle Ordnung ihrer Relationsstruktur bewahren müssen, da diese die Grundlage ihrer Vermittlungsstruktur liefert und die Instanzen einer Relationsstruktur ohne diese Grundlage weder ihrer Sozialisations- und Förderarbeit nachkommen können noch gegenüber ihren Sequenzen und Teilsequenzen legitim bleiben.

Daraus resultiert gleichsam die vierte Folge für soziologische Untersuchungen auf Basis der Theorie der Relation: die Priorisierung von Akteurkategorien durch Vermittlungsinstanzen in den vier Relationsstrukturen. Wir haben bereits darauf hingewiesen, dass die Reziprozität in einer Relationsstruktur sowohl als Verteilungs- als auch als Schließungsinstrument fungiert -- Akteure prädestinieren sich ab ihrer sozialen Arbeit in den Sequenzen einer Relationsstruktur für eine bestimmte Position innerhalb der vier Akteurkategorien, die ausnahmslos ihrem Widerstand _für_ und _gegen_ die Relationsstruktur entspricht und die es ihnen erlaubt, sich ausgehend von dieser Position mit den Vermittlungsinstanzen in eine Relationsstruktur einzuschreiben (vgl. ebd., 49). Dieser letzte Nachsatz ließe vermuten, dass unterschiedslos alle Akteure die Möglichkeit erhalten, eine Reziprozität in ihrer Relationsstruktur zu erleben. Dies ist allerdings mit Nichten der Fall und zwar deshalb, weil jede Art von Vermittlungsinstanz mit einer bestimmten Ebene der Vermittlungsstruktur verbunden ist und aufgrund dessen ein Teil der Akteure ausgehend von ihrer ebenenspezifischen Position in den Sequenzen einer Relationsstruktur keine passenden Vermittlungsinstanzen findet oder erreicht, wodurch ihnen wiederum die Möglichkeit zur Zirkulation verwehrt bleibt (ebd., 303). Ein solcher Sachverhalt bedarf der Erklärung: Zum einen gibt es zwar Akteure, denen wegen der vorwiegend morphologischen Determination Ihrer Position in allen Relationsstrukuren vergleichbare Zirkulationsmöglichkeiten eingeräumt werden -- so lassen sich bspw. in einer statischen Perspektive unmittelbar mehr Zirkulationen unter Akteuren der ersten Kategorie und mittelbar unter den Akteuren der zweiten Kategorie verzeichnen (vgl. ebd., 304f.). Das heißt jedoch nicht, dass grundsätzlich immer jene Akteure bzw. Akteurkategorien, die über mehr Zirkulationsmöglichkeiten verfügen, in allen Relationsstrukturen gleichermaßen begünstigt werden. Dies ist deshalb der Fall, weil nicht immer dieselben Akteurkategorien am stärksten zur Bewahrung der Zirkulation in einer Relationsstruktur beitragen. So verfügt jede Relationsstruktur entsprechend ihrer Abweichungs- bzw. Kernsequenz über eine bestimmte herrschende Art von Vermittlungsinstanz, die wir als Schwerkraftzentrum einer Relationsstruktur bezeichnen -- in der ersten Relationsstruktur die relationsspezifischen Vermittlungsinstanzen, in der zweiten die sequenzspezifischen Instanzen, in der dritten die teilsequenzspezifischen Instanzen und in der vierten Relationsstruktur die umverteilenden Vermittlungsinstanzen (vgl. ebd., 247). Weil nun ferner jedem Schwerkraftzentrum einer Relationsstruktur die Bewahrung und Verbreitung des Hauptmerkmals und der damit verbundenen sequentiellen Kernbedeutung einer Relationsstruktur obliegt, adressiert diese Instanz eine bestimmte Ebene der Vermittlungsstruktur, die wiederum mit der Einführung eines herrschenden Hierarchieprinzips einhergeht, wodurch wiederum diejenigen Akteure bestimmter Akteurkategorien besonders angesprochen werden, die für die Bewahrung der Zirkulation unabdingbar sind (vgl. ebd., 305). Obwohl also in jeder Sequenz von jeder Relationsstruktur immer alle vier Akteurkategorien vorhanden sind, werden vom Schwerkraftzentrum einer jeden Relationsstruktur bei stabiler Zirkulation diejenigen Akteure bzw. Akteurkategorien besonders prioritär sozialisiert und in ihrer Zirkulation gefördert, die wesentlich zur Gewährleistung der allgemeinen Zirkulation einer Relationsstruktur beitragen. In der ersten Relationsstruktur sind dies vor allem die Akteure der ersten Kategorie [am Beispiel einer Forschungseinrichtung vgl. @PapilloudSchultze2023, 129] und mittelbar die Akteure der zweiten Kategorie, in der zweiten sind es vorrangig die Akteure der zweiten Kategorie sowie mittelbar die der dritten Kategorie, in der dritten sind es vorrangig Akteure der dritten Kategorie sowie mittelbar die der zweiten Kategorie und in der vierten Relationsstruktur sind es vor allem die Akteure der vierten Kategorie und unmittelbar die der ersten Kategorie [@PapilloudSchultze2022, 305f.].

Gesetz dem Fall jedoch, dass die allgemeine Zirkulation in einer Relationsstruktur instabil verläuft und entlang der sequentiellen Ordnung einer Relationsstruktur, die mit der Prioritätsreihenfolge der Vermittlungsinstanzen und den von ihnen jeweils prioritär geförderten Akteurkategorien korrespondiert, angepasst wird, ließe sich dieses, anhand der Abweichungs- bzw. der Kernsequenz aller vier Relationsstrukturen vorgestellte Muster auf alle Relationsstrukturen übertragen. Das heißt also, dass jede Stufe der Anpassung der Zirkulation in den Sequenzen von einer Relationsstruktur nicht nur mit der Einführung eines vom herrschenden Hierarchieprinzip abweichenden Hierarchieprinzips einhergeht, das wiederum ausgehend von der Sequenz, in der gerade von der mit dieser Sequenz assoziierten Vermittlungsinstanz die Anpassung der Zirkulation vorgenommen wird, implementiert wird. Es heißt vielmehr auch, dass jede Stufe der Anpassung der Zirkulation gleichsam mit einer diesem Hierarchieprinzip entsprechenden Umverteilung der Zirkulationsmöglichkeiten zwischen den Akteurkategorien korrespondiert, und zwar in dem Maße, wie die allgemeine Zirkulation einer Relationsstruktur entlang der sequentiellen Ordnung dieser Relationsstruktur angepasst zirkuliert.

Dieses Muster der Priorisierung von Akteuren bestimmter Kategorien informiert allerdings nicht nur darüber, welche Akteurkatagorien in einer Relationsstruktur im Vergleich zu anderen Akteurkategorien derselben Relationsstruktur im Falle einer stabilen Zirkulation der Akteure für die Bewahrung der Zirkulation von besonderer Relevanz sind und wie die sukzessive Förderung nicht-priorisierter Akteurkatgorien zur Stabilisierung der Zirkulation in einer Relationsstruktur beiträgt. Es informiert darüber hinaus auch über die Soziabilitätsnetzwerke, die in Relationsstrukturen zwischen Akteurkategorien gebildet werden bzw. auf Basis strategischer wie emotionaler Wahlverwandtschaften entstehen, die Bourdieu in seiner Anatomie des Geschmacks entlang seines Machtansatzes rekonstruiert [@Bourdieu 2012, 373ff.]. Bevor wir allerdings auf diese Soziabilitätsnetzwerke eingehen können, gilt es voran zu schicken, dass die in jeder Relationsstruktur im Falle stabiler Zirkulation priorisierten Akteurkategorien nicht vollständig mit den Akteurkategorien übereinstimmen, aus denen wiederum die Soziabilitätsnetzwerke bestehen [@PapilloudSchultze2022, 306]. Dies rechtfertigt sich damit, dass von den zwei priorisierten Akteurkateggorien einer jeden Relationsstruktur eine unterschiedlich starke Wirkung auf die Bewahrung der Zirkulation in ihrer Relationsstruktur ausgeht. So übten die jeweils vorrangig priorisierten Akteurkategorien jeweils die unmittelbar stärkste Bewahrungsmacht auf die Zirkulation ihrer Relationsstruktur aus, während jeweils die zweite priorisierte Akteurkategorie einer jeden Relationsstruktur lediglich mittelbar zur Bewahrung der Zirkulation in ihrer Relationsstruktur beitragen. Entsprechend bilden sich im Umfeld der mittelbar priorisierten Akteurkategorie und im Umfeld der unmittelbar priorisierten Akteurkategorie einer jeden Relationsstruktur jeweils separate, eigene Soziabilitätsnetzwerke heraus, wobei dasjenige im Umfeld der unmittelbar priorisierten Akteurkategorie einer jeden Relationsstruktur das mächtigste Soziabilitätsnetzwerk darstellt. Die mächtigsten Soziabilitätsnetzwerke in den vier Relationsstrukturen wären allerdings keine Netzwerke im hier gemeinten Sinne, wenn sie neben den unmittelbar priorisierten Akteurkategorien nicht auch diejenigen Akteure umfassten, die mit der Zirkulation der unmittelbar priorisierten Akteurkategorie direkt assoziiert sind. Diese Akteure sind zumeist aus der sekundär bzw. mittelbar priorisierten Kategorie in die primär priorisierte Kategorie zirkuliert und besetzen dort eine Anwärterposition auf die Weiterzirkulation in den oder zwischen den Sequenzen innerhalb ihrer Relationsstruktur, weshalb sie für die Erneuerung der privilegierten Akteurkategorie unverzichtbar sind. Entsprechend bestehen die wichtigsten Soziabilitätsnetzwerke in jeder Relationsstruktur zuvorderst aus den Akteuren der unmittelbar priorisierten Akteurkatagorie und nachrangig aus den Nachrückern aus der mittelbar priorisierten Akteurkategorie (vgl. ebd., 310, Tab. 7.1), die maßgeblich zur Erneuerung, zum Fortbestand und ggf. zur Neukonstitution der privilegierten Akteurkategorie beitragen, weshalb Soziabilitätsnetzwerke prinzipiell zum Vorteil der darin unmittelbar priorisierten Akteurkategorie gereichen [vgl. am Beispiel einer Forschungseinrichtung @PapilloudSchultze2023, 127]. Wie bereits angeklungen ist, verfügt jede Relationsstruktur jedoch nicht nur über ein besonders mächtiges Soziabilitätsnetzwerk, sondern über insgesamt vier Netzwerke, deren Bedeutung für die Bewahrung der Zirkulation jedoch im Falle einer stabilen Zirkulation sukzessiv entlang der sequentiellen Ordnung ihrer Relationsstruktur abnimmt [@PapilloudSchultze2022, 309]. Nichtsdestotrotz sind auch diese weniger mächtigen Soziabilitätsnetzwerke insofern für die Bewahrung der Zirkulation von Bedeutung, als sie entlang der Anpassung der Zirkulation aufgrund der durch die Anpassung erfolgenden Umverteilung von Zirkulationsmöglichkeiten sukzessiv an Stärke gewinnen und so schrittweise zu Lasten der ihnen temporär zufallenden Bewahrungsmacht zur Neukonstitution des mächtigsten Soziabiltätsnetzwerkes, ohne das keine Re-Stabilisierung der Zirkulation in einer Relationsstruktur möglich ist, beitragen. Aus diesem Grund, d. h. je nach Stabilität oder Anpassung der Zirkulation, wirken Soziabilitätsnetzwerke auf die Akteure als Kontexte sowohl der Eröffnung als auch der Schließung von Zirkulationsmöglichkeiten und -wegen, was wiederum den Widerstand der Akteure _für_ und _gegen_ die Relationsstruktur bzw. die Sequenz, in der sie sich jeweils befinden, mitdeterminiert.

Dieser Punkt führt uns schließlich zur fünften und letzten Folge, die sich aus den oben vorgestellten Grundlagen der Theorie der Relation für empirische Untersuchungen ergibt und im Speziellen die Bedeutung umverteilender Vermittlungsinstanzen in allen Relationsstrukturen und ihre Rolle in Bezug auf die unvermeidliche soziale Ungleichheit unter den Akteuren betrifft [@PapilloudSchultze2022, 311]. Diesbezüglich sei zuerst erwähnt, dass die Arbeit umverteilender Vermittlungsinstanzen -- im Unterschied zu Instanzen, die auf der Ebene der Relationsstruktur, ihrer Sequenzen oder Teilsequenzen tätig sind und auf jeder dieser Ebenen ihren unmittelbaren Einfluss auf die Reziprozität in ihrer Relationsstruktur zu bewahren suchen (vgl. ebd., 244) -- vorrangig auf die Umverteilung von vertikalen wie horizontalen Zirkulationsmöglichkeiten unter den Akteuren in einer Relationsstruktur gerichtet ist. Ihre Hauptaufgabe besteht deshalb ungeachtet der jeweiligen Relationsstruktur in der Entwicklung formaler Verfahren der Umverteilung und der Institutionalisierung der entwickelten Regeln der Umverteilung, die dann wiederum von den anderen Instanzen, die sich primär mit den Akteuren in einer Relationsstruktur beschäftigen, je nach Ebene der Vermittlungsstruktur umgesetzt werden (ebd.). Insofern besteht die Stärke umverteilender Vermittlungsinstanzen darin, dass sie die anderen Instanzen nicht nur auf die unabänderliche soziale Ungleichheit zwischen den Akteuren hinweisen, sondern zugleich kompensatorische Verfahrenslösungen ausarbeiten, mit denen die zuständigen Instanzen dann die Akteure optimaler adressieren und ihre Zirkulationsmöglichkeiten wirksamer regulieren können, was wiederum ihren unmittelbaren Einfluss auf die Reziprozität in ihrer Relationsstruktur bewahrt (vgl. ebd., 311). Solche Verfahren können jedoch die soziale Ungleichheit unter den Akteuren nicht vollständig und dauerhaft beheben, sie tragen aber dazu bei, diese zumindest temporär, d. h. kurz- oder mittelfristig, abzumildern. Dies erklärt sich damit, dass keine Vermittlungsinstanz die Reziprozität in einer Relationsstruktur direkt zu beeinflussen imstande ist und umverteilende Instanzen zudem einzig und allein formale Lösungsverfahren konzipieren, deren Umsetzung in den Händen der anderen Instanzen liegt (vgl. ebd., 244-245). Nichtsdestoweniger sind umverteilende Vermittlungsinstanzen unverzichtbarer Bestandteil einer jeden Relationsstruktur, weil sie als Instanzen der Optimierung maßgeblich zur Erarbeitung, Institutionalisierung und Effektivität formaler Verfahren der Umverteilung von Akteuren beitragen und entlang dieser Einflusssphäre die Reziprozität und Zirkulation ihrer Relationsstruktur mitgewährleisten.

### Schluss

Anhand der in diesem Beitrag vorgestellten theoretischen Grundlagen der Theorie der Relation und der sich daraus ergebenden dynamischen Folgen ist unmittelbar einzusehen, dass die Theorie der Relation konsequent als eine Soziologie _durch_ Relation entwickelt wurde, deren Ausformulierung und Systematisierung streng dem Primat der Zirkulation als erstrangiges Startifikationsprinzip folgt. Vom Standpunkt der Theorie der Relaion bringt dies für die soziologische Theoriebildung im Bereich der relationalen Soziologie zwei wesentliche Vorzüge: Zum einen bietet sie eine _quasi-realistische_ Perspektivierung der sozialen Welt an, die sich abseits einer Ontologie der Relation bewegt und somit nicht Gefahr läuft, Akteure, Vermittlungsinstanzen, Tätigkeiten und Tätigkeitsbereiche, Aktanten sowie symbolische und formale Medien _als_ Relation zu substantialisieren. Zum anderen bietet sie aber ebenso eine _formal neostrukturalistische_ Perspektivierung an, in der der Terminus Relation als Makrobegriff entwickelt wird, der wiederum in seiner zirkulationstheoretischen Konzeption der Dynamik und Pluralität unterschiedlichster sozialer Lebenswirklichkeiten Rechnung trägt. Somit besteht ein weiterer Vorzug der Theorie der Relation darin, dass sie einen strukturierten Rahmen bietet, in dem erstens Makroprozesse und -netzwerke bzw. Zusammenstellungen und Bewegungen von Kollektiven nicht einzig als Produkte der Organisation von Mikrointeraktionen, Transaktionen, Handlungsinterdependenzen oder (in)formalen Beziehungen rekonstruiert bzw. modelliert werden, ohne dabei gleichzeitig die "strukturierende Kraft" von Relation [@Emirbayer2008, 9] oder die Arbeit von Akteuren einerseits und von Vermittlungsinstanzen andererseits in ihrer Kontextgebundenheit und ihrer mittelbaren Einflussnahme auf die Relationsstrukturen, ihre Zirkulation, ihre Reziprozität etc. in Abrede zu stellen. Vielmehr inkludiert die Theorie der Relation die Pluralität und Dynamik der Lebensformen, indem sie abseits von der Existenz einer einzigen _idealen_ Relation von der grundlegenden Einsicht ausgeht, dass wir alle tagein tagaus, experimentell und quasi zwangsläufig von einer Relation abweichen; eine Feststellung, die keineswegs pejorativ zu verstehen ist, sondern im Rahmen der Theorie der Relation zirkulationsanalytisch erschlossen und -- wie gezeigt -- anhand des Primats der Zirkulation systematisiert wurde.

Die Art und Weise wiederum, wie und inwiefern von einer Relation abgewichen wird, haben wir anhand von vier Relationsstrukturen, die als kanonische Formen der Abweichungen von einer _idealen_ Relation zu behandeln sind, plausibilisiert. Zudem haben wir die Folgen solcher Abweichungen für die sequentielle Ordnung und Strukturierung der vier Relationsstrukturen herausgehoben, die jeder Relationsstruktur ein eigenes Profil unter Rekurs auf die Abweichungs- bzw. der Kernsequenz der entsprechenden Relationsstruktur verleiht. Wie gezeigt wurde, bestimmt dieses Profil nicht nur den Verlauf der allgemeinen Zirkulation entlang des Wechselspiels zwischen Position und Relation, sondern ebenso die Art und Weise der sozialen Arbeit der Akteure an und im Umgang mit relationalen Ereignissen sowie deren Widerstandsverhältnis _für_ und _gegen_ die Relationsstruktur und deren Sequenzen und die daraus resultierenden Zirkulationsmöglichkeiten für Akteure innerhalb und zwischen Relationsstrukturen. Daneben determiniert das kernsequenzspezifische Profil einer jeden Relationsstruktur aber auch die Prioritätsreihenfolge der Arten von Vermittlungsinstanzen, deren Vermittlungs- und Formalisierungsarbeit sowie die Durchsetzung und Unterstützung des herrschenden Hierarchieprinzips im Falle stabiler Zirkulation oder die stufenweise Durchsetzung nicht-herrschender Hierarchieprinzipien entlang der Kaskadenwirkung der Stärkung und Schwächung von Vermittlungsinstanzen im Falle destabilisierter Zirkulation. Darüber hinausgehend haben wir ebenfalls die Folgen dieses Profils für die Reziprozität, deren je nach Relationsstruktur variierende Kernbedeutung sowie die darauf beruhende Bedeutung der Legitimität skizziert und im Zusammenhang mit der sozialen Ungleichheitsproblematik beleuchtet. Im Anschluss daran wir erklärt, dass das Profil einer jeden Relationsstruktur mit der Priorisierung von Akteuren bestimmter Kategorien und der Bildung mächtiger Soziabilitätsnetzwerke konvergiert, wobei diese Priorisierung im Falle der Anpassung der Zirkulation neu-dimensioniert wird und zwar so lange, bis die Erneuerung oder Neukonstitution der priorisierten Akteurkategorie und mithin des damit mittelbar verknüpften Soziabilitätsnetzwerkes ihren Abschluss findet. Und schließlich haben wir auf die überragende Bedeutung umverteildender Vermittlungsinstanzen sensibilisiert, die stets mit der Nachjustierung und Optimierung der formalen Verfahren der anderen Instanzen beschäftigt sind und auf diese Weise zu wichtigen Bewahrungsinstanzen einer jeden Relationsstruktur generieren.

Einen Punkt, der ebenfalls durch das Profil einer Relationsstruktur determiniert wird und unmittelbar mit den Vermittlungsinstanzen von Relationsstrukturen verbunden ist, soll nun abschließend thematisiert werden: Die Rede ist von Satellisierungsstrategien, mit deren Hilfe Vermittlungsinstanzen ihre Einflusssphäre innerhalb und zwischen Relationsstrukturen zu entwickeln suchen, um nicht zuletzt ihre Reziprozitätsmacht gegenüber den anderen Relationsstrukturen zu festigen und ggf. auszudehnen.








<!--
Hier würde ich die folgenden Punkten verallgemeinern kommentieren, die wir im Kap. 7 der TR erwähnen, und zwar:

Priorisierung von Akteurkategorien, Anpassung und Hierarchieprinzipien (vielleicht ein allgemeiner Punkt 'Hierarchien')

Reziprozität und Legitimität

Ungleichheiten und Umverteilung

Mögliche Argumentationslinie: Investition in die Durchsetzung von Reziprozitätsstrukturen, die alle anderen Strukturen der Rezirprozität mit dem Ziel repräsentieren, materialisieren und attraktivieren können, die Vielfalt von Zirkulationen (und damit von Akteuren, Aktanten und Vermittlungsinstanzen) ausdrücken zu können; weil aber jede Relationsstruktur die Pluralität von Zirkulation immer aufgrund ihr Hauptmerkmal aufgreift und durchsetzt, führt diese Verbreitung von Relationsstrukturen zum Kampf zwischen Pluralitäten, davon sich ihre Zuspitzungen in Meta-Relationsstrukturen ergeben.




<!--
Andererseits heißt das aber auch, dass dieselbe sequentielle Etablierung von Relationsstrukturen nach den Sequenzen Investition, Repräsentation, Materialität und Attraktivität in einer zirkulationsdynamischen Perspektive deshalb zu kurz greift, weil sie nicht in jeder Relationsstruktur in derselben Prioritätsordnung mobilisiert werden. Das bedeutet wiederum, dass jede Relationsstruktur nicht nur über ihr eigenes Hauptmerkmal verfügt, sondern auch eine mit diesem Merkmal korrespondierende Sequenz der sozialen Arbeit besonders priorisiert, die dann wiederum als Ausgangspunkt der sequentiellen Ordnung einer jeden Relationsstruktur fungiert und sich sowohl in einer jeweils unterschiedlichen Anordnung der Sequenzen der sozialen Arbeit als auch in der Entwicklung der allgemeinen Zirkulation entlang dieser Sequenzen niederschlägt. Wenn wir uns nun den Vermittlungsinstanzen und deren Differsifizierung zuwenden, so lässt weiter ausführen, dass zwar in jeder Relationsstruktur in Korrespondenz zu deren sequentieller Etablierung alle Arten von Vermittlungsinstanzen vorhanden sind, diese unterschiedlichen Arten von Vermittlungsinstanzen aber nicht die gleiche Priorität aufweisen, weil die Priorität einer bestimmten Art von Vermittlungsinstanz unmittelbar mit derjenigen Sequenz verbunden ist, die als Ausgangspunkt der sequentiellen Ordnung einer Relationsstruktur fungiert. Damit einhergehend ließe sich fortführen, dass in ähnlicher Weise, wie aus der je spezifischen sequentiellen Ordnung einer Relationsstruktur die Entwicklung der allgemeinen Zirkulation dieser Relationsstruktur resultiert, sich auch die Vermittlungsinstanzen nach der Zirkulation voneinander unterscheiden, und zwar je nachdem, wie diese Zirkulation in ihrer Ausgangssequenz gegeben ist. Entsprechend kann die Ausgangssequenz, die in der Theorie der Relation auch als Kernsequenz bezeichnet wird, weil an diesem Punkt die allgemeine Zirkulation einer jeden Relationsstruktur beginnt und endet und ohne sie keine Zirkulation zustande kommt, als Grundlage zur Bestimmung der Arten von Vermittlungsinstanzen herangezogen werden. Beginnen wir mit der Kernsequenz.

In der ersten Relationsstruktur stellt die Sequenz Investition die Kernsequenz dar, in der zweiten die Sequenz Repräsentation, in der dritten die Sequenz Materialität und in der vierten Relationsstruktur stellt die Sequenz Attraktivität die Kernsequenz dar. Jede dieser vier Kernsequenzen ist mit einer bestimmten Ebene der Vermittlungsstruktur von Vermittlungsinstanzen verknüpft, weshalb die Bewahrung und Verbreitung dieser Ebene der Vermittlungsstruktur jeweils auch mit einer bestimmten Art von Vermittlungsinstanz assoziiert ist. So adressieren die relationsstrukturspezifischen Vermitlungsinstanzen die kernsequenzspezifische Bedeutung der ersten Relationsstruktur, die sequenzspezifischen Vermittlungsinstanzen die kernsequenzspezifische Bedeutung der zweiten Relationsstruktur und die teilsequenzspezifischen bzw. die umverteilenden Vermittlungsinstanzen adressieren die kernsequenzspezfische Bedeutung der dritten bzw. der vierten Relationsstruktur. Weil also in jeder Relationsstruktur die allgemeine Zirkulation nach denselben vier Sequenzen entwickelt wird, weisen alle Relationsstrukturen alle vier Arten von Vermittlungsinstanzen auf. Da allerdings jede Relationsstruktur über eine ihr eigene Kernsequenz verfügt, die für die Entwicklung der allgemeinen Zirkulation in ihrer sequentiellen Ordnung unerlässlich ist, kommt der mit dieser Kernsequenz verbundenen Art von Vermittlungsinstanz eine Priorität im Vergleich zu den anderen Arten von Vermittlungsinstanzen zu und da dieser prioritären Art von Vermittlungsinstanz nicht nur die Aufrechterhaltung der allgemeinen Zirkulation ihrer Relationsstruktur, sondern auch die Unterstützung des Hauptmerkmals ihrer Relationsstruktur obliegt, bildet diese Art schließlich das Schwerkraftzentrum einer Relationsstruktur. Das heißt jedoch nicht, dass die anderen Arten von Vermittlungsinstanzen, die entsprechend der sequentiellen Ordnung der allgemeinen Zirkulation von einer Relationsstruktur auf die Kernsequenz folgen, für eine Relationsstruktur verzichtbar wären. Im Gegenteil, denn jede Art von Instanz kommt eine besondere Bedeutung in Bezug auf die Förderung der Zirkulation aller Akteure in einer Relationsstruktur zu, weshalb keine Relationsstruktur auf eine Ebene ihrer Vermittlungsstruktur verzichten kann, selbst wenn diese Ebenen der Ebene der Kernsequenz nachgeordnet sind und sich ihre spezifische Bedeutung unter stetiger Bezugnahme auf die Kernsequenz ergibt.

-->





### Bibliographie
