---
title: "Die Suche nach Eindeutigkeit und die Macht der Päpste"
indent: true
output:
    html_document: default
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Zwischen den Aufregungen um die Abaya in Frankreich und dem Streben nach der politischen Macht von Päpsten der katholischen Religion im Mittelalter gibt es für den externen Beobachter wahrscheinlich kaum Gemeinsamkeiten. Im ersten Fall sprechen wir von einer weiblichen Bekleidung in der Form von einem langen Gewand, die aus der arabischen Welt stammt und außer Gesicht und Hände alles bedeckt. Im zweiten Fall sprechen wir von der langen Geschichte des Kampfes für die Macht und ihre Ausübung auf allen Ebenen des spirituellen sowie des weltlichen Lebens zwischen Päpsten, Kaisern, Königen und Adeligen. Der erste Fall ist im Laufe des Jahres 2023 immer mehr von den Medien aufgegriffen worden, weil in diesem Jahr die französische Regierung durch ihren neu ernannten Bildungsminister Gabriel Attal die Abaya in der Schule verboten hat [vgl. illustrativ etwa @Ayad2023; @Libe2023; @Fig2023; auch in Deutschland @Tagesspiegel2023; @Zeit2023; @FAZ2023]. Nach dem französischen Bildungsministerium sei die Abaya keine bloße modische Kleidung, die häufiger von jungen Mädchen mit arabischem Migrationshintergrund in Frankreich in der Öffentlichkeit getragen werde. Sie sei vielmehr ein religiöses Symbol des Islam, das nach der französischen Regierung ebenso auch einer Form vom radikalen religiösen Militantismus dienen könnte und zudem seit 2004 wie andere ostentativ getragene religiösen Symbole in der Öffentlichkeit als verboten gelte [vgl. dazu das französische Rundschreiben @BO2004]. Der zweite Fall besetzt deutlich weniger Platz in den Medien und scheint uns zu einer langen Vergangenheit zu führen, von der wir glauben würden, dass wir uns von dieser definitiv entfernt hätten.

<<<<<<< Updated upstream
Beide Fälle konvergieren jedoch zu einer Besonderheit der Verhältnisse zwischen Politik und Religion, die in Frankreich mit dem Wort _laïcité_ gekennzeichnet ist. In der deutschen Übersetzung wird dieser Begriff häufig mit dem Begriff des Laizismus wiedergegeben, selbst wenn er auf der Ebene der Säkularisierung die komplexen Wechselbeziehungen zwischen Politik und Religion zu reduzieren tendiert, davon die _laïcité_ ein der Symbolen ist. Die Polemik um die Abaya gibt der französischen politischen Macht eine Gelegenheit, die Bedeutung der Formalisierungsoperationen von politischen Instanzen im Bereich der _laïcité_ hervorzuheben. Es wird darauf aufmerksam gemacht, dass das gesetzliche Apparat zur _laïcité_ seit der Kopftuch-Affäre von 1989 regelmäßig justiert wurde (1989, 1993, 1994 und schließlich 2004; vgl. ebd.). In Unterstützung des Gesetzes sind entsprechende politischen Instanzen der (Um)Verteilung aktiv gewesen, die an der Untersuchung von religiösen Symbolen insbesondere hinsichtlich der Art und Weise gearbeitet haben, wie sie in der Gesellschaft von unterschiedlichen Akteuren und Kollektivakteuren verwendet werden. Ein Beispiel ist der _Observatoire de la laïcité_ (2013-2021). Einer Initiative vom Präsidenten Jacques Chirac folgend (2003), arbeitet der _Observatoire_ im Dienst der französischen Regierung, und er beobachtet und bewertet solche Symbolen. Zu diesem Zweck führt er Untersuchungen zur _laïcité_ in Frankreich durch, die in der Form von Berichten und Informationsbrochüren veröffentlicht werden. Er formuliert Empfehlungen an die Regierung, und er trägt somit dazu bei, dass die von der französischen Regierung geprägte Auffassung der _laïcité_ in der Öffentlichkeit weiterhin präsent bleibt. Aber selbst in der politisch-orientierten Relationsstruktur, in der die Arbeit von solchen umverteilenden Instanzen an der Attraktivität der Repräsentation zur Entwicklung und Unterstützung der Legitimität der politischen Macht essentiell ist, kommen solche Instanzen an ihre Grenzen. Weil der _Observatoire_ verdächtigt wird, durch seine Untersuchungen insbesondere muslimische Gemeinschaften übertrieben positiv in ihrem Umgang mit religiösen Symbolen zu bewerten, wird er abgebaut. Er wird von einer interministeriellen Kommission ersetzt, die nur noch dafür sorgen muss, dass die Gesetze zur _laïcité_ berücksichtigt werden.

In Verbindung mit der Errichtung vom _Observatoire_ und seinem Abbau zeigt sich an diesem Beispiel, wie wichtig und schwierig die Frage der _laïcité_ für die französische Regierung ist. Wenn es um die _laïcité_ geht, führen die Debatten unvermeidlich zur Frage der Legitimität der politischen Repräsentation der _laïcité_ und derer Gewährleistung durch die französischen Regierung aus dem Hintergrund von der langen Geschichte der Auseinandersetzungen zwischen Politik und Religion in Frankreich [vgl. dazu etwa @cpb87, @cpb87b bes. im Kontext des Protestantismus und der Konflikte mit katholischen Bewegungen]. Deshalb ist es nicht überraschend, dass bei Störungen oder Schwächungen im institutionellen Umgang mit der _laïcité_ die Debatten fast unvermeidlich zur Hinterfragung der Legitimität der französischen Regierung münden. Hinter diesem besonderen Beispiel steckt allgemeiner die Auseinandersetzung zwischen zwei Relationsstrukturen bzw. zwei Ordnungsprinzipien von Verhältnissen zur materiellen und spirituellen Existenz, die ein Fallbeispiel aus der Geschichtsforschung zu den Konflikten zwischen Päpsten, Kaisern, Königen und adeligen Familien vor und kurz nach der gregorianischen Reform zu verdeutlichen erlaubt. Mit einem solchen Fallbeispiel geht es uns insbesondere darum, einen Punkt der Theorie der Relation zu illustrieren, der die Einflussstrategien zwischen Relationsstrukturen und zwischen Instanzen in diesen Relationsstrukturen betrifft. In unserem Fall sind es für die katholische Religion die soziokulturell-orientierte Relationsstruktur und für die Politik die politisch-orientierte Relationsstrukturen. Zwischen den Päpsten, den Kaisern, den Königen und den Adeligen geht es wie heute am Beispiel der Abaya in Frankreich um die Verfestigung und die Verbreitung der eigenen Relationsstruktur als Durchsetzung von einem besonderen Ordnungsprinzip von Verhältnissen, die die Akteure zu sich selbst, zu den anderen, zu Kollektivakteuren und zu Aktanten bzw. Mediationen im Laufe ihrer Arbeit an relationalen Ereignissen entwickeln. Dabei werden Akteure von Instanzen dieser Relationsstrukturen auf entsprechende Zirkulationswege gebracht, die weitere Zirkulationsmöglichkeiten generieren und insgesamt die Tätigkeitsbereiche in Relationsstrukturen und diese Relationsstrukturen selbst stärken.

Im Vergleich zu den anderen Kapiteln befinden wir uns hier in einer Zeit, in der schon etwa aufgrund der Demographie und der wirtschaftlichen Lebensbedingungen sowohl die soziokulturell-orientierte Relationsstruktur als auch die politisch-orientierte Relationsstruktur weniger als heute stratifiziert sind bzw. weniger Akteure, Instanzen und Zirkulationswege sowie Zirkulationsmöglichkeiten aufweisen. Zudem ist in dieser Zeit die Entwicklung von solchen Zirkulationswegen häufig langwierig, und solche Wege bleiben meistens brüchig. Dies spricht einerseits für die im Vergleich zu unseren Zeiten wenige Eindeutigkeit der Relationsstrukturen und derer Instanzen, was die Sozialisation der Akteure in diesen Relationsstrukturen erschwert und zu schwierigen Prozessen der Legitimation durch Einschreibung dieser Akteure in Relationsstrukturen führt. Andererseits trägt diese schwache Eindeutigkeit von Relationsstrukturen dazu bei, die Entwicklung von Akteurstrategien in den Vordergrund zu bringen, die darauf abzielen, die allgemeine Zirkulation in den jeweiligen Relationsstrukturen zu organisieren und zu institutionalisieren. Zwar operieren diese Akteure nicht allein. Aber die Mobilisation von anderen Akteuren, die eine solche Arbeit an der Produktion von Kollektivakteuren und von Instanzen zur Unterstützung von Legitimationsprozessen in Relationsstrukturen voraussetzt, ist häufig mit viel Zeit und Aufwand verbunden. Wenn sie gelingt, gewährleistet sie nicht unbedingt die Langlebigkeit dieser Instanzen. Was die Geschichtsforschung hier abbildet, ist eine komplexe Verflechtung von Blockaden und Satellisierungen, die häufig auf der Ebene von Einzelvertretern von Vermittlungsinstanzen personifiziert werden, die im Laufe der Jahrhunderte zur Behauptung von zwei Relationsstrukturen beitragen, die sich immer fester voneinander unterscheiden werden. Ziel in diesem Kapitel ist es nicht, diese Entwicklung vollständig zu erklären, sondern einen ihrer Schlüsselmoment um die Päpste der katholischen Religion vor und kurz nach der gregorianischen Reform zu adressieren.

## Verortung -- Kaiserkrönung und kirchlicher Widerstand.

Dass Relationsstrukturen strukturell nicht eindeutig unterschieden werden können, ergibt sich in der Theorie der Relation daher, dass Relationsstrukturen von gleichen Sequenzen strukturiert sind, die im Laufe von Abweichungen von einer idealen Relation sowie von anderen Relationsstrukturen als eine andere Anordnung von diesen Sequenzen an einem jeweils unterschiedlichen Pukt abweichen. Der Punkt, an dem die Relationsstrukturen abweichen, definiert das Hauptmerkmal von einer Relationsstruktur und ihre Kernsequenz, das als Grundlage zur Sozialisation auf diese Relationsstruktur und entsprechend als Verortungsmerkmal der unterschiedlichen Tätigkeitsbereichen gilt, die sich in Relationsstrukturen entwickeln. Dass die Religion in der soziokulturell-orientierten Relationsstruktur entwickelt wird, ergibt sich daraus, dass in dieser Relationsstruktur die Investition in die Relation die Kernsequenz darstellt und das Hauptmerkmal dieser Relationsstruktur bezeichnet. Bei der Investition in die Arbeit an relationalen Ereignissen geht es hier grundsätzlich und vor allem um die Relation selbst als unendliches Horizont und Grundmotivation von einer solchen Arbeit, dass etwa der Glaube und das Leben nach Glaubensüberzeugung in der Religion symbolisiert [vgl. @Starck2000]. Dies bedeutet gleichzeitig nicht, dass die anderen Sequenzen der Repräsentation, der Materialität und der Attraktivität der Religion unwichtig wären. Diese Anmerkung gilt ebenfalls _ceteris paribus_ für die politische Macht und ihre Verankerung in einer politisch-orientierten Relationsstruktur. Sie wird um die Kernsequenz der Repräsentation als Horizont und Grundmotivation der Vertretung von Kollektiven durch Machtakteure entwickelt, was gleichzeitig nicht bedeutet, dass die anderen Sequenzen in dieser Relationsstruktur unbedeutsam wären. In der Religion wie in der Politik sind diese Sequenzen deshalb wichtig, weil sie den Bereich durch die Unterstützung der allgemeinen Zirkulation von Akteuren in die Sequenzen der jeweiligen Relationsstrukturen stärken. Dass eine solche Zirkulation nicht von selbst gebildet wird, hängt jedoch nicht nur von Merkmalen, die den Relationsstrukturen intern wären -- wie etwa die Schwierigkeiten bei der Entwicklung von Zirkulationswegen aufgrund von fehlenden Akteuren und Instanzen, die solche Wege bahnen und Zirkulationsmöglichkeiten entwickeln könnten. Der Einfluss von Relationsstrukturen aufeinander führt auch zu Schwächungen oder Störungen der allgemeinen Zirkulation in Relationsstrukturen, und er trägt dazu bei, Uneindeutigkeit zu begünstigen. Unser Fall der Päpste der katholischen Religion vor und kurz nach der gregorianischen Reform liefert ein gutes Beispiel davon.

Wenn Relationsstrukturen nicht eindeutig sind, dann ist die Mobilisation von Akteuren nicht einfach, was die Arbeit an relationalen Ereignissen erschwert. Eine solche Situation findet man nach Karl der Große mit seinen Nachfolgern von Otto I. zu Otto II., Otto III., Heinrich VI., Friedrich II. und Heinrich VII., wenn diese Könige nach Rom reisen, um vom Papst gekrönt und der Tradition folgend als Kaiser ernannt zu werden. Diese Praxis, die sich im Übergang vom Karolingerreich zum Heiligen Römischen Reich durchsetzt, basiert auf die Anerkennung einer Teilung der Mächte zwischen Politik und Religion, die als Produkt aus der Zusammenarbeit zwischen Päpsten und Kaisern in der Form einer Teilung der Mächte über weltlichen und spirituellen Sachverhalten etabliert wird [@Cavuldak2015, 34-35]. Dass eine solche Verständigung nicht von selbst geht und brüchig bleibt, attestiert vielleicht am Deutlichsten die Asymmetrie dieses Verhältnisses zwischen Päpsten und Kaisern, die sich daran zeigt, dass die Kaiser _in fine_ das Sagen behalten sollten, was die Päpste in der unkomfortablen Lage versetzt, "nicht einmal in der Lage [zu sein], dem oströmischen Kaiser die Vorrangstellung der Kirche auch nur in 'göttlichen Dingen' abzuringen" (ebd., 34).

Diese schwache Position von römischen Päpsten im Vergleich zu den Kaisern im ersten Reich symbolisiert einerseits die Verhinderung der Zirkulation von Päpsten in die Politik durch die politischen Instanzen des Kaisertums. Das beste Beispiel davon liefert die Rekrutierung des kirchlichen hochrangigen Personals und die formale Verfahren, die sie voraussetzt, die vollständig vom Kaisertum satellisiert werden bzw. die unter der Kontrolle des Kaisers fallen. Bischöfe und Geistigen werden zwar von der Kirche vorgeschlagen. Aber sie werden nicht vom Papst, sondern vom Kaiser nominiert. An diesem Beispiel sieht man, wie die Instanzen des Kaisertums durch ihre Satellisierung der Instanzen der katholischen Kirche die Kirche und ihre Instanzen in ihrem Dienst arbeiten lassen. Diese Entwicklung von Satellisierungsstrategien erklärt teilweise, wieso die Praxis der Krönung von Königen zu Kaisern durch den Papst nach Karl der Große zwar etabliert, jedoch nicht unbedingt systematisch so durchgesetzt wird, wie sie formal durchgesetzt werden sollte.
=======
Beide Fälle konvergieren jedoch zu einer Besonderheit der Verhältnisse zwischen Politik und Religion, die in Frankreich mit dem Wort "laïcité" gekennzeichnet ist. In der deutschen Übersetzung wird dieser Begriff häufig mit dem Begriff des Laizismus wiedergegeben, selbst wenn er auf der Ebene der Säkularisierung die komplexen Wechselbeziehungen zwischen Politik und Religion zu reduzieren tendiert, wovon die "laïcité" eines der Symbolen ist. Die Polemik um die Abaya gibt der französischen politischen Macht eine Gelegenheit, die Bedeutung der Formalisierungsoperationen von politischen Instanzen im Bereich der "laïcité" hervorzuheben. Es wird darauf aufmerksam gemacht, dass der gesetzliche Apparat zur "laïcité" seit der Kopftuch-Affäre von 1989 regelmäßig justiert wurde (1989, 1993, 1994 und schließlich 2004; vgl. ebd.). In Unterstützung des Gesetzes sind entsprechende politischen Instanzen der (Um)Verteilung aktiv gewesen, die an der Untersuchung von religiösen Symbolen insbesondere hinsichtlich der Art und Weise gearbeitet haben, wie sie in der Gesellschaft von unterschiedlichen Akteuren und Kollektivakteuren verwendet werden. Ein Beispiel ist der _Observatoire de la laïcité_ (2013-2021). Einer Initiative vom Präsidenten Jacques Chirac folgend (2003), arbeitet der _Observatoire_ im Dienst der französischen Regierung, und beobachtet und bewertet solche Symbole. Zu diesem Zweck führt er Untersuchungen zur "laïcité" in Frankreich durch, die in der Form von Berichten und Informationsbrochüren veröffentlicht werden. Er formuliert Empfehlungen an die Regierung und trägt somit dazu bei, dass die von der französischen Regierung geprägte Auffassung der "laïcité" in der Öffentlichkeit weiterhin präsent bleibt. Aber selbst in der politisch-orientierten Relationsstruktur, in der die Arbeit von solchen umverteilenden Instanzen an der Attraktivität der Repräsentation zur Entwicklung und Unterstützung der Legitimität der politischen Macht essentiell ist, kommen solche Instanzen an ihre Grenzen. Weil der _Observatoire_ verdächtigt wird, durch seine Untersuchungen insbesondere muslimische Gemeinschaften übertrieben positiv in ihrem Umgang mit religiösen Symbolen zu bewerten, wird er abgebaut. Er wird von einer interministeriellen Kommission ersetzt, die nur noch dafür sorgen muss, dass die Gesetze zur "laïcité" berücksichtigt werden.

Sei es in Verbindung mit der Errichtung vom _Observatoire_ oder mit seinem Abbau, zeigt sich an diesem Beispiel, wie wichtig und schwierig die Frage der "laïcité" für die französische Regierung ist. Wenn es um die "laïcité" geht, verweisen die Debatten unvermeidlich auf die Frage der Legitimität der politischen Repräsentation der "laïcité" und deren Gewährleistung durch die französischen Regierung, insbesondere vor dem Hintergrund der langen Geschichte der Auseinandersetzungen zwischen Politik und Religion in Frankreich [vgl. dazu etwa @cpb87, @cpb87b bes. im Kontext des Protestantismus und der Konflikte mit katholischen Bewegungen]. Deshalb ist es nicht überraschend, dass bei Störungen oder Schwächungen im institutionellen Umgang mit der "laïcité" die Debatten fast unvermeidlich zur Hinterfragung der Legitimität der französischen Regierung führen. Hinter diesem besonderen Beispiel steckt allgemeiner die Auseinandersetzung zwischen zwei Relationsstrukturen bzw. zwei Prinzipien der Ordnung von Verhältnissen zur materiellen und spirituellen Existenz, die ein Fallbeispiel aus der Geschichtsforschung zu den Konflikten zwischen Päpsten, Kaisern, Königen und adeligen Familien vor und kurz nach der gregorianischen Reform zu verdeutlichen erlaubt. Mit einem solchen Fallbeispiel geht es uns insbesondere darum, einen Punkt der Theorie der Relation zu illustrieren, der die Einflussstrategien zwischen Relationsstrukturen und zwischen Instanzen in diesen Relationsstrukturen betrifft. In unserem Fall sind es für die katholoische Religion die soziokulturell-orientierte Relationsstruktur und für die Politik die politisch-orientierte Relationsstruktur. Zwischen den Päpsten, den Kaisern, den Königen und den Adeligen geht es wie heute am Beispiel der Abaya in Frankreich um die Verfestigung und um die Verbreitung der eigenen Relationsstruktur als Durchsetzung von einem besonderen Ordnungsprinzip der Verhältnisse, das die Akteure zu sich selbst, zu den anderen, zu Kollektivakteuren und zu Aktanten bzw. Mediationen im Laufe ihrer Arbeit an relationalen Ereignissen entwickeln. Dabei werden Akteure von Instanzen dieser Relationsstrukturen auf entsprechende Zirkulationswege gebracht, die weitere Zirkulationsmöglichkeiten generieren und insgesamt die Tätigkeitsbereiche in Relationsstrukturen und diese Relationsstrukturen selbst stärken.

Im Vergleich zu den anderen Kapiteln befinden wir uns hier in einer Zeit, in der schon etwa aufgrund der Demographie und der wirtschaftlichen Lebensbedingungen sowohl die soziokulturell-orientierte Relationsstruktur als auch die politisch-orientierte Relationsstruktur weniger als heute stratifiziert sind bzw. weniger Akteure, Instanzen und Zirkulationswege sowie Zirkulationsmöglichkeiten aufweisen. Zudem gestaltet sich in dieser Zeit die Entwicklung von solchen Zirkulationswegen häufig langwieriger, was nichts über die Festigkeit dieser Zirkulationswege aussagt, denn sie bleiben meistens brüchig. Dies spricht einerseits für eine im Vergleich zu unseren Zeiten geringere Eindeutigkeit der Relationsstrukturen und deren Instanzen, was die Sozialisation der Akteure in diesen Relationsstruktur erschwert und zu schwierigen Prozessen der Legitimation durch Einschreibung dieser Akteure in Relationsstrukturen führt. Andererseits trägt diese schwache Eindeutigkeit von Relationsstrukturen dazu bei, die Entwicklung von Akteurstrategien in den Vordergrund zu bringen, die darauf abzielen, die allgemeine Zirkulation in den jeweiligen Relationsstrukturen zu organisieren und zu institutionalisieren. Zwar operieren diese Akteure nicht allein, aber die Mobilisation von anderen Akteuren, die eine solche Arbeit an der Produktion von Kollektivakteuren und von Instanzen zur Unterstützung von Legitimationsprozessen in Relationsstrukturen voraussetzt, ist oft langwierig. Wenn sie gelingt, gewährleistet sie nicht unbedingt die Langlebigkeit dieser Instanzen. Was die Geschichtsforschung hier abbildet, ist eine komplexe Verflechtung von Blockaden und Satellisierungen, die häufig auf der Ebene von Einzelvertretern von Instanzen und von Einzelakteuren personifiziert werden, die im Laufe der Jahrhunderte zur Behauptung von zwei Relationsstrukturen beitragen, die sich immer fester voneinander unterscheiden werden. Ziel in diesem Kapitel ist es nicht, diese Entwicklung vollständig zu erklären, sondern einen Schlüsselmoment von dieser Entwicklung zentriert um die Päpste der katholischen Religion vor und kurz nach der gregorianischen Reform zu vertiefen.

## Verortung -- Kaiserkrönung und kirchlicher Widerstand.

Dass Relationsstrukturen strukturell nicht eindeutig unterschieden werden können, ergibt sich in der Theorie der Relation daher, dass Relationsstrukturen von gleichen Sequenzen strukturiert sind, die im Laufe von Abweichungen von einer idealen Relation sowie von anderen Relationsstrukturen als eine andere Anordnung von diesen Sequenzen an einem jeweils unterschiedlichen Punkt abweichen. Der Punkt, an dem die Relationsstrukturen abweichen, definiert das Hauptmerkmal von einer Relationsstruktur und ihre Kernsequenz, das als Grundlage zur Sozialisation auf diese Relationsstruktur und entsprechend als Verortungsmerkmal der unterschiedlichen Tätigkeitsbereiche gilt, die sich in Relationsstrukturen entwickeln. Dass die Religion in der soziokulturell-orientierten Relationsstruktur entwickelt wird, ergibt sich daraus, dass in dieser Relationsstruktur die Investition in die Relation die Kernsequenz darstellt und das Hauptmerkmal dieser Relationsstruktur bezeichnet. Bei der Investition in die Arbeit an relationalen Ereignissen geht es hier grundsätzlich und vor allem um die Relation selbst als unendlicher Horizont und Grundmotivation von einer solchen Arbeit, wie sie etwa der Glaube und das Leben nach Glaubensüberzeugung in der Religion symbolisiert [vgl. @Starck2000]. Dies bedeutet gleichzeitig nicht, dass die anderen Sequenzen der Repräsentation, der Materialität und der Attraktivität der Religion fremd oder unwichtig wären. Diese Anmerkung gilt ebenfalls _ceteris paribus_ für die politische Macht und ihre Verankerung in einer politisch-orientierten Relationsstruktur. Sie wird um die Kernsequenz der Repräsentation als Horizont und Grundmotivation der Vertretung von Kollektiven durch Machtakteure entwickelt, was abermals nicht gleichzeitig bedeutet, dass die anderen Sequenzen in dieser Relationsstruktur unbedeutsam wären. In der Religion wie in der Politik sind diese Sequenzen deshalb wichtig, weil sie den Bereich durch die Unterstützung der allgemeinen Zirkulation von Akteuren in die Sequenzen dieser Relationsstrukturen stärken. Dass eine solche Zirkulation nicht von selbst gebildet wird, hängt jedoch nicht nur von Merkmalen ab, die den Relationsstrukturen intern (inhärent) wären -- wie etwa Schwierigkeiten bei der Entwicklung von Zirkulationswegen aufgrund von fehlenden Akteuren und Instanzen, die solche Wege bahnen und Zirkulationsmöglichkeiten entwickeln könnten. Der Einfluss von Relationsstrukturen aufeinander führt auch zu Schwächungen oder Störungen der allgemeinen Zirkulation in Relationsstrukturen, und er trägt dazu bei, Uneindeutigkeit zu begünstigen. Unser Fall der Päpste der katholischen Religion vor und kurz nach der gregorianischen Reform liefert ein gutes Beispiel dafür.

Wenn Relationsstrukturen nicht eindeutig sind, dann ist die Mobilisation von Akteuren nicht einfach, was die Arbeit an relationalen Ereignissen erschwert. Eine solche Situation findet man in der Nachfolge Karl des Großen von Otto I. zu Otto II., Otto III., Heinrich VI., Friedrich II. und Heinrichs VII., wenn diese Könige nach Rom reisen, um vom Papst gekrönt und der Tradition folgend als Kaiser ernannt zu werden. Diese Praxis, die sich im Übergang vom Karolingerreich zum Heiligen Römischen Reich durchsetzt, basiert auf die Anerkennung einer Teilung der Mächte zwischen Politik und Religion, die als Produkt aus der Zusammenarbeit zwischen Päpsten und Kaisern in der Form einer Teilung der Mächte über weltliche und spirituelle Sachverhalten etabliert wird [@Cavuldak2015, 34-35]. Dass eine solche Verständigung nicht von selbst geht und brüchig bleibt, attestiert vielleicht am Deutlichsten die Asymmetrie dieses Verhältnisses zwischen Päpsten und Kaisern, die sich daran zeigt, dass die Kaiser _in fine_ das Sagen behalten sollten, was die Päpste in die unkomfortable Lage versetzt, "nicht einmal in der Lage [zu sein], dem oströmischen Kaiser die Vorrangstellung der Kirche auch nur in 'göttlichen Dingen' abzuringen" (ebd., 34).

Diese schwache Position von römischen Päpsten im Vergleich zu den Kaisern im ersten Reich symbolisiert einerseits die Verhinderung der Zirkulation von Päpsten in die Politik durch die politischen Instanzen des Kaisertums. Das beste Beispiel davon liefert die Rekrutierung des hochrangigen Kirchenpersonals und die formalen Verfahren, die sie voraussetzen und die vollständig vom Kaisertums satellisiert werden bzw. die unter die Kontrolle des Kaisers fallen. Bischöfe und Geistliche werden von der Kirche vorgeschlagen, aber sie werden nicht vom Papst, sondern vom Kaiser nominiert. An diesem Beispiel sieht man, wie die Instanzen des Kaisertums durch ihre Satellisierung der Instanzen der katholischen Kirche die Kirche und ihre Instanzen in ihrem Dienst arbeiten lassen. Diese Entwicklung von Satellisierungsstrategien erklärt teilweise, wieso die Praxis der Krönung von Königen zu Kaisern durch den Papst nach Karl dem Großen zwar etabliert ist, jedoch nicht unbedingt systematisch durchgesetzt wird.
>>>>>>> Stashed changes

Schon ab der Zeit von Otto I. versuchen die deutschen Könige, am besten mit einem von ihnen ausgewählten Papst in Deutschland zum Kaiser gekrönt zu werden [am Beispiel von Otto I., vgl. @Grundmann1967, 10-12]. Diese Strategie gipfelt in der Bestellung von Synoden, um den römischen Papst davon zu überzeugen und die deutschen Fürsten für das Argument zu gewinnen, dass es zum Vorteil der ständigen Besetzung der politischen Macht wäre, die Kaiserkrönung vom Kaisersohn schon zu Lebenszeit des Kaisers und somit gleichzeitig mit der Königskrönung des Kaisersohnes vorzunehmen [siehe die Versuche von Otto I. und Heinrich VI., ebd., 11-12]. Das ein solches Unternehmen nicht von selbst geht, ergibt sich aus der Notwendigkeit, weitere Akteure für diesem Plan zu mobilisieren, was für die Könige und Kaiser des ersten Reiches grundsätzlich bedeutete, die Generationenkette abzusichern, damit der Thron mit einem Kaisersohn ständig besetzt wird. Die Investition von Kaisern und Königen in die Generation kann einerseits als Verfestigung ihrer Macht durch Ebschaft des Kaisertums gesehen werden. Andererseits zielt sie aber auch auf die Verfestigung und die Verdeutlichung der politisch-orientierten Relationsstruktur ab ihrer Institutionen ab, die somit stabilisiert werden können und Einschreibungsprozesse von Akteuren und Instanzen in dieser Relationsstruktur besser -- und in diesem Fall bedeutet dies jenseits des Einflusses der katholischen Kirche -- unterstützen können.

Aber genau bei der Gewährleistung der Produktion von Kaisersöhnen tauchen die ersten Schwierigkeiten auf, die diese Satellisierung der soziokulturell-orientierten Relationsstruktur durch die politisch-orientierte Relationsstruktur destabilisieren: "Immer wieder wurde sie durch den frühen Tod eines Kaisers, ehe er thronfähige Söhne hatte, oder durch das Erlöschen des Königsgeschlechts im Mannesstamm und dadurch bedingten Zwist um die deutsche Thronfolge unterbrochen. Hätten Nachkommen Ottos I. einander auf dem deutschen Thron so ununterbrochen vom Vater auf den Sohn folgen können wie etwa die Kapetinger in Frankreich von 987 bis 1328 [...], ohne Zweifel wäre dann auch das deutsche Königtum faktisch erblich geworden und mit ihm das Kaisertum" (ebd.). Von diesem Generationenproblem profitiert Papst Gregor VII., der seinen unmittelbaren Einfluss auf die kirchlichen Institutionen mit dem Wunsch geltend macht, sie zu stärken, um daraufhin einen mittelbaren Einfluss auf das Kaisertum auszuüben. In dieser Zeit besteigt Heinrich IV. im Alter von sechs Jahren den Thron und wird Kaiser des ersten Reiches, wobei er aufgrund seines Alters seine Macht zuerst nicht persönlich ausübt. Von dieser Angelegenheit profitiert der Mönch Hildebrand, Berater der römischen Päpste und künftiger Papst Gregor VII., um in Abwesenheit einer starken kaiserlichen Macht in der Folge von Papst Leo IX. die Reformen der Kirche voranzubringen. Kirchliche Institutionen, wie die Möglichkeit für die Priester zu heiraten, Kinder zu haben und eine Familie zu gründen, müssen abgebaut werden [@Cochini2006]. Praktiken des Verkaufs von kirchlichen materiellen und immateriellen Gütern oder Funktionen an lokale Herren und Fürsten gelten als verboten und werden stärker bekämpft. Selbst wenn diese Reformen außerhalb von Rom wie in Paris oder in Deutschland zuerst nicht angenommen werden, ziehen sie sich mit der Zeit jedoch durch und erlauben Gregor VII. die Kirche davon zu überzeugen, dass sie sich "mit dem Papst an der Spitze nicht mehr damit [begnügte], über die Amtseinsetzung der Geistlichen zu verfügen und das Sagen in religiösen Belangen zu haben, sondern [...] die Unterordnung der weltlichen Gewalt [verlangte]" [@Cavuldak2015, 35]. Diese starke Position, die Gregor VII. mit dem Ausbau von alten und dem Aufbau von neuen Instanzen der Kirche in Unterstützung seiner Position als Repräsentant der katholischen Kirche bezieht, hat in den Termini der Theorie der Relation weitreichende Folgen.

Auf der Ebene der Einflussstrategien zwischen Relationsstrukturen schwächt Gregor VII. die Satellisierungsstratgie der Könige und Kaiser durch den Abbau und den Aufbau von Instanzen der Kirche, die den Einfluss von Instanzen des Kaisers stärker bekämpfen sollten. Eine unmittelbare Folge daraus, die sich mit dem Ergebnis des Investiturstreites zwischen Gregor VII. und Heinrich IV. ergibt, ist das Recht für die Kirche, Bischöfe und Äbte unabhängig auszuwählen und zu nominieren, selbst wenn Gregor VII. dem Kaiser die Möglichkeit lässt, solchen Wahlen beizuwohnen und in Streitfällen einzugreifen. Eine mittelbare Folge daraus ergibt sich mit der Art und Weise, wie sich Gregor VII. als Purist der Repräsentation der katholischen Kirche darstellt, dessen Repräsentant _par excellence_ der römische Papst sein muss. Diese Verabsolutierung der Repräsentation ist mit dem Wunsch verbunden, Zirkulationsmöglichkeiten für weitere Mitglieder der kirchlichen Elite in die Politik vorzubereiten, in der es vorrangig um die Repräsentation geht bzw. darum, dass die Kirche und der Papst nicht nur als Repräsentanten von katholischen Gläubigen, sondern als Repräsentanten von allen Menschen gelten, die ihnen wie Könige und Kaiser unterworfen wären. Was wie eine bloße Strategie der Eroberung der politischen Macht durch die katholische Kirche aussieht, ist grundsätzlich ein Widerstand _für_ die katholische Kirche, den Gregor VII. als einer ihrer höchsten Repräsentanten im Namen der kirchlichen Kolletive durchzusetzen versucht. Das ein solches Unternehmen schwierig ist, zeigt sich einerseits vor der Zeit von Gregor VII. in Bezug auf die Verhältnisse zwischen Adelsfamilien und Bischöfen und andererseits nach Gregor VII. in Bezug auf die Schismen in der katholischen Kirche.

## Vom Adel zum Bischof

Eine Wirkung des Kampfes von römischen Päpsten für die Repräsentation nicht nur in spirituellen, sondern auch in weltlichen Angelegenheiten, wie noch Bonifaz VIII. mehr als ein Jahrhundert nach Gregor VII. betont (ebd., 37), ist die Destabilisierung der Zirkulationsdynamik in der katholischen Kirche, die die bisherigen Verhältnisse zwischen Religion und Politik und speziell zwischen Adelsfamilien und Religion erschüttert. Zu diesen Verhältnissen, wie sie vor und während der gregorianischen Reformen standen, hat die mittelalterlische Geschichtsforschung beigetragen und sich besonders in ihrer Perspektivierung der Verhältnisse zwischen Adel und Bischöfen erneuert. Nehmen wir das Beispiel der deutschen Geschichtsforschung zu Adelsfamilien und Bischöfen im 10.-12. Jahrhundert. In diesem Zusammenhang herrscht der Ansatz der engen, wenn nicht der Familienbeziehungen zwischen Adel und Bischöfen, wonach die Adelsfamilien die Bischöfe liefern, was zur Voraussetzung führt, dass die Kirche im Dienst der Reproduktion und Verbreitung der Macht von Adelsfamilien arbeitet [vgl. etwa @Prinz1971, @Stormer1973]. Daraus entsteht der Eindruck, dass die Bischöfe aufgrund ihres sozialen Ursprungs treue Diener der politischen Machtinteressen von Königen und Kaisern wären bzw. dass die politisch-orientierte Relationsstruktur die soziokulturell-orientierte Relationsstruktur der Religion vollständig satellisiert hätte. Dieses Argument bleibt jedoch brüchig.

Einerseits sagen die Quellen häufig nichts zum sozialen Ursprung von Bischöfen, und andererseits liefert der Einsatz der genealogisch-besitzgeschichtlichen Methode (Zusammenhang zwischen Besitz, Familienname und Vorname) keinen endgültigen Beleg dafür, dass Bischöfe tatsächlich mit dem Adel verwandt wären [vgl. etwa @Patzold2005, 345-346]. Dies gelte nicht nur für die Verhältnisse zwischen Adelsfamilien und der katholischen Kirche in Deutschland, sondern vermutlich auch europaweit [@Reuter1982]. Dazu wird erwähnt, das eine Reproduktion der Macht durch die Zirkulation von Akteuren aus Adelsfamilien in die katholische Kirche feste Zirkulationswege voraussetzt, die nur dann existieren, wenn die politische Macht ihre Satellisierung der Religion mittel- bis langfristig gewährleisten kann. Dies würde bedeuten, dass die politische Macht von Adelsfamilien und darüber hinaus von Kaisern und Königen stabil genug wäre, um solche Zirkulationswege zu unterstützen. Aber im Hochmittelalter ist es für Könige und Kaiser schwierig, ihren Einfluss und ihre entsprechende Politik sowie politische Projekte langfristig zu entwickeln [vgl. dazu etwa @Althoff1996]. Die politisch-orientierte Relationsstruktur übt also eine Satellisierung der katholischen Kirche aus, aber sie ist nicht in der Lage, eine solche Satellisierungsstrategie auf lange Sicht zu verfestigen. Damit fehlt ihr eine wichtige Bedingung zur Bildung einer vollständig imperialen Kirche.

Zwar entwickeln Adelsfamilien und Bischöfe durchaus enge Wechselbeziehungen, was auch Howe für Europa vom 9. zum 11. Jahrhundert unterstreicht, wenn er feststellt, dass Adelsfamilien -- darunter insbesondere die Hochadelfamilien bzw. die höchste Schicht der Adelfamilie -- massiv in die katholische Kirche investieren: "Adlige besaßen häufig ihre eigenen Kirchen, die sie oder ihre Familien gegründet hatten und in einer Weise regierten, die durch das kanonische Recht legitimiert war. Nach dem Zusammenbruch des karolingischen Reiches wurden die Traditionen der religiösen Aufsicht oft von Grafen und sogar niederen Adligen geerbt, die zu 'Fürsprechern' und 'Beschützern' von Abteien und Bistümern wurden und sie wie Privatkirchen behandelten. Sie vergaben kirchliche Ämter, nahmen Anteile an den Einkünften [...] und kauften, verkauften und vererbten kirchliche Rechte, ohne sich so sehr um die Gefahren der Simonie zu kümmern" [@Howe1988, 320]. Diese Adelfamilien finanzieren die Rekonstruktion oder die Restaurierung von ehemaligen kirchlichen Gebäuden mit bedeutsamen Gaben, und damit unterstützen sie zumindest mittelbar die reformistischen Bewegungen in der katholischen Kirche: "Es ist praktisch unmöglich, eine klösterliche Reformbewegung zu nennen, die in ihrer Entstehung und Ausbreitung nicht der Großzügigkeit des Adels zu verdanken ist" (ebd., 327).

Aber selbst wenn im 10. bis 11. Jahrhundert die Adelsfamilien zunehmend Bischöfe an die katholische Kirche liefern, können diese Bischöfe, wie Howe hervorhebt, nicht allein auf ein Dasein als treue Diener der Machtreproduktion von Adelsfamilien und mittelbar von Königen und Kaisern reduziert werden. Diese Bischöfe handeln im Eigensinn als kirchliche Elite und tragen dementsprechend zur Materialisierung der Repräsentation der katholischen Kirche ganz konkret in Form der Verbreitung ihrer Präsenz in der Form von Gebäuden, vom kirchlichen Personal und bei den rekrutierten Gläubigen auf der lokalen und regionalen Ebenen bei. Daraus ergibt sich, dass der Wechsel der Position im Wechsel der Relationsstruktur bzw. die Zirkulation dieser Akteure von Adelsfamilien der politisch-orientierten Relationsstruktur zu Bischöfen der soziokulturell-orientierten Relationsstruktur mehr als nur eine Verkleidung von Adelmitgliedern ist, die im Gewand des Bischofs Politik betreiben bzw. weiterhin exklusiven politischen Interessen von politischen Machtakteuren dienen würden.

Weitere Argumente dazu liefert etwa die Geschichtsforschung zu Bischofsstädten vom 9. bis zum 11. Jahrhundert. Durch ihre Investition in die katholische Kirche tragen die Bischöfe zur Verfestigung der Repräsentation der katholischen Kirche auf der Ebene von Städten und zu derer Attraktivität für die Bevölkerung bei. Beiträge wie etwa derjenige von Bernhard Jussen zeigen, wie diese Entwicklung einer kirchlichen Macht der Bischöfe lange vor dem 9. Jahrhundert eingesetzt hat, die grundsätzlich aus einer Krise der Legitimität und der Repräsentation entstanden ist. Bischöfe und Adelsfamilien hinterfragen ihre eigene Statusbedeutung, ihre gesellschaftliche Rolle, ihre Selbstwahrnehmung und Selbstvorstellung in der Öffentlichkeit [@Jussen1995], was sie wiederum zu Überlegungen darüber führt, wie die kirchliche Macht zumindest in kleinen Ortschaften in der Praxis besser und eindeutiger erkannt und anerkannt werden kann. Die Forschung etwa von Frank Hirschmann und Steffen Patzold zur Stadtplannung liefert Belege zu einer solchen Arbeit an der Repräsentation der Macht der katholischen Kirche in der Form der Investition der Bischöfe in die Stadtplanung [@Hirschmann1998; @Patzold2002]. So geht es für die Bischöfe z. B. darum, die städtische Infrastruktur zu verbessern, die Struktur der Stadt neu und häufig nach den Modellen der heiligen Städte Rom oder Jerusalem zu konzipieren oder das schwierige Problem des Wassers und der Wasserlieferung (der städtischen Wasserversorgung?) zu lösen. Diese Tätigkeiten der Bischöfe, die weit über die Stadtplannung hinaus bis hin zur Beschäftigung mit dem Kanonrecht und -- mit der Rezeption des römischen Rechtes im Mittelalter -- mit dem römischen Recht reicht, ist auch das notwendige Übel, das mit der Anerkennung und der entsprechenden Legitimation zusammenfällt, die diese Bischöfe für sich zu beanspruchen gedenken. Tatsächlich bleibt aber die Macht der Stadtbischöfe von der Anerkennung dieser Macht durch die Priester und Mönche der katholischen Kirche abhängig, die ihre Bischöfe an ihren Taten messen und ihnen (diesen Taten gegenüber entweder befürwortend im Widerstands _für_ oder ablehnend im Widerstand _gegen_ gegenüberstehen) entsprechend in _für_ oder _gegen_ widerstehen.

Dass eine solche Reziprozität als Träger der Legitimität von Machtakteuren stark geprägt wird, stellt sich nicht nur in Bezug auf die Hierarchie in der katholischen Kirche heraus, sondern auch allgemeiner in Bezug auf die (hoch)mittelalterlische Gesellschaft. So betont Bougard für das 9. Jahrhundert: "Die Elite-Position kann nie endgültig besetzt werden, sondern sie setzt ihre Anerkennung von denen voraus, die dieser Elite nicht angehören, von denen, die die 'Gleichen' oder die Peers sind, und schließlich von der legitimierenden Autorität, wenn es eine gibt" [@Bougard2013, 1082]. Dies führt Bougard zu einer Geschichte der Elite vom 5.-6. Jahrhundert bis zum 11. Jahrhundert mit Fokus auf Frankreich, die er mit Bezug auf die Mediationen dieser Reziprozität -- insbesondere Vermögen häufig in Form des Landesbesitzes und manchmal auch in der symbolischen Form von öffentlichen Funktionen -- innerhalb der -- imperialen oder kirchlichen -- Elite oder zwischen dieser Elite und den anderen gesellschaftlichen Gruppen verortet. Dabei zeigt er, dass "Die Elite tatsächlich dieses Merkmal (diese Funktion?) hat, die unterschiedlichen sozialen Ebenen, die unterschiedlichen Gemeinschaften anhand von multiplen Interaktionen zwischen der oberen Autorität, die legitimiert, und den Gruppen, über die sie herrscht, kommunizieren zu lassen. Etwa auf der lokalen Ebene war der Einsatz von Mediationen, von Vermittlern, die in der Kommunikation zwischen Bauern -- die Mehrheit der Bevölkerung -- und der herrschenden Elite spezialisiert waren, für die Integration der 'dörflichen' Gesellschaften in die übergeordnete Gesellschaft notwendig. Dies betrifft alle Sektoren: das Religiöse, die Verwaltung, die Justiz etc." (ebd., 1083). Dieser Gebrauch von Mediationen als Hebel der Formalisierung von Verhältnissen zwischen sozialen Eliten und Bauern und somit als Gewährleistung der Ausübung von Legitimitätsprozessen über die Elite in der ganzen Gesellschaft hinaus stärkt nicht nur die Elite in ihrer Position und ihrer Zirkulation. Sie muss auch die Möglichkeit zur Anerkennung und Legitimation und daher zur Zirkulation für die ganze Gesellschaft bzw. idealerweise für alle Akteure gewährleisten, weil dies die Grundlage für die Legitimität der Elite bildet.

Weil die Forscher häufig zu Quellen gelangen, die fast ausschließlich nur Machtakteure und Elitegruppen betreffen, ist es schwierig, genau zu wissen, wie die anderen sozialen Gruppen einen solchen Zugang zur Zirkulation und daher zur sozialen Mobilität erhalten und eine solche Mobilität tatsächlich konkretisieren konnten. Aber der Blick zu den unteren Schichten von Elitegruppen legt nahe, dass eine solche Mobilität zumindest für diese sozialen unteren Fraktionen der Elite bzw. oberen Fraktionen von reichen Bauern tatsächlich existiert hat: "die hochmittelalterliche Gesellschaft entspricht einem anthropologischen Modell, nach dem keine Größe, keine Ehre unabhängig von einer Handlung in Richtung der Menschen in der Form von Verteilungen oder Dienstleistungen existieren kann [...]. Und dieses Modell betrifft die kirchliche Elite ebenfalls [...], weil die Leitung der christlichen Bevölkerung durch den Klerus voraussetzt, dass dieser nicht ausgeschlossen sondern in die Bevölkerung und ihre Praktiken inkludiert wird: Der Bischof ist Mitglied seiner Gemeinschaft, selbst wenn er sich davon durch sein Verhalten und seine Predigt unterscheidet und abhebt" (ebd., 1092). Für diese These spricht die praktische Handlung von Stadtbischöfen und Bischöfen, die darauf abzielt, durch die Unterstützung der Einheit der katholischen Kirche bei der Konkretisierung der Einheit der Bevölkerung (aufseiten der/die katholische Kirche) zur Eindeutigkeit der katholischen Religion beizutragen (zu führen).

## Das Streben nach Einheit und Eindeutigkeit

Um dieses Streben nach Einheit und Eindeutigkeit besser veranschaulichen zu können, kommen wir zur Dynamik der Produktion von Zirkulation und entsprechend zu ihrer Wurzel in der doppelten Einschreibung zurück, wie sie die Theorie der Relation problematisiert. In der Theorie der Relation wird grundsätzlich zwischen zwei Dynamiken der Zirkulation unterschieden. Einerseits haben wir die allgemeine Zirkulation der jeweiligen Relationsstrukturen nach Anordnung von Sequenzen ab der Kernsequenz von einer Relationsstruktur. In diesem Kapitel sprechen wir von der soziokulturell-orientierten Relationsstruktur, deren allgemeine Dynamik von der Sequenz Investition zur Repräsentation, Materialität und Attraktivität verläuft. In der politisch-orientierten Relationsstruktur beginnt die allgemeine Zirkulation hingegen bei der Sequenz Repräsentation als Kernsequenz dieser Relationsstruktur, und verläuft weiter zur Materialität, Attraktivität und Investition. Etwa für die Kaiser, die Könige und die Adelsfamilien im Mittelalter, für die es um Macht geht, ist die Repräsentation das Alpha und das Omega ihrer Zirkulation, und entsprechend zielen Sie darauf ab, ihre Repräsentation als Machtakteure zu materialisieren -- durch etwa Gaben und Konstruktionen oder Renovierungen von kirchlichen Gebäuden --, um sie dann für Akteure und Kollektiven attraktiv zu machen und somit weitere Investitionen in ihre Repräsentation als Machtakteure zu fördern. Das ist grundsätzlich das, was wir mit unseren obigen Ausführungen gesehen haben. In der katholischen Kirche geht es um eine allgemeine Zirkulation, bei der sich alles um die Investition in die katholische Kirche dreht, die repräsentiert und materialisiert wird, damit sie an Attraktivität für immer mehr Akteure und Kollektiven gewinnt, die eine solche Investition weiter unterstützen.

Damit eine solche Zirkulation optimal zirkuliert, müssen die Grundbedingungen der allgemeinen Zirkulation so gesichert werden, dass der Punkt, an dem diese Zirkulation verwundbar bleibt, so unbeschadet wie möglich bleibt, ansonsten wird von der allgemeinen Zirkulation und weiter von der Relationsstruktur selbst abgewichen. Wenn wir die Grundbedingungen der Zirkulation in jeder Relationsstruktur in den Termini der Sequenzen ihrer allgemeinen Zirkulation wiedergeben, dann können solche Bedingungen auf die zwei Sequenzen reduziert werden, die mit der Kernsequenz von einer Relationsstruktur unmittelbar verbunden sind. Die Sequenz dagegen, die mit dieser Kernsequenz lediglich mittelbar bzw. über die zwei anderen Sequenzen verbunden ist -- die sogenannte Brückensequenz --, ist die Sequenz, die der wunde Punkt der Zirkulation in einer Relationsstruktur darstellt. Am Beispiel der zwei Relationsstrukturen, die wir in diesem Kapitel beschreiben, ergibt sich dann Folgendes: In der soziokulturell-orientierten Relationsstruktur muss die Investition in diese Relationsstruktur attraktiv sein, damit sie repräsentiert werden kann, ansonsten wird sie nicht konkret bzw. kommt sie nicht zu ihrer Materialisierung [vgl. @PapilloudSchultze2022,339ff.]. Daher ist der wunde Punkt der Zirkulation in der soziokulturell-orientierten Relationsstruktur die Sequenz Materialität. Die Materialität muss gewährleistet werden, damit die Investition in dieser Relationstruktur tatsächlich gefördert wird. Jede Form von Abweichung von diesem Pfad schwächt die doppelte Einschreibung in dieser Relationsstruktur und entsprechend die Zirkulation der Akteure und die Position von Instanzen in ihr. In der politisch-orientierten Relationsstruktur wird die Repräsentation als Kernsequenz dieser Relationsstruktur gewährleistet, wenn in die Repräsentation investiert und diese Repräsentation materialisiert wird. Das sind die Bedingungen, damit die Repräsentation überhaupt an Attraktivität gewinnen kann (vgl. ebd., 342). Wenn eine solche Attraktivität der Repräsentation geschwächt oder gestört wird, dann wird die doppelte Einschreibung in dieser Relationsstruktur geschwächt, was nachgerade zur Schwächung oder Störung der Investition in die Repräsentation und derer Materialisierung zum Nachteil der Akteure und Instanzen in dieser Relationsstruktur führt.

Kommen wir jetzt mit dieser Unterscheidung auf das zurück, was wir von den Adelsfamilien und den Bischöfen gesagt haben. Wir merken, dass sich die Adelsfamilien nach dem idealen Sozialisationspfad ihrer politisch orientierten Relationsstruktur verhalten, wenn sie anhand von Gaben die katholische Kirche unterstützen. Durch die Materialisierung ihrer Macht unterstützen sie unmittelbar ihre Attraktivität als Repräsentanten der Macht, wodurch sie gleichsam ihre Macht auch gegen die Macht der vorhandenen lokalen Herren oder der herrschenden Könige absichern. Aber mit der Entsendung von Mitgliedern ihrer Familie oder von engen Vertrauten in die Religion, die dort zu Bischöfen werden, wird die Bedeutung ihrer materiellen Investition verändert. In der soziokulturell-orientierten Relationsstruktur trägt sie nicht unmittelbar zur Stärkung der Attraktivität der Repräsentation bei, sondern zur Investition in die Kirche selbst. Außerdem spielt hier eine solche Entsendung von Akteuren eine sehr wichtige Rolle, weil diese Akteure dazu beitragen, die ganze Relationsstruktur ab der Einschreibung von Akteuren und Instanzen in der katholischen Kirche zu stärken. Das ist die doppelte Bedeutung der materiellen Investition von Adelsfamilien: Sie stärkt sie sowohl intern bzw. vom Standpunkt der politischen Macht als auch extern bzw. vom Standpunkt der Religion, und sie eröffnet diesen Familien sowohl Zirkulationswege und Zirkulationsmöglichkeiten in beiden Relationsstrukturen, als auch Positionen in beiden politischen und religiösen Elitegruppen.

Vor diesem Hintergrund wird verständlich, dass die entsprechenden Akteure aus Adelsfamilien, die Bischöfe werden, sich einerseits immer noch als Mitglieder einer gesellschaftlichen Laienelite wahrgenommen haben, und sich andererseits immer intensiver mit ihren kirchlichen Aufgaben beschäftigt haben bzw. sich zu Mitglieder einer kirchlichen Elite profiliert haben, die imstande ist, Zirkulationswege und Zirkulationsmöglichkeiten in der katholischen Kirche zu bahnen und zu verbreiten. Dass ein solches Engagement für die Investition in die katholische Kirche zur Verdeutlichung der katholischen Religion gegenüber der Macht von Kaisern und Königen beiträgt, ist nicht nur auf der Ebene des Engagements der Bischöfe für ihre Stadt oder auf der Ebene der Vermehrung von kirchlichen Gebäuden in Städten und Regionen ersichtlich. Es zeigt sich auch durch die Arbeitsteilung ab der Bischöfe als Zeichen für die Stratifikation der katholischen Religion und für die entsprechende Implementierung von Instanzen zur Förderung und Vermehrung von Zirkulationswegen und Zirkulationsmöglichkeiten für Teile der Bevölkerung, die nicht oder nur wenig in der katholischen Religion integriert waren.

Etwa in den Studien, die Pierre Bonnassie im Jahre 1995 herausgibt [@Bonnassie1995], sieht man am Beispiel Südfrankreich, Nordspanien, England oder Böhmen vom 9. bis zum 12. Jahrhundert zahlreiche Beispiele einer solchen Stratifikation durch Delegation von Aufgaben von den Bischöfen zu den Mitgliedern des Klerus und manchmal auch zu den Mitgliedern der Gemeinden. So unterstreichen Bonnassie und Illy: "Der Bischof verleiht den Gemeindemitgliedern selbst das Patronat, insbesondere das Recht, ihren Diener zu wählen" [@Illy1995, 158]. Diese Praxis, die insbesondere im 10. Jahrhundert üblich war, setzt voraus, dass das Patronat nicht nur von hochrangigen Priestern ausgeübt wird, sondern auch von Priestern, die geweiht werden, nachdem sie sich zum Bau ihrer Kirche verpflichtet haben. Manchmal sind es Familienunternehmen, die von Klerikern aus der Bauernschaft geführt werden, die lesen und schreiben können und sogar über eine gewisse religiöse Ausbildung verfügen. Anders gesagt, handelt es sich für Bischöfe und Priester die katholische Kirche überall dort zu bringen, wo sie noch nicht Fuß gefasst hat, und dabei Bauer über Priester zu rekrutieren, die zur Integration der Gemeinschaft in die Kirche beitragen. Es geht um die Einheit der katholischen Kirche und um ihre Verbreitung, die zuerst durch die Verbreitung von Instanzen geht, davon die erste der Klerus ist, der von immer mehr Akteure aus der Gemeinde besetzt und geleitet wird. Im Vergleich zu Bischöfen und zu weiteren kirchlichen Akteuren (etwa Stiftsherren und Mönchen), die aus Adelfamilien kommen, kommen diese Prister aus der Bevölkerung der (freien) Bauer [vgl. dazu im selben Kontext @Loubes1995]. Formal bleiben sie zwar der Herrschaft von adeligen kirchlichen Akteuren unterworfen. Aber ihre Aufgaben verbreiten sich, was ihnen auch eine gewisse Handlungsmacht in ihrer Gemeinde geben, die auch zur Verbreitung von Gemeinden mit Priestern und entsprechend zur Verbreitung des Klerus über die Jahrzehnte beiträgt. Zwar funktioniert dieses Muster nicht überall, und er erstreckt sich in der Zeit nicht gleichförmig bzw. er ist nicht homogen. Nichtsdestotrotz zeigt es eine strukturierende Tendenz in der katholischen Kirche, die im Investiturstreit gipfelt: Die Kirche gewinnt an institutioneller Breite und an Festigkeit. Die Zeit scheint reif zu sein, um die politische Macht zu ergreifen, die bisher von Kaisern und Königen ausgeübt wurde.

## Die Macht der Päpste

Das Bild der Standesgesellschaft, das die Soziologie in Bezug auf den Mittelalter traditionell prägt, wird am Beispiel der Verflechtungen von Religion und Politik in dieser Zeit zumindest zum Teil hinterfragt. Dies ist umso mehr der Fall, als eine solche Verflechtung zu keiner bloßen Mischung von Religion und Politik führt, sondern zur Strukturierung beider Bereiche und darüber hinaus zur Verdeutlichung ihrer jeweiligen Relationsstrukturen entwickelt wird. Die gregorianische Reform ist in dieser Hinsicht einen entscheidenden Schritt in diese Richtung, weil Gregor VII. durch Maßnahmen, die darauf abzielen, die Beispielhaftigkeit vom kirchlichen Personal zu fördern, Zirkulationswege und Zirkulationsmöglichkeiten für dieses Personal von der Investition in die katholische Kirche zur Repräsentation der katholischen Kirche bereitet, davon der Repräsentant überhaupt der Papst sein soll.

Mit dieser Betonung der Wichtigkeit der Repräsentation hebt sich Gregor VII. auf der Ebene von einem Machtakteur in der soziokulturell-orientierten Relationsstruktur, und er bezieht somit strukturell eine äquivalente Position wie die von Kaisern und Königen in der politisch-orientierten Relationsstruktur. Oder in den Worten von Muresan: "Die Imperialisierung des Papstums stellt sich (...) als Nachahmung der imperialischen Institution selbst dar (...). Systematisch durch das gregorianische Papstum wieder aufgenommen, führt diese Dynamik in der zweiten Hälfte des 12. Jahrhunderts zur revolutionären Idee, dass papa est verus imperator. Demnach ist der Papst der Vikar von Christus, und der Kaiser konnte dann nur noch der Vikar vom Papst sein" [@Muresan2019, 141]. Diese Formalisierung vom Titel "Papst", der nicht nur der Leiter der katholischen Religion ist, sondern der universelle Anführer in spirituellen wie in weltlichen Angelegenheiten, kommt in der zweiten Anführung vom _Dictatus papae_ besonders prägend vor: "Quod solus Romanus pontifex iure dicatur universalis. (...) 'Nur der römische Pontifex gilt juristisch als universal ernannt'" (ebd., 202-203). Damit wird das Selbstverständnis des Papstums im Mittelalter ausgedrückt [@Althoff2019, bes. 189-202], nach dem der Papst "der wahre Kaiser" wäre [@Fuhrmann1985].

Unter Spezialisten des Investiturstreites und des Papstes Gregor VII. bestehen die Debatten zum Einfluss von Gregor VII. auf die Entwicklung des Papstums in den folgenden Jahrhunderten sowie zur Begrifflichkeit, die in diesem Zusammenhang verwendet wird -- etwa "Investiturstreit" oder "Reform" --, oder noch zur genauen Rolle des Rechtes als Begründungsgrundlage des Statutes vom Papst als universalem Papst bis heute offen. Nichtsdestotrotz bleibt in der Literatur zum Investiturstreit gut belegt, dass die Anführung von Gregor VII. den Klerus in seiner Struktur und Verbreitung durch kirchlichen Regelungen und entsprechenden Disziplinarmaßnahmen bzw. durch Verfestigung und Verdeutlichung von formalen Verfahren als kirchliche Institution gestärkt hat. Somit trägt Gregor VII. entscheidend zur Verdeutlichung der katholischen Kirche auf der institutionellen Ebene. Aber gleichzeitig trägt er dazu bei, die Zirkulation in der katholischen Kirche und ihre Kapazität, die politische Macht zu satellisieren, zu destabilisieren. Wie beide Bewegungen in Gang gesetzt werden und sich gegenseitig unterstützen, kann anhand der Theorie der Relation wie folgt erklärt werden.

Um Destabilisierungen der allgemeinen Zirkulation von Relationsstrukturen verstehen zu können, müssen die Folgen der Strukturierung von Relationsstrukturen berücksichtigt werden. Die Zeit der Stärkung der Investition in die katholische Kirche hat nicht nur ihre Bedeutung als Kirche gegenüber den Kaisern und Königen verdeutlicht und spezifiziert. Sie hat auch gezeigt, dass die katholische Kirche in der Lage war, immer mehr Akteure zu sich zu ziehen bzw. nicht nur die Mitglieder aus Adelfamilien, sondern auch freie Bauer aus entferntesten Örtlichkeiten, denen sie Bildung und Karrierewege gesamt mit einer Strukturierung der Gemeinden angeboten hat. Die katholische Kirche hat somit die Zirkulationsmöglichkeiten zur Sequenz der Repräsentation für die Akteure der ersten Kategorie in der katholischen Kirche bestens vorbereitet, die entsprechend im _Dictatus papae_ die formale Akte zur Rechtfertigung von einem solchen Schritt zum Vorteil der weiteren Strukturierung von Zirkulationswegen in der katholischen Kirche und zum Vorteil der Strukturierung der Sequenz Repräsentation selbst findet.

Aber durch die Hervorhebung des Papstes als universales Machtakteurs gibt es in der kirchlichen Elite die Tendenz, diese Sequenz der Repräsentation zu verabsolutieren und sie zum neuen Hauptmerkmal der Zirkulation in der katholischen Kirche zu befördern. Die Folgen daraus sind zweierlei. Einerseits führt eine solche Verabsolutierung der Repräsentation zur Destabilisierung der Zirkulation in der katholischen Kirche durch Veränderung ihrer Grundbedingungen. In unserem vorherigen Absatz haben wir diesen Punkt thematisiert: Eine Zirkulation in Relationsstrukturen hängt von einer bestimmten Anordnung von Sequenzen dieser Zirkulation ab, die der doppelte Einschreibung von Akteuren und Instanzen in dieser Relationsstruktur gewährleistet. Wird diese Ordnung von Sequenzen gestört oder geschwächt, dann wird eine solche doppelte Einschreibung destabilisiert, was die betroffene Relationsstruktur schwächt und sie gegenüber den Satellisierungen von anderen Relationsstrukturen verwundbarer macht. Mit der Verabsolutierung der Repräsentation in der soziokulturell-orientierten Relationstruktur, in der sich die katholische Kirche entwickelt, findet eine solche Veränderung der Anordnung von Sequenzen in Unterstützung der allgemeinen Zirkulation in der katholischen Kirche statt, die am besten durch die Verschiebung des Wundpunktes von der Materialität zur Attraktivität in der Unterstützung der Repräsentation führt, als ob die katholische Kirche tatsächlich wie die imperialie Macht funktionieren würde.

Ein Beleg für diese neue Strukturierung der katholischen Kirche um die Repräsentation zur Stärkung der Attraktivität dieser Repräsentation gibt die Entwicklung der Rolle und der Stratifizierung von Kardinalen "zu einem universalkirchlichen Kollegium, das zu einer wichtigen Sprosse innerhalb der hierarchischen Stufenleiter der Kirche wurde" [@Ganzer1993, 114]. Mit liturgischen Aufgaben beschäftigt, ändert sich die Rolle von Kardinalen mit Leo IX., der die Kardinalbischöfe bei der Leitung der katholischen Kirche miteinbezieht. Selbst die Hierarchisierung der Kardinale verändert sich. Wenn die Kardinalbischöfe unter Leo IX. und Gregor VII. die Elite der Kardinalen bezeichnen, die sich von den unteren Ordnen des Kardinalpresbyters und des Kardinaldiakons dadurch unterscheiden, dass sie unmittelbar an der politischen Entscheidung vom Papst mitbeteiligt sind, verändert sich diese Hierarchie in der Zeit durch den sukzessiven Aufstieg der beiden unteren Ordnen auf die Höhe der Kardinalbischöfe (ebd., 117-118). Daraus ergibt sich die Einheit des Kardinalkollegiums.

Mit dem Aufbau einer solchen kirchlichen Institution in der Unterstützung der Repräsentation von Päpsten wird die Macht der Kardinalen in der katholischen Kirche erheblich verstärkt. Einerseits wählen sie den Papst. Andererseits beteiligen sie sich immer mehr an den päpstlichen Entscheidungen, daraus die neue kardinalspezifische Instanz des Konsistoriums entsteht, das wie ein "Gericht für gewichtigere Fälle" wie etwa Glaubensfragen funktioniert (ebd., 119). Ein solcher Machtgewinnt kommt jedoch unvermeidlich zum Nachteil der Päpste, davon die Macht geschwächt und gestört wird. Das Kardinalkollegium "suchte (...) in die päpstliche Sphäre selbst einzugreifen und eine Teilhabe an der Machtfülle des Papsttums zu erringen" (ebd., 121). Eine solche Destabilisierung der Macht der Päpste kommt schon in der Zeit von Gregor VII. vor, wenn sich ein Teil seiner Kardinalen von ihm mit der Rechtfertigung lösen, dass nicht dem Papst allein die Leitung der Kirche belassen werden dürfte, sondern sie sollte wenn nicht insbesondere zumindest gleichermaßen von den Kardinalen geleitet werden. Dass diese Störung der Macht der Päpste durch die Verabsolutierung der Sequenz der Repräsentation die katholische Religion für eine lange Zeit erschüttern sollte und der politischen Macht eine Gelegenheit anbieten würde, die Oberhand über die Kirche zu behalten, zeigt nicht nur das Wibertinischen Schisma in der Zeit von Gregor VII., sondern im Allgemeinen die Verbreitung von konkurrierenden Päpste bzw. von Gegenpäpste.

Gegenpäpste sind keine Invention des Mittelalters, sondern sie tauchen schon vor dem Mittelalter auf, wenn in Streitfällen konkurrierende Päpste zu einem etablierten Papst entweder kirchlich intern oder vom Kaiser vorgeschlagen werden, um den Stuhl Petri zu beziehen [@Laudage2012]. Im Fall von Gegenpäpsten, die die imperiale Macht vorschlägt, handelt es sich von Päpsten, die in Unterstützung der Kaisers Interessen und zum Zweck der Unterdrückung der Macht von römischen Päpsten ausgewählt werden. Häufig können die Kaiser mit der Komplizenschaft von Kardinalen etablierter Päpste rechnen, die ihren Papst delegitimieren. Vom Kardinal Beno wird etwa Gregor VII. "zu einem Werkzeug des Teufels stilisiert: Da der diabolus die Christen nicht durch die paganos habe verwirren können, habe er zu einem falsum monachum gegriffen. (...) Hildebrand und seine Anhänger (...) seien novos idolatras in Anlehnung an die antike gens idolatrie" [@Matena2017, 131]. Wie Matena hervorhebt, sind Gegenpäpste ebenfalls von gegenseitigen Delegitimationsstrategien betroffen -- sie seien Götzendiener, Heretiker, Schismatiker und ihre Kardinalen werden ebenfalls als "anticardinales" nicht nur in Worten und Schriften, sondern auch in Bildern und anhand von Symbolen bezeichnet (ebd., 138). Das Vokabular, die Bilder und Symbolen, die in diesem Streit von beiden Seiten der Mitstreiter zur Etikettierung der anderen Seite verwendet werden, zeigen wie gespalten die Entscheidungsgrundlage für oder gegen die Entwicklung der katholischen Religion um die Repräsentation ist.

Mit Götzendiener, Heretiker und Schismatiker wird zwar gesagt, dass sich die Päpste bzw. Gegenpäpste und ihre Anhänger von den wichtigsten Werten der katholischen Theologie -- keine Idolen bewundern, das christliche Leben mit Bescheidenheit und aufmerksame Berücksichtigung der Dienste in Unterstützung der Einheit der Kirche leben [vgl. dazu @Schmidt2017] -- endgültig entfernt haben. Nichtsdestotrotz bleibt die Frage weiterhin offen, wer der richtige Papst ist bzw. was es bedeutet, der legitime Papst zu sein, und grundsätzlicher worin die Legitimität des Papstums bzw. die Legitimität der Autorität in der katholischen Religion verankert werden soll. Besteht sie in der politischen Macht, also tatsächlich darin, dass die Kirche strukturell ähnlich wie das imperialistische Reich auf die Gefahr hin entwickelt wird, dass dabei grundlegende Werte der katholischen Theologie verabschiedet werden? Besteht sie dagegen in der kirchlichen Macht, also eher darin, dass die Kirche entsprechend ihrer Kernsequenz der Invistition in die eigene Autorität in kirchlichen und darüber hinaus in spirituellen Angelegenheiten auf die Gefahr hin entwickelt wird, die Oberhand über Kaiser und Könige zu verlieren?

In der Zeit von Gregor VII. bis Urban II. wird diese symmetrische Verwendung von symbolischen Mediationen als Symptom der Uneindeutigkeit der Positionierung der katholischen Kirche in ihrer eigenen Relationsstruktur auch auf der Ebene der (gegen)päpstlichen Urkunden deutlich. Wie Schönfeld für die Zeit des Wibertinischen Schismas zeigt, beeinflussen sich Päpste und Gegenpäpste bei der Verfassung von Urkunden auf der Ebene von formalen Einzelheiten gegenseiteig. Vor Urban II. ist es etwa nicht selten, in päpstlichen Urkunden die Übernahme von "Schrift- und Kanzleicharakteristika aus nordalpinen Provenienzen, vor allem der salischen Herrscherkanzlei, der sogenannten Reichskanzlei" zu beobachten [@Schonfeld2017, 118]. Aber wenn die Päpste auf Reise sind, oder wenn sie nach Rom nicht zurück gehen können, weil dort ein anderer Papst inthronisiert wurde, müssen sie auf Schreiber zugreifen, die da vorhanden sind, wo sie sich befinden: "So zeigt das Beispiel Alexanders II. (...) einen den Kursivschriften nahestehenden Schrifttyp eines Schreibers oberitalienischer Provenienz. Schon aufgrund der Behandlung der Schäfte auf der Grundlinie und der rationaleren Gestaltung von Ober- und Unterlängen wird die Abweichung vom Schrifttyp der Reichskanzleischrift deutlich" (ebd.). Deshalb gibt es bei päpstlichen Urkunden sowohl eine Übernahme von Formalien aus der imperialischen Kanzelei als auch eine gewiße Improvisation bei der Verwendung der Schrift ab den Buchstabenformen zur Initiale des Papstnamens, die diese unbequeme Position der römischen Päpste zwischen kirchlich internen Konflikten wegen ihres Strebens nach Repräsentation und den Konflikten der Repräsentation selbst mit den Kaisern und Königen wiedergibt.

Mit Urban II. zeigt sich jedoch eine Harmonisierung der Urkunden, die den Willen der katholischen Kirche übersetzt, sich von "Einflüssen 'von außen'" zu befreien, "womit die Imitation des Anderen zunehmend zu einer Imitation des Selbst wurde, gleichsam einer 'Corporate Identity' der Institution Papsttum" (ebd., 124). Bei der Verfassung von Urkunden wird weniger improvisiert, was sich etwa daran zeigt, dass die Vielfalt der unterschiedlichen Formalien "auf wenige Varianten zusammengeschmolzen wurde. Eine davon bestand aus der grafisch einheitlichen Auszeichnung des Papstnamens einschließlich der Salutatio in Form von Gitterschrift, die vor oder mit dem rechten Zeilenrand abschloss" (ebd., 122). Diese Beherrschung der Mediation "Urkunde" bzw. ihr Einbezug in die Arbeit der römischen Päpste an der Gestaltung von Verhältnissen innerhalb der katholischen Kirche und mit dem Kaiser trägt einerseits zur Verdeutlichung der Position der Päpste gegenüber dem Kaiser bei. Aber andererseits trägt sie auch zur Umstellung der Position der Päpste bei, die durch die Verdeutlichung ihrer Kommunikation zur Unterstützung der Eindeutigkeit ihrer Handlung ihr Streben nach Repräsentation immer mehr in Unterstützung der Investition in die katholische Kirche bzw. die Repräsentation weniger im Bezug auf die politische Macht und mehr zur Hervorhebung der Autorität der katholischen Kirche bringen.

Damit wird eine Zirkulation gebannt, die in den nächsten Jahrhunderten nach Gregor VII. im Laufe der Schismen die kirchliche Elite immer mehr davon überzeugt, dass die Repräsentation im Dienst der Investition in die Einheit der katholischen Kirche entwickelt werden muss und nicht in der Konkurrenz zur imperialistischen Macht. Der Weg zur Eindeutigkeit der katholischen Kirche, worauf Müller verweist [vgl. @Muller2017], kann als Ergebnis der Satellisierungsstrategien verstanden werden, die zwischen Religion und Politik entwickelt worden sind und dazu beigetragen haben, die Grundlage der zeitgenössischen Debatten zum Umgang mit der _laïcité_ bereitzustellen.

## Schlußwort

In diesem Kapitel haben wir anhand vom Fallbeispiel der Macht von Päpsten der katholischen Religion vor und kurz nach des Investiturstreites den Punkt der Satellisierungsstrategien zwischen Relationsstrukturen illustriert. Dabei haben wir gesehen, wie diese Strategien, die den Einfluss nach Allianzen bevorzugen, mittelbar darauf abzielen, die Grundbedingungen der allgemeinen Zirkulation in einer Relationsstrukturen so zu verändern, dass diese Relationsstruktur unter der Kontrolle der satellisierenden Relationsstruktur kommt. Aber die Entwicklung von Satellisierungsstrategien hat auch eine Wirkung auf die satellisierte Relationsstruktur, die durch sie strukturiert wird. Adelfamilien im (Hoch)Mittelalter, die nach Macht streben, investieren sowohl in die Politik als auch in die Religion, um intern und extern ihr Streben nach Macht zu gewährleisten. Aber dabei unterstützen sie ebenfalls indirekt eine Strukturierung der katholischen Kirche, die mit der Zeit in der Lage sein wird, fest Institutionen zur eigenen Stärkung gegenüber die Macht von Kaisern und Königen zu etablieren und Zirkulationswege sowie Zirkulationsmöglichkeiten für das kirchliche Personal sowie für Akteure von Gemeinden zu verfestigen und zu diversifizieren. Dies trägt nicht nur dazu bei, eine solide Grundlage für die Reform der katholischen Kirche im Mittelalter vorzubereiten. Dies führt zum Veränderung der Gestaltung der katholischen Kirche von der Investition in die Kirche selbst zur Repräsentation ihrer Macht als universelle Macht über die politische Macht der Kaiser und Könige.

Hier wiederum von der Seite der katholischen Religion kommt der Versuch, die politisch-orientierte Relationsstruktur zu satellisieren, was sowohl unmittelbar zu Konflikten um die Repräsentation und ihre Bedeutung für beide Parteien, als auch zu einer neuen Strukturierung der katholischen Kirche selbst führt. Konflikte zwischen Bischöfen und Päpsten eskalieren, Gegenpäpsten stellen sich in der Konkurrenz zum römischen Papst, die entweder von den Kaisern allein oder mit der Komplizenschaft von Kardinalen und weiteren Bischöfen inthronisiert werden, die sich vom römischen Papst lösen. Die Konkurrenz in der Elite der katholischen Kirche, davon die einen für die Verabsolutierung der Repräsentation allein und davon die anderen für die Einheit der katholischen Kirche kämpfen, bahnt den Weg zur Entwicklung von Schismen als Symptomen von andauernden gegenseitigen Satellisierungen zwischen der soziokulturell- und der politisch-orientierten Relationsstrukturen, die sich bis zum 15. Jahrhundert erstrecken. Dabei sollte für die katholische Kirche immer deutlicher werden, dass ihr Kampf für die Repräsentation nur ein Schritt auf dem Weg zur eigenen Eindeutigkeit war, der, wenn er verabsolutiert werden würde, ihre Autorität und folglich die Einheit der katholischen Kirche maßgeblich beschädigen wenn nicht endgültig zerstören würde. Dass die Verlust der universale Macht zum Gewinn der kirchlichen Autorität führen würde, dass die katholische Kirche von einer direkten zu einer indirekten Machtausübung entwickelt werden würde [@Love1967], sollte für weitere Satellisierungen und entsprechende Strukturierungen in der katholischen Kirche führen, die später im Abendländischen Schisma gipfeln. Dass Millet das Konzil von Pisa unter der Frage der Legitimität der Repräsentativität in der katholischen Religion sah [@Millet1991], fasst das Ringen der katholischen Kirche um die Repräsentation ihrer Autorität und deren Repräsentanten bis heute gut zusammen.

## Literatur
