---
title: "Was uns die Reziprozität der Gabe erzählt"
indent: true
output:
    html_document: default
csl: chicago-author-date.csl
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Die Theorie der Relation weist dem Begriff der Reziprozität eine wichtige Bedeutung zu, gleichzeitig könnte jedoch der Eindruck entstehen, dass die Theorie der Relation den Terminus Reziprozität abwertet.

Tatsächlich geht die Theorie der Relation einerseits davon aus, dass Reziprozität das Ergebnis aus der doppelten Einschreibung von menschlichen zirkulierenden Akteuren und von gesellschaftlichen Instanzen unter der Bedingung ihres Widerstands in Relationsstrukturen ist. In diesem Zusammenhang bedeutet Reziprozität vom Standpunkt der Akteure neue Zirkulationsmöglichkeiten, die sie auf neue Zirkulationswege führen und ihre Zirkulation stärken oder schwächen/stören. Vom Standpunkt der gesellschaftlichen Instanzen bedeutet Reziprozität eine Stärkung oder Schwächung/Störung von deren Position in Sequenzen von Relationsstrukturen, die zur Differenzierung dieser Instanzen, ihrer formalen Verfahren und ihrer entsprechenden (positiven und negativen) Sanktionsmacht wesentlich beiträgt. Deshalb beeinflusst die Reziprozität die Legitimität sowohl von Akteuren als auch von gesellschaftlichen Instanzen, d. h. von deren jeweiligen Praktiken und deren Tätigkeitsbereichen. Diese Legitimität versteht sich stets in Bezug auf die Unterstützung des Primats der Zirkulation bzw. in Bezug darauf, wie das Primat der Zirkulation nach der sequentiellen Ordnung der Zirkulation in einer bestimmten Relationsstruktur abgebildet wird. Der Reziprozität kommt in der Theorie der Relation also deshalb eine so elementare Bedeutung zu, da sie am Erhalt und an der Verbreitung von Sequenzen und Relationsstrukturen maßgeblich mitwirkt. Oder anders gesagt: Die Reziprozität unterstützt die Auffassung des Primats der Zirkulation in Relationsstrukturen und deren mögliche Verbreitung auf die anderen Relationsstrukturen. Dies fasst die allgemeine Botschaft der Theorie der Relation wie folgt zusammen: Eine Relationsstruktur in all ihren Komponenten (Akteure, Aktanten, Instanzen, Zirkulationen) versucht stets, allen anderen Relationsstrukturen ihre Auffassung der Reziprozität in Unterstützung der Vervollständigung ihres eigenen Hauptmerkmals aufzudrängen. Entsprechend zielt eine Relationsstruktur durch all ihre Komponenten immer und unermündlich darauf ab, ihre Auffassung von Reziprozität zur idealen Reziprozität bzw. ihre Auffassung von Relation zur idealen Relation zu entwickeln, nach der sich dann die Zirkulationen in den anderen Relationsstrukturen sowie deren Komponenten zu richten hätten.

Andererseits geht die Theorie der Relation gleichsam davon aus, dass die Reziprozität nicht ständig verwirklicht wird, sondern nur dann, wenn eine Einschreibung von Akteuren und gesellschaftlichen Instanzen in einer Relationsstruktur erfolgt. Aus diesem Grund kann auch die Reziprozität die Verbreitung von Relationsstrukturen auf andere Relationsstrukturen einschränken, wenn diese Einschreibung weniger gut erfolgt oder gar ausbleibt. In der Theorie der Relation führt eine solche Betrachtung der Reziprozität zu der Aussage, dass Reziprozität nicht etwa eine Kerneigenschaft aller Arten von relationalen Ereignissen ist. Vielmehr kommt sie nur in Einschreibungsakten von Akteuren und gesellschaftlichen Instanzen in einer Relationsstruktur unter der Bedingung des Widerstands _für_ oder _gegen_ diese Relationsstruktur vor. Deshalb sind relationale Ereignisse nicht genuin mit einer Norm der Reziprozität verbunden, geschweige denn versiegelt, oder anders gesagt, Relationalität reimt sich nicht mit Reziprozität. Wie lassen sich aber diese beiden Aspekte zur Auffassung von Reziprozität zusammen denken?

Um diese Frage zu beantworten, kehren wir in diesem Kapitel zu Marcel Mauss' Ansatz in _Die Gabe_ zurück, weil Mauss in _Die Gabe_ ein Argument entwickelt, das in der Theorie der Relation ähnlich vorkommt. In _Die Gabe_ spricht Mauss von der Reziprozität kaum wortwörtlich. Nichtsdestotrotz ist seine Auffassung von Reziprozität stets präsent, insbesondere wenn Mauss vom Erwidern der Gabe spricht, weshalb wir uns jetzt mit diesem besonderen Moment der Gabe beschäftigen werden, der einen Gabentausch schließt und zum weiteren Gabentausch führt. Nach Mauss stellt das Moment des Erwiderns der Gabe ein Ideal der Reziprozität dar, dessen Verwirklichung die soziale Kohäsion der Gesellschaft und daher die gesellschaftliche Ordnung gewährleistet. Dieses letzte Argument hebt Mauss in seinem Spätwerk _Die Nation_ stark hervor. Die Nation wird nach Mauss dadurch gekennzeichnet, dass die Reziprozität ihr Organisationsprinzip ist, das durch die Genossenschaften vertreten und so in der modernen Gesellschaft durchgesetzt werden soll. Im Folgenden diskutieren wir diese Auffassung der Reziprozität bei Mauss und vergleichen sie mit der Auffassung von Reziprozität in der Theorie der Relation. Dabei argumentieren wir, dass -- trotz der Ähnlichkeiten im Verständnis der Bedeutung von Reziprozität für die soziologische Theoriebildung -- Mauss' Auffassung von Reziprozität von einem normativen Argument abhängig ist. Dies führt dazu, dass bei Mauss die Abweichungen von einer idealen Reziprozität unberücksichtigt bleiben. Genau diese Abweichungen von einer idealen Reziprozität sollten jedoch berücksichtigt werden, wenn wir verstehen wollen, wie durch die mehr oder weniger erfolgreiche Durchsetzung der Reziprozität Sequenzen und Relationsstrukturen mehr oder weniger erfolgreich strukturiert werden bzw. an Verbreitung gewinnen oder gegen Schrumpfungen kämpfen müssen.

Bevor wir allerdings zu dieser Diskussion der Reziprozität bei Mauss kommen, soll der Leser kurz ins Bilde gesetzt werden: In diesem Kapitel geht es nicht darum, eine Einführung zum Mauss'schen Werk, dem Mauss'schen Gabeverständnis oder zur mittlerweile fast unüberschaubaren Sekundärliteratur zu diesem Thema zu liefern. Dies haben wir in der Breite wie in der Länge anderswo dargestellt [@Papilloud2017; @monoPapilloud2023; @monoPapilloud2024]. Wir gehen davon aus, dass diese Grundlagen, auf denen wir unser Argument aufbauen werden, weitgehend bekannt sind. In diesem Kapitel soll deshalb deutlich gemacht werden, wieso der Begriff der Reziprozität ein unvermeidbares Werkzeug für die Strukturierung eines relationalen Musters in der Soziologie und _a fortiori_ für das Verständnis der Wechselwirkungen zwischen den Ebenen, die die Architektur der Theorie der Relation bilden, darstellt. Diese Erkenntnis, die wir aus der Diskussion von Mauss' Auffassung zur Gabe gewinnen, vervollständigen wir unter Rückgriff auf seine Überlegungen zur Reziprozität in _Die Nation_.

## Die Reziprozität in der Gabe

Stellen wir das Problem der Reziprozität zuerst allgemein dar: Wir befinden uns in der Soziologie mit diesem Begriff in einer Situation des doppelten Zwangs, wozu auch die Theorie der Relation in gewisser Weise beiträgt. Einerseits muss festgestellt werden, dass eine Reihe soziologischer Theorien den Begriff der Reziprozität gar nicht berücksichtigen, weil solche Theorien nicht genuin nach einem relationalen Ansatz strukturiert sind, selbst wenn sie gelegentlich relationale Erklärungsmuster zu produzieren imstande sind. Andererseits gibt es Theorien, die den Begriff der Reziprozität aufgreifen, um ihn gleichzeitig in Bezug auf die soziologische Untersuchung zu disqualifizieren -- die Reziprozität sei eine Erfindung oder sie sei normativ beladen und daher von wenig analytischer Bedeutung; dazu später mehr. Die Auffassung von Reziprozität in der Theorie der Relation könnte als Beispiel des zweiten Falles wahrgenommen werden, denn in der Tat behauptet sie, dass Reziprozität kein genuines Merkmal von sozialen Ereignissen ist. Ist dies nicht kontra-intuitiv und kontra-produktiv? Es scheint wie selbstverständlich, dass ein soziales Verhältnis ohne mehr oder weniger Reziprozität kein soziales Verhältnis sein kann bzw. nicht als solches existieren kann. Zudem würde man sich mit der Aussage, dass Reziprozität kein genuines Merkmal sozialer Ereignisse sei, das Leben unnütz erschweren. Einmal die Reziprozitität aus den sozialen Ereignissen ausgeklammert, käme man schnell in Bedrängnis bei der Erklärung von einfachen Interaktionssituationen, die der Beobachtung das Gegenteil preisgeben. Sehen wir nicht hier und da im Austausch von Gegenständen, von Meinungen, Zeichen und Symbolen, von Glauben und selbst von Menschen bspw. bei Paarbeziehungen oder der Familiengründung stets ein Hin und Zurück von Aktanten und Akteuren? Mauss' Gabe scheint das Paradebeispiel dessen zu sein. Das Gegebene scheint unvermeidlich Erwartungen auf Erwiderungen hervorzurufen, die nicht nur den Akteur betreffen, der etwas gibt, sondern auch denjenigen, der die Gabe empfängt.

Wenn dem so ist, dann stellt sich die Frage, wieso Mauss zwei Begriffe -- einerseits den Begriff des _hau_ und andererseits den Begriff der Verpflichtung -- verwendet, um die Rückgabe zu erklären. Tatsächlich wären diese zwei Begriffe überflüssig, wenn wir davon ausgingen, dass relationale Ereignisse an sich immer gegenseitig verlaufen. Als Erklärung für diese Hin-und-Zurück-Bewegung würde die Reziprozität reichen. Sie wäre die Kraft des Austausches, dessen Dynamik _sui generis_. Wieso dies nicht der Fall ist bzw. wieso Mauss die Reziprozität nicht in den relationalen Ereignissen zwischen Einzelakteuren oder in den interpersönlichen Interaktionen situiert, lässt sich besser nachvollziehen, wenn wir den Standpunkt in der Gabe beziehen, der für Mauss mit der wichtigsten der drei Positionen der Gabe verbunden ist: das Erwidern.

Nach Mauss ist "[d]er wichtigste dieser geistigen Mechanismen [des Gabentausches; CP und EMS] [...] ganz offensichtlich jener, der dazu zwingt, das empfangene Geschenk zu erwidern" [@Mauss1990, 25]. Das Erwidern der Gabe ist zeitlich nicht nur der letzte Akt im Zyklus des Gabentausches nach dem Geben und dem Empfangen der Gabe. Er ist auch ein Moment der Anerkennung -- die Anerkennung der Position des Gebers seitens des Empfängers einerseits, die Anerkennung der Position des Empfängers seitens des Gebers andererseits, und schließlich die Anerkennung des Gabentauches selbst, der sich nicht nur zwischen Geber und Empfänger sowie _vice versa_ entwickelt, sondern auch auf das Kollektiv, auf ihre Familie und auf ihren Clan übergreift. Dieser letzte Halbsatz ist deshalb besonders wichtig, weil er uns zeigt, wie Mauss die Gabe weit über die drei Momente des Gebens, Empfangens und Erwiderns sowie weit über Einzelakteure hinaus denkt. Die Gabe bringt die ganze Gesellschaft in Zirkulation, die durch Einzelakteure vertreten wird. Die Reziprozität in der Gabe ist also ein kollektives Phänomen, weshalb Mauss die Reziprozität nicht bei Einzel- und auch nicht bei Kollektivakteuren situiert sieht, sondern in den Gegenständen selbst, die ausgetauscht werden.

Mit dem Erwidern sagt Mauss zum einen, dass die Gabe eine Schließung von relationalen Ereignissen schafft. Verhältnisse, Interaktionen, Handlungen, die die Akteure der Gabe in den Tausch investiert haben, haben sich ereignet. Dieses Ergebnis symbolisiert das Erwidern des gegebenen Gegenstandes, das den Beleg dafür liefert, dass ein Gabentausch tatsächlich stattgefunden hat. Dies trägt zu der "Gewißheit" bei, dass eine Gabe immer erwidert wird (ebd., 82-83). Mauss spricht von dieser Gewißheit auf der Grundlage der Übersetzung eines Begriffes: dem _hau_. Er versteht das _hau_ als das, was in der Maori Sprache den Geist des Gebers im gegebenen Gegenstand beschreibt. Weil die Gegenstände, die im Gabentausch verwendet werden, ausnahmslos ein _hau_ einbeziehen, verlangen sie stets ihre Rückkehr zum Geber. Wenn der Empfänger des Gegenstandes diesen nicht erwidert, wird er diskreditiert. Das _hau_ ist also derjenige Begriff, der die "Kraft der Dinge" übersetzt (ebd., 103), die ihre Rückgabe an den Geber fordern, während das _hau_ gleichzeitig das "Zeichen und Pfand des Reichtums, eine magisch-religiöse Garantie des Rangs und Überflusses" (ebd., 111) darstellt, das die Position des Akteurs bezeichnet, der die Gabe gibt. Diese Deutung des _hau_ wird Debatten hervorrufen, die wiederum zu dem Punkt konvergieren, dass Mauss die Reziprozität als Merkmal der ausgetauschten Gegenstände missverstanden habe [vgl. etwa @Firth1940; @LeviStrauss2012; @Lefort1950, 1402; @Bourdieu1972; @Derrida1992].

Mauss rationalisiere bzw. reifiziere das _hau_. Er mache daraus ein konkretes Merkmal von Gegenständen, obgleich dieses Merkmal der magischen Umwelt der Gesellschaften der Gabe angehöre bzw. zur Weltvorstellung der Bevölkerungen gehöre, die Mauss untersucht. Mauss füge dem Gabentausch dieses magische Merkmal hinzu, weil er ansonsten nicht erklären könne, wieso die Gabe nicht nur gegeben, sondern auch erwidert wird. Daraus entstehe der Eindruck, dass die Reziprozität der Gabe eine greifbare Tatsache wäre. Sie wäre so konkret wie der Gegenstand selbst, der die Reziprozität trage, dessen Zirkulation vom Geber zum Empfänger und zurück zum Geber die Dynamik der Reziprozität ausmache und somit die Reziprozität zum ultimativen Muster jeder Form von Austausch erkläre. Ob ein solcher Begriff wie die Reziprozität in anderen Kulturen Sinn mache, bliebe jedoch fraglich. Ebenso fraglich bliebe Mauss' Andeutung, dass mit dem Reziprozitätsbegriff nicht nur Austauschpraktiken, sondern relationale Ereignisse im Allgemeinen grundsätzlich besser verstanden werden könnten. Täuschungsmanöver und Strategien, die im Gabentausch ebenso am Werk sind und darauf abzielen, diesen Tausch zu destabilisieren, ließen sich mit einem Begriff, wie dem der Reziprozität, nur unzureichend erfassen und erklären. Kurzum: Mit der Reziprozität schlage Mauss eine Deutung der Dynamik von Interaktionen und Handlungen vor, die er erfinde, zumal sich das _hau_ der konkreten Untersuchung vollständig entzöge.

Wenn die Gabetheorie jedoch stärker unter Berücksichtigung der Überlegungen von Mauss zur Magie und zu magischen Phänomenen kontextualisiert wird, die er zusammen mit Henri Hubert entwickelt hat, dann lässt sich deutlich besser erkennen und begreifen, was sich hinter dem _hau_ und dessen Deutung durch Mauss verbirgt.

## Hinter dem _hau_

In ihrer _Esquisse d'une théorie générale de la magie_ (1903) unterscheiden Hubert und Mauss die Magie von der Religion. Die Magie tendiere "zum Konkreten", die Religion "zum Abstrakten" [@Mauss2012c, 394]. Die Merkmale der Magie bilden eine "lebende, formlose und unorganische Masse, deren Bestandteile weder eine feste Position noch eine eindeutige Funktion haben" (ebd., 332), wohingegen die Religion als ein spezialisiertes System dargestellt wird, in dem sowohl "das Ritual und seine Arten" als auch "die Mythologie und Dogmatik wirklich autonom sind" (ebd.). Diese Unterschiede sind jedoch vor allem analytischer Natur. Im Alltagsleben der Gesellschaften, so stellen Mauss und Hubert heraus, gibt es keine radikale Trennung zwischen der Magie und der Religion, die von denselben "elementaren Tatsachen, [den] Grundtatsachen" abhängen, und von Hubert und Mauss mit dem _mana_ gleichgesetzt werden (etwa ebd., 389). Das _mana_ ist eine Art magische und religiöse Kraft, mit der Mauss in _Die Gabe_ die Kraft des Gabentauschs im Sinne eines Austausches erklärt, der von einer Reziprozität gespannt werde [@Mauss1990, 103]. Es gibt also nach Mauss eine klare Verbindung zwischen dem _hau_ und dem _mana_ in der Gabe, was allerdings nicht bedeutet, dass sich Mauss mit einer ausschließlich auf diesen beiden Termini beruhenden Erklärung der Dynamik der Gabe zufrieden gezeigt hätte. Entsprechend unterstreicht Mauss unter Rekurs auf das _mana_: "Doch nach unserem jetzigen Eindruck scheint uns dieser Begriff des mana noch zu sehr vom Mechanismus des sozialen Lebens abgelöst; er ist noch zu sehr etwas Verstandesmäßiges" [@Mauss2012c, 372]. Diese Einschätzung rechtfertigt sich damit, dass das _mana_ das konkrete Merkmal der Magie nur symbolisch wiedergibt. Im Konkreten besteht diese Praxis darin, schwachen Zusammenstellungen von Menschen und Gegenständen "Form" zu geben, d. h. aus solchen Zusammenstellungen Riten zu machen (ebd., 395), die darauf abzielen, eine "physische Wirkung" in der Gesellschaft bzw. konkrete, handfeste Veränderungen in der Gesellschaft zu initiieren [@Mauss1947, 85]. Oder anders gesagt: Die Magie operiert grundsätzlich nach einer "Kontiguitätsbeziehung" [@Mauss2012c, 305]. Sie ist Teil einer allgemeineren Logik des Sozialen, die darin besteht, Menschen und Gegenstände zusammenzustellen, damit "durch Kontiguität eine sympathetische Beziehung" hergestellt wird (ebd.). Sie ist nichts anders als die Beziehung, durch die Menschen und Gegenstände, die lose zusammengestellt wurden, einander ersetzbar werden, weil sie "substanziell identisch" geworden sind (ebd.). Genau diese Idee tritt in der Erklärung der Gabe entlang des _hau_ erneut hervor: Im Gabentausch geht es _ummittelbar_ um die Ersetzbarkeit der Positionen der Akteure und damit um die Bedeutung der Mediationen und deren Rolle in Unterstützung von Positionswechseln. Daraus entsteht _mittelbar_ eine Reziprozität als Beleg dafür, das eine solche Umstellung von Positionen _konkret_ stattgefunden hat: Der Empfänger der Gabe wird zum Geber und der Geber der Gabe wird zum Empfänger.

Diese Umstellung von Positionen der Tauschpartner in der Gabe hat Folgen für die Elemente -- Menschen und Nicht-Menschen --, die als Mediationen des Gabentausches fungieren: Sie verbleiben nicht mehr so, wie sie waren, als sie gegeben worden sind. So werden sie entweder verändert zurückgegeben oder sie werden mit einem oder mit mehreren anderen Mediationen zurückgegeben. Gaben verändert oder mit mehr Mediationen zu erwidern, ist Pflicht und verpflichtet somit den anderen Tauschpartner dazu, den Gabentausch fortzusetzen. Solche Gaben "mit Zinsen" [@Mauss1990, 79] folgen jedoch keiner wirtschaftlichen Logik, sondern einer Logik der sozialen Herausforderung, wo es darum geht, "den Geber oder Tauschpartner zu erniedrigen" (ebd., 172). Im Vergleich zum wirtschaftlichen _do ut des_, in dem die Reziprozität im individuellen Vertrauen angesiedelt ist, und im Vergleich zum Vertrag, der die Reziprozität in der Form von Kompensationen formal abbildet, geht es nach Mauss im Gabentausch darum, dass unter unterschiedlichen Bedingungen bzw. anhand von verschiedenen Meditationen getestet wird, ob und wie der Tauschpartner im Austausch bleibt und diesen Austausch (weiter) unterstützt. Oder anders gesagt: Im Gabentausch wird durch die Anhäufung von Mediationen getestet, wie widerstandsfähig die Tauschpartner sind, in dem sie _gegeneinander_ und gleichzeitig _für_ den Gabentausch widerstehen. Was im Gabentausch wie eine Pflicht aussieht, ist also einerseits die Herausforderung sowohl zur Mobilisierung von Akteuren als auch zur Umstellung von Positionen, die andererseits den Widerstand der Akteure im Gabentausch hervorruft. Durch den Gabentausch widerstehen die Tauschpartner deren eigener Einschränkung bzw. _gegen_ ihre Beschränkung auf eine bestimmte Position und damit gleichzeitig _für_ die Umstellung ihrer Position, was gewährleistet, dass der Gabentausch weiterentwickelt und auf weitere Akteure und Aktanten verbreitet wird.

Dieses letzte Element der Verbreitung des Gabentausches ergibt sich nach Mauss aus den demonstrativsten Formen der Zerstörung von Vermögen im _potlatch_, die zeigen, dass hinter dem, was im Gabentausch zirkuliert, kollektive Güter und Kollektive bzw. Institutionen wie der Totenkult oder das Gottesopfer auf dem Spiel stehen (ebd., 73). Im _kula_ haben die Gegenstände "einen Namen, eine Persönlichkeit, eine Geschichte, ja selbst eine Legende, so daß manche Individuen sogar diese Namen annehmen [...] man kann nicht umhin, ihre erhabene und sakrale Natur zu erkennen" (ebd., 59-60). Es ist nicht möglich, die Gegenstände des _kula_ unabhängig von den Kulten und Institutionen zu verwenden, mit denen diese verbunden sind, weshalb Mauss herausstellt: "Den Lebenden geben heißt den Toten geben" (ebd., 90 Anm. 142). Diese Gegenstände sind in unterschiedlichem Maße Verlängerungen von gesellschaftlichen Instanzen, die nicht nur den Rhythmus des Gabentausches, sondern auch die Umstellung von Positionen im Gabentausch -- vom Geber zum Empfänger und zum Erwiderer -- bestimmen. Beim Erwidern der Gabe geht es deshalb nicht darum, die Gabe des Gebers auszugleichen. Es geht vielmehr darum, sich in Verbindung mit den gesellschaftlichen Instanzen und zwar ab dem Moment der Verwendung eines (materiellen oder immateriellen) Gegenstandes zu setzen, um sich mit diesen Instanzen, mit den Aktanten, die sie verlängern, und mit den sozialen Gruppen, denen die Akteure des Gabentausches angehören, in den Gabentausch einzuschreiben. Die Herausforderungen, das Spiel mit der Ehre des Tauschpartners (ebd., 88-89), die "Heftigkeit, die Übertreibung und de[r] Antagonismus", die im Gabentausch hervorgerufen werden (ebd., 81), stellen deutliche Beispiele einer solchen Verbreitung des Gabentausches auf der Ebene von Kollektiven dar, in welchem sich diese Kollektive mit den Akteuren in den Gabentausch einschreiben können.

Nehmen wir das Beispiel des _potlatch_, das Mauss deshalb häufig erwähnt, weil der _potlatch_ das, was im Gabentausch passiert, vergrößert bzw. übertreibt und somit besser verständlich werden lässt. Der _potlatch_ wird von einem Häuptling, sei es ein Familien- oder ein Clanchef, gegeben. Ein _potlatch_ zu geben, setzt voraus, dass der Häuptling nicht nur seine Familie, sondern die größtmögliche Anzahl von Akteuren um sich herum mobilisiert. Alle werden mobilisiert, um sich in den relationalen Ereignissen, die das _potlatch_ ausmachen, einzuschreiben. Der melanesische _kula_ liefert ein weiteres gutes Beispiel von einer solchen Praxis. Die Clans versammeln sich um dessen Chef. Gemeinsam bereiten sie maritime Expeditionen vor, um Clans auf anderen Inseln Gaben zu überbringen. Es sind stammesübergreifende Phänomene, die "ja selbst auf internationaler Ebene bestimmt werden" (ebd., 24), wie die Beispiele des nordamerikanischen _potlatch_ zeigen. Sie können auch clanintern sein. Beim Tlingit-_potlatch_ treten "Clans, Phratrien und verschwägerte Familien [...] gegeneinander auf, und im allgemeinen scheinen die Verteilungen insofern eine Gruppenangelegenheit zu sein, als die Persönlichkeit des Häuptlings nicht ins Gewicht fällt" (ebd., 71). "Der Häuptling identifiziert sich mit seinem Clan und dieser mit jenem" (ebd., 76). Durch diese Identifikation zwischen Einzel- und Kollektivakteuren auf der Grundlage von Kontiguitätsbeziehungen erfolgt der Wechsel der Positionen im Gabentausch auf der Ebene von Einzel- und von Kollektivakteuren. Die ganze Gesellschaft erlebt ihre eigene Zirkulation als Zirkulation von Menschen, Aktanten und Symbolen zur Stärkung der Gesellschaft und ihrer Instanzen. Die Reihe an Operationen, die notwendig sind, damit der Gabentausch entwickelt wird, zielen auf die Einschreibung sowohl von Akteuren als auch von Instanzen der Gesellschaft in den Gabentausch ab und zwar stets unter der Bedingung des Widerstands der Akteure _für_ die Verbreitung des Gabentausches auf weitere Kollektive, woraus sich mittelbar die Reziprozität des Gabentausches ergibt.

Einschreibung, Widerstand, Reziprozität -- diese drei Begriffe generieren die Formel der Gabe als dreigliedrige Zirkulation des Gebens, Empfangens und Erwiderns. Aber bei Mauss tauchen sie im Hintergrund der zahlreichen Beispiele vom Gabentausch und dessen Deklinationen in unterschiedlichen Kulturen auf. Er verwendet sie nicht im Rahmen einer analytischen Vertiefung der Gabe. Wieso die Gabe weder zu einer Theorie der Gabe im Besonderen noch zu einer Theorie der Relation im Allgemeinen führt, lässt sich zweierlei erklären.

## Von der Gabe zur Nation

Mauss hat einen theoretischen Anspruch, der mehrmals in seinem Werk auftaucht und vor allem die Theoretisierung der konkreten gesellschaftlichen Grundlagen betrifft, die eine Gesellschaft generiert. Zu derartigen konkreten gesellschaftlichen Grundlagen gehört zwar die Gabe, aber Mauss theoretisches Anliegen reicht bei weitem über die Gabe hinaus. Schon 1901 mit Paul Fauconnet hebt Mauss die zentrale Bedeutung von "kollektiven Gewohnheiten" hervor, die sie "zum eigentlichen Gegenstand der Soziologie" machen [@Mauss1969, 146-148], und die Mauss zudem als wichtiger als die kollektiven Repräsentationen, die seinem Onkel Emile Durkheim zufolge das Alpha und das Omega des sozialen Lebens bilden, einstuft. Oder um es mit Mauss aus seiner Schrift _Rapports réels et pratiques de la psychologie et de la sociologie_ (1924) auf den Punkt zu bringen: "In der Gesellschaft gibt es etwas anderes als kollektive Repräsentationen, wie wichtig oder dominant sie auch sein mögen" [@Mauss1989b, 287]. Laut Mauss bestehe die Gesellschaft nicht nur aus kollektiven Repräsentationen, sondern aus konkreten kollektiven Tatsachen, aus Menschen, Gruppen und Praktiken, die ihrerseits kollektive Gewohnheiten widerspiegeln (ebd., 291-292). Selbst wenn Mauss also nicht in Abrede stellt, dass die kollektiven Repräsentationen einer der wichtigsten Gegenstände der Soziologie sind, so sollten sie dennoch nicht über die kollektiven Gewohnheiten gesetzt werden. Wie die Magie mit ihrer Tendenz zum Konkreten zeigt, bilden diese kollektiven Gewohnheiten nicht nur Ideen und Repräsentationen ab, sondern auch "die Vernunft, die Persönlichkeit, die Entscheidungskraft oder die Freiheit, die praktische Gewohnheit, die geistige Gewohnheit und de[n] Charakter, die Variation dieser Gewohnheiten" (ebd., 289). Mauss bringt damit jedoch nicht etwa zum Ausdruck, dass die kollektiven Repräsentationen den kollektiven Gewohnheiten untergeordnet seien. Vielmehr legt er nahe, dass kollektive Gewohnheiten eine vergleichbare Rolle wie kollektive Repräsentationen für die Bestimmung der Entwicklung einer Gesellschaft spielen. In dieser Hinsicht entfernt sich Mauss vom Determinismus Durkheims, weil er voraussetzt, dass die Wirkung sowohl von kollektiven Gewohnheiten als auch von kollektiven Repräsentationen begrenzt ist. Diese Grenzen sind nicht abstrakt, sondern sie ergeben sich aus dem alltäglichen Leben der Akteure und Gruppen in einer Gesellschaft.

Dieser Anspruch, eine Theoretisierung des konkreten gesellschaftlichen Lebens vorzunehmen, ergibt sich als der rote Faden aus Mauss' Werk. Er führt Mauss dazu, einerseits immer expliziter von der Reziprozität zu sprechen, die er andererseits als konkret greifbaren Gegenstand vorstellt. Etwa in seinem Essay _La cohésion sociale dans les sociétés polysegmentaires_  von 1931 spricht Mauss von einer unmittelbaren und von einer mittelbaren Reziprozität [@Mauss1969b, 18-19] in Bezug auf die Kontiguitätsbeziehung, die er in seiner Untersuchung der Magie und später in _Die Gabe_ erwähnt. Durch diese Kontiguitätsbeziehung werden in manchen Gesellschaften (Australien, Nord-, Ost- und Westamerika, Neukaledonien; vgl. ebd.) der Großvater und das Enkelkind gleichgesetzt, sodass der Vater sein Kind behandeln muss, als ob es sein Vater wäre. Dies ist ein Fall der unmittelbaren Reziprozität, in dem die Positionen von Großvater und Kind gewechselt werden. Im Falle mittelbarer Reziprozität beschreibt Mauss eine Situation der Delegation oder der Übertragung von Kontiguitätsbeziehungen auf andere Akteure, die sich beispielsweise in Initiations- oder Institutionsriten manifestieren (ebd., 18). Die Akteure, die initiiert oder instituiert werden, initiieren und instituieren weitere Akteure. Allerdings entwickelt Mauss diese Dimensionierung einer konkreten Reziprozität nicht weiter. Aus den Ausführungen in _La cohésion sociale dans les sociétés polysegmentaires_ bleibt deshalb der Eindruck zurück, dass Mauss die Reziprozität im Sinne einer Allianz von Akteuren versteht. Eine solche Allianz erwähnt Mauss schon in _Die Gabe_. Am Beispiel der Gaben der Ankunft auf den Trobriand Inseln hält Mauss fest, dass in der Regel "nach dem bestmöglichen Partner" gesucht wird [@Mauss1990, 68], denn es geht um die Allianz mit ihm. Jedoch stellt die Allianz im Gabentausch ein Moment dar, das am Ende vom Gabentausch auftaucht und der daraus resultierenden Reziprozität folgt. In _Die Gabe_ bestätigt die Allianz -- etwa durch Hochzeiten oder durch die Gründung eines neuen Clans --, dass eine Reziprozität stattgefunden hat. Sie verdeutlicht, dass Einschreibungen von Einzel- und Kolletivakteuren unter der Bedingung ihres Widerstandes mehr oder weniger erfolgreich stattgefunden haben, die zur Neuverteilung der Akteure und zur Schließung des Gabentausches geführt haben. Die Allianz ist also ein Moment der Schließung von einem Gabentausch und des Neuanfanges von einem anderen Gabentausch, der die Akteure und die gesellschaftlichen Instanzen vor die Herausforderung stellt, die Reziprozität in einer anderen Konfiguration der Gesellschaft zu generieren.

Trotz dieser Diskrepanz zwischen Reziprozität und Allianz liegt Mauss in der Folge daran, seine Auffassung von einer konkreten Reziprozität im Sinne einer Allianz weiter zu konkretisieren und durchzusetzen, selbst wenn er dabei den Begriff der Allianz nicht mehr explizit erwähnt. Dieses Anliegen taucht in seinem Spätwerk _Die Nation oder Der Sinn fürs Soziale_ deutlich auf. In _Die Nation_ spricht Mauss von der Reziprozität in Verbindung mit einem konkreten Gegenstand: die Genossenschaft. Er geht davon aus, dass ein Prinzip der Genossenschaft in den alten Gesellschaften existiert hat, das im Laufe der Zeit herausgearbeitet und verbessert wurde, bis es die Grundlage der zeitgenösisschen Genossenschaften gebildet hat. In allen Gesellschaften setzt Mauss Gruppen oder kleine Gesellschaften voraus, "von denen eine ganze Reihe sich bereits 'genossenschaftlich' nannte, bevor die Idee überhaupt aufkam, oder 'auf Gegenseitigkeit beruhend', was dasselbe ist" [Mauss2017. 315]. Wie man hier besonders gut beobachten kann, ersetzt Mauss die Verbindung zwischen der Reziprozität und der Allianz durch die Verbindung zwischen der Reziprozität und dem Genossenschaftlichen, wobei ihn diese letzte Verbindung dazu führt, Parallelen zwischen der Gabe und den Formen von Genossenschaften zu skizzieren [vgl. dazu auch @Hart2014; @Mallard2019]. Nach Mauss belegen die Genossenschaften in den zeitgenössischen Gesellschaften, dass die Gabe nicht nur ein Phänomen von alten Gesellschaften ist, sondern durch Genossenschaften in der Moderne aufbewahrt wird. Das zeigt die Reziprozität, die die gemeinsame Grundlage sowohl des Gabentausches als auch der Genossenschaften sei. Wie die Gabe sind Genossenschaften "intersoziale Bedingungen des Zusammenlebens der Gesellschaften" [@Mauss2017. 116]. Deshalb spricht Mauss von der Nation als eine "Inter-Nation" (ebd., 342), die durch die Interdependenz zwischen Nationen verwirklicht wird: "[D]iese wechselseitige Abhängigkeit [wird] von den Völkern selbst erkannt, empfunden und gewollt. Die Völker hegen ganz klar den Wunsch, dass dieser wechselseitigen Abhängigkeit gesetzlich, in einem kodifizierten, sanktionierten, öffentlichen und privaten Völkerrecht Ausdruck verliehen wird. In diesem Punkt sind die Völker ihren Führungen voraus" (ebd., 344).

Dieser Zusammenhang, den Mauss zwischen der Reziproztität und dem Genossenschaftlichen konstruiert und der einen Zusammenhang zwischen der Gabe einerseits und der Nation andererseits suggeriert, wirft jedoch eine neue Frage auf. Wenn Mauss von der Reziprozität in _Die Gabe_ spricht, setzt er sie nicht etwa in eine Verbindung mit einer speziellen sozialen Gruppe, sondern er macht aus der Reziprozität ein kollektives Phänomen, das quer durch die Gesellschaft geht, ja die Gesellschaft durchdringt, und deshalb ebenso bei anderen bzw. nicht genossenschaftlichen sozialen Gruppen auffindbar ist. Zwar kann Mauss durchaus konstatieren, dass das Genossenschaftliche schon immer in alten Gesellschaften vorhanden war. Aber würde das dann gleichsam bedeuten, dass die Reziprozität in _Die Gabe_ eigentlich das Genossenschaftliche ist, das Mauss in _Die Nation_ in den Vordergrund stellt? Mauss gibt keine Antwort auf eine solche Frage, was auch Folgen für seine allgemeine Lehre der Überbleibsel bzw. des Überlebens von Relikten aus alten Gesellschaften in unseren Gesellschaften zeitigt. Um diese Folgen zu verstehen, kommen wir zurück zu _Die Nation_.

In _Die Nation_ spricht Mauss von Austauschbeziehungen, die von Genossenschaften und nach Mauss insbesondere von Konsumgenossenschaften unterstützt werden. Diese Genossenschaften stellen den besten, wenn nicht gar den einzig möglichen Weg dar, über den sich die moderne Gesellschaft zu einer realen sozialen Gesellschaft entwickeln könnte, die nach Mauss eine sozialistische Gesellschaft und ferner eine Nation wäre. Jetzt gibt es zwischen den Gesellschaften der Gabe und den zeitgenössischen Gesellschaften nicht nur räumliche, zeitliche und kulturelle Unterscheidungen, sondern auch eine entscheidende strukturelle Unterscheidung. Die Gesellschaften der Gabe, die Mauss untersucht, sind segmentäre Gesellschaften. Zwar spricht Mauss von einigen dieser Gesellschaften der Gabe als Nationen [z. B. den Kwakiutl; @Mauss1990, 79], und erwähnt überdies Beispiele des Gabentausches zwischen Nationen (ebd., 181). Aber gleichzeitig hebt er hervor, dass diese Gesellschaften der Gabe ein weit entferntes Modell davon seien, was die Nation in den zeitgenössischen Gesellschaften repräsentiere. Zudem sollte ein solches Modell überwunden werden, weil die Gesellschaften der Gabe noch in ihrer Segmentierung gefangen seien, die die Entstehung der Nation verhindert habe: "Zunächst einmal kann nur dann von einer Nation die Rede sein, wenn die Gesellschaft einen gewissen Integrationsgrad aufweist, das heißt sie muss die gesamte Segmentierung durch Clans, Stadtstaaten, Stämme, Königreiche und Feudalgebiete hinter sich gelassen haben" [@Mauss2017, 88]. Genau an dieser Stelle offenbart sich die Problematik mit dem von Mauss ins Feld geführten Argument, wonach es eine Verbindung zwischen den Gesellschaften der Gabe und unseren zeitgenössischen Gesellschaften gäbe, die gewährleisten würde, dass beide Gesellschaften auf derselben Bedeutung der Reziprozität beruhten. Denn wenn die Gesellschaften der Gabe tatsächlich verschwinden müssten, damit es überhaupt zur Entwicklung der Nation komme, dann würde damit jeder Begründung der Boden entzogen, der zufolge sich plausibilisieren ließe, dass die Bedeutung der Reziprozität, die Mauss in der Gabe hervorhebt, von Genossenschaften wiederaufgenommen und als das Genossenschaftliche weiter entwickelt werden würde.

Mauss sieht sich also bei seiner Argumentation mit zwei entgegengesetzten Sachverhalten konfrontiert. So postuliert er einerseits das Überleben der Reziprozität der Gabe im Prozess der Auflösung von Gabengesellschaften. Andererseits betont er den mit dieser Auflösung einhergehenden Bedeutungsverlust vom Gabentausch in seiner strukturierenden Rolle für Gesellschaften, obgleich er in demselben Prozess einen strukturierenden Prozess für die moderne Gesellschaft zu erkennen glaubt. Diese Antinomie versucht Mauss mit dem Begriff der Verbreitung des genossenschaftlichen Merkmals in den Gesellschaften zu überwinden, die er mit der Verbreitung der Reziprozität in den Gesellschaften der Gabe verbindet.

## Die Verbreitung der Reziprozität als Nationalisierung

Der Begriff der Verbreitung verwendet Mauss in _Die Nation_ im Sinne der Verbreitung des genossenschaftlichen Merkmals auf alle Instanzen einer Gesellschaft. Dieser Sachverhalt meint das, was für Mauss der Begriff der Inter-Nation voraussetzt: Die Nation im Sinne einer Inter-Nation kann vollständig verwirklicht werden, wenn das Ideal, das die Genossenschaften verkörpern, innerhalb und zwischen den Nationen verbreitet wird. Dieses Ideal ist ein demokratisches Ideal im Sinne einer "Verbraucherdemokratie" (ebd., 313) bzw. einer "auf Wechselseitigkeit beruhende[n] Demokratie" (ebd., 288) -- einer "démocratie profonde" [@Mauss2018, 367] --, die die Konsumgenossenschaften realisieren würden. Die Konsumgenossenschaften verwirklichen dieses Idealbild der Demokratie, weil sie das Interesse der Verbraucher unterstützen (ebd.). Da ferner die "Verbraucherinteressen [...] bei allen Bürgern eines Landes gleich [sind]" [@Mauss2017, 326], unterstützen die Konsumgenossenschaften das allgemeine Interesse aller Bürger insofern, als sie das Interesse eines Bürgers verteidigen. Aus diesem Grund lösen die Konsumgenossenschaften auch "das Problem der utilitaristischen Moral zumindest teilweise" (ebd.) und führen darüber hinaus zur Verwirklichung einer Nation sowohl auf der wirtschaftlichen als auch auf der rechtlichen Ebene. Die Wirtschaft und das Moralisch-Rechtliche (ebd., 91) -- solche Formeln in _Die Nation_ erinnern unzweideutig an die ersten Zeilen der _Gabe_, in denen Mauss auf Folgendes hinweist: "Die vorliegende Arbeit ist Teil einer umfangreicheren Untersuchung. Schon seit Jahren richtet sich unser Interesse sowohl auf den Bereich des Vertragsrechts wie auf das System der wirtschaftlichen Leistungen zwischen den verschiedenen Sektionen oder Untergruppen, aus denen sich die sogenannten primitiven Gesellschaften und auch jene Gesellschaften zusammensetzen, die wir archaische nennen könnten" [@Mauss1990, 17]. Die Kontinuität zwischen _Die Gabe_ und _Die Nation_ ist diesbezüglich deutlich, selbst wenn Mauss in _Die Nation_ die Idee der Verbreitung in den Vordergrund stellt. Damit legt er nahe, dass die Nation eine Verbreitung dieser idealen, auf Reziprozität basierten Demokratie -- einen "Nationalisierungsprozess" [@Mauss2017, 91] -- voraussetzt, wovon die Verbreitung der Wirtschaft auf transnationaler Ebene zuerst Zeugnis ablegt. Aber diese Verbreitung der Wirtschaft auf internationaler Ebene reicht an sich nicht aus, um die Nation zu verwirklichen. Die Wirtschaft ist zwar der Tätigkeitsbereich, der diesen Weg bahnt. Denselben Weg muss jedoch auch das Recht gehen, um auf der Ebene des Völkerrechts gestärkt entwickelt zu werden, weil allein ein solch gestärktes Völkerrecht in der Lage ist, "die Idee einer von den Nationen gebildeten egalitären Gesellschaft" vollständig zu konkretisieren (ebd., 201).

Dies ist eine entscheidende Aussage aus _Die Nation_. Tatsächlich besagt sie, dass nach Mauss die Logik der Verbreitung vor allem durch das Recht und insbesondere durch die Entwicklung eines internationalen Rechts zu ihrer effizienten Entwicklung kommt (ebd., 344). Nur auf diesem Weg lässt sich also die Inter-Nation tatsächlich als eine Zusammenstellung von Nationen verwirklichen, die in "wechselseitige[r] Anbhängikeit" zueinander stehen (ebd., 343). Dies setzt eine doppelte Bewegung in gegensätzlichen Richtungen voraus, die in ähnlicher Weise bereits in _Die Gabe_ entwickelt wird und auch noch für Mauss' Auseinandersetzung mit Sebald Rudolf Steinmetz' These über den Zusammenhang von Praktiken der Rache und dem Totenkult in alten Gesellschaften konstitutiv ist. Durch das Recht erfolgt eine Formalisierung der Reziprozität als Kern von Mauss' Auffassung der "démocratie profonde", die gewährleisten kann, dass private Angelegenheiten nicht privat bleiben, sondern in Verbindung mit dem kollektiven Zusammenleben gebracht werden. Dies hat einerseits zur Folge, dass private Kriege [vgl. die ähnlichen Erwähnungen in Mauss' Rezension zu Steinmetz @Mauss2012a, 68 und in _Die Nation_ @Mauss2017, 343] unterbunden werden, woraus sich wiederum andererseits eine Legitimität sowohl für individuelle als auch für kollektive Akteure bzw. sowohl für Individuen als auch für gesellschaftliche Instanzen ergibt und gewonnen wird. Dieses Argument weist jedoch eine Schwierigkeit auf. Die Formalisierung der Reziprozität, von der Mauss spricht, verläuft von den (internationalen) rechtlichen Institutionen zu den (nationalen) Einzelindividuen, was den Ansatz der Reziprozität im Mauss'schen Verständnis schwächt.

Zwar stellt Mauss heraus: "Die Völker hegen ganz klar den Wunsch, dass dieser wechselseitigen Abhängigkeit gesetzlich, in einem kodifizierten, sanktionierten, öffentlichen und privaten Völkerrecht Ausdruck verliehen wird" (ebd., 344). Diese Aussage räumt allerdings nicht die analytischen Lücken aus, die Mauss bei seinem Versuch akkumuliert, aus der Reziprozität der Gesellschaften der Gabe eine konkrete Grundlage für die modernen Gesellschaften im Sinne einer sozialen Demokratie zu generieren, die die Genossenschaften mit Unterstützung des internationalen Rechtes verbreiten würden. Mit dem Argument des Wunsches der Bevölkerung wird zudem mittelbar eine Entsprechung von symmetrischen Erwartungen an der Seite der Einzelakteure und an der Seite der gesellschaftlichen Instanzen postuliert, als ob solche Erwartungen von einer Reziprozität zwischen Einzelmenschen und gesellschaftlichen Instanzen vorstrukturiert wären. Dabei geht eine der wichtigsten Lehren von _Die Gabe_ verloren: Alles im Gabentausch zirkuliert, und weil alles zirkuliert, gibt es zu keinem Zeitpunkt eine Gewährleistung dafür, dass die Gabe tatsächlich verwirklicht wird, was wiederum die unzähligen Vorsichtsmaßnahmen, die Herausforderungen, die Entwicklung von Strategien belegen, die den Gabentausch begleiten. Gleichzeitig reicht diese Erwähnung, zu der die Kritiken konvergieren, die über Mauss' _Die Gabe_ und insbesondere im Rahmen seiner Deutung des _hau_ vorgebracht wurden, an sich nicht aus, um die Produktivität des Konzeptes der Reziprozität für die Theorie abzulehnen, wie es Mauss in _Die Gabe_ bis zu _Die Nation_ zu transportieren versucht. Aber dafür muss man sich nicht nur von den kritischen Stimmen zu Mauss' Gebrauch der Reziprozität distanzieren, sondern auch von Mauss' Auffassung der Reziprozität. Dies ist das, was die Theorie der Relation in ihrer Auffassung der Reziprozität anstrebt.

## Von Mauss zur Theorie der Relation

Nicht nur in _Die Gabe_, sondern auch in _Die Nation_ stellt Mauss fest, dass die Verwirklichung von einer Reziprozität oder von einer auf Wechselseitigkeit beruhenden Demokratie, die die Genossenschaften als Organisationsmodell der modernen Gesellschaft hervorbrächten, nicht selbstverständlich ist. Es bedarf sehr viel Arbeit und die Mobilisation von ebenso vielen Einzel- und Kollektivakteuren sowie Aktanten in unterschiedlichen Formen. "Eben diese Vermischung von Personen und Dingen ist das Merkmal von Vertrag und Tausch" [@Mauss1990, 52], mit dem Mauss sein Verständnis der Totalität im Sinne der "'Ganzheit'" bzw. der "gesellschaftlichen Systeme in ihrer Gesamtheit" (ebd., 177) zum Ausdruck bringt. Was uns die Reziprozität der Gabe erzählt, wie wir oben gesehen haben, ist jedoch mehr als nur die Feststellung einer Totalität der Gesellschaft, was der Vergleich der Reziprozität in _Die Gabe_ mit der Reziprozität in _Die Nation_ deutlich unterstreicht. Der Gabentausch der alten Gesellschaften macht unzweideutig klar, dass die Kämpfe um die Ehre, um den sozialen Rang, um die Produktion und Reproduktion der gesellschaftlichen Strukturen bis in die Gegenwart hinein reichen. _Die Nation_ macht jedoch darauf aufmerksam, dass sich die Gesellschaften und mithin deren Totalität und Reziprozität im sozialen Raum diversifiziert haben und im Laufe der Zeit komplexer geworden sind. Oder um es anders zu formulieren: Es gibt eine Differenzierung der Totalität, die zur Herausforderung der zeitgenössischen Gesellschaften geworden ist. Obgleich auch Mauss dies feststellt, argumentiert er weiter nach einem Ansatz, der vorsieht, dass eine solche Differenzierung die zeitgenössischen Gesellschaften vor die Aufgabe stellt, Bedingungen zu erfüllen, die in den Gesellschaften der Gabe gewährleistet haben, dass diese Gesellschaften auf der Grundlage des Gabentausches produziert und reproduziert wurden. Jedoch blendet er dabei aus, dass solche Bedingungen nicht mehr mit denjenigen übereinstimmen, die in den Gesellschaften der Gabe vorhanden waren. Diese Diskrepanz bzw. diese Abweichung der modernen Gesellschaften von den Gesellschaften der Gabe nimmt die Theorie der Relation als Ausgangspunkt ihrer Auffassung der Reziprozität als Abweichung von einer _idealen_ Reziprozität auf, ohne jedoch dabei auf Mauss' Überlegung zu verzichten.

Etwa die drei Begriffe der _Einschreibung_ von Akteuren und Instanzen der Gesellschaft im Gabentausch unter der Bedingung des _Widerstandes_ der Akteure zum Zweck der _Verbreitung_ des Gabentausches auf weitere Kollektive bzw. zum Zweck weiterer Zirkulationen von Akteuren und Aktanten zu Kollektivakteuren: Sie erlauben eine konkrete Problematisierung der Bedingungen, von denen Mauss spricht. Hier übernimmt die Theorie der Relation eine solche Vertiefung jenseits der zwei Vorstellungen, die die Überlegungen Mauss' in _Die Gabe_ und _Die Nation_ stark beeinflussen. Die erste Vorstellung, wie mehrmals erwähnt, ist diejenige von einer idealen Reziprozität in den Gesellschaften der Gabe, die zu der zweiten Vorstellung der Verwirklichung dieser idealen Reziprozität in den modernen Gesellschaften durch die Verbreitung des Rechts auf der Ebene eines internationalen Rechts führt. Sich von diesen zwei Vorstellungen zu verabschieden, bedeutet nicht, auf die Reziprozität zu verzichten. Es bedeutet, die Reziprozität als Abweichung von dieser _idealen_ Reziprozität zu reformulieren, die Mauss in den Gesellschaften der Gabe durch die verpflichtende Erwiderung von Gaben gegeben sieht und die in den modernen Gesellschaften in Form einer von Konsumgenossenschaften strukturierten sozialen Demokratie fortlebt. Was spricht für eine solche Auffassung der Reziprozität als Abweichung von einer _idealen_ Reziprozität?

Am Beispiel von den häufig übertriebenen privaten Emotionen, die im Gabentausch zum Ausdruck kommen, zeigt Mauss, von welch wichtiger Bedeutung diese Emotionen und Gefühle für die Durchführung des Gabentausches und ferner für die konkrete Organisation der Gesellschaft sind. Sie finden Einsatz in Unterstützung von gesellschaftlichen Klassifikationsoperationen wie etwa "den Unterschied zwischen Dingen des persönlichen Gebrauchs und solchen, die 'properties' sind" (ebd., 67 Anm. 64). Deshalb sollten sie auch nicht dem individuellen Akteurausdruck allein überlassen werden, sondern von der Gesellschaft mitgesteuert werden. Im Gabentausch werden entsprechend bestimmte Gefühle obligatorisch an bestimmten Orten und zu bestimmten Zeiten ausgedrückt. Nehmen wir das Beispiel der Verwendung von Witzen im Gabentausch. Etwa bei den asiatischen Eskimogesellschaften werden im Gabentausch Witze gemacht, um die andere Partei dazu zu bewegen, ihre Gegenstände zu geben. Für die andere Partei ist es dann wichtig, nicht über diese Witze zu lachen. Eine solche Selbstbeherrschung soll vermitteln, dass man ein kühner Tauschpartner ist, der sich nicht leicht aus dem Konzept bzw. aus dem Gabentausch herausbringen lässt (ebd., 41 Anm. 45). Diese Kühnheit des Akteurs im Gabentausch trägt dazu bei, die Stärke des Clans bzw. die starke Position des Clans in Unterstützung des Gabentausches hervorzuheben, dem dieser Akteur angehört. Deshalb zeigt auch der Akteur, der nicht über die Witze des Kontrahenten lacht, die Stärke seiner Verbindung zu seinem Clan, die nicht gestört werden darf, weil sie ansonsten nicht nur diesen Akteur, sondern auch seinen ganzen Clan gefährden könnte bzw. sie delegitimieren würde. Diese Vermittlung des Kollektivs durch Individuen macht das Kernmerkmal der Gabe als totale Leistung aus: "Totale Leistung liegt in dem Sinne vor, daß wirklich der ganze Clan durch die Vermittlung seines Häuptlings kontrahiert, für alle seine Mitglieder, für alles, was er besitzt, und für alles, was er tut" (ebd., 24).

Dies hat eine erste Folge für die Auffassung von Reziprozität in der Theorie der Relation. Wie Mauss zeigt, kommt die Reziprozität im Zusammenhang von Einzel- und Kollektivakteuren bzw. von Individuen und gesellschaftlichen Instanzen und nicht etwa zwischen Einzelindividuen zustande. Mauss beschreibt diesen Zusammenhang anhand unzähliger Beispiele, er versäumt es aber, diesen Zusammenhang mit der Einschreibung von Akteuren und deren Instanzen unter der Bedingung des Widerstandes _für_ oder _gegen_ eine solche Einschreibung zu verbinden. Demgegenüber spricht er von der Verpflichtung bzw. von verpflichtenden Erwiderungen von Gaben, die er mit dem _hau_ zugespitzt begründet. Dies ist das, was die Theorie der Relation vermeidet, wenn sie diesen Zusammenhang im Sinne der Verbindung zwischen Einschreibung, Widerstand und Reziprozität aufbewahrt, weil sie eine Reziprozität generiert, die als Grundlage für die Verteilung und die Legitimation von Einzel- und Kollektivakteuren dient. Für die Theorie der Relation wird hieraus die Vorstellung gewonnen, dass eine Reziprozität mehr oder weniger erfolgreich auf der Grundlage der mehr oder weniger erfolgreichen Durchsetzung der Einschreibung von Einzel- und Kollektivakteuren im Gabentausch verwirklicht wird. Um zu Mauss' Beispiel der Witze in den Eskimogesellschaften zurückzukommen: Wenn bei Witzen nicht gelacht wird, wenn die Stärke der eigenen Position in der Gruppe und der eigenen Gruppe gezeigt wurde, dann ist die Einschreibung mit dem Tauschpartner im Gabentausch erfolgt. Folglich kann der Gabentausch wie die Umstellung von Positionen der Tauschpartner und ihrer jeweiligen Gruppen stattfinden. Es kann zirkuliert werden, und abhängig von der Art und Weise, wie gut oder schlecht dieser Gabentausch stattgefunden hat, stärkt er oder schwächt er die ganze Gesellschaft bzw. führt er zu Verbreitungen von Verhältnissordnungen durch spezifische Allianzen oder demgegenüber zur Schrumpfung von solchen Verhältnissordnungen in einer Gesellschaft, die bis zu gesellschaftlichen Spaltungen reichen.

Daraus ergibt sich die zweite und vielleicht selbstverständlichste Folge für die Theorie der Relation. Sie betrifft dezidiert die strukturelle Unterscheidung bei den Erwartungen von Einzel- und Kollektivakteuren und stellt sich gleichsam in eben jener strukturellen Unterscheidung von Reziprozitätsoperationen dar. Eingedenk dieser strukturellen Unterscheidung findet die Einschreibung von Einzelakteuren im Gabentausch auf der Grundlage der Umstellung ihrer Position in der Gabe statt, während die Einschreibung von Kollektivakteuren auf der Grundlage der Stärkung ihrer Position im Gabentausch erfolgt. Deshalb ist auch Mauss' Aussage in _Die Nation_, wonach sich die Bürger eine Organisation der Gesellschaft auf Basis von Genossenschaften erträumen, eher mit seiner eigenen Wunschvorstellung verbunden, die moderne Gesellschaft durch (Konsum)Genossenschaften vollkommen strukturiert zu sehen. Denn selbst in den Gesellschaften des Gabentausches kommt es zur Verdeutlichung der unterschiedlichen Erwartungen von Einzel- und Kollektivakteuren, was zudem die Ambivalenz des Gabentausches als Austausch ausmacht, der sowohl zur Allianz als auch zur Rivalität nicht nur zwischen den Parteien im Austausch führen kann, sondern auch innerhalb von jeder Partei. Diese Ambivalenz spiegelt sich nicht nur in den Gegenständen, die sowohl "gefährlich und tödlich" (ebd., 35-36) als auch "'erheiternd, tröstlich und besänftigend an sich'" (ebd., 60-61) sind. Sie betrifft auch die Akteure selbst. Der Vertreter des Clans kann auch zum Verräter werden bzw. er kann sich auch mit einem anderen Clan in Verbindung setzen oder seinen eigenen Clan gründen, wie Mauss und Durkheim in dem Aufsatz _Über einige primitive Formen von Klassifikation_ hervorheben [@Mauss1987]. Der Clan kann auch seinen Häuptling verraten, wenn dessen Mitglieder den Verdacht hegen, dass sie von ihm nicht mehr adäquat vertreten werden.

Die dritte Folge für die Auffassung der Reziprozität in der Theorie der Relation ergibt sich aus dem Zusammenspiel der beiden erstgenannten Folgen: Die Reziprozität führt nicht unbedingt zur Verbreitung von Zirkulationen, wie Mauss postuliert. Gerade weil die Reziprozität ständig gestört und geschwächt werden kann, was im Kontrast die Existenz von Sanktions- und Kompensationssystemen in den Gesellschaften der Gabe hervorheben und diese gleichsam notwendig machen, kann die Reziprozität ebenso zur Schrumpfung von Zirkulationen oder zu deren Störung und Schwächung führen. Dies passiert, wenn sie suboptimal erfolgt bzw. wenn Einschreibungen aufgrund von Widerständen geschwächt stattfinden oder ganz und gar gestört werden und ausbleiben. Deshalb ist es wahrscheinlicher, dass es zwischen den Gesellschaften der Gabe und den modernen Gesellschaften keine einfache Kontinuität gibt, deren entscheidenden Beleg die Genossenschaften in den modernen Gesellschaften lieferten. Es gibt eher eine komplexe Ausdifferenzierung der Reziprozität, die zu strukturellen Differenzierungen innerhalb der Gesellschaften und zwischen den Gesellschaften in Zeit und Raum führt. Dies verdeutlicht die Botschaft der Theorie der Relation in historischer Hinsicht: Die Ausdifferenzierung der Reziprozität und die Verfestigung jener differenzierten Auffassung der Reziprozität in einer speziellen Auffassung von Zirkulation führt zu unterschiedlichen Organisationsformen der Gesellschaft in Zeit und Raum.

## Schlußwort

Fassen wir zusammen, was wir in diesem Kapitel aufgezeigt haben. Mauss' Auffassung von Reziprozität ist als normativer Moment seiner Erklärung der Einheit der Gabe, ferner der Einheit der Einzel- und Kollektivakteure sowie schließlich der Einheit der alten und der zeitgenössischen Gesellschaften stets präsent. Einerseits spiegelt sich diese normative Auffassung im _hau_ wider, sie wird aber andererseits auch mit dem Begriff der Verpflichtung verdeutlicht. Begleitet wird eine solch normative Auffassung von Reziprozität im Mauss'schen Werk von der ethnographischen Beschreibung unterschiedlicher Situationen des Gabentausches. Mauss rekurriert entweder auf Sanktions- und Kompensationssysteme, die die Ambivalenz von ausgetauschten Gegenständen hervorheben. Er stellt die Beziehungen zwischen Akteuren der Gabe dar, die allesamt den Kontext des Gabentausches, in denen es nach Ansicht von Mauss sowohl um Allianzen als auch um Rivalitäten geht, betonen. Hinter dem Kreis der drei Verpflichtungen der Gabe -- Gaben zu geben, zu empfangen und zu erwidern -- erscheint eine bedeutsame soziale Arbeit bei der Einschreibung der Akteure mit Aktanten im Gabentausch und ein Widerstand sowohl _gegen_ Akteure also auch _für_ die Zirkulation der Gabe. Im Zuge dessen entsteht vorübergehend eine Reziprozität, die, selbst wenn sie nicht ideal hergestellt wird und daher Verstöße und Verletzungen zulässt, die Grenze zwischen Zyklen des Gabentausches und damit die Akteure und Aktanten absegnet, die daran teilgenommen haben und entsprechend positiv und negativ sanktioniert werden.

Diese ethnographische Beschreibung, die Mauss' Auffassung der Reziprozität begleitet, bietet also grundlegende Elemente an, um aus der Reziprozität ein analytisches Werkzeug zu machen, das es erlaubt, den Beitrag von Akteuren durch ihre Arbeit an relationalen Ereignissen zur Entwicklung von Zirkulationsmöglichkeiten und Zirkulationswegen in der Gesellschaft und zur Stärkung oder Schwächung/Störung der Position von gesellschaftlichen Instanzen besser zu bestimmen. So lässt sich also besser verstehen und erklären, wie solche Zirkulationen relationale Ereignisse in der Gesellschaft auf der Ebene von großen Referenzrahmen je nachdem auffangen und organisieren, wie eine Reziprozität entstanden ist und so aufbewahrt worden ist, dass sie zum Hauptmerkmal von solchen Referenzrahmen wird bzw. zu ihnen wesentlich beiträgt. Diese Ausdifferenzierung der Reziprozität in der Gesellschaft in Abweichung zu einer _idealen_ Reziprozität ist der Weg, den die Theorie der Relation vorschlägt, um eine Theorie der Gesellschaft anzubieten, die vollständig auf dem Primat der Zirkulation ruht. Die Reziprozität fungiert als Potenzierung vom Primat der Zirkulation im Positiven wie im Negativen bzw. im Sinne der Verbreitung wie im Sinne der Schrumpfung einer solchen Zirkulation und deren entsprechendem Referenzrahmen, die in der Theorie der Relation als Relationsstrukturen konzipiert werden. Die Erklärung dieser Relationsstrukturen vertiefen wir im nächsten Kapitel. Dort illustrieren wir die Aussage, nach der die Theorie der Relation vier Relationsstrukturen vorsieht, und wie diese Relationsstrukturen Tätigkeitsbereiche dimensionieren, in denen die Akteure ihr Alltagsleben verbringen. Als Beispiel für die Tätigkeitsbereiche und die entsprechenden Akteure widmen wir uns der gesellschaftlichen Sphäre der Kunst.

## Literatur
