---
title: "Transformers. Medien als Akkumulatoren von Verhältnissen"
indent: true
output:
    html_document: default
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Früher in der Öffentlichkeit wenig thematisiert, ist es jetzt beinah unmöglich, den Ausdruck _KI_ für künstliche Intelligenz zu verfehlen. Es ist die letzte digitale Mediation _en vogue_, darum sich viele gesellschaftliche Debatten und Kontroversen drehen, seitdem diese Technologie unter dem Namen _ChatGPT_ -- GPT für _Generative Pretrained Transformers_ -- bekannt und im Internet zur Verfügung gestellt wurde. Wer _ChatGPT_ probiert hat, hat ein Gefühl dafür gewonnen, in welche Richtung die nächsten Entwicklungen im Internet und in den sozialen Medien gehen und welche möglicherweise weitreichende Veränderungen unsere Gesellschaften durchgehen würden, die heutzutage nicht mehr als durch digitale Relationen in der Form von zahlreichen Algorithmen vernetzten Gesellschaften weg zu denken sind [@Seyfert2019; @Seyfert2021]. _ChatGPT_ zeigt allen Akteuren und Instanzen unserer Gesellschaften vielleicht deutlicher als andere Mediationen zuvor, dass die Macht von Medien und im Allgemeinen von Mediationen deshalb so bewältigend ist, weil sie unsere Verhältnisse zu den anderen und zur Welt abfangen, bewerten und weiter entwickeln können bzw. weil sie jede Stufe der Arbeit an relationalen Ereignissen formal generieren können, ohne dass dabei Akteure und gesellschaftliche Instanzen notwendig wären. Die Welt der Mediationen ist eine Welt, in der idealerweise nicht mehr die Akteure und die Kollektiven anhand von Verhältnissen die Mediationen dieser Verhältnisse kontrollieren, sondern diese Mediationen kontrollieren diese Verhältnisse anhand von Akteuren und Kollektiven. Oder vom Standpunkt des Primats der Zirkulation ausgedrückt: In dieser Welt der Mediationen geht es vor allem darum, dass es nicht nur anhand von Akteuren und Kollektiven, sondern auch jenseits von ihnen zirkuliert wird.

Aus dieser Verselbstständigung von Mediationen ergibt sich die Grundlage von einer eigenen Ordnung von Verhältnissen mit eigener Idealisierung der perfekten Relation als _creatio continua_ auf der Grundlage einer ununterbrochenen Zirkulation. Diese Ordnung von Verhältnissen fungiert als Selbstverständnis der Medien orientierten Relationsstruktur. In dieser Relationsstruktur gewährleisten die Mediationen die doppelte Einschreibung von Akteuren und Instanzen, d.h. sie eröffnen Zirkulationspotentiale, sie bringen Akteure auf entsprechende Zirkulationswege, und sie stärken die Position von gesellschaftlichen Vermittlungsinstanzen. Entsprechend arbeiten die Akteure und die Instanzen in dieser Relationsstruktur an der Verselbständigung von Mediationen in der Ausführung ihrer eigenen Operationen im Dienst der Gewährleistung der doppelten Einschreibung von Akteuren und Instanzen und ferner im Dienst der Unterstützung von Zirkulationen in dieser Relationsstruktur. Diese Operationen setzen eine mediale Kontrolle voraus, die Verhältnisse vom Standpunkt ihrer Einbettung in formalen Verfahren von gesellschaftlichen Instanzen und nach ihrer Verbindungen miteinander evaluiert. Diese Kontrolle fungiert gleichzeitig als Grundbedingung der doppelten Einschreibung, die weitere Einschreibungen generiert und weitere Wertungen produziert, daraus die entsprechende Zirkulation ihre Bedeutung und ihre Wichtigkeit für die Relationsstruktur übernimmt. Oder anders gesagt: Die mediale Kontrolle ist eine unmittelbare Kontrolle der Effizienz von Zirkulationen auf der Grundlage der Bewertung von Einschreibungen für eine Relationsstruktur, die sich mittelbar als Bewertung sowohl der Akteure als auch der gesellschaftlichen Instanzen ergibt, die in diesen Einschreibungen einbezogen werden. Weil sie Akteure und Instanzen in Relationsstrukturen mittelbar betrifft, bildet diese Kontrolle die Kernbedeutung der Reziprozität in der Medien orientierten Relationsstruktur. Die Legitimität von Akteuren und von Instanzen, die in dieser Relationsstruktur zirkulieren bzw. aufgebaut werden, hängt davon ab, dass sie sich bei Akten der doppelten Einschreibung dieser Kontrolle unterwerfen.

Aus der Arbeit von Akteuren und Instanzen der Medien orientierten Relationsstruktur an Mediationen ergeben sich jedoch zahlreiche Abweichungen vom Ideal der perfekten Relation bzw. der perfekten Zirkulation aufgrund von einer perfekt kontrollierten Einschreibung in Relationsstrukturen, wie sie die Medien orientierte Relationsstruktur anstrebt. Wie in den anderen Relationsstrukturen strukturieren diese Abweichungen die Medien orientierte Relationsstruktur. Sie vergeben ihr ihre spezielle Identität als Ordnung von Verhältnissen, die zur Materialisierung der Investition in die Repräsentation der Attraktivität von Mediationen beitragen. Diese Attraktivität ist das Hauptmerkmal und die Kernsequenz dieser Relationsstruktur, ab der sie sich als selbstständige Relationsstruktur mit eigener Zirkulation bildet. Die Verselbständigung einer solchen Medien orientierten Relationsstruktur symbolisiert die wachsende Bedeutung der Zirkulation in allen Gesellschaften bis heute. In allen Gesellschaften, die in der Zeit und im Raum nicht nur demographisch wachsen, sondern auch strukturell komplexer werden, wird die Zirkulation von einer Möglichkeit zu einer Notwendigkeit, die am besten von Mediationen gewährleistet werden kann, weil sie vermeiden können, dass Akteure und gesellschaftliche Instanzen Einschreibungsprozesse und resultierende Zirkulationen verfehlen oder eskamotieren.

Die zeitgenössischen Transformers symbolisieren einen aktuellen Schritt in die weitere Entwicklung der Medien orientierten Relationsstruktur. Als Mediation etablieren sie sich auf der Grundlage von zahlreichen Veränderungen im technischen Umgang mit Informationen und Wissen. In diesem Kapitel führen wir zuerst in die Operationen ein, die solche Transformers formalisieren und in der Form von Algorithmen durchführen. Daraus ergibt sich, dass diese Operationen grundsätzlich auf alten Praktiken der Aufnahme und Verarbeitung von Informationen und Wissen ab dem Lesen und Schreiben von Texten basieren, die sich in der Zeit vom Standpunkt ihrer Verbindungen miteinander verändern. Diese Veränderungen entsprechen einer Desakralisierung der Beziehung zwischen dem Autor und seinem Text und einer Umstellung des Verhältnisses zwischen dem Autor und seinem Text. Der Text muss nicht mehr die Media darstellen, die zur richtigen Interpretation der Intentionen des Autors führt, dem sich der Text unterwerfen sollte. Der Text muss zur Media werden, die die Fähigkeit des Autors beweist, weitere Texte und somit weitere Autoren an dem Text mehr oder weniger explizit einzubeziehen und miteinander zu verbinden, also aus einem Text eine Stütze von zahlreichen Verhältnissen zur Information und zum Wissen zu machen, die einen Text für weitere Akteure und für die Produktion und Rezeption von weiteren Texten attraktiv machen.

Diese Verselbständigung des Textes von der symbolischen Autorität seines Autors bahnt nicht nur den Weg zur Entwicklung von Tätigkeitsbereichen, in denen es um die Texte geht, was zum Aufbau von gesellschaftlichen Instanzen und zur Zirkulation von entsprechenden Akteuren führen, die solche Texte produzieren und rezipieren. Dies werden wir in diesem Kapitel am Beispiel der Literatur in Frankreich im 19. Jahrhundert in ihrer Verbindung mit literarischen Zeitschriften, Verlagen und mit der Presse beschreiben. Die Verselbständigung von Texten führt auch zur Konstitution einer speziellen Ordnung von Verhältnissen bzw. einer Medien orientierten Relationsstruktur mit entsprechenden Instanzen. Sie fokussieren eine solche Verselbstständigung von Mediationen mit dem Ziel, Zirkulationsmöglichkeiten für Akteure auf der Grundlage ihrer Fähigkeit zu verschaffen, weitere Verbindungen von Mediationen auf Mediationen zu bringen, die die Arbeit der Akteure an relationalen Ereignissen nicht nur erleichtert, sondern sie teilweise übernimmt und entsprechende Zirkulationswege daraus generiert. Wenn erste Schritte in diese Richtung von der Presse ab dem 19. Jahrhundert geleistet werden, bringt die Entwicklung von digitalen Technologien im 20. Jahrhundert den notwendigen Impuls zur endgültigen Etablierung einer selbständigen vierten Ordnung von sozialen Verhältnissen, einer Medien orientierten Relationsstruktur, deren Hauptmerkmal und Selbstverständnis in der Attraktivität von all möglichen Mediationen als Grundlage der Legitimation der Zirkulation von Akteuren, der Position von gesellschaftlichen Instanzen und der Satellisierung von anderen Relationsstrukturen besteht.

## Transformers als relationale Dispositiven

Die Theorie der Relation schlägt ein grundsätzliches Verständnis von Mediationen als Träger von Verhältnissen vor, wobei die jeweiligen Mediationen ein Prinzip des Arrangements dieser Verhältnisse darstellen. Deshalb versteht sie Mediationen nicht nur im Sinne von Trägern von Funktionen oder von Formen bzw. von anderen ehemaligen Mediationen [@Mcluhan2001], sondern auch als relationale Dispositiven. Damit solche relationale Dispositiven erfolgreich entwickelt werden, ist es erforderlich, dass Mediationen zu abstrakteren Mediationen entwickelt werden. Nur so können unterschiedliche Verhältnisse bzw. Verhältnisse, die auf unterschiedliche Kontexte verweisen, auf solche Mediationen gebracht und miteinander verbunden werden, ohne dass die jeweiligen Kontexte, die als Organisationsrahmen und Sinnzusammenhang der entsprechenden Verhältnisse gelten, diese Umstellungen und Verbindungen schwächen oder stören. Diese Abflachung von Kontexteffekten durch die Extrapolation von Verhältnissen macht aus abstrakte Mediationen mächtige Akkumulatoren und Generatoren von formalen Verhältnissen, die überall in Relationsstrukturen und Sequenzen von Relationsstrukturen verbreiten werden können. Dies entspricht der Art und Weise, wie die Medien orienterten Relationsstruktur die anderen Relationsstruktur zum Vorteil der eigenen Verbreitung und der Verbreitung der eigenen Fassung der Reziprozität als medialer Kontrolle satellisiert. Sie verbreitet formale äquivalente Verhältnisse in der Form von relationalen Dispositiven auf die anderen Relationsstrukturen, die entsprechend als Kontrollinstanzen von Verhältnissen im Dienst von Einschreibungsprozessen in diesen Relationsstrukturen eingesetzt werden können. Ein solches Verfahren ist dasjenige, dass in der Forschung zu Sprachen und zur Modellierung von Sprachen seit den 1950er Jahren entwickelt wurde, davon die Transformers wie _Generative Pretrained Transformers_ das zeitgenössische Ergebnis sind [@Hutchins1995].

Sprachmodelle wurden entwickelt, um das spezifische Problem der Übersetzung von einer Sprache in eine andere Sprache mit Hilfe eines Rechners zu lösen (ebd.). Bis in die 1980er Jahren erweisen sich die meist mit Unterstützung von der Firma _IBM_ durchgeführten Übersetzungsexperimente jedoch als bescheiden. Mit einem Rechner war es möglich, Begriffe in einer begrenzten Anzahl von Texten zu übersetzen, die anhand von einem statistischen Verfahren in Sätzen aufgegriffen und übersetzt wurden. Jedoch konnte ein solches Verfahren keine langen Wortfolgen wie etwa lange Sätze verarbeiten. Es gaben häufig Fehler, die ein menschliches Eingreifen zur Überprüfung und Korrektur der Übersetzung erforderten [@Pierce1966; @Zong2022]. Der technische Fortschritt, insbesondere die Steigerung der Rechenleistung (bessere _Central Processing Unit_ und _Graphics Processing Unit_) und des Arbeitsspeichers hat dazu geführt, dass einerseits größere Datenmengen gespeichert werden konnten und andererseits den Umfang von statistischen Operationen über diese Daten erweitert werden konnten. Aus dieser Entwicklung ergibt sich Mitte der 1980er Jahre die Methode des _Recurrent Neural Network_ (RNN). Dabei geht es darum, die Verhältnisse zwischen Begriffen in Sprachen auf der Grundlage der Modellierung von Verhältnissen zwischen Neuronen im menschlichen Gehirn zu überdenken. Mit der RNN-Methode können mehr Korrespondenzen zwischen Begriffen hergestellt -- der sog. _deep learning_ Ansatz  -- und gleichzeitig mit größeren Wortzusammenstellungen gearbeitet werden. Daraus wurden ausgefeilteren Sprachmodellen wie etwa das Modell der bidirektionalen rekurrenten neuronalen Netzwerken (BRNN), das Langzeitgedächtnismodell (LSTM) oder das _gated recurrent units_ (GRUs) Modell konstruiert [siehe @Hochreiter1997]. Solche Modelle sind Matrixen von Verbindungen zwischen Begriffen, die nach einem Ähnlichkeitsansatz quantitativ gewertet werden. Begriffe, die stark verbunden sind, gelten als Begriffe, die häufig zusammen in Sätzen und Absätzen auftauchen und deshalb auf ähnliche Sinnzusammenhänge bzw. auf ähnliche Inhalte verweisen. Begriffe, die dagegen schwach miteinander verbunden sind, gelten als Begriffe, die weniger häufig zusammen in Sätzen und Absätzen auftauchen und deshalb als Begriffe, die auf unterschiedliche Inhalte verweisen. Diese Sprachmodelle können entsprechend als eine Referenzmatrix verwendet werden, um weiter Sammlungen von Daten zu untersuchen und deren Inhalt zu werten.

Trotz Fortschritte in der Entwicklung von Rechnerkomponenten, die Rechner immer leistungsfähiger gemacht haben, reichen die technischen Entwicklungen nicht immer aus, um große Datensammlungen anhand von solchen Sprachmodellen auszuwerten. Anfang 2017 wurden deshalb GPT-Modelle entwickelt, die dieses Problem lösen sollten. Das innovative Merkmal von GPT-Modellen besteht darin, Matrixen von Begriffen nicht mit Sequenzen von Begriffen -- etwa mit Sätzen -- zu verbinden, sondern mit einzelnen Begriffen. Dies beschreibt den Kern von einem Transformer: Er verbindet einen Begriff mit den Begriffen, die am wahrscheinlichsten mit diesem Begriff in einer bestimmten Sprache auf der Grundlage von einer bestimmten Datensammlung verbunden sind. GPT-Modelle sind deshalb einerseits eine Erweiterung der Sprachmodelle, die nach einem _deep learning_ Ansatz konstruiert wurden. Andererseits besteht ihre Besonderheit darin, dass sie aufgrund von solche Matrixen die Wahrscheinlichkeit schneller und mit wenigen rechnerischen Kosten bestimmen können, dass ein Begriff _B_ nach einem Begriff _A_ auf der Grundlage von einem Kontext von Begriffen auftaucht, die am wahrscheinlichsten mit dem Begriff _A_ in einer gegebenen Sprache verbunden sind [siehe auch @Devlin2019]. In künftigen Versionen von solchen Transformern geht es darum, das Ergebnis dieser Wahrscheinlichkeitsrechnung zu benutzen, um die Effizienz des Sprachmodells selbst bzw. um die Genauigkeit der Matrixen zu verbessern, damit solche Wahrscheinlichkeitsrechnungen schneller und präziser erfolgen, ohne dass der Rechner überfordert wird und dass das Sprachmodell zu schnell obsolet wird. Durch eine solche Verbesserung wird vorstellbar, dass Sprachmodelle immer schneller berechnet werden, was sie gegen der kontinuierlichen Produktion von Inhalten in den digitalen Welten des Internets und der sozialen Medien weniger anfällig machen würden.

Bei Transformers geht es also um die Akkumulation von Dateien und von Verbindungen zwischen diesen Dateien, die erlauben, weitere Verbindungen zwischen diesen Dateien und entsprechend weitere Dateien aus diesen Verbindungen zu generieren. Eine solche Akkumulation anhand und in der Form von Mediationen zu entwickeln, ist nicht erst mit der wissenschaftlichen Arbeit an der _KI_ entstanden. Sie stellt eine Grundtendenz bei dem Einbezug von und der Arbeit an Mediationen durch Akteure und gesellschaftliche Instanzen dar, davon wir die Bedeutung besser verstehen können, wenn wir die Grundoperationen von Tansformers dekonstruieren und sie auf dem Hintergrund der Praktiken perspektivieren, die diese Transformers in abstrakter Form reproduzieren, und zwar: Dateien aufnehmen bzw. lesen und sie zerlegen bzw. exzerpieren, um weitere Zusammenstellungen von Dateien auf der Grundlage der aufgenommenen und zerlegten Dateien zu produzieren. Wie aus Mediationen Akkumulatoren von Verhältnissen generiert werden, werden wir zuerst im Rahmen der ersten Operation vertiefen, die wir erwähnt haben: Lesen.

## Lesen

Transformers lesen Dateien, und wenn wir dieses Lesen von Außen betrachten würden, würden wir sagen, dass es nichts mit dem Lesen von Texten durch übliche menschlichen Akteuren gemein hat. Transformers nehmen Texte auf, die in diesem Sinne gelesen werden, dass sie in Sätzen und Begriffen zerlegt, von unerwünschten Zeichen und Begriffen gereinigt und in der Form von Listen und ferner von Vektoren bzw. eindimensionalen Matrixen dargestellt werden. Damit stellen Transformers die Ausgangslage für die Berechnung von Verbindungen zwischen Begriffen und die notwendige Stufe zum Arrangement von solchen Verbindungen in der Form von anderen Texten auf der Grundlage vorhandener Textdateien bereit. Deshalb haben Transformers Debatten über den Wert von einem solchen Lesen von Dateien in seiner Verbindung mit Wissen als Produktion von Erkenntnis aus der Interaktion zwischen Menschen und digitalen Technologien wieder animiert, die teilweise schon in Bezug auf die Auffassung von verteilter Kognition in den Neuro- und Kognitionswissenschaften [@Magnus2007; @Michaelian2013; @Anderson2018; @Risku2020] und auf die Rolle von Algorithmen bei der Unterstützung menschlicher Entscheidungen eingeführt wurden [@Pariser2012; @Anderson2012; @Braverman2014; @Bucher2018; @LeeLarsen2019]. Die Fragen, die sich in diesen Zusammenhängen stellen, betreffen den Sinn der Wissensproduktion und den Wert des entsprechenden Wissensinhaltes, wenn dieses Wissen nicht primär von menschlichen Akteuren, sondern maßgeblich von digitalen Mediationen hergestellt wird. Die Auseinandersetzung mit dem Lesen und den Lesenstechniken in der Geschichte zeigt nicht nur, dass solche Fragen nicht neu sind. Sie zeigt auch eine Aufmerksamkeit der Literatur auf die Verselbständigung von Mediationen und auf die Verhältnisse, die sie zum Lesen, zu den Texten, die gelesen werden, und zum Wissen, das aus diesen Texten entnommen wird, in die Gesellschaften einführen. Einerseits wird hervorgehoben, dass eine solche Verselbständigung von Mediationen die soziokulturelle Kontrolle über solche Mediationen schwächen kann. Aber andererseits wird unterstrichen, dass diese Verselbständigung von Mediationen mehr Verhältnisse auf Verhältnisse generiert, die die Möglichkeiten von solchen Mediationen vermehren, in immer mehr Verhältnissen und Praktiken einbezogen zu werden, solche Verhältnisse und Praktiken entsprechend zu stärken und insgesamt zur Verbesserung der Einschreibung von Akteuren in unterschiedlichen Tätigkeitsbereichen beizutragen . Dieses Dilemma zwischen Kontrollverlust vs. Vermehrung und Stärkung von Einschreibungsmöglichkeiten, die Mediationen wie Transformers anbieten, stellt sich beim Lesen schon ab der Auseinandersetzung mit der Frage ähnlich, ob es laut oder lautlos gelesen werden sollte, was zu weiteren Fragen bezogen auf das schnelle oder langsame, einmalige oder mehrmalige, vollständige oder nur teilweise Lesen führt.

Die Debatten zu der Entwicklung von unterschiedlichen Lesenspraktiken beziehen sich generisch auf das rekurrierende Problem der Hierarchisierung von Mediationen, die mit Satellisierungsstrategien innerhalb von Relationsstrukturen und zwischen Relationsstrukturen verbunden sind und ähnlich wie sie je nach Erfolg oder Scheitern von Satellisierungsstrategien umgestellt werden. Im paradigmatischen Fall vom lauten und lautlosen Lesen, den wir hier beispielhaft fokussieren, wird zuerst ersichtlich, dass die Verbreitung des lautlosen Lesens in der Zeit andere Verhältnisse zum Lesen und zum gelesenen Text mit sich bringt, selbst wenn das laute Lesen nicht deswegen marginalisiert oder gar verabschiedet wird: "Das lautlose Lesen verdrängte nicht das laute Lesen, das weiterhin nicht nur beim Vorlesen, sondern auch beim 'Für-sich'-Lesen praktiziert wurde" [@Zedelmaier2001, 14; vgl. auch @Bickenbach2017]. Mit der Verbreitung vom lautlosen Lesen entwickeln sich neue Verbindungen zwischen beiden Techniken des Lesens, die zu weiteren Verbindungen mit anderen Lesenstechniken -- wie etwa das oben hervorgehobene langsame und schnelle Lesen -- führen. Nichtsdestotrotz bewahrt das laute Lesen die Oberhand über das lautlose Lesen, weil es häufig mit dem menschenzentrierten Lesens assoziiert wird. Mit dem lauten Lesen wird nicht nur abstrakt und allgemein den Menschen ins Zentrum des Lesens gerückt, sondern dieser Phonozentrismus, wie Jacques Derrida sagt [@Derrida1967], ist gleichzeitig die Signatur der Wissensmacht des lauten Lesers. Das Aussprechen des Geschriebenen ist die Bedingung für die aufmerksame Berücksichtigung vom Textinhalt, der, weil er durch das Aussprechen des Textes einverleibt wird, als besser verstanden gilt. Die Herrschaft des Wortes durch die Macht dessen Klangs segnet die Herrschaft des Sprechers oder des Rezitators über den lautlosen Leser ab, der die Worten nicht erleben kann, weil er sie nur "sieht", weshalb er deren Inhalt nur oberflächlich verstehen kann.

Sei es in der griechischen Antike oder im 19. Jahrhundert und trotz der Revolution in der Produktion von schriftlichen Mediationen, die den Buchdruck im 15. Jahrhundert bringt und das lautlosen Lesen zuerst zu begünstigen scheint, setzt sich diese Hierarchie zwischen dem lauten und dem lautlosen Lesen noch eine gute Zeitlang weiter durch [@Gavrilov1997]. Um es mit dem Wortlaut der Theorie der Relation auszudrücken: Beim lauten und lautlosen, langsamen und schnellen Lesen sowie bei der Verhältnisse, die zwischen diesen unterschiedlichen Lesenstechniken entwickelt werden, spielt sich die Durchsetzung von unterschiedlichen Hierarchieprinzipien zwischen textuellen Mediationen, den Akteuren, die sie beanspruchen, den Insititutionen, mit denen sich diese Akteure in Sequenzen von Relationsstrukturen einschreiben, und diesen Sequenzen selbst. Diese Hierarchie zwischen dem lauten und dem lautlosen Lesen von der griechischen Antike bis zum Mittelalter macht aus dem lauten Lesen die gewöhnliche Praxis des Lesens, wenn das lautlose Lesen ein Sonderfall vom lauten Lesen darstellt [@Busch2002; vgl. auch @Bickenbach2017, 40ff.]. Entsprechend werden die Texte und die Leser hierarchisiert. Laut werden insbesondere literarische Werke von hoher Bedeutung gelesen, wenn dagegen das leise Lesen alltägliche Schriften oder Texte von weniger Bedeutung betreffen. Laut lesen meistens Gelehrte und im Allgemeinen Akteure, die sich tagtäglich bzw. beruflich mit Texten beschäftigen. Bei diesen Personen kommt sogar eine Kombinatorik zwischen dem lauten und lautlosen lesen häufig vor. In diesem Fall wird das lautlose Lesen meistens als eine Art von Hilfsmittel gebraucht, um sich den Inhalt von Werken, die schon gelesen wurden oder manchmal auswendig gelernt wurden, wieder in Erinnerung zu bringen. Wenn mit dem lauten Lesen das langsame Lesen in Verbindung gebracht wird, wird dabei hervorgehoben, dass laut lesen nicht nur als Rhetorikkunst praktisiert wird, sondern auch als Kontrollmittel im Dienst des richtigen Verständnisses vom Text zur Bildung vom entsprechenden adäquaten Wissen. Wer laut liest, stellt sich dann in einem adäquaten Verhältnis nicht nur zu einem Text, sondern auch zu der Intention des Textautores.

Wie Bickenbach am Beispiel von Christoph Martin Wieland hervorhebt, ist diese Asymmetrie zwischen lautem und lautlosem Lesen eng mit dem Thema der Kontrolle bzw. des Kontrollverlustes des Autors über seinen eigenen Text verbunden. Dieses Thema wird im Laufe der 17. und 18. Jahrhundert von Autoren immer mehr aufgegriffen, die wahrnehmen, dass die Leser zahlreicher werden und im Grunde so lesen, wie sie möchten [ebd., 31; vgl. auch @Schenda1970, der im Jahr 1760 eine Verdoppelung der Ausleihen in Bibliotheken mehrheitlich von Menschen feststellt, die weder Adeligen, Aristokraten oder Großbürger sind]. Für Autoren wie Wieland oder später auch Arthur Schopenhauer und Friedrich Nietzsche birgt sich in dieser Gleichgültigkeit des Lesens die Gefahr, den Text mit eigenem Wissen zu Interpretationen zu zwingen, die mit den Autors Intentionen nicht übereinstimmen. Dies würde dazu führen, den Text falsch zu verstehen. Hier kann nur ein aufmerksames und langsames lautes Lesen helfen, oder wie Bickenbach am Beispiel von Nietzsche sagt: "Lesen wäre im Idealfall das Ablesen der Tatsachen ohne Verfälschung der eigenen Interpretation" (ebd., 41). Im Fall von Nietzsche bereitet dieses ideale "Ablesen der Tatsachen" die Grundlage seiner Kulturkritik der Moderne vor, wo das laute Lesen als Erbe der Antike die einzige adäquate Technik zum richtigen Verständnis von Texten als physische Leistung vom Leser zur Gewährleistung des richtigen Verständnisses der Intentionen des Textautors wahrgenommen wird. Nichtsdestotrotz trägt die Erweiterung des Kreises der Leserschaft -- von kleinen Kreisen ausgebildeter Akteuren vor dem 18. Jahrhundert auf immer mehr Akteure nach dem 18. Jahrhundert und entsprechend auf ein wachsendes Publikum von Texten -- zur steigenden Attraktivität von Texten bei, die die Asymmetrie zwischen lautem und lautlosem Lesen anfechten und andere Verhältnisse zum lauten und lautlosen Lesen zum Vorteil der Texte als Mediation der Akkumulation von Texten und Autoren, daher von Wissen und Kultur generieren. Dabei verfügt diese Tendenz auf eine alte Praktiken der Verwendung von Texten durch das Zitieren und das Exzerpieren in der Unterstützung der Verhältnisse zwischen der Aufbewahrung der Mündlichkeit der Sprache im geschriebenen Text und dem Anspruch vom geschriebenen sowie schreibenden Lesen bzw. zum Lesen mit Stift [@Kramer2005; @Kramer2012].

## Zitieren und Exzerpieren

Wie Alain de Libera mit Fokus auf das Mittelalter sagt: "Die mittelalterliche Textualität ist, wenn man so will, eine mündliche Textualität; der mittelalterliche Text ist eine Mischung aus mündlichen und schriftlichen Texten, wobei das Mischungsverhältnis selbst für den modernen Leser manchmal nicht greifbar und fast immer unklar ist" [@Libera1984, 18]. Oder anders gesagt: Die Vermischung zwischen dem lauten und lautlosen Lesen, die von der Antike bis in unserer Zeit festgestellt wird, entspricht einer Vermischung von Mündlichem und Schriftlichem in den Texten selbst, die im Mittelalter -- im Fall von de Libera vom 12. bis zum 15. Jahrhundert -- als Wissensstrategie entwickelt wird, um die Überzeugungskraft des Textes selbst zu stärken, wobei "einen Text zu 'lesen' ihn in Verbindungen zu bringen bedeutet" (ebd., 28). Dies zeigt die Bedeutung der Mündlichkeit in den Texten des Mittelalters als Stütze der Erkenntnisentwicklung, die insbesondere in der Praktik des Zitierens und des Exzerpierens hervorgehoben wird.

Beim Zitieren und beim Exzerpieren verwenden die Gelehrten sowohl den explizit Gesagten -- kontextualisierte Zitaten oder Erwähnungen von Textstellen aus anderen Texten bzw. von anderen Autoren --, als auch den Nahegelegten -- die Paraphrase --, als auch den Nicht-Gesagten -- die Verwendung von Textstellen Anderer ohne Verweis auf die Quelle bzw. als stillschweigende Übernahme von Textpassagen oder Argumenten Dritter. Bei den Verbindungen, die die Autoren zwischen dem Zitierten, dem Paraphrasierten und dem Plagierten an ihrem Text herstellen, geht es darum, dem Text eine "gute" Autorität zu geben, und dazu gehört es, dass das Wiederverwendete nicht als solches wahrgenommen wird: "Das Autoritätsargument wird von den Mittelalterlichen immer noch als einer der niedrigsten, wenn nicht der niedrigste theologische Ort. Der edle Gebrauch von Autorität, d.h. der richtige Gebrauch eines Textes, eines Satzes oder eines Fragments, ist still: Es ist nicht einmal die Intertextualität, sondern die Intratextualität, die Assimilation, die Abwendung, die Wiederverwendung des Anderen, die Verwischung des Unterschieds, die Totalisierung des Diskurses" (ebd. 26). Wenn das Lesen den Text insbesondere mit dem Gedächtnis des Lesers verbindet, sollen die Techniken des Zitierens und Exzerpierens das Gedächtnis des Lesers zum Vorteil von einem künftigen Leser zum Text bringen, der zum medialen Gedächtnis wird. Diese Darstellung vom Text als Rezeption des Gedächtnisses, das im Mittelalter als wichtigste Stütze des Wissens und der Kultur wahrgenommen wird [@Wenzel1995], ist gleichzeitig die Grundbedingung für die kritische Auseinandersetzung mit Texten im Sinne der Verbindungen, die ein Text zwischen anderen Texten und Autoren darstellt und schließlich veröffentlicht. Mit dem Exzerpieren als Lagerung des Gelesenen in Handschriften und Texten, als _copy/paste_ mit Schere und Klebstoff, wie in Wörterbüchern und Enzyklopädien häufig praktisiert, ändert sich bald im 18. Jahrhundert, so die These von Elisabeth Décultot [@Decultot2014], die Lesekultur und die Verschriftungspraxis im Sinne einer Veränderung des Verhältnisses zum Text, zu den Autoren und zu den Institutionen des Wissens.

Wenn im Mittelalter und in der Renaissance das Exzerpieren nach Rubriken organisiert wird, die aus der Antike geerbt werden und von Textsammlungen zu Textsammlungen fast identisch verwendet werden, ändern sich die Methoden des Exzerpierens im Lauf des 17. Jahrhunderts [@Decultot2023, 95]. Mehrere Autoren, die Texte zum methodischen Exzerpieren schreiben, unterstreichen, dass diese Kategorien, nach denen Texte exzerpiert werden, mehr nach den Bedürfnissen des Lesers und nach der Struktur vom gelesenen Text ausgewählt und verwandelt bzw. umformuliert werden sollten (die _miscellanea_ im Kontrast zu den _collectanea_; vgl. ebd., 97). Textstellen für sich selbst zu kopieren, wird im 18. Jahrhundert mehr und mehr als "das einzige richtige Mittel, den Text zu assimilieren" verstanden (ebd., 101). Diese Praxis führt zur Generation von zumindest in der Form neuen Texten aus Exzerpten [vgl. die vergleichbaren Anmerkungen für die Zeit von der Spätantik zum frühen Mittelalter in @Dusil2017; vgl. auch @Strosetzki2015] und zur Verbreitung des Exzerpierens über die Literatur und die Philosophie hinaus zu anderen Bereichen wie die Kunstgeschichte oder die experimentelle Wissenschaften als personalisierte Methode der kritischen Auseinandersetzung mit Texten und Textsammlungen zum möglichen Verbrauch in der eignen Textproduktion. Mit der Systematisierung des Exzerpieren ab dem 18. Jahrhundert wird nicht mehr einfach "narrativ" bzw. ohne Fragestellung oder ohne ein festes Ziel gelesen, sondern es wird gelesen, um bestimmte Textstellen aus Texten zu nehmen, die die Fragestellung untermauern, oder die erlauben, das vom Leser angestrebte Ziel zu erreichen [@Abbott2014]. Die Praktik des Exzerpierens wird somit zu einer der Grundlage von weiteren schriftlichen Medien wie die Rezension, die zu den Institutionen des Journalismus und der literarischen Kritik führt [vgl. dazu @Gantet2021 am Beispiel von Albrecht von Haller]. Für diese Institutionen stellt die Attraktivität von Texten den Kern ihrer Arbeit an der Entwicklung ihrer Vermittlungsstruktur dar, die sie entsprechend nicht nur rezensieren, sondern auch hierarchisieren und dazu beitragen, die Vielfalt der Lese- und Schreibpraktiken zu verbreiten und somit die Produktion von Texten nicht nur zu diversifizieren, sondern auch zu professionalisieren. Nehmen wir ein Beispiel an der Schnittstelle zwischen dem Bereich der Literatur, der Instanzen der literarischen Kritik und der Presse im 19. und im 20. Jahrhundert in Frankreich.

## Literatur, literarische Kritik und die Presse

Im Rahmen der Literatur arbeitet die spezialisierte Kritik daran, Texte nicht nur attraktiver zu machen, sondern sie in Bezug auf diese Attraktivität zu werten. Das Problem, das die spezialisierte Kritik adressiert, ist weniger dasjenige, dass Wieland und Nietzsche hervorheben, wenn sie die Rolle des Autors des Textes als _auctoritas_ und daher als Sprachrohr der richtigen Deutung der Intentionen des Autors zur Gewährleistung vom richtigen Wissen über den Text perspektivieren. Wie Roland Barthes und zu einem gewissen Punkt auch Michel Foucault nahelegen, die _auctoritas_ des Textautors über seinen Text muss nicht überschätzt werden [@Barthes1984; @Foucault1969]. Ein Text setzt zudem immer Paratexte und Intertexte voraus [@Kristeva1969], die seine Dimensionalität vervielfältigen, die aus dem Text seine eigene Interdiskursivität hervorheben [@Compagnon1979], wie sie etwa im Genre des Romans Fjodor Dostojevski berühmt gemacht hat. Diese Intertextualität kommt in den Vordergrund dessen, was die Kritiker fokussieren, wenn sie einen Text rezensieren. Es geht um den Text als eine Sammlung von Texten im Text, die die Kritiker zwar nicht unabhängig vom Autor und von den Autoren betrachten, die am Text mittelbar und unmittelbar mitwirken. Aber sie werden ihn nicht mehr nur in Bezug auf einen menschlichen _auctoritas_, sondern allgemeiner vom Standpunkt der Effektivität vom Text in der Unterstützung der Literatur und der Zirkulation -- von Ideen, Methoden, Techniken, Gefühlen, Emotionen sowie von Akteuren, die in diesem Bereich tätig sind --, von seiner Durchsetzungskraft als Mediation von möglichst allen vorstellbaren Verhältnissen zur Literatur. Mit der Kritik bekommt die Attraktivität eine wichtige Bedeutung als Ausgangs- und Endsequenz der Zirkulation in der Literatur, die entsprechend von weiteren Kollektiven und Instanzen besetzt wird. Sie werden dort aufgebaut, um die Literatur und ihre Akteure zu fördern und eine Umverteilung von textuellen Mediationen zur Effizienz der Zirkulationen in der Literatur vorzunehmen, davon die kleinen und größeren literarischen Zeitschriften sowie die Verlagen ein Beispiel sind.

Kleine und größere Zeitschriften zur Literatur werden in Europa ab dem 17. Jahrhundert veröffentlicht. Ihre Verbreitung profitiert von der wachsenden Anzahl der Akteure, die Autoren werden, davon ab dem Anfang des 19. Jahrhunderts die Mehrheit vom Groß- und Kleinbürgertum kommt [@Darnton1991; @Charle1982], sowie von der Vergrößerung des Leserkreises, die im 19. Jahrhundert mit der Verrechtlichung und der Verbreitung der Ausbildung deutlich fortschreitet. Im Unterschied zu den Verlagen arbeiten die Zeitschriften nicht primär an die Materialisierung der Attraktivität von Literatur. Sie arbeiten primär an der Attraktivität der Investition in die Literatur, davon sie die unvermeidlichen Institutionen von künstlerischen Tätigkeiten, die Vermittlungsinstanzen von Kunst und Künstlern bzw. von Zirkulationen sowohl innerhlab der Kunst als auch zwischen der Kunst und anderen Tätigkeitsbereichen in anderer Relationsstrukturen werden. Wie Pierre Bourdieu anmerkt, führt diese Institutionalisierung der Literatur -- und im allgemeinen der künstlerischen Praktiken -- zur Strukturierung der Produktion der Literatur nach einer eingeschränkten und einer großen Produktion [@Bourdieu2008]. Diese Spaltung spiegeln die Distinktionskämpfe zwischen Autoren, Literaturgenren, Zeitschriften und Verlagen wider, die die Institutionalisierung der Kunst bzw. ihre feste Verankerung in einer Ordnung von Verhältnissen mit eigener Zirkulation, Einschreibungsakten und Legitimiationsprinzipien abbildet. Diese Unterscheidung zwischen einerseits der reinen Literatur, in der Bourdieu die Gewährleistung der Automie der Literatur und der Herrschaft von Hochkultur versteht, und andererseits der unreinen Literatur als offene Tür zur niedriegeren bzw. dank der Schule gelernten literarischen Kultur, die die Großproduktion massifiziert, bildet die Grundlage der "Prinzipien der Vision und Division" der Welt, die die Institutionen der Literatur -- in erster Linie die Zeitschriften -- zu durchsetzen versuchen [etwa @Bourdieu1991, 13]. Daraus entsteht eine Dialektik der Autonomie/Heteronomie der Literatur, bei der nach Bourdieu das Außen die Autonomie der Literatur entkräften will, um ihr ihre Hierarchieprinzipien aufzuzwingen, die der komerziellen Logik der Nachfrage von Werken folgt und die Autoren entsprechend entlang der Assoziationskette "verkaufsstark, erfolgreich, berühmt" vs. "verkaufsschwach, nicht erfolgreich, unbekannt" hierarchisiert. Dagegen wehren sich die Autoren, die die Literatur lediglich nur für die Literatur unterstützen, und Hierarchieprinzipien in der Literatur entwickeln, die aus der Anerkennung zwischen Autoren auf der Grundlage von ihrer Investition in die Literatur entsteht. Für diese Künstler versteht sich die eigene Bedeutung und die Bedeutung ihrer Tätigkeit nicht nach Verkaufszahlen und Materialität, sondern nach Prestige und Attraktivität.

Deshalb gibt es zwischen diesen Zeitschriften und den Verlagen häufig Konflikte in Bezug auf die Autoren, die sie veröffentlichen [@Schuh2020], was ihre Verankerung in zwei unterschiedlichen Sequenzen der Zirkulation in der Literatur infolge der Institutionalisierung ihres unterschiedlichen Verhältnisses zur Literatur und ihrer Akteure widerspiegelt. Die Zeitschriften, die im Fall von kleinen Zeitschriften bzw. von Zeitschriften kleineres Formates, die nur einige Monate/Jahre erscheinen und derer finanziellen Situation in der Regel prekär ist, wollen Autoren -- meistens neue oder wenig bekannte Autoren -- in allen möglichen Bereichen der Literatur fördern. Dies gilt insbesondere für die kleineren Zeitschriften, die manchmal von solchen Autoren organisiert und herausgegeben werden, deren Inhalt sehr vielfältig ist, und für die es primär um die Attraktivität der Autoren geht, die dort veröffentlichen. Um diese Zeitschriften entwickeln sich Soziabilitätsnetzwerke zwischen solchen Autoren, die sich mit diesen Zeitschriften in der Literatur einschreiben. Belege von einer solchen Einschreibung liefern Autoren, die in unterschiedlichen Zeitschriften tätig sind, davon sie manchmal auch die Redakteure werden. Für diese Autoren eröffnen sich Zirkulationsmöglichkeiten zu größeren bzw. berühmteren Zeitschriften. Zu diesen größeren Zeitschriften können sie dann weiter zirkulieren (vgl. ebd., 105 beispielhaft zur Zirkulation von Alfred Jarry und Léon-Paul Fargue) und ihre Einschreibung mit den Redakteuren und Herausgebern von diesen letzteren Zeitschriften konkretisieren. Diese starke Vernetzung von kleinen und größeren Zeitschriften mit entsprechenden Soziabilitätsnetzwerken zwischen neuen bzw. kaum bekannten Autoren und berühmten Redakteuren tendiert jedoch dazu, den Verlagen die Autoren zu rauben, davon sie manchmal das Geschäftsmodell übernehmen und selbst kleine Verkaufsstrukturen entwickeln [@Mollier1999].

Insbesondere ab der Mitte des 19. Jahrhunderts bis zum Ersten Weltkrieg wehren sich die Verlagen immer mehr gegen die Macht der Zeitschriften, die sie finanziell schwächen und in eine Nebenrolle in der Unterstützung von Literatur setzen, was die Verlagen dem Einfluss von diesen Zeitschriften unterwirft. Für die Verlagen müssen die kleinen und größeren Zeitschriften "Kommunikationsmittel für die Verlagen" insbesondere in der Verbindung mit der Presse sein. Nur so können die Verlagen ihre Rolle und ihre Position in der Literatur als Multiplikatoren nicht nur für die Autoren, sondern auch für die Texte und die Zeitschriften, die sie veröffentlichen, spielen. Das Selbstverständnis der Verlagen besteht darin, dass sie sich als Institutionen sehen, die die Autoren und die Zeitschriften zur Presse und somit möglicherweise zum öffentlichen und kommerziellen Erfolg bringen (ebd., 106). Wie Léon Vanier zu Louis Lormel sagt: "'Zu Ihnen, die den Feder halten, geht der Ruhm, und mir an der Theke gehört der Verkauf. Und alles wird in der Welt der Zeitschriften besser'" (ebd., 97). Oder in den Termini der Theorie der Relation formuliert: Die Verlagen bestehen darauf und erinnern die Zeitschriften daran, dass Satellisierung nicht gleich Satellisierung ist. Eine Satellisierung innerhalb von einer Relationsstruktur zwischen den Instanzen dieser Relationsstruktur kann diese Relationsstruktur durch die Konkurrenz zwischen den Hierarchieprinzipien und den entsprechenden Hierarchien zwischen Medien, Soziabilitätnetzwerken und Akteuren schwächen und stören, die sie verursacht. Dagegen kann diese Relationsstruktur von einer Satellisierung gestärkt werden, die zwischen Relationsstrukturen entwickelt wird, wenn diese Satellisierung die Kernsequenz von einer Relationstruktur -- meistens unmittelbar -- stärkt. Genau das haben die Verlagen in ihrem Streit mit den Zeitschriften in Sicht: Um das Interesse der Presse zu wecken, sich den Weg zum breiteren Publikum zu verschaffen und dieses Publikum zur Literatur zu bringen, muss die Arbeit an der Vermittlungsstruktur von Instanzen der Literatur keine Redundanzen aufweisen, sondern im Interesse von allen bzw. von Zeitschriften sowie von Verlagen gut geteilt werden. Aber dafür muss der Kontext stimmen, und in der Zeit des Konfliktes zwischen Verlagen und kleinen wie großen Zeitschriften am Ende des 19. Jahrhundert in Frankreich stimmt der Kontext nicht mehr.

Wie Marie-Françoise Melmoux-Montaubin erklärt: "Mit der dritten Republik schrumpft der literarischen Presse und mit ihr die kritische Tätigkeit in den Zeitungen schon vor der Gesetze von 1881. Diese Wende passiert eigentlich am Ende vom Zweiten Reich: Der politische Diskurs übernimmt einen wachsenden Platz, die Liberalisierung des Regimes erlaubt bald, die eigene politische Meinung uneingeschränkt auszudrücken. Wenn das Feuilleton und die Veröffentlichung von Fiktionen in Ausschnitten noch einen kleinen Platz in den Zeitung behalten, wird die Kritik allmählich ausgeschlossen (...), als ob Kolumnisten und Journalisten davon ironisch bezeugen würden, was die Realität der 'Literatur' in der Zeitung des XIX. Jahrhunderts für sie war: eine Unterhaltung, die mit keinem essentiellen Interesse für die Literatur verbunden war" [@Melmoux2001, 939]. Die Presse, die in Frankreich im Laufe des 19. Jahrhunderts die wichtigste Instanz für die Verselbständigung einer Medien orientierten Relationsstruktur darstellt, folgt dabei dem Pfad, der ihre eigene Verselbständigung nicht nur von der Literatur, sondern auch von der Politik strukturiert hat: Die Verbindung mit dem Alltäglichen in ihrer Diversität, die ihre Rubriken und später ihr Deklinationen in zahlreichen Magazinen widerspiegeln, sowie die Kommentierung dieser Diversität in kleinen knappen Artikeln. Mit der Verbreitung des Telegraphnetzwerkes, das die Zirkulation der Information beschleunigt und das Gefühl der Augenblicklichkeit der Information vermittelt, wie Gabriel Tarde im Jahre 1901 sagt [@Tarde2006], mit der Bahn, die die Zeitungen schnell und zum niedrigen Preis überall transportiert, mit dem Anstieg der Papierproduktion parallel zur Verbesserung der Drucktechniken [@Feyel2011], verändert sich die Auffassung der Information, die Organisation der Zeitungsredaktionen und die Rolle des Journalisten. Es geht um knappen Schilderungen von konkreten Ereignissen auf der Grundlage von Reportagen, die von entsprechenden Reporters im Feld vermittelt werden und die öffentliche Meinung einerseits informieren und vertreten, andererseits befragen und messen sollen [@Kalifa2011]. Mit dem Journalismus und der Konstitution einer selbständigen Medien orientierten Relationsstruktur entsteht gleichzeitig mit dem Anspruch der neuen Organisation und der schnellen Verbreitung der Information die Feststellung, dass die Information perpetuell generiert wird und deshalb anhand von effizienten Medien kontrolliert werden sollte, wenn man nicht riskieren will, dass sie uns entwicht. Diese zwei scheinbar widersprüchlichen Ansprüche zu vereinbaren, bereiten den Weg zur Entwicklung der Überlegungen über die effiziente Verwaltung und Verbreitung von Information anhand von Rechnern vor, daraus die Forschung im Bereich der künstlichen Intelligenz entsteht, die zur Entwicklung von Transformers führt.

## Die digitale Wende

Die grundsätzlichen Operationen von Transformers weisen auf eine Fülle von Lesens- bzw. Schreibenstechniken und Praktiken, die diese Transformers in zahlreichen Verhältnissen dimensionieren und solche Verhältnisse in der Form von Algorithmen zur neuen Verbindungen von Informationsinhalten miteinander und somit zur Generierung neuer Informationen aus Sprachdateien und darüber hinaus aus allen möglichen digitalen Dateien formalisieren und verwenden. In dieser Hinsicht sind Transformers auf dem Grundsatz, wie wir es in diesem Kapitel gezeigt haben, nicht neu. Was sie neu macht, wie wir es am Beispiel der Presse am Anfang des 20. Jahrhunderts gesehen haben, ist die Fülle an Informationen, die sie behandeln und zur Verfügung von möglicherweise allen Akteuren und Kollektiven in einer sehr kurzen Zeit wenn nicht augenblicklich zum finanziellen Profit der Dienstleister stellen können, die sie konzipieren und warten. Diese Massifikation der Information unterscheidet sich zweierlei von derjenige der Presse und später des Rundfunks, des Fernsehers und selbst des Internets. Zum einen betrifft sie jeden gesellschaftlichen Tätigkeitsbereich -- von spezialisiertesten Tätigkeitsbereichen zu denen des _common sense_, der Unterhaltung, der Freizeit usw. -- und jeden ihrer Aspekten [@Zong2022]. Zum zweiten wird sie zur Verfügung von jedem Akteuren und jedem Kollektiv gestellt, der aus dieser Masse an Information seine eigenen Verbindungen gestalten und neue Informationsinhalte generieren kann. Der Transformers ist in diesem Sinne ein Super-Akkumulator und Super-Produzent von Informationen von aller möglichen Arten und entsprechend eine mächtige Mediation zur Satellisierung von anderen Relationsstrukturen durch die Medien orientierten Relationsstrukturen. Dies verdanken die Transformers der weiteren Verselbständigung von Texten und im Allgemeinen von all dem, was in Information umgewandelt werden kann, davon er der zeitgenössische Vertreter und die aktuelle Verlängerung ist. Diese Verselbständigung entspricht einer dreifachen Verschiebung der Perspektive zur Information im Bereich der digitalen Techniken.

Die erste Verschiebung ist mit dem Namen von Vannevar Bush (1890-1974) verbunden, der der Gründer des _National Defense Research Committee_ unter Roosevelt (1940) und der Leiter des _Office of Scientific Research and Development_ in den Vereinigten Staaten während und nach dem Zweiten Weltkrieg ist. Bush konzipiert in den 1920er Jahren einen elektromechanischen Rechner, der komplexe Differentialgleichungen lösen muss [@Shurkin1984, 95]. Dieser Rechner ist eigentlich eine Zusammenstellung von unterschiedlichen elektromechanischen Elementen, die insgesamt 200 Tonen wiegen und mit 300 Kilometern von Kabeln miteinander verbunden sind. Das Projekt erfreut die amerikanische Regierung und beeindruckt die Bevölkerung, für die eine solche enorme Maschine wie ein "'gigantisches mechanisches Gehirn'" aussieht [@Bowles1996, 5]. Dieses Bild übernimmt Bush in seinem Text zur Entwicklung der Forschung zu Rechnern im Jahre 1945, und in diesem Zusammenhang erwähnt er die Verbindung zwischen Rechnern und der menschlichen Intelligenz [@Bush1945]. Im Vergleich mit der Information bedeutet die Idee von Bush, dass die Entwicklung von Rechnern den Inhalt von Information fokussieren sollte, um Information gut verwalten, organisieren und in der Gesellschaft gerecht verteilen zu können. Mit der steigenden Produktion von Information gibt es das Risiko, dass Akteure und Gesellschaften von dieser Information überflutet werden. Deshalb sind die Rechner da, die dabei helfen können, es zu verstehen, welche Information wichtig bzw. notwendig ist und welche nicht. Diese erste Verschiebung, die von der formalen Media "Information" zu ihrem Inhalt geht, dass die Grundlage für den vernünftigen Umgang mit Information in den Gesellschaften nach dem Zweiten Weltkrieg bereitet, führt zu zweiten Verschiebung in der Folge Alan Turings Vision von intelligenten Maschinen.

Die zweite Verschiebung der Perspektive zur Information besteht in den Herausforderungen, die den Bushs Vorschlag mit sich bringt. Wenn es darum geht, anhand von Rechnern Informationen ab deren Inhalt zu verwalten, dann setzt es voraus, dass Rechner in der Lage sind, diese Information selbstständig inhaltlich zu bewerten. Dafür sollten die Rechner eine ähnliche Intelligenz wie die menschliche Intelligenz aufweisen, um den Inhalt von Information auswerten zu können und dabei helfen, diese Information nach ihrer Bedeutung zu hierarchisieren.




Dabei folgen diese


Deshalb einerseits schrumpfen die Konflikte zwischen Zeitschriften und Verlagen am Anfang des 20. Jahrhunderts mit einer Arbeitsteilung, die den Verlagen erlauben, ihre Position an der Schnittstelle der Satellisierungsstrategien zwischen Kunst und Presse zu stärken. Deshalb andererseits versuchen Verlagen Mediationen in der Form von unterschiedlichen Kunstgenren und Kunstformen zu unterstützen -- wenn nicht mit zu konzipieren --, wie dies mit dem Essay in der Literatur vor und nach dem Ersten Weltkrieg passiert. Der Essay "führt auf die Notwendigkeit zurück, legitime Formen für die Veröffentlichung von wissenschaftlichen und aktuellen Inhalten seitens der Literaturverleger zu erfinden und Schriftsteller dazu zu mobilisieren, deren anfängliche Position weitgehend auf der Ablehnung dieser Produktion beruht" (ebd.). Der Essay soll einerseits die Avant-Garde in der Literatur satellisieren und als eine Mediation dargestellt werden, die am Beispiel von alltäglichen Situationen den Talent des Künstlers hervorhebt, wenn er gleichzeitig ein breites Publikum ansprechen muss. Als Mediation soll er sowohl die eingeschränkten und die Großproduktion innovativ miteinander verbinden. Für die Verlagen geht es grundsätzlich um solche Formaten, um solche verdichteten Mediationen, die in der Lage sind, sehr unterschiedliche Verhältnisse zu Kunst und Kultur abzufangen zum Vorteil der Stärkung ihrer Position als eine gesellschaftliche Vermittlungsinstanz von Kunst in der soziokulturellen Relationsstruktur. Sie sollen in der Lage sein, sowohl mit den Künstlern und Zeitschriften als auch mit der Presse umzugehen, um ihre Kapazität, andere Mediationen als ihre eigenen Merkmale zum eigenen Vorteil dieser Mediation zu harmonieren und zu transportieren.



Eine solche Situation, die wir im Konflikt zwischen Zeitschriften und Verlagen am Ende des 19. Jahrhundert finden, entspricht jedoch einem in Zeit und Raum eingeschränkten Zustand der Institutionalisierung, die in der Kunst stattfindet und mit der Entstehung von einer Avant-Garde korreliert. Nehmen wir ein Beispiel. Was zeigt uns die innerlichen Revolution der Malerei in Frankreich mit dem _Salon des Refusés_ in der Mitte des 19. Jahrhunderts, die Bourdieu als der Ausgangspunkt zur Konstitution von einem autonomen Feld der Kunst und entsprechend als Moment der Bildung von einer Avant-Garde in der Malerei interpretiert? Sie ist nicht nur der _acte fondateur_ der Kunst als Feld in Frankreich, davon die strukturierenden Folgen nur dieses Feld betreffen würden. Sie unterstützt eine andere Art der Produktion von Kunst, eine andere Verwendung von Kunsttechniken, andere Kriterien zur Bewertung von einem Kunstwerk. Der _Salon_ stärkt gleichzeitig die Attraktivität der Kunst durch die Aufmerksamkeit, die sein Verstoß gegen die bisher akzeptierten Regeln der Kunst in der Gesellschaft aufweckt, davon die Sichtbarste die Transgression des Verhältnisses von Kunstwerken auf eine gesellschaftlich geteilte Auffassung und Wahrnehmung der Realität ist. In der Malerei wie in der Literatur wird die _auctoritas_ zum Vorteil der Mediationen dieser Autorität -- Gemälde, Dichtung, Romanen usw. -- angefochten, die entsprechend auf zahlreiche Verhältnisse zur Kunst und Kultur öffnet. Kunst bedeutet deshalb im Verständnis der Gesellschaften ab dem 19. Jahrhundert nicht mehr nur der Gegenstand, das Kunstwerk, sondern die Ideen, die Konzepte, die Perspektiven, die Umwandlung von Techniken und Traditionen sowie von entsprechenden Autoren und Strömungen, die in einem Kunstwerk mehr oder weniger explizit erwähnt bzw. zitiert werden. Es eröffnet sich eine Welt von zahlreichen und sehr unterschiedlichen Korrespondenzen zwischen dem Inhalt von einem Kunstwerk, seine Form, was er zeigt und was in ihm wahrgenommen oder von ihm verstanden wird. Diese Akkumulationskraft von Mediationen der Kunst, die ein wichtiges Ergebnis der Institutionalisierung der Kunst darstellt, führt seblbst bei der Avant-Garde und bei den kleinen Zeitschriften, die dieser Avant-Garde eine Stimme und eine Sichtbarkeit verleiht, zum Verständnis, dass eingeschränkte und große Kunstproduktion nicht nur kommunizieren, sondern auch kommunizieren müssen. Oder wie Olivera am Beispiel der Literatur sagt: "Die neuen, aus der Avantgarde hervorgegangenen Verlage waren mit der Notwendigkeit konfrontiert, Zugang zu einem breiten Publikum zu haben und den größtmöglichen Bereich der 'allgemeinen Literatur' abzudecken, ohne das symbolische Kapital zu verlieren, das mit der Tatsache verbunden ist, dass sie die 'reine' Literatur verkörpern, es sei denn, sie würden ein kleiner Verlag von einem kleinen Kreis bleiben" [@Olivera2002, 105].



## Die Rolle der Presse

Ab dem 17. Jahrhundert haben künstlerische Zeitschriften zur Vervielfältigung und zur Stratifizierung des Angebots von Texten mit entsprechenden Publika und mit entsprechenden Techniken des Lesens, des Interpretierens und des Schreibens beigetragen.
