---
title: "Das Künstlerleben leben"
indent: true
output:
    html_document: default
csl: chicago-author-date.csl
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Die Abweichungen von einer idealen Reziprozität im Laufe der Einschreibungen von Akteuren in Zirkulationen und in Relationsstrukturen kann in der Kunst besonders gut beobachtet werden. In diesem Kapitel wollen wir ein solches Beispiel auf der Grundlage einer internationalen Untersuchung zu Künstlerinnen und Künstlern behandeln, die nicht vollständig von ihrer künstlerischen Tätigkeit leben können und häufig darauf angewiesen sind, einer zusätzlichen Beschäftigung abseits ihres künstlerischen Schaffens nachzugehen und eine Stellung auf dem Arbeitsmarkt zu beziehen, um wirtschaftlich ihre Exsitenz abzusichern. Dieses Beispiel hilft dabei, zwei für die Theorie der Relation tragende Merkmale ins Zentrum zu stellen und diese anhand empirischen Materials zu illustrieren und zu erklären. Das erste Merkmal betrifft das Grundaxiom der Theorie der Relation, wonach es weder eine _ideale_ Relation noch eine _ideale_ Reziprozität (vgl. Kapitel 2) gibt, sondern vielmehr Abweichungen von einer idealen Reziprozität und demzufolge Abweichungen von einer idealen Zirkulation, die die Besonderheit der Zirkulation der Akteure ausmachen, sie in Akteurkategorien übersetzen und sie auf diese Kategorien verteilen. Das zweite Merkmal betrifft dagegen den Wechsel von Relationsstrukturen, zu denen die Zirkulation von Akteuren führen kann und die in der Regel dann mit erheblichen, daraus resultierenden Belastungen an der Seite der Akteure einhergehen können, so ihre Zirkulation in einer Relationsstruktur nicht stabilisiert werden kann.

Das Datenmaterial, das wir in diesem Kapitel verwenden, wurde von Olga Kisseleva im Rahmen ihres internationalen Kunstprojekts mit dem Titel _Double vie_ zum Doppelleben der Künstler erhoben und über mehrere Jahre hinweg gesammelt [vgl. URL: https://icca.univ-paris13.fr/double-vie-positionnement-socio-professionnel-des-artistes/]. Es umfasst 25 Künstlerinnen und Künstler, die über ihr Doppelleben, d. h. sowohl über ihre kreativ-künstlerische als auch ihre existenzsichernde Tätigkeit, berichten. Dieses Material wurde von Kisseleva anschließend mit den Kunstwerken der befragten Künstler:innen verbunden und im Rahmen von Ausstellungen gezeigt [@Kisseleva2011; vgl. auch URL: https://vimeo.com/38367747}; URL: https://ensa-dijon.fr/double-vie-dolga-kisseleva/]. Die befragten Künstler:innen, die vor allem im Bereich digitaler Kunst tätig sind, hat Kisseleva im Laufe ihrer verschiedenen Reisen getroffen. Sie arbeiteten in unterschiedlichen Ländern wie etwa Frankreich, Brasilien, Rumänien, China, den USA oder Russland. Mit ihnen hat Kisseleva Einzelgespräche geführt. Die Künstler und Künstlerinnen wurden gebeten, über ihr eigenes Leben zu sprechen, während dessen sie gerade entweder ihrer Arbeit in der Kunst oder ihrer Tätigkeit als Arbeitnehmer:in nachgingen, was zusammen filmisch dokumentiert wurde. Die Gespräche beginnen alle mit derselben Ausgangsfrage: Wie leben Sie ihr Doppelleben? Die filmischen Aufzeichnungen der 25 Gespräche wurden im Laufe der Zeit transkribiert und uns zur Untersuchung überreicht, wobei 2 Künstler:innen von der Untersuchung ausgeschlossen wurden, da sich das entsprechende Transkriptmaterial zu stark von dem der anderen 23 unterschied [vgl. URL: https://icca.univ-paris13.fr/double-vie-positionnement-socio-professionnel-des-artistes/]. Mit der Analyse der verbleibenden 23 Interviewtranskripte verbanden und verbinden sich in der Hauptsache zwei zentrale Zielstellungen:

Das erste Ziel bestand in dem Anspruch, besser zu verstehen, wie und mit welchen Folgen die befragten Künstler:innen ihr Leben zwischen ihrer künstlerischen Tätigkeit und ihrer wirtschaftlichen Tätigkeit organisierten. Dabei zeigt unsere Untersuchung wenig überraschend, dass ein solches Doppelleben für alle befragten Künstler zu schmerzhaften Erfahrungen und Erlebnissen führt. Nichtsdestotrotz möchte die überwiegende Mehrheit der befragten Kunstschaffenden weder die Kunst verlassen noch ihre künstlerisch-kreative Arbeit aufgeben. Welche Gründe für dieses Beharrungsvermögen im Bereich der Kunst vonseiten der Kunschaffenden genannt werden, führt uns zur zweiten Zielstellung der vorliegenden Untersuchung.

Um die zwei oben genannten Merkmale der Theorie der Relation sowohl zu illustrieren als auch zu erklären, führen wir in diesem Kapitel eine weitere Analyse der von Kisseleva erhobenen Daten mit Hilfe einer Topic-Modell-Analyse durch. Die Topic-Modell-Analyse ist eine Klassifikationsalgorithmen basierte quantitative Methode zur Modellierung qualitativer Daten [vgl. bspw. zu Anwendungsfeldern der Topic-Modell-Analyse vgl. @monoPapilloudSchultze2023, 3-50, 155-186; vgl. auch @monoPapilloudHinneburg2018, 19-42]. Im Rahmen dieses Kapitel unterstützt uns diese Methode dabei, die Zirkulation von Akteuren zwischen Relationsstrukturen und in unserem Fall zwischen den Bereichen der Kunst und der Wirtschaft auf der Grundlage der Gespräche mit den 23 befragten Künstlern zur Gestalt ihres Doppellebens zu rekonstruieren und zu veranschaulichen. Auf dieser Grundlage werden wir einen Sonderfall der Akteurzirkulation beleuchten, dem die Theorie der Relation besondere Aufmerksamkeit widmet, wenn sie besagt, dass Akteure nicht nur die Relationsstruktur wechseln können, sondern auch zwischen Relationsstrukturen oszillieren können. Das Doppelleben der befragten 23 Künstler:innen entspricht in der Tendenz einer solchen Oszillation zwischen Relationsstrukturen und skizziert, wie schwierig es für Kunstschaffende sein kann, eine Position in einer Relationsstruktur und in Sequenzen und Tätigkeitsbereichen dieser Relationsstruktur zu stabilisieren. Eine solche Tendenz untersuchen wir im Folgenden vertiefend, zuvor kommen wir jedoch zu den theoretischen Überlegungen, die in der Theorie der Relation mit dem Wechsel der Relationsstruktur assoziiert sind.

## Der Wechsel der Relationsstruktur

Der Wechsel der Relationsstruktur ist für Einzelakteure grundsätzlich eine banale Zirkulationsmöglichkeit, die ihnen entweder mittelbar oder unmittelbar zur Verfügung steht [vgl. @PappilloudSchultze2022, 143]. Sie setzt voraus, dass der Widerstand dieser Akteure _gegen_ die Relationsstruktur, in der sie sich befinden, so ausgeprägt ist, dass er ihre Einschreibung in dieser Relationsstruktur entsprechend schwächt oder stört und ihre Zirkulation verhindert [vgl. ebd., 177-178]. Ein solcher Wechsel der Relationsstruktur ist häufig mit Erwartungen auf die Stabilisierung der eigenen Position in einer anderen Relationsstruktur und mit Erwartungen auf Erwartungen etwa in Bezug auf bessere Lebensplanungsmöglichkeiten verbunden [vgl. ebd., 172ff.]. Für die Akteure, die stärker von den strukturellen Determinanten einer Relationsstruktur betroffen sind und bei denen die bezogene Position ihre Zirkulation entsprechend einschränkt [vgl. Abb. 5.1 ebd., 176], stellt der Wechsel der Relationsstruktur eine mittelbare Zirkulationsmöglichkeit dar [vgl. ebd., 171f.]. Für diese Akteure ist also der Wechsel der Relationsstruktur bedingt und somit keineswegs selbstverständlich. Er ergibt sich daraus, dass diese Akteure ihre Position durch Relation wechseln und weiter zirkulieren müssen, bis sie sich in der Lage befinden, einen solchen Wechsel der Relationsstruktur tatsächlich konkretisieren zu können. „Weiter zirkulieren“ bedeutet hier zweierlei.

Eine erste Bedeutung der Zirkulation von Akteuren ergibt sich daraus, dass Akteure ihre Position im Sinne der stärkeren Unterstützung ihrer Sequenz in einer Relationsstruktur und schließlich ihrer Relationsstruktur umstellen. Bei einer solchen Positionsumstellung handelt es sich für die entsprechenden Akteure darum, weitere Einschreibungsakte mit Instanzen ihrer Relationsstruktur zu leisten, um zu den Akteurkategorien zu gelangen, die das Hauptmerkmal der Relationsstruktur am meisten unterstützen. Die Umstellung von Positionen geht entsprechend für diese Akteure mit einem Aufstieg in der Relationsstruktur einher, was sich wiederum in der Erwartung dieser Akteure insofern widerspiegelt, als sie sich immer mehr wie ein unabdingbares Element ihrer Relationsstruktur verstehen und aufgrund ihrer ausgeprägten Unterstützung und der damit einhergehenden Position in der ersten Akteurkategorien umittelbar an der Verbreitung ihrer Relationsstruktur teilhaben und teilnehmen [vgl. hierzu ebd., 150-161]. Selbst wenn eine solche Positionumstellung allen Akteuren in einer Relationsstruktur zur Verfügung steht, hängt die Wahrscheinlichkeit, dass sie tatsächlich umgesetzt wird, einerseits vom Widerstand der Akteure ab, Einschreibungsakte mit Instanzen ihrer Relationsstruktur zu verwirklichen [vgl. ebd., 180-192]. Dies setzt andererseits voraus, dass diese Instanzen tatsächlich vorhanden sind und solche Einschreibungsakte fördern. Die Wahrscheinlichkeit einer tatsächlichen Umstellung von Positionen hängt also vom Trias Einschreibung, Widerstand und Reziprozität ab, wobei sich jedwede Positionsumstellung dieser Art nicht etwa linear entwickelt, sondern vielmehr symmetrisch. Wo Einschreibungsakte mit einem stärkeren Widerstand _für_ die Relationsstruktur und mit einer stärkeren Reziprozität bzw. mit Instanzen im Dienst der Stärkung der Kernsequenz von einer Relationsstruktur einhergehen, die das Hauptmerkmal der Relationsstruktur unmittelbar unterstützen, werden folglich die Möglichkeiten für die Akteure verstärkt, die Relationsstruktur zu wechseln [vgl. ebd.]. Symmetrisch gilt diese Überlegung ebenfalls: Wo Einschreibungsakte mit einem stärkeren Widerstand _gegen_ die Relationsstruktur und mit einer schwächeren Reziprozität durch die Einschreibung mit Instanzen, die mit Instanzen im Dienst der Hauptsequenz einer Relationsstruktur konkurrieren, einhergehen, werden die Möglichkeiten für die Akteure verstärkt, die Relationsstruktur zu wechseln [ebd.].

Im ersten Fall haben wir es mit aufsteigenden Zirkulationswege und im letzten Fall mit absteigenden Zirkulationswegen zu tun [vgl. dazu ebd., 192-198]. Obgleich diese Zirkulationswege in entgegengesetzten Richtungen verlaufen, üben sie nichtsdestotrotz vergleichbare Wirkungen auf die Akteure aus, die auf diesen Wegen zirkulieren. Aufsteigende Zirkulationen führen Akteure dazu, die Sequenz zu verabsolutieren, in der sie sich befinden, und die verabsolutiertesie Sequenz als neue Hauptsequenz mit entsprechenden Instanzen zu definieren, die die Zirkulationsdynamik in der ganzen Relationsstruktur neu entwickeln muss. Dies ruft Widerstände von Akteuren und Steuerungsmaßnahmen von Instanzen hervor, die die Relationsstruktur unterstützen, was die Akteure, die ihre Sequenz zu verabsolutieren trachten, dazu bewegt, zu der Relationsstruktur zu wechseln, in der ihre Sequenz die Hauptsequenz der Relationsstruktur darstellt [vgl. ebd., 187]. Im letzten Fall haben wir absteigende Zirkulationswege mit Akteuren, die ihre Relationsstruktur verlassen, um in eine andere Relationsstruktur mit der Hoffnung auf bessere Zirkulationsmöglichkeiten und entsprechende besser geeignete Instanzen zu wechseln [vgl. ebd., 182f.]. Von der Sequenz, in der sie ihre Relationsstruktur verlassen, gelangen sie dann in der entsprechenden Sequenz einer anderen Relationsstruktur, auf die sie sich sozialisieren müssen, um sich neue Zirkulationsmöglichkeiten und mögliche aufsteigende Zirkulationswege zu verschaffen. Strukturell ändert sich ihre Situation nicht. Sie müssen Zeit in die Einschreibung mit den Instanzen der neuen Sequenz in der Ankunftsrelationsstruktur investieren, was Aufwand bedeutet, um solche aufsteigenden Zirkulationswege zu bahnen. Die auf diesen Akteuren lastenden strukturelle Determinanten werden jedoch gleichzeitig auch dadurch subvertiert, dass die allgemeine Zirkulationsdynamik, an der sie teilhaben, anders als diejenige in der verlassenen Relationsstruktur verläuft, was ihnen die Chance gibt, neu anzufangen. Die Situation für die Akteure, die durch ihren aufsteigenden Zirkulationsweg die Relationsstruktur wechseln, stellt sich analog vor.

Der Wechsel der Relationsstruktur kann allerdings ebenfalls in Verbindungen zu weiteren Akteuren und Akteurkategorien gebracht werden, die weder das Hauptmerkmal von einer Relationsstruktur stark unterstützen noch das Hauptmerkmal von einer Relationsstruktur schwach unterstützen. In ihrem Ansatz zur Kategorisierung der Akteure sieht die Theorie der Relation vier Akteurkategorien vor, von denen die erste Kategorie den ersten Fall und die vierte Kategorie den letzten Fall am besten illustrieren. Wenn wir uns nun den Akteuren der zweiten und der dritten Kategorie zuwenden, so ist festzuhalten, dass sich die beiden erstgenannten Fälle nicht ohne Weiteres auf die zweite und dritte Akteurkategorie übertragen lassen, weil sich die Akteure der zweiten und dritten Kategorien im Unterstützungsgrad respektive in der Ausprägung ihres Widerstands sowohl von den Akteuren der ersten als auch von den Akteuren der vierten Kategorien abweichen. So unterstützt die zweite Akteurkategorie das Hauptmerkmal von einer Relationsstruktur weniger stark als die erste Akteurkategorie, wohingegen die dritte Akteurkategorie in einem weniger stark ausgeprägten Widerstand _gegen_ das Hauptmerkmal von einer Relationsstruktur steht als die vierte Kategorie und entsprechend die Relationsstruktur immer noch bis zu einem gewissen Grad unterstützt, selbst wenn diese Unterstützung weniger stark ausgeprägt ist als bei der zweiten Akteurkategorie [vgl. Abb. 5.1 ebd., 176]. In diesem Zusammenhang ist es nützlich, daran zu erinnern, dass die Theorie der Relation in Bezug auf ihren Stratifikationsansatz nicht nach einer Akkumulationslogik (von Ressourcen, Privilegien, Vorteilen usw.) argumentiert, um diese Akteurkategorien in Bezug auf strukturelle und morphologische Determinanten zu beschreiben, sondern nach einer Opferlogik. Die Akteure der ersten und vierten Kategorie eint, dass sie bei ihrer Zirkulation verlieren können bzw. nichts zu verlieren haben. Im Vergleich dazu verbindet sich mit demselben Muster der Aufopferung für die Akteure der zweiten und dritten Kategorie eine andere Frage, die sich überlegen, wie viele Opfer die Unternehmung weiterer Schritte in ihrer Zirkulation von ihnen verlangen würde bzw. wieviel sie bereit sind, zu verlieren. Deshalb gehen wir mit der Theorie der Relation davon aus, dass die erste und die vierte Akteurkategorien im Vergleich zu den zwei anderen Akteurkategorien weniger von den strukturellen Determinanten ihrer Relationsstruktur an ihrer Zirkulation gehindert und weniger von den Bestimmungen ihrer Position durch die Relationsstruktur eingeschränkt werden. Diese Akteure gewinnen mit ihrer Zirkulation an Distanz zu ihrer Relationsstruktur, und ihre Zirkulation spiegelt diese Distanz wider. Für die Akteure der ersten Kategorie führt dieser Gewinn an Distanz nicht unbedingt zum Wechsel der Relationsstruktur. Er kann ebenso gut zum Wechsel der Sequenzen in derselben Relationsstruktur führen, wenn diese Akteure weiterhin die Bedeutung der Relationsstruktur über diejenige ihrer Sequenz stellen. Für die Akteure der vierten Kategorie kommt lediglich der Wechsel der Relationsstruktur in Frage, weil die Akteure der vierten Akteurkategorie _gegen_ die Relationsstruktur insgesamt widerstehen und zwar unabhängig davon, in welcher Sequenz dieser Relationsstruktur sie sich befinden. Für diese Akteure setzt also der Bezug einer anderen Position abseits ihrer Relationsstruktur unmittelbar voraus, die Relationsstruktur zu wechseln. Dabei kann beobachtet werden, dass Akteurkategorien, die aufsteigende Zirkulationswege aufbauen, ihre Zirkulationswege mehr als Akteure diversifizieren können, die absteigende Zirkulationswege bahnen, was wiederum zu vermehrten Zirkulationsmöglichkeiten innerhalb sowie zwischen Relationsstrukturen führen kann.

Wenn wir uns nun den Kunstschaffenden und ihrem Doppelleben zwischen künstlerischen und wirtschaftlichen Tätigkeiten zuwenden, so sei vorausgeschickt, dass von den 23 befragten Künstlerinnen und Künstlern nicht alle Akteurkategorien, von denen wir gesprochen haben, gleichermaßen abgebildet werden. Selbst wenn wir davon ausgehen, dass das Doppelleben von Kunstschaffenden auch unter Akteuren der ersten Kategorie beobachtet werden kann, so befinden sich unter den befragten Künstlern und Künstlerinnen, wie wir noch zeigen werden, keine Akteure, die dieser Akteurkategorie zugeordnet werden können. Konkret heißt das, dass der von Kisseleva erhobene Datensatz keine Akteure enthält, die Teil einer Kunstelite wären; sei es auf der Ebene der Investition in die Kunst selbst, der Repräsentation der Kunst in der Gesellschaft, der Verwirklichung von Kunstobjekten auf dem Kunstmarkt, oder sei es auf der Ebene der gesellschaftlichen Attraktivität von Kunst, deren Akteuren, Gegenständen oder deren Projekten. Vielmehr handelt es sich bei den von Kisseleva befragten Künstlern und Künstlerinnen vielmehr um Akteure, die sich an der Schwelle zwischen der dritten und vierten Akteurkategorien befinden. Zudem gehören sie alle der Sequenz Investition im Bereich der Kunst mit einer starken Priorisierung der Mobilisation von weiteren Akteuren und Aktanten um ihre künstlerische Praxis bzw. um ihr Kunstvorhaben an, das sie zur Legitimation bringen möchten. Ferner verstehen und entwickeln sie ihr Doppelleben sehr unterschiedlich und zwar je nachdem, ob für sie ihre künstlerische Tätigkeit tatsächlich noch in Zirkulation in der Kunst gebracht werden kann, oder ob sich für sie eine solche Zirkulation zusehends schwieriger gestaltet, bis sie schließlich keinen Anlauf mehr nehmen und sich dazu veranlasst sehen, die Kunst zu verlassen bzw. zur wirtschaftsorientierten Relationsstruktur zu zirkulieren.

Aus Sicht der Theorie der Relation ist eine solche Dynamik des Doppellebens der Künstler, wenn wir sie in Verbindung mit den Akteurkategorien in Relationsstrukturen bringen, kein seltenes Phänomen. Eine solche Dynamik stellt vielmehr eine weit verbreitete Art und Weise dar, das Künstlerleben zu leben. Aus diesem Grund ist es auch unwahrscheinlich, dass eine solche Dynamik am Rande der Kunst von einigen wenigen Außenseitern entwickelt wird, was gleichsam die romantische Figur des Künstlers und das Künstlerleben -- nach der Formel "die Kunst nur um ihrer selbst willen" -- zu dekonstruieren beiträgt. Ein solcher Ansatz ist in der zeitgenössischen Kunstsoziologie, die nach einem makrosoziologischen Ansatz zum Künstlerleben argumentiert, keineswegs neu.

## Zeitgenössische makrosoziologische Ansätze zum Künstlerleben

Es gibt eine bedeutsame zeitgenössische Literatur, die nach einem makrosoziologischen Ansatz zur Kunst [etwa @Francastel1989; @Heinich2004; @Luhmann2008; @Schwietring2010; @Reckwitz2016], zu ihrer Entwicklungsgeschichte als Tätigkeitsbereich in der Moderne [wie z.B. @Becker1998; @Bourdieu2008; @Moulin2009; @Reckwitz2012], zu den Künstlern, den damit verbundenen sozialen Milieus und dem Publikum der Kunst [u.a. @Gerhards1997; @Chiapello1998; @Bourdieu2006; @Fourmentraux2012] und zu den Kunstinstitutionen wie etwa Museen [vgl. etwa @Wall2006; @Baumann2016] argumentiert. Im Vergleich dazu ist die Literatur, die nach einem solchen Ansatz das Künstlerleben im Allgemeinen und im Besonderen das Doppelleben der Künstler zwischen Kunst und Wirtschaft untersucht, eher als überschaubar einzustufen.

Ein wiederkehrendes Werk, das in diesem Zusammenhang kontinuierlich Erwähnung findet, bilden die Untersuchungen von Pierre Bourdieu zum Feld der Kunst und insbesondere zum Feld der Literatur. Die Überlegung Bourdieus zur Kunst, wie sie sich als Feld ab dem 19. Jahrhundert konstituiert und strukturiert [vgl. @Bourdieu2008], ruht auf dem Prinzip der Abwertung bzw. der Leugnung der sozialen Realität als Grundlage erstens der sozialen Position des Künstlers in der Gesellschaft und zweitens der Position, die er im Feld der Kunst bezieht. Der Künstler definiert sich selbst als "Schöpfer", dessen Schöpfungspraktiken "einheitlich" und mit anderen sozialen Praktiken "nicht vergleichbar" sind [@Bourdieudelsaut1975, 20]. Durch seine Kunst zelebriert der Künstler sein ästhetisches Verhältnis zur (sozialen) Realität als Ausdruck seiner Unabhängigkeit von den sozialen Determinanten und damit vom Einfluss der anderen sozialen Felder -- bei Bourdieu insbesondere dem Einfluss vom Feld der Wirtschaft und dem der Politik [@Bourdieu2008, 104]. Aus diesem "Bruch mit der Alltagswelt" entsteht das Künstlerleben als eine soziale Erfindung der Künstler (ebd., 100), in dessen Zentrum ausschließlich die Kreativität der Schöpfer selbst und nebstdem ihre Schöpfungen Platz finden und auf weitere Bereiche des Alltags erweitert werden sollten [@Bourdieu1975]. Dieses Künstlerleben trägt in sich die Prinzipien der Vision und Division der Welt, die der Kunst eigen sind und das Feld der Kunst um die symbolische Autorität von herrschenden Elitekünstlern -- die die "Autorität der Erfahrung des Unsagbaren" repräsentieren, wie Bourdieu sagt (ebd., 12) -- und mithin den Kampf zur Definition und Aneignung dieser Autorität strukturieren.

Instabil wird dieser Ansatz jedoch, wenn die Ansprechpartner der Kunstschaffenden in ihrer gesellschaftlichen Umwelt berücksichtigt werden, die Bourdieu weder in der Kunst, noch in der Wirtschaft, noch in der Politik, sondern in den Zwischenräumen zwischen Kunst, Wirtschaft und Politik situiert. Diese "Mittlerpersonen zwischen künstlerischem und ökonomischem Feld, also die Verleger, Galeristen, Theaterleiter, vor allem aber auch für die mit der Durchführung des Staatsmäzenatentums betrauten Beamten" sind die Akteure, die die Entwicklung des Feldes der Kunst dynamisieren [@Bourdieu2008, 115]. Sie bringen die Prinzipien der Wirtschaft ins Feld der Kunst ein, wodurch die "Mittler" sowohl eine ökonomische Marktlogik in die Kunst einführen als auch eine Distanzierung der Künstler zu dieser Marktlogik je nachdem verursachen, wie die Künstler ihr Künstlerleben von materiellen Interessen und insgesamt von der gesellschaftlichen Alltagswelt fern halten möchten. Diese Verortung von Mittlerpersonen an der Schnittstelle zwischen Kunst und Wirtschaft -- ähnliche Beispiele liefert Bourdieu zur Schnittstelle zwischen Kunst und Politik, wenn er vom Künstler als Intellektuellen spricht (vgl. ebd., 209ff.) -- stellt jedoch eine bedeutsame Schwierigkeit in Bezug auf Bourdieus Erklärung zur Entstehung des Kunstfeldes im 19. Jahrhundert dar. Für eine Theorie, die nach einem positionellen Ansatz argumentiert, fehlt eine Begrüdung, die erklären würde, wieso solche Mittlerpersonen nicht in einem bestimmten Feld positioniert sind bzw. ob eine Position zwischen Feldern mit der Feldtheorie begründet werden kann. Die Erwähnung dieser Mittlerpersonen scheint stattdessen eher das Argument der Schließung von Feldern, das die sozialen Felder als solche konstituiert und das der allgemeinen Dialektik der Verkennung/Anerkennung folgend auf der Verteidigung der symbolischen Macht in den sozialen Feldern ruht, zu gefährden. Tatsächlich stellt sich die Frage, ob das Feld der Kunst nur aufgrund der Durchsetzung des Künstlerlebens in der Gesellschaft existiert oder ob dieses Künstlerleben, seine Durchsetzung und seine entsprechende Transformation nicht vieleher als ein kollektives Produkt verstanden werden sollte, zu dem nicht allein die Künstler, sondern ebenso sehr die Künstler in Relation mit den Verlegern, den Galeristen, den Theaterleitern, den Ausstellungskuratoren und ferner den Kritikern oder auch den Kultur- und Kunstzeitschriften beitragen, von denen Bourdieu ebenfalls spricht. Mit Blick auf eben diesen Problemschwerpunkt im Kern der Feldtheorie Bourdieus wurden bisher aus dem Bereich makrosoziologischer Ansätze zur Kunst zwei Alternativen vorgeschlagen.

Eine erste Alternative formuliert Eve Chiapello mit ihrer Erwähnung vom Künstler-Managern, d. h. von Künstlern, die Techniken und Strategien aus der Wirtschaft bzw. aus der Branche des Managements übernehmen und in Unterstützung ihrer Laufbahn in der Kunst einsetzen. Diese Künstler, die ebenfalls Mitglieder der zeitgenössischen Avant-Garde inkludieren, stellen sich nicht gegen die Welt der Wirtschaft, sondern sie arbeiten mit wirtschaftlichen Instanzen der Kunst zusammen, die ihnen dabei helfen, ihre Kunstwerke zu produzieren und zu verkaufen [@Chiapello1998, 37ff.]. Mit diesem Argument hebt Chiapello hervor, dass die Organisationen und die Akteure, die in diesen Organisationen arbeiten -- die Mittlerpersonen Bourdieus --, nicht in einem Zwischenraum zwischen der Kunst und der Wirtschaft tätig sind, sondern ihre Tätigkeit gemeinsam mit den Künstlern unmittelbar innerhalb der Kunst entwickeln. Sie unterstreicht, dass die Opposition zwischen Wirtschaft und Kunst, die Bourdieu als eine Opposition zwischen einer Logik der materiellen und einer Logik der symbolischen Profitakkumulation versteht, an der Seite der Künstler die Angst hervorruft, dass ihr Kunstwerk durch die kapitalistische Marktlogik beeinflusst bzw. verändert wird. Wie Chiapello diesbezüglich betont, ist im Kunstmilieu die prinzipielle Auffassung vorherrschend, wonach "die Regeln der Kunst mit denen des Managements nichts zu tun haben" [@Chiapello1997, 77]. Wie Bourdieu konstatiert demnach auch Chiapello einen Gegensatz zwischen Schöpfung und Management: "Nichts ist für einen Schöpfer, der sich als total versteht, unerträglicher, als wenn ihm Arbeitsregeln, ein Thema, eine Technik, Fristen, ein Budget auferlegt werden, das nicht überschritten werden darf, wobei der Gipfel die Retusche des eigenen Werks durch andere ist" (ebd., 80). Doch obgleich das Management in den Instanzen der Kunst tatsächlich unermüdlich versucht, das Kunstprojekt zu kontrollieren, so wird diese Kontrolle keineswegs im Sinne einer vollständigen Machtausübung vorgenommen, die ausschließlich darauf abzielen würde, dass "die Kontrolle die Kunst zerstör[e]" (ebd., 81) bzw. die Kunst zur reinen Ware im Dienst des kapitalistischen Marktes der symbolischen Güter umgewandelt werde. Häufig vertragen Kunstprojekte weitaus höhere Kontrollmaßnahmen, ohne dass dies gleichsam zu schlechter Kunst oder gar zur Zerstörung der Kunst führe (ebd.). Oder anders gesagt: Wenn das Management im Rahmen von Kunstinstanzen Formalisierungsoperationen entwickelt, dann nicht einfach deshalb, weil diese Instanzen die Kunst abwerten oder zerstören wollen. Umgekehrt geht es bei diesen Kunstinstanzen darum, sich mit den Künstlern in der Relation zur Kunst als Projekt und als Grundlage der Tätigkeit von Künstlern und Kunstinstanzen einzuschreiben. Diese Einschreibung ist sowohl für die Künstler und ihre Legitimität als Künstler als auch für die Kunstinstanzen und deren Legitimität als Instanzen der Kunst essentiell. Deshalb ist diese Kontrolle, die die Kunstinstanzen auf die Künstler und ihre Kunstprojekte ausüben, ein wichtiges Element zur Förderung der Zusammenarbeit an solchen Kunstprojekten und zu ihrer entsprechenden (positiven oder negativen) Sanktionierung. Aus diesem Grund stellt die ausgeübte Kontrolle für die Instanzen der Kunst auch keine einfache "kybernetische Kontrolle" dar (ebd., 103), sondern eine Kontrolle, die den Anspruch hat, wenig formalistisch bzw. weniger bürokratisch zu erfolgen. Dies kennzeichnet diese Instanzen der Kunst, die zwar an der wirtschaftlich-materiellen Verwirklichung von Kunstprojekten arbeiten, gleichzeitig jedoch weder nach den strengen rationalisierenden Regeln von üblichen wirtschaftlichen Firmen operieren noch die romantische Vorstellung der Künstler als unerschöpflichen Schöpfer füttern.

Nach Chiapello erlebt die Kunst seit den 1980er Jahren eine "Revolution" (ebd.) in dem Sinne, dass diese spezifische Wirtschaft, die in der Kunst von solchen Kunstinstanzen entwickelt wird, zwar nach angepassten Regeln des Managements von Kunstprojekten vorgeht, zugleich aber nicht nur in der Kreativität des Künstlers die Quelle des eigenen Profits sieht, sondern auch die Bedingung der eigenen Legitimität. Andreas Reckwitz als Vertreter der zweiten Alternative zu Bourdieus Kunstsoziologie erkennt in einer solchen Entwicklung, die er grundsätzlich mit den Veränderungen der Kultur des Subjektes in den modernen Gesellschaften in Verbindung bringt, jedoch keinesfalls eine ausschließlich gesellschaftliche Verbreitung der Kreativität, die mit der entsprechenden Entwicklung von anschließenden Tätigkeiten und Tätigkeitsbereichen einhergeht. Die Kreativität wird seiner Einschätzung nach mindestens ebenso zum Imperativ umformuliert: "Kreativität umfasst in spätmodernen Zeiten [...] eine Dopplung von Kreativitätswunsch und Kreativitätsimperativ, von subjektivem Begehren und sozialer Erwartung: Man will kreativ sein und soll es sein" [@Reckwitz2012, 10]. Selbst wenn diese These über die Kunst hinaus entwickelt wird, um eine kultursoziologische Theorie der (Spät)Moderne in ihren unterschiedlichen Entwicklungsstufen aus der Theorie der Kulturen des Subjektes in Geltung zu bringen [vgl. etwa @Reckwitz2017], spielt die Kunst eine wesentliche Rolle als Ausgangspunkt der Verbreitung der Kreativität auf die ganze Gesellschaft. Mit der Kunst ab dem 17. und insbesondere im 19. Jahrhundert wird die romantische Vorstellung des Künstlerlebens, worin sich die "'Distanz zur Notwendigkeit'" als die Grundlage zur "umfassenden Ästhetisierung der Gesellschaft" etabliert, zur Quelle und zur Referenz einer Lebenspraxis, in deren Zentrum das affektive Verhältnis zum Selbst und zu anderen als einer Form der Selbsterfüllung und der befriedigende Beziehung zur sozialen Welt steht [@Reckwitz2012, 34-35]. In der Kunst entstehen ebenfalls die ersten Dispositive zur Unterstützung und zur weiteren Verbreitung der Kreativität, die über die Kunst hinaus greifen [zur historischen Genealogie des Kreativitätsdispositivs entlang von vier Phasen vgl. ebd., 52-53]. Diese Dispositive in Form von Kunstinstanzen, Kunstprojekten und Kunstgegenständen, die das allgemeine Publikum erreichen sollen, führen eine ästhetische Sozialität in die Gesellschaft ein, die weitere gesellschaftliche Bereiche außerhalb der Kunst -- von der Wirtschaft bzw. der Welt der Arbeit und der Massenmedien bis hin zum Internet und den zeitgenössischen sozialen Medien -- dazu bewegt (ebd., 54), die Kreativität auf die ganze Gesellschaft zu verbreiten. Die Künstler als Produzenten einer neuen ästhetischen Lebensführung sind gleichzeitig die Akteure in der Gesellschaft, die als 'Kreateure' zur Produktion des ästhetischen Neuen als konstante gesellschaftliche Forderung beitragen, was wiederum die (Spät)Moderne dynamisiert. Mit der Entwicklung des Surrealismus und der Pop Art im 20. Jahrhundert sind die Künstler zudem nicht nur Produzenten von Kunstwerken, also "Kreateure" (ebd., 54), sondern "Initiatoren von Atmosphären" (ebd., 114), Gestalter von Stimmungen, Designer von Räumlichkeiten, Visonäre des Zeitgeistes, die als "Arrangeure" (ebd., 115) von den Medien zum Star verwandelt werden (ebd., 122). Diese Entwicklung betrifft allerdings nicht alle Künstler. Die meisten von ihnen müssen zeigen, dass sie kreativ sind bzw. dass ihre Kreativität zur ästhetischen Sozialität und zur daraus entstandenen Verbreitung der Singularität in der (spät)modernen Gesellschaft effizient beiträgt. Die Kreativität, einst die distinktive Eigenschaft des Künstlers, ist also in der Moderne zum verallgemeinerten Druckmittel im privaten wie im öffentlichen Leben geworden und als solche wirkt sie auch auf die Künstler zurück. Selbst wenn sich Reckwitz' Argumentation zur Kunst und den Künstlern in der (Spät)Moderne vorerst in dem bis hierher Dargelegten erschöpft, so legt er doch nahe, dass das Künstlerleben im Sinne der romantischen Figur des Künstlers, der sich der Kunst nur um ihrer selbst willen widmet, das geworden ist, was sie bedrängt und ihre Zirkulation sowohl in der Kunst als auch in der Gesellschaft erschwert. Eine solche Auffassung vom Künstlerleben trifft zum Teil auch auf die 23 befragten Künstler und Künstlerinnen zu, wenn sie über ihr Doppelleben zwischen Kunst und Wirtschaft sprechen, obgleich weniger die Kreativität als vielmehr ihre Beschäftigung auf dem Arbeitsmarkt als belastend empfinden, wie unsere Topic-Modell-Analyse zeigt.

## Topic-Modell-Analyse des Doppellebens der Künstler

Zur Auswertung der verschriftlichten Angaben der 23 befragten Künstlern, die uns geliefert wurden, haben wir die Methode der Topic-Modelling anhand von unserer Anwendung _Multi-Text Analyser_ bzw. MTA (https://github.com/cp1972/mta-app.git) verwendet. Wie diese Methode zu verstehen und zu verwenden ist, haben wir im Rahmen von einem Beitrag zu Topic-Modelling veranschaulicht [@monoPapilloudHinneburg2018]. In einer anderen Untersuchung zur Forschung an hohen Technologien in der Medizin haben wir die Kompatibilität dieser Methode mit dem theoretischen Rahmen der Theorie der Relation ausführlich diskutiert [@monoPapilloudSchultze2023]. Deshalb sparen wir dem Leser die technischen Details zu dieser Methode und konzentrieren uns lediglich auf eine kurze Beschreibung dessen, wie diese Methode qualitatives Datenmaterial auswertet.

Als auf Klassifikationsalgorythmen basierte Methode erlaubt MTA, Argumentationsstrukturen zu modellieren, sie für jeden einzelnen Befragten zu erforschen und die Befragten auf der Grundlage ihrer Aussagen mit großer Genauigkeit und einem Minimum an Deutungsverzerrung voneinander zu unterscheiden. Diese Modelle von qualitativen Daten eröffnen den Zugang zu den Organisationsprinzipien des Diskurses der Befragten, d. h. zu den Topics, die ihre Antworten strukturieren. In Bezug auf die Theorie der Relation erlaubt eine solche Methode unmittelbar, die Verbindung zwischen den Befragten und den Akteurkategorien zu untersuchen, von denen wir oben gesprochen haben. Mittelbar liefert sie Interpretationselemente zur Zirkulation dieser Akteure innerhalb der Sequenzen von einer Relationsstruktur und zwischen Relationsstrukturen und daher zu ihrer Positionierung bzw. zu ihrer Positionsumstellung zwecks ihrer Einschreibung in einer Relationsstruktur.

Im Falle der 23 befragten Künstler führt die Modellierung ihrer Aussagen zu vier Topics, also zu vier semantischen Strukturen oder vier Leitthemen, die alle Aussagen der Befragten dimensionieren. Diese Themen sind die folgenden:

  - das erste Thema (Topic 0) bezieht sich auf die künstlerischen Projekte der Befragten, die ihnen sehr am Herzen liegen und einen sehr wichtigen Platz in ihrem Leben einnehmen bzw. eingenommen haben; es bezieht sich ebenfalls auf ihre Arbeit als Arbeitnehmer auf dem Arbeitsmarkt in der Wirtschaft, die, weil sie ihre künstlerische Praxis nicht mehr wie gewünscht entwickeln können, immer mehr an Bedeutung gewinnt;
  - das zweite Thema (Topic 1) konzentriert sich auf die Selbstdarstellung im Rahmen der künstlerischen Tätigkeit, den körperlichen Ausdruck bei dieser Tätigkeit und den Ausdruck von Gefühlen und Emotionen, die diese Tätigkeit hervorruft; zudem enthält dieses Topic Elemente der positiven Betrachtung der Arbeit auf dem Wirtschaftsmarkt, die die Künstler, die dieses Topic unterstützen, zu neuen Ideen inspiriert und Emotionen hervorruft, die sie wiederum im Rahmen ihrer künstlerischen Arbeit aufgreifen und verarbeiten;
  - das dritte Thema (Topic 2) bezieht sich auf die Beschreibung der Arbeit der Befragten auf dem Wirtschaftsmarkt: die Aufgaben, die sie zu erfüllen haben, die Beziehungen zu anderen Arbeitskollegen und den Platz, der diese Arbeit in ihrem Leben einnimmt; diese Arbeit betrachten die Künstler mit Pragmatismus bzw. als eine notwendige Beschäftigung zur materiellen Unterstützung der künstlerischen Karriere;
  - das vierte Thema (Topic 3) betrifft die Zeit, die die Arbeit der Künstler auf dem Wirtschaftsmarkt erfordert; selbst wenn diese Arbeit notwendig ist, um alltäglichen Bedürfnissen und Verpflichtungen -- etwa das Bezahlen von Rechnungen und der Miete -- nachzukommen, sind die Kosten einer solchen wirtschaftlichen Tätigkeit für die Künstler hoch, die eine solche Tätigkeit häufig als eine Belastung empfinden, in die sie idealerweise so wenig Zeit wie möglich investieren wollen.

Quantitativ betrachtet sind diese Themen voneinander unabhängig (vgl. Abbildung 1). Diese Unabhängigkeit der Themen ist deshalb wichtig, weil sie gewährleistet, dass die generierten Themen keine Unterthemen eines oder mehrerer der vier Themen bilden, die sich aus unserer Analyse ergeben.

<embed src="Kap-3-Kunst-Graphiken/Similar_Topics.pdf" type="application/pdf">

Im Rahmen der Auswertung nach Topics kann beobachtet werden, wie sich die Themen in den Protokollen verteilen (vgl. Abbildung 2). Dadurch wird ersichtlich, wie jeder Befragte durch seine Aussagen eine Hierarchie zwischen den Themen, die er/sie am meisten hervorhebt, und den Themen herstellt, die nur am Rande oder gar nicht angesprochen werden und entsprechend bedeutungslos sind.

<embed src="Kap-3-Kunst-Graphiken/Part_Topics.pdf" type="application/pdf">

Die Abbildung 2 zeigt einerseits eine ungleiche Verteilung der Themen unter den Befragten. Andererseits lässt sie auch einige Ähnlichkeiten in der Art und Weise erkennen, wie sich die Themen in den Aussagen einiger der Befragten verteilen. Diese Ähnlichkeiten sind für unsere Analyse wichtig, weil sie darauf hinweisen, dass es, selbst wenn nicht alle Befragten dieselben Themen betonen, dennoch Gemeinsamkeiten zwischen einigen der befragten Künstlerinnen und Künstler gibt, die auf Ähnlichkeiten bezüglich der Erfahrung mit ihrem Doppelleben hindeuten. Augrund dessen ließe sich postulieren, dass diese befragten Künstler und Künstlerinnen auf Basis ähnlicher Erfahrungen eines Doppellebens Gruppen von Gleichgesinnten bilden.

Um dieses Postulat zu stabilisieren, untersuchen wir, ob solche Ähnlichkeiten mit der Art und Weise verbunden werden können, wie die befragten Künstler und Künstlerinnen die vier Themen ansprechen und in welcher Reihenfolge sie diese thematisieren. Um jede Zweideutigkeit zu vermeiden, sei daran erinnert, dass es sich bei solchen Ähnlichkeiten nicht um Ähnlichkeiten des linguistischen Inhalts (ähnlicher Begriffe) oder der von unseren Befragten verwendeten Sprache (ähnlicher Aussagen) handelt, sondern um eine Ähnlichkeit in der Art und Weise, wie sie verstärkt ein Thema unterstreichen und dieses exponieren und entsprechend weniger andere Themen ansprechen oder behandeln. Die Abbildung 3 stellt solche Ähnlichkeiten je nachdem dar, ob die befragten Künstler bestimmte Themen auf Kosten anderer Themen bevorzugen (grüne Quadrate) und welche Themen sie nicht bevorzugen (rote Quadrate).

<embed src="Kap-3-Kunst-Graphiken/Similar_Texts.pdf" type="application/pdf">

Unsere Topic-Modell-Analyse liefert damit also drei Ergebnisse. Das erste Ergebnis betrifft die Anzahl der Themen und die Bedeutung dieser Themen. Das zweite Ergebnis bezieht sich auf die Verteilung der Themen in den Ausführungen der befragten Künstlerinnen und Künstler und das dritte Ergebnis informiert schließlich darüber, wie Gruppen von Befragten erkannt werden, die eine vergleichbare Hierarchiesierung zwischen den hervorgehobenen bzw. vernachlässiten Themen vornehmen und vor diesem Hintergrund eine vergleichbare Priorisierung der vier Themen in ihren Aussagen unterstützen und zeigen. Diese drei Ergebnisse können folgendermaßen vertieft werden:

Wie unsere Abbildung 3 zeigt, weisen die Gruppen von Befragten jeweils eine unterschiedliche Homogenität auf. Innerhalb jeder Gruppe gibt es entsprechend Befragte, die dazu neigen, eine bestimmte Art und Weise, wie sie die vier Themen innerhalb ihrer Aussage priorisieren, stärker als andere Gleichgesinnten zu unterstützen. Innerhalb jeder Gruppe gibt es daher eine Variabilität der Unterstützung priorisierter Themen. Dasselbe Argument lässt sich auch in Bezug auf die Priorisierung der Themen fruchtar machen. So lässt sich anhand der Abbildung 3 ebenfalls beobachten, wie die Priorisierung bzw. Hierarchisierung der Themen, die eine Gruppe von befragten Künstlern vornimmt, stärker bzw. schwächer als die Priorisierung der Themen ist, die andere Gruppen unterstützen bzw. hervorheben, und wie daraus eine Hierarchisierung unterschiedlicher Priorisierungsordnungen entsteht. In der Summe bedeuten beide Aussagen, dass wir die drei Ebenen von unserer Topic-Modell-Analyse gleichzeitig berücksichtigen können, d. h. wir können in einem Zuge die folgenden drei Analyseebenen betrachten:

  - die Gewichtung, die die Befragten den einzelnen Themen in ihren Aussagen verleihen;
  - die Gruppen von Befragten, die auf der Grundlage der besagten Gewichtung gebildet werden;
  - das Prinzip, das die Priorisierung der Themen in jeder Gruppe bestimmt, d. h. das Leitthema, das eine Gruppe besonders unterstützt und unter das die Mitglieder derselben Gruppe die anderen Themen einordnen.

Die Abbildung 4 stellt eine solche Verknüpfung unserer drei Analyseebenen graphisch dar.

<embed src="Kap-3-Kunst-Graphiken/Result.pdf" type="application/pdf">

Die Abbildung 4 zeigt einerseits die Klassifizierung der von jeder Gruppe unterstützten Priorisierung bzw. Hierarchisierung der Themen auf der Grundlage eines Themas, das alle Gruppen insgesamt am stärksten unterstützen. Andererseits bildet sie aber auch die die Künstlerinnen und Künstler als Einzelakteure ab und zeigt, in welcher Weise diese jeweils ein Thema mehr (dunklere, d.h. rotfarbene, und breitere Verbindungslinien) oder weniger (hellere, d. h. orangefarbene, und schmalere Verbindung) unterstützen. Diesbezüglich lässt sich Abbildung 4 entnehmen, dass das von allen Künstlern am stärksten unterstützte Hierarchisierungsprinzip aus dem Topic 3 besteht, gefolgt von Topic 1 und von Topic 2. Das bedeutet gleichsam, dass die befragten 23 Künstlerinnen und Künstler in ihrer Gesamtheit das Topic 0 in einem sehr geringen Ausmaß unterstützen und entsprechend das Topic 0 lediglich von drei der befragten Künstler -- namentlich von Traces, Kamilla und Lekha -- in relativ ähnlicher Gewichtung hervorgehoben wird, um ihre Erfahrungen als Kunstschaffende auf dem Wirtschaftsmarkt zum Ausdruck zu bringen. Wenn wir nun zum Inhalt der Aussagen zurückkehren, von denen wir in Abbildung 4 einige zur Illustration und zum besseren Verständnis der Topics eingeblendet haben, können wir die Bedeutung der vier Topics in ihrer Hierarchisierung und Priorisierungsordnung je Gruppe von Kunstschaffenden wie folgt konkretisieren:

  - das Topic 3, das gemessen an allen Aukünften der Kunstschaffenden am stärksten vorherrscht und von Boxe, Trolley, Florent, Elevation, Nalinda und Veda am ausgeprägtesten hervorgehoben wird, bezieht sich auf den Wunsch, sich vor allem und möglichst nur der Kunst widmen zu können. Wie bei allen Befragten muss auch diese Künstlergruppe, deren Mitglieder nicht allein von ihrer künstlerischen Tätigkeit leben können, in der Wirtschaft arbeiten. Wenngleich diese Arbeit auf dem Wirtschaftsmarkt als notwendig wahrgenommen wird, so wird sie doch auch vornehmlich als eine Belastung empfunden, der man zwar so gut es geht nachkommt, die man jedoch auch so schnell es geht los werden möchte. Was also für diese Gruppe von Kunstschaffenden am meisten zählt, ist die künstlerische Tätigkeit, die um jeden Preis fortgesetzt werden muss;
  - das Topic 1, das in Bezug auf alle befragten Künstlerinnen und Künstler im Anschluss an Topic 3 am zweithäufigsten Unterstützung findet -- insbesondere aber von Agnieszka und Nathalia am stärksten und von David, Luiza, Odile und Pillow in starkem Maße priorisiert wird -- betrifft die Vorteile, die die Mitglieder dieses Künstlerkollektivs in ihrer Arbeit auf dem Wirtschaftsmarkt sehen und die von ihnen trotz der damit einhergehenden einschränkenden Aspekte als eine Inspirationsquelle für ihre künstlerische Praxis wahrgenommen wird. Diese Künstlerinnen und Künstler verstehen entsprechend ihr Doppelleben nicht etwa als Opposition zwischen der künstlerischen Tätigkeit einerseits und ihrer Lohnarbeit andererseits, sondern vielmehr als eine gegenseitige Befruchtung beider Tätigkeitsbereiche. Das Nachgehen einer Lohnarbeit hat für dieses Künstlerkollektiv also auch positive Auswirkungen und zwar sowohl auf ihre künstlerische Praxis als auch auf ihre Person, weil sie sich auf diese Weise gleichsam besser in die Gesellschaft integriert fühlen;
  - das Topic 2 folgt den Topics 3 und 1, und es wird am deutlichsten von Arnold, Claudia, Cube, Garspard und Maria unterstützt. Diese Künstlergruppe sieht ihre Arbeit auf dem Wirtschaftsmarkt vornehmlich als ein notwendiges Übel an, da sie ausschließlich über diesen Weg die Fortsetzung ihrer künstlerischen Praxis zu gewährleisten imstande sind. Folglich perspektivieren sie ihre Tätigkeit als Arbeitnehmer abseits des Künstlerischen vorrangig auf pragmatische Weise: Sie ist nützlich, um das tägliche Leben zu finanzieren (in Ähnlichkeit zur Künstlergruppe, die in Bezug auf ihr Doppelleben prioritär das Topic 3 unterstützt) und sie kann somit dazu beitragen, weitere Schritte in der künstlerischen Karriere zu leisten;
  - das Topic 0 findet am wenigsten Unterstützung unter den befragten Kunstschaffenden und wird, wie bereits erwähnt, in ähnlich starkem Maße von Kamilla, Lekha und Traces zum Ausdruck ihres Doppellebens berücksichtigt. Diese Künstlergruppe sieht sich zunehmend oder ganz und gar außerstande, neben ihrer Erwerbsarbeit auf dem Wirtschaftsmarkt weiterhin in ihre künstlerische Tätigkeit zu investieren, wie es sich die Mitglieder dieser Gruppe wünschen würden. In den meisten Fällen ist dies eine derart schmerzhafte und enttäuschende Erfahrung, dass diese Künstlerinnen und Künstler sich dazu veranlasst sehen, die Kunst ufzugeben und sich fortan vollends ihrer Arbeit auf dem Wirtschaftsmarkt zu widmen.
  - die Künstler DHL und KPD liefern Aussagen, die die vier Topics wenig unterstützen; bei DHL gibt es eine stärkere, wenn auch eine nichtsdestotrotz relativ schwache Verbindung zum Topic 2, selbst wenn dieser Akteur ebenso die Topics 1 und 3 thematisiert und in geringem Umfang unterstützt; Der Kunstakteur KPD untersützt demgegenüber eher stärker das Topic 1 und in schwächerem Maße das Topic 2. Jedoch kann insgesamt bemerkt werden, dass die Verbindungen von DHL und KPD zu diesen Topics im Vergleich zu den anderen Befragten sehr schwach sind (schmale Verbindungen), was im Vergleich zu den Inhalten ihrer Aussagen nicht weiter überrascht, denn DHL wie KPD sprechen weder eingehend über ihr Doppelleben und ihre Erfahrungen damit noch über ihrer Kunst oder ihrer Tätigkeit in der Wirtschaft.

Aus diesen vier Themen und den damit einhergehenden Priorisierungsaordnungen, die vonseiten der befragten Kunstschaffenden vorgenommen werden, ergeben sich vier nuancierte Ausdrücke bzw. Vergegenwärtigungen des Verhältnisses zwischen dem Widerstand der Kunstakteure _für_ und dem Widerstand der befragten Kunstakteure _gegen_ die soziokulturell-orientierte Relationsstruktur als Grundlage ihrer Zugehörigkeit zu Akteurkategorien in der Kunst, zur Umstellung ihrer Position in der Kunst und zu ihrem Wechsel der Relationsstruktur, dessen genaue Bedeutung wir im Folgenden vertiefen.

## Das Doppelleben der Künstler im Wechsel der Relationsstruktur

Wie oben schon erwähnt, gehören die befragten Kunstschaffenden in unserer Untersuchung keiner "Kunstelite" an. Es handelt sich also weder um Künstlerpuristen noch um Puristen der soziokulturell-orientierten Relationsstruktur -- die erste Akteurkategorie in der Kunst [vgl. @PapilloudSchultze2022, 64-68; vgl. auch 90-94, 169, Abb. 5.1, 176]. Ferner befinden sich unter den Kunstschaffenden unseres Samples keine Künstler der zweiten Akteurkategorie, die zu diesen Künstlerpuristen aufsteigen möchten, d.h. die eine aufsteigende Zirkulation in der Kunst zu entwickeln versuchen, welche sie zu der ersten Kategorie von Akteuren in der Kunst platzieren würde [ebd., Abb. 5.1, 176; 171, 175]. Bei den befragten Künstlern und Künstlerinnen handelt es sich vielmehr um Akteure, die Schwierigkeiten haben, ihre Zirkulation in der Kunst zu entwickeln, weshalb die Mitglieder der vier Gruppen von Kunstschaffenden bei den Akteuren der dritten und der vierten Kategorien zu situieren sind [ebd., 168, 171-172, 263-268]. In diesen zwei Kategorien sind die Akteure entweder mehr von den strukturellen bzw. positionellen als von den morphologischen bzw. zirkulatorischen Determinanten der soziokulturell-orientierten Relationsstrukturen betroffen (Akteure der dritten Kategorie) oder aber mehr von den morphologischen als von den strukturellen Determinanten (Akteure der vierten Kategorie) betroffen [vgl. ebd., Abb. 5.1, 176]. Das heißt wiederum, dass die untersuchten Kunstakteure viel mehr für ihre Anerkennung als Künstler kämpfen müssen, weshalb diese Akteure auch deutlich stärker mit der Frage ringen, ob sich ein solcher Kampf überhaupt lohnt. Aus der Positionierung in der dritten und vierten Akteurketegorie resultieren zudem eine Reihe von Schwierigkeiten, andere Akteure in Unterstützung ihrer angestrebten und zu realisierenden Kunstprojekte zu mobilisieren. Solch ungünstige Umstände wirken sich auf ihre künstlerische Tätigkeit entsprechend bremsend aus, weil sie diese weniger regelmäßig und kontinuierlich entwickeln können. Zudem treffen sie in ihrer Position in diesen Akteurkategorien vornehmlich auf Instanzen der Kunst, die nicht in der Breite der Kunst, sondern in spezifischen Teilsequenzen der Kunst arbeiten [zu den teilsequenzspezifischen Instanzen vgl. ebd., 241-244], was in der Konsequenz bedeutet, dass diese Istanzen die befragten Akteure nicht auf die Breite der Kunst hin sozialisieren und fördern können, sondern lediglich auf spezifische Kunstbereiche hin. Diese Nähe zu kleinteiligeren Instanzen des Kunstbetriebs trägt dazu bei, ihre Einschreibung in der Kunst in viele Akten zu zerstückeln.
Das heißt, die Künstler dieser Kategorien müssen eine Reihe von Instanzen konsultieren, um sich mit den von ihnen konsultierten Instanzen in die Kunst einzuschreiben, von diesen Instanzen bei der (Weiter)Entwicklung ihrer künstlerischen Tätigkeit gefördert zu werden und in der Folge ihre Zirkulation in der soziokulturell-orientierten Relationsstruktur überhaupt entwickeln zu können; eine Arbeit also, die den Künstlern und Künstlerinnen viel Aufwand, viel Zeit und Nerven und entsprechend einen langen Atem abverlangt. Dies ist auch die Ursachenlage dafür, dass Künstler der dritten und vierten Kategorie im Verhältnis zu Kunstschaffenden der ersten und zweiten Kategorie schneller altern, da diese sich ausschließlich auf wenig entwickelten Zirkulationswegen bewegen. Aus diesem Grund ließe sich vermuten, dass die Befragten unseres Samples mit ihrer Arbeit auf dem Wirtschaftsmarkt eine Möglichkeit gefunden und erhalten hätten, auf ihre Zirkulation beschleunigend zu wirken bzw. sie zu ihrem Vorteil zu korrigieren. Die Mitglieder der vier Gruppen von Kunstschaffenden betrachten jedoch eine solche Umstellung ihrer Zirkulation mit variierender Ambivalenz.

Wenn wir den Widerstand der befragten Künstler fokussieren, merken wir, dass wir zwei entgegengesetzte Gruppen haben, die einerseits das Topic 3 und andererseits das Topic 0 stark unterstützen. Die ersten Künstler und Künstlerinnen um das Topic 3 widerstehen stark _für_ ihre künstlerische Praxis und entsprechend stark _gegen_ eine Tätigkeit auf dem Wirtschaftsmarkt. Die zweite Gruppe von Kunstschaffenden um das Topic 0 widerstehen einerseits relativ stark _gegen_ die künstlerische Praxis, in deren Rahmen sie schmerzhafte Erfahrungen gemacht haben, und andererseits in geringem Maße _gegen_ eine Tätigkeit auf dem Wirtschaftsmarkt, der sie allerdings ohnehin nachgehen müssen, um mit den Herausforderungen ihres Alltags zurechtzukommen. Die erste Künstlergruppe illustriert Akteure der dritten Akteurkategorie in der Kunst gut, und in dieser Kategorie bezeichnen sie insbesondere die Akteure von der dritten Schicht an der Schnittstelle zur dritten Schicht der zweiten Akteurkategorie in der Kunst [vgl. ebd., 175-176]. In Symmetrie zu Akteuren der zweiten Kategorie handelt es sich bei diesen Künstlern der dritten Schicht von Kategorie drei um solche, die sich mit der Kunst und mit der romantischen Figur des Künstlers ("sich der Kunst nur um ihrer selbst willen zu widmen") stark identifizieren und nur in die Kunst investieren möchten. Aber im Unterschied zu Kunstschaffenden der zweiten Akteurkategorie reicht ihre Zirkulation in der Kunst nicht aus, um eine derart ausschließliche Investition in die Kunst zu ermöglichen, zu unterstützen und den Aufstieg in die zweite Akteurkategorie zu gewährleisten. Deshalb erleben diese Künstler auch immer wieder Auszeiten, in denen sie einer Erwerbsarbeit auf dem Wirtschaftsmarkt nachgehen, selbst wenn sie dabei nicht anstreben, sich selbst in einer solchen wirtschaftlichen Tätigkeit mit Instanzen der Wirtschaft einzuschreiben. Sie hören mit ihrer Kunsttätigkeit nur vorübergehend auf, ohne jedoch mit ihrer Zirkulation in der Kunst aufzuhören, um zu einer anderen -- in unserem Fall wirtschaftsorientierten -- Relationsstruktur zu zirkulieren. Ihre Arbeit auf dem Wirtschaftsmarkt sehen sie als eine unnütze aber notwendige Klammer in ihrem Künstlerleben, worauf sie jedoch nicht verzichten können und die sie deshalb so schnell als möglich wieder ad acta legen wollen.

Die zweite Gruppe von Künstlern in Unterstützung des Topics 0 illustrieren Akteure in der Kunst, die zur vierten Akteurkategorie und in dieser Kategorie besonders zu den Akteuren gehören, die eine Position in der ersten Schicht beziehen [vgl. ebd., 174]. Solche Akteure bereiten sich darauf vor, die Kunst und die entsprechende soziokulturell-orientierten Relationsstruktur zu verlassen. Für diese Künstlerinnen und Künstler ist ein Leben in der Kunst nicht mehr das, was zu ihrer Zirkulation und daher zu ihrer Laufbahn beiträgt, was ihre Erwartungen erfüllt und sie im Leben bewegt [vgl. ebd., 154-159]. In der Kunst werden sie immer stärker bedrängt, bis ihre künstlerische Tätigkeit ihre Zirkulation so beeinträchtigt, dass sie ihr Leben zerstört. Für diese Kunstschaffenden gibt es nicht mehr sehr viel andere Möglichkeiten, als von der Kunst und der soziokulturell-orientierten Relationsstruktur zur wirtschaftsorientierten Relationsstruktur zu wechseln, was die meisten dieser Künstler und Künstlerinnen als den nächsten Schritt in ihrer Zirkulation verstehen, den sie nicht nur mit mehr oder weniger starkem Bedauern angehen, sondern auch mit starker Kritik gegen die Kunst und ihre Instanzen verbinden.

Die zwei anderen Gruppen von befragten Künstlern um das Topic 1 und das Topic 2 sind ebenfalls gute Beispiele für Akteure der dritten Akteurkategorie in der Kunst. Ihre künstlerische Tätigkeit relativieren sie im Vergleich zu Akteuren der zweiten Kategorie, für die ihre künstlerische Tätigkeit nicht relativiert werden darf. Nichtsdestotrotz haben diese Künstler die Kunst noch nicht aufgegeben. Sie versuchen, ein _modus vivendi_ zwischen ihrer Tätigkeit in der Kunst und ihrer Tätigkeit in der Wirtschaft zu finden. Es handelt sich daher um Gruppen von Künstlern, die sich zwar an der Schwelle befinden, in die Kategorie vier abzusteigen und von dort aus die Kunst und ihre Relationsstruktur für die wirtschaftsorientierte Relationsstruktur zu verlassen. Gleichzeitig halten sie sich jedoch an der Kunst und ihrer künstlerischen Tätigkeit fest, leisten Widerstand entweder _für_ den Erhalt ihrer Position in der dritten Akteurkategorie oder _für den Aufstieg in die zweite Akteurkategorie und stemmen sich insofern mit aller Kraft _gegen_ den Abstieg in die vierte Kategorie von Akteuren, als sie die Hoffnung nicht aufgeben, ihre Position doch noch umstellen zu können und/oder eine aufsteigende Zirkulation in der Kunst für sich zu beanspruchen. Für beide Künstlergruppen verbindet sich also ihr hochgradig ausgeprägtes Beharrungsvermögen in der Kunst mit dem stetigen Bestreben nach einem Positionswechsel in der Kunst, selbst wenn diese Möglichkeit mit der Zeit immer geringer wird: Sie müssen demnach in der Kunst verbleiben, da ansonsten jedewede Perspektive auf eine wie auch immer geartete Zirkulation in der Kunst verschwände. Die Arbeit, die sie in der Wirtschaft ausüben, kommt ihnen somit gelegen, weil eben diese wirtschaftsnahe Tätigkeit es ihnen erlaubt, ihre Position in der Kunst aufzubewahren oder strategisch zu nutzen, um ihre Möglichkeiten einer aufsteigenden Zirkulation auszubauen.

Die Künstler und Künstlerinnen, die das Topic 1 am deutlichsten unterstützen, liefern das beste Beispiel für diejenigen Akteure der dritten Kategorie in der Kunst, die in der ersten Schicht dieser Kategorie und somit an der Schwelle zur dritten Schicht der vierten Akteurkategorie positioniert sind [vgl. ebd., Abb. 5.1, 176]. Es handelt sich um Kunstakteure, deren Chance, in die vierte Akteurkategorie herab zu zirkulieren, relativ groß ist und sie in der Folge dazu führen kann, die Kunst zu verlassen, um eine Zirkulation in der Wirtschaft zu entwickeln. Nichtsdestotrotz ist es für diese Künstler und Künstlerinnen noch nicht an der Zeit, tatsächlich abzusteigen und die Relationsstruktur zu wechseln, weil ihre Arbeit auf dem Wirtschaftsmarkt maßgeblich dazu beiträgt, ihrer künstlerischen Tätigkeit weiter nachzugehen und ihren Platz in der Kunst zu bewahren. Nichtsdestotrotz besteht für sie aber auch die Chance, dass die Vorteile, die sie aus ihrer wirtschaftlichen Tätigkeit ziehen, sie schließlich doch dazu führt, die Kunst aufzugeben und sich ihrer Arbeit auf dem Wirtschaftsmarkt vollständig zu widmen.

Die Künstlerinnen und Künstler, die das Topic 2 am meisten unterstützen, sind dagegen gute Beispiele für Akteure in der zweiten Schicht der dritten Akteurkategorie in der Kunst. Für sie geht es darum, sowohl ihre künstlerische Tätigkeit als auch ihre Tätigkeit auf dem Wirtschaftsmarkt nicht zu verlieren, damit sie in der Kunst verbleiben können. Die Tätigkeit auf dem Wirtschaftsmarkt unterstützt ihre Position in der Kunst, selbst wenn diese Position schwer umzustellen ist, da sie sich auf einem wenig entwickelten Zirkulationsweg in Richtung der zweiten Akteurkategorie bewegen, und von den betroffenen Kunstschaffenden entsprechend erfordert, dass sie einen nicht geringen Teil ihrer Zeit in die Tätigkeit auf dem Wirtschaftsmarkt investieren. Nichtsdestotrotz bleibt ihr Verhältnis zu dieser letzten Tätigkeit von qualitativer utilitaristischer Natur: Es wird in der Wirtschaft gearbeitet, aber es wird nicht in der Wirtschaft zirkuliert. Dort findet keine Einschreibung statt. Die einzige Einschreibung, die stattfinden soll und stattfinden kann, ist die in der Kunst, selbst wenn sich diese Akteure gleichsam darüber bewußt sind, dass eine solche Einschreibung eine sehr prekäre Zuflucht bedeutet, die insbesondere dann zum Scheitern verurteilt ist, so sie ihren Arbeitsplatz oder ihre Tätigkeit auf dem Wirtschaftsmarkt verlören.

Diese Deutung der Ergebnisse von unserer Analyse der 23 befragten Kunstschaffenden mit dem Instrumentarium der Theorie der Relation zeigt ein interessantes Merkmal in Bezug auf die Zirkulation selbst. Dort unterscheidet sich die Theorie der Relation von den makrosoziologischen Ansätzen zum Doppelleben der Künstler, die wir oben im Konstrast zu Bourdieus Soziologie der Kunst mit Chiapello und Reckwitz dargestellt haben.

## Zirkulationsmerkmale des Doppellebens der Künstler

Ein erstes Merkmal der Zirkulation der befragten Künstlerinnen und Künstler, das unmittelbar aus unserer Analyse hervorgeht, betrifft den stetigen Wechsel dieser Kunstschaffenden zwischen Ihrer künstlerischen Tätigkeit und ihrer Arbeit auf dem Wirtschaftsmarkt. Für fast alle Befragten reicht ein Wechsel der Tätigkeit, der zu einem Wechsel der Relationsstruktur führen würde, an sich nicht aus, damit eine Zirkulation in einer anderen Relationsstruktur stattfindet. Dafür muss eine (doppelte) Einschreibung in einer Relationsstruktur stattfinden, die, wenn sie nicht stattfindet, die Akteure häufig zwischen Relationsstrukturen bis zur Erschöpfung der eigenen zirkulatorischen Potentiale und auf entsprechende Kosten der Lebensführung oszillieren lässt. Nur die Mitglieder derjenigen Künstlergruppe, die im Vergleich mit den anderen Befragten das Topic 0 in stark unterstützen, wollen die Relationsstruktur wechseln bzw. die soziokulturell-orientierte Relationsstruktur für die wirtschaftsorientierten Relationsstruktur verlassen, um sich in der Ankunftsrelationsstruktur mit Instanzen der Wirtschaft einzuschreiben und ihre Zirkulation dort weiterzuentwickeln.

Dies führt zum zweiten Zirkulationsmerkmal der befragten Künstlerinnen und Künstler, die eine wichtige Aussage der Theorie der Relation hervorhebt, wie wir sie eingangs unterstrichen haben. Am Beispiel der befragten Kunstschaffenden kann festgestellt werden, dass ein Wechsel der Tätigkeit und der Relationsstruktur eine bestimmte Ausgangsposition in einer Relationsstruktur voraussetzt, damit überhaupt eine Zirkulation in der Ankunftsrelationsstruktur vonseiten der Akteure entwickelt werden kann und die Akteure tatsächlich zirkulieren bzw. damit eine (doppelte) Einschreibung in dieser Ankunftsrelationsstruktur erfolgen kann. Die Akteure, die einen solchen Sprung schaffen, müssen Bedingungen auf der Ebene der Umstellung ihrer Position erfüllen, die sie dann erfüllen, wenn sie entweder in die erste Akteurkategorie in der (Ankunfts)Relationsstruktur oder in die vierte Akteurkategorie in ihrer Relationsstruktur zirkulieren. In unserem Fall betrifft eine solche Situation eine kleine Minderheit von Kunstschaffenden, die die Kunst verlassen und in die Wirtschaft gehen. Für die anderen bedeutet und entspricht der Wechsel ihrer Tätigkeit vor allem dem Versuch, sich in der Kunst zu halten und ggf. weiter durchzusetzen bzw. weiter in der Kunst zu zirkulieren.

Diese Ergebnisse zeigen einerseits eine Distanz zum Ansatz von Bourdieu, nach dem die Künstler im Feld der Kunst für eine bestimmte Definition der Kunst und um die legitimen Regeln der Kunst gegeneinander kämpfen, was ein Kampf für die künstlerische Autorität ist, die das Feld der Kunst nach Fraktionen von Künstlern stratifiziert -- die Avant-Garde, die sich ausschließlich der Kunst widmet, die Künstler, die für den Kunstmarkt arbeiten, und die Neuankömmlinge im Feld der Kunst, die das Métier lernen [@Bourdieu2008]. Dieser Ansatz betrifft in unserem Fall insbesondere die befragten Künstler, die das Topic 3 unterstützen. Selbst wenn diese Künstler einer Tätigkeit auf dem Wirtschaftsmarkt nachgehen müssen, damit sie in der Kunst weiterhin tätig sein können, zählt für sie nicht die Definition der Regeln der Kunst, sondern vor allem ihre künstlerische Praxis selbst bzw. ihr Kunstprojekt. Was für sie an Unbequemlichkeit kaum zu übertreffen ist, ist der Wechsel ihrer Tätigkeit, weshalb sie versuchen, diesen Wechsel so kurzlebig wie möglich zu gestalten, damit sie so viel Zeit wie möglich in ihre künstlerische Tätigkeit investieren können. Der erhoffte Wechsel der Position in der Kunst ist die Motivation, diese künstlerische Tätigkeit weiterhin durchzuführen, koste es, was es wolle. Dieser Anspruch, der im Allgemeinen mit dem Versuch verbunden ist, eine bestimmte Organisation der Verhältnisse der entsprechenden Akteure zum sie umgebenden Umfeld zu bewahren, spiegelt auf der Ebene der Erwartungen (und der Erwartungen auf Erwartungen) von diesen Künstlern die Richtung wider, die sie ihrer Zirkulation geben wollen: Sie wollen aufsteigen.

Aber im Unterschied zu Bourdieus Ansatz, der voraussetzt, dass alle Künstler den gemeinsamen Praxissinn -- die _illusio_ -- in ihrem Feld der Kunst teilen (vgl. etwa ebd., 278), weshalb sie alle die Macht in diesem Feld ergreifen und ausüben wollen, zeigen unsere Ergebnisse, dass die anderen Kunstschaffenden nicht unbedingt und keinesfalls um jeden Preis zu der zweiten oder zur ersten Akteurkategorie in der Kunst zirkulieren möchten. Oder anders gesagt: Sich "der Kunst "nur um ihrer selbst willen zu widmen" im Sinne eines sozialen Exzellenzmerkmals der eigenen künstlerischen Praxis bedeutet für sie nur eine ungeeignete und unnützliche Verkrampfung, die die Entfaltung der eigenen künstlerischen Praxis verhindert. Auch die Arbeit auf dem Wirtschaftsmarkt kann eine Quelle der künstlerischen Kreativität sein und/oder ein Umfeld darstellen, von dem die künstlerische Kreativität profitiert. Diese Haltung gegenüber dem eigenen Doppelleben erinnert an Reckwitz' Ansatz zu den Kulturen des Subjekts, wenn er sagt: "Die Moderne produziert keine eindeutige, homogene Subjektstruktur, sie liefert vielmehr ein Feld der Auseinandersetzung um kulturelle Differenzen bezüglich dessen, was das Subjekt ist und wie es sich formen kann" [@Reckwitz2006, 14]. Wie Reckwitz im Kontrast zu Bourdieu nahelegt, gibt es nicht nur eine einzige Art und Weise, das Künstlerleben zu leben und es als solches anerkannen zu lassen bzw. dafür Anerkennung zu erhalten. Neben der künstlerischen Tätigkeit gibt es auch andere Praktiken, die zu anderen Formen der Anerkennung führen als diejenigen, die ausschließlich in der Welt der Kunst entwickelt werden. Eine solche Haltung betrifft jedoch unter den befragten Kunstschaffenden unseres Samples insbesondere diejenige, die das Topic 2 am stärksten unterstützen. Für sie eröffnet die Welt der wirtschaftlichen Arbeit eine Möglichkeit, ihre Distinktionsmerkmale in der Kunst zu diversifizieren, selbst wenn derartige Distinktionsmerkmale, die aus der Tätigkeit dieser Kunstschaffenden auf dem Wirtschaftsmarkt entspringen und dort erworben werden, auch auf die Richtung ihrer Zirkulation einwirken, weshalb sich diese Künstler und Künstlerinnen schließlich immer wieder mit der Frage tragen, ob ihre Zirkulation weiterhin in der Kunst oder stattdessen eher zur Wirtschaft hin entwickelt werden sollte.

In einer ähnlichen Position befinden sich auch die befragten Künstlerinnen und Künstler, die das Topic 1 am stärksten unterstützen und sich von den anderen Kunstschaffenden durch ihren Pragmatismus und ihre Kontrolle der Umstellung ihrer Position bzw. ihrer Zirkulation in der Kunst und in der Wirtschaft unterscheiden. Hier greift Reckwitz' Ansatz nicht, sondern eher Chiapellos Beschreibung der Künstler-Manager, wenn sie von der Selbstkontrolle der Künstler spricht, die die Regeln und Normen von Instanzen des Kunstmanagements zum Vorteil ihres Kunstprojekts bzw. ihrer künstlerischen Praxis aufgreifen. Im Unterschied zum Kontext der Untersuchung Chiapellos, haben wir jedoch mit diesen Künstlern Akteuren vor uns, die die Regeln und Normen von Instanzen in der Wirtschaft -- also außerhalb der Kunst -- nur vorübergehend einbeziehen, ohne sich mit solchen Instanzen in der Wirtschaft tatsächlich einzuschreiben. Die Tätigkeit in der Wirtschaftswelt wird bewußt utilitaristisch genutzt, um die Möglichkeit der eigenen Zirkulation in der Kunst am Leben zu halten bzw. um die Position, die sie in der Kunst beziehen und als gefährdet sehen, nicht zu verlieren.

Nichtsdestotrotz, und wie Chiapello hervorhebt, zeigen die befragten Kunstschaffenden um die Topics 2 und 1, dass wir, sobald wir die Minderheitenwelt der Künstlereliten verlassen -- in der Theorie der Relation die Akteure, die der ersten Kategorie angehören --, für die sich die Exklusivität der künstlerischen Praxis wie selbstverständlich gegen jede andere soziale Praxis in der Kunst richtet und durchsetzt, auf eine differenzierte Mehrheitswelt der Künstler stoßen, von denen viele zwischen mehreren Tätigkeitsbereichen bzw. wie im Falle der Künstler unseres Samples zwischen Kunst und Wirtschaft zirkulieren. Für diese Künstler und Künstlerinnen stellt sich wie für die künstlerischen Eliten die Frage der doppelten Einschreibung, und sie stellt sich umso mehr, als ihre Zirkulation in der Kunst stottert und unvermeidlich Kompromisse hinsichtlich des Anspruchs auf Exklusivität ihrer künstlerischen Praxis hervorruft.

Schließlich liefern die Befragten, die das Topic 0 am stärksten unterstützen, exemplarische Fälle für Aussteiger aus der Kunst, die ihre Praxis fortan, wenn auch in unterschiedlicher Ausprägung, ausschließlich aus der Perspektive der Wirtschaftswelt entwickeln, in der sie als Arbeitnehmer tätig sind. Auch wenn diese Befragten also die Minderheit der befragten Kunstschaffenden bilden und eine Gruppe darstellen, die von der Kunstwelt endgültig enttäuscht wurden, so zirkulieren sie nichtsdestotrotz nicht etwa aus Überzeugung in der Wirtschaft, sondern vielmehr, weil sie keine Zirkulationsmöglichkeit mehr für sich selbst in der Kunst sehen. Als Aussteiger aus der Kunst sind diese Befragten diejenige, die den Diskurs über die Exklusivität der künstlerischen Praxis, wie er insbesondere von mächtigen Vermittlungsinstanzen in der Kunst propagiert wird, auf das schärfste kritisieren.

## Schlusswort

In unserem Kapitel haben wir die Aussagen von 23 Künstlern, die ein Doppelleben zwischen Kunst und Wirtschaft führen, mit der Methode des Topic-Modellings untersucht. Wir haben die vier wichtigsten Topics bzw. Leitthemen, die die Aussagen der Befragten strukturieren, herausgearbeitet. Auf dieser Grundlage ließen sich Gruppen von Befragten ausmachen, die je nachdem voneinander unterschieden werden konnten, wie sie diese Leitthemen in ihren Ausführungen priorisieren bzw. hierarchisieren. Diese Gruppen von befragten Künstlern und Künstlerinnen haben wir dann mit der Stratifikation von Relationsstrukturen nach Akteurkategorien in Verbindung gebracht und diesbezüglich die Konsequenzen thematisiert, die ihre Aussagen über ihr Doppelleben auf ihre Zirkulation ausüben. In der Diskussion der makrosoziologischen Ansätzen der zeitgenössischen Kunstsoziologie von Bourdieu, Chiapello und Reckwitz unter Bezugnahme auf unsere Ergebnisse konnte wir beobachten, dass diese drei Ansätze nur teilweise mit unseren Gruppen von befragten Kunstschaffenden korrespondieren.

Die Künstler um das Topic 3 werden am besten von Bourdieus Ansatz repräsentiert, wonach das Feld der Kunst von einem globalen Kampf um die Definition sowohl der Regeln der Kunst als auch der Kunst selbst zur Gewährleistung für die Künstler, die diesen Kampf gewinnen, eine Machtposition in der Kunst einzunehmen, organisiert werden würde. Jenseits dieses globalen Schauplatzes der Elite im Kunstfeld geht es den Künstlern jedoch nicht so sehr um einen Kampf zum Erreichen von Definitionsmacht über die Regeln der Kunst, sondern vielmehr um einen Widerstand _für_ ihre künstlerische Praxis in Unterstützung ihrer Zirkulation in der Kunst, die gleichzeitig einen Widerstand _gegen_ die Arbeit auf dem Wirtschaftsmarkt voraussetzt. Diese Künstler wollen ihre künstlerische Tätigkeit unbedingt bewahren, die durch ihre Beschäftigung auf dem Wirtschaftsmarkt so wenig wie möglich gestört werden soll.

Die Künstler um das Topic 2 und 1 zeigen dagegen das, was Reckwitz nicht nur für die Künstler und die Kunst, sondern im Allgemeinen in Bezug auf die Verbreitung der Kreativität in der (spät)modernen Gesellschaft hervorhebt. Die romantische Vorstellung des Künstlers, der sich nur seiner Kunst widmet, wird in der Praxis zum Druckmittel. Dies ist eine Folge der Verbreitung der Kreativität außerhalb der Kunst in der Moderne, die Künstler häufig dazu bewegt oder gar dazu zwingt, ihre angestammten Tätigkeiten und Tätigkeitsbereiche an den Schnittstellen zu anderen gesellschaftlichen Bereichen, zwischen denen sie dann oszillieren, zu entwickeln, wodurch sie auf kurz oder lang zur Verbreitung künstlerischer Tätigkeiten über alle sozialen Gefilde hinweg beitragen. Manche Künstler, wie die um das Topic 2, versuchen tatsächlich, wenn nicht beide Bereiche zumindest symbolisch unmittelbar miteinander zu verknüpfen, so doch zumindest ihre Erfahrungen in beiden Bereichen in Relation mit der Hoffnung zu bringen, dass sie zur Singularisierung ihrer Zirkulation in der Kunst beiträgt. Andere dagegen, wie Chiapello nahelegt, deren Argument insbesondere die befragten Künstlerinnen und Künstler um das Topic 1 betrifft, stellen sich selbst eher als eine Art selbstunternehmerischen Künstler vor, die ihre Zirkulation in der Kunst pragmatisch und insbesondere auf materiellem Weg über ihre Beschäftigung in der Wirtschaft unterstützen. Aber im Unterschied zu den Künstlern um das Topic 2 achten diese Künstler um das Topic 1 darauf, das beide Bereiche nicht in Berührung kommen.

Diese Ergebnisse unterstreichen einmal mehr die wichtige Bedeutung der (doppelten) Einschreibung für das Verständnis der Zirkulation in der Theorie der Relation und die damit verbundene Diskrepanz, die in der Praxis zwischen Einschreibung und Zirkulation stattfindet, wenn Akteure zwischen Relationsstrukturen -- wie hier die befragten Kunstschaffenden zwischen der soziokulturell-orientierten und der wirtschaftsorientierten Relationsstrukturen -- oder zwischen Sequenzen hin und her wechseln. Eine Beschäftigung auf dem Arbeitsmarkt bedeutet für die meisten befragten Kunstschaffenden nicht, dass sie zur wirtschaftsorientierten Relationsstruktur zirkulieren, geschweige darin weiter zirkulieren. Sie streben stets eine Einschreibung in der Kunst an, was sich auf der Ebene ihrer eigenen Vorstellung von der wirtschaftlichen Beschäftigung insofern widerspiegelt, als dass sie diese meistens utilitaristisch wahrnehmen und häufig nur als Nebenjob verstehen oder auch als vorübergehenden Projekteinsatz einstufen, was wiederum gleichsam bedeutet, dass sie ihre wirtschaftliche Tätigkeit keineswegs als nächste Herausforderung der eigenen Zirkulation einstufen.

Gleichzeitig lässt sich aber ebenso feststellen, dass die Überreste des romantischen Ideals, wonach sich ein Künstler zeitlebens und vollends "der Kunst um ihrer selbst willen" verschreibt, für unsere Befragten das Hindernis in ihrer Zirkulation in der Kunst dar, das dann konkret wird, wenn es sich darum handelt, diese Zirkulation in der Kunst durchzusetzen und sich entsprechend mit Kunstinstanzen in der soziokulturell-orientierten Relationsstruktur einzuschreiben. Ihre hybride Zirkulation, die ein hybrides Verhältnis zur künstlerischen Praxis widerspiegelt, trifft in der Kunst nur selten und nur teilweise auf entsprechende Kunstinstanzen, die sich der Förderung eines solch hybriden Verhältnisses zur künstlerischen Praxis annehmen würden und mit denen sich diese Künstler dann schließlich in der soziokulturell-orientierten Relationsstruktur einschreiben könnten [@PapilloudSchultze2022, 59-60]. Selbst wenn also unsere vier Gruppen von Kunstschaffenden auf Kunstinstanzen träfen, die sich entsprechend des von den Künstlern unterhaltenen Verhältnisses zur Kunst als zur doppelten Einschreibung geeignet erweisen [vgl. ebd.], so wären diese Kunstinstanzen zumeist solche, die in der Kunst weniger breit angelegt sind und deshalb in Teilsequenzen der Kunst arbeiten [vgl. ebd., 241-244]. Deshalb können sich diese Künstler auf kurz oder lang nicht dem subjektiven Eindruck erwehren, dass sie der Kunst entweder nicht vollkommen oder schlimmstenfalls gar nicht mehr angehören, was zur objektiven Schrumpfung ihrer Erwartungen -- und ihrer Erwartungen auf Erwartungen -- auf eine Karriere in der Kunst führt, sie zu schwebenden statt zirkulierenden Akteuren in der Kunst macht und ihr objektives Oszillieren zwischen Kunst und Wirtschaft stärkt. Entsprechend ist es für die befragten Künstlerinnen und Künstler im Laufe der Zeit immer schwieriger, Einschreibungsmöglichkeiten und daher Zirkulationsmöglichkeiten in der Kunst ausfindig zu machen, was die Austritte von Akteuren aus der Kunst im Allgemeinen und den Wechsel der Relationsstruktur von der Kunst in die Wirtschaft der befragten Kunstschaffenden um das Topic 0 im Speziellen erklärt.

Die (doppelte) Einschreibung als Grundlage der Entwicklung von einer Zirkulation innerhalb oder zwischen Relationsstrukturen ergibt sich nicht von selbst. Neben der Investition in die eigene Zirkulation erfordert sie Vermittlungsinstanzen, die eine solche Investition fördern und (positiv sowie negativ) sanktionieren, damit eine solche Einschreibung und die daraus folgende Zirkulation legitimiert werden und zur Entstehung einer Reziprozität als dreigliedrige Operation der Anerkennung, Verteilung und Schließung von Zirkulationen zwischen Akteuren und Vermittlungsinstanzen führt. Dies spiegelt die Festigkeit von Relationsstrukturen wider, was wir am Beispiel der befragten Künstler und Künstlerinnen in unserer Untersuchung gut beobachten können. Zwischen der künstlerischen Praxis und der Beschäftigung in der Wirtschaft gibt es nicht nur eine Unterscheidung von Tätigkeiten, Tätigkeitsbereichen, von Beschäftigungen, von Praktiken. Es gibt auch und vor allem eine Unterscheidung von Relationsstrukturen, von Organisationsprinzipien der Arbeit an sozialen Ereignissen, von Verhältnissen zur Umgebung, in denen diese Tätigkeiten und Tätigkeitsbereiche, Beschäftigungen und Praktiken entwickelt werden. Dieser Unterscheidung entsprechen Zirkulationswege und Zirkulationsmöglichkeiten, die auf der Grundlage von Einschreibungsakten mit Vermittlungsinstanzen entwickelt werden. Oder anders gesagt: Diese Unterscheidung ist eine Unterscheidung der Dynamik von Relationsstrukturen als Abweichung von einer _idealen_ Relation, deren Preis für die Akteure, die von einer Relationsstruktur zu einer anderen Relationsstruktur zirkulieren, in der Veränderung dieser Einschreibung ist, die ein anderes bzw. relationsstrukturspezifisches Odnungsprinzip von Verhältnissen zu sich selbst, zu anderen und im Allgemeinen zur sozialen Welt erfordert. Das eine solche Entwicklung nicht von selbst vonstatten geht, sondern Bedingungen voraussetzt, die die Akteure in Bezug auf ihre Position, ihre Zirkulation und in Bezug auf die Vermittlungsinstanzen in ihrer Ausgangsrelationsstruktur erfüllen müssen, zeigt unsere Untersuchung als die Quelle von einer sozialen Ungleichheit, die strukturell umso fester erscheint, als sie von ihrer Entstehung bis in ihren Folgen vom Primat der Zirkulation abhängt.

## Literatur
