---
title: "Transformer. Medien als Akkumulatoren von Verhältnissen"
indent: true
output:
    html_document: default
csl: chicago-author-date.csl
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Früher in der Öffentlichkeit wenig thematisiert, ist es jetzt beinah unmöglich, dem Ausdruck _KI_ für künstliche Intelligenz auszuweichen. Spätestens seitdem diese Technologie unter dem Namen _ChatGPT_ -- GPT für _Generative Pretrained Transformers_ -- publik und im Internet für jedermann zur Verfügung gestellt wurde, liegt KI als digitale Mediation in Form von ChatGPT nicht nur im Trend, sondern hat auch eine Reihe gesellschaftlicher Debatten und Kontroversen ausgelöst. Wer sich ein Stück weit mit _ChatGPT_ beschäftigt hat, dürfte ein Gefühl dafür gewonnen haben, in welche Richtung die nächsten Entwicklungen im Internet und in den sozialen Medien einschlagen und welche möglicherweise weitreichenden Veränderungen für unsere Gesellschaften damit einhergehen werden, die dann kaum mehr in den zunehmend durch digitale Relationen in Form von zahlreichen Algorithmen vernetzten Gesellschaften weg zu denken sind [@Seyfert2019; @Seyfert2021]. _ChatGPT_ zeigt allen Akteuren und Instanzen unserer Gesellschaften und zwar womöglich deutlicher als alle anderen (digitalen) Mediationen zuvor, dass die Macht von Medien und im Allgemeinen von Mediationen deshalb so überwältigend ist, weil sie unsere Verhältnisse zu anderen und zur Welt abfangen, bewerten und weiterentwickeln. Sie sind imstande, jede Stufe der Arbeit an relationalen Ereignissen formal zu generieren, ohne dass dabei Akteure und gesellschaftliche Instanzen notwendig wären. Die Welt der Mediationen ist eine Welt, in der idealerweise nicht mehr die Akteure und die Kollektive anhand von Verhältnissen die Mediationen dieser Verhältnisse kontrollieren, sondern die Mediationen selbst derartige Verhältnisse anhand von Akteuren und Kollektiven kontrollieren. Oder vom Standpunkt des Primats der Zirkulation ausgedrückt: In dieser Welt der Mediationen geht es vor allem darum, dass nicht nur auf Basis von Akteuren und Kollektiven, sondern auch jenseits von ihnen zirkuliert wird.

Aus dieser Verselbstständigung von Mediationen ergibt sich die Grundlage einer eigenen Ordnung von Verhältnissen mit eigener Idealisierung der perfekten Relation als _creatio continua_ auf Basis einer ununterbrochenen Zirkulation. Diese Ordnung von Verhältnissen fungiert als Selbstverständnis der medienorientierten Relationsstruktur, als Fokus ihrer Zirkulationsordnung. In dieser Relationsstruktur gewährleisten die Mediationen die doppelte Einschreibung von Akteuren und Instanzen, d. h. sie eröffnen Zirkulationspotentiale, sie bringen Akteure auf entsprechende Zirkulationswege und sie stärken die Position von gesellschaftlichen Vermittlungsinstanzen [@PapilloudSchultze2022, 111-119]. Entsprechend arbeiten die Akteure und die Instanzen in dieser Relationsstruktur stetig an der Verselbständigung von Mediationen in Ausführung ihrer eigenen Operationen im Dienst der Gewährleistung der doppelten Einschreibung von Akteuren und Instanzen und ferner im Dienst der Unterstützung von Zirkulationen in dieser Relationsstruktur (ebd., 116-117). Die Ausführung dieser Operationen verlangt dabei gleichsam eine mediale Kontrolle, bei der die Verhältnisse vom Standpunkt ihrer Einbettung in formale Verfahren von gesellschaftlichen Instanzen und nach ihren Verbindungen miteinander evaluiert werden. Eine so gelagerte mediale Kontrolle fungiert nachgerade als Grundbedingung der doppelten Einschreibung, die weitere Einschreibungen generiert und weitere Wertungen produziert, woraus die entsprechende Zirkulation wiederum ihre Bedeutung und ihre Wichtigkeit für die Relationsstruktur zieht. Oder anders gesagt: Die mediale Kontrolle ist eine unmittelbare Kontrolle der Effizienz von Zirkulationen auf der Grundlage der Bewertung von Einschreibungen für eine Relationsstruktur, die sich mittelbar als Bewertung sowohl der Akteure als auch der gesellschaftlichen Instanzen ergibt, die in diese Einschreibungen jeweils einbezogen werden. Weil diese Kontrolle mittelbar sowohl Akteure als auch Instanzen in Relationsstrukturen betrifft, ist es eben auch jene mediale Kontrolle, die insbesondere in der medienorientierten Relationsstruktur die Kernbedeutung der Reziprozität bildet. Hieraus folgt gleichsam, dass die Legitimität von Akteuren, die in dieser Relationsstruktur zirkulieren bzw. aufgebaut werden, und die Legitimität von Instanzen -- entsprechend dieser Kernbedeutung der Reziprozität -- maßgeblich davon abhängt, ob sich sowohl die Akteure als auch die Instanzen bei den Akten der doppelten Einschreibung dieser Kontrolle unterwerfen.

Aus der Arbeit von Akteuren und Instanzen der medienorientierten Relationsstruktur an Mediationen ergeben sich jedoch zahlreiche Abweichungen vom Ideal der perfekten Relation bzw. der perfekten Zirkulation aufgrund einer perfekt kontrollierten Einschreibung in Relationsstrukturen, wie sie von dieser Relationsstruktur angestrebt wird. Wie in den anderen Relationsstrukturen strukturieren diese Abweichungen die medienorientierte Relationsstruktur. Sie verleihen ihr ihre spezielle Identität als Ordnung von Verhältnissen, die zur Materialisierung der Investition in die Repräsentation der Attraktivität von Mediationen beitragen (vgl. den Schmetterlingspfad der Sequenz Attraktivität in ebd., 115, Abb. 3.13). Diese Attraktivität in Verbindung zu ihrem akteurzentrierten Hauptmerkmal bildet die Kernsequenz dieser Relationsstruktur, ab der sich die medienorientierte Relationsstruktur gleichsam als selbstständige Relationsstruktur mit eigener Zirkulation konstituierte. Die Verselbständigung einer solchen medienorientierten Relationsstruktur symbolisiert die wachsende Bedeutung der Zirkulation in allen Gesellschaften, die bis heute anhält. In allen Gesellschaften, die in Zeit und Raum nicht nur demographisch wachsen, sondern auch strukturell zusehends komplexer werden, wird die Zirkulation von einer Möglichkeit zu einer Notwendigkeit, die deshalb nicht den Akteuren und gesellschaftlichen Instanzen allein überlassen werden kann. Deshalb braucht es entsprechende Mediationen, damit gewährleistet wird, dass Akteure und gesellschaftliche Instanzen ihre doppelten Einschreibungsprozesse nicht verfehlen und die resultierenden Zirkulationen nicht eskamotieren.

Zeitgenössische Transformer wie ChatGPT symbolisieren ferner einen ebenso aktuellen wie weiteren Entwicklungsschritt der medienorientierten Relationsstruktur, der vor allem unterstreicht, dass Mediationen in ihren Eigenschaften als Transformer zahlreichen Veränderungen im technischen Umgang mit Informationen und Wissen etablieren. Um diese zentrale Aussage der Theorie der Relation unter Rekurs auf die medienorientierte Relationsstruktur zu plausibilisieren, führen wir in diesem Kapitel zuerst in die Operationen ein, die solche Transformer formalisieren und in Form von Algorithmen durchführen. Aus dieser Darstellung wird sich ergeben, dass diese Operationen letztlich auf alten Praktiken der Aufnahme und Verarbeitung von Informationen und Wissen ab dem Lesen und Schreiben von Texten basieren, die sich lediglich im Laufe der Zeit in ihren Verbindungen zueinander verändert haben. Diese Veränderungen entsprechen, wie zu zeigen sein wird, einerseits einer Desakralisierung der Beziehung zwischen dem Autor und seinem Text und andererseits einer Umstellung des Verhältnisses zwischen dem Autor und seinem Text. Das heißt, dass der Text nicht mehr die symbolische Leitmediation, die einzig und allein zur richtigen Interpretation der Intentionen des Autors führe und der sich der Text zu unterwerfen habe, darstellen muss. Der Text selbst muss zur Leitmediation werden, die lediglich die Fähigkeit des Autors unter Beweis zu stellen hat, nicht nur weitere Texte verfassen zu können, sondern dabei auch weitere Autoren mehr oder weniger explizit einzubeziehen und sie miteinander zu verbinden. Damit firmiert der Text gleichsam zu einer Stütze von zahlreicher Verhältnissen zur Information und zum Wissen, die wiederum einen Text für weitere Akteure und für die Produktion und Rezeption von weiteren Texten attraktivieren.

Diese Verselbständigung des Textes von der symbolischen Autorität seines Autors und dessen Intention bahnt nicht nur den Weg für die Entwicklung von Tätigkeitsbereichen, in denen es um Texte geht, sondern führt mindestens ebenso sehr zum Aufbau von gesellschaftlichen Instanzen und zur Zirkulation der entsprechenden Akteure, die solche Texte produzieren und rezipieren. Jene Entwicklungshistorie des Textes gilt es in diesem Kapitel am Beispiel der Literatur in Frankreich im 19. Jahrhundert in ihrer Verbindung mit literarischen Zeitschriften, Verlagen und der Presse nachzuzeichnen, um zu veranschaulichen, wie die Verselbständigung einer einzigen Mediation wie der des Textes zur Verselbständigung der medienorientierten Relationsstruktur mit entsprechenden Instanzen beiträgt. Mit Blick auf die Neubildung von mannigfaltigen Instanzen soll ferner demonstriert werden, dass die Instanzen der medienorientierten Relationsstruktur stets die Verbreitung der Verselbstständigung von Mediationen entlang der Zielstellung fokussieren, um zum einen Zirkulationsmöglichkeiten für Akteure auf der Grundlage ihrer Fähigkeit zu schaffen. Zum anderen fokussieren sie aber auch die Herstellung von weiteren Verbindungen von Mediationen zu Mediationen. Solche Verbindungen sollen nicht nur die Arbeit der Akteure an relationalen Ereignissen erleichtern, sondern diese Arbeit auch teilweise übernehmen und entsprechende Zirkulationsmöglichkeiten und Zirkulationswege generieren. Während die ersten Schritte in Richtung der Verselbstständigung der medienorientierten Relationsstruktur von der Presse ab dem 19. Jahrhundert geleistet werden, bringt die Entwicklung von digitalen Technologien im 20. Jahrhundert den notwendigen Impuls zur endgültigen Etablierung der medienorientierten Relationsstruktur.

## Transformers als relationale Dispositive

Die Theorie der Relation schlägt ein grundsätzliches Verständnis von Mediationen als Träger und Erzeuger von Verhältnissen vor, wobei die jeweiligen Mediationen ein Prinzip des Arrangements dieser Verhältnisse darstellen [vgl. @PapilloudSchultze2022, 319-330; speziell zur Rolle der Medien in der medienorientierten Relationsstruktur vgl. ebd., 333-335]. Deshalb versteht die Theorie der Relation Mediationen nicht nur im Sinne von Trägern von Funktionen oder von Formen bzw. von anderen ehemaligen Mediationen [@Mcluhan2001], sondern auch als relationale Dispositive [@PapilloudSchultze2022, 361-366]. Damit solche relationalen Dispositiven erfolgreich entwickelt werden, ist es erforderlich, dass Mediationen zu abstrakteren Mediationen weiterentwickelt werden. Nur so können unterschiedliche Verhältnisse bzw. Verhältnisse, die auf unterschiedliche Kontexte verweisen, auf solche Mediationen übertragen und miteinander verbunden werden, ohne dass die jeweiligen Kontexte, die als Organisationsrahmen und Sinnzusammenhang der entsprechenden Verhältnisse gelten, diese Umstellungen und Verbindungen schwächen oder stören. Diese Abflachung von Kontexteffekten durch die Extrapolation von Verhältnissen macht aus abstrakte Mediationen mächtige Akkumulatoren und Generatoren von formalen Verhältnissen, die überall in Relationsstrukturen und Sequenzen von Relationsstrukturen verbreiten werden können. Dies entspricht der Art und Weise, wie die medienorienterte Relationsstruktur die anderen Relationsstrukturen zum Vorteil der eigenen Verbreitung und der Verbreitung der eigenen Auffassung von Reziprozität als medialer Kontrolle satellisiert. Sie verbreitet formal äquivalente Verhältnisse in Form von relationalen Dispositiven auf die anderen Relationsstrukturen (vgl. ebd., 401-414; Abb. 9.4, ebd., 407), die entsprechend als Kontrollinstanzen von Verhältnissen im Dienst von Einschreibungsprozessen in diesen Relationsstrukturen eingesetzt werden können. Ein solches Verfahren ist dasjenige, dass in der Forschung zu Sprachen und zur Modellierung von Sprachen seit den 1950er Jahren entwickelt wurde, dessen zeitgenössisches Ergebnis Transformers wie _Generative Pretrained Transformers_ sind [@Hutchins1995].

Sprachmodelle wurden entwickelt, um das spezifische Problem der Übersetzung von einer Sprache in eine andere Sprache mit Hilfe eines Rechners zu lösen (ebd.). Bis in die 1980er Jahre erweisen sich jedoch die meist mit Unterstützung der Firma _IBM_ durchgeführten Übersetzungsexperimente als wenig brauchbar. So war es zwar mit einem Rechner durchaus möglich, Begriffe in einer begrenzten Zahl von Texten anhand eines statistischen Verfahrens aus vollständigen Sätzen herauszugreifen und zu übersetzen. Ein solches Verfahren konnte allerdings keine langen Wortfolgen wie etwa ganze Sätze verarbeiten. Es kam immer wieder zu Übersetzungsfehlern, sodass letztlich ein menschliches Eingreifen zur Überprüfung und Korrektur der Übersetzung erforderlich blieb [@Pierce1966; @Zong2022]. In der Folge sorgte der technische Fortschritt, insbesondere die Steigerung der Rechenleistung (bessere _Central Processing Units_ und _Graphics Processing Units_) und des Arbeitsspeichers, dafür, dass einerseits größere Datenmengen gespeichert und andererseits der Umfang von statistischen Operationen über diese Daten erweitert werden konnten. Aus dieser Entwicklung ergibt sich Mitte der 1980er Jahre die Methode des _Recurrent Neural Network_ (RNN). Dabei geht es darum, die Verhältnisse zwischen Begriffen in Sprachen auf der Grundlage der Modellierung von Verhältnissen zwischen Neuronen im menschlichen Gehirn zu überdenken. Mit der RNN-Methode können so nicht nur mehr Korrespondenzen zwischen Begriffen hergestellt werden -- der sog. _deep learning_ Ansatz  --, sondern es kann gleichzeitig mit größeren Wortzusammenstellungen gearbeitet werden. Auf dieser Grundlage wurden ausgefeiltere Sprachmodelle konstruiert, wie etwa das Modell der bidirektionalen rekurrenten neuronalen Netzwerke (BRNN), das Langzeitgedächtnismodell (LSTM) oder das _gated recurrent units_-Modell (GRUs) [siehe @Hochreiter1997]. Solche Modelle sind Matrizen von Verbindungen zwischen Begriffen, die nach einem Ähnlichkeitsansatz quantitativ gewertet werden. Begriffe, die stark verbunden sind, gelten als Begriffe, die häufig zusammen in Sätzen und Absätzen auftauchen und deshalb auf ähnliche Sinnzusammenhänge bzw. auf ähnliche Inhalte verweisen. Begriffe, die dagegen schwach miteinander verbunden sind, gelten als Begriffe, die weniger häufig zusammen in Sätzen und Absätzen auftauchen und deshalb als Begriffe gelten, die auf unterschiedliche Inhalte verweisen. Diese Sprachmodelle können entsprechend als eine Referenzmatrix verwendet werden, um weitere Sammlungen von Daten zu untersuchen und deren Inhalt zu werten.

Trotz der Fortschritte in der Entwicklung von Rechnerkomponenten, die Rechner letztendlich immer leistungsfähiger gemacht haben, reichten die technischen Entwicklungen aber immer noch nicht aus, um große Datensammlungen anhand solcher Sprachmodelle auszuwerten. Anfang des Jahres 2017 wurden deshalb GPT-Modelle entwickelt, die dieses Problem lösen sollten. Das innovative Merkmal von GPT-Modellen besteht darin, Matrizen von Begriffen nicht mit Sequenzen von Begriffen -- etwa mit Sätzen -- zu verbinden, sondern mit Einzelbegriffen. Dies beschreibt den Kern eines Transformers: Er verbindet einen Begriff mit den Begriffen, die am wahrscheinlichsten mit diesem Begriff in einer bestimmten Sprache auf der Grundlage von einer bestimmten Datensammlung verbunden sind. GPT-Modelle sind deshalb einerseits eine Erweiterung der Sprachmodelle, die nach einem _deep learning_ Ansatz konstruiert wurden. Andererseits besteht ihre Besonderheit darin, dass sie aufgrund von solche Matrizen schneller und mit wenigen rechnerischen Kosten bestimmen können, mit welcher Wahrscheinlichkeit ein Begriff _B_ nach einem Begriff _A_ auf der Grundlage eines Kontextes von Begriffen, der am wahrscheinlichsten mit dem Begriff _A_ in einer gegebenen Sprache verbunden ist, folgt [siehe auch @Devlin2019]. In künftigen Versionen von solchen Transformern geht es darum, das Ergebnis dieser Wahrscheinlichkeitsrechnung zu verwenden, um die Effizienz des Sprachmodells selbst bzw. um die Genauigkeit der Matrizen zu verbessern. Damit können solche Wahrscheinlichkeitsrechnungen noch schneller und immer präziser erfolgen, ohne dass der Rechner überfordert wird oder das Sprachmodell zu schnell obsolet wird. Durch solche Verbesserungen ist es zudem durchaus vorstellbar, dass Sprachmodelle immer schneller berechnet werden, was sie gegenüber der kontinuierlichen Produktion von Inhalten in den digitalen Welten des Internets und in den sozialen Medien widerstandsfähiger und weniger fehleranfällig werden ließe.

Bei Transformern wie ChatGPT geht es also um die Akkumulation von Dateien und von Verbindungen zwischen diesen Dateien, die es erlauben, weitere Verbindungen zwischen diesen Dateien und entsprechend weitere Dateien aus diesen Verbindungen zu generieren. Eine solche Akkumulation anhand und in Form von Mediationen zu entwickeln, ist nicht erst mit der wissenschaftlichen Arbeit an der _KI_ entstanden. Sie stellt eine Grundtendenz beim Einbezug von und der Arbeit an Mediationen durch Akteure und gesellschaftliche Instanzen dar, deren Bedeutung wir besser verstehen können, wenn wir die Grundoperationen von Tansformern dekonstruieren und sie vor dem Hintergrund der Praktiken perspektivieren, die diese Transformer in abstrakter Form reproduzieren, und zwar: Dateien aufnehmen bzw. lesen und sie zerlegen bzw. exzerpieren, um weitere Zusammenstellungen von Dateien auf der Grundlage der aufgenommenen und zerlegten Dateien zu produzieren. Wie aus Mediationen Akkumulatoren von Verhältnissen generiert werden, werden wir zuerst im Rahmen der ersten Operation vertiefen, die wir erwähnt haben: dem Lesen.

## Lesen

Transformer lesen Dateien, und wenn wir dieses Lesen von Außen betrachten, so müssten wir zunächst einmal sagen, dass es nichts mit dem Lesen von Texten durch übliche menschliche Akteure gemein hat. Transformer nehmen Texte auf, die insofern "gelesen" werden, als sie in Sätze und Begriffe zerlegt, von unerwünschten Zeichen und Begriffen gereinigt und in Form von Listen und ferner von Vektoren bzw. eindimensionalen Matrizen dargestellt werden. Damit stellen Transformer einerseits die Ausgangslage für die Berechnung von Verbindungen zwischen Begriffen und andererseits die notwendige Stufe zum Arrangement solcher Verbindungen in Form von anderen Texten auf der Grundlage vorhandener Textdateien bereit. Deshalb haben Transformer Debatten über den Wert dieser Art des "Lesens" von Dateien in dessen Verbindung mit Wissen als Produktion von Erkenntnis aus der Interaktion zwischen Menschen und digitalen Technologien wieder animiert, die teilweise schon in Bezug auf die Auffassung von verteilter Kognition in den Neuro- und Kognitionswissenschaften [@Magnus2007; @Michaelian2013; @Anderson2018; @Risku2020] und in Bezug auf die Rolle von Algorithmen bei der Unterstützung menschlicher Entscheidungen eingeführt wurden [@Pariser2012; @Anderson2012; @Braverman2014; @Bucher2018; @LeeLarsen2019]. Die Fragen, die sich in diesem Zusammenhang stellen, betreffen den Sinn der Wissensproduktion und den Wert des entsprechenden Wissensinhaltes, und zwar unter der Bedingung, dass dieses Wissen nicht primär von menschlichen Akteuren, sondern maßgeblich von digitalen Mediationen hergestellt wird. Eingedenk dieser Tatsache zeigt der Rekurs auf die Auseinandersetzung über das Lesen und über die Lesestechniken in der Geschichte nicht nur, dass solche Fragen keineswegs neu sind. Historische Auseinandersetzungen über das Lesen und die Lesetechniken zeigen auch und vor allem eine besondere Aufmerksamkeit auf die Verselbständigung von Mediationen und auf die Verhältnisse, die solche Mediationen zum Lesen, zu den Texten, die gelesen werden, und zum Wissen, das aus diesen Texten entnommen und gewonnen wird, in die Gesellschaften einführen. Einerseits wird hervorgehoben, dass eine auf Basis von Transformern eingeführte bzw. beschleunigte Verselbständigung von Mediationen die soziokulturelle Kontrolle über solche Mediationen schwächen kann. Andererseits wird jedoch ebenso unterstrichen, dass diese Verselbständigung von Mediationen mehr Verhältnisse auf Verhältnisse generiert, die die Möglichkeiten derartiger Mediationen vermehren, erstens in immer mehr Verhältnisse und Praktiken einbezogen zu werden und zweitens solche Verhältnisse und Praktiken entsprechend zu stärken. Dies trägt wiederum insgesamt zur Verbesserung der Einschreibung von Akteuren in unterschiedlichen Tätigkeitsbereichen bei. Eben dieses Dilemma zwischen Kontrollverlust vs. Vermehrung und Stärkung von Einschreibungsmöglichkeiten, die Mediationen wie Transformer anbieten, stellt sich in ganz ähnlicher Weise beim Lesen bereits ab der Auseinandersetzung mit der Frage, ob laut oder lautlos gelesen werden soll, was zu weiteren Fragen bezogen auf das schnelle oder langsame, einmalige oder mehrmalige, vollständige oder nur teilweise Lesen führt.

Die Debatten zur Entwicklung von unterschiedlichen Lesenspraktiken beziehen sich generisch auf das rekurrierende Problem der Hierarchisierung von Mediationen, die mit Satellisierungsstrategien innerhalb von Relationsstrukturen und zwischen Relationsstrukturen einhergehen und je nach Erfolg oder Scheitern von Satellisierungsstrategien umgestellt werden. Im paradigmatischen Fall des lauten und lautlosen Lesens, den wir hier beispielhaft fokussieren, wird zuerst ersichtlich, dass die Verbreitung des lautlosen Lesens in der Zeit andere Verhältnisse zum Lesen und zum gelesenen Text mit sich bringt, selbst wenn das laute Lesen deswegen nicht marginalisiert oder gänzlich verabschiedet wird: "Das lautlose Lesen verdrängte nicht das laute Lesen, das weiterhin nicht nur beim Vorlesen, sondern auch beim 'Für-sich'-Lesen praktiziert wurde" [@Zedelmaier2001, 14; vgl. auch @Bickenbach2017]. Mit der Verbreitung des lautlosen Lesens entwickeln sich vielmehr neue Verbindungen zwischen beiden Techniken des Lesens, die zu weiteren Verbindungen mit anderen Lesetechniken -- wie etwa das oben hervorgehobene langsame und schnelle Lesen -- führen. Nichtsdestotrotz bewahrt das laute Lesen die Oberhand über das lautlose Lesen, weil es häufig mit dem menschenzentrierten Lesen assoziiert wird. Mit dem lauten Lesen wird nicht nur abstrakt und allgemein der Mensch ins Zentrum des Lesens gerückt, sondern der Phonozentrismus, wie Jacques Derrida sagt [@Derrida1967], soll gleichzeitig als Leitmediation des Aufbaus und der Steigerung der Wissensmacht jedes Lesers beitragen. Das Aussprechen des Geschriebenen ist die Bedingung für die aufmerksame Berücksichtigung des Textinhalts, der, weil er durch das Aussprechen des Textes einverleibt wird, als besser verstanden gilt. Die Herrschaft des Wortes durch die Macht von dessen Klang segnet also die Herrschaft des Sprechers oder des Rezitators über den lautlosen Leser ab, der die Worte zudem deshalb nicht erleben kann, weil er sie nur "sieht", deren Inhalt nur oberflächlich versteht und folglich das gesehene Wort nicht wirklich zu einem Erkenntnisgewinn führen oder gebraucht werden kann.

Sei es in der griechischen Antike oder im 19. Jahrhundert und auch eingedenk der Revolution in der Produktion von schriftlichen Mediationen, die der Buchdruck im 15. Jahrhundert hervorbringt und das lautlose Lesen zuerst zu begünstigen scheint, setzt sich diese Hierarchie zwischen dem lauten und dem lautlosen Lesen eine gute Zeitlang weiter durch [@Gavrilov1997]. Um es mit den Worten der Theorie der Relation auszudrücken: Beim lauten und lautlosen, langsamen und schnellen Lesen sowie bei den Verhältnissen, die zwischen diesen unterschiedlichen Lesetechniken entwickelt werden, geht es primär um die Durchsetzung von unterschiedlichen Hierarchieprinzipien zwischen textuellen Mediationen, den Akteuren, die sie beanspruchen, den Insititutionen, mit denen sich diese Akteure in Sequenzen von Relationsstrukturen einschreiben, und diesen Sequenzen selbst. Diese Hierarchie zwischen dem lauten und dem lautlosen Lesen von der griechischen Antike bis zum Mittelalter generiert aus dem lauten Lesen die gewöhnliche Praxis des Lesens, während das lautlose Lesen ein Sonderfall des lauten Lesens darstellt [@Busch2002; vgl. auch @Bickenbach2017, 40ff.]. Entsprechend werden die Texte und die Leser hierarchisiert. Laut werden insbesondere literarische Werke von hoher Bedeutung gelesen, wohingegen das leise Lesen alltäglichen Schriften oder Texten von weniger Bedeutung vorbehalten ist. Laut lesen meistens Gelehrte und im Allgemeinen Akteure, die sich tagtäglich bzw. beruflich mit Texten beschäftigen. Bei diesen Personen kommt sogar eine Kombinatorik zwischen dem lauten und lautlosen Lesen häufig vor. In diesem Fall wird das lautlose Lesen meistens als eine Art von Hilfsmittel gebraucht, um sich den Inhalt von Werken, die schon gelesen wurden oder gar auswendig gelernt wurden, wieder in Erinnerung zu bringen. Demgegenüber wird mit dem lauten Lesen das langsame Lesen in Verbindung gebracht, wobei hervorzuheben ist, dass das laute Lesen nicht nur als Rhetorikkunst praktisiert wird. Es ist auch ein Kontrollmittel im Dienst des richtigen Verständnisses von Texten zur Bildung von entsprechend adäquatem Wissen. Wer laut liest, stellt sich also nicht nur in ein adäquates Verhältnis zu einem Text, sondern auch zu der Intention des Autors und Urhebers eines Textes sowie mittelbar zu den Instanzen des Wissens, zu denen ein solcher Autor zirkuliert ist.

Wie Bickenbach am Beispiel von Christoph Martin Wieland hervorhebt, ist diese Asymmetrie zwischen lautem und lautlosem Lesen eng mit dem Thema der Kontrolle bzw. des Kontrollverlustes des Autors über seinen eigenen Text verbunden. Dieses Thema wird im Laufe des 17. und 18. Jahrhunderts von Autoren immer mehr aufgegriffen, die wahrnehmen, dass die Leser zahlreicher werden und im Grunde so lesen, wie sie möchten [ebd., 31; vgl. auch @Schenda1970, der im Jahr 1760 eine Verdoppelung der Ausleihen in Bibliotheken mehrheitlich von Menschen feststellt, die weder Adelige noch Aristokraten oder Großbürger sind]. Für Autoren wie Wieland oder später auch Arthur Schopenhauer und Friedrich Nietzsche birgt eine solche Gleichgültigkeit des Lesens die Gefahr, den Text mit eigenem Wissen zu Interpretationen zu zwingen, die mit den Intentionen des Autors nicht übereinstimmen. Dies würde dazu führen, den Text falsch zu verstehen. Hier kann nur ein aufmerksames und langsames lautes Lesen helfen, oder wie Bickenbach am Beispiel von Nietzsche sagt: "Lesen wäre im Idealfall das Ablesen der Tatsachen ohne Verfälschung der eigenen Interpretation" (ebd., 41). Im Fall von Nietzsche bereitet dieses ideale "Ablesen der Tatsachen" die Grundlage seiner Kulturkritik der Moderne vor, wo das laute Lesen als Erbe der Antike die einzige adäquate Technik zum richtigen Verständnis von Texten als physische Leistung des Lesers zur Gewährleistung des richtigen Verständnisses der Intentionen des Autors wahrgenommen wird. Nichtsdestotrotz trägt die Erweiterung des Kreises der Leserschaft -- von kleinen Kreisen ausgebildeter Akteure vor dem 18. Jahrhundert auf immer mehr Akteure nach dem 18. Jahrhundert und entsprechend auf ein wachsendes Publikum bzw. eine wachsende Leserschaft von Texten -- zur steigenden Attraktivität von Texten bei. Dieser Prozess fechtet die Asymmetrie zwischen lautem und lautlosem Lesen sukzessiv an, und generiert nach und nach eine andere Symbolik um das Lesen von Texten, die wiederum andere Verhältnisse zum lauten und lautlosen Lesen zum Vorteil der Texte als Mediation der Akkumulation von Texten und Autoren und ferner von Wissen und Kultur hervorbringt. Diese Symbolik stützen alte Praktiken der Verwendung von Texten durch das Zitieren und das Exzerpieren in Unterstützung der Verhältnisse zwischen der Aufbewahrung der Mündlichkeit der Sprache im geschriebenen Text und dem Anspruch vom geschriebenen sowie schreibenden Lesen bzw. zum Lesen mit Stift [@Kramer2005; @Kramer2012].

## Zitieren und Exzerpieren

Wie Alain de Libera mit Fokus auf das Mittelalter sagt: "Die mittelalterliche Textualität ist, wenn man so will, eine mündliche Textualität; der mittelalterliche Text ist eine Mischung aus mündlichen und schriftlichen Texten, wobei das Mischungsverhältnis selbst für den modernen Leser manchmal nicht greifbar und fast immer unklar ist" [@Libera1984, 18]. Oder anders gesagt: Die Vermischung zwischen dem lauten und lautlosen Lesen, die von der Antike bis in unsere Zeit festgestellt wird, entspricht einer Vermischung von Mündlichem und Schriftlichem in den Texten selbst, die im Mittelalter -- im Fall von de Libera vom 12. bis zum 15. Jahrhundert -- als Wissensstrategie entwickelt wird, um die Überzeugungskraft des Textes selbst zu stärken, wobei "einen Text zu 'lesen' ihn in Verbindungen zu bringen bedeutet" (ebd., 28). Dies zeigt die Bedeutung der Mündlichkeit in den Texten des Mittelalters als Stütze der Erkenntnisentwicklung, die insbesondere in der Praktik des Zitierens und des Exzerpierens hervorgehoben wird.

Beim Zitieren und beim Exzerpieren verwenden die Gelehrten sowohl das explizit Gesagte -- kontextualisierte Zitate oder Erwähnungen von Textstellen aus anderen Texten bzw. von anderen Autoren -- als auch das Nahegelegte -- die Paraphrase --, sowie das Nicht-Gesagte -- die Verwendung von Textstellen anderer ohne Verweis auf die Quelle bzw. als stillschweigende Übernahme von Textpassagen oder Argumente Dritter. Bei den Verbindungen, die die Autoren zwischen dem Zitierten, dem Paraphrasierten und dem Plagierten an ihrem Text herstellen, geht es darum, dem Text eine "gute" Autorität zu verleihen. Dazu gehört ebenso, dass das Wiederverwendete nicht als solches sichtbar ist und auch nicht als solches wahrgenommen wird: "Das Autoritätsargument wird von den Mittelalterlichen immer noch als einer der niedrigsten, wenn nicht der niedrigste, theologische Ort angesehen. Der edle Gebrauch von Autorität, d. h. die richtige Verwendung eines Textes, eines Satzes oder eines Fragments, ist still: Es ist nicht einmal die Intertextualität, sondern die Intratextualität, die Assimilation, die Abwendung, die Wiederverwendung des Anderen, die Verwischung des Unterschieds, die Totalisierung der Diskurse" (ebd. 26). Während also das Lesen den Text insbesondere mit dem Gedächtnis des Lesers verbindet, sollen die Techniken des Zitierens und Exzerpierens eher das Gedächtnis des Lesers zum Vorteil von einem künftigen Leser eines Textes bringen, der dann zum medialen Gedächtnis wird und es als Kulturgut symbolisiert. Diese Behandlung von Text als Rezeption des Gedächtnisses, die im Mittelalter als wichtigste Stütze des Wissens und der Kultur wahrgenommen wird [@Wenzel1995], ist gleichzeitig die Grundbedingung für die kritische Auseinandersetzung mit Texten und zwar verstanden im Sinne der Verbindungen, die ein Text zwischen anderen Texten und Autoren herstellt, darstellt und schließlich veröffentlicht. Mit dem Exzerpieren als Lagerung bzw. Aufbewahrung des Gelesenen in Handschriften und Texten, als _copy/paste_ mit Schere und Klebstoff, wie in Wörterbüchern und Enzyklopädien häufig praktiziert, ändert sich im 18. Jahrhundert von Grund auf, so die These von Elisabeth Décultot [@Decultot2014], die Lesekultur und die Verschriftungspraxis im Sinne einer Veränderung des Verhältnisses zum Text, zu den Autoren und zu den Institutionen des Wissens. Die symbolische Media "Text" und mit ihr die Verhältnisse zum Text gehen somit in feinere Verfahren der Formalisierung ein.

Während also im Mittelalter und in der Renaissance das Exzerpieren nach Rubriken organisiert wird, die auf das Erbe der Antike zurückgehen und von Textsammlungen zu Textsammlungen fast identisch verwendet werden, ändern sich die Methoden des Exzerpierens im Lauf des 17. Jahrhunderts [@Decultot2023, 95]. Mehrere Autoren, die Texte zum methodischen Exzerpieren schreiben, unterstreichen, dass diese Kategorien, nach denen Texte exzerpiert werden, mehr an den Bedürfnissen des Lesers orientiert und eher nach der Struktur des gelesenen Textes ausgewählt und verwandelt bzw. umformuliert werden sollten (die _miscellanea_ im Kontrast zu den _collectanea_; vgl. ebd., 97). Textstellen für sich selbst genommen zu kopieren, wird im 18. Jahrhundert mehr und mehr als "das einzig richtige Mittel, den Text zu assimilieren", verstanden (ebd., 101). Diese Praxis führt zur Genese von neuen Texten, die zumeist in Form von Exzerpten vorgelegt werden [vgl. vergleichbare Anmerkungen für die Zeit von der Spätantike bis zum frühen Mittelalter in @Dusil2017; vgl. auch @Strosetzki2015]. Das Exzerpieren wird damit über die Literatur und die Philosophie hinaus bis hin zu anderen Bereichen wie der Kunstgeschichte oder den experimentellen Wissenschaften als personalisierte Methode der kritischen Auseinandersetzung mit Texten und Textsammlungen zur möglichen Verwendung in der eignen Textproduktion verbreitet. Mit der Systematisierung des Exzerpierens ab dem 18. Jahrhundert wird nicht mehr einfach "narrativ" bzw. ohne Fragestellung oder ohne ein festes Ziel gelesen. Es wird gelesen, um bestimmte Textstellen aus Texten zu selektieren und zu extrahieren, die eine Fragestellung untermauern, oder es erlauben, das vom Leser angestrebte Ziel zu erreichen [@Abbott2014]. Die Praktik des Exzerpierens wird somit zur formalen Grundlage weiterer schriftlichen Medien wie der Rezension, die zu den Institutionen des Journalismus und der literarischen Kritik führt [vgl. dazu @Gantet2021 am Beispiel von Albrecht von Haller]. Für diese Institutionen stellt die Attraktivität von Texten den Kern ihrer Arbeit an der Entwicklung ihrer Vermittlungsstruktur dar, die sie entsprechend ihrer Vermittlungsstruktur weiterhin formalisieren bzw. nicht nur rezensieren, sondern auch hierarchisieren, kontextualisieren, perspektivieren usw. Damit tragen sie dazu bei, die Vielfalt der Lese- und Schreibpraktiken um formale Verfahren der Auseinandersetzung mit Texten zu verbreiten und somit die Produktion von Texten nicht nur zu diversifizieren, sondern auch zu professionalisieren. Um diesen Zusammenhang zu veranschaulichen, konzentrieren wir uns nun auf ein Beispiel, das sich genau an der Schnittstelle zwischen dem Bereich der Literatur, den Instanzen der literarischen Kritik und der Presse im 19. und im 20. Jahrhundert in Frankreich bewegt.

## Literatur, literarische Kritik und die Presse

Im Rahmen der Literatur arbeitet die spezialisierte Kritik daran, Texte nicht nur attraktiver zu machen, sondern sie in Bezug auf diese Attraktivität zu werten. Das Problem, das die spezialisierte Kritik adressiert, ist weniger dasjenige, dass Wieland und Nietzsche hervorheben, wenn sie die Rolle des Autors eines Textes als _auctoritas_ und daher als Sprachrohr der richtigen Deutung der Intentionen des Autors zur Gewährleistung des richtigen Wissens über den Text perspektivieren. Wie Roland Barthes und zu einem gewissen Grad auch Michel Foucault nahelegen, darf die _auctoritas_ des Textautors über seinen Text nicht überschätzt werden [@Barthes1984; @Foucault1969]. Ein Text setzt zudem immer Paratexte und Intertexte voraus [@Kristeva1969], die seine Dimensionalität vervielfältigen und dessen eigene Interdiskursivität hervorheben [@Compagnon1979], wie sie etwa im Genre des Romans Fjodor Dostojevski berühmt gemacht hat. Diese Intertextualität gelangt zudem in den Vordergrund dessen, was die Kritiker fokussieren, wenn sie einen Text rezensieren. Es geht um den Text als eine Sammlung von Texten im Text, die die Kritiker zwar nicht unabhängig von der Autorenschaft, die am Text mittelbar und unmittelbar mitwirken, betrachten. Sie werten ihn aber nicht mehr nur in Bezug auf einen menschlichen _auctoritas_, sondern in allgemeinerer Form vom Standpunkt der Effektivität des Textes in Unterstützung der Literatur und der Zirkulation -- von Ideen, Methoden, Techniken, Gefühlen, Emotionen sowie von Akteuren, die in diesem Bereich tätig sind --, von seiner Durchsetzungskraft als Mediation von möglichst allen vorstellbaren Verhältnissen zur Literatur. Mit dieser Kritik wird also gleichsam der Attraktivität eine wichtige Bedeutung als Ausgangs- und Endsequenz der Zirkulation in der Literatur eingeräumt, die entsprechend von weiteren Kollektiven und Instanzen besetzt wird. Sie werden dort aufgebaut, um die Literatur und ihre Akteure zu fördern und eine Umverteilung von textuellen Mediationen zur Effizienz der Zirkulationen in der Literatur vorzunehmen, wovon wiederum die kleinen und größeren literarischen Zeitschriften sowie die Verlage ein Beispiel geben.

Kleine und größere Zeitschriften für Literatur werden in Europa ab dem 17. Jahrhundert veröffentlicht. Ihre Verbreitung profitiert einerseits von der wachsenden Zahl von Akteuren, die Autoren werden und von denen mit Beginn des 19. Jahrhunderts die Mehrheit aus dem Groß- und Kleinbürgertum stammt [@Darnton1991; @Charle1982]. Andererseits wird deren Verbreitung aber auch von der Vergrößerung des Leserkreises gefördert, der im 19. Jahrhundert mit der Verrechtlichung, dem wachsenden Bildungsniveau und der voranschreitenden Alphabetisierung deutlich fortschreitet. Im Unterschied zu den Verlagen arbeiten die Zeitschriften jedoch nicht primär an der Materialisierung der Attraktivität von Literatur. Sie arbeiten vielmehr an der Attraktivität der Investition in die Literatur, wodurch sie zusehends zu  unangefochtenen Institutionen für derartige künstlerische Tätigkeiten generieren, d. h. zu uneingeschränkten Instanzen der Vermittlung von Kunst und Kunstschaffenden einerseits und von Zirkulationen sowohl innerhalb der Kunst als auch zwischen der Kunst und anderen Tätigkeitsbereichen in anderen Relationsstrukturen werden. Wie Pierre Bourdieu anmerkt, führt diese Institutionalisierung der Literatur -- und im allgemeinen der künstlerischen Praktiken -- zur Strukturierung der Produktion der Literatur nach einer eingeschränkten und einer kommerziellen Produktion [@Bourdieu2008]. Diese Spaltung spiegeln die Distinktionskämpfe zwischen Autoren, Literaturgenren, Zeitschriften und Verlagen wider, die die Institutionalisierung der Kunst bzw. ihre feste Verankerung in einer Ordnung von Verhältnissen mit eigener Zirkulation, Einschreibungsakten und Legitimiationsprinzipien abbildet. Die Unterscheidung zwischen einerseits der reinen Literatur, die Bourdieu als die Gewährleistung der Automie der Literatur versteht und in der er die Herrschaft der Hochkultur sieht, und andererseits der unreinen Literatur als stets offene Tür zur niedriegeren bzw. dank der Schule gelernten literarischen Kultur, die die Großproduktion massifiziert, bildet die Grundlage der "Prinzipien der Vision und Division" der Welt, die die Institutionen der Literatur -- in erster Linie die Zeitschriften -- durchzusetzen versuchen [etwa @Bourdieu1991, 13]. Daraus entsteht eine Dialektik der Autonomie/Heteronomie der Literatur, bei der nach Bourdieu das Außen die Autonomie der Literatur entkräften will, um ihr ihre Hierarchieprinzipien aufzuzwingen, die wiederum der kommerziellen Logik der Nachfrage von Werken folgt und die Autoren entsprechend entlang der Assoziationskette "verkaufsstark, erfolgreich, berühmt" vs. "verkaufsschwach, nicht erfolgreich, unbekannt" hierarchisiert. Dagegen wehren sich die Autoren, die die Literatur lediglich um der Literatur selbst willen unterstützen und Hierarchieprinzipien in der Literatur entwickeln, die aus der Anerkennung zwischen Autoren auf der Grundlage ihrer Investition in die Literatur entsteht. Für diese Kunstschaffenden versteht sich die eigene Bedeutung und die Bedeutung ihrer Tätigkeit nicht nach Verkaufszahlen und Materialität, sondern nach Prestige und Attraktivität.

Dies erklärt auch, weshalb es zwischen den Zeitschriften und den Verlagen häufig zu Konflikten in Bezug auf die Autoren kommt, die dieselben veröffentlichen [@Schuh2020] und deren Verankerung in zwei unterschiedlichen Sequenzen der Zirkulation in der Literatur infolge der Institutionalisierung ihres unterschiedlichen Verhältnisses zur Literatur und ihrer Akteure widerspiegelt. Die Zeitschriften, die im Fall von kleinen Zeitschriften bzw. von Zeitschriften kleineren Formates nur einige Monate/Jahre erscheinen und deren finanzielle Situation in der Regel prekär ist, wollen Autoren -- meistens neue oder wenig bekannte Autoren -- in allen möglichen Bereichen der Literatur fördern. Dies gilt insbesondere für die kleineren Zeitschriften, die nicht selten von solchen Autoren organisiert und herausgegeben werden, deren Inhalt sehr vielfältig ist und für die es primär um die Attraktivität der Autoren geht, die dort veröffentlichen. Um diese Zeitschriften entwickeln sich Soziabilitätsnetzwerke zwischen solchen Autoren (zum Verständnis von Soziabilitätsnetzwerken in der Auffassung der Theorie der Relation vgl. @PapilloudSchultze2022, 305-310), die sich mit diesen Zeitschriften in der Literatur einschreiben. Belege einer solchen Einschreibung liefern Autoren, die nicht nur in unterschiedlichen Zeitschriften publizieren bzw. tätig sind, sondern auch des Öfteren als Redakteure dieser Zeitschriften in Erscheinung treten. Für jene Autoren eröffnen sich dadurch Zirkulationsmöglichkeiten zu größeren und berühmteren Zeitschriften, zu denen die entsprechenden Autoren vermehrt weiter zirkulieren [vgl. @Schuh2020, 105 beispielhaft zur Zirkulation von Alfred Jarry und Léon-Paul Fargue] und ihre Einschreibung mit den Redakteuren und Herausgebern von diesen letzteren Zeitschriften konkretisieren können. Diese starke Vernetzung von kleinen und größeren Zeitschriften mit entsprechenden Soziabilitätsnetzwerken zwischen neuen bzw. kaum bekannten Autoren und berühmten Redakteuren tendiert jedoch gleichsam dazu, den Verlagen die Autoren abspenstig zu machen, deren Geschäftsmodell sie zudem insofern adaptieren, als sie selbst kleine Verkaufsstrukturen entwickeln [@Mollier1999].

Insbesondere ab der Mitte des 19. Jahrhunderts bis zum Ersten Weltkrieg wehren sich die Verlage immer mehr gegen die Macht der Zeitschriften, von denen sie finanziell geschwächt und in eine Nebenrolle in der Unterstützung von Literatur gedrängt werden, was die Verlage mehr und mehr dem Einfluss dieser Zeitschriften unterwirft. Für die Verlage stellen die kleinen und größeren Zeitschriften im Wesentlichen "Kommunikationsmittel für die Verlage", insbesondere in Verbindung mit der Presse, dar. Nur so können die Verlage ihre Rolle und ihre Position in der Literatur als Multiplikatoren nicht nur für die Autoren, sondern auch für die Texte und die Zeitschriften, die sie veröffentlichen, wahrnehmen und halten. Das Selbstverständnis der Verlage besteht folglich darin, dass sie sich als Institutionen sehen, die die Autoren und Zeitschriften zur Presse bringen und ihnen auf diesem Weg möglicherweise zum öffentlichen und kommerziellen Erfolg verhelfen (ebd., 106). Eingedenk dieses Selbstverständnisses der Verlage äußert sich Léon Vanier gegenüber Louis Lormel folgendermaßen: "'Zu Ihnen, die die Feder halten, geht der Ruhm, und mir an der Theke gehört der Verkauf. Und alles wird in der Welt der Zeitschriften besser'" (ebd., 97). Oder um es in den Termini der Theorie der Relation zu formulieren: Die Verlage bestehen darauf und erinnern die Zeitschriften daran, dass Satellisierung nicht gleich Satellisierung ist. Eine Satellisierung innerhalb einer Relationsstruktur, d. h. zwischen den Instanzen derselben Relationsstruktur, kann die Relationsstruktur durch die verursachte Konkurrenz zwischen zwei Hierarchieprinzipien und den entsprechenden Hierarchien zwischen Medien, Soziabilitätnetzwerken und Akteuren schwächen oder gar stören. Demgegenüber kann eine Relationsstruktur von einer Satellisierung gestärkt werden, so diese Satellisierung zwischen Relationsstrukturen entwickelt wird und die Kernsequenz der satellisierenden Relationstruktur -- meistens unmittelbar -- stärkt. Genau das haben die Verlage bei ihrem Streit mit den Zeitschriften im Blick: Um das Interesse der Presse dafür zu wecken, sich den Weg zu einem breiteren Publikum zu bahnen und dieses Publikum zur Literatur zu bringen, muss die Arbeit an der Vermittlungsstruktur von Instanzen der Literatur nicht etwa redundant entwickelt werden, sondern im Interesse von allen und die Tätigkeiten und Tätigkeitsbereiche sowohl von Zeitschriften als auch von Verlagen gut geteilt werden. Aber dafür muss der Kontext stimmen, und in der Zeit des Konfliktes zwischen Verlagen und kleinen wie großen Zeitschriften am Ende des 19. Jahrhunderts in Frankreich stimmt der Kontext selbstredend nicht.

Marie-Françoise Melmoux-Montaubin erklärt dies wie folgt: "Mit der Dritten Republik schrumpft die literarische Presse und mit ihr die kritische Tätigkeit in den Zeitungen schon vor den Gesetzen von 1881. Diese Wende passiert eigentlich am Ende des Zweiten Reiches: Der politische Diskurs übernimmt einen wachsenden Platz, die Liberalisierung des Regimes erlaubt bald, die eigene politische Meinung uneingeschränkt auszudrücken. Während das Feuilleton und die Veröffentlichung von Fiktionen in Ausschnitten noch einen, wenn auch kleinen Platz in den Zeitung behalten, wird die Kritik allmählich ausgeschlossen [...], als ob Kolumnisten und Journalisten ironisch bezeugen würden, was die Realität der 'Literatur' in den Zeitungen des XIX. Jahrhunderts für sie war: eine Unterhaltung, die mit keinem essentiellen Interesse für die Literatur verbunden war" [@Melmoux2001, 939]. Die Presse, die in Frankreich im Laufe des 19. Jahrhunderts die wichtigste Instanz für die Verselbständigung einer medienorientierten Relationsstruktur im Werden darstellt, folgt dabei dem Pfad, der ihre eigene Verselbständigung nicht nur von der Literatur, sondern auch von der Politik strukturiert hat: Die Verbindung mit dem Alltäglichen in ihrer Diversität, die ihre Rubriken und später ihre Deklinationen in zahlreichen Magazinen widerspiegeln, sowie die Kommentierung dieser Diversität in kleinen knappen Artikeln. Mit der Verbreitung des Telegraphnetzwerkes, das die Zirkulation der Information beschleunigt und das Gefühl der Augenblicklichkeit der Information vermittelt, wie Gabriel Tarde im Jahre 1901 sagt [@Tarde2006], mit der Eisenbahn, die die Zeitungen schnell und zu einem niedrigen Preis überall hin transportiert, und nicht zuletzt mit dem Anstieg der Papierproduktion parallel zur Verbesserung der Drucktechniken [@Feyel2011] verändert sich die Auffassung zur Information, die Organisation der Zeitungsredaktionen und die Rolle des Journalisten. Es geht um knappe Schilderungen von konkreten Ereignissen auf der Grundlage von Reportagen, die von entsprechenden Reportern im Feld vermittelt werden und die öffentliche Meinung einerseits informieren und vertreten, andererseits aber auch befragen und messen sollen [@Kalifa2011]. Mit dem Journalismus und mit dem Aufstieg einer medienorientierten Relationsstruktur entsteht gleichzeitig mit dem Anspruch einer neuen Organisation und einer deutlich beschleunigten Verbreitung von Informationen die Anschauung, dass die Information perpetuell generiert und parallel dazu anhand von effizienteren Medien kontrolliert werden sollte, damit die Information nicht entwischt. In Vereinbarung dieser zwei, scheinbar widersprüchlichen Ansprüche bereitet den Weg zur Entwicklung von Überlegungen über die effiziente Verwaltung und Verbreitung von Informationen anhand von Rechnern vor, aus der dann die Forschung im Bereich der künstlichen Intelligenz entsteht und zur Entwicklung von Transformern führt.

## Die digitale Wende

Die grundsätzlichen Operationen von Transformern weisen auf eine Fülle von Lese- bzw. Schreibtechniken und Praktiken hin, die diese Transformer in zahlreichen Verhältnissen dimensionieren und solche Verhältnisse in der Form von Algorithmen zu neuen Verbindungen von Informationsinhalten miteinander verknüpfen und somit zur Generierung neuer Informationen aus Sprachdateien und darüber hinaus aus allen möglichen digitalen Dateien formalisieren und verwenden. In dieser Hinsicht sind Transformer grundsätzlich nicht neu, wie wir in diesem Kapitel gezeigt haben. Was sie neu macht -- wie am Beispiel der Presse zu Begin des 20. Jahrhunderts gezeigt -- ist die Fülle an Informationen, die sie behandeln und zur Verfügung von möglicherweise allen Akteuren und Kollektiven in einer sehr kurzen Zeit, wenn nicht gar augenblicklich zum finanziellen Profit der Dienstleister, die sie wiederum konzipieren und warten, stellen können. Diese Massifikation der Information unterscheidet sich in zweierlei Hinsicht von derjenigen der Presse und später des Rundfunks, des Fernsehers und selbst des Internets. Zum einen betrifft sie jeden gesellschaftlichen Tätigkeitsbereich -- ausgehend von den spezialisiertesten Tätigkeitsbereichen zu denen des _common sense_, der Unterhaltung, der Freizeit usw. -- und jeden ihrer Aspekte [@Zong2022]. Zum anderen wird sie zur Verfügung von jedem Akteur und jedem Kollektiv gestellt. Dadurch ist es Akteuren wie Kollektiven möglich, aus der zur Verfügung gestellten Masse an Information ihre je eigenen Verbindungen zu gestalten und neue Informationsinhalte zu generieren. In diesem Sinne sind Transformer ein Super-Akkumulator und Super-Produzent von Informationen aller Art und entsprechend eine mächtige Mediation zur Satellisierung von anderen Relationsstrukturen durch die medienorientierte Relationsstruktur. Dies verdanken die Transformer der weiteren Verselbständigung von Texten und im Allgemeinen von all dem, was in Information umgewandelt werden kann, deren zeitgenössischer Vertreter und aktuelle Verlängerung Transformer darstellen. Diese Verselbständigung entspricht einer dreifachen Verschiebung der Perspektive zur Information im Bereich der digitalen Techniken.

Die erste Verschiebung ist mit dem Namen von Vannevar Bush (1890-1974), Gründer des _National Defense Research Committee_ unter Roosevelt (1940) und Leiter des _Office of Scientific Research and Development_ in den Vereinigten Staaten während und nach dem Zweiten Weltkrieg, verbunden. Bush konzipiert in den 1920er Jahren einen elektromechanischen Rechner, der komplexe Differentialgleichungen lösen soll [@Shurkin1984, 95]. Dieser Rechner ist eigentlich eine Zusammenstellung von unterschiedlichen elektromechanischen Elementen, die insgesamt 200 Tonen wiegen und mit 300 Kilometern von Kabeln miteinander verbunden sind. Das Projekt erfreut die amerikanische Regierung und beeindruckt die Bevölkerung, für die eine solch enorme Maschine wie ein "'gigantisches mechanisches Gehirn'" aussieht [@Bowles1996, 5]. Dieses Bild übernimmt Bush in seinem Text zur Entwicklung der Forschung zu Rechnern im Jahre 1945 und erwähnt in diesem Zusammenhang die Verbindung zwischen Rechnern und der menschlichen Intelligenz [@Bush1945]. Im Vergleich zur Information bedeutet die Idee von Bush, dass die Entwicklung von Rechnern den Inhalt von Information fokussieren sollte, um Information gut verwalten, organisieren und in der Gesellschaft gerecht verteilen zu können. Dies ist deshalb geboten, weil die steigende Produktion von Informationen das Risiko birgt, dass Akteure und Gesellschaften von Informationen überflutet werden. Einer solchen Entwicklung sollen Rechner entgegenwirken, indem sie dabei helfen zu verstehen, welche Information wichtig bzw. notwendig ist und welche nicht. Diese erste Verschiebung, die von der formalen Mediation "Information" zu ihrem Inhalt geht und die Grundlage für den vernünftigen Umgang mit der Information in den Gesellschaften nach dem Zweiten Weltkrieg bereiten soll, führt zu einer zweiten Verschiebung in Folge von Alan Turings Vision von intelligenten Maschinen.

Die zweite Verschiebung der Perspektive zur Information besteht in der Herausforderung, die Bushs Vorschlag mit sich bringt. Wenn es darum geht, anhand von Rechnern Informationen ab (anhand) deren Inhalt(s) zu verwalten, dann setzt das voraus, dass Rechner in der Lage sind, diese Information selbstständig inhaltlich zu bewerten. Dafür sollten die Rechner eine ähnliche Intelligenz wie die menschliche aufweisen, um den Inhalt von Information auswerten zu können und dabei zu helfen, diese Information nach ihrer Bedeutung zu hierarchisieren. Solche Rechner sind nicht mehr elektromechanische Maschinen, die mathematische Gleichungen berechnen. Es handelt sich um Rechner von Rechnern, um Prozeduren, die an unsere zeitgenössische Software erinnern, und mathematische Funktionen, die auf der Grundlage von binarisierten Daten berechnet werden. Dass diese Rechner auf Englisch "computer" genannt werden, geht dabei auf einen von Turing angestellten bzw. nahegelegten Vergleich zwischen seiner Auffassung von solchen (theoretischen) Rechnern einerseits und der Funktion von Personen andererseits, die Kalkulationen in der Wissenschaft und in Organisationen vornehmen [@Turing1950, bes. 435], was die Aufmerksamkeit der Forscher unweigerlich auf die Konzeption von Rechnern lenkt, die die kognitiven Funktionen von Menschen nachahmen können [@Aspray1985]. Die Idee von intelligenten Maschinen oder, wie John McCarthy sie nennt, von der künstlichen Intelligenz der Maschinen [@Luhl1996, 11], stimmt jedoch mit Turings Verständnis von "Intelligenz" nicht überein. So hat er mit diesem bildhaften Terminus nicht etwa die Kompetenz, sondern die rechnerische Leistung von Rechnern im Blick [@Block1981, 16; @Block1995, 384], die aufgrund eben jener rechnerischen Leistung imstande sind, Menschen den Eindruck zu vermitteln, dass das Verhältnis zum Rechner dem Verhältnis zu einem anderen Menschen ähnlich sei [@Unseld1992, 188]. Von dieser Auffassung von Rechnern bis zu der Idee, dass Rechner mächtige Vermittler von Verhältnissen zur Information werden könnten, sind es nur noch wenige Schritte, die den Weg für die dritte Verschiebung der Perspektive zur Information bahnen.

Die Voraussetzungen der dritten verschiebung fasst Nornberg folgendermaßen zusammen: "In den späten 1950er Jahren begannen einige Forscher, Rechner als Partner im kreativen Denken zu betrachten, um die Interaktion zwischen Menschen und Computern, die Beschaffung von Systemen mit künstlicher Intelligenz, die Entwicklung natürlicher Sprache und Übersetzungssysteme für Maschinensprache zu erforschen" [@Nornberg1996, 43]. Diese Forschenden arbeiten entlang eines anderen Ansatzes, der von Akkustikforscher Jack Licklider (1915-1990) inspiriert ist und wonach es darum gehe, aus Rechner kompetente Mitarbeiter von Menschen zu machen, die zusammen an "der Entwicklung der interaktiven Verwaltung der Information" arbeiten [@Licklider1967, 3]. Die Theorie der Kommunikation, an der Licklider arbeitet [vgl. @Licklider1968], findet ferner ihren Ausgangspunkt in der Auffassung von Informationen als etwas, was kontinuierlich von Menschen produziert wird und deshalb für Einzelmenschen schnell unüberschaubar wird, wenn sie die Informationen nicht in Zusammenarbeit mit Rechnern verwalten können. Dieser Ausgangspunkt setzt voraus, dass Vorräte an Informationen konstituiert und angelegt werden, die von Rechnern ausgewertet werden können, damit die Fragen von Menschen, deren entsprechende Antworten solche Vorräte an Informationen bereits enthalten müssten, schnell und präzise beantwortet werden können. Vom Standpunkt Lickliders gibt es in Bezug auf Informationen keine Unterscheidung zwischen Wissen und Nicht-Wissen, weil das Nicht-Wissen einem in der Fülle der Information versteckten Wissen entspricht, zu dem wir keinen Zugang haben, weil eben gerade die Fülle an Information dies verhindere (ebd.). Deshalb müssen Rechner so entwickelt werden, dass sie den Menschen den Zugang zu diesem Wissen eröffnen und ihnen dabei helfen, dieses Wissen in Verbindung mit anderen Informationen zu bringen, und zwar zur Generierung von neuen Informationen einerseits und neuem Wissen auf Basis dieser neuen Informationen andererseits. Dieses "neue Wissen" ist nicht nur eine neue Gestaltung des bereits vorhandenen Wissens, sondern es ist auch ein Wissen, das sich aus dieser interaktiven Reflexivität zwischen Menschen und Rechnern zur Information ergibt und zum Vorrat von vorhandenen Informationen beiträgt, was dieses Wissen wiederum bereichert. Nach Lickliders Theorie der Kommunikation wird nicht nur die Information auf die mediale Kontrolle von Rechnern anhand von Software geschoben, sondern auch -- wenn auch nicht vollständig, so doch zumindest zum Teil -- die Operationen, die mit dem Aufgreifen und der Produktion von Informationen verbunden waren -- also grundsätzlich mit den Lese- und Schreibpraktiken, die solche Rechner immer mehr von selbst durchführen können. Das Prinzip, welches der Entwicklung von Transformern zugrunde liegt, ergibt sich also aus dieser dreifachen Verschiebung der Perspektive zur Information. Es trägt dazu bei, die medienorientierte Relationsstruktur in ihrer Unabhängigkeit von den anderen Relationsstrukturen zu stärken und ihre mächtigen Mediationen in Unterstützung ihrer Satellisierungsstrategien zu platzieren, was ab den 1970-80er Jahren mit dem Aufbau von entsprechenden Institutionen der Förderung der Informatik in diesen Relationsstrukturen im Laufe der Entwicklung des _personal computer_ und des Internets deutlich wird.

## Schlußwort

In diesem Kapitel haben wir am Beispiel von Transformern beschrieben, wie Medien zu Akkumulatoren und Multiplikatoren von Verhältnissen werden, die im Rahmen von Transformern auf eine lange Geschichte der Verschiebung des technischen und praktischen Umgangs mit textuellen Informationen auf Mediationen dieser Informationen verweist -- Texte in Form von Fachbüchern, Wörterbüchern, Enzyklopädien, literarischen Texten, Zeitschriften- und Zeitungsartikeln und mit der digitalen Wende von allen möglichen Textdateien und weiteren nicht textuellen Dateien (etwa Bildern oder Tönen). Dabei werden solche Verhältnisse nicht nur im Sinne von Aufnahme- und Abgabepraktiken bzw. von Lese- und Schreibpraktiken und entsprechenden Techniken auf Mediationen übertragen, sondern auch auf weitere Verhältnisse, die die Deutung der Informationsinhalte und ihre Gestaltung zur Generierung von Wissen miteinbeziehen. Wir haben gesehen, dass eine solche Verschiebung von Verhältnissen auf Mediationen nicht nur zur Verselbstständigung dieser Mediationen führen, sondern am Beispiel der Literatur auch zur Strukturierung von Tätigkeitsbereichen in Relationsstrukturen, bei denen diese Mediationen verwendet werden. Dieser Prozess gipfelt in der Verselbständigung von einer Relationsstruktur, in der die Attraktivität von Mediationen zur Kernsequenz entwickelt wird und die Zirkulation von Akteuren, die Position von gesellschaftlichen Vermittlungsinstanzen und deren Einschreibungsakte strukturiert. In dieser Relationsstruktur sind Legitimationsverfahren und die Legitimität unmittelbar mit der medialen Kontrolle von Mediationen verbunden, die als die Reziprozität in der medienorientierten Relationsstruktur hervorgehoben und in Form einer unimodalen Reziprozitätsmacht in der gesamten Relationsstruktur verstetigt wird [@PapilloudSchultze2022, Tab. 9.1, 374], um dann auf Basis von eben jener medialen Kontrolle von Mediationen von dieser Relationsstruktur ausgehend auf die drei anderen Relationsstrukturen verbreitet zu werden.

Aus der Verselbständigung der Medien und der Konstitution einer medienorientierten Relationsstruktur als einer Ordnung von Verhältnissen, die von Mediationen aufgenommen, verarbeitet und produziert wird, ergeben sich wiederum zwei Folgen. Die erste Folge haben wir schon thematisiert. Sie betrifft die Schließung der Erzeugung von weiteren Relationsstrukturen als Ordnung von Verhältnissen. Mit der Verselbständigung der medienorientierten Relationsstruktur ist die letzte Abweichungsmöglichkeit von einer _idealen_ Relation verwirklicht worden, wobei diese Abweichung darin besteht, die Produktion von Verhältnissen aussschließlich auf Mediationen zum Vorteil der Zirkulation in Relationsstrukturen zu gründen. Die zweite Folge, die sich aus dieser Schließung der Generierung von weiteren Relationsstrukturen ergibt, betrifft die Relativierung der Bedeutung von einzelnen Relationsstrukturen zum Vorteil ihrer Sequenzen und der damit verbundenen Arbeit von gesellschaftlichen Instanzen in diesen Sequenzen. Dabei verschiebt sich die Auffassung über den Einfluss zwischen Relationsstrukturen auf den Einfluss zwischen den Sequenzen von Relationsstrukturen als die Möglichkeit für gesellschaftliche Instanzen, aus Satellisierungsstrategien die eigene Relationsstruktur ab ihrer Sequenz -- hier der Sequenz Attraktivität -- zu subvertieren. Damit zielen die gesellschaftlichen Instanzen darauf ab, in der Zusammenarbeit mit gesellschaftlichen Instanzen in anderen Relationsstrukturen Metarelationsstrukturen zu entwickeln [Näheres zu Metarelationsstrukturen vgl. ebd., 414-420; siehe auch am Beispiel der Translation in der Nanomedizin @PapilloudSchultze2023, 251-259], die sich von den jeweiligen Determinanten der allgemeinen Zirkulation in jeder der vier Relationsstrukturen befreien können. Solche Metarelationsstrukturen leben vom Ideal einer Relation, das unabhängig vom Primat der Zirkulation existiert, in denen die Sequentialität der Zirkulation durch Zirkulationen innerhalb und zwischen Sequenzen von Metarelationsstrukturen subvertiert und damit für Akteure und Instanzen in solchen Metarelationsstrukturen stark relativiert ist. In solchen Metarelationsstrukturen zählen nur noch einzelne Zirkulationswege und Zirkulationsmöglichkeiten zur Rechtfertigung einerseits von Einschreibungsakten und andererseits von Positionsumstellungen der Akteure, sowie darüber hinaus zur Rechtfertigung der Positionsstärkung der gesellschaftlichen Instanzen, wovon die medienorientierte Relationsstruktur lediglich einen ersten Vorgeschmack gibt.

## Literatur
