---
title: "Exkurs zu sozialen Ungleichheiten"
indent: true
output:
    html_document: default
csl: chicago-author-date.csl
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Wir haben mehrmals über die Art und Weise überlegt, wie wir dieses Thema der sozialen Ungleichheiten vom Standpunkt der Theorie der Relation einführen wollten. Die sozialen Ungleichheiten stellen nicht nur ein wichtiges, sondern auch ein anspruchvolles Thema der Soziologie und der Sozialwissenschaften mit einer unübersichtlichen Sekundärliteratur dar. Es stellt sich deshalb die Frage, inwiefern die Theorie der Relation die Soziologie in ihren Untersuchungen der sozialen Ungleichheiten neu herausfordern kann. Im Folgenden versuchen wir, diese Frage mit den Grundbegriffen der Theorie der Relation, die wir in diesem Band mit Beispielen illustriert haben, zu vertiefen und eine Antwort zu skizzieren. Um dem Leser den Zugang zur Perspektivierung der sozialen Ungleichheiten mit der Theorie der Relation zu erleichtern, wollen wir zuerst ein Parallel mit der Forschung im Bereich der Intersektionalität ziehen. Der Grund dafür ist, dass wir in der Theorie der Relation einen vergleichbaren Anspruch wie in der intersektionalen Forschung finden, seitdem sich diese Forschung angefangen mit den Arbeiten von Patricia Hill Collins und Ange-Marie Hancock einen Schwung in die Richtung der soziologischen und sozialwissenschaftlichen Forschung erlebt hat [siehe insb. @Collins2000; @Hancock2007]. Die Intersektionalität als "neuer Begriff, um eine alte Frage der Theoretisierung von Beziehungen zwischen den unterschiedlichen Formen der sozialen Ungleichheit" [@Walby2007, 450], die 1989 von der afro-amerikanischen Juristin Kimberle Crenshaw zur Problematisierung der ethnischen und Geschlechtsungleichheiten verwendet wurde [@Crenshaw1989], verfolgt dem Ziel, eine multidimensionale Analyse der sozialen Ungleichheiten zu unterstützen. Dies bedeutet, dass vom Standpunkt der Intersektionalitätsforschung die sozialen Ungleichheiten nicht nach einer einzigen Ursache oder nach einer einzigen Herrschaftsmacht in der Gesellschaft erklärt werden können, sondern sie müssen ab der Relation zwischen den unterschiedlichen Kategorien von sozialen Unterscheidungen verstanden werden. Anders gesagt, unterstützen die Wissenschaftler und Wissenschaftlerinnen im Bereich der Intersektionalität ein Verständnis von sozialen Ungleichheiten an der Schnittstelle der unterschiedlichen sozialen Merkmale, der Verhältnisse zwischen Akteuren und gesellschaftlichen Instanzen in Zeit und Raum. Dies führt zur Veranschaulichung von nicht einer Achse, sondern mehreren Achsen der sozialen Ungleichheiten, die deshalb existieren, weil sie nicht auf einer gemeinsamen Grundlage ruhen. In der Theoriearbeit von Walby wird diese Idee von unterschiedlichen Grundlagen der sozialen Ungleichheiten wie folgt präzisiert [vgl. @Walby2007, 454, 459].

Um den "segregativen Reduktionismus" zu vermeiden (ebd., 459), sollte nach Walby die Intersektionalität nicht von einer einzigen, sondern von mehreren Grundlagen und Prinzipien der sozialen Ungleichheiten sprechen, weil diese Ungleichheiten aus unterschiedlichen Systemen von sozialen Verhältnissen entstehen, die sich gegenseitig mehr oder weniger beeinflussen. Diese Systeme sind Zusammenstellungen von Relationen, die sich von der Wirtschaft, zur Politik und zur Zivilgesellschaft (die drei Systeme, die Walby identifiziert) deshalb unterscheiden, weil sie nicht gleichermaßen organisiert und entwickelt werden. Dies spiegelt sich wiederum auf der Ebene der Akteure und Kollektivakteure wider, die in diesen Systemen tätig sind. Dies ist das, was Walby als die Ontologie von Systemen versteht, die in diesem Zusammenhang das Selbstverständnis von Systemen in Bezug auf ihre Art und Weise bedeutet, wie sie die sozialen Verhältnisse (nach Walby insbesondere die Klassen- und Geschlechtsverhältnisse sowie die Verhältnisse zwischen Ethnien) organisieren und (re)produzieren. Ist die Intersektionalität in der Lage, diese Zusammenstellung von Systemen und sozialen Verhältnissen besser zu verstehen, die solche Systeme gleichermaßen enthalten aber unterschiedlich organisieren und (re)produzieren, dann kann sie einen entscheidenden Beitrag zur Frage der Multidimensionaliät von sozialen Ungleichheiten sowie von ihren Wirkungen auf der Mikro-, Meso- und Makroebenen der Gesellschaft leisten. Diesen Anspruch teilt die Theorie der Relation aufgrund der gegebenen Multidimensionalität ihres Theorierahmens, auch wenn sie ihn nicht nur in Verbindung mit den Leitungskategorien der Intersektionalität (Geschlecht, Klassen und Ethnie) verbindet, sondern auch auf weitere Kategorien zu verbreiten versucht. Wenn soziale Ungleichheiten relational gedacht werden können, dann braucht es in der Soziologie eine Theorie, die der Komplexität vom Relationalen strukturieren kann, worauf die Theorie der Relation mit dem Primat der Zirkulation abzielt.

In diesem Sinne entstehen multidimensionale Strukturen von sozialen Ungleichheiten aus dem kontinuierlichen Einfluss zwischen den Relationsstrukturen und zwischen den Sequenzen innerhalb von diesen Relationsstrukturen. Durch die Zirkulationswege und -möglichkeiten werden sie je nachdem strukturiert, wie die Akteure in diesen Sequenzen und in diesen Relationsstrukturen ihre Einschreibung mit Vermittlungsinstanzen dieser Sequenzen und Relationsstrukturen entwickeln. Ähnlich wie in der Intersektionalitätsforschung beschäftigt sich dann die Theorie der Relation mit Intersektionen. Jedoch untersucht sie sie nicht primäre zwischen Kategorien von Merkmalen, sondern grundsätzlich zwischen Zirkulationen, Sequenzen und Relationsstrukturen, in denen diese Kategorien von Merkmalen unterschiedlich vorkommen und von unterschiedlicher Bedeutung für die Entstehung von Strukturen der sozialen Ungleichheit sind. Diese Intersektion zwischen Zirkulationen, Sequenzen und Relationsstrukturen ist also deshalb wichtig, weil sie über das Gewicht von Merkmalskategorien im Laufe der Einschreibung von Akteuren und Instanzen in Relationsstruktur, und daher über die Strukturierungskraft von solchen Einschreibungsakten sowohl für die Zirkulation der Akteure als auch für die Position von Vermittlungsinstanzen der Relationsstrukturen informiert. Daraus entstehen variable Strukturen der sozialen Ungleichheiten, die sich je nach Zirkulation, Sequenz und Relationsstruktur mehr oder weniger gut durchsetzen bzw. später oder früher von anderen Strukturen der sozialen Ungleichheiten ersetzt werden. Damit unterstützt die Theorie der Relation einen ähnlichen Ansatz wie in der Intersektionalitätsforschung. Es geht nicht darum, Strukturen der sozialen Ungleichheiten auf einen Nenner zu bringen. Es geht darum, die Vielfalt von diesen Strukturen besser zu erkennen. So kann besser verstanden werden, wie bzw. aufgrund von welchen Verhältnissen zwischen Zirkulationen, Sequenzen und Relationsstruktur solche Ungleichheiten entstanden sind. Es kann ferner besser verstanden werden, welche Merkmalskategorien eine wichtige Rolle für die Entstehung und die mögliche Durchsetzung und Verbreitung von solchen Ungleichheitsstrukturen spielen. Schließlich kann es besser verstanden werden, wie solche Merkmalskategorien durch ihr Gewicht auf die Einschreibung von Akteuren und Instanzen in Relationsstrukturen diese Relationsstrukturen in ihrer Zirkulation und folglich in ihrer Verbreitung auf die anderen Relationsstrukturen beeinflussen. Mit diesen letzten Sätzen befinden wir uns bereits im Herzen der Begrifflichkeit, die die Theorie der Relation verwendet, zu der wir jetzt einleitend und vertiefend kommen.

Aus den Themen, die in diesem Band entwickelt wurden, ist deutlich geworden, dass die Theorie der Relation mit vier grundsätzlichen Ordnungen von Verhältnissen bzw. mit vier Relationsstrukturen arbeitet, die sich voneinander auf der Grundlage ihrer sequentiellen Organisation unterscheiden [im Detail, vgl. auch @PapilloudSchultze2022, 81-119]. Entsprechend werden soziale Ungleichheiten nach der sequentiellen Ordnung der vier Relationsstrukturen aufgefasst. Deshalb unterscheidet die Theorie der Relation vier Muster der sozialen Ungleichheiten zwischen Relationsstrukturen, die mit den jeweiligen Relationsstrukturen in Unterstützung ihres Hauptmerkmals und dessen Verbreitung auf andere Relationsstrukturen verbunden sind. Weil Relationsstrukturen von den selben vier Sequenzen strukturiert sind, lassen sich diese vier Muster der sozialen Ungleichheiten nicht nur zwischen, sondern auch innerhalb von jeder Relationsstruktur vorfinden. Schließlich und weil sich Relationsstrukturen gegenseitig beeinflussen, gibt es ein Konkurrenzkampf zwischen diesen Mustern der sozialen Ungleichheiten innerhalb und zwischen Relationsstrukturen. Er bedeutet, dass die Forderung nach mehr Gleichheit -- wie ebenfalls die verwandten Forderungen nach mehr Anerkennung, Gerechtigkeit, besseren Arbeits- und Lebensbedingungen usw. -- den Versuch verdeutlicht, ein Muster der sozialen Ungleichheiten durch ein anderes zu ersetzen und es auf alle Sequenzen und Relationsstrukturen zu verbreiten. In dieser Hinsicht ähnelt unser Relationsansatz Bourdieus Prinzip der "Klassifikations- bzw. Klassifizierungskämpfe" [@Bourdieu1975b; @Bourdieu1980b; @Bourdieu1984a; @Bourdieu2012b], die für Bourdieu "Kämpfe um das Monopol auf die Macht über das Sehen und Glauben machen, über das Erkennen und Anerkennen, über das Durchsetzen der legitimen Definition der Gliederung der sozialen Welt und damit über die Bildung und Auflösung sozialer Gruppen sind" [@Bourdieu1980b, 65]. Aber an eben dieser Stelle unterscheidet sich unser Relationsansatz von Bourdieus Klassifikationskampf, weil soziale Ungleichheitsmuster, wie sie aus der Zirkulationsdynamik von Relationsstrukturen ausgebaut werden, nicht darauf abzielen, Positionen von Akteuren und Klassen von Akteuren in der sozialen Welt zu verfestigt. Es geht um die Verfestigung der jeweiligen Zirkulation dieser Relationsstrukturen selbst, d. h. von einer Zirkulation, deren Dynamik die damit verbundene Hierarchie von Akteurkategorien und von gesellschaftlichen Instanzen in einer bestimmten Relationsstruktur unterstützt. Nur so kann eine Umstellung der Position von Akteuren innerhalb einer Relationsstruktur oder zwischen Relationsstrukturen sowie eine Verfestigung der Position von gesellschaftlichen Instanzen in dieser Relationsstruktur gewährleistet werden. Deshalb beeinflusst dieser Kampf zwischen Mustern der sozialen Ungleicheiheiten die Art und Weise, wie Akteure Eintritts-, Ausstritts- und Übergangsbedingungen in, aus und zwischen Zirkulationen erfüllen. Demzufolge sind Akteure vertikal innerhalb von Sequenzen von Relationsstrukturen, horizontal in Bezug auf die eigene Akteurkategorie zwischen Sequenzen von Relationsstrukturen und im Querschnitt innerhalb von einer Relationsstruktur und zwischen den Relationsstrukturen ungleich und werden diesen drei Arten entsprechend ungleich verteilt. Mittelbar betreffen diese Ungleichheiten ebenfalls die gesellschaftlichen Instanzen der Relationsstrukturen, mit denen sich die Akteure in Zirkulationen und in einer Relationsstruktur einschreiben. Dies rekapituliert in konzentrierter Form die Auffassung von sozialer Ungleichheit vom Standpunkt der Theorie der Relation, wovon wir in diesem Kapitel sprechen werden.

## Einstieg

Um den Einstieg in dieses Kapitel vorzubereiten, wollen wir in gebotener Kürze an das Alleinstellungsmerkmal der Relationsstrukturen erinnern, das wir in unserem Theorieband beschrieben haben [@PapilloudSchultze2022]. Es besteht darin, dass die vier Relationsstrukturen eine unterschiedliche allgemeine Zirkulation aufzeigen, die in ihrer jeweiligen Kernsequenz sowohl beginnt als auch endet. Auf diese Kernsequenz der jeweiligen Relationsstrukturen kann zurückgegriffen werden, um die Relationsstrukturen in unmittelbarem Bezug auf die sozialen Ungleichheiten voneinander zu kontrastieren. Dies machen wir im Folgenden in Kurzform, wobei wir diese kurze Beschreibung in diesem Kapitel an gegebener Stelle weiter vertiefen.

Die Relationsstruktur mit Kernsequenz Investition verbreitet bevorzugt ein Muster der sozialen Ungleichheit, bei dem die Eintrittsbedingungen in Zirkulationen zur Unterstützung der Herkunftskollektive von Akteuren gestärkt werden. Daraus ergeben sich soziale Ungleichheiten, die vereinfacht nach der folgenden Aussage beschrieben werden können: Woher man kommt, bestimmt bis wohin man gehen kann. Die Zirkulation der Akteure der ersten Kategorie trägt zur Stärkung und zur Durchsetzung dieses Musters der sozialen Ungleichheit in dieser Relationsstruktur maßgeblich bei, die sich insbesondere mit breiten gesellschaftlichen Instanzen der Relationsstruktur in dieser Relationsstruktur einschreiben.

In der Relationsstruktur mit Kernsequenz Repräsentation werden ebenfalls die Eintrittsbedingungen in Zirkulationen gestärkt, selbst wenn sie zur Unterstützung nicht primär von Herkunfts-, sondern von Affiliationskollektiven der Akteure beitragen. Dieses Muster der sozialen Ungleichheit kann wie folgt zusammengefasst werden: Wer, was, wie, wieso, wann und wo vertreten wird, bestimmt bis wohin man gehen kann. Die Verbreitung von diesem Ungleichheitsmuster unterstützt die Zirkulationen von Akteuren der zweiten Kategorie, die sich maßgeblich mit gesellschaftlichen Instanzen der Sequenzen in dieser Relationsstruktur einschreiben.

Die Relationsstruktur mit Kernsequenz Materialität zeigt im Vergleich zu den obigen zwei anderen Relationsstrukturen einen Verlust an Bedeutung von Kollektiven für die Zirkulation der Akteure. Für sie geht es um die selbständige Arbeit an Mediationen zur eigenen Verselbständigung und zur eigenen Verwirklichung. Die Kollektive begleiten die Akteure entsprechend lediglich vorübergehend, und sie müssen idealerweise zu einer wachsenden Anzahl anderer Akteure führen, die die Materialisierungskraft von Einzelakteuren bewerten und belohnen. Ein solches Muster der sozialen Ungleichheit verbreitet insbesondere die Zirkulation von Akteuren der dritten Kategorie, die sich bevorzugt mit gesellschaftlichen Instanzen der Teilsequenzen in dieser Relationsstruktur einschreiben.

Schließlich zeigt die Relationsstruktur mit Kernsequenz Attraktivität die vorherrschende Rolle vom Wechsel der Zirkulationen zur Strukturierung von sozialen Ungleichheiten. Sie setzt die fortdauernde Erneuerung von individualisierenden Merkmalen zur Stärkung der eigenen Attraktivität gegenüber der breiten Masse der Bevölkerung bzw. der Akteure voraus. Dieses Muster der sozialen Ungleichheiten wird von der Zirkulation der Akteure der vierten Kategorie und von der Arbeit der gesellschaftlichen Instanzen der Umverteilung von Zirkulationswegen und Zirkulationsmöglichkeiten am besten verbreitet. Es entspricht Ungleichheiten vor dem Zirkulationswechsel angefangen mit dem Wechsel von Mediationen, relationalen Ereignissen, Kollektiven und schließlich Sequenzen und Relationsstrukturen.

Diese vier Muster bezeichnen nicht nur vorherrschende Muster sozialer Ungleichheiten in Unterstützung der Kernsequenz der jeweiligen Relatonsstrukturen. Sie bezeichnen auch Muster von sozialen Ungleichheiten in den entsprechenden Sequenzen innerhalb von Relationsstrukturen. Dies erklärt sich damit, dass die Relationsstrukturen von den gleichen Sequenzen strukturiert sind, selbst wenn sich die Anordnung dieser Sequenzen je nach Relationsstruktur unterscheidet. Wir finden deshalb in einer Relationsstruktur immer vier Muster sozialer Ungleichheiten vor, die eine jede Relationsstruktur hinsichtlich der darin zum Tragen kommenden sozialen Ungleichheitsmuster unterschiedlich stark bestimmen, wenngleich das mit der Kernsequenz einer Relationsstruktur assozierte und in der Kernsequenz einer Relationsstruktur gegebene Muster sozialer Ungleichheit in einer Relationsstruktur vorherrscht. Eine solche Vorherrschaft des in der Kernsequenz einer Relationsstruktur gegebenen soziale Ungleichheitsmusters lässt sich jedoch auch insofern unterwandern und temporär durch ein anderes ersetzen, als die anderen Sequenzen von einer Relationsstruktur wie Einfallstore für den Einfluss bzw. für die Satellisierung von anderen Relationsstruktur fungieren, wodurch wiederum das Ungleichheitsmuster der Kernsequenz von dem in einer anderen Sequenz unterstützten Muster in derselben Relationsstruktur zeitweise abgeschwächt oder gar unterminiert werden kann, wenn diese andere Sequenz von einer anderen Relationsstruktur satellisiert wird.

Daraus ergibt sich eine allgemeine Beschreibung sozialer Ungleichheit, wie sie vom Standpunkt der Theorie der Relation aus zu verstehen ist: Das vorherrschende Muster von sozialer Ungleichheit in der Kernsequenz einer Relationsstruktur kann durch die Verbreitung anderer Muster sozialer Ungleichheiten in den anderen Sequenzen dieser Relationsstruktur je nach der Stärke der Satellisierung bzw. der Stärke der Einflussnahme durch die anderen Relationsstrukturen destabilisiert werden. Um vorherrschend zu bleiben, muss sich dann das Muster der Kernsequenz in einer Relationsstruktur durchsetzen, was die Verbreitung der Relationsstruktur auf die anderen Relationsstrukturen voraussetzt (siehe auch ebd., 384-400).

Mit dieser Auffassung von sozialer Ungleicheit ist die Theorie der Relation in der Lage, nicht nur die Reichweite bzw. die Grenzen der Verbreitung von spezifischen Mustern sozialer Ungleiheit zu problematisieren, indem sie vertikale oder horizontale soziale Ungleichheiten innerhalb von Sequenzen zwischen Akteurkategorien und zwischen den unterschiedlichen Arten von gesellschaftlichen Instanzen adressieren kann. Sie kann ebenso sehr Querschnittsungleichheiten erfassen, indem sie einerseits in Rechnung stellt, dass soziale Ungleichheit viele Gesichter hat, und eingedenk dieser Tatsache zu untersuchen imstande ist, wie soziale Ungleichheiten in einer Sequenz von einer Relationsstruktur sozialen Ungleichheiten in den anderen Sequenzen derselben Relationsstruktur und in anderen Relationsstrukturen strukturieren und beeinflussen können. In dieser Hinsicht ist soziale Ungleichheit ein Beispiel von Makrophenomänen, die alle Ebenen von Relationsstruktur betreffen und deshalb auch unter Berücksichtigung dieser Ebenen der Analyse zugeführt werden können.

Dies ist der Grund, weshalb in diesem Kapitel die Auffassung von sozialen Ungleichheiten zuerst ein Rückblick auf das Grundgerüst der Theorie der Relations erfordert, bevor wir dann zur Bedeutung von Sequenzen als Register von sozialen Merkmalen und Determinanten von Eintritts-, Austritts- und Übergangsbedingungen in Zirkulationen kommen. Anschließend besprechen wir die vier vorherrschenden Muster der sozialen Ungleichheiten in den entsprechenden Relationsstrukturen, und wir zeigen an einem Beispiel, wie sie durch den wechselwirkenden Einfluss von Relationsstrukturen aufeinander innerhalb von Relationsstrukturen stabilisiert bzw. destabilisiert werden. In diesem Kapitel ist unser Ziel nicht, die komplexen Formen, die sozialen Ungleicheiten haben, erschöpfend zu erörtern. Vielmehr handelt es sich darum, eine Einführung in die Frage der sozialen Ungleichheit anzubieten, um zu veranschaulichen, wie soziale Ungleichheiten durch Relation in Zirkulation problematisiert werden.

## Soziale Ungleichheiten im Grundgerüst der Theorie der Relation

Die Theorie der Relation versteht soziale Ungleichheiten auf der Grundlage der Anordnung von Sequenzen in jeder Relationsstruktur. Diese Anordnung der Sequenzen gewährleistet, dass einerseits die allgemeine Zirkulation und damit das Hauptmerkmal der jeweiligen Relationsstrukturen, das die Kernsequenz dieser Relationsstruktur symbolisiert, bewahrt wird. Andererseits trägt sie zur besonderen Auffassung der Reziprozität bei, die jede Relationsstruktur kennzeichnet und versucht, auf die anderen Relationsstrukturen zu verbreiten. Die Frage der sozialen Ungleichheiten, wie sie die Theorie der Relation aufgreift, ist also tief im Grundgerüst der Relationsstrukturen verwurzelt, wovon wir in diesem Band einige der wichtigsten Merkmale anhand von Beispielen illustriert haben. Mit diesem Exkurs weichen wir von der bisherigen Darstellung ab, weil wir mehr Raum für die analytische Beschreibung von sozialen Ungleichheit brauchen, selbst wenn wir für den komplexeren Fall von Querschnittsungleichheiten auf ein Beispiel aus der Bildungssoziologie zurückgreifen werden, das der besseren Veranschaulichung dieser Frage der sozialen Ungleichheiten durch Relation in Zirkulation dient.

Fangen wir erst einmal mit der folgenden grundlegenden Feststellung an, die wir in unserer Einleitung dargestellt und kommentiert haben: Soziale Ungleichheiten sind zum Ersten und wie viele andere sozialen Makrophänomene (wie etwa Konflikte, Ungerechtigkeiten, Stigmatisierungen, Diskriminierungen) das Ergebnis von Abweichungen in dem Sinne, dass die Relationsstrukturen Abweichungen von einer _idealen_ Relation sind. Anders gesagt, gäbe es in einer idealen Relation _ceteris paribus_ keine sozialen Ungleichheiten. Akteure und Gruppen wären alle gleich. Zum Zweiten und anschließend an diese erste Anmerkung sind soziale Ungleichheiten strukturierende Phänomene für Relationsstrukturen und für die Zirkulationen in Relationsstrukturen. Soziale Ungleichheiten sind nicht nur das Ergebnis der Ausdifferenzierung von Akteuren, von Akteurkategorien und von Vermittlungsstrukturen der entsprechenden gesellschaftlichen Instanzen in den jeweiligen Relationsstrukturen. Sie bilden auch die Ausgangslage für eine solche Ausdifferenzierung, die in der Ausdifferenzierung von Akten der doppelten Einschreibung von Akteuren und Instanzen in die allgemeine Zirkulation von Relationsstrukturen widerspiegelt wird. Daraus ergeben sich die Unterscheidungen zwischen den verschiedenen Zirkulationswegen und Zirkulationsmöglichkeiten, die aus diesen Zirkulationswegen generiert werden. Dies macht die Relationalität von sozialen Ungleichheiten aus, die in der Theorie der Relation vom Primat der Zirkulation wie folgt perspektiviert wird.

In jeder Relationsstruktur gibt es eine Anordnung von Sequenzen, die die allgemeine Zirkulation in einer Relationsstruktur bestimmt. Nehmen wir etwa die Relationsstruktur mit Kernsequenz Investition. Die allgemeine Zirkulation startet in der Kernsequenz Investition von dieser Relationsstruktur. Sie geht zur nächsten Sequenz der Repräsentation dieser Investition. Sie entwickelt sich dann weiter zur Sequenz der Materialisierung dieser Repräsentation. Schließlich kommt sie zur Sequenz der Attraktivität von einer solchen Materialisierung, die diese Zirkulation wieder zur Kernsequenz Investition bringt. Dies ist eine analytische oder genauer eine formale Beschreibung der allgemeinen Zirkulation in dieser Relationsstruktur. Aus den Beispielen in den anderen Kapiteln haben wir jedoch gelernt, dass eine solche Zirkulation nicht automatisch zirkuliert, und dies hat zwei Gründe.

Wenn es keine Repräsentation der Investition in die Arbeit an der Verkettung von relationalen Ereignissen gibt, dann wird die allgemeine Zirkulation, die diese Relationsstruktur bezeichnet, beeinträchtigt. Im konkreten Wortlaut würde ein solcher Fall bedeuten, dass die Mobilisation von einem Kollektiv im Laufe dieser Arbeit nur teilweise oder gar nicht geglückt ist. Im Fall von einer schwachen Mobilisation oder wenn kein Kollektiv entsteht, gibt es zudem Schwierigkeiten bei der Repräsentation der geleisteten Arbeit durch Vertreter der (schwach) mobilisierten Akteure. Dies ist der erste Grund für eine gefährdete allgemeine Zirkulation in dieser Relationsstruktur.

Der zweite Grund für die Gefährdung der allgemeinen Zirkulation ist gegeben, wenn nicht etwa der Aufbau der nächsten Sequenz nach der Kernsequenz Investition in dieser Relationsstruktur -- die Sequenz Repräsentation -- geschwächt oder gestört wird, sondern wenn solche Schwächungen oder Störungen in der Sequenz davor bzw. vor der Kernsequenz Investition -- also hier in der Sequenz Attraktivität -- auftauchen. Wenn die Attraktivität für die Kernsequenz Investition in dieser Relationsstruktur nicht unterstützt wird -- Akteure und Kollektiven finden die Arbeit an relationalen Ereignissen wenig attraktiv, wenn überhaupt --, dann gibt es nur wenige Akteure, die weiter in die Arbeit an der Verkettung von relationalen Ereignissen investieren bzw. die aus der Sequenz Attraktivität in die Kernsequenz Investition zirkulieren. Auch in diesem Fall wird die allgemeine Zirkulation in dieser Relationsstruktur gefährdet.

Wie man dieser formalen Beschreibung entnehmen kann, ist es für die allgemeine Zirkulation in Relationsstrukturen wichtig, dass sowohl die nächste Sequenz nach der jeweiligen Kernsequenzen als auch die letzte Sequenz vor den jeweiligen Kernsequenzen gewährleistet bzw. entwickelt wird, damit die allgemeine Zirkulation in den jeweiligen Relationsstrukturen überhaupt zirkuliert. Wenn diese Bedingung nicht erfüllt ist, dann kann die verbleibende Sequenz  -- die Schwachpunktssequenz von einer Relationsstruktur, die deshalb so genannt wird, weil sie am meisten von der Entwicklung der allgemeinen Zirkulation in den anderen Sequenzen von einer Relationssttruktur abhängig ist  -- nicht einbezogen werden. Dies kann zur Schrumpfung von Relationsstrukturen führen, die umso mehr an Bedeutung für die Akteure, Kollektive und Instanzen verlieren, als sie kaum noch Zirkulationswege und Zirkulationsmöglichkeiten zur Unterstützung von Positionen durch Relation anbieten. Die Gewährleistung von der Folgesequenz einerseits und der letzten Sequenz um die Kernsequenz von einer Relationsstruktur zum Einbezug der Schwachpunktssequenz ist eine Querschnittsverbindung zwischen Sequenzen der jeweiligen Relationsstruktur, die wir aufgrund ihrer Form _Schmetterlingspfad_ nennen (vgl. ebd., 86ff.). Dieser Schmetterlingspfad bereitet die Grundlage zur Dimensionierung der sozialen Ungleichheiten nach dem Primat der Zirkulation vor. Wir halten an dieser Stelle kurz inne, um an Distanz zu dem zu gewinnen, was wir bisher beschrieben haben.

Wir sagen, dass sich soziale Ungleichheiten aus der Abweichung von einer Ordnung von Determinanten ergeben, die die Zusammenstellung von Sequenzen in einer Relationsstruktur darstellen. Dies werden wir in der nächsten Sektion vertiefen, in der wir von Sequenzen als Registern von sozialen Merkmalen sprechen. Eine solche Aussage bedeutet, dass sich die Theorie der Relation grundsätzlich nicht von anderen soziologischen Theorien hinsichtlich ihrer grundlegenden Auffassung von sozialer Ungleichheit unterscheidet. Wie wir schon im Vergleich zu der Soziologie von Pierre Bourdieu gezeigt haben (ebd.), setzen soziale Ungleichheiten voraus, dass Akteure soziale Merkmale beziehen und so priorisieren und zusammenstellen, dass sie eine vorherrschende Ordnung von solchen Merkmalen, wie sie in der Gesellschaft verbreitet sind, unterstützen. Entsprechend werden Akteure sozial ungleich, wenn sie diese Merkmale nicht oder weniger umfangreich beziehen und sie nicht im Sinne der Unterstützung der vorherrschenden Ordnung solcher Merkmalen priorisieren und zusammenstellen können. Der Punkt, an dem sich nun die Theorie der Relation von anderen Theorieansätzen unterscheidet, betrifft die Auffassung von dieser vorherrschenden Ordnung der sozialen Merkmale. Sie ist weder vorgegeben noch konstant, wie sie in der Vorstellung Bourdieus von einem allgemeinen und eindimensionalen Machtverhältnis, das die ganze Gesellschaft umspannen würde, geben ist [@Bourdieu2012a; siehe auch @Nassehi2004; @Kieserling2008; für eine kritische Betrachtung eines solchen Ansatzes über die Soziologie Bourdieus hinaus, vgl. @Kaelble2017], oder bei den Ansätzen der Ressourcenknappheit stets mitschwingt [vgl. etwa @Roessel2005, @Weingartner2019; vgl. auch @Hradil2016; @Mau2015]. Vielmehr variiert sie je nachdem, wie eine Relationsstruktur ihre Kernsequenz durchsetzt bzw. wie stark oder schwach sie von anderen Relationsstrukturen beeinflusst, d. h. satellisiert wird. Mit diesem Ansatz, der sich unmittelbar aus dem Primat der Zirkulation ergibt, lässt sich verstehen, dass je nach Verbreitung oder Schrumpfung von einer Relationsstruktur die vorherrschende Ordnung der sozialen Merkmale entsprechend der Veränderung der allgemeinen Zirkulation in dieser Relationsstruktur aufgrund der Durchsetzung anderer Sequenzen derselben Relationsstruktur verändert wird. Dies zieht eine Veränderung sozialer Ungleichheit bzw. des dominanten Ungleichheitsmusters innerhalb und zwischen Akteurkategorien in den einzelnen Sequenzen bei Veränderung des Schmetterlingspfades in einer Relationsstruktur nach sich, was wiederum Folgen sowohl für die horizontale Ungleicheit als auch für Querschnittsungleichheiten zeitigt. Konkret bedeutet dies, dass je nach Variation des Schmetterlingspfads in einer Relationsstruktur Akteure und Akteurkategorien, die im Normalfall bzw. angesichts des dominanten Ungleichheitsmusters Vorteile für sich in Anspruch nehmen konnten, diese Vorteile verlieren und aufgrund von temporär wirksamen anderen Ungleichheitsmusters benachteiligt werden. Umgekehrt können in dieser Situation Akteuren, die von dem im der Kernsequenz einer Relationsstruktur gegebenen Ungleichheitsmusters einst benachteiligt waren, durch eine solche Veränderung Vorteile zufallen.

Damit wird nicht nur gesagt, dass soziale Ungleichheiten relational in dem Sinne zu denken sind, als sie in Bezug auf die Stärkung bzw. Schwächung von Relationsstrukturen und ihren Sequenzen rekonstruiert werden müssen [zum vergleichbaren Verständnis von sozialen Ungleichheiten nach einem Mehrebenenansatz, vgl. @Schwinn2007, @Schwinn2019; ebenfalls @Schimank2015]. Es wird auch gesagt, dass je nach Variation des Schmetterlingspfades in einer Relationsstruktur spezifische Formen der sozialen Ungleichheit durchgesetzt werden, die von spezifischen Akteurkategorien in spezifischen Tätigkeitsbereichen in der Gesellschaft verbreitet werden. Dies hängt jedoch wiederum davon ab, ob die Akteure solcher Akteurkategorien und Bereiche zur Einschreibung mit Instanzen der Relationsstruktur kommen, die in einer Relationsstruktur keine vergleichbare Wichtigkeit haben. Wenn wir uns etwa die Relationsstruktur mit Kernsequenz Investition ansehen, in der Instanzen der Relationsstruktur mehr Macht bei der Verbreitung der Reziprozität und der entsprechenden Legitimation von Akteuren als Instanzen der (Teil)Sequenzen haben, dann ist es selbstverständlich, dass eine Veränderung des Schmetterlingspfades in dieser Relationsstruktur einerseits zwar die Macht der Instanzen der (Teil)Sequenzen stärkt. Aber andererseits fördern diese Instanzen die Akteurkategorien in (Teil)Sequenzen, was bedeutet, dass das neue Muster sozialer Ungleichheit, das sie durchzusetzen versuchen, weniger breit angelegt ist und sich entsprechend mühsamer durchsetzen wird. Es gibt deshalb eine Elastizität von sozialen Ungleichheiten je nach der Art gesellschaftlicher Instanz, die durch die Variation der Muster sozialer Ungleichheit unterstützt wird, und die folgendermaßen zusammengefasst werden kann: Wenn wir uns von der Kernsequenz entfernen, verändert sich das Muster der sozialen Ungleichheit, aber es setzt sich immer mühsamer durch. Dies bedeutet für die Akteurkategorien, die von solchen Veränderungen unmittelbar profitieren würden, dass sie  weiterhin mehr Zeit zur Entwicklung ihrer sozialen Arbeit aufbringen müssen, um sich mit den gesellschaftlichen Instanzen einzuschreiben und von einer solchen Veränderung tatsächlich profitieren zu können [vgl. das Beispiel der Finanzkrise 2008 in @Beyer2018; vgl. @Schwinn2015 besonders zu unstrukturierten sozialen Ungleichheiten]. Oder um es anders zu formulieren: Solche Akteurkategorien, die sich durch die Veränderung des Musters sozialer Ungleichheiten besser durchsetzen können, tun dies jedoch in einem geschwächten Zustand der Relationsstruktur, was ihren sozialen Aufstieg unvermeidlich einschränkt.

Bevor wir nun zur Beschreibung der Schmetterlingspfade in den Kernsequenzen der vier Relationsstrukturen kommen, müssen wir uns mit den Sequenzen außerhalb ihrer strukturellen und formalen Eigenschaften beschäftigen. Diese Sequenzen gelten nicht nur als Stufen der allgemeinen Zirkulation in den jeweiligen Relationsstrukturen, sondern auch als Register von sozialen Merkmalen, die solche Sequenzen in Zirkulation und entsprechend zu Akteuren und Kollektiven bringen.

## Sequenzen als Register von sozialen Merkmalen

Es liegt in der sequentiellen Ordnung von Relationsstrukturen, dass Unterscheidungen -- wenn auch nicht unbedingt alle davon [vgl. @Hirschauer2014] -- zu Ungleichheiten bzw. zu ungleichen Unterscheidungen in Zirkulation entwickelt werden können. Sequenzen von Relationsstrukturen werden vom Wechsel der Positionen durch Relation in Zirkulation gebildet. Ferner werden sie von der tatsächlichen Mobilität von Akteuren, wie sie Positionen beziehen und verlassen, strukturiert. Der Schmetterlingspfad von Sequenzen stellt die Zusammenstellung von Bedingungen dar, die eine solche Mobilität bestimmen, wobei der Schmetterlingspfad, der in einer Relationsstruktur das Hauptmerkmal dieser Relationsstruktur und ihrer Kernsequenz unterstützt, die Bedingungen zusammenstellt, die dieses Hauptmerkmal und diese Kernsequenz bestimmen.

Am Beispiel der Relationsstruktur mit Kernsequenz Investition haben wir gesehen, dass die Repräsentation die erste Anlaufstation der allgemeinen Zirkulation in dieser Relationsstruktur darstellt, während die Attraktivität die letzte Anlaufstation von dieser Zirkulation bildet. Der Übergang zur weiteren Zirkulation bestimmt die Sequenz an der Schnittstelle zwischen den Sequenzen Repräsentation und Attraktivität, und diese Intersektion bildet die Sequenz bzw. die Schwachpunktsequenz Materialität. Es gibt also Eintrittsbedingungen in Zirkulationen, Austrittbedingungen aus Zirkulationen und Bedingungen zum Übergang von einer Zirkulation zur weiteren Zirkulation an der Intersektion der Eintritts- und Austrittsbedingungen. Diese allgemeine Formulierung beschreibt die Art und Weise, wie die Theorie der Relation die sozialen Ungleichheiten als dreifache soziale Ungleichheit auf den Ebenen von Eintritts-, Austritts- und Übergangsbedingungen in Bezug auf Zirkulationen problematisiert, die stattgefunden haben, stattfinden und stattfinden werden. Diese Auffassung von sozialer Ungleicheit stellt eine allgemeine bzw. multivariierende Grundlage bereit [vgl. @Meyer2017], die eine einleitende Einsicht in die Komplexität der Frage der sozialen Ungleichheit widergibt. Um eine solche Einsicht zu vertiefen, muss sie in Bezug auf Akteurkategorien und Instanzen bzw. in Relation zu Einschreibungsakten in Sequenzen und Relationsstrukturen gebracht werden. Bevor wir jedoch auf diesen Punkt systematisch eingehen können, ist es notwendig, in einem ersten Schritt die Bedeutung der Sequenzen als Register von sozialen Merkmalen zur Bestimmung von sozialer Ungleichheit näher auszubuchstabieren.

Mit der Sequenz Investition in den vier Relationsstrukturen befinden wir uns im Register der Arbeit an relationalen Ereignissen mit anderen Akteuren. Dieses Register verweist ebenso auf die Tätigkeiten von Akteuren an relationalen Ereignissen, an der Arbeit an relationalen Phänomenen ausgehend von den verschiedenen Formen der Ausübung von Soziabilität, wie auf Tätigkeiten von Akteuren zur Gewandtheit, zur Bildung von Freundschaften, von Netzwerken, von Allianzen, von Entbindungen, Entfernungen, von passiven Haltungen, (Zu)Rückhaltungen, Reaktionen und weiteren Phänomenen dieser Art, die die Entstehung, Entwicklung und (Ab)Schließung oder Auflösung von Ketten zwischen relationalen Ereignissen betreffen. In diesem Register finden wir wieder, was in den Sozialwissenschaften mit Begriffen wie Beziehungen, Interaktionen beschrieben und ferner in Termini wie Sozialkapital oder Netzwerk zum Ausdruck kommt [vgl. @Bourdieu1983; @Coleman1988; @Putnam1993; vgl. ebenfalls @Rose2013; @Schultze2022].

Mit der Sequenz Repräsentation befinden wir uns in allen Relationsstrukturen im Register von Kollektiven und deren Vertretern bzw. vom Aufbau, Ausbau und Abbau von Gruppen von Akteuren, die durch ihre Mitglieder vertreten werden. Diese Kollektive und ihre Vertreter können Herkunftskollektive (etwa die Familie), Affiliationskollektive (etwa Peer-Gruppen) oder Begleitungskollektive (etwa Gemeinschaften oder Förderer wie Stiftungen, Sponsoren, Mäzene) sein. Ihre Wichtigkeit für die Akteure besteht sowohl in der Anwesenheit dieser Kollektive als auch in ihrer Abwesenheit wie etwa im Fall von alten Dynastien oder alten Familien [vgl. etwa @Bourdieu1992; siehe auch @Crosnoe2004; @Gerard2004; @Ryabov2009]. Diese Merkmale bezeichnen die An- oder die Zugehörigkeiten von Akteuren zu Kollektiven.

Die Sequenz Materialität beschreibt in den vier Relationsstrukturen individualisierende Merkmale, die von körperlichen zu räumlichen Merkmalen reichen und auch Besitzmerkmale von Akteuren (wie etwa Eigentum) mit einschließen. Darunter findet man die verschiedenen Merkmale, die vonseiten der Familienforschung, der Frauen- und Diversitätsforschung, der Soziologie des Außenseitertums, der Intersektionalität u. v. a. m. hervorgehoben haben [@Cho2013], wie etwa das Geschlecht, die Hautfarbe, die kulturelle Identität, die soziogeographischen Ansiedelungsmerkmale wie die Wohnsituation oder der Wohnort. Diese Merkmale gehören zur Behauptung von Akteuren als besondere bzw. singuläre Akteure [vgl. @Reckwitz2017].

Die Sequenz Attraktivität verweist in allen Relationsstrukturen auf Mediationen im Sinne von menschlichen und nicht menschlichen Mediationen. Unter diesen nicht menschlichen Mediationen gibt es nicht nur materielle oder symbolische Gegenstände (etwa schulische und hochschulische Titel, Verdienstsymbole, Abzeichen), sondern auch Methoden, Techniken und Praktiken, Routinen und institutionalisierte Verhaltenskodexe, Umgangsformen und weitere unterschiedliche Formen von _modi operandi_ [vgl. exemplarisch @Bourdieu2009]. All diese menschlichen wie nicht menschlichen Mediationen dienen den Akteuren als Teile einer Ausrüstung zur Entwicklung von Strategien und Taktiken, die sie zur Gestaltung ihres Alltages und entsprechend im Umgang mit ihrer Zirklation im Alltag einsetzen [vgl. @Decerteau1988].

Weil jeder Schmetterlingspfad diese Sequenzen in einer eigenen Art und Weise miteinander verbindet, stehen die sozialen, mit den Sequenzen assoziierten Merkmale immer in einem bestimmten Verhältnis zueinander. Etwa der Erwerb von oder das Streben nach einem Hochschulabschluss (Attraktivitätsregister) versteht sich immer an der Schnittstelle zu den drei anderen Registern von einer Relationsstruktur. Entsprechend erfordert und setzt der Erwerb eines Hochschulabschlusses immer eine Einstellung zur Arbeit an relationalen Ereignissen mit anderen Akteuren (Investition), den starken oder schwachen, manifesten oder impliziten Bezug auf Kollektive (Repräsentation) und individuelle Merkmale (Materialität) voraus, die die Einschreibung mit gesellschaftlichen Instanzen von Relationsstrukturen bestimmen.

An eben jenem Punkt unterscheidet sich die Theorie der Relation nicht von den üblichen soziologischen und _a fortiori_ relationalen Ansätzen, die soziale Ungleichheit als relationales Muster bzw. als Verbindung von Kontexten sozialer Merkmale verstehen [vgl. beispielhaft dazu @Tilly1998]. Ein solches Muster wirkt als ein Bestimmungszusammenhang und gleichzeitig als ein Sinnzusammenhang der Akteure und Gruppen zur Verbreitung ihrer Zirkulation qua Stabilisierung ihrer Erwartungen. Die Frage jedoch, die die Theorie der Relation aufwirft und stets stellt, betrifft den Referenzpunkt dieser Verbindung zwischen sozialen Bestimmungsmerkmalen. Oder anders formuliert: Anhand welchen Verhältnisses sollen solche Kontexteffekte von sozialen Bestimmungsmerkmalen interpretiert werden? Die Antwort auf diese Frage lautet: Auf Basis des Schmetterlingspfades in einer Relationsstruktur, der sich in dieser Relationsstruktur durchsetzt bzw. der den Referenzrahmen für die Entwicklung der allgemeinen Zirkulation in dieser Relationsstruktur bildet. Die Schmetterlingspfade stellen zudem keine Ausnahme von dem Grundsatz der Relationsstrukturen als Abweichungen von einer idealen Relation dar. Im Gegenteil, denn auch die Schmetterlingspfade weichen voneinander ab.

## Abweichungen vom Schmetterlingspfad

Als wir in unserer Einleitung von den Sequenzen und den Relationsstrukturen sprachen, haben wir hervorgehoben, dass sie als Abweichungen entstehen und entwickelt werden. Die Sequenzen weichen also ebenso voneinander ab, wie die Relationsstrukturen voneinander abweichen, was wiederum sowohl die Sequenzen als Sequenzen als auch die Relationsstrukturen als Relationsstrukturen strukturiert. Derselbe Ansatz gilt auch für die Schmetterlingspfade und zwar ebenso aus strukturellen wie morphologischen bzw. zirkulatorischen Gründen.

Der strukturelle Grund betrifft den Kern des Abweichungsansatzes in der Theorie der Relation. Wenn es also weder eine _ideale_ Relation noch eine _ideale_ Sequenz, d. h. weder ein ideales Verhältnis noch eine ideale Art der Tätigkeitsentwicklung gibt, sondern Relationsstrukturen und Sequenzen vielmehr Abweichungen von einer solchen idealen Relation und Sequenz darstellen, dann gibt es folglich auch nicht nur einen, sondern mehrere Schmetterlingspfade und zwar je nachdem, welche Sequenz wir in einer Relationsstruktur berücksichtigen. Dies bedeutet, dass die Kernsequenz von einer Relationsstruktur ihren Status als Kernsequenz verlieren kann, wenn diese Relationsstruktur durch die Satellisierungen von anderen Relationsstrukturen destabilisiert wird. In der Folge einer solchen Einflussnahme wird dann eine andere Sequenz zur Kernsequenz in der satellisierten Relationsstruktur, die diejenige ist, die am stärksten für den Einfluss durch eine andere Relationsstruktur offen ist. Ein solches Szenario entspricht einer Schwächung der Relationsstruktur, weil im Falle einer Destabilisierung ihrer allgemeinen Zirkulation diese Zirkulation zwar weiter zirkuliert, diese Zirkulation aber gleichsam nicht mehr in Unterstützung des Hauptmerkmals dieser Relationsstruktur zirkuliert, sondern in Unterstützung des Hauptmerkmals der anderen, satellisierenden Relationsstruktur. Die Destabilisierung von einer Relationsstruktur durch die Satellisierung von anderen Relationsstrukturen führt damit unweigerlich zur variablen Elastizität von sozialen Ungleichheiten, wie wir sie oben bereits hervorgehoben haben. Nehmen wir ein Beispiel.

Eine stärkere politische Steuerung der Wissenschaft -- beispielsweise mit dem Ziel, dass die Wissenschaft mehr an praxisnahen Lösungen in Unterstützung der regionalen Wirtschaft arbeitet (Verbreitung der Sequenz Repräsentation in der Relationsstruktur mit Kernsequenz Investition; vgl. unser Beispiel in @monoPapilloudSchultze2023) -- kann zur Destabilisierung der wissenschaftlichen Forschung etwa in Form von Einschränkungen der Forschungsfreiheit mit Folgen für die Orientierung der Forschungstätigkeiten, für die Ergebnisse aus solchen Forschungstätigkeiten (Verdichtung statt Verbreitung der existierenden Forschungen), für das Profil der wissenschaftlichen Bereiche, für die Ausbildung von jungen Wissenschaftlern und Studierenden usw. führen. Die allgemeine Zirkulation in der Forschung würde zwar weiter aber dafür auch stärker in Unterstützung einer politischen Agenda zirkulieren, was zur Abweichung vom Schmetterlingspfad führt, wie er regulär in der Kernsequenz Investition der entsprechenden Relationsstruktur gegeben ist und entwickelt wird. Die Gewichtung von sozialen Merkmalen in ihrer Verbindung zueinander, die diese Zirkulation bestimmen, ändert sich durch den Einfluss der satellisierenden Relationsstruktur, die den Schmetterlingspfad ihrer Kernsequenz -- in unserem Beispiel die Kernsequenz der Repräsentation -- der satellisierten Relationsstruktur aufdrängt. Demzufolge gewinnt die Repräsentation und die Arbeit an der Attraktivität dieser Repräsentation in der Wissenschaft ebenso an Bedeutung wie die Akteure und Instanzen, die im Dienst der Repräsentation der Wissenschaft in der Gesellschaft arbeiten. Die Forscher und Forscherinnen gehen in einem solchen Falle mehr auf Tagungen, Kongresse, Messen und die Vulgarisierung von Wissen nimmt zu. Die Presse- und Marketingsabteilungen von wissenschaftlichen Instanzen spielen eine bedeutsamere Rolle zur Inszenierung wissenschaftlicher Instanzen in der Öffentlichkeit. Die Ministerien und die staatlichen Förderer der wissenschaftlichen Forschung gewinnen an Bedeutung im Hinblick auf die Profilierung von Forschungstätigkeiten und von Wissen, und durch ihre Förderungsprogramme tragen sie dazu bei, das erklärte und genuin politisch motivierte Ziel einer Verankerung von wissenschaftlichen Instanzen in der regionalen Wirtschaftslandschaft zu stärken.

Dieses Beispiel legt nah, dass es so viele Schmetterlingspfade bzw. Verbindungen zwischen sozialen Bestimmungsmerkmalen gibt, wie es Sequenzen in Relationsstrukturen gibt. Kehren wir daher zum bisher erwähnten Beispiel der Relationsstruktur mit Kernsequenz Investition zurück. Der Schmetterlingspfad, der das Hauptmerkmal dieser Relationsstruktur kennzeichnet und in der Kernsequenz dieser Relationsstruktur gebildet wird, stellt eine Variante der Zusammenstellung von sozialen Merkmalen dar, aus denen sich ein Muster sozialer Ungleichheiten in der Kernsequenz Investition ergibt. Diese Relationsstruktur besteht jedoch nicht nur aus der Kernsequenz Investition. Sie bezieht vielmehr die drei anderen Sequenzen mit ein, die die Stufen der allgemeinen Zirkulation in dieser Relationsstruktur abbilden. Es gibt also neben dem Schmetterlingspfad, der in Unterstützung der Kernsequenz Investition entwickelt wird, weitere Schmetterlingspfade, die die Besonderheit der Verbindung zwischen sozialen Bestimmungsmerkmalen in Unterstützung der jeweiligen anderen drei Sequenzen ausmachen. Deshalb haben wir je nach dem Einfluss von anderen Relationsstrukturen auf die Relationsstruktur mit Kernsequenz Investition und zwar neben dem Schmetterlingspfad in Unterstützung der Sequenz Investition gleichsam einen Schmetterlingspfad in Unterstützung der Sequenz Repräsentation, einen weiteren Schmetterlingspfad in Unterstützung der Sequenz Materialität und einen letzten Schmetterlingspfad in Unterstützung der Sequenz Attraktivität. Diese drei Schmetterlingspfade weichen vom Schmetterlingspfad der Kernsequenz Investition ab, der seinerseits ebenfalls von einer ideale Investition in die soziale Arbeit mit anderen Akteuren an der Verkettung von relationalen Ereignissen abweicht.

Daraus ergibt sich, dass eine Relationsstruktur strukturell bzw. aufgrund ihrer Sequenzen immer eine Konkurrenz zwischen unterschiedlichen Mustern von sozialen Ungleichheiten bzw. zwischen Verbindungen von sozialen Bestimmungsmerkmalen abbildet, die sich je nachdem durchsetzen, wie stark oder schwach eine Relationsstruktur von den anderen Relationsstrukturen satellisiert wird [vgl. Bourdieus Umformulierung des Klassenkampfes als "lutte des classements", @Bourdieu1980, 233-244; ebenfalls @Bourdieu1966]. Diese Verbindungen sind das, was in der Theorie der Relation als (konkurrierende) Muster sozialer Ungleichheiten bezeichnet wird und die die Sequenzen stratifizieren. Oder um diese Aussage vom Standpunkt der einzelnen Sequenzen umzuformulieren: Aufgrund von ihrer Stratifikation in Akteurkategorien und Arten von gesellschaftlichen Instanzen bilden die Sequenzen von einer Relationsstruktur konkurrierende Arrangements von sozialen Bestimmungsmerkmalen, deren Zusammenstellung der Schmetterlingspfad der jeweiligen Sequenzen wiedergibt. Dort liegt der zirkulatorische Grund, weshalb Abweichungen von Schmetterlingspfaden entstehen. Die Schmetterlingspfade stehen stets in einem wechselseitigen Spannungsverhältnis zueinander und werden je nachdem gestärkt oder geschwächt bzw. gestört, wie Zirkulationen innerhalb und zwischen Relationsstrukturen gestärkt oder geschwächt bzw. gestört werden. Dies führt zu drei allgemeinen Folgen in Bezug auf die Art und Weise, wie die Theorie der Relation soziale Ungleichheit versteht.

### Folgen

Die erste Folge ergibt sich unmittelbar aus dem Abweichungsansatz der Theorie der Relation: Zirkulationen von Akteuren weichen von einem vorherrschenden Schmetterlingspfad in einer Relationsstruktur -- wenn auch mehr oder weniger und variierend bzw. gestaffelt nach Akteurkategorien einerseits und dem Netzwerk an gesellschaftlichen Instanzen andererseits, dafür aber immer unvermeidlich -- ab. Akteure bringen zudem soziale Merkmale nicht in immer gleichem Maße miteinander in Verbindung, genauso wie die Akteure nicht immer soziale Merkmale entsprechend des vorherrschenden Schmetterlingspfades in einer Relationsstruktur miteinander kombinieren. Dies liegt daran, dass Akteure nicht gleichermaßen innerhalb und zwischen Relationsstrukturen zirkulieren, weil sie sich nicht gleichermaßen mit den gleichen gesellschaftlichen Instanzen in Sequenzen und Relationsstrukturen einschreiben. Dies begründet die Auffassung von vertikalen Ungleichheiten innerhalb der Sequenzen von einer Relationsstruktur, die in der Hierarchisierung von Akteurkategorien und von gesellschaftlichen Instanzen in den Sequenzen dieser Relationsstruktur besteht und mithin widerspiegelt wird.

Die zweite Folge betrifft die Auffassung von horizontalen Ungleichheiten in einer Relationsstruktur. Diese Ungleichheiten tauchen innerhalb von Akteurkategorien auf, weil Akteurkategorien nicht ausschließlich in einer einzigen Sequenz von einer Relationsstruktur, sondern in allen Sequenzen von einer Relationsstruktur anwesend sind bzw. sein können. Dies erklärt sich damit, dass Akteure von Akteurkategorien innerhalb von Relationsstrukturen zirkulieren, wodurch sie dazu beitragen, ihre Kategorie auf die Sequenzen und daher auf die entsprechenden Tätigkeitsbereiche in einer Relationsstruktur auszudehnen. Die Entwicklung dieser Zirkulation hängt jedoch nicht zuletzt auch vom Zustand der Relationsstruktur selbst ab, was die Elastizität von sozialen Ungleichheiten bedingt und die horizontalen Ungleichheiten beeinflusst. Etwa bei einem stabilen Schmetterlingspfad beispielsweise in der Kernsequenz Investition der entsprechenden Relationsstruktur: Dort haben alle Akteurkategorien in dieser Kernsequenz bessere Zirkulationsmöglichkeiten als die entsprechenden Akteurkategorien in den anderen Sequenzen. In den anderen Sequenzen haben die Akteurkategorien der Sequenz Repräsentation bessere Zirkulationsmöglichkeiten als die Akteurkategorien in den Sequenzen Materialität und Attraktivität und die Akteurkategorien in der Sequenz Materialität haben wiederum noch etwas bessere Zirkulationsmöglichkeiten als die Akteurkategorien in der Sequenz Attraktivität. Das bedeutet, dass bei einem stabilen Schmetterlingspfad in der Sequenz Investition etwa die erste Akteurkategorie in der Kernsequenz Investition weniger von sozialen Ungleichheiten als die erste Akteurkategorie in der Sequenz Repräsentation betroffen ist. Diese erste Akteurkategorie in der Sequenz Repräsentation ist demgegenüber wiederum weniger sozialen Ungleichheiten ausgesetzt als die erste Akteurkategorie in der Sequenz Materialität. Und schließlich ist die erste Akteurkategorie in der Sequenz Materialität erneut ein Stück weit weniger von sozialen Ungleichheiten betroffen als die erste Akteurkategorie in der Sequenz Attraktivität. Diese allgemeine Überlegung gilt für alle Akteurkategorien im Verhältnis zu ihren Zirkulationsmöglichkeiten bzw. zu deren Chancen, im gegebenen Zustand einer Relationsstruktur ihre Position durch Relation zu wechseln.

Überdies gibt es zwischen diesen zwei ersten Folgen und somit zwischen den vertikalen und horizontalen sozialen Ungleichheiten einen Zusammenhang: Vertikale und horizontale sozialen Ungleichheiten entstehen aus der Unterstützung bzw. der fehlenden Unterstützung der Prioritätsordnung der Sequenzen, wie sie im vorherrschenden Schmetterlingspfad gegeben sind, nach der die allgemeine Zirkulation in einer Relationsstruktur organisiert wird. Diese Prioritätsordnung bildet und dimensioniert den Sinnzusammenhang der sozialen Arbeit und der entsprechenden Tätigkeiten zur Entwicklung von Zirkulationen und Einschreibungsakten, die den entsprechenden Schmetterlingspfad in seiner Sequenz stärken. Anders gesagt, hängen soziale Ungleichheiten von der Priorisierung von Registern sozialer Determinanten bzw. in der Mobilisierung von einem Register von sozialen Determinanten in Unterstützung von einem anderen Register sozialer Determinanten ab und konkret bedeutet, dass sich soziale Ungleichheiten in der Theorie der Relation aus dem pyramidalen Kaskadeneffekt von einem zum nächsten Register sozialer Determinanten und zwar entlang derjenigen Prioritätsordnung ergeben, wie sie im Schmetterlingspfad einer Sequenz abgebildet werden. Oder anders gesagt: Soziale Ungleichheiten hängen davon ab, ob dieser pyramidale Kaskadeneffekt stattfindet (vertikale Ungleichheiten) und ob er nach der Prioritätsordnung stattfindet (horizontale Ungleichheiten), wie er vom vorherrschenden Schmetterlingspfad in einer Relationsstruktur abgebildet wird. Im ersteren Fall resultiert die Bildung von sozialen Ungleichheiten aus der doppelten Einschreibung in Zirkulationen und in Relationsstrukturen, während sich im zweiten Fall die Bildung von sozialen Ungleichheiten aus der Unterstützung von Sequenzen ergibt. Beide Fälle sind wie zwei unterschiedliche aber komplementäre Aspekte desselben Problems sozialer Ungleichheiten aufzufassen, zu denen eine dritte Perspektivierung durch die Zirkulation hinzugefügt wird.

Die Akteure zirkulieren nicht nur innerhalb von und zwischen Sequenzen, sondern auch zwischen Relationsstrukturen (Mehrebenenansatz). Sei es in anderen Sequenzen oder in anderen Relationsstrukturen; die Akteure treffen nicht nur auf weitere gesellschaftliche Instanzen, sie treffen auch auf andere Schmetterlingspfade bzw. auf andere Verhältnisse zwischen sozialen Determinanten der Zirkulation in einer Sequenz bzw. in einer Relationsstruktur. Dies trägt einerseits dazu bei, dass sie bei ihrer Einschreibung in diesen Ankunftsequenzen und -relationsstrukturen neu sozialisiert werden bzw. auf neue Verhältnisse zwischen sozialen Determinanten der Zirkulation gefördert werden. Andererseits stärkt dies den Schmetterlingspfad in der Ankunftsequenz und -relationsstruktur, der die Durchsetzung vom entsprechenden Muster sozialer Ungleichheit fördert. Dadurch verändert sich auch die Priorisierung von Registern sozialer Determinanten. Mit ihr verändert sich wiederum der pyramidale Kaskadeneffekt bzw. die Strukturierung von sowohl vertikalen als auch horizontalen Ungleichheiten, was mit entsprechdenden Konsequenzen für die doppelte Einschreibung von Akteuren und Instanzen in Zirkulationen und in Relationsstrukturen einhergeht und nicht zuletzt auch Konsequenzen für die Bedeutung des Hauptmerkmals der Relationsstruktur an sich und im Vergleich mit den anderen Relationsstrukturen zeitigt, die eine Relationsstruktur zu satellisieren versuchen. Dies bedeutet, dass die Hierarchiesierung innerhalb von Sequenzen (vertikale Ungleichheiten) und zwischen Sequenzen (horizontale Ungleichheiten) innerhalb von einer Relationsstruktur die Hierarchiesierung zwischen den Relationsstrukturen beeinflusst, und umgekehrt. Diese dritte Folge von vertikalen und horizontalen Ungleichheiten auf die sozialen Ungleichheiten zwischen Relationsstrukturen, zwischen den Akteuren und den Instanzen in diesen Relationsstrukturen, ist das, was wir Querschnittsungleichheiten nennen. Sie ergeben sich mittelbar aus der Verbreitung von vertikalen und horizontalen Ungleichheiten auf Zirkulationen innerhalb von Relationsstrukturen. Auf diesen Punkt kommen wir später noch einmal zurück. Die dreifache Auffassung von sozialen Ungleichheiten, wie sie für die Theorie der Relation konstitutiv ist, kommt zu zwei Ergebnissen.

### Ergebnisse

Wie andere Makroansätze kommt die Theorie der Relation in ihrer Auffassung von sozialer Ungleichheit zum einen zu dem Ergebnis, dass sich der Kampf gegen soziale Ungleichheiten für mehr Gleichheit in der Gesellschaft als Kampf zwischen Mustern sozialer Ungleichheiten erweist. Bestimmte Zirkulationswege und Zirkulationsmöglichkeiten werden im Vergleich zu anderen Zirkulationswegen und Zirkulationsmöglichkeiten mit den Akteuren, Kollektiven, gesellschaftlichen Instanzen und Aktanten, die mit ihnen verbunden sind, bevorzugt bzw. benachteiligt.

Zum anderen gelangt die Theorie der Relation in ihrer Auffassung sozialer Ungleichheit aber auch zu einem Ergebnis, welches sie von anderen Auffassungen von sozialer Ungleichheit nach dem Ansatz der Knappheit von Ressourcen in der Gesellschaft kontrastiert. Während also ein solcher Ansatz, der soziale Ungleichheit anhand knapper Ressourcenausstattung aufschließt, einfache Fälle sozialer Ungleichheit gut erklären kann -- Akteure, die weniger Ressourcen als andere Akteure haben oder über gar keine Ressourcen verfügen, werden benachteiligt --, bleibt er stets mit der Annahme der strukturellen Gleichförmigkeit von Gesellschaft einerseits und von gesellschaftlichen Bereichen andererseits verbunden -- zu weniger Ressourcen oder gar keinen Ressourcen Zugang zu besitzen, benachteiligt die betroffenen Akteure überall in der Gesellschaft. Wenn wir dagegen davon ausgehen, dass Strukturen weder statisch noch immer gleich bleiben bzw. dass sie durch Zirkulationen subvertiert werden, dann wird das Problem der Relationalität von sozialen Determinanten und ihrer Förderung durch gesellschaftliche Instanzen wichtiger [siehe in Bezug auf den Zugang zu Bildung und den Ausgang aus dem Ausbildungssystem, vgl. etwa @Solgaetal2009, @Solga2009]. Nicht knappe Ressourcen an sich oder einzig und allein führen zu sozialen Ungleichheiten, sondern mangelhafte bis fehlende Verbindungen zwischen diesen Ressourcen oder Verbindungen, die zu stark vom vorherrschenden Pfad der Zirkulation in einer Relationsstruktur abweichen [siehe dazu Schultzes kritische Betrachtung von Bourdieus Sozialkapital, das Bourdieu im Vergleich zu den anderen Kapitalarten vernachlässigt, so es als die notwendige Grundlage für den Auf- und Ausbau der anderen Kapitalarten betrachtet und anerkannt wird; vgl. @Schultze2022; vgl. die ähnliche Überlegung mit einer Operationalisierung bei @Franzen2007]. Davon hängt ab, ob die Akteure auf gesellschaftliche Instanzen in ihrer Sequenz und in ihrer Relationsstruktur treffen, die sie fördern, oder ob sie einen langen Weg einhergehend mit viel Arbeits- und Zeitaufwand zu bahnen gezwungen sind und vielleicht in Generationen investieren müssen, wenn sie selbst diesen Weg nicht bis zum Ziel gehen können, um solche Instanzen zu erreichen, die ihre Zirkulation potenzieren können [zu solchen Alterungseffekten und der entsprechenden ausgebremsten Zirkulation von Akteuren am Beispiel des Arbeitsmarktes, vgl. @Mayer2010].

Mit dieser Auffassung von sozialer Ungleichheit vom Standpunkt der Relationalität sozialer Determinanten, ihrer Priorisierung zum Aufbau von pyramidalen Kaskadeneffekt zum Zweck der Einschreibung in Zirkulationen und Relationsstrukturen zeigt sich das Problem der sozialen Ungleichheiten vom Standpunkt der Akteure grundsätzlich als ein Problem der Umstellung von Zirkulationen auf mehreren Ebenen und daher des Übergangs von einer zur nächsten Zirkulation, von einer zur nächsten Sequenz und von einer zur anderen Relationsstruktur [vgl. eine vergleichbare Problematisierung im Sinne von Verteilungsungleichheiten bei @Solgaetal2009, 21]. Eine solche Umstellung muss geleistet werden, um an der Verbesserung der eigenen sozialen Situation zu arbeiten. Aber sie generiert auch Kosten -- insbesondere neue Sozialisationskosten aufgrund des Wechsels der Position, des Wohnortes, des Berufs, des Freundeskreises, des Partners, der alltäglichen Gewohnheiten usw. --, ohne den erfolgreichen Ausgang der Umstellung auf die eigene Situation gewährleisten zu können. Zirkulationen zirkulieren weiter und unter anderem auch wegen solcher Umstellungen, was zu weiteren Abweichungen von einem vorherrschenden Schmetterlingspfad und zu dessen Abschwächung zum Vorteil von einem anderen Schmetterlingspfad führen kann. Deshalb kann es selbst bei aller Anstrengung zur Vebesserung der eigenen Situation so sein, dass der Zug schon abgefahren ist, dass die bewerkstelligte und geschaffte Priorisierung von sozialen Determinanten nicht mehr mit der neuen Konfiguration der Zirkulation in einer Relationsstruktur kompatibel und stimmig ist. Davon sind die Akteure am meisten betroffen, die mehr Arbeits- und Zeitaufwand leisten müssen, damit ihre eigene Zirkulation entlang des vorherrschenden Schmetterlingspfades in einer Relationsstruktur orientiert ist [vgl. die Überlegungen Bourdieus zur Anpassung des Habitus an die gesellschaftlichen Strukturen im Kontext der Diskussion zur _hysteresis_ von Habitus in @Bourdieu2012a]. Daher bildet sich der Widerstand von Akteuren in Relation mit ihrer Einschreibung in die Zirkulation von einer Relationsstruktur und mit der Reziprozität, die sich aus einer solchen Einschreibung ergeben kann.

Wir haben die Frage der sozialen Ungleichheit in ihrer Verbindung mit dem Grundgerüst der Theorie der Relation beschrieben. Dabei haben wir gesehen, dass soziale Ungleichheiten die wichtigsten Bedingungen zur Entwicklung von Zirkulationen (Eintritt, Austritt, Übergang) bestimmen, was wiederum diese Zirkulationen vom vorherrschenden Muster der allgemeinen Zirkulation in einer Relationsstruktur mehr oder weniger abweichen lässt. Ein solches Muster haben wir mit dem Begriff des Schmetterlingspfades als eine bestimmte Zusammenstellung von sozialen Determinanten präzisiert, in der diese Determinanten nach ihrer Bedeutung in der Unterstützung der Zirkulation in einer Relationsstruktur hierarchisiert werden. Der Schmetterlingspfad entwickelt sich auf der Grundlage von einer Sequenz in einer Relationsstruktur. Da Relationsstrukturen von vier Sequenzen strukturiert werden, können in jeder Relationsstruktur vier Muster sozialer Ungleichheit gebildet werden. Ihre Stärke in Unterstützung der allgemeinen Zirkulation in einer Relationsstruktur wird umso mehr geschwächt, umso weiter die Sequenz, ab der sich der Schmetterlingspfad bildet, von der Kernsequenz dieser Relationsstruktur entfernt ist (siehe oben unsere Anmerkungen zur Elastizität von sozialen Ungleichheiten). Dies ergibt sich daraus, dass durch die Veränderung der allgemeinen Zirkulation in einer Relationsstruktur diese Relationsstruktur in ihrer Kernsequenz immer weiter geschwächt wird und sich damit auch ihr Hauptmerkmal entsprechend weniger gut durchsetzen kann. Diese Vorstellung, die sich aus der Auffassung von sozialer Ungleicheit, die die Theorie der Relation anbietet, ergibt, kann jetzt verwendet werden, um die aus einem so verstandenen vorherrschenden Muster sozialer Ungleichheit und dessen Elastizität resultierenden Folgen für die Akteure einerseits und die gesellschaftlichen Instanzen andererseits zu konkretisieren, wie sie sich ab der Kernsequenz der vier Relationsstrukturen entwickeln und ausgestalten. Anschließend wird diese Beschreibung durch ein Beispiel zu Querschnittsungleichheiten vervollständigt, das einen Fall der Veränderung des Musters sozialer Ungleichheiten infolge der Satellisierung einer Relationsstruktur durch eine andere Relationsstruktur behandelt.

<!-- Braucht man diese vertiefende Beschreibung vom Muster der SU in der Kernsequenz von jeder Relationsstruktur? Sollte man nicht dagegen bei der Beschreibung der drei Formen von Ungleichheiten (vertikal, horizontal, querschnitt) bleiben?

## Soziale Ungleichheiten und Kernsequenz der Realtionsstrukturen

Was motiviert der Konkurrenzkampf zwischen Mustern der sozialen Ungleichheiten? Die Theorie der Relation hat eine unmittelbare Antwort auf diese Frage, die wie folgt formuliert werden kann: Dieser Kampf ergibt sich aus der Verbreitung vom Kampf zwischen gesellschaftlichen Instanzen zur Durchsetzung ihrer Vermittlungsstruktur als Grundlage der Stärkung ihrer Position in Sequenzen und Relationsstrukturen und als Gewährleistung von Einschreibungsakten mit Akteuren. Dies bedeutet nicht, dass gesellschaftliche Instanzen soziale Ungleichheiten unmittelbar (re)produzieren, als ob sie ausschließlich im Dienst von bestimmten Akteurkategorien arbeiten würden [wie etwa bei Bourdieu, ebd.]. Gesellschaftliche Instanzen arbeiten an der Verbreitung ihrer Vermittlungsstruktur zur Stärkung ihrer Position. Je nach der Ebene, auf der sie ihre Arbeit leisten -- der Ebene der Relationsstruktur, derer Sequenzen und Teilsequenzen --, stärken sie entsprechend den ganzen Schmetterlingspfad oder einen von seinen Achsen oder nur noch eine von seinen Sequenzen. Dies hat Folgen für die Stabilität der Schmetterlingspfade in den Relationsstrukturen, und wenn wir die Schmetterlingspfade der Kernsequenzen von diesen Relationsstrukturen fokussieren, bestimmen dann diese Kämpfe zwischen gesellschaftlichen Instanzen maßgeblich die Stabilisierung bzw. Destabilisierung von Relationsstrukturen. In dem Folgenden vertiefen wir diese Aussage für jede der vier Realtionsstrukturen. Wir fangen mit der Relationsstruktur an, davon die Kernsequenz die Investition ist.

### Relationsstruktur mit Kernsequenz Investition

In der Relationsstruktur mit Kernsequenz Investition sind die Instanzen der Relationsstruktur mächtiger als die Instanzen der (Teil)Sequenzen. Sie sind die einzigen Instanzen, davon die Vermittlungsstruktur unmittelbar in Bezug auf die Verkettung von relationalen Ereignissen entwickelt wird, die sie formalisieren und in die sie sich mit den damit verbundenen Akteuren und Kollektiven sowie mit den von ihnen mobilisierten Aktanten und Mediationen einschreiben. Der Schmetterlingspfad der Kernsequenz von dieser Relationsstruktur setzt sich deshalb im Vergleich zu den konkurrierenden Pfaden der Sequenzen besser durch. Er ist stabiler, was auf der Ebene von sozialen Ungleichheiten bedeutet, dass sie relativ fest bleiben bzw. dass sie die anderen gesellschaftlichen Instanzen dieser Relationsstruktur durch die Stärkung ihrer Arbeit an der Unterstützung von konkurrierenden Schmetterlingspfaden wenig verändern können. Das Muster der sozialen Ungleichheiten setzt in dieser Relationsstruktur voraus, dass Zirkulationswege am besten gebahnt werden, wenn die Akteure mit der Anwesenheit der Kollektiven, dazu sie gehören, zu denen sie sich affilieren oder die sie begleiten, rechnen können. Diese Kollektiven unterstützen sie bei ihrer Zirkulation umso mehr, als sie sich dort befinden oder befunden haben, wo die Akteure zirkulieren. Eine solche Bedingung in ihrer starken Form der Verwandschaft erfüllen wenige Akteure, die mehrheitlich wenn nicht ausschließlich Akteure der ersten Kategorien in dieser Relationsstruktur sind. Mehr Akteure erfüllen diese Bedingung in ihrer milderen Form der Affiliation, die zur zweiten Akteurkategorie dieser Relationsstruktur gehören. Akteure der dritten Kategorie können diese Bedingung nur noch in ihrer schwachen Form der Begleitung erfüllen, wenn Akteure der vierten Kategorien gegen solche Affiliationen stärker wiederstehen.

Im Vergleich zu dieser ersten Bedingung verteilt sich die zweite Bedingung auf Akteurkategorien besser. Sie betrifft die Auseinandersetzung der Akteure mit Mediationen, die die gesellschaftlichen Instanzen formalisiert haben und den Akteuren zwecks Einschreibung in der Relationsstruktur und in ihrer Sequenzen zu Verfügung stellen. Darunter sind die Mediationen von Instanzen der Relationsstruktur, die diese Instanzen in der Form von relationalen Dispositiven bzw. von Techniken, Methoden und Verfahren der Entwicklung von Verkettungsoperationen an relationalen Ereignissen entwickeln. Durch den Umgang mit und die Verwendung von diesen Mediationen erhalten Akteure Zirkulationsmöglichkeiten zum Aufbau von weiteren Zirkulationswegen. Im Vergleich zur ersten Bedingung kann diese zweite Bedingung von mehreren Akteurkategorien besser erfüllt werden. Dies ist einerseits damit verbunden, dass Mediationen grundsätzlich auf alle Akteure offen sind, die sich solche relationalen Dispositiven aneignen können. Dies wiederum ist damit verbunden, dass diese Mediationen von gesellschaftlichen Instanzen der Relationsstruktur entwickelt werden, die sich in dieser Relationsstruktur am besten verbreiten und daher mehr Akteurkategorien erreichen.

Individuelle Merkmale von Akteuren spielen in diesem Zusammenhang eine Rolle beim Übergang zwischen Zirkulationswegen und daher ebenfalls zwischen Sequenzen und Relationsstrukturen. Sie setzen voraus, dass die Eintritt- und Austrittsbedingungen erfüllt wurden, die die Zirkulationen in dieser Relationsstruktur unterstützen. Hier zählt weniger die Singularität des Akteurs an sich. Was mehr zählt ist die Art und Weise, wie ein Akteur die mit ihm verbundenen vergangenen oder gegenwärtigen Kollektiven in Unterstützung seiner Aneignung und Verwendung von Mediationen zur Verkettung von relationalen Ereignissen bringt. Die Akteure der ersten Kategorie in dieser Relationsstruktur, die die Eintritt- und Austrittsbedingungen gut erfüllen, brauchen weniger Zeit- und Arbeitsaufwand, um Übergangsbedingungen ebenfalls gut erfüllen und zu weiteren Sequenzen oder Relationsstrukturen zirkulieren zu können. Deshalb ist diese Akteurkategorie diejenige, die in dieser Relationsstruktur am meisten von der Stärkung ihrer Kernsequenz im Sinne der erfolgreichen bzw. aufsteigenden vertikalen und horizontalen Mobilitätschancen profitiert. Oder anders formuliert: sie ist am meisten vor der Wirkung sozialer Ungleichheiten geschützt. Für die Akteure der zweiten Kategorie muss dagegen mehr Zeit- und Arbeitsaufwand in die Erfüllung von Eintrittsbedingungen investiert werden, um Affiliationsstrategien stärken zu können und Chancen zu vermehren, in Richtung der ersten Akteurkategorie zu zirkulieren. Akteure der dritten Kategorien sind in einer ähnlichen Situation wie die Akteure der zweiten Kategorie mit dem Nachteil, dass sie die Eintrittsbedingungen in Zirkulation noch weniger gut als sie erfüllen. Deshalb müssen sie mehr Zeit- und Arbeitsaufwand in die Erfüllung von Eintrittsbedingungen bei verhältnismäßig mehr Schwierigkeiten spenden, Austritts- und Übergangsbedingungen zu unterstützen. Entsprechend gestaltet sich ihre Zirkulationen in die Richtung der zweiten Akteurkategorie schwieriger. Für die Akteure der vierten Kategorie ist es noch mehr der Fall aufgrund von entsprechenden schlechteren Eintritts- und Austrittsbedingungen.

Insgesamt zeigt die Relationsstruktur mit Kernsequenz Investition folgendes vorherrschendes Muster der sozialen Ungleichheiten. Es hebt besonders stark die Ungleichheiten vor Eintrittsbedingungen hervor, die je nach Akteurkategorien mehr oder weniger gut mit der Erfüllung von Austrittsbedingungen kompensiert werden. Die Erfüllung von Austrittsbedingungen können Affiliationen mit Kollektiven verfestigen, die in dieser Relationsstruktur bestanden haben oder immer noch bestehen. Aber sie kostet Arbeit und Zeit, die die Akteurkategorien unterschiedlich belasten. Diese Kompensationsstrategien, die durch die Stärke und die Reichweite von gesellschaftlichen Instanzen der Relationsstruktur gewährleistet wird, kann noch relativ gut für Akteure der zweiten Kategorie entwickelt werden. Ihre Wirkung auf die Akteure der dritten Kategorie wird jedoch geschwächt. Den Akteuren der vierten Kategorie überzeugen sie nur noch davon, dass ihr Austritt aus Zirkulationswegen in dieser Relationsstruktur ihren Austritt aus dieser Relationsstruktur vorbereitet. Gehen wir jetzt zur Relationsstruktur, davon die Kernsequenz diejenige der Repräsentation ist.

### Relationsstruktur mit Kernsequenz Repräsentation

In dieser Relationsstruktur entwickelt sich ein vorherrschendes Muster der sozialen Ungleichheiten, das ähnlich wie im Fall der Relationsstruktur mit Sequenz Investition stark auf Eintrittsbedingungen in Zirkulationen ruht. In dieser Relationsstruktur sieht der Schmetterlingspfad, der die Kernsequenz der Repräsentation in Unterstützung des Hauptmerkmals dieser Relationsstruktur bezeichnet, wie folgt aus.

Die Eintrittsbedingungen beziehen sich auf individualisierende Merkmale der Akteure als Vertreter von Kollektiven (Materialität). Die Austrittbedingungen betreffen die Verkettung von relationalen Ereignissen, die diese Akteure mit anderen Akteuren bewerkstelligen (Investition). Die Erfüllung von Übergangsbedingungen in der Form der Aneignung und Verwendung von Mediationen kommt in der Unterstützung der Attraktivität der Repräsentation von Kollektiven und deren Repräsentanten (Schwachpunktsequenz). In dieser Relationsstruktur ist es entsprechend wichtig, dass die Akteure all diese individualisierenden Merkmale beziehen, die sie darauf vorbereiten, die Vertreter nicht nur von einem besonderen Kollektiv, sondern von allen möglichen Kollektiven zu werden, die von der Aura, dem Projekt, dem Lebensstil und der Haltung, dem Wort und dem Widerwort, dem Sinn für Humor bis zu den sozialen und kulturellen Wurzeln sowie den ästhetischen Merkmalen von solchen Vertretern begeistert werden können. In dieser Relationsstruktur sind verwandte Affiliationen der Repräsentanten zu Repräsentierten nicht das Alpha, sondern das Omega der Zirkulation von Akteuren, für die es darum geht, Vertrautheit in para-soziale Verwandschaft umzuwandeln [in Anlehnung an dem Begriff der para-soziale Interaktion; vgl. hierzu @Horton1956]. Dies kommt insbesondere der Akteure der zweiten Kategorie im Vergleich zu den Akteuren der ersten Kategorie gelegen, die Eintrittsbedingungen erfüllen und sie per Affiliation weiter ausbauen, um als Vertreter nicht nur von ihrem Kollektiv, sondern auch von anderen Akteurkategorien zu fungieren. Weil diese Akteure ihre Zirkulation in Sequenzen der Relationsstruktur entwickeln, tragen sie dazu bei, die Position von gesellschaftlichen Instanzen der Sequenzen, davon sie das bevorzugte Publikum zwecks Einschreibung in dieser Relationsstruktur darstellen, gegen die Instanzen der Relationsstruktur und der Teilssequenzen zu stärken.

Akteure der ersten Kategorie, die ihr Vertretungspotential ausbauen wollen, können jedoch mit der Erfüllung von Austrittsbedingungen bzw. mit der Distanzierung zum eigenen Herkunftsmilieu und der Investition in der Mobilisierung und der Unterstützung von weiteren Kollektiven ihre Nachteile bei der Erfüllung von Eintrittsbedingungen kompensieren und ihre individualisierenden Merkmale in der sozialen Arbeit an relationalen Ereignissen mit Dritten verwerten zu lassen. Wenn solche Strategien nicht als bloße Erweiterung von Verwandschaftsbeziehungen durch Affiliationen zu fremden Kollektiven entwickelt werden (etwa durch Hochzeit, Clubing oder Formen von _gated community_), sondern zur Mobilisation von anderen Kollektiven erfolgt, dann können diese Akteure dazu beitragen, die Position von gesellschaftlichen Instanzen der Relationsstruktur zu unterstützen. Nichtsdestotrotz verlieren solche Instanzen bei der Durchsetzung vom Muster der sozialen Ungleichheiten in dieser Relationsstruktur an Macht deshalb, weil sie immer unter dem Verdacht stehen, Monopolen von Kollektiven um ihre Vertreter zu begünstigen bzw. Vertrautheit durch Verwandschaft zu ersetzen. Dies belastet wiederum die werdenden Vertreter aus der ersten Akteurkategorie, die für Instanzen der Relationsstruktur das bevorzugte Publikum zur Einschreibung in einer Relationsstruktur darstellen. Sie müssen ständig gegen den Verdarcht kämpfen, dass sie nicht zu Verrätern im Dienst von ihrem Herkunftsmilieu werden. Deshalb ist in dieser Relationsstruktur die zweite Akteurkategorie diejenige, die von aufsteigenden vertikalen und horizontalen Mobilität am meisten profitiert bzw. die am meisten vor der Wirkung sozialer Ungleichheiten geschützt ist.

Akteure der dritten und vierten Kategorie befinden sich in dieser Relationsstruktur in einer ähnlichen Position, wie Akteure der entsprechenden Kategorien in der Relationsstruktur mit Kernsequenz Investition. Sie verfügen zwar über Affiliationspotentiale. Aber im Vergleich mit den Akteuren der zweiten Kategorie erfordert es von ihnen deutlich mehr Zeit- und Arbeitsaufwand, um solche Potentiale zu entwickeln, was sich in ihrem Fall in eine erhebliche Mehrarbeit am Ausbau von individualisirenden Merkmalen niederschlägt, die sie zu Vertretern von all möglichen Kollektiven profilieren würden. Deshalb ist es für sie ebenfalls schwieriger, die Eintrittsbedingungen in Zirkulationen zu erfüllen. Zudem verhindert die erhöte Zeit- und Arbeitsaufwand an ihrem Vertretungsprofil eine erfolgreiche Zirkulationen in die Richtung der zweiten und ersten Akteurkategorien. Die Erfüllung von Übergangsbedingungen von einer Zirkulation zu einer anderen Zirkulation wird damit erschwert, was sich in ihrer Schwierigkeit widerspiegelt, die Repräsentation von Kollektiven, die sie unterstützen können, für alle mögliche Kollektiven attraktiv zu machen. Sie müssen sich dann bei der Aneignung von zahlreichen Mediationen unterschiedlicher Art unvermeidlich mehr anstrengen, damit die Repräsentation von Kollektiven an Attraktivität gewinnt, davon die Zusammenstellung angesicht ihrer Schwierigkeiten, Eintritts- und Austrittsbedingungen zu erfüllen, brüchig bleibt. Mehr als die Akteure der zwei ersten Kategorie belastet die Akteure der dritten und vierten Kategorie der Zweifel an ihrer Überzeugungskraft und an ihrer Glaubwürdigkeit im Dienst der Repräsentation von Kollektiven. Deshalb gelangen sie häufig dazu, kleine Gruppen, informelle oder noch lose Zusammenstellungen von Akteuren zu vertreten, was die Wahrnehmung begünstigt, dass sie insbesondere als Repräsentanten vom Widerstand gegen die Repräsentation von größeren Kollektiven und deren Repräsentanten fungieren.

### Relationsstruktur mit Kernsequenz Materialität

Wenn wir in den zwei erwähnten Relationsstruktur mit Kernsequenzen Investition und Repräsentation ein herrschendes Muster der sozialen Ungleichheiten haben, das vom Gewicht Herkunfts- und Affiliationsmerkmalen getragen wird, ändert sich dies für die zwei anderen Relationsstrukturen, die wir jetzt beschreiben. Es handelt sich einerseits um die Relationsstruktur mit Kernsequenz Materialität und andererseits um die Relationsstruktur mit Kernsequenz Attraktivität. In beiden Relationsstrukturen, in denen die Bedeutung von Kollektiven im Allemgeinen und im Besonderen in Bezug auf soziale Ungleichheiten relativiert wird, geht es bei der Durchsetzung des Musters der sozialen Ungleichheiten maßgeblich um die Arbeit der Einzelakteure an der eigenen Verwirklichung mit Investition von den unterschiedlichsten Mediationen zur Verbesserung ihrer Zirkulation.

Im Fall der Relationsstruktur mit Kernsequenz Materialität geht es um das eigene Tun als Verwirklichung vom Selbst und Machtshebel der Selbstverwirklichung. Diese Relationsstruktur setzt ein Muster der sozialen Ungleichheiten voraus, in dem die Eintrittsbedingungen unmittelbar mit der Bestimmung vom Tun der Akteure und daher mittelbar mit all möglichen Mediationen verbunden ist, der sich ein Akteur aneignen und in der Unterstützung der eigenen Zirkualtion verwenden kann. Weil Mediationen grundsätzlich von allen Akteurkategorien beansprucht und in ihre Zirkulation einbezogen werden, unterscheiden sich die Akteurkategorien voneinander nicht nur dadurch, welche Art von Mediationen und wieviele davon sie beanspruchen. Sie unterscheiden sich auch und insbesondere dadurch, wie sie durch den Einbezug dieser Mediationen ihre eigene Materialisierungskraft belegen und im Dienst ihrer Zirkulation in dieser Relationsstruktur bringen. Die Erfüllung von diesen Eintrittsbedingungen öffnet auf Zirkulationswege und Zirkulationsmöglichkeiten in dieser Relationsstruktur, die aus den Akteuren Vertretern der Sachlichkeit im doppelten Sinne des objektivierten Realismus von machenden Akteuren und der einzig möglichen und deshalb relevanten Realität, die in materialen Merkmalen bzw. in Gegenständen, Produkten, Waren, Mobilien, Immobilien, Vermögen sowie Techniken, Strategien, Methoden, Verfahren abgebildet wird.

Die Erfüllung von Eintrittsbedingungen in dieser Relationsstruktur unterstützt die Erfüllung von Austrittsbedingungen, die in der schwächsten Form der Affiliation zu Kollektiven bzw. in ihrer Begleitung besteht. Durch das, was sie realisieren, ziehen die Akteure Kollektiven zu sich, davon sie vorübergehen die Vertreter zwecks der Anerkennung der eigenen Materialisierungskraft werden, die sie brauchen, um sich weitere Zirkulationsmöglichkeiten zu verschaffen und weitere Zirkulationswege vorzubereiten. Damit sind die Bedingungen vorhanden, um den Übergang von Zirkulationen zu Zirkulationen in dieser Relationsstruktur zu leisten bzw. um die Schwachpunktsequenz der Investition in die soziale Arbeit mit anderen Akteure zur Mobilisation dieser Akteure in der Legitimation der eigenen Materialisierungskraft einzubeziehen. So wird die Kernsequenz der Materialität gestärkt und in dieser Relationsstruktur verbreitet, was insbesondere zum Vorteil der Akteure der dritten Kategorie kommt. Aufgrund ihrer im Vergleich zu Akteuren der ersten und zweiten Kategorien schwächeren Position in der Vertretung von Kollektiven bzw. ihrer stärkeren Freiheit im Umgang mit Kollektiven und weil diese Akteurkategorie im Vergleich zur vierten Akteurkategorien der Relationsstruktur und derer Sequenzen weniger stark widersteht, ist sie diejenige, die von der Stärkung der Kernsequenz Materialität zur Förderung ihrer vertikalen und horizontalen Mobilitätschancen am meisten profitiert bzw. vor der Wirkung sozialer Ungleichheiten geschützt ist.

Ohne feste Anbindungen an Kollektiven sind sie besser in der Lage, die Affiliations- und Desaffiliationsstrategien zu vervielfältigen, die notwendig sind, damit Übergänge zwischen Zirkulationen in dieser Relationsstruktur geschafft werden können. Dabei tragen die Akteure der dritten Kategorie zur Stärkung von gesellschaftlichen Instanzen der Teilsequenzen in dieser Relationsstruktur bei, für die sie das bevorzugte Publikum zwecks der doppelten Einschreibung in dieser Relationsstruktur darstellen. Diese Instanzen der Teilsequenzen sind zwar weniger breit in Relationsstrukturen als Instanzen der Relationsstruktur oder der Sequenzen angelegt. Häufig sind es Instanzen zur förderung von sehr spezialisierten Tätigkeiten, die nur in bestimmten Sektoren oder Bereichen in Sequenzen von Relationsstrukturen entwickelt werden. Sie sind zwar weniger prestigeträchtig als breitere gesellschaftliche Instanzen von Relationsstrukturen, die in der Lage sind, mehrere Tätigkeitsbereiche in einer oder mehreren Sequenzen von einer Relationsstruktur zu adressieren. Aus Einschreibungsakten mit Instanzen der Teilsequenzen ergibt sich deshalb eine mässige Legitimität, die die Gefahr in sich birgt, die Akteure in eine Spirale der kleinen Schritte zu befangen bzw. sie nur noch in sehr kurzen Zirkulationswege von Instanzen der Teilsequenzen zu anderen Instanzen der Teilsequenzen einzuschließen.

Vorteilhaft sind sie für Akteure dennoch, weil sie eine einfachere Vermittlungsstruktur mit wenigen formalisierten Verfahren zeigen, daraus sich kürzere Wege zur doppelten Einschreibungen ergeben. Sie bieten also einen unkomplizierten Zugang zu Zirkulationsmöglichkeiten in einer Relationsstruktur insbesondere für Akteure wie die Akteure der dritten Kategorie an, die aufgrund der strukturellen Determinanten, die sie bestimmen, Schwierigkeiten bei der Entwicklung von Zirkulationswegen und Zirkulationsmöglichkeiten erleben. Sie stellen deshalb eine erste Stufe in der Entwicklung von einer Zirkulation zu breiteren gesellschaftlichen Instanzen der Sequenzen und der Relationsstruktur zur Förderung der vertikalen und horizontalen Mobilität dieser Akteure dar.

### Relationsstruktur mit Kernsequenz Attraktivität

In dieser Relationsstruktur finden wir eine ähnliche Situation wie in der Relationsstruktur mit Kernsequenz Materialität, auch wenn hier der Schmetterlingspfad eine andere Anordnung von sozialen Determinanten darstellt, die die allgemeine Zirkulation fördern. Die Bedeutung von Kollektiven hat sich vollständig relativiert. Sie spielen nur noch eine Rolle für die Einzelakteure bei der Erfüllung von Übergangsbedingungen bzw. beim Übergang zwischen Zirkulationen. Die Aneignung von Meditationen und der Umgang mit Mediationen dient der Stärkung der Mediationen selbst ohne entsprechende Folgen für die Akteure, die sie aneignen und verwenden. Anders gesagt wird in dieser Relationsstruktur und im Kontrast zur Relationsstruktur der Materialität die Wirkung von der Arbeit der Einzelakteuren an der eigenen Individualisierung zur Verbesserung von ihrer Zirkulation geschwächt. Diese doppelte Relativierung der Bedeutung von Kollektiven und von Einzelakteuren spiegelt sich im Schmetterlingspfad dieser Relationsstruktur wider: Die Erfüllung von Eintrittsbedingungen in Zirkulationen hängt nicht primär von Herkunfts-, Affilitions- oder Begleitungsstrategien und auch nicht von der Behauptung der Einzelakteure ab. Sie setzt die breite Öffentlichkeit voraus (Investition - Erfüllung von Eintrittsbedingungen), davon die Unterstützung über die Stärkung bzw. die Schwächung der Zirkulation von Akteuren auf der Grundlage der Beurteilung und der Wertung ihrer Arbeit an individualisierenden Merkmalen entscheidet (Materialität - Erfüllung von Austrittsbedingungen). So kann die Schwachpunktsequenz der Repräsentation in dieser Relationsstruktur einbezogen werden, davon die Bedeutung als Vertretung von Kollektiven der durch die breite Öffentlichkeit abgesegneten Attraktivität von Mediationen unterworfen wird. Es handelt sich darum, die Attraktivität von Mediationen durch die Akteure, Kollektiven, gesellschaftliche Instanzen und weitere Aktanten, die sie verwenden oder mit diesen Mediationen verbunden sind, zu repräsentieren.

Im Vergleich zu den anderen Relationsstrukturen gibt es in dieser Relationsstruktur eine Verbreitung vom Muster der sozialen Ungleichheiten auf der Grundlage von vorübergehenden Angelegenheiten, die aufgegriffen oder nicht aufgegriffen werden. Sie stellen sich in der Form vom guten oder vom schlechten Coup dar, der erfolgt oder nicht erfolgt. Was als erfolgreich oder nicht erfolgreich gilt, darüber entscheiden die Publika um die Akteure, die diese Akteure nur noch formal in der Folge ihrer Verwendung von Mediationen repräsentieren. Ihre Entscheidung ergibt sich durch diese Mediationen als Bewertungen der unterschiedlichen individualisierenden Merkmalen von Einzelakteuren, die ihr Umgang mit Mediationen zu verwerten ermöglicht, und sie werden von den gesellschaftlichen Instanzen aufgenommen, die diese Mediationen zur Verfügung der Akteure und Kollektiven in der Gesellschaft stellen. In dieser Relationsstruktur stellt sich die doppelte Einschreibung von Akteuren und Instanzen auf der Grundlage der Bedeutung von Einzelzirkulationswegen im Vergleich zu all anderen Zirkulationswegen dar, die entwickelt wurden. Dabei spielen gesellschaftliche Umverteilungsinstanzen eine wichtige Rolle, die eine solche Bedeutung von Einzelzirkulationswegen aufarbeiten und erklären. Sie sind die gesellschaftlichen Instanzen, die an der Verbesserung der Vermittlungsstruktur von gesellschaftlichen Instanzen durch die Kontrolle und die Analyse von Einschreibungsakten arbeiten. In dieser Relationsstruktur gewinnen sie deshalb an Macht, weil ihre Arbeitsgrundlage durch die massive Verwendung von Mediationen deutlich ausgedehnt wird, die sie ohne viel Arbeits- und Zeitaufwand aufbereiten bzw. verdaten können. Diese Instanzen fungieren deshalb als stärkste Kraft im Hintergrund der Einschreibungsakten, wie sie von den anderen gesellschaftlichen Instanzen in dieser Relationsstruktur vorgenommen werden, weil sie einen wichtigen Einfluss auf die Sanktionsoperationen dieser Instanzen ausüben und damit auf die Verbreitung des vorherrschenden Musters der sozialen Ungleichheiten in dieser Relationsstruktur entscheidend beitragen.

Die Akteure, die von der Verbreitung dieses Musters der sozialen Ungleichheiten am meisten profitieren, gehören der vierten Akteurkategorie an. Einerseits haben diese Akteure beim Versuch, aufsteigende Zirkulationswege in dieser Relationsstruktur zu entwickeln, nichts zu verlieren. Andererseits und aufgrund der Schwächung der Bedeutung von den Verbindungen zu Kollektiven und vom stufenartigen Aufbau von Zirkulationswegen in dieser Relationsstruktur können diese Akteure aufsteigende Zirkulationswege bahnen, ohne den Arbeits- und Zeitaufwand wie in den anderen Relationsstrukturen leisten zu müssen. Die Gelegenheit zum sprunghaften Aufstieg kann ausreichen, angenommen dass die Massenbewertungen gut auffallen, wofür das Verhältnis mit den Publika in der Form der Selbstinszenierung ständig unterstützt werden muss. Dabei geht es darum, das zu szenarisieren, was sie sind bzw. sein wollen, damit fremde Bewertungen gefördert werden, davon die Arbeit von Instanzen der Umverteilung an der Verbesserung von formalen Verfahren aller gesellschaftlichen Instanzen abhängt. Deshalb ist die vierte Kategorie von Akteuren in dieser Relationsstruktur diejenige, derer Mobilität im Allgemeinen und derer gesellschaftlichen Aufstiegschancen im Besonderen am meisten profitiert, wie sie diejenige ist, davon die Zirkulationsmöglichkeiten die Zirkulationswünsche der anderen Akteurkategorien am meisten anlockt. Es gibt in dieser Relationsstruktur deshalb eine enge Verbindung zwischen der medialen Inszenierung der Attraktivität von Einzelakteuren und der formalen Operationen von Umverteilungsinstanzen zum Vorteil der anderen gesellschaftlichen Instanzen und zum Vorteil der Entwicklung von weiteren Zirkulationsmöglichkeiten und Zirkulationswegen für die Akteure.

-->

An diesem Punkt erinnern wir an die pädagogische Typisierung der Relationsstrukturen, die wir in diesem Band verwendet haben, um einen erleichterten Zugang und ein besseres Verständnis zu der entsprechenden Realität des Begriffs der Relationsstruktur zu gewährleisten. Wir haben hervorgehoben, dass die Relatonsstruktur mit Kernsequenz Investition diejenige ist, die in der Welt der Kultur _lato sensu_ (Kunst, Literatur, Religion, Wissenschaft usw.) vorherrscht, während die Relationsstruktur mit Kernsequenz Repräsentation diejenige ist, die vor allem in der Welt der Politik dominiert. Die Relationsstruktur mit Kernsequenz Materialität wäre insbesondere in der Welt der Wirtschaft vorhanden, wohingegen die Relationsstruktur mit Kernsequenz Attraktivität die Welt der Medien in besonderem Maße kennzeichnet, weil sie dort vorherrscht. Im Hinblick auf die Thematik sozialer Ungleichheit ergibt sich hieraus, dass Herkunftsungleichheiten insbesondere in der Welt der Kultur vertikale Ungleichheiten bzw. soziale Ungleichheiten in den Tätigkeitesbereichen der Kultur strukturieren. Affiliationsungleichheiten strukturieren dagegen insbesondere vertikale Ungleichheiten in der Welt der Politik und Ungleichheiten der Opportunisten bzw. Opportunitätsungleichheiten bezeichnen insbesondere die Strukturierung von vertikalen Ungleichheiten in der Welt der Wirtschaft. In der Welt der Medien schließlich ergeben sich vertikale Ungleichheiten in ihrer Struktur vornehmlich aus der Umwandlung der öffentlichen Bewertungen von Einzelakteuren in Kriterien zur Verbesserung von formalen Verfahren der gesellschaftlichen Instanzen. Diese vier Muster sozialer Ungleichheit ergeben sich zum einen aus der Relativierung des Einflusses von Kollektiven und zum anderen aus der Relativierung des Einflusses von Einzelakteuren auf die soziale Ungleichheit bzw. auf die Steuerung ihrer Zirkulationen. Der Einfluss von Mediationen auf die soziale Ungleichheit wächst dabei entsprechend in dem Maße, wie wir uns von der Relationsstruktur mit Kernsequenz Investition zu derjenigen mit der Kernsequenz Attraktivität bewegen und von der Relationsstruktur mit Kernsequenz Attraktivität freilich am besten illustriert wird.



Vertikale und horizontale Ungleichheiten sind jedoch nicht die einzigen Arten sozialer Ungleichheit, die die Theorie der Relation zu fassen und zu beschreiben imstande ist. Sie kann ebenso Querschnittsungleichheiten theoretisch wie empirisch greifbar machen und erkennen. Diese Art sozialer Ungleichheit ergibt sich erstens daraus, dass jedes der vier Muster sozialer Ungleichheit, von denen wir bisher gesprochen haben, in jeder Relationsstruktur vorhanden ist. Zweitens ergibt sich diese Art sozialer Ungleichheit aber auch daraus, dass diese Muster gleichsam in einem mittelbaren Verhältnis zu den vier Relationsstrukturen stehen und somit zwischen Relationsstrukturen existent sind. Dies rechtfertigt sich damit, dass die Relationsstrukturen stets versuchen, Einfluss aufeinander auszuüben und sich gegenseitig zu satellisieren. An dieser Stelle kommen wir auf einen Punkt zurück, der bereits in unserer Einleitung in diesem Kapitel Erwähnung fand: Die Satellisierung von einer Relationsstruktur durch eine andere Relationsstruktur destabilisiert die allgemeine Zirkulation in der satellisierten Relationsstruktur (vgl auch Abs. Abweichungen vom Schmetterlingspfad in diesem Kapitel). Da die allgemeine Zirkulation stets vom Schmetterlingspfad der Kernsequenz der entsprechenden Relationssttruktur unterstützt wird, trägt der Einfluss von einer auf eine andere Relationsstruktur zur unmittelbaren Destabilisierung von diesem Schmetterlingspfad bei, was wiederum das vorherrschende Muster sozialer Ungleichheit in der satellisierten Relationsstruktur zum Vorteil eines anderen Schmetterlingspfades und dem diesem Pfad entsprechenden Muster sozialer Ungleichheit in derselben Relationsstruktur schwächt bzw. stört. Zu diesem Fall, der die Konzeption von Querschnittsungleichheiten in exemplarischer Weise skizziert, kommen wir nun abschließend.

## Querschnittsungleichheiten

Ein Schmetterlingspfad wird in einer Relationsstruktur stabilisiert, wenn er die Entwicklung von Zirkulationswegen stabilisiert. Dies ist der Fall, wenn Akteure und gesellschaftliche Instanzen Einschreibungsmöglichkeiten in einer Relationsstruktur entwickeln können, was voraussetzt, dass ein Übergang von einer zur nächsten Zirkulation tatsächlich möglich ist und auch Umsetzung findet. Dahingehend ließe sich also zusammenfassen: Ein Schmetterlingspfad wird dadurch stabilisiert, dass die Erfüllung von Übergangsbedingungen gewährleistet wird. Auf der Ebene einer Relationsstruktur setzt dies jedoch zwingend voraus, dass die Schwachpunktsequenz einer Relationsstruktur so wenig wie möglich unter den Einfluss anderer Relationsstrukturen fallen darf. Wenn wir diesen Sachverhalt in den Termini unserer pädagogischen Typisierung der Relationsstrukturen ausdrücken, hieße das, dass die Welt der Kultur versucht, vor allem dem Einfluss der Wirtschaft zu entkommen, während die Welt der Politik bevorzugt dem Einfluss der Medien zu entgehen versucht, die Welt der Wirtschaft sich primär dem Einfluss der Wissenschaft zu entziehen sucht und schließlich die Welt der Medien vor allem dem Einfluss der Politik zu vermeiden bemüht ist. Dieses Verhältnis der Relationsstrukturen auf ihre jeweilige Schwachpunktsequenz -- die erste Ebene von Querschnittsungleichheiten, wie sie zwischen Relationsstruktur entwickelt werden -- wirkt sich auf die soziale Ungleichheit innerhalb von Relationsstrukturen transversal strukturierend aus -- die andere Ebene von Querschnittsungleichheiten, wie sie zwischen Sequenzen von einer Relationsstruktur entwickelt werden. Oder anders gesagt: Die stabile Entwicklung von einer Relationsstruktur setzt voraus, dass vertikale Ungleichheiten in den jeweiligen Sequenzen einer Relationsstruktur von der Gewährleistung ihrer Schwachpunktsequenz im Dienst der Verbreitung ihrer Kernsequenz und daher der ganzen Relationsstruktur strukturiert werden. Dies gilt, wie wir in der _Skizze einer Theorie der Relation_ im Detail gezeigt haben [@PapilloudSchultze2022], für alle Relationsstrukturen gleichermaßen. Die Erklärung dieses Sachverhalts werden wir hier nicht wiederholen, stattdessen werden wir diesen Sachverhalt unter Rekurs auf eine Relationsstruktur konkretisieren und vertiefen, auf die wir im Rahmen dieses Kapitels zu Illustrationszwecken schon mehrmals zurückgegriffen haben: Die Relationsstruktur mit Kernsequenz Investition bzw. die Relationsstruktur, die die Bereiche der Kultur vorherrschend strukturiert.

### Stabilisierung im Schmetterlingspfad in der Kernsequenz

Aus der Thematisierung der Bereiche der Kultur -- die Kunst, die Wissenschaft, die Religion usw. -- mit der Theorie der Relation ergibt sich, dass soziale Ungleichheiten und entsprechende Hierarchien zwischen Akteuren und Akteurkategorien durch die Einschränkung sowohl der übermäßigen Verbreitung als auch der möglichen Schwächung von materiellen Bestimmungen ihrer Zirkulation strukturiert werden. Als Schwachpunktsequenz dieser Bereiche droht sie, ihre Entwicklung zu gefährden, weshalb sie unbedingt mit den anderen Sequenzen im Schmetterlingspfad der Kernsequenz Investition verbunden bleiben muss. Dazu tragen am meisten die Akteure der Kernsequenz Investition -- darunter insbesondere die Akteure der ersten Akteurkategorie -- durch ihre Arbeit an der Investition in die Kultur als solche (Schriftsteller schreiben ihre Bücher, Wissenschaftler forschen, Künstler arbeiten an ihrem Werk) und in Unterstützung des Hauptmerkmals dieser Relationsstruktur bei. Mittelbar führt diese Arbeit an der Verbreitung der Kernsequenz zur Stärkung und Verbreitung desjenigen Musters sozialer Ungleichheit, wie es im Schmetterlingspfad dieser Kernsequenz gegeben und abgebildet ist.

In der Welt der Kultur sind die Akteure der ersten Kategorie diejenigen, deren Herkunftskollektive dort anwesend sind oder waren, die die Akteure diese Kategorie perpetuieren. Die Akteure der zweiten Kategorie versuchen hingegen, sich durch Affiliationsstrategien möglichst etablierten Kollektiven im Bereich der Kultur anzuschließen und durch die Aneignung und Verwendung von Mediationen, die Instanzen der Kultur bereitstellen, in Richtung der Akteure der ersten Kategorie weiterzuzirkulieren. Die Akteure der dritten und vierten Kategorien werden dagegen benachteiligt, da sie weder mit der Anwesenheit von Herkunftskollektiven, geschweige dem Anschluss an diese, rechnen können noch auf ein ausgeprägtes Affiliationspotential zurückgreifen können. Sie müssen sich entsprechend deutlich mehr bemühen, Affiliationsstrategien zu entwickeln und sich mit Hilfe von Mediationen in den unterschiedlichen Tätigkeitsbereichen der Kultur in Begleitung der entsprechenden Instanzen verwandt zu machen. Die Akteure der dritten Kategorie sind von einer solchen Benachteiligung am stärksten betroffen. Einerseits haben sie im Vergleich zu den Akteuren der vierten Kategorie die Hoffnung nicht aufgegeben, diesen Bereichen der Kultur anzugehören. Sie hoffen darauf, dass sie eine (möglichst aufsteigende) Zirkulation trotz der Vervielfältigung von Einschreibungsakten mit verschiedenen Instanzen der Kultur -- angefangen mit den bescheidensten von ihnen, die an Teilen der Kernsequenz Investition arbeiten -- aufbauen zu können. Andererseits steht ihnen aber immer noch der Zugang zu Mediationen offen, die ihre Einschreibungen mit Instanzen der Kultur fördern. Dafür zahlt die dritte Akteurkategorie jedoch einen relativ hohen Preis, der sich vornehmlich in einem deutlich höheren Zeit- und Arbeitsaufwand bei der Erfüllung von Eintritts-, Austritts- und Übergangsbedingungen zur Entwicklung von Zirkulationen niederschlägt.

Diese dritte Akteurkategorie ist strukturell mehr als die vierte Akteurkategorie, aber zirkulatorisch weniger als sie belastet. Der Grund dafür ist, dass sie keinen kurzen Zirkulationsweg aus der Kernsequenz bahnen kann. Im Vergleich zur ersten und zur zweiten Akteurkategorie ist sie doppelt, d. h. sowohl strukturell als auch zirkulatorisch, benachteiligt. Wollen diese Akteure der dritten Kategorie in der Kernsequenz Investition weiter zirkuliern oder diese Sequenz verlassen, müssen sie ohnehin deutlich mehr Arbeit an ihrer Zirkulation als die anderen Akteurkategorien mit einem Ergebnis leisten, dass im Vergleich keineswegs als sicher einzustufen ist. In dieser dritten Akteurkategorie sind besonders diejenige Akteure von dieser Ungleichheit betroffen, die die notwendigen sozialen Bestimmungsmerkmale nicht vorweisen können, damit solche Bedingungen überhaupt erfüllt werden können -- häufig etwa Neuankömmlinge in dieser Relationsstruktur mit wenig Erfahrung, Frauen auf der Suche nach Affiliationskollektiven, ältere Akteure, die sich mit veralteten Mediationen beschäftigen oder Akteure, die sich auf der Ebene von Einschreibungen mit kleinen Instanzen der Kultur verschränken.

Die Stärkung der vertikalen Ungleichheiten in der Kernsequenz Investition hat nicht nur Folgen für diese Sequenz, sondern auch für die drei anderen. Wenn die Kernsequenz stabil verbreitet wird, dann stärkt sie den Einbezug der anderen drei Sequenzen im Dienst der Verbreitung der ganzen Relationsstruktur unter dem Impuls und der Ägide der Kernsequenz. Dies gilt für alle Relationsstrukturen, und stärkt die Hierarchisierung der Sequenzen nach ihrer Anordnung im Schmetterlingspfad der Kernsequenz. Vertikale Ungleichheiten in einer Sequenz führen dann nicht nur zu horizontalen Ungleicheiten zwischen Sequenzen, sondern auch zur Vertikalisierung von Sequenzen und entsprechend zu ihrer Ungleichheit. Auf unser Beispiel zurückbezogen, bedeutet dies, dass die Verbreitung der Sequenz Investition zuerst die Bedeutung der Sequenz Repräsentation, dann der Sequenz Attraktivität und schließlich der Sequenz Materialität einschränkt. Deshalb gewinnen Eintrittsbedingungen in Zirkulationen vor den Austrittsbedingungen und den Übergangsbedingungen an Bedeutung. Herkunfts- und Affiliationskollektive werden wichtiger als die Aneignung von und der Umgang mit Mediationen, denen mehr Gewicht als den individualisierenden Merkmale der Einzelakteure beigemessen wird. Dies hat Folgen für die Hierarchiesierung von Akteuren in den drei anderen Sequenzen neben der Kernsequenz und zwar im Sinne der Belastung ihrer Zirkulation, die wie folgt dargestellt werden können.

In der Sequenz Repräsentation ist nicht mehr die dritte Akteurkategorie wie in der Kernsequenz Investition am stärksten belastet, sondern die zweite Akteurkategorie. Durch die Stärkung von Eintrittsbedingungen in Zirkulationen gewinnen Herkunftskollektive an Macht, was die Affiliation der Akteure der zweiten Kategorie zu bereits instituierten Kollektiven einschränkt, wodurch diese nur unter Schwierigkeiten in Richtung der Akteure der ersten Kategorie in dieser Sequenz zirkulieren können. Dies wiederum schwächt die Sequenz Materialität, zu der entsprechend weniger Akteure aus den Sequenzen Investition und Repräsentation zirkulieren, weil die Zirkulation zwischen diesen Sequenzen maßgeblich von Akteuren mit (gegenwärtigen oder vergangenen) anwesenden Kollektiven entwickelt wird. Davon sind insbesondere die Akteure der ersten Kategorie in der Sequenz Materialität betroffen, die zunehmend altern und deshalb von absteigenden Zirkulationen bzw. von Deklassierung bedroht werden. Die Akteure in der Sequenz Attraktivität sind im Vergleich weniger gefährdet, weil diese Sequenz am wenigsten durch die Ankunft von neuen Akteuren aus anderen Sequenzen destabilisiert wird. Diese Sequenz kann an Akteuren verlieren, was die Zirkulationsmöglichkeiten für die verbleibenden Akteure in dieser Sequenz verhältnismäßig verbessern kann, die wiederum schneller von vakanten zu weiteren vakanten Positionen zirkulieren können. Aber ein solcher Vorteil gilt nur vorübergehend: Wenn die Sequenz Materialität weiter geschwächt wird, dann zieht sie die Sequenz Attraktivität in die Spirale der Schwächung mithinein, weil die letztere von beiden Sequenzen nicht mehr in der Lage ist, genügend Akteure in die Kernsequenz Investition zu entsenden bzw. die Akteure für diese Relationsstruktur zu begeistern, was sie unvermeidlich schwächt.

Die Stärkung der Kernsequenz Investition, des entsprechenden Schmetterlingspfades und des damit verbundenen Musters der sozialen Ungleichheiten verdeutlicht eines: Die Ambivalenz der Akteure der Kultur gegenüber all denen bzw. allen Akteuren und gesellschaftlichen Instanzen, die individualisierenden Merkmalen eine übertriebene Rolle bei der Bestimmung von Zirkulationen beimesssen. Im Fall einer stabilen Entwicklung solcher Bereiche sind also insgesamt diejenigen Akteure und Instanzen in dieser Relationsstruktur Diskriminierung ausgesetzt, die die Anerkennung und die Legitimität von Kultur in Bezug auf ihre Arbeit an der Materialisierung von Kultur in Gütern und Dienstleistungen für die breite Gesellschaft umdefinieren. Es sind die Akteure der Schwachpunktsequenz Materialität und unter ihnen insbesondere diejenigen der ersten Kategorie, die diese Sequenz stark unterstützen. Dies ist die unmittelbare Folge aus der Stabilisierung von solchen Bereichen der Kultur, die wie folgt zusammengefasst werden kann: Die Akteure und Instanzen, die die Materialität von Kultur am ausgeprägtesten unterstützen, sind diejenigen in dieser Relationsstruktur, die am stärksten verachtet und entsprechend in ihrer Zirkulation bzw. Position einerseits und ihrer Arbeit an relationalen Ereignissen andererseits am meisten gegenüber den Akteuren der anderen Sequenzen vertikal (in der Sequenz), horizontal (in Bezug auf homologe Akteurkategorien/Arten der gesellschaftlichen Instanzen in anderen Sequenzen) und transversal (zwischen Sequenzen) diskriminiert werden.

### Destabilisierung vom Schmetterlingspfad der Kernsequenz

Nehmen wir jetzt an, dass die Bereiche der Kultur destabilisiert werden. Dies entspricht einer Situation der infiltrierenden Dienstabarmachung einer Sequenz in der Relationsstruktur mit Kernsequenz Investition durch eine andere Relationsstruktur, die ihren kernsequenzsprezifischen Schmetterlingspfad gegen den Schmetterlingspfad der Kernsequenz Investition durchsetzt. Wie wir in diesem Kapitel und in diesem Band bereits gezeigt haben, entspricht eine solche infiltrierende Dienstbarmachung der Einflussnahme einer Relationsstruktur auf die Relationsstruktur mit Kernsequenz Investition. Um dies zu illustrieren, konzentrieren wir uns in der Folge auf das Beispiel der Einflussnahme der Politik auf die Wissenschaft in einem speziellen Fall der Demokratisierung des Studiums an Universitäten wie etwa bei der Flexibilisierung des _Numerus clausus_ an Universitäten in Bachelor-Studiengängen.

Mit der Flexibilisierung des _Numerus clausus_ zur Erlangung eines Studienplatzes werden mehr Akteure zum Universitätsstudium zugelassen. Diese Maßnahme lockert einerseits die Verbindung zwischen Akteuren und Herkunftskollektiven auf. Akteure können auch ohne die (gegenwärtige oder vergangene) Anwesenheit von Herkunftskollektiven auf eine Karriere an der Universität hoffen [@Lörz2011, 459; @Müller2004, 345]. Affiliationsstrategien können dafür ausreichend sein, was insbesondere den Akteuren der zweiten Kategorie zum Vorteil gereicht. Die Aneignung und die Verwendung von Mediationen, die die Universität bereitstellt -- pädadogischen Methoden, der Umgang mit unterschiedlichen Formaten von Lehrveranstaltungen und von Prüfungen, die Möglichkeit, Module im Studienplan flexible zusammenzustellen, die Erreichbarkeit des Lehrpersonals usw. [@Winter2018, 286] -- gewinnen umso mehr an Bedeutung, als die Universität verstärkt ein heterogeneres Publikum bedient [@Bildungsberichterstattung2018, 157; @Zechlin2012, 83]. Ähnlich verhält es sich mit dem Austausch zwischen Akteuren innerhalb der Universität. Weil sie vermehrt heterogen sind [@Reifenberg2021a; @Berg2014, 100], tragen die Akteure zur qualitativen und quantitativen Ausdifferenzierung dieses Austauschs bei, was die Bedeutung der Arbeit an relationalen Ereignissen mit anderen Akteuren stärkt. Die Repräsentation von Wissen und von der Wissenschaft wird durch diese Maßnahme attraktiver, was jedoch den Schmetterlingspfad der Kernsequenz Investition, der den Bereich des akademischen Lebens vorherrschend strukturiert, zum Vorteil des Schmetterlingspfades der Sequenz Repräsentation destabilisiert.

Der Schmetterlingspfad der Sequenz Repräsentation erhält in der Folge sehr viel mehr Unterstützung, dessen sequentielles Muster im Schmetterlingspfad der Relationsstruktur mit Kernsequenz Repräsentation das Schwergewicht bildet und entsprechend die Welt der Politik in besonderem Maße strukturiert. Diese Stärkung der Sequenz Repräsentation im Bereich der Wissenschaft durch die Politik kräftigt die Entwicklung des dieser Sequenz entsprechenden Musters der sozialen Ungleichheit. Nach diesem Muster müssen die Akteure, die an der Universität erfolgreich studieren möchten, einerseits mehr in die eigene Materialisierungskraft (Eintrittsbedingungen) investieren. Andererseits gewinnt der Austausch mit sehr unterschiedlichen Akteuren an der Universität an Bedeutung [@Bargel2009, 42], um sich im Studium orientieren zu können (bspw. mit Dozenten und Mitstudierenden; Austrittsbedingungen). Die Erfüllung dieser Bedingungen durch die Studierendenschaft verbessert die Aneignung von und den Umgang mit unterschiedlichen Mediationen, die die Universität im Laufe des Studiums anbietet, um die Akteure bei ihrem Übergang von einem zum anderen Zyklus im Curriculum bestmöglichst zu fördern. Im Sinne des Musters sozialer Ungleichheit, das durch die Dienstbarmachung der Sequenz Repräsentation durch die Politik in den Bereichen der Kultur eingeführt wird, bedeutet das, dass die Veränderungen, die durch die Flexibilisierung des _Numerus clausus_ zu Beginn eines Universitätsstudiums herbeigeführt werden, vorteilhafte Wirkungen nicht nur für die zweite Akteurkategorie in der Sequenz Repräsentation hat, sondern auch die Möglichkeiten von aufsteigenden Zirkulationen für die dritte Akteurkategorie verbessert. Die Bevorteilung der Akteure der zweiten und dritten Akteurkategorie gestaltet sich wiederum für die Akteure der ersten Kategorie in der Sequenz Repräsentation als Nachteil, denn für sie stellt die Universität nun nicht mehr die natürliche Verlängerung ihres Herkunftsmilieus mit gleichgesinnten Akteuren dar. Aber die Akteure in dieser Sequenz, die am meisten geschwächt und benachteiligt werden, gehören der vierten Akteurkategorie an. Dies rechtfertigt sich damit, dass der Widerstand der Akteure der vierten Kategorie gegen all das, was die Universität repräsentiert, infolge der Maßnahme zur Demokratisierung des Studiums an der Universität und darüber hinaus zur Demokratisierung des Zugangs zu Wissen und zur Wissenschaft sowohl an Verbreitungsmacht als auch an Kraft verliert. Dies gilt umso mehr und und schließt die Akteure der ersten Akteurkategorie mit ein, als diese immer mehr aufgrund ihrer Einstellung und Haltung gegenüber dem Ausbildungssystem -- also meistens _ad personam_ -- diskriminiert werden, weil sie einer solchen Maßnahme zur Demokratisierung des Studiums zur mittelbaren Stärkung meritokratischer Prinzipien im Studium skeptisch bis ablehnend gegenüberstehen und die Verbreitung der Meritokratie an Universitäten kaum unterstützen.

Daraus ergibt sich ferner, dass die Durchsetzung dieses neuen Musters sozialer Ungleichheit nicht nur eine Wirkung auf die neue Strukturierung der Sequenz Repräsentation in der Relationsstruktur mit Kernsequenz Investition ausübt. Sie beeinflusst gleichzeitig auch die Strukturierung aller anderen Sequenzen in dieser Relationsstruktur. Durch die Schwächung der ersten Akteurkategorie in der Kernsequenz Investition, gewinnt die Zirkulation der Akteure der zweiten Kategorie in der Sequenz Repräsentation an Spielraum und Freiheitsgraden. Diese Akteure können leichter und auf kürzerem Wege in Richtung der Akteure der ersten Kategorie zirkulieren, was ihnen wiederum bessere Zirkulationsmöglichkeiten in die Sequenz Materialität einräumt, in die sie entsprechend verstärkt zirkulieren können. Dies geht zum Vorteil der ersten Akteurkategorie in der Sequenz Materialität, die entsprechend gestärkt wird. Gleichzeitig wird die Zirkulation von Akteuren der dritten Kategorie in der Sequenz Materialität ausgebremst, die dort das erdrückende Gewicht des neuen Musters sozialer Ungleichheit unvermeidlich zu spüren bekommen. Die Stärkung der Sequenz Materialität führt jedoch auch dazu, dass weniger Akteure diese Sequenz für die Sequenz Attraktivität verlassen, was sowohl die Zirkulation der Akteure in der Sequenz Attraktivität als auch die Weiterzirkulation der Akteure zur nächsten Sequenz Investition schwächt. Davon ist insbesondere die aufsteigende Zirkulation der Akteure der zweiten Kategorie in der Sequenz Attraktivität betroffen, was gleichzeitig den Schwachpunkt der Einführung des neuen Ungleichheitsmusters ausgehend vom Schmetterlingspfad der Sequenz Repräsentation markiert.

Die vermehrten aufsteigenden Zirkulationsmöglichkeiten, die die Akteure der zweiten Kategorie unmittelbar (Sequenz Repräsentation) und mittelbar (in den anderen Sequenzen) erhalten, sind nichtsdestotrotz mit der entsprechenden Stärkung der Kontrolle der Aneignung von und des Umgangs mit Mediationen verbunden, die die Attraktivität der Repräsentation von Wissen und von der Wissenschaft in der Gesellschaft zu gewährleisten hat [@Roessler2015, 14, 23]. Dies schlägt sich auf die Akteure dieser Akteurkategorie in besonderem Maße nieder, da sie zwar von der Schwächung der Selektivität beim Eintritt in die Universität profitieren, gleichzeitig aber auch umso mehr in die Lage versetzt sehen, stets und ständig ihre Fähigkeiten und ihr Geschick sowie ihre Strategien und Taktiken bei der Aneignung von und dem Umgang mit Mediationen unter Beweis stellen und belegen zu müssen. Die Erfüllung dieser Übergangsbedingungen, in deren Rahmen den individualisierenden Merkmalen der Akteure ein stärkeres Gewicht zukommt, verlangen von den Akteuren der zweiten Kategorie, dass sie die Kosten tragen, die mit dem Übergang von Zirkulation zu Zirkulation verbunden sind -- etwa die Entfernung von der Familien, von Freundeskreisen, die neue Sozialisation auf den neuen Standort, auf neue Akteure, Kollektiven, Aktanten und Mediationen an diesem Standort usw. Die Förderung der Zirkulation der Akteure der zweiten Kategorie ist also wichtig, weil ihre Zirkulation die Attraktivität der Repräsentation von Wissen und von der Wissenschaft konkretisiert und nicht etwa _visa versa_ die Universität die Attraktivität von solchen Akteuren und ihrer Akteurkategorie grundsätzlich repräsentieren würde. Die Durchsetzung der Sequenz Repräsentation bedeutet also lediglich, dass das Wissen und die Wissenschaft die größt mögliche Anzahl von Akteuren adressieren und erreichen sollte und es nicht darum gehen kann, dass die Repräsentation unterstützt wird, die sich eine Akteurkategorie von Wissen und von der Wissenschaft macht.

Anhand dieses Beispiels ist ersichtlich, dass der Einfluss von einer Relationsstruktur auf eine andere Relationsstruktur nicht zur Abmilderung von sozialer Ungleichheit führt, sondern zum Wechsel des Musters der sozialen Ungleichheit und zur entsprechenden temporären Umverteilung des Gewichts von Registern sozialer Merkmale, die durch die Durchsetzung eines neuen Ungleichheitsverhältnisses entstehen und dann anstelle des dominanten Ungleichheitsmusters ebenfalls auf den Akteuren bzw. auf den Akteurkategorien lasten. Akteure, die im stabilen Zustand des Schmetterlingspfades von einer Relationsstruktur Schwierigkeiten haben, ihre Zirkulation zu entwickeln, können von einer Destabilisierung der Relationsstruktur profitieren. An unserem Beispiel des _Numerus clausus_ sehen wir, dass Akteuren der zweiten Kategorie bessere Zirkulationsmöglichkeiten eingeräumt werden, wenn der Schmetterlingspfad der Relationsstruktur mit Kernsequenz Investition durch eine von politischen Instanzen ausgeübte Stärkung des Schmetterlinspfades der Sequenz Repräsentation destabilisiert wird. Dagegen verlieren die Akteure der ersten Kategorie an Zirkulationsmöglichkeiten, wovon mittelbar die Akteure der dritten Kategorie profitieren, die insbesondere in den Sequenzen der Repräsentation und der Attraktivität zirkulieren. Die Akteure der ersten und der vierten Kategorie profitieren nur wenig von einer solchen Umstellung, selbst wenn sie in der Sequenz Materialität zirkulieren, die in dieser Konfiguration diejenige ist, in der diese Akteurkategorien am wenigsten benachteiligt werden. Deshalb kann mit der Theorie der Relation erklärt werden, dass Maßnahmen zur Demokratisierung des Studiums an der Universität zwar eine Wirkung im Sinne der Unterstützung der Zirkulation von Akteuren haben, deren Zirkulationsmöglichkeiten ohne derartige Maßnahmen eingeschränkt geblieben wären [@Spexard2018, 39]. Jedoch bleibt die Wirkung von solchen Maßnahmen ungleichmäßig und begrenzt, da ein solcher Eingriff von Außen wiederum eigene soziale Ungleichheiten generiert, zu deren Verbreitung insbesondere die Zirkulation der Akteure der zweiten Kategorien in dieser Relationsstruktur beiträgt.

Im Destabilisierungszustand der Relationsstruktur mit Kernsequenz Investition verändert sich ebenfalls die Bedeutung von Leitideen, die die Entwicklung von Tätigkeitsbereichen motiviert, die wiederum solche Leitideen unterstützen. Am verwendeten Beispiel handelt es sich um die Leitideen des akademischen Wissens, der Wissenschaft und der Forschung, die durch die Durchsetzung der Sequenz Repräsentation ebenfalls im Dienst dieser Sequenz umformuliert werden [@Schimank2001, 227]. Solche Leitideen sollen in der Gesellschaft mehr Verbreitung finden und unter Zuhilfenahme solcher Maßnahmen wie der Flexibilisierung des _Numerus clausus_ an der Universität in der Praxis umgesetzt werden soll. Mehr Akteure sollen die Möglichkeit erhalten, mit einem universitären Abschluß in den Arbeitsmarkt einzutreten [@Schimank2001, 225; Munske2014, 37], was jedoch mittelbar gleichsam dazu beiträgt, die Bedeutung der Forschung und der wissenschaftlichen Karriere in den akademischen Bereichen zu relativieren [@Munske2014, 38;@Bourdieu2012a]. Die Flexibilisierung des _Numerus clausus_ verändert also nicht nur die Rekrutierungspolitik an der Universität, sondern mindestens ebenso sehr die Orientierung der Forschungstätigkeiten und die Karrieren des entsprechenden Personals im Sinne eines Mehr an Pragmatismus und Offenheit auf die breite Gesellschaft [@Krücken2001, 334]. Im Mittelbau sollen die Karrieren schneller aufgebaut werden [@Holzer2021, 224], was Wirkung auf die Auswahl von Dissertationsthemen, auf die Arbeit des Personals in Unterstützung von anderen Tätigkeiten an den Lehrstühlen, an denen ein solches Personal tätig wird oder ist, an der Länge der Zirkulation und an ihrer regelmäßige Entwicklung an der Universität zeitigt (ebd., 227). Die Grundlagenforschung wird Schritt für Schritt durch angewandte Forschungsvorhaben sowohl an den Standorten als auch in den Veröffentlichungsorganen der unterschiedlichen Fachbereiche ersetzt [@Lackner2020, 157]. Dies führt zur Schrumpfung, Umstrukturierung oder gar zum Abbau von Bereichen, die Schwierigkeiten haben, mit einer solchen Umorientierung der Leitideen von Universität umzugehen. Instanzen der Relationsstruktur werden somit geschwächt und deren Arbeit teilweise gestört [@Olbertz1998, 26]. Sie verlieren an Macht im Vergleich zu anderen weniger breit angelegten Instanzen, die ihre Arbeit in (Teil)Sequenzen entwickeln (im Fall der Universitäten etwa Fachhochschulen und weitere spezialisierte Hochschulen wie etwa Hochschulen für Pädagogik, für das Ingenieurwesen, für das Verwaltungswesen usw.) [@Reifenberg2021b; @Maier2021; @Stölting2001, 39].

Wenn diese Tendenz weiter voranschreitet, dann kommt die Durchsetzung der Sequenz Repräsentation an ihrer Grenzen bzw. sie fördert mittelbar die Durchsetzung der Sequenz Materialität, deren Instanzen die Repräsentation von Wissen und Wissenschaft in der Breite der Gesellschaft konkreter in den Teilsequenzen dieser Relationsstruktur zu verbreiten behaupten [@Roessler2015]. Eine im Zuge dessen sehr wahrscheinlich einsetzende Schwächung der Sequenz Repräsentation kann tatsächlich zum Vorteil der Durchsetzung der Sequenz Materialität vorkommen, wenn diese letztere Sequenz stärker von einer anderen Relationsstruktur beeinflusst wird. In diesem Fall würde es sich um den Einfluss der Relationsstruktur mit Kernsequenz Materialität handeln. Die Grundlage für die Entwicklung von solchen externen Einflüssen ist bereits gegeben. Am Beispiel des akademischen Lebens denke man beispielsweise an die unterschiedlichen Akteure der Wissenschaft, die dazu bewegt werden bzw. sich veranlasst sehen, in die Wirtschaft in Unterstützung der Forschungsabteilungen von Firmen zu arbeiten, oder an Wissenschaftler:innen, die dabei gefördert werden, eigene Unternehmen (wie etwa Start-ups oder Spin-offs) zu gründen [@Maschwitz2018, 254-255; @Hahn2018, 43-81; @Hesser2017, 4; @Roessler2015,4, 21-26; @Jakszat2014, 4]. Solche Akteure und Instanzen gehen davon aus, dass die Repräsentation von Wissen und der Wissenschaft über die gesamte Gesellschaft hinweg ein Ziel zu verfolgen habe, das in der Konkretisierung dieses Wissens und der Wissenschaft besteht [@Roessler2015, 18-21, 26-36, 38-39]. Nur so könne diese Repräsentation von Wissen und der Wissenschaft zur realen Quelle der Verwirklichungsmacht von Akteuren im Dienst von Wachstum und Wohlstand werden. Die Destabilisierung der Relationsstruktur mit Kernsequenz Investition durch die infiltrierende Dienstbarmachung der Sequenz Repräsentation durch die Politik sowie die Durchsetzung dieser Sequenz gegen die Kernsequenz Investition im universitären Bereich ist dann nur der Anfang von weiteren Destabilisierungen, die aus der Durchsetzung von anderen Sequenzen in dieser Relationsstruktur unter Impuls und Einfluss von Satellisierungsstrategien anderer Relationsstrukturen resultieren würden -- etwa die Durchsetzung der Sequenz Materialität im universitären Betrieb infolge einer verstärkten Einflussnahme durch Instanzen der Wirtschaft, was zur Schwächung erstens der Sequenz Repräsentation zum Vorteil der Sequenz Materialität und zweitens der Satellisierungstrategie der Politik zum Vorteil derjenigen der Wirtschaft führen würde.


## Schlusswort

Eine erste Beobachtung, die gleichmäßig für die Akteure bzw. die Akteurkategorien in den Sequenzen von einer Relationsstruktur und für die gesellschaftlichen Instanzen dieser Relationsstruktur gilt, ist die Wechselbeziehung zwischen der Veränderung von Zirkulationen (und daher von Einschreibungsakten) und der Veränderung des Musters sozialer Ungleichheit. Wie an unserem Beispiel zur Flexibilisierung des _Numerus clausus_ an Universitäten sichtbar wird, führt eine Förderung von Zirkulationen in der Kernsequenz nur eingeschränkt zu einer besseren Zirkulation von weniger privilegierten Akteurkategorien in dieser Sequenz, was auch in eingeschränktem Umfang die gesellschaftlichen Instanzen stärkt, mit denen sich diese Akteurkategorie in Zirkulationen einschreiben. Zudem wirkt eine solche Förderung von Zirkulationen in der Kernsequenz nur eingeschränkt auf die Zirkulation von entsprechend weniger privilegierten Akteurkategorien in den anderen Sequenzen einer Relationsstruktur ein. Dies erklärt sich damit, dass soziale Ungleichheiten nicht abgebaut werden, sondern sich lediglich ein anderes Muster sozialer Ungleichheit durchsetzt und im Zuge dessen das vormals vorherrschende Muster sozialer Ungleichheit schwächt bzw. stört. Etwa wenn die Zirkulation in der Kernsequenz Investition der entsprechenden Relationsstruktur gelockert wird. In diesem Fall profitieren davon vornehmlich die Akteure der zweiten Kategorie in der Kernsequenz Investition und in der nachfolgenden Sequenz Repräsentation. Aber dies geht zum Vorteil der Konsolidierung von Eliten in den zwei weiteren Sequenzen Materialität und, wenn auch in abgeschwächter Form, Attraktivität.

Dadurch wird deutlich, dass die Durchsetzung eines anderen Musters sozialer Ungleichheit aufgrund des Versuchs, soziale Ungleichheiten abzubauen, lediglich die Last der sozialen Ungleichheiten auf die Schultern anderer Akteurkategorien verlagert, die beim Wechsel des Musters sozialer Ungleichheit von solchen Ungleichheiten mehr als zuvor betroffen sind. Wenn man bedenkt, dass eine Destabilisierung des Musters sozialer Ungleichheit die gesellschaftlichen Instanzen schwächt, die für die Stabilität und die Verbreitung einer Realtionsstruktur verantwortlich sind, dann kann hinzugefügt werden, dass die Verschiebung sozialer Ungleichheiten auf andere Akteurkategorien mit der Einschränkung von Einschreibungsakten für alle Akteurkategorien einhergeht, was den vorherrschenden Typus der Reziprozität in einer Relationsstruktur zu Lasten der Zirkulation von allen Akteuren in derselben Relationsstruktur unterminiert. Oder um es an unserem Beispiel festzumachen: Die Lockerung des Zugangs zum universitären Studium hat zwar das Studium demokratisiert. Zugleich hat die Demokratisierung des Zugangs zur Universität aber auch dazu beigetragen, dass die Erfüllung von Eintritts-, Austritts- und Übergangsbedingungen zur Durchsetzung eines anderen Musters sozialer Ungleichheit umdefiniert wurde. Deshalb ist die Zirkulation von Akteuren im Studium und nach dem Studium nicht wesentlich demokratischer geworden, selbst wenn sie anders und nach anderen Leitideen -- in unserem Beispiel nach den Leitideen der Repräsentation von Wissen und der Wissenschaft in der breiten Gesellschaft -- verläuft bzw. verlaufen ist. Was eine solche Demokratisierung bringt, ist dann insbesondere eine Veränderung der Bedeutung von Wissen, der Wissenschaft, des Studiums an der Universität, der Universität selbst und der Akteure, Aktanten und Mediationen, die mit dieser Instanz bzw. den Instanzen des universitären Betriebs verbunden sind.

## Literatur
