---
title: "Stars als Anführer und die Attraktivität der Repräsentation."
indent: true
output:
    html_document: default
csl: chicago-author-date.csl
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

## 1. Einleitung

Bisher haben wir vor allem einen Grundsatz der Theorie der Relation unterstrichen: So sehr man sich auch um ideale Verhältnisse in geradezu allen nur erdenklichen Lebensbereichen bemüht, so sehr kommt es im Kosmos gelebter Sozialität stets und ständig und mithin unausweichlich zu Abweichungen vom Manuskript; sei es von einer idealen Reziprozität, einer idealen Relation oder einer idealen Zirkulation, woraus wiederum die Besonderheiten der Zirkulation von Akteuren resultieren und diese in bestimmten Akteurkategorien platzieren. Dieses grundlegende Faktum der Pluralität und Dynamik des Sozialen spiegelt sich nicht nur in der Auffassung von Reziprozität wider, die für die Theorie der Relation zentral ist und eine neue Perspektive auf das Reziprozitätsverständnis von Marcel Mauss im Anschluss an seine Analysen zur Gabe, zur Nationalisierung und den Genossenschaften erlaubt [vgl. unser Kapitel 2 \ref{Was uns die Reziprozität der Gabe erzählt}]. Dieses grundlegende Faktum spiegelt sich mindestens ebenso sehr in den mannigfaltigen Schwierigkeiten wider, denen sich Kunstschaffende der dritten und vierten Akteurkategorie im Unterschied zu Kunstakteuren der ersten und zweiten Kategorie bei der Entwicklung ihrer Zirkulation in der soziokulturellen Relationsstruktur gegenübersehen und sie mehr oder weniger dazu zwingt, ein Doppelleben zwischen künstlerisch und wirtschaftlich orientierten Tätigkeiten aufzunehmen [vgl. unser Kapitel ref{Das Künstlerleben leben}]. Dies hat, wie wir gesehen haben, nicht nur zur Folge, dass die betreffenden Kunstschaffenden einen Teil ihrer Zeit auf dem Wirtschaftsmarkt einsetzen müssen, um ihren Lebensunterhalt zu sichern. Vielmehr wirkt sich ihr Doppelleben zwischen Kunst und Wirtschaft auch insofern nachteilig bzw. bremsend auf deren weiteres Fortkommen in der soziokulturellen Relationsstruktur aus, als sie ihrer Kunst weder regelmäßig noch kontinuierlich nachgehen können, aufgrund ihrer Position in den unteren beiden Akteurkategorien oftmals nur atomistische Kunstinstanzen erreichen, die ihre Einschreibung im Bereich der Kunst in viele kleine Akte zerlegen, und den Kunstschaffenden die Entwicklung eines ohnehin wenig gebahnten Zirkulationswegs zusätzlich erschweren.

Der Grundsatz der Theorie der Relation, wonach es geradezu zum Status quo gehört, dass es in jedweder Sozialität permanet zu Abweichungen von Skript und von _idealen_ Verhältnissen kommt, beschränkt sich jedoch nicht ausschließlich auf instabile Zirkulationen wenig rennomierter Kunstschaffender im Bereich der Kunst. Er vergegenwärtigt sich auch in der Politik, wo sich Abweichungen von einer _idealen_ Reziprozität im Zuge der Einschreibung von Akteuren in Zirkulationen und Relationsstrukturen ebenso gut beobachten lassen. Auch hier kann es selbstverständlich zu instabilen oder gar oszillierenden Zirkulationen kommen. Es lassen sich in der Politik allerdings auch stabile Zirkulationen von Akteuren beobachten, die zwar keine ausgewiesenen Politikakteure sind, denen es aber nichtsdestotrotz gelungen ist, ausgehend von der Traumfabrik bzw. dem Mediengeschäft in die Politik zu zirkulieren und eine stabile Zirkulation in der Politik zu entwickeln.

In diesem Kapitel sehen wir uns demzufolge genauer an, dass der Wechsel der Relationsstruktur für die Akteure auch ohne die Inkaufnahme von erheblichen Opfern realisiert werden kann, was wiederum wesentlich dazu beiträgt, ihre Zirkulation in der Ankunftsrelationsstruktur zu stabilisieren. Eine stabile Zirkulationsentwicklung von Akteuren infolge des Wechsels der Relationsstruktur ist jedoch keine einzigartige Besonderheit bestimmter Akteure, sondern resultiert auch bei ihnen aus Abweichungen von einer _idealen_ Reziprozität und aus Abweichungen von einer idealen Zirkulation, die sich in stabilen Zirkulationen übersetzen und die Akteure auf die oberen Akteurkategorien verteilen. Diese zwei Grundsätze der Theorie der Relation, sollen in exemplarischer Weise anhand der Zirkulation zweier Protagonisten illustriert werden, deren Zirkulation vom Film- und Fernsehbusiness in die Politik keineswegs eine Ausnahme bildet, sondern vielmehr auf längst gebahnten Zirkulationswegen ihrer Vorgänger verläuft und derer Beispiele es entsprächend viele gäbe.^[Zu nennen wären hier bspw. die US-Präsdienten Ronald Reagon und Donald Trump, der Haitianische Präsident Michael Martelly, die EU-Parlamentsabgeordneten Nana Mouskuri und Martin Sonneborn, die Bayrische Landtagsabgeordnete Barbara Rütting, der Bundestagsabgeordnte Charles M. Huber, die italienische Parlamentsabgeordnete Ilona "Cicciolina" Staller, die US-Delegierte der UN-Vollversammlung Shirley Temple, der US-Senator Fred Thomson sowie Clint Eastwood, Vicky Leandros und Sonny Bono, die ein Bürgermeisteramt inne hatten.] Die Rede ist von Arnold Schwarzenegger einerseits und Wolodymyr Selenskj andererseits.

Das Anliegen dieses Kapitels besteht also nicht etwa darin, einen Sonderfall der Zirkulation von Akteuren zu beleuchten. Vielmehr gilt es, einen Normalfall der Zirkulation von Akteuren am Beispiel Arnold Schwarzeneggers und Wolodymyr Selenskyjs ins Zentrum zu rücken, der im Wechsel der Relationsstruktur besteht und von Akteuren ausgeführt wird, denen diese Zirkulationsmöglichkeit, anders als den Akteuren der zweiten und dritten Akteurkategorien, unmittelbar zur Verfügung steht, weil sie sich in ihrer Relationsstruktur in der ersten Akteurkategorie befinden und zur Gruppe der Puristen der Relationsstruktur gehören (im Folgenden werden wir aus Gründen der besseren Lesbarkeit von Relationspuristen sprechen) [vgl. @PappilloudSchultze2022, 142]. Diese Ausgangsposition in der ersten Akteurkategorie stellt jedoch, wie bereits betont wurde, keineswegs eine hinreichende Bedingung für den Wechsel der Relationsstruktur dar. Sie zeugt zunächst einmal lediglich davon, dass Schwarzenegger und Selenskyj als Akteure der ersten Kategorie, ebenso wie Akteure der vierten Kategorie, stärker von den morphologischen Determinanten einer Relationsstruktur betroffen sind, als von den strukturellen Determinanten (ebd., 135), weshalb ihnen diese Zirkulationsmöglichkeit wie selbstverständlich offen steht. Selbst wenn jedoch die Zirkulation in eine andere Relationsstruktur eine selbstverständlich Zirkulationsmöglichkeit für Akteure wie Schwarzenegger und Selenskyj darstellt, die obendrein kaum Opfer verlangt, heißt das noch lange nicht, dass diese Zirkulationsmöglichkeit auch tatsächlich ergriffen wird. Für die Umstellung der Position zwischen zwei Relationsstrukturen ist deshalb ein bestimmter Widerstand aufseiten der Akteure elementar, der sie daran hindert, sich erneut in ihre Ausgangsrelationsstruktur mit ihren üblichen oder neuen gesellschaftlichen Instanzen einzuschreiben und darin weiter von Sequenz zu Sequenz zu zirkulieren (vgl. ebd., 180ff.). Anders formuliert, wäre es sowohl für Schwarzenegger als auch Selenskyj ein Leichtes gewesen, nachdem _Terminator 3_ im Juli 2003 als Nummer eins an den Kinokassen angelaufen war [@Schwarzenegger2014, 514] bzw. die Ausstrahlung der dritten Staffel der Fernsehserie _Diener des Volkes_ eine Woche vor der ersten Runde der Präsidentschaftswahlen in der Ukranie geplant war [vgl. @Iwan2019], sich einem neuen Film- oder Fernsehprojekt zuzuwenden. Dazu kam es jedoch bei beiden Protagonisten nicht, was nicht daran gelegen hat, dass Schwarzenegger keine neuen Rollen angeboten bekommen hätte oder Selenskyj und das Team der Produktionsfirma _Kwartal 95_ keine neuen Ideen für Spielfilme oder Serien entwickelt hätten. Es kam also bei diesen beiden Stars nicht zur Wiederaufnahme von Tätigkeiten in der medialen Relationsstruktur, weil ihr Wunsch, in die Politik zu gehen, um dort -- in Erwartung der Stabilisierung ihre Position in der politischen Relationsstruktur -- wirklich etwas für die Ukrainer zu verändern (Selenskyj) oder um an etwas zu arbeiten, was wichtiger als der Einzelne ist (Schwarzenegger), größer und stärker war. In einer derart gelagerten Erwartung und Erwartung auf Erwartungen spiegelt sich einerseits ein unabdingbarer Widerstand _für_ die Kernsequenz der politischen Relationsstruktur wider, die in der Repräsentation von Kollektiven besteht und am Beispiel Selenskyjs und Schwarzeneggers in dem Bedürfnis nach der Repräsentation der Ukrainer bzw. der Kalifornier kristallin wird. Solche Erwartungen und Erwartungen auf Erwartungen spiegeln jedoch auch andererseits einen geradezu unausweichlichen Widerstand _gegen_ die Kernsequenz Attraktivität der medialen Relationsstruktur wider, worin alle Tätigkeiten und Tätigkeitsentwicklungen ausschließlich im Dienst der Attraktivität von Einzelakteuren als Stars, als Entertainer, als Kaberettist, als Jounalisten etc. ausgeübt werden und Akteure entsprechend nicht die Rolle zukommt, als Repräsentant einer sozialen Gruppe bzw. der Bevölkerung einer Nation oder eines Landes zu fungieren. Diese spannungsreiche Parallelität von Widerstand _für_ und _gegen_ lässt sich am Beispiel Schwarzeneggers gut verdeutlichen. So sagt er von seinem Wechsel von der Traumfabrik in die Politik retrospektiv, dass ihm einerseits "die Schauspielerei [...] zum Hals raus[hängt]" und er an etwas arbeiten wolle, das größer und wichtiger war als er selbst [@Schwarzenegger2014, 517, 513]. Andererseits sei ihm aber ebenso glasklar gewesen, dass er allen Menschen [im Bundesstaat Kalifornien; CP & EMS] dienen wolle [@Schwarzenegger2023c], es an der Zeit sei, den amtierenden Gouverneur "Gray Davis zu terminieren" und er zur Abwechslung mal das Volk vertreten wolle [Schwarzenegger zit. nach @Newman2003].

Daraus spricht gleichsam, dass sich Akteure, die einen Wechsel der Relationsstruktur anstreben und/oder realisieren, sich nicht mehr als unabdingbares Element ihrer Relationsstruktur empfinden und aus der Position eines Relationspuristen der ersten Akteurkategorie auch nicht mehr an der Verbreitung ihrer Relationsstruktur mitwirken möchten, sondern die Sequenz Repräsentation, d. h. die Repräsentation eines Kollektivs, in gewisser Weise verabsolutieren. Die Folge einer solchen Verabsolutierung ist, dass die entsprechenden Akteure ihre Relationsstruktur, in der diejenige Sequenz, für die sie am meisten brennen bzw. die sie verabsolutieren, nicht die Kernsequenz darstellt, für diejenige Relationsstruktur verlassen, in der diese Sequenz die Kernsequenz bildet und entsprechend alle Tätigkeiten und alle Tätigkeitsbereiche im Dienste eben jener Sequenz ausgeführt werden. Es ist also das Ziel solcher Akteure, zum unabdingbaren Element ihrer Ankunftsrelationsstruktur zu werden, dort abermals in die Position eines Relationspuristen zu zirkulieren und von dort aus an der Verbreitung ihrer neuen Relationsstruktur, im Falle Schwarzeneggers und Selenskyjs in der politischen Relationsstruktur, teilzuhaben und teilzunehmen [vgl. @PapilloudSchultze2022, 150-161]. Ein solcher Wechsel der Relationsstruktur bzw. die Zirkulation vom Film- und Fersehbusiness in die Politik verlangt allerdings nicht nur einen geeigneten Widerstand aufseiten der Akteure, sondern auch die Realisierung von Einschreibungsakten mit Instanzen der Ankunftsrelationsstruktur (ebd., 180-192). Dies wiederum setzt voraus, das diese Instanzen der Vermittlung auch tatsächlich vorhanden und für die Akteure erreichbar sind, was im Falle Schwarzeneggers und Selenskyjs bedeutet, dass sie politische Instanzen finden oder im Zweifelsfalle selbst gründen müssen (zum Aufbau von Instanzen vgl. ebd., 212-219), die dann derartige Einschreibungsakte fördern und dabei helfen, aus Stars Anführern zu machen (vgl. Abb. 9.1 in ebd., 374). Bis hierher lässt sich also zum einen festhalten, dass auch der Wechsel der Realationsstruktur durch Relationspuristen der ersten Akteurkategorie, wie auch bei den wenig rennomierten Kunstschaffenden aus Kapitel 3 vom Trias Einschreibung, Widerstand und Reziprozität abhängt. Zum anderen lässt sich aber ebenso sehr festhalten, dass wir es, so der Realationsstrukturwechsel aus dem unbedingten Widerstand _für_ eine bestimmte Sequenz resutiert, die in der Ankunftsrelationsstruktur die Kernsequenz bildet, wie dies auch bei Schwarzenegger und Selenskyj der Fall ist, mit einer aufsteigenden Zirkulation zu tun haben, die einer transversalen Mobilität entspricht. 

Ehe wir uns nun jedoch auf jenes Trias und mithin die Stufen der transversalen Mobilität unserer Relationspuristen Schwarzenegger und Selenskyj konzentrieren, wenden wir uns zuerst der soziologischen Mobilitätsforschung zu.  und stellen die Frage, welche Konzepte von den Vertretern dieses festen Markenkerns soziologischer Forschung angeboten werden, um die von unseren Protagonisten realisierte soziale Mobilität zwischen Kulturindustrie und Politik zu messen und zu erklären. Dabei wird uns besonders die Frage beschäftigen, auf welche Weise die "onthologischen Prämissen" dieser Konzepte [@Abbott2020, 80, Fn. 10; vgl. auch ebd., 84] die Erkenntnishorizonte zur sozialen Mobilität unserer beiden Protagonisten determinieren und darüber gleichsam eine bestimmte Auffassung von sozialer Mobilität unterstützen.^[Diese Frage ist deshalb von Relevanz, da die Forschung zur sozialen Mobilität Aufschluss darüber geben soll, inwiefern Gesellschaften dem Prinzip der Chancengleichheit und der Durchlässigkeit von Klassengrenzen bzw. Strukturen sozialer Schichtung Rechnung tragen [@Iversen2021, 2; @Nennstiel2021, 1; @Song2020, 251; @Javis2017, 2; @Leeuwen2010, 429]. Das heißt wiederum, dass es sich bei sozialer Mobilität um ein abgeleitetes Forschungsprogramm handelt, da es schier unmöglich ist, Positionsumstellungen von Individuen oder sozialen Gruppen in und zwischen den klassen- oder schichtspezifischen Strukturen einer Gesellschaft zu erfassen, ohne diese zuvor in Klassen oder Status- und Berufsgruppen untergliedert zu haben [vgl. @Nobel1979, 483; vgl. auch @Goldthorpe1992, 28-29; @Yaish2020, 1].]

## 2. Die zwei paradigmatischen Ansätze sozialer Mobilitätsforschung  

Obgleich für die Mobilitätsforschung, und zwar trotz ihrer langen Tradition [@Sorokin1959; @Blau1967; @Treiman1977, @Featherman1978; @Ganzeboom1992; @Erikson1992], "konzeptionelle Fragen weitaus weniger wichtig [waren]" [@Sørensen1977, 965], konstatieren Erikson und Goldthorpe, dass es eine regelrechte Fülle von "verschiedenen konzeptionellen Kontexte[n]" gibt, "in denen die Untersuchung der sozialen Mobilität durchgeführt" wird [@Erikson1992, 28].^[Diese Pluralität geht auf "eine Reihe unterschiedlicher und oft gegensätzlicher Interessen, sowohl sozialpolitischer als auch wissenschaftlicher Art" aufseiten der Forschenden zurück [@Erikson1992, 29; vgl. auch @Goldthorpe1987, 2-29], resultiert aber auch aus dem "Fortbestehen großer Unstimmigkeiten in wesentlichen empirischen Fragen" und "methodischen Schwierigkeiten" (ebd., 28), wodurch der "Entwicklung von Indizes [...] große Aufmerksamkeit gewidmet [wurde]" [@Sørensen1977, 965; vgl. auch @Duncan1966; @Treiman1975; @Featherman1988].] Angesicht einer solchen konzeptionellen Diversität schlagen Erikson und Goldthorpe daher eine Systemematisierung entlang zweier Haupttendenzen vor: "eine, in der Mobilität als innerhalb einer Klassenstruktur stattfindend betrachtet wird" und eine andere, in der sie als innerhalb einer Form von sozialer Hierarchie stattfindend betrachtet wird" [@Erikson1992, 29]. Entsprechend gestaltet sich auch die Definition sozialer Mobilität. Im ersten Falle versteht sich soziale Mobilität auf "die Bewebung von Individuen zwischen _sozialen Positionen_, die anhand von Beziehungen innerhalb von Arbeitsmärkten und Produktionseinheiten identifiziert werden" (ebd.). Im zweiten bezeichnet soziale Mobilität dagegen "die Bewegung von Individuen zwischen _sozialen Gruppierungen oder Aggregaten_", die "nach Kriterien wie [beruflichem; CP & EMS] Prestige, [sozio-ökonomischem; CP & EMS] Status" oder "wirtschaftlichen Ressourcen [...] ihrer Mitglieder geordnet sind" (ebd.). Wir beginnen unsere Betrachtung mit den klassenstrukturellen Kontexten am Beispiel des EGP-Klassenshema und verorten darin anschließend die Mobilität Schwarzeneggers und Selenskyjs vom Showbusiness in die Politik. 

## 2.1 Soziale Mobilität in klassenstrukturellen Kontexten und das EGP-Klassenschema

Zentrum der nach Klassenstrukturen verfahrenden Mobilitätsforschung bildet die "Mobilität im Sinne relationaler Veränderungen" [...] der Einbindung des Einzelnen in die Beziehungen innerhalb von Arbeitsmärkten und Produktionseinheiten", wobei sich derartige ,Veränderungen’ nicht nahtlos als "Auf- und Abstiege interpretieren lassen" (ebd., 31). Entsprechend interessiert sich jedweder Klassenansatz zwar auch für vertikale und horizontale Mobilität, diese ist jedoch nicht ausschließlich das Produkt individueller (Miss)Erfolge. Vielmehr wird angenommen, dass sich Klassen und Klassenfraktionen durch eine gewisse Homogenität hinsichtlich der Verfügung über (Kapital)Ressourcen, ihre "Exposition gegenüber strukturellen Veränderungen" und hinsichtlich ihrer klassenspezifischen Interessen auszeichnen (ebd., 31f.).^[An dieser Stelle sei darauf verwiesen, dass diese Homogenitätsannahme auf die wesentlichen Elemente von Klassenkonzeptionen beruht und somit hinter der Kompelxität bspw. des Sozialraummodells von Bourdieu [@Bourdieu2012a] oder der Konzeption der Klassenlage nach Weber [@Weber1980,177-180] zurückbleibt, wenngleich jeder Klassenansatz seine eigenen strukturell-konzeptionellen Schwächen aufweist [vgl. @Wright1979].] Damit ist es prinzipiell möglich, sowohl die aus unterschiedlichen Klassenpositionen resultierende soziale Ungleichheit als auch die sich in jenen Positionen widerspiegelnden "strukturelle[n] Aspekte der wirtschaftlichen Entwicklung" in die Analyse von Chancen, Raten und Mustern sozialer Mobilität zu integrieren (ebd., 32). Entsprechend interessiert im Klassenkontext weniger, ob Positionsumstellungen "aufwärts oder abwärts gerichtet" sind, sondern vielmehr die "Arten von Gewinnen und Verlusten", die mit Positionswechseln einhergehen (ebd., 33).^[So kann ein Wechsel der Klassenposition zwar "ein höheres Einkommen und kürzere Arbeitszeiten" bedeuten, zugleich kann er aber auch mit einer "Entwertung [...] erworbener Fähigkeiten" und "kultureller und sozialer Verarmung" zusammenfallen (ebd., 33).] Der wohl populärste Klassenstruktur-Kontext, der in der sozialen Mobilität Anwendung findet [vgl. @Braun2000], ist das von _E_rikson, _G_oldthorpe und _P_ortocarero entwickelte EGP-Klassenschema. Diesem in seiner Sieben-Klassen-Version wollen wir uns nun dezidiert zuwenden, um zu sehen, welche Perspektiven es uns auf die von Schwarzenegger und Selenskyj realisierte Positionsumstellung vom kommerziellen Show-, TV- und Filmbusiness in die Politik eröffnet. Zunächst aber ein paar Worte zum Aufbau des Klassenschemas selbst.

Das EGP-Klassenschema zielt grundsätzlich auf eine Klassendifferenzierung ab, in der Positionen in Relation zu Arbeitsmärkten und Produktionseinheiten "im Hinblick auf die [Regulierung der; CP & EMS] Beschäftigungsverhältnisse" klassifiziert (ebd., 37) und mithin "Personen in ähnlichen Markt- und Arbeitssituationen" elektisch zusammengefasst sind (ebd., Fn. 9).^[Diese Klassenkategorisierung ist von der Annahme getragen, "die wichtigsten Merkmale der Mobilität unter den Bevölkerungen moderner Industriegesellschaften darzustellen" (@Erikson1992, 35].] Insofern verstehen Erikson und Goldthorpe also die soziale Klassenzugehörigkeit von Personen bzw. von Haushalten als Produkt ihrer Marktlage und ihrer Beschäftigungsverhältnisse. Auf Basis dieser Unterscheidung ergibt sich die primäre Drei-Teilung von Beschäftigten-Hauptklassen nach erstens _Arbeitgebern_, zweitens _Selbstständigen_ und drittens _Arbeitnehmern (ebd., 37, 40). Diese drei Hauptklassen gliedern sich ferner in Fraktionen von Beschäftigten, wobei für unsere Zwecke vor allem die Klasse der Arbeitgeber und die der Arbeitnehmer von Relevanz ist.^[Der Vollständigkeit halber sei angemerkt, dass die Klasse der Selbstständigen aus den Kleingewerbetreibenden ohne Beschäftigte (IVb) und andere Selbstständige in der Primärproduktion (IVc) besteht (ebd., 40).] So gliedert sich die Klasse der Arbeitgeber zum einen in Großunternehmer und führende Industrielle, d. h. in die Klasse der "größeren Eigentümer" (I), und zum anderen in die Kleingewerbetreibenden (IVa + IVc), d. h. in die Klasse der kleineren Eigentümer (vgl. ebd., 40; vgl. auch Fig. 2.1 ebd., 36, 38-39).^[Tragend für diese Unterklassifizierung ist das Merkmal der Unternehmensgröße und die tatsächlich ausgeübten Funktionen (ebd., 40).] Für die Klasse der Arbeitnehmer richtet sich die Differenzierung demgegenüber nach der konkreten Art der Regulierung des Beschäftigungsverhältnisses, woraus die Unterscheidung zwischen Arbeitnehmern mit klassischem Arbeitvertrag und Arbeitnehmern im Dienstverhältnis gewonnen wird (ebd. 41-42). Die im Dienstverhältnis beschäftigten Arbeitnehmer untergliedern sich entsprechend in Fachkräfte, Verwaltungsangestellte und Beamte, die entweder im höheren Dienst (I) oder im unterem Dienst (II) tätig sind (vgl. Fig. 2.1 ebd., 36, 38-39). Sie bilden zusammen die "Dienstklasse" bestehend aus Beamten und Kadern (ebd., 42), wobei insb. die Mitglieder der obersten Dienstklasse (I) gemeinsam mit den größeren Eigentümern (I) an der Spitze des EPG-Klassenschemas stehen. In der Arbeitnehmerklasse mit klassischem Arbeitsvertrag, die der Lohnarbeiterklasse nahe kommt, werden die manuell arbeitenden Facharbeiter des Handwerks (VI) sowie die einfachen manuellen Arbeiter in Industrie und Landwirtschaft (VIIa + VIIb) unterschieden (vgl. Fig. 2.1 in ebd., 36, 38-39). Zwischen der idealtypischen Atbeitssituation der Dienst- und Arbeiterklasse werden im EGP-Schema schließich die Arbeitnehmer im Angestelltenverhältnis platziert (vgl. ebd.), in der wiederum routinierte, nicht-manuell Beschäftigte des höheren und unteren Dienstes (IIIa + IIIb) und Techniker der unteren Ebene (V) platiert werden werden (ebd.).

## 2.1.1 Schwarzeneggers und Selenskyjs Wechsel in die Politik am Beispiel des EGP-Klassenschemas

Wenn wir nun danach fragen, welche Erkenntnisse das EGP-Schema bzgl. der Zirkulation Schwarzeneggers und Selenskyjs aus dem Show-, TV- und Filmgeschäft in die Politik liefert, gilt es zunächst die Klassenpositionen zu bestimmen, zwischen denen Schwarzenegger und Selenskyj zirkuliert sind. Dahingehend lässt sich konstatieren, dass beide Protagonisten sowohl während ihrer Erwerbstätigkeit im Show-, TV- und Filmbusiness als auch in Bezug auf die Ausübung ihrer entsprechenden Ämter der oberen Dienstklasse (I) zuzuordnen sind. Während bei den Exekutivämtern, die Schwarzenegger und Selenskyj in der Zielposition bekleidet haben bzw. bekleiden, die Klassenzuordnung unumstritten ist, bedarf die Einordnung ihrer Tätigkeit im Schauspiel-, Kabarett- und Produktionsgewerbe zur Dienstklasse I näherer Erläuterung.^[Bei dieser Eingruppierung orientieren wir uns an Friedman und Laurison, die in ihrer kürzlich erschienen Monographie _The Class Ceiling_  explizit die sozialen Mobilität von Erwerbstätigen in Kultur- und Kreativberufen auf Basis des EGP-Klassenschemas untersuchen [vgl. @Friedman2019].] So kann als erstes gesagt werden, dass Schwarzenegger und Selenskyj als "Film- und Fernsehschaffende" aufgrund ihrer unzähligen Zirkulationen von Film- und TV-Projekt zu Film- und TV-Projekt zweifellos die obersten "Ränge" des Show-, TV- und Filmbusiness erreicht haben [@Friedman2019, 266], wobei das, was Friedman als 'oberste Ränge' bezeichnet, in der Theorie der Relation den Relationspuristen entspricht, die sich an der Spitze der ersten Akteurkategorie in jeder Sequenz, unabhängig von ihrer Relationsstruktur, befinden. Von dort aus haben jene Akteure, so Friedman und Laurison weiter, "einen unverhältnismäßigen Zugang zu genau der Art von ,Schlüsselpositionen’", die gemeinhin mit der Elite assoziiert sind (ebd.), ohne eine Erklärung für dieses Phänomen des ,unverhältnismäßigen Zugangs zu Schlüsselpositionen’ zu liefern. In der Theorie der Relation erklärt sich dies damit, dass die Relationspuristen stärker den morphologischen als den strukturellen Determinanten ihrer Relationsstruktur unterliegen, weshalb _Relations_puristen relativ unkompliziert die _Relation_ durch Position wechseln und, so ihnen die doppelte Einschreibung in der Ankunftsrelationsstruktur gelingt, nahezu ungehindert von ,Spitzenposition’ zu ,Spitzenposition’ zirkulieren können. Abgesehen davon spricht für die Zuordnung Schwarzeneggers und Selenskyjs Tätigkeit in der Kulturindustrie zur obersten Dienstklasse I, dass sie als Führungskräfte in der Kultur- und Kreativwirtschaft "einen bedeutenden Einfluss auf das öffentliche Leben aus[üben] und [...] eine zentrale Rolle bei der Gestaltung der kulturellen Identität der Nation durch Film, Medien und darstellende Künste [spielen]" (ebd.). Und schließlich ist ebenso zu berücksichtigen, dass beide Protagonisten entlang ihrer Zirkulation von einem zum nächsten Film- und TV-Projekt in der kommerziellen Kultur- und Kreativwirtschaft ein sehr hohes Einkommen erzielt haben.^[Friedman und Laurison bringen ferner zwei weitere Argumente an, die die Zuordnung von ’Film- und Fernsehschaffenden’ zu den Eliteberufen unterstützen. So gehören jene Berufsgruppen der Kultur- und Kreativwirtschaft nicht nur "zu den wettbewerbsintensivsten aller [...] Eliteberufe", sondern diese sind zudem "sehr begehrt, da sie Kreativität, Selbstdarstellung und Glamour versprechen" [@Friedman2019, 266].] 

Mit Blick auf diese Einordnung der Positionsumstellung, die sowohl von Schwarzenegger als auch von Selenskyj zwischen der Kulturindustrie einerseits und der Politik andererseits realisiert wurde, lässt sich auf Basis des EGP-Klassenschemas Folgendes hervorheben: Zunächst einmal ist festzustellen, dass die Zirkulation unserer beiden Protagonisten mittels des EGP-Schemas als soziale Mobilität von einer Führungsposition zu einer anderen Führungsposition zu verstehen ist, d. h. als eine Positionsumstellung innerhalb der obersten Dienstklasse der Führungskräfte, Verwaltungsangestellten und Beamten. Entsprechend ist festzustellen, dass diese Bewegung entweder für das EGP-Klassenschema vollständig unsichtbar bleibt und folglich nicht mit dem Klassenstrukturkontext des EGP-Schemas adäquat erfasst werden kann, oder diese Positionsumstellung -- so das Einsatzgebiet bzw. der Markt der Erwerbstätigkeit in der Analyse der obersten Dienstklasse Berücksichtigung findet -- als horizontale Mobilität zwischen äqiuvalenten Führungspositionen verstanden werden würde. Ersterer Lesart würde also die soziale Mobilität von Schwarzenegger und Selenskyj zwischen zwei Märkten entgehen, während letzterer der Auffassung Vorschub leistet, als ob es lediglich einen marginalen Unterschied zwischen dem Bekleiden des Gouverneuramtes bzw. des Präsidentschaftsamtes und den Tätigkeiten, Verantwortlichkeiten und Einflussnahmemöglichkeiten einer Führungskraft im medialen Show-, Film- und TV-Gewerbe gäbe. Das heißt wiederum, dass sich klassenstrukturelle Kontexte im Allgemeinen und das EGP-Schema im Besonderen zur Untersuchung der sozialen Mobilität von Schwarzenegger und Selenskyj als eher ungeeignet erweisen, wenn die Positionsumstellung dieser beiden Protagonisten innerhalb der oberen Dienstklasse weder als Wechsel der Beziehung zum Arbeitsmarkt noch als Regulationsveränderung der Beschäftigung bestimmt wird. Das EGP-Schema bietet somit für unsere Zwecke eine eher unzureichende Erklärungsgrundlage, zumal unklar ist, wie mit der doppelten Verankerung der oberen Dienstklasse I sowohl in der Klasse der Arbeitgeber als auch in der Klasse der Arbeitnehmer umzugehen ist. Diesbezüglich wäre für unsere beiden Protagonisten herauszustellen, dass sie nicht nur der Arbeitnehmer-Klasse I angehören, sondern parallel dazu auch der Arbeitgeber-Klasse I bzw. der Klasse der größeren Eigentümer und zwar sowohl vor als auch nach ihrer Zirkulation in die Politik.^[Für die Einstufung zur Arbeitnehmerklasse I spricht ein vertragsrechtliches Argument, das von Schwarzenegger vorgebracht wird. So konnte er bspw. weder zu den Vorwahlen noch zur regulären Gouverneurswahl im November 2002 gegen den amtierenden Gouverneur Gray Davis antreten, weil die Zeit des Wahlkampfes mit den Dreharbeiten zu _Terminator 3_ kollidiert sind, zu denen er sich vertraglich verpflichtet hat und mit Millionen schweren Klagen im Falle einer Vertragsverletzung hätte rechnen müssen, wie sein Produzent Andrew G. Vajna ihm gegenüber einräumt [@Schwarzenegger2014, 493f.; vgl auch @Schwarzenegger2023c]. Selbstredend ist Schwarzenegger schlussendlich trotzdem Gouverneur von Kalifornien geworden und zwar weil Mitte des Jahres 2003 einem Bürgerbegehren zur Amtsenthebung (Recall) von Gouverneur Gray Davis stattgegeben wurde [@Mathews2003, vgl. auch @Schwarzenegger2014, 504]. Abseits derartiger abhängiger Beschäftigungsverhältnisse können Schwarzenegger und Selenskyj jedoch auch plausibel der Klasse der größeren Eigentümer (I) in der Arbeitgeber-Klasse zugeordnet werden, auch wenn sie darin eher als "abnormales Element", um nicht zu sagen als absolute "Ausnahmefälle" behandelt werden [@Erikson1992, 40], da es sich bei ihnen um Großeigentümer bzw. Großunternehmer handelt, die sich vor allem durch den Besitz von Restaurants, Geschäften etc. (Schwarzenegger) oder des Produktionsunternehmens _Studio Kwartal 95_ (Selenskyj) auszeichnen (ebd.). So ist Schwarzenegger auf der Grundlage seiner exorbitanten Gagen in Investment-Geschäfte bspw. in Immobilien, in Einkaufszentren, einen Weinberg, ins Flugzeugleasing oder den Investmentfond _Dimensional Fund Advisers_  involviert [vgl. @Schwarzenegger2014, 442, 444-447], wobei er für die Betreuung dieser Geschäfte den Finanzberater Paul Wachter beschäftigt (ebd., 443). Daneben betreibt Schwarzenegger aber auch seit seiner Zeit als Bodybuilder den Versandhandel _Fitness Production Inc._ [vgl. @Pott2024], wofür er ebenfalls mindestens eine Mitarbeiterin abhängig beschäftigt [@Schwarzenegger2014, 443]. Fittness Production Inc. fungiert zudem als Eigentümer einer Reihe von Marken- und Workmarkenrechten, die einerseits an seine Bodybuilding-Karriere und andererseits an seine Rolle als Terminator angelehnt sind, darunter auch die Wahlkampfwortmarke _Governator_ [@Pott2024]. Und schließlich ist Schwarzenegger (Mit)Veranstalter des jährlichen Arnold Sports Festivals, der weltgrößten Fitness Messe, wofür er einen eigenen Ticketvertrieb im Netz betreibt [vgl. URL: https://www.arnoldsports.com/] und dem der Versandhandel Official Arnold Classic Merchandise angegliedert ist [vgl. URL: https://arnoldshop.com/s]. Ähnlich gestaltet sich die Klassenfrage bei Selenskyj. So ist er vor seiner Präsidentschaft nicht nur der populärste Kabarettist und Schauspieler der Ukraine, sondern gleichzeitig auch als Drehbuchautor, als Ideengeber und als Produzent tätig und zwar sowohl im Kontext seiner Produktionsfirma für Film- und Fernsehunterhaltung _Studio Kwartal 95_ [vgl. URL: https://kvartal95.com/en/about-kvartal/] als auch für die 1+1 Mediaholding des Oligarchen Ihor Kolomojskyj [vgl. @Nelles2019]. Zugleich ist Selenskyj aber auch Miteigentümer und Geschäftsführer der Rundfunkproduktionsanstalt _Studio Kwartal 95_, an der er -- wie seine Miteigentümer Borys und Serhij Shefir sowie Andrij Jakowlew auch -- mit 25 Prozent beteiligt ist [@Durot2022; @Trub2021]. Ferner geht aus den sogenannten Pandora-Papers hervor, dass Selenskyj und seine Kwartal-Miteigentümer um ihre Fernsehproduktionsfirma mindestens seit 2012 ein kompliziertes Geflecht aus über zehn Offshore-Firmen auf den Jungferninseln, Zypern und in Belize aufgebaut haben [vgl. @OCCRP2021; @Trub2021; @Lysenko2021]. Im Zentrum dieses Briefkastenfirmen-Geflechts steht die _Maltex Mul­ti­ca­pi­tal Corp._, die ebenfalls zu je 25 Prozent den Gebrüder Shefir, Jakowlew und Selenskyj gehören, wobei die Anteile Selenskyjs und seiner Frau Olena über die Firma _Film Heritage_ liefen [@OCCRP2021; @Trub2021] und kurz vor dem ersten Präsidentschaftswahlgang im März 2019 einer Firma ihres Miteigentümer Sergij Shefir übertragen wurden [@Lysenko2021; @OCCRP2021]. Dieses Übertragungsgeschäft wurde aufgrund des Timings und der Tatsache, dass Selenkyjs Anteile an Maltex nicht in seiner Einkommensdeklaration aus dem Jahr 2020, 2019, 2018 und 2017 angegeben wurden sowie Maltex weiterhin jährliche Dividenden an Selenskyjs Ehefrau bzw. an _Film Heritage_ ausschüttet, "als Versuch Selenskijs gedeutet, vor der Präsidentschaftswahl veröffentlichungspflichtige Vermögenswerte zu verschleiern" [@Lysenko2021; vgl. auch @OCCRP2021; @Ukrin2019a; @Ukrin2019b; @Ukrin2021]. Zudem ist den Einkommensdeklarationen Selenskyjs zu entnehmen, dass er eine Reihe von Immobilien in der Ukraine und Italien besitzt und im Aktiengeschäft tätig ist [@Ukrin2019a; @Ukrin2019b; @Ukrin2021]. Insofern sind also Schwarzenegger und Selenskyj nicht nur der obersten Dienstklasse in der Arbeitnehmerklasse zu verorten, sondern gleichzeitig auch der Klasse I der größeren Eigentümer in der Arbeitgeberklasse.] Wir wenden uns daher jetzt den hierarchischen Kontexten der sozialen Mobilitätsforschung zu, um zu fragen, welche Erkenntnisse uns diese und zwar in exemplarischer Form anhand des von Ganzeboom und Kolelgen entwickelten _International Socio-Economic Index of Occupational Status_ für die Analyse der Zirkulation Schwarzeneggers und Selenskyjs von der Kulturindustrie in die Politik liefern können.

## 2.2 Soziale Mobilität in hierarchischen Kontexten und der internationale sozio-ökonomische Index des beruflichen Status (ISEI-08)  

Wie bereits erwähnt, beruht die nach hierarchischen bzw. kontinuierlichen Kontexten [@Ganzeboom1992, 3ff.] verfahrenden Mobilitätsforschung auf den drei Kriterien _Berufsprestige_, _sozio-ökonomischer Berufsstatus_ und _Einkommen_ [vgl. @Erikson1992, 29]. Folglich bezeichnet soziale Mobilität hier die Positionsumstellung von Individuen zwischen hierarchisch gegliederten Aggregaten innerhalb entweder eines gesamtgesellschaftlichen Prestige- oder Statusgruppengefüges oder aber innerhalb eines durch Einkommen strukturierten Gesellschaftsgefüges.^[Die Analyse der Einkommensmobilität, bei der angenommen wird, dass "die Schichtzugehörigkeit mit der Entwicklung des Einkommens [...] zusammenhängt" [@Yaish2020, 1] und soziale Mobilität über die einkommensspezifische Ressourcenausstattung von Individuen vermittelt wird, findet vor allem in der Wirtschaftswissenschaften Anwendung (ebd., 2, vgl. auch @Mazumder2005).] Weiterführend werden wir uns auf die Prestige- und Statusmobilität konzentrieren, da in der Soziologie die Auffassung geteilt wird, dass die Analyse beruflicher Mobilität entlang der Zusammenfassung von Berufen zu Prestige- oder Statusgruppen auf Basis von Skalen, der Untersuchung von Einkommensmobilität vorzuziehen sei [@Goldthorpe2006, 129; vgl. auch @Featherman1978; @Breen2005]. Entsprechend ist für berufliche Prestige- bzw. Statusmobilität die Annahme tragend, dass jede Berufsposition mit einem bestimmten gesellschaftlich zugeschriebenen Ansehen [vgl. @Hoffmeyer2003, 125; @Treiman1975; @Treiman1977; @Ganzeboom2003, 162] bzw. mit einem bestimmten sozio-ökonomischen Status [vgl. @Duncan1961; @Blau1967; @Featherman1975; @Ganzeboom1992; @Ganzeboom1996] verbunden ist. Auf dieser Grundlage wird soziale Mobilität also als Umstellung oder Erhalt der Berufsposition von Individuen innerhalb eines sozialen Prestige- bzw- Statusgefüges erschlossen.^[Die parallele Betrachtung von Prestige- und Statusmobilität rechtfertigt sich damit, dass die Untersuchung von Statusmobilität laut Duncan zu Anfang dem Ziel verpflichtet war [vgl. @Duncan1961], "Prestigewerte für alle Berufe zu verallgemeinern" [@Ganzeboom2003, 162], allerdings ohne diese auf gesamtgesellschaftlichen Zuschreibungen zu fundieren [vgl. @Ganzeboom 1992]. Somit erfolgt die Bestimmung des Status nach wie vor über eine "nach ihrem Prestige geordnete Liste von Berufen" [@Hoffmeyer2003, 125].] Daran ist gleichsam ersichtlich, dass in hierarchischen Kontexten sozialer Mobilität dem Indikator _Beruf_ eine prioritäre Bedeutung zukommt, die zunächst auf der Einsicht beruht, "dass die Arbeitsteilung der Kern sozialer Ungleichheit ist" [erste Überlegungen hierzu vgl. @Durkheim1983, 273-290]. Infolgedessen begann die Stratifikations- und Mobilitätsforschung damit, "aus Informationen über Berufe Maße für den sozialen Status [und das soziale Prestige; CP & EMS] abzuleiten" [@Ganzeboom2003, 159] und die so gewonnenen Status- bzw. Prestigemaße in Skalen zu überführen (ebd.). Dabei wird zum Zweck der Standardisierung und Vergleichbarkeit der Codierung von Berufsgruppen zu Status- bzw. Prestigewerten sowie deren Skalierung mehrheitlich auf die _I_nternational _S_tandard _C_lassification of _O_ccupations in der Fassung von 1968 (ISCO-68), von 1988 (ISCO-88) oder in der neuesten Fassung aus dem Jahr 2008 (ISCO-08) zurückgegriffen, die jeweils von der _International Labour Organisation_ (ILO) zur Verfügung gestellt wird.^[In den 1960er und 1970er Jahren kam es zu einer regelrechten Explosion der Konstruktion diverser beruflicher Prestige- und Statusskalen, wodurch die Forschungsergebnisse zusehends von Inkonsistenz und Dissonanzen geprägt waren [vgl. bspw. @Sørensen1975, 457; @Treiman1975, 184; @Mayer1980; 97-100; @Stawarz2013, 385-386; @Iversen2021, 6-13]. Um angesichts dieser unübersichtlichen Lage wieder Vergleichbarkeit herstellen, wurden die meisten Status- und Prestigeskalen auf die International Standard Classification of Occupations (ISCO) umgestellt. Einzige Ausnahme bildet die Magnitude-Prestige-Skala von Wegener (1988), die mit der deutsch-nationalen Klassifikation der Berufe (KldB) kompatibel ist [vgl. @Ganzeboom2010, 4-5; @Hoffmeyer2003, 127, 131; @BAfA2020a; @BAfA2020b].] Der wohl elaborierteste hierarchische Kontext der beruflichen Mobilitätsforschung ist der _I_nternational _S_ocio-_E_conomic _I_ndex of Occupational Status (ISEI). Dieser wurde von Ganzeboom, Treiman und de Graaf entwickelt und liegt in Anlehnung an die Weiterentwicklungen der internationalen Standardberufsklassifikation von 2008 (ISCO-08) nunmehr in der Fassung aus dem gleichen Jahr (ISEI-08) vor. Diesen wollen wir nun daraufhin befragen, welche Perspektiven er uns bzgl. der Positionsumstellungen Schwarzeneggers und Selenskyjs vom kommerziellen TV- und Filmbusiness in die Politik eröffnet. Zunächst jedoch sehen wir uns die Konzeption des internationalen sozio-ökonomischen Index des beruflichen Status von 2008 (ISEI-08) etwas genauer an.

Der ISEI-08 beruht auf "der gleichen konzeptionellen Logik" und mithin auf "den gleichen methodischen Verfahren wie der ursprüngliche ISEI und die nationalen SEI-Skalen" [@Ganzeboom2010, 5; vgl. auch @Ganzeboom2010c, 3]. Das heißt einerseits, dass der ISEI-08 weiterhin "soziale und wirtschaftliche Ressourcen [erschließen]" soll, "die den [beruflichen; CP & EMS] Statuserwerb in der Gesellschaft beschleunigen" [@Ganzeboom2010, 5], wobei "der berufliche Status als der Mechanismus konzeptualisiert und gemessen wird, der Bildungsnachweise in Einkommen umwandelt" (ebd., 11). Der Beruf ist also als eine Art "Zwischenstation" modelliert, die "die wichtigste Ressource einer Person (Bildung) in die wichtigste Vergütung einer Person (Einkommen) transformier[t]" [@Ganzeboom1992, 9]. Andererseits basiert die Codierung der internationalen sozio-ökonomischen Indexscala zum Berufsstatus-08 aber auch weiterhin auf der Konzeption der internationalen Standarsberufsklassifikation in der neuesten Fassung von 2008. Somit ist also für den ISEI-08 -- in Parallelität zur ISCO-08 -- eine deduktiv-hierarchische Berufssystematik tragend, die entlang von zehn beruflichen Hauptgruppen über 44 berufliche Unterhauptgruppen und 120 beruflichen Nebengruppen bis hin zu 403 beruflichen Einheitsgruppen zunehmend detaillierter organisiert ist [@Ganzeboom2010, 6].^[Dieses System aus 4 Berufsgruppen entspricht wiederum "der Anzahl der informativen Ziffern [...], die zur Codierung eines Berufs oder einer Berufsgruppe verwendet werden" [@Ganzeboom2010, 6].] Anschließend wurde für alle 507 codierten Haupt-, Unterhaupt-, Neben- und Einheitsgruppen auf Basis der Daten des _I_nternational _S_ocial _S_urvey _P_rogramm (ISSP) ein eigener Statuswert berechnet bzw. geschätzt (ebd., 12).^[Konkret stammen die Daten des Datensatzes "aus den kombinierten 2002-2007 Runden" des ISSP und "verein[en] detaillierte Berufsdaten mit Bildungs- und Einkommensdaten von 198.000 Männern und Frauen aus über 42 Ländern" [@Ganzeboom2010, 12]. Zudem wurden die Indikatoren Bildung und Einkommen so gewichtet, dass der ISEI-08 als optimale Skalierung von Berufen im Kontext eines Statuserlangungsprozesses definiert werden könne (ebd., 11, 13).] Insofern bestehe also ein wesentlicher Vorteil des sozio-ökonomischen Index des beruflichen Status darin, dass nicht nur 507 Berufsgruppen und Berufen unterschieden werden können, sondern ihnen gleichsam ein eigener Statuswert zugeordnet werden kann [vgl. @Ganzeboom2010b; vgl. auch @Erikson1992, 31]. Der höchste Statuswert des ISEI-08 beträgt dabei 89 und kommt ausschließlich der Nebenhauptgruppe der Ärzteschaft (Ziffer 2210) bestehend aus den Einheitsgruppen der Allgemeinmediziner und der Fachärzte zu (Ziffer 2211-2212), die wiederum in der Unterhauptgruppe der ,akademischen und verwandten Gesundheitsberufe’ (2200) angesiedelt sind und zur Hauptgruppe der ,akademischen Berufe’ gehören [vgl. @Ganzeboom2010b, 3; vgl. auch @BfS2017]. Demgegenüber beträgt der niedrigste Statuswert 10 [@Ganzeboom2010b, 9]. Er drückt den sozio-ökonomischen Berufsstatus der Unterhauptgruppe -- bestehend aus vier Nebengruppen (Ziffer 6310-6340) -- der ,Landwirte, Fischer, Jäger und Sammler für den Eigenbedarf’ (Ziffer 6300) aus, die ihrerseits zur Hauptgruppe der ,Fachkräfte in Land- und Forstwirtschaft und Fischerei’ gehören [@Ganzeboom2010b, 9; vgl. auch @BfS2017]. Der gleiche Statuswert von 10 kommt jedoch auch der Einheitsgruppe der ,Jäger und Fallensteller’ (Ziffer 6224) zu (ebd.), wodurch kenntlich wird, dass es zwar beim ISEI-08 den Fall gibt, dass Berufe, für die der gleiche Statuswert errechnet wurde, durchaus viel miteinander gemein haben können. Gleichsam weist der ISEI-08 aber auch Fälle auf, in denen Berufe von gleichem Statuswert "nicht unbedingt viel miteinander gemein haben müssen" und oftmals "in der Tat ganz unterschiedliche Positionen innerhalb der Arbeitsteilung einnehmen" [@Erikson1992, 39]. Im Folgenden werden wir nun die von Schwarzenegger und Selenskyj vollzogenen Positionswechsel vom Medienbusiness in die Politik mit dem ISEI-08 konkretisieren und auf jeder Aggregationsebene die Bewegung zwischen beiden Positionen als Auf- bzw. Abstieg kennzeichnen.   

## 2.2.1 Schwarzeneggers und Selenskyjs Wechsel in die Politik am Beispiel des internationalen sozio-ökonomischen Index des beruflichen Status (ISEI-08) 

Wenn wir nun danach fragen, welche Erkenntnisse der ISEI-08 hinsichtlich der Zirkulation Schwarzeneggers und Selenskyjs aus dem Show-, TV- und Filmgeschäft in den Politikbetrieb liefert, so zeigt sich auf der Ebene der beruflichen Haupt-, Unterhaupt-, Neben- und Einheitsgruppen folgendes Bild: Auf der Ebene der Berufshauptgruppen lässt sich zunächst feststellen, dass der Weg vom Star zum politischen Anführer Kaliforniens bzw. der Ukraine im ISEI-08 als ein Positionswechsel ausgehend von der Hauptgruppe der ,Fachkräfte’ (Ziffer 2000) in die der ,Führungskräfte’ (Ziffer 1000) zu verstehen ist [@Ganzeboom2010b, 1, 2; vgl. auch @ILO2012, 87, 109]. Dieser hauptberufliche Wechsel entspricht im ISEI-08 einer vertikalen Mobilität, die jedoch insofern in absteigender Richtung verläuft, als Schwarzenegger und Selenskyj eine Berufshauptgruppe mit dem Statuswert 65 für eine andere mit dem Wert 62 verlassen und dabei drei Statuswertpunkte einbüßen [@Ganzeboom2010b, 1, 4]. Diese Richtungseinschätzung der von Schwarzenegger und Selenskyj absolvierten sozialen Mobilität ändert sich jedoch, wenn wir diese auf den Ebenen der beruflichen Unterhaupt-, Neben- und Einheitsgruppen zunehmend detaillierter ins Auge fassen. So gelingt unseren beiden Protagonisten auf der Aggregationsebene der beruflichen Unterhauptgruppen mit dem Wechsel von der Berufsgruppe der ,juristischen, sozialen und kulturellen Fachkräfte’ (Ziffer 2600) in die der ,Geschäftsführer, Vorstände, leitenden Verwaltungsbediensteten und Angehörigen gesetzgebender Körperschaften’ (Ziffer 1100) nicht nur eine vertikale Mobilitätsbewegung [@ILO2012, 88, 158]. Vielmehr realisieren Schwarzenegger und Selenskyj auf dieser Ebene gleichsam einen Aufstieg um drei Statuswertpunkte, indem sie von einer Position mit Statuswert 66 in eine mit dem Wert 69 zirkulieren [@Ganzeboom2010b, 1, 4]. Besonders ausgeprägt ist diese aufsteigende Mobilität jedoch auf der Ebene der Berufsnebengruppen. Hier ist sowohl Schwarzenegger als auch Selenskyj ausgehend von der Nebengruppe der ,kreativen und darstellenden Künstler’ mit einem Statuswert von 53 (Ziffer 2650) der Sprung in die Nebengruppe der ,Gesetzgeber und hohen Beamten’ geglückt, für die der ISEI-08 einen Statuswert von 68 (Ziffer 1110) schätzt [vgl. ebd.; vgl. auch @ILO2012, 88, 166]. Entsprechend haben Schwarzenegger und Selenskyj auf der Aggregationsebene der Nebenberufsgruppen einen durchaus erstaunlichen Aufstieg realisiert, indem die Zielposition einen um 15 Statuspunkte gesteigerten Wert gegenüber dem Statuswert der Ausgangsposition aufweist. Diese bemerkenswerte aufsteigende Mobilität ist allerdings auf der Ebene der beruflichen Einheitsgruppen nicht mehr sichtbar. So haben Schwarzenegger und Selenskyj ausgehend von ihrer Haupttätigkeit als Schauspieler (Ziffer 2655) des Action- und Komödienfilm- und Seriengenres zwar immer noch einen Aufstieg durch ihre Zirkulation in die Position eines ,Gesetzgebers’ (Ziffer 1111), d. h. in das Amt eines Gouverneurs bzw. das Präsidentschaftsamt der Ukraine, realisiert [@Ganzeboom2010b, 1, 4; vgl. auch @ILO2012, 89, 167f.]. Bei dieser Zirkulation sind die beiden Protagonisten jedoch nur von einer Position mit dem Statuswert 64 in eine Position mit dem Statuswert 66 gewechselt (vgl. ebd.), wodurch sie ihren beruflichen Status lediglich um zwei Punkte gesteigert haben. Stellen wir für Selenskyj gleichsam seine Tätigkeit als Produzent von Filmen und Serien und seine Geschäftsführertätigkeit für die Rundfunk- und Fernsehanstalt Kwartal 95 in Rechnung [vgl. @Nelles2019], so kann für Selenskyj einen Statuszugewinn von drei Punkten festgestellt werden, da für diese Augangsposition im ISEI-08 ein Statuswert von 63 geschätzt wurde [@Ganzeboom2010b, 4]. 

Für den ISEI-08 als Analyseinstrument am Beispiel der beruflichen Mobilität Schwarzeneggers und Selenskyjs ließe sich ingesamt positiv hervorheben, dass dieser hierarchische Kontext im Unterschied zum EGP-Klassenschema nicht nur in der Lage ist, die von beiden Protagonisten realisierte berufliche Mobilität von der Position eines Schauspielers bzw. Produzenten in das politische Amt eines Gouverneurs bzw. eines Präsidenten auch als solche zu erkennen und zu erfassen. Zudem erlaubt der hierarchische Kontext des ISEI-08, die soziale Mobilität Schwarzeneggers und Selenskys als vertikale Mobilität zu behandeln und auf Basis der entsprechenden Statuswerte Aussagen über die Richtung der beruflichen Mobilität beider Protagonisten auf jeder der vier Aggregationsebenen zu treffen. So haben Schwarzenegger und Selenskyj auf der Ebene der Berufshauptgruppen eine absteigende soziale Mobilität um drei Stauswertpunkte vollzogen, während sie auf den drei weiterführenden Aggregationsebenen jeweils eine aufsteigende Mobilität vom Star zum politischen Anführer absolviert haben. In Bezug auf das Ausmaß der aufsteigenden Mobilität ist allerdings ebenso hervorzuheben, dass der Statusgewinn von Aggregationsebene zu Aggregationsebene nicht nur relativ stark zwischen fünfzehn und drei bzw. zwei Statuspunkten variiert, sondern auch von dem Befund der absteigenden Mobilität auf der Ebene der Berufshauptgruppen in gewisser Weise geschnitten wird. Eingedenk dieser Varianz bzgl. der Richtung und des Ausmaßes der Statusmobilität Schwarzeneggers und Selenskyjs ließe sich entsprechend lediglich sagen, dass der ISEI-08 in der Lage ist, deren Positionswechsel von der kulturindustriellen Medienbranche in die höchten politischen Ämter als vertikale Mobilität zu klassifizieren. An diesen Befund anknüpfend, ließe sich ferner konstatieren, dass die berufliche Mobilität innerhalb hierarchischer Kontexte im Allgemeinen und im Rahmen des ISEI-08 im Besonderen wesentlich als eindimensionales Phänomen gefasst ist [vgl. @Ganzeboom1992, 7], was überdies zu einer künstlichen Verengung der komplexen Phänomenologie beruflicher Mobilität auf ein Ordnungsprinzip -- am Beispiel des ISEI-08 der sozio-ökonomische Berufsstatus -- führt. Weiten wir nun den Blick auf die Modellierung des ISEI-08, so ist zudem festzustellen, dass sich berufliche Statusmobilität vornehmlich auf der Individualebene abspielt. Dies wiederum hat einerseits zur Folge, dass der Fokus auf berufliche Statusmobilität -- verstanden als Umwandlungsmechanismus der Bildungsnachweise von Schwarzenegger und Selenskyj in deren jeweiliges Einkommen [vgl. @Ganzeboom2010, 11] --, der Auffassung Vorschub leistet, als ob es einzig in der Hand der Akteure läge, ihre vertikale Zirkulation zwischen zwei Statuspositionen zu beeinflussen. Andererseits hat die  Individualisierung beruflicher Mobilität als Statusmobilität aber auch zur Folge, dass die institutionelle Ebene, die für die Realisierung vertikal Mobilität ebenso unerlässlich ist wie das Zutun der Akteure, weder bei der Konzeption noch bei der Messung von Statusmobilität Berücksichtigung findet. Damit bleibt der ISEI-08 hinter Sorokins Auffassung zu vertikaler Mobilität zurück, wenn dieser zu bedenken gibt, dass es, damit die vertikale Mobilität in jeder Gesellschaft funktioniere, in den 'Membranen' zwischen den Stratifikationsebenen einer Gesellschaft [...] 'Fahrstühe' oder 'Känäle' geben müsse, die es den Individuen erst ermöglichten, sich von Startifikationsebene zu Stratifikationsebene auf- und abwärts zu bewegen [@Sorokin1959, 164]. Als ’Kanäle’ oder ’Fahrstühle’ vertikaler Mobilität fungieren dabei vornehmlich "verschiedene[n] soziale[n] Institutionen" und Organisationen, die die Durchführung vertikaler Mobilität unterstützen und befördern; ein Punkt, dem die Theorie der Relation über das Konzept der doppelten Einschreibung Rechnung trägt [vgl. @PapilloudSchultze2022, 34-58].^[Sorokin unterscheidet insgesamt sieben unterschiedliche ’Kanäle’ vertikaler Zirkulation. Dazu gehören bspw. die Armee [@Sorokin1959, 164ff.], die Kirche (ebd., 166ff.), Regierungsfraktionen, politische Organisationen und politische Parteien (ebd., 172ff.), wissenschaftliche, literarische und künstlerische Institutionen, die Presse oder auch wirtschaftsnahe Organisationen (ebd., 175ff.).]

In engem Zusammenhang damit steht eine weitere Problematik, die mit der Statusmobilität und der Konzeption des ISEI-08 einhergeht und nun anhand der beruflichen Unterhaupt- und Einheitsgruppen mit Blick auf Schwarzeneggers und Selenskyjs Zielposition in exemplarischer Weise veranschaulicht werden soll. So haben wir hervorgehoben, dass auf der Ebene der Unterberufshauptgruppen sowohl Schwarzenegger als auch Selenskyj eine aufsteigende Mobilität vom Statuswert 66 zum Statuswert 69 geleistet haben. Der Statuswert 69 ist jedoch nicht nur auf die berufliche Unterhauptgruppe der ,Geschäftsführer, Vorstände, leitenden Verwaltungsbediensteten und Angehörigen gesetzgebender Körperschaften’ (Ziffer 1100) begrenzt [@Ganzeboom2010b, 1; @ILO2012, 88, 158], sondern erstreckt sich auch auf die Unterhauptgruppen der ,Naturwissenschaftler, Mathematiker und Ingenieure’ (Ziffer 2100) und der ,Fachkräfte für Informations- und Kommunikationstechnologien’ (Ziffer 2500) [vgl. @Ganzeboom2010b, 2, 4].^[Wechselt also eine Akteur tatsächlich die Branche seiner Tätigkeitsausübung von der Wissenschaft in die Politik indem bspw. eine promovierte Diplomphysikerin für Theoretische Chemie von einer Position im Zentralinstitut für physikalische Chemie der Akademie der Wissenschaften der DDR in weniger als einem Jahr in die Position einer Bundestagsabgeordneten für die Christlich Demokratische Union (CDU) zirkuliert [@Merkel2024], so lässt sich diese Positionsumstellung aufgrund gleicher Statuswerte der diesen Positionen zugeordneten beruflichen Unterhauptgruppen 1100 und 2100 kaum adäquat mit dem ISEI-08 erfassen.] Gleiches lässt sich auf der Ebene der beruflichen Einheitsgruppen demonstrieren, auf der Schwarzenegger und Selenskyj laut ISEI-08 ebenfalls eine aufsteigende Mobilität vom Schauspieler mit Statuswert 64 zum Staatspräsidenten bzw. zum Gouverneur mit Statuswert 66 realisiert haben [vgl. @ILO2012, 89; vgl. auch @Ganzeboom2010b, 1, 4]. Der Statuswert 66 ist allerdings auch den Einheitsgruppen der ,Fachkräfte in Vertrieb und Marketing' (Ziffer 1221), der ,Fachkräfte im Bereich Umwelt- und Arbeitsmedizin sowie Hygiene' (Ziffer 2263), der ,Wirtschaftsprüfer und Steuerberater' (Ziffer 2411), der ,Finanz- und Anlagenberater' (Ziffer 2412), der ,Finanzanalysten' (Ziffer 2413) sowie der ,Flugsicherungstechniker' (Ziffer 3155) zugeordnet [@Ganzeboom2010b, 1, 3, 4, 5]. 

Vor diesem Hintergrund lässt sich entsprechend hervorheben, dass der ISEI-08 als hierarchischer Kontext über die Schätzung bzw. Bererchnung gleicher Statusmaße eine Homogenisierung unterschiedlicher Tätigkeiten und Tätigkeitsbereiche vornimmt [vgl. zu diesem Kritikpunkt auch @Erikson1992, 30]. Dadurch ist es weder möglich, eine Positionsumstellung zwischen diesen oberen Berufen als vertikale Mobilität (bspw. vom Finanzanalysten zum Minister) zu klassifizieren, noch einen Positionswechsel zwischen diesen Berufseinheiten zumindest als horizontale Mobilität zu fassen. Aus der Homogenisierung unterschiedlicher Tätigkeiten aufgrund gleicher Statuswerte, die nicht nur für die Ebene der Eineits-, sondern auch für die anderen drei Aggregationsebenen Gültigkeit beansprucht, resultiert überdies eine Homogenisierung von gesellschaftlichen Tätigkeitssphären bzw. von Teilsystemen (Luhmann) oder sozialen Feldern (Bourdieu). Insofern entsteht also nicht nur der Eindruck, als sei es empirisch wie theoretisch irrelevant, ob es sich um politisch orientierte Tätigkeiten der Berufsausübung oder um wirtschafts-, medien- oder wissenschaftsnahe etc. Tätigkeiten auf den vier hierarchischen Ebene des ISEI-08 handelt. Es entsteht auch der Eindruck, als sei das Einsatzgebiet bzw. die gesellschaftliche Sphäre der Berufausübung zu vernachlässigen legitim, wodurch es in gewissem Umfang zu einer Vermischung zwischen den Sphären der Wissenschaft, der Wirtschaft oder der Politik kommt.^[Damit untergräbt der ISEI in gewissem Umfang die konzeptionellen Grundlagen der internationalen Standardberufsklassifikation (ISCO-08), deren erklärtes Ziel darin besteht, "eine Reihe von Tätigkeiten, deren Hauptaufgaben und -pflichten durch einen hohen Grad an Ähnlichkeit gekennzeichnet sind" [@ILO2012, 11], zu branchen- und dienstleistungsspezifischen Berufsgruppen und Berufen zusammenzufassen [@Ganzeboom2010, 4; vgl. auch @BAfA2020b]. Die branchenspezifische Zurodnung der Berufe bzw. die Ähnlichkeitserfassung beruflicher Tätigkeitsspektren wird im ISCO-08 weiterführend entlang von vier "Konzepten" ausdifferenziert. Zu diesen Konzepten bzw. Ähnlichkeitsparametern gehören erstens "das erforderliche Wissensgebiet", zweitens "die verwendeten Werkzeuge und Maschienen", drittens "die Materialien, mit denen gearbeitet wird" und schließlich "die Art der produzierten Waren/Erzeugnisse und Dienstleistungen" [@ILO2012, 11]. Diese ’Konzepte’ werden teils entlang der Modellierung des sozio-ökonomischen Berufsstatus im ISEI-08 untergraben.]

Insgesamt lässt sich also für den ISEI-08 im Hinblick auf die berufliche Mobilität Schwarzeneggers und Selenskyjs von der Kulturindustrie in die Politik bzw. vom Schauspieler in das Präsidentschafts- und Governeursamt festellen, dass der ISEI-08 zwar in der Lage ist, die Zirkulation der beiden Protagonisten als vertikale Mobilität zu klassifizieren. Er liefert jedoch keine Erklärung dafür, wie Schwarzenegger und Selenskyj der Sprung vom Film- und Fernsehgeschäft in den Politikbetrieb gelungen ist, welche Strukturen bzw. Pfade zwischen unterschiedlichen gesellschaftlichen Sphären einen solchen Wechsel begünstigen, welche Rolle der Zugang der beiden Protagonisten zu bestimmten institutionellen Instanzen spielt, welche Bedeutung der vermehrten Verwendung von Medien bei der Realisierung dieser transversalen Mobilität in die Politik zukommt und wie diese die Zirkulation Schwarzeneggers und Selenskyjs zu beschleunigen imstande ist.

## 3. Die Zirkulation Schwarzeneggers und Selenskyjs in die Politik aus der Perspektive der Theorie der Relation

Wie wir bis hierher gesehen haben, geben uns die gängigen Ansätze sozialer Mobilitätsforschung -- exemplarisch demonstriert am EGP-Klassenschema und dem ISEI-08 -- kaum das nötige Instrumentarium an die Hand, um die von Schwarzenegger und Selenskyj vollzogene Zirkulation aus der Position eines hoch dekorierten Schauspielers (und Produzenten) des kommerziellen Film- und TV-Business in das höchste Amt Kaliforniens bzw. der Ukraine hinlänglich zu erklären. Dies ist aus der Perspektive der Theorie der Relation vor allem deshalb verwunderlich, da der Wechsel der Relationsstruktur eine selbstverständliche Zirkulationsmöglichkeit darstellt, die auch Friedman und Laurison einräumen, selbst wenn sie diese als ,unverhältnismäßig’ bewerten [vgl. @Friedman2019, 266]. Demnach hätten bestimmte Akteure, so sie erst einmal die ,obersten Ränge’ in der Gesellschaft erreicht hätten, einen ,unverhältnismäßigen Zugang’ zu anderen ,Schlüsselpositionen’ und könnten quasi maßlos und unkontrolliert von ,Spitzenposition’ zu ,Spitzenposition’ zirkulieren (ebd.). Diese Zirkulationsmöglichkeit ist allerdings weder maßlos oder frei von jeder Kontrolle, noch beruht sie auf einem Un-Verhältnis oder stünde nur den Akteuren in den ,obersten Rängen’ offen. Vielmehr steht diese Zirkulationsmöglichkeit, wie bereits betont wurde, unterschiedslos allen Akteuren mittelbar zur Verfügung, und zwar unabhängig von ihrer Position in den Sequenzen einer Relationsstruktur, während sie gleichsam denjenigen Akteuren unmittelbar offensteht, die sich entweder in den ,obersten Ränge’ oder in den ,niedrigsten Rängen’ der Akteurkategorien in den Sequenzen einer Relationsstruktur befinden. Nun steht zwar außer Frage, dass Schwarzenegger und Selenskyj als Mitglieder der Relationspuristen die Möglichkeit des Wechsels der Relationsstruktur unmittelbar gegeben ist, dies gleichwohl aber noch nicht bedeutet, das diese Zirkulationsmöglichkeit auch tatsächlich realisiert wird. Wie bereits gesehen, verlangt der Wechsel der Relationsstruktur vielmehr einerseits einen geeigneten Widerstand aufseiten der Akteure, der in der Verabsolutierung der Sequenz besteht, die in der Ankunftsrelationsstruktur die Kernsequenz bildet. Entsprechend streben Schwarzenegger und Selenskyj gleichermaßen an, in die politische Relationsstruktur zu zirkulieren, um sich dort voll und ganz in den Dienst der _Attraktivität der Repräsentation_ von Kollektiven zu stellen, wofür sie der medialen Relationsstruktur den Rücken kehren und ihren Dienst an der _Repräsentation der Attraktivität_ von Einzelakteuren als Stars, als Kabarettisten etc. quittieren. Andererseits haben wir aber auch gesehen, dass allein auf Basis eines solchen Widerstandsverhältnisses, noch kein erfolgreicher Wechsel der _Relation durch Position_ zustande kommt oder schlicht die Stabilisierung der Position in der Ankunftsrelationsstruktur scheitert. Es braucht daher auch die Durchführung von Einschreibungsakten mit Instanzen des Politikbetriebs bzw. mit "verschiedenen sozialen Institutionen" des politischen Geschehens [@Sorokin1959, 164]. Insofern ist also der Wechsel der Relationsstruktur durch Akteure der ,obersten Ränge’ und mithin der Wechsel von der medialen in die politische Relationsstruktur durch Schwarzenegger und Selenskyj ebenfalls von dem konzeptionellen Trias Einschreibung, Widerstand und Reziprozität abhängig. Auf jenen Trias werden wir nun anhand unserer beiden Fallbeispiele näher eingehen. Zuvor werden wir jedoch den von Schwarzenegger und Selenskyj absolvierten Zirkulationsweg, den wir weiter oben bereits als aufsteigende Zirkulation beschrieben haben und der über transversale Mobilität realisiert wurde, genauer beleuchten. Im Anschluss daran, werden wir uns den Wahlkampfstab Schwarzeneggers und Selenskyjs zuwenden und derren bedeutung als Resozialisierungsinstanzen näher erörten. Und schließlich wenden wir uns der Rolle der Medien zu um zu klären, wie die Verwendung dieser Medien, die vornehmlich aus dem Tätigkeitsrepertoire der medialen Relationsstruktur stammen, es Schwarzenegger und Selenskyj ermöglicht haben, ein Verhältnis zwischen sich selbst als politische Anführer und ihrer jeweiligen Wählerschaft herzustellen. Wir beginnen unsere Betrachtung mit der Präzisierung des von Schwarzenegger und Selenskyj absolvierten Zirkulationsweg von der Kulturindustrie in die Politik und der Bestimmung der Position, die beide Protagonisten in der Ankunftsrelationsstruktur als erstes bekleiden.

### 3.1 Die Bekanntgabe der Kandidatur für das Gouverneurs- und Präsidentschaftsamt als Coup Schwarzeneggers und Selenskyjs

Die mediale Relationsstruktur zeichnet sich grundsätzlich dadurch aus, dass Akteure wie Arnold Schwarzenegger und Wolodymyr Selenskyj so wenig wie möglich in relationale Ereignisse investieren, um anstelle solcher Ereignisse selbst im Zentrum der Zirkulationsdynamik zu stehen [@PapilloudSchultze2022, 112]. Eine Besonderheit dieser Relationsstruktur besteht zudem in dem exorbitanten Aufkommen von Medien (ebd., 119). Dieser Medien bedienen sich wiederum Akteure, um ihre Reziprozitätsmöglichkeiten deutlich zu steigern und sowohl schneller als auch einfacher der allgemeinen Zirkulation folgend -- Attraktivität ... Investition ... Repräsentation ... Materialität ... Attraktivität ... (vgl. Abb. 3.13 in ebd., 115)-- in der medialen Relationsstruktur zu zirkulieren (ebd., 115), was zugleich die Grundlage der Macht dieser Akteure bildet (ebd., 116). Am besten wissen sich dabei die Relationspuristen, wie sie von Schwarzenegger und Selenskyj verkörpert werden, diese Medien, die von den Vermittlungsinstanzen eingesetzt werden, um möglichst viele Individualitäten ihrer Akteure zu adressieren, für sich und ihre stetige Zirkulation zunutze zu machen. So akkumulieren sie nicht nur über jede vollendete Zirkulation -- d. h. mit jedem vollendeten Film-, Serien-, Entertainmentprojekt -- immer mehr Medien, sondern gewinnen auch wertvolle Einblicke in die Regulation der Zirkulation in der medialen Relationsstruktur, indem sie an der Seite der entsprechenden Instanzen stets an ihren akkumulierten Medien arbeiten (ebd.). Diese besondere Kontrolle, Kenntnis und Verfügung über alle möglichen Medien lässt sich allerdings auch zweckentfremden und zur Attraktivierung der Akteure außerhalb der medialen Relationsstrukturen einsetzen. Die Art und Weise, wie die Kandidatur für das Gouverneursamt im Falle Schwarzeneggers und das Präsidentschaftsamt im Falle Selenskyjs bekannt gegeben wurde, legt davon Zeugnis ab und unterstreicht gleichsam, wie das Prinzip der Verführung durch unsere beiden Protagonisten Einzug in die politische Relationsstruktur hält.

Ausgangspunkt der Zirkulation in die Politik bildet sowohl bei Schwarzenegger als auch bei Selenskyj die Kernsequenz Attraktivität der medialen Relationsstruktur. So hatte Schwarzenegger Ende Juli 2003, als er erfahren hat, dass es zu Abberufungs- und Neuwahlen um das Gouverneursamt in Kalifornien kommen würde, gerade seine weltweite Promotion-Tour für _Terminator 3_ (Repräsentation), der seit dessen Erscheinen Anfang Juli (Verwirklichung) _ad hoc_ die Nummer 1 an den Kinokassen (Attraktivität) war, abgeschlossen [@Schwarzenegger2014, 514; vgl. auch Schwarzenegger2023c]. Auch Selenskyj befindet sich Ende des Jahres 2018 gerade wieder in der Kernsequenz Attraktivität der medialen Relationsstruktur. Zuvor hat er mit Unterstützung seines Teams von Studio Kwartal 95 das ganze Jahr über -- betraut mit der Idee, dem Drehbuch und den Dreharbeiten in der Hauptrolle des ukrainischen Präsidenten Wassyl Holoborodko (Investition), der Vermarktung (Repräsentation) und dem Verkauf an die 1+1 Mediaholding des Oligarchen Ihor Kolomojskyj (Verwirklichung) -- an der dritten Staffel der Erfolgsserie _Diener des Volkes_ gearbeitet, deren Erstausstrahlung eine Woche vor der ersten Runde der Präsidentschaftswahlen am 31. März 2018 beginnt (Attraktivität) [@Iwan2019]. Aus dieser Position heraus, wäre es für die Relationspuristen Schwarzenegger und Selenskyj ein Kinderspiel gewesen, sich einem neuen Film- oder Serienprojekt zuzuwenden (Investition), dieses zu promoten und zu vermarkten (Repräsentation) und sich über das Erscheinen (Verwirklichung) erneut als Superstars der kommerziellen Medienindustrie zu stilisieren. Entsprechend ihres über die Jahre gewachsenen Widerstands _für_ die Kernsequenz Repräsentation der politischen Relationsstruktur und _gegen_ die Kernsequenz _Attraktivität_ der medialen Relationsstruktur übte jedoch die Repräsentation eines Kollektivs eine ungleich größere Anziehungskraft auf beide Protagonisten aus. Dieser Widerstand besteht allerdings nicht in einer Verteufelung der Attraktivität _per se_, sondern der Fokus dessen, was es zu attraktivieren gilt, entwickelt sich bei beiden Akteuren von einem ausschließlich akteurzentrierten Standpunkt zu einem vornehmlich austauschzentrierten Standpunkt, der von akteurzentrierter Attraktivität, d. h. von Schwarzenegger und Selenskyj in der Rolle des politischen Anführers, monopolisiert wird [vgl. @PapilloudSchultze2022, 97-103]. Damit einhergehend verändert sich auch das Augenmerk beider Protagonisten hinsichtlich der Frage, was es zu repräsentieren gilt und wie diese Repräsentation im Verhältnis zur Investition/Materialität bzw. zur Materialität/Investition ausdifferenziert wird. Schwarzenegger und Selenskyj geht es somit nicht mehr um die Repräsentation ihrer selbst als Ikonen des Aktion- und Science-Fiction-Filmgenres oder des politisch-satirischen Kabaretts bzw. der Leinwand-Präsidentschaft, in dessen Verwirklichung es zu investieren gilt. Es liegt Schwarzenegger und Selenskyj viel eher alles an ihrer Attraktivierung als Repräsentanten zum Zweck der Repräsentation der Bevölkerung Kaliforniens bzw. der Ukraine und zwar über den Weg der Verwirklichung von Investitionen bspw. in die Vorreiterstellung Kaliforniens bei erneuerbaren Energien [vgl. @Bustillo2003; @CNN2003b] oder in den Kampf gegen die Korruption in der ukrainischen Politik [vgl. @Gon2019a; @Zelenskyj2019]. Damit ist deutlich, dass sowohl Schwarzeneggers als auch Selenskyjs Widerstand einer Umkehrung der Verhältnisse entspricht, die sich ausgehend von den konstituierenden Strukturen der Kernsequenz Attraktivität in der medialen Relationsstruktur (Materialität...Investition...Repräsentation...Attraktivität) hin zu den konstituierenden Strukturen der Kernsequenz Repräsentation in der politischen Relationsstruktur (Investition...Materialität...Attraktivität...Repräsentation) verändert hat. Eingedenk dieser Umkehrung des Widerstands wagen also Schwarzenegger und Selenskyj den riskanten Sprung in die Politik, indem sie von der Kernsequenz Attraktivität der medialen Relationsstruktur in die Sequenz Attraktivität der politischen Relationsstruktur zirkulieren.^[Diese transversale Mobilität des Wechsels der Relationsstruktur ist deshalb als riskant einzustufen, weil keinesfalls gesichert ist, dass Schwarzenegger und Selenskyj tatsächlich zum Repräsentant ihrer Bevölkerungen generieren, da sie, bis sie die Kernsequenz Repräsentation in der politischen Relationsstruktur erreichen, noch durch die Sequenz Investition zirkulieren müssen, und beide Protagonsiten obendrein ihre bis dato gewohnte Art der Tätigkeitsentwicklung vom Standpunkt der Attraktivität nun durch eine Tätigkeitsentwicklung vom ausschließlichen Standpunkt der Repräsentation zu ersetzen haben.]

Zeugnis dieses Sprungs in die Politik legt die Kandidatur Schwarzeneggers und Selenskyjs für das Amt des Gouverneurs von Kalifornien bzw. für das Prädidentschaftsamt der Ukraine ab, die beide im Gewand einer Sensation öffentlichkeitswirksam im Fernsehen bekannt gebenen haben. Schwarzenegger erklärt nach eigenen Angaben den amtierenden Gouverneur von Kalifornien im Juni 2003 zu seinem höchst persönlichen Feind -- ähnlich wie Sergio Olivia, der ihn in Miami beim ersten Mr. Olympia-Wettkampf 1968 geschlagen hat [@Schwarzenegger2023a], und Sylvester Stallone, sein stärkster Kontrahent in den 1980er-Jahren [@Schwarzenegger2023b] -- und fasst, entgegen aller Skepsis, die ihm vonseiten der Traumfabrik entgegengeschlagen ist [@Schwarzenegger2023c], den Plan, Davis den Rang abzulaufen [@Schwarzenegger2014, 512, 513]. Das heißt jedoch nicht, dass Schwarzenegger seine Kandidatur sofort nachdem Ende Juli 2003 öffentlich wurde, dass es zu Abberufungs- und Neuwahlen im Bundesstaat Kalifornien kommen würde [@Mathews2003], seine Kandidatur auch bekannt gegeben hätte. Er ließ vielmehr eine Woche verstreichen, in der er die Presse darüber im Ungewissen ließ, ob er tatsächlich eine Kandidatur erwäge, sofern ihn die republikanische Partei, deren jahrelanges Mitglied er seit seiner Einbürgerung 1983 war, brauche, wie er gegenüber der New York Times eingeräumt hatte [@Schwarzenegger2014, 511]. Schwarzenegger verfolgt jedoch eine andere Taktik, denn er war am 06. August 2003 in der Unterhaltungssendung The Tonight Show zu Gast [@Schwarzenegger2023c]. Dort von Moderator Jay Leno gefragt, ob er zur Wahl um das Gouverneursamt antreten werde, sorgt Schwarzenegger für Furore als er verkündet, dass er kandidiere, weil Gray Davis, der die Menschen so enttäuscht habe, abgewählt werden müsse" (ebd.; vgl. auch @Schwarzenegger2014, 519). Damit sorgt er nicht nur aufseiten Jay Lenos für reichlich Irritation, der retrospektiv über diesen Auftritt Schwarzeneggers sagt: "Ich war sprachlos. Ich dachte, du bist ein Filmstar. Was willst du?" [@Schwarzenegger2023c]. Ebenso fassungslos zeigt sich auch Linda Hamilton, die Arnolds Kandidatur als "eine hirnverbrannte Idee" bezeichnet (ebd.), oder Danny DeVito, der sagt: "Ich fand's absurd. Es klang lächerlich. Du willst Gouverneur werden? Wer bist du" (ebd.)? Es gab allerdings auch positive Reaktionen, bspw. von James Cameron, der angibt, dass sich Schwarzenegger all die Zeit auf seine größte Rolle vorbereitet habe (ebd.), oder von Jamie Lee Curtis, die sich erinnert gedacht zu haben, dass Schwarzenegger ganz sicher gewinnen werde (ebd.).

Mit einem noch größeren Paukenschlag steigt Selenskyj, unterstützt von seinem Kwartal 95-Team, in den Präsidentschaftswahlkampf ein. Dabei geht es Selenskyj mehr noch als Schwarzenegger in aller erster Linie darum, das Leben auf der Leinwand in das echte, reale Leben zu verwandeln und die durch Selenskyj erzeugte und verkörperte Attraktivität des Geschichtslehrers Wassyl Holoborodko, der in der Serie _Diener des Volkes_ zufällig zum Präsident der Ukraine gewählt wird und aller Widerstände zum Trotz beginnt, gegen die Korruption der Kiewer Politik zu kämpfen, in die Attraktivität der Repräsentation mit Selenskyj als Präsident umzumünzen. Als Rahmen hierfür wählt Selenskyj und sein Studio die Comedysshow _Vecherniy Kvartal_ (Abendkwartal), die seit ihrem Start vor 11 Jahren das beliebteste Unterhaltungsprogramm im ukrainischen Fernsehen sei [Selenskyj zit. nach @Prensario2016] und am Silvesterabend 2018 auf 1+1 ein Millionenpublikum erreicht [@Rogacin2022, 123]. Dieses satirisch-politische Erfolgsformat, in dem Selenskyj vornean "die politische Situation, die herrschende Klasse und die von ihr durchgeführten Reformen ins Lächerliche" zieht [@Iwan2019], ist jedoch nicht die einzige Mediation, die Selenskyj bemüht, um seine Kandidatur für das Präsidentschaftsamt der Ukraine bekanntzugeben. Er bedient sich überdies auch aus der Trickkiste der ukrainischen Politik, indem er die alljährliche Neujahresansprache des amtierenden Präsidenten, die zum Jahreswechsel 2018/2029 Petro Poroschenko an das ukrainische Volk richtet, adaptiert und als Mediationsform seiner eigenen Präsidentschaftskandidatur verwendet. Für die Ausstrahlung der Neujahresansprache des amtierenden Präsidenten unterbrechen üblicher Weise "[a]lle ukrainischen Fernsehsender [...] das Programm" [@Rogacin2022, 123]. Entsprechend unterbricht auch der Sender 1+1 um Mitternacht die Sendung  _Vecherniy Kvartal_, sendet jedoch nicht etwa die Neujahresansprache von Poroschenko, sondern zur Überraschung der Zuschauerschaft und Irritation der Politiker:innen eine kurze Neujahresansprache Selenskyjs an das Volk der Ukraine (ebd.; vgl. auch @Iwan2019). In dieser wendet sich Selenskyj "wie ein guter Bekannter" an die Ukrainer:innen als seine "Freunde" und präsentiert sich als Kandidat eines ’dritten’ Weges inmitten verhärteter politischer Fronten des Weiter-so-wie-bisher bzw. des Kofferpackens, und erklärt, dass der Königsweg in dem Versuch bestehe, selbst in der Ukraine etwas zu verändern [Selenskyj zit. nach @Rogacin2022, 123]; ein Weg, den er für sich gewählt habe (ebd.). Anschließend erzählt der Showmaster, dass er seit langem gefragt werde, ob er kandidiere oder nicht, er aber anders als 'unsere' Politiker nicht etwas verspreche und dann nicht Wort halte (ebd.). Nach dieser Bezugnahme auf den gängigen Politikbetrieb kündigt Selenskyj Folgendes an: "Liebe Ukrainer, ich verspreche euch, dass ich als Präsident der Ukraine kandidiere. Und ich erfülle sofort mein Versprechen: Ich kandidiere als Präsident der Ukraine. Ich stelle mich zur Wahl. Kommt, lasst uns das gemeinsam machen! Auf das neue Jahr! Auf den neuen Diener des Volkes!" (ebd., 123f.). 

Vor diesem Hintergrund lässt sich sowohl für Schwarzenegger als auch für Selensky festhalten, dass die Kandidaturbekanntgabe einem medialen Coup gleicht, wenngleich Selenskyj mit seiner Bekanntmachung aus zwei Gründen eine ungleich größere theatralische Meisterleistung geglückt ist. Zum einen deshalb, weil nicht etwa der amtierende, sondern der Präsident aus dem Fernsehen zum "Volk" spricht und sich Selenskyj die große Popularität der beiden ersten Staffeln von _Diener des Volkes_ insofern zunutze macht, als sich sein Publikum längst "an die politische Rolle der Hauptfigur gewöhnt [hat]" [@Iwan2019]. Zum anderen aber auch, weil er bis zur letzten Minute vor Ablauf der Nominierungsfrist für eine Präsidentschaftskandidatur am 31.Dezember 2018 gewartet hat, um mit dem größt möglichen Überraschungseffekt sowohl aufseiten der ukrainischen Bevölkerung als auch der des politisch-oligarchischem Establishments in das Rennen um das Präsidentschaftsamt einzusteigen und mit der Unterstützung seines Studio Kwartal 95 dafür sorgt, dass seine Wahlkampfkampagne mit einem großen Paukenschlag beginnt. Um einen medialen Coup handelt es sich schließlich im Falle Schwarzeneggers und Selenskyjs aber auch deshalb, weil beide für die Bekanntgabe ihrer Kandidatur auf kommerzielle Unterhaltungsformate zurückgreifen und sich nicht etwa, wie im Politikbetrieb mehrheitlich üblich, für eine Pressekonferenz entscheiden, auf der sie gegenüber einer Reporterschaft des politischen (Qualitäts)Jounalismus ihre Absichten zu erklären und ggf. weiterführende Fragen bspw. zu ihrem Wahlprogramm oder der Umsetzung desselben zu beantworten hätten. 

Ferner unterstreichen die medialen Coups Schwarzeneggers und Selenskyjs, dass die von Medienschaffenden gängige Art der Tätigkeitsentwicklung in der Kernsequenz Attraktivität der medialen Relationsstruktur, die dem Muster der Repräsentation von Investitionen in die Verwirklichung der Attraktivität von Einzelakteuren folgt, in abweichender Form auch für die Sequenz Attraktivität der politischen Relationsstruktur Gültigkeit beansprucht [vgl. Abb. 3.7 & Abb. 3.13 in @PapilloudSchultze2022, 102, 115; vgl. auch ebd., 125]. Diese abweichende Kompatibilität zeigt sich entsprechend darin, als es bei der Zirkulation von der Kernsequenz Attraktivität der medialen Relationsstruktur in die Sequenz Attraktivität der politischen Relationsstruktur, vor allem darum geht, die mediale Popularität und die kommerzielle Berühmtheit eines bestimmten Protagonisten, die wiederum über eine Vielzahl von Zirkulationen in der medialen Relationsstruktur erworben wurde (ebd., 186), in der politischen Relationsstruktur in die Attraktivität desselben Protagonisten als Repräsentant von Kollektiven umzuwandeln; ein Schachzug, der sowohl Schwarzenegger als auch Selenskyj mit Hilfe ihrer medialen Coups mit Bravur gelungen ist. Dies verdeutlicht zugleich, dass die transversale Mobilität von Akteuren nicht unbedingt einer Veränderung von Tätigkeiten verlangt, sondern lediglich zu einem anderen Bezug auf diese Tätigkeiten -- im Falle Schwarzeneggers und Selenskyjs von der Attraktivierung ihrer selbst als Stars, als Entertainer etc. hin zur Attraktivierung ihrer selbst als Repräsentanten Kaliforniens bzw. der Ukraine -- führt (vgl. ebd., 181), indem dieselbe Tätigkeit vom Standpunkt der Kernsequenz der Ankunftsrelationsstruktur aufgegriffen wird. Dies erklärt sich nicht zuletzt damit, dass Akteure einen Wechsel der Relationsstruktur im Sinne von „_Transversalverlagerungen_“ [@Bourdieu2012, 220, 210–221] nicht zwischen beliebigen Sequenzen zweier Relationsstrukturen vornehmen können. Vielmehr ist jeder Wechsel der Relationsstruktur -- aufgrund des Wechselspiels zwischen strukturellen und morphologischen Determinanten in der Ankunftsrelationsstruktur (vgl. ebd., 188; vgl. auch Abb. 5.2 in ebd.) -- nur über die Zirkulation zwischen gleichen Sequenzen zweier Relationsstrukturen möglich. Entsprechend sind also Schwarzenegger und Selenskyj von der Kernsequenz Attraktivität der medialen Relationsstruktur in die Sequenz Attraktivität der politischen Relationsstruktur zirkuliert (vgl. Abb. 5.2 in ebd.), wobei ihre Kandidatur für das Amt des Gouverneurs von Kalifornien bzw. des Präsidenten der Ukraine bzw. deren Prüfung und Annahme zeigt, dass beide Protagonisten zunächst einmal formal von den zuständigen Instanzen der politischen Relationsstruktur zugelassen wurden (ebd., 187).

Diese Zirkulation geht gleichsam mit einem Positionswechsel einher, wenngleich Schwarzenegger und Selenskyj dabei nicht etwa die Akteurkategorie, sondern lediglich die Schicht ihrer Akteurkategorie gewechselt haben. Das heißt konkret, dass beide Protagonisten die Kernsequenz Attraktivität der medialen Relationsstruktur ausgehend von der ersten Schicht der ersten Akteurkategorie als Relationspuristen verlassen haben, um in der Sequenz Attraktivität der politischen Relationsstruktur zu zirkulieren, wo sie als Neulinge des Politikgeschäfts entsprechend ihrer formal als legitim anerkannten Kandidaturnominierung eine Position in der dritten Schicht der ersten Akteurkategorie beziehen (ebd., 187). Die Positionierung in der dritten Schicht innerhalb der ersten Akteurkategorie in der Sequenz Attraktivität der politischen Relationsstruktur ergibt sich daraus, dass Schwarzenegger und Selenskyj als ehemalige Relationspuristen der Sequenz Attraktivität der medialen Relationsstruktur in der politischen Relationsstruktur zuerst eine Resozialisation im Sinne der Sozialisation auf das Widerstandsprinzip der Ankunftssequenz zu durchlaufen haben (ebd.). Diese Resozialisation auf die Sequenz Attraktivität der politischen Relationsstruktur ist folglich für Schwarzenegger und Selenskyj notwendig, um ihre Auffassungen über Erwartungen und Erwartungen auf Erwartungen entsprechend der politischen Relationsstruktur umzustellen, um sich Zirkulationsmöglichkeiten in der poltischen Relationsstruktur vom Standpunkt der Repräsentation zu verschaffen (ebd.). Die Resozialisation sieht dabei vor, dass sich nun sowohl Schwarzenegger als auch Selenskyj -- dem Verlauf des Schmetterlingspfades der Sequenz Attraktivität in der politischen Relationsstruktur entsprechend (vgl. Abb. 3.7 in ebd., 102) -- voll und ganz auf die Repräsentation ihrer Investitionen in die Verwirklichung der Attraktivierung ihrer selbst als Repräsentanten eines Kollektivs (vgl. ebd. 125) konzentrieren, wofür sie, wie wir noch sehen werden, vermehrt auf Medien, die nicht zum gängigen Repertoire der politischen Relationsstruktur gehören, zurückgreifen. Allein der Rückgriff auf Medien aus der Trickkiste des Showgeschäfts reicht allerdings nicht aus, damit sich Schwarzenegger und Selenskyj auf die Sequenz Attraktivität der politischen Relationsstruktur resozialisieren. Sie benötigen gleichsam auch Zugang zu geeigneten gesellschaftlichen Instanzen der Politik oder müssen, so ihnen der Zugang zu diesen Instanzen verwehrt bleibt, eigene Instanzen gründen, um sich Zirkulationsmöglichkeiten in der Politik zu verschaffen und ihre Zirkulation zu stabilisieren. Zu aller erst geht es jedoch darum, dass die gesellschaftlichen Instanzen beide Protagonisten im ihrem Wahlkampf unterstützen und gleichsam mit dafür Sorge tragen, dass sich Schwarzenegger und Selenskyj nicht nur im Falle eines Wahlsieges erneut in der politischen Relationsstruktur einschreiben können (vgl. ebd., 34-58), sondern auch im Zuge dessen in die Position eines Relationspuristen zurückzukehren. Diesen Aspekt werden wir im Folgenden unter Rekurs auf den Wahlkampfstab und den Wahlkampf Schwarzeneggers und Selenskyjs konkretisieren und beginnen erneut mit dem Fall Arnold Schwarzeneggers.

### 3.2 Der Wahlkampfstab des  _Governator_ Schwarzenegger und des _Diener des Volkes_ Selenskyj als Resozialisations- und Förderinstanzen des Politikbetriebs 

Die Resozialisation Schwarzeneggers und Selenskyjs auf die Sequenz Attraktivität in der politischen Relationsstruktur (vgl. Abb. 3.7 in ebd., 102) und zwar unter stetiger Berücksichtigung der Kernsequenz Repräsentation derselben Relationsstruktur folgt grundsätzlich dem Ziel, die Attraktivität Schwarzeneggers und Selenskyjs als Repräsentanten ihrer jeweiligen Kollektive und als Repräsentanten der Repräsentation ihrer Kollektive, d. h. einerseits der Kalifornier und des Bundesstaates Kalifornien und andererseits der Ukrainer und des Landes der Ukraine, tatsächlich zu verwirklichen (vgl. ebd., 125). Diese Verwirklichung der Attraktivität unserer beider Protagonisten als Reräsentanten ihrer Kollektive kann also nur darin bestehen, die Wählerschaft von deren Attraktivität als politische Anführer zu überzeugen, um dann auf dieser Grundlage die von ihnen angestrebten politischen Ämter zu gewinnen. Um dies jedoch sicherzustellen, kommen Schwarzenegger und Selenskyj nicht umhin, erstens in ihre Attraktivität als charismatische Führungspersönlichkeiten zu investieren bspw. über die Entwicklung einer politischen Agenda (ebd.). Zweitens müssen diese Investitionen in ihre Attraktivität als Repräsentanten Kaliforniens und der Ukraine aber auch an Reprasentation gewinnen (ebd., 125), damit schließlich ihre Attraktivität als politische Führungspersönlichkeit Verwirklichung findet und sich sowohl im Wahlsieg materialisiert als auch in der Amtseinführung manifestiert. Um dies zu gewährleisten, braucht es jedoch entsprechende Vermittlungsinstanzen, die Schwarzenegger und Selenskyj bei der Repräsentation der Investitionen in die Verwirklichung ihrer Attraktivität als Gouverneur von Kalifornien und Staatspräsident der Ukraine unterstützen. Diese Vermittlungsinstanzen entsprechen dem Wahlkampfstab, der sowohl von Schwarzenegger als auch von Selenskyj mobilisiert und rekrutiert wird, um zu gewährleisten, dass die Attraktivierung der beiden Protagonisten als politische Schwergewichte Verwirklichung und die Zirkulation beider Protagonisten von der US-amerikanischen und ukrainischen Traumfabrik in die Politik Stabilisierung findet. 

Für den Fall Arnold Schwarzeneggers lässt sich diesbezüglich zunächst einmal hervorheben, dass er über einen exklusiven Zugang zu politischen Experten und Expertinnen verfügt, die eine große Expertise in Fragen des politischen Wahlkampfs und der darauffolgenden Regierungstätigkeit verfügen und sowohl von Schwarzenegger persönlich als auch entlang der _weak ties_ [@Granovetter1973] bzw. des Sozialbilitätsnetzwerks [vgl. Abb. 7.1 in @PapilloudSchultze2022, 310] von Schwarzenegger rekrutiert werden. Diese Rekrutierung und mithin die Gründung einer "eigene[n] Organisation" [@Schwarzenegger2014, 491) setzt bei Schwarzenegger bereits mit Beginn des Jahres 2001 ein, also weit über zwei Jahre vor dem eigentlichen Wahlsieg Schwarzeneggers am 07. Oktober 2003. So ist bekannt, dass Schwarzenegger zu Beginn des Jahres 2001 nicht nur den Vorsatz fasst, seine "Chancen [...] für eine Kandidatur zum Gouverneur" zu ermitteln [@Schwarzenegger2014, 489], sondern er dafür auch ein 6-köpfiges politisches Beratungsteam anheuert (ebd., 489-492). Dieses Beratungsteam markiert den Beginn der Gründung einer "eigene[n] Organisation" (ebd., 491), d. h. einer für Schwarzeneggers Kandidatur zuständigen politischen Instanz, die insofern die Grundlagen zur Verwirklichung der Attraktivität Schwarzeneggers als zukünftigen Gouverneur erarbeiten soll, als Schwarzenegger den Auftrag erteilt, eine Wahlkampfkampagne mit einer politischen Agenda, mit Slogans und einem Fundraisingkonzept sowie eine Wahlkampfstrategie zu erarbeiten (ebd., 490-491, 511-512; vgl. auch @Barabak2013]. Das 6-köpfige Team rekrutiert sich dabei, wie auch die Ausdehnung desselben im August 2003, vollständig aus dem inneren Kreis des Politberatungsteams, das einst den Republikaner Peter Barton "Pete" Wilson in politische Ämter auf Landes- und Bundesebene gehoben hat [vgl. @Schwarzenegger2014, 497; vgl. auch @Desert2003; @Leduff2003]. Allen voran sind hier Bob White und George Gorton zu nennen, wobei White während der Wahlkampfs von Schwarzenegger "das Tagesgeschäft der Kampagne [leitet]" und Gorton "Schwarzeneggers Chefstratege [ist]" [@Leduff2003].^[White war überdies drei Jahrzehnte für Wilson "als Stabschef in der Staatsversammlung Kaliforniens, im Büro des Bürgermeisters von San Diego, im US-Senat in Washington D.C. und im Büro des Gouverneurs in Sacramento tätig" [@White2024] und gilt als einer "der wichtigsten Politikberater in Sacramento" [@Schwarzenegger2014, 489]. Demgegenüber leitete Gorton "alle erfolgreichen Gouverneurs- und US-Senatswahlen von Gouverneur Pete Wilson" und gilt als ein hoch dekorierter "politischer Berater der Republikanischen Partei" [@Wallace1994; vgl. auch @Bennett2008b]. Den Chef-Stratege Gorton soll Schwarzenegger laut Medienberichten bereits im Jahr 2000 als ersten politischen Berater engagiert haben [@Bennett2008a; @Bennett2008b].] Gorton war zudem "in den nationalen Wahlkampfteams der Präsidenten Richard Nixon, Gerald Ford und Ronald Reagan tätig", und leitete bereits nationale Wahlkampagnen "in Russland, Panama, Rumänien, der Tschecheslowakei" und "Kanada" [@Wallace1994].] Über Gorton konnte Schwarzenegger zudem auf die zwei Partner "Joe Shumate und Dick Dresner" zurückgreifen, mit denen Gorton seit dessen "Beteiligung an der Wiederwahlkampagne von Boris Jelzin" zusammen arbeitet (ebd.). Shumate fungierte im Wahlkampf Schwarzeneggers als Chefstratege [@Desert2003] und betreut während des Wahlkampfes "Umfragen und Fokusgruppen für Schwarzenegger" [@Marin2010], wohingegen der "hoch angesehene Meinungsforschungsguru" [@Hamilton2003] Dick Dresner als Meinungsforscher im Wahlkampf tätig ist [@Desert2003]. Auch mit an Bord war in dieser frühen Phase der Kampagnenentwicklung "der republikanische Medienexperte", PR-Berater und "Experte für politische Slogans" Donald Sipple [@Schwarzenegger2014, 497], der in Schwarzeneggers Kampf ums Gouverneuramt für dessen Wahlwebespots zuständig war [@Leduff2003].^[Sipple "[gilt] als einer der effektivsten Werbefachleute in der Politik" aus dem Lager der Republikaner [@Leduff2003] und hat zudem die "Wahlkampagnen von Bob Dole, George Bush und seinem Sohn George W. Bush, sowie von Pete Wilson entworfen" [@Blow1997]. Er erstellt ferner in Vorbereitung der Wahlkampagne Schwarzeneggers "Drei-Minuten-Clips, die wiederum "Fokusgruppen von Wählern vorgeführt [wurden]" [@Schwarzenegger2014, 497].] Und schließlich zählt zu diesem 6-köpfigen Politberatungsteam auch der ehemalige Gouverneur Kaliforniens Pete Wilson, der höchst persönlich "als einer der Co-Vorsitzenden des Wahlkampfs" Schwarzeneggers fungiert [@Leduff2003]. Mit Bekanntgabe der Kandidatur Schwarzeneggers um das Amt des Gouverneurs kam es dann zu einer Erweiterung des Wahlkampfstabs durch weitere Polit-Experten, auf die Schwarzenegger durch seine engen Kontakte einerseits zu führenden Politikern der Republikanische Partei und andererseits zur Gönnerschaft der politischen Wohltätigkeitsarbeit des Kennedy-Shriver-Clan zurückgreifen konnte. Zu diesem Personenkreis gehören wiederum David Dreier, Co-Vorsitzender der Kampagne Schwarzeneggers (ebd.; vgl. auch @Schwarzenegger2014, 528), Patricia Clarey,^[Sie war zudem die ehemalige Stellvertreterin von Ex-Gouverneur Wilson [@Leduff2003].] die "die Logistik [leitet]" und "als Bindeglied zu Schwarzeneggers Frau Maria Shriver [gilt] [@Leduff2003]. Ebenfalls zu diesem Kreis gehören Sean Walsh, einer der "Wahlkampfsprecher" (ebd.), Dick Riordan, Darrell Issa und Ed Leamer, die Schwarzenegger Themenseminare geben [@Schwarzenegger2014, 528], sowie Abel Maldonado, ebenfalls Co-Vorsitzender der Kampagne und "Sprecher in Sachen Einwanderung" [@Leduff2003]. Ferner seien noch Martin Wilson, "Co-Manager der täglichen Wahlkampftätigkeit" (ebd.), Mike Murphy, auch Chefstratege des Wahlkampfs [@Schwarzenegger2023c; vgl. auch @Schwarzenegger2014, 530] und natürlich seine Ehefrau Maria Shriver, die "zwei Generationen Autorität und Erfahrung ein[brachte]" [@Schwarzenegger2014, 525], zu nennen, die ebenfalls zum Wahlkampfteam Schwarzeneggers gehören.^[Selbstredend ist nicht davon auszugehen, dass sich das Wahlkampfteam Schwarzeneggers lediglich auf diese 16 Personen reduziert. Es darf allerdings angenommen werden, dass die aufgeführten Expertinnen und Experten den festen Kern des Wahlkampfteams Schwarzeneggers gebildet haben und die Tätigkeiten der weiteren Wahlhelferschaft koordinierten und ineinander fließen ließen.] 

Hieran wird deutlich, dass das Wahlkampfteam Schwarzeneggers nicht nur aus höchst erfahrenen und "'kampferprobten' alten Hasen des ehemaligen Gouverneurs Pete Wilson" [@Desert2003; vgl. auch @Leduff2003; @White2024; @Marin2010; @Hamilton2003; @Blow1997; @Wallace1994] besteht, sondern sich zudem fast ausschließlich aus Angehörigen, Mitstreitern, Verbündeten und Mitgliedern aus dem Lager und Umfeld der republikanischen Partei zusammensetzt. Dies ist keineswegs Zufall, sondern trägt vielmehr die Früchte zur Schau, die Schwarzenegger zum Zeitpunkt seines Wahlkampfs deshalb zu ernten imstande ist, weil er spätestens seit seiner Einbürgerung im Jahr 1983 selbst bekennender Republikaner und Parteimitglied ist [@Schwarzenegger2014, 303, 309], er sehr enge Kontakte -- allen voran zu Ex-Gouverneur Pete Wilson und den Ex-Präsidenten Richard Nixon und George Bush Senior (ebd., 305ff., 382ff., 421f. ] -- zur Republikanischen Partei sowohl in Sacramento als auch im Weißen Haus unterhält (ebd., 384, 407ff.), mit seiner Starpower immer wieder "nach Kräften" republikanische Spitzen- und Landespolitiker in deren Wahlkämpfen unterstützt (ebd., 307, 384ff.) und zu Amtseinführungen und Parteitagen der Republikaner eingeladen wird (ebd., 381ff.).^[So begleitete Schwarzenegger bspw. George Bush Senior auf seiner Wahlkampftour zur Präsidentschaftswahl [@Schwarzenegger2014, 381ff.], wo er wertvolle Einblicke in das Wahlkampfgeschäft erhielt [@Schwarzenegger2014, 381ff.]. Zudem ist anzumerken, dass der _Regency Club_ einer der wichtigsten Ausgangspunkte für Schwarzeneggers Verbindungen vornehmlich in konservative Kreise der Republikaner darstellen dürfte; einem noblen "Zufluchtsort für die Business-Elite" von Los Angeles, der vsl. 1981 seine Pforten öffnete [@LA2011]. Besitzer des Regency Clubs war Investment-Unternehmer und Selfmade-Man David Murdock, auf Platz 949 der reichsten Menschen der Welt [@Forbes2024], der regelmäßig republikanische Wahlkämpfer wie Donald Trump und Pete Wilson mit vier- bis sechssstelligen Beträgen unterstützt hat [@Murdock2016]. Im Regency Club waren jedoch nicht nur "[v]iele konservative Geschäftsleute [...] Stammgäste" [@Schwarzenegger2014, 304]. Es gingen dort auch namenhafte Landes- und Bundespolitiker der Republikaner ein und aus. Unter ihnen bspw. "[e]influssreiche Leute aus der Regierung Reagan" (ebd., 305), aber auch George Deukmejian, der von 1967 bis 1979 erst kalifornischer Senator und von 1983 bis 1991 Gouverneur von Kalifornien war [@CSL2019a], oder Pete Wilson, langjähriger Bekannter von Richard Nixon, ebenfalls ehemaliger US-Senator Kaliforniens und von 1991 bis 1999 Gouverneur von Kalifornien [@CSL2019b]. Der Regency Club diente entsprechend auch immer wieder als Ort für Wahlkampfveranstaltungen bspw. für Deukmejian und Wilson [@Schwarzenegger2014, 305]. Im Regency Club fand schließlich auch eine Fundraising-Party anlässlich des Wahlkampfs von Schwarzenegger statt, die von Wilson organisiert wurde, um Großspender zu akquirieren (ebd., 525). Daneben bewegt sich Schwarzenegger aber auch regelmäßig in hochdekorierten "liberaleren Kreisen" (ebd.), wobei als ursächlich hierfür seine Zugehörigkeit zum Kennedy-Shriver-Clan und die von ihm selbst oder Eunice Shriver geleistete Wohltätigkeitsarbeit zu nennen ist [@Schwarzenegger2023b].]

Über eine derart stark ausgeprägte Rückendeckung, Unterstützung und Förderung durch eine etablierte politische Partei verfügt Selenskyj nicht, was sich ebenso auf die Bildung seines Wahlkampfstabs auswirkt, wie die Mittel tangiert, mit denen Selenskyj seinen Wahlkampf bestreitet. Dieser auf den ersten Blick als Nachteil erscheinende Umstand rechtfertigt sich damit, dass in der Zeit, als sich Selenskyj für das Präsidentschaftsamt bewirbt, die Oligarchen der Ukraine nicht nur "weite Teile der ukrainischen Wirtschaft" und "der ukrainischen Medien" kontrollieren, sondern auch "[weite Teile] [...] des gesamten ukrainischen Staatsapparates" [@Much2021]. Die Zerschlagung jener Seilschaften, die sich quer durch alle Gesellschaftssphären der Ukraine ziehen und auf deren Boden die Korruption bis ins Maßlosen gedeiht, gehört, neben der Befreiung des Donbas, zu den obersten Zielen, die sich mit Selenskyjs Präsidentschaftskandidatur und dessen politischer Agenda verbinden [@Iwan2019; vgl. auch @Zelenskyj2019; vgl. auch @Ukraine2019]. Vor diesem Hintergrund ist es nur allzu verständlich, dass weder Selenskyj den Anschluss an eine in der Werchowna Rada, dem Parlament der Ukraine, vertretene Partei sucht, noch die Mitglieder der ukrainischen Parteiinstanzen einen Präsidentschaftskandidaten nominieren würden, der ihnen allen in einer solchen Deutlichkeit den Kampf erklärt hat [@Zelenskyj2019]. Entsprechend ist Selenskyj gezwungen, seine eigene politische Parteiinstanz zu gründen, um für eine formale und praktische Grundlage seiner etwaigen Präsidentschaft Sorge zu tragen, sich für die Wählerschaft in glaubwürdiger Weise gegen die "herrschende Klasse" richten zu können und sich von dieser gleichsam erkennbar abzusetzen [@Iwan2019]; und zwar ebenso, wie der Held der Serie _Diener des Volkes_ Wassyl Holoborodko, dessen Leinwand-Präsidentschaft ganz im Zeichen des Kampfes gegen die korrupte politische Klasse steht (ebd.). Insofern besteht also für Selenskyj und dessen engsten Kreis der Produktionsfirma Studio Kwartal 95 die erste Herausforderung darin, eine eigene Partei zu gründen, als deren Präsidentschaftskandidat dann Selenskyj in Erscheinug treten kann.

Auf die Notwendigkeit einer Parteigründung wird Selenskyj nach Angabe Rogacins vonseiten des Anwalts Andrij Bohdan aufmerksam gemacht, der Selenskyj Anfang des Jahres 2016 im Auftrag des Oligarchen Ihor Kolomojskyj konsultiert, um ihn davon zu überzeugen, 2019 für das Amt des Staatsoberhauptes zu kandidieren [@Rogacin2022, 126]. Kurz darauf, im April 2016, wird dann die "_Partei des entschlossenen Wandels_ unter dem Vorsitz von Iwan Bakanow offiziell registriert" [@Sluga2024] und im Dezember 2017 in _Diener des Volkes_ umbenannt (ebd., vgl. auch @Rudenko2022, 130).^[Dass die _Partei des entschlossenen Wandels_ nicht von Anfang an _Diener des Volkes_ hieß, ist darauf zurückzuführen, dass zuerst "der Name der Serie gesichert werden musste, bevor er von Außenstehenden politisch genutzt werden konnte" [@Iwan2019].] Damit hat Selenskyj nicht nur eine eigens für ihn ins Leben gerufenen gesellschaftliche Instanz gegründet, die Selenskyj im Januar 2019 offiziell als Spitzenkandidat für die Wahl nominiert [@Sluga2024], den Vorsitz der Partei übernimmt auch der Anwalt und Leiter des Studio Kwartal 95 Iwan Bakanov [@IMI2020], ein Jugendfreund Selenskyjs [@Iwan2019], unter dessen "Führung die Bildung des Parteiteams" 2016/2017 beginnt [@Sluga2024]. Entsprechend sind an dieser Stelle neben der _Partei des entschlossenen Wandels_ zwei Vermittlungsinstanzen genannt, die Selenskyj bei dessen Vorbereitungen einer Präsidentschaftskandidatur unterstützen: Einerseits der engste Kreis des Studio Kwartal 95 und andererseits der Oligarch Kolomojskyj, der Selenskyj von jeher "massiv gefördert" hat [@Hassel2019], die Präsidentschaft Selenskyjs jedoch vorwiegend mittelbar unterstützt, da er Bohdan als Vorhut abstellt, damit dieser als eine Art Transferinstanz zwischen Selenskyj und ihm in Erscheinung treten kann [@Rudenko2022, 49]. So wurde bspw. bekannt, dass Selenskyj in den darauffolgenden zwei Jahren, "laut Journalisten des ukraischen Programms von Radio Free Europe [...] mindestens 14 Mal" Kolomojskyj in Genf und Israel besucht hat -- die letzten Male nach der Entscheidung über seine Präsidentschaftskandidatur im Herbst 2018" [@Hassel2019; vgl. auch @Rudenko2022, 49]. Bei diesen Reisen wurde Selenskyj stets von Bohdan begleitet, der zwar Ende 2018 als einer der wichtigsten "Selenskyj-Vertrauten" gilt, der sich aber auch während des Wahlkampfs eher im Hintergrund hält [@Rudenko2022, 49].^[Bohdan kannte sich nach Angabe Rudenkos im ukrainischen Politikbetrieb und dessen Intrigen bestens aus. Zuletzt war er als politischer Barater von Gouverneur Kolomojskyj und anschließend auch anderweitig für den Oligarchen und seine 'Privat-Gruppe' tätig [vgl. @Rudenko2022, 48f.]. Er begann seine politische Zirkulation auf einem Posten bei der Westukrainischen Eisenbahn, zieht nach Kiew als sein Vorgesetzter Verkehrsminister wird und arbeitet als Anwalt bis er schließlich die Position des stellvertretenden Justizministers innehat. Anschließend fungiert er als "ehrenamtlicher Berater des Parlamentsabgeordneten Andrij Portnow", als "Regierungskommissar für Fragen der Antikorruptionspolitik und kandidiert daraufhin zwei Mal als Abgeordneter des Ukrainischen Parlaments Werchowna Rada ohne Erfolg, wobei er das zweite Mal zuerst für den "Block Petro Poroschenko" angetreten ist, um dann von demselben Block unrechtmäßig von Liste gestrichen zu werden (ebd., 48-49).]
   
Neben Kolomojskyj und dessen Transferinstanz Bohdan, die mittelbar und unmittelbar zu Selenskyjs Wahlkampfstab gezählt werden können, wobei sich für beide Instanzen nicht sagen lässt, welche konkrete Rolle ihnen bei Selenskyjs Vorbereitungen zukommt -- außer, dass sich "der Kandidat von ehemaligen Bodyguards des Oligarchen schützen und in dessen Autos herumkutschieren [ließ]" [@Much2021]--, beginnen Selenskyj und sein Kwartal Team im Herbst 2018 mit der Bildung eines Wahlkampfstabs, um die doppelte Einschreibung in die politische Relationsstruktur zu gewährleisten [@Rogacin2022, 131]. Zu diesem Zweck gewinnt das Team zuerst den Politologen und "einen der vielversprechendsten jungen Politiker der Ukraine" Dmytro Rasumkow (ebd., 132), der erst für Selenskyj als Wahlkampfstratege tätig ist und im Mai 2019 die Nachfolge von Iwan Bakanow als Vorsitzender der Partei _Diener des Volkes_ übernimmt [@Sluga2024], während Bakanow in die Position des Leiters des Sicherheitsdienstes der Ukraine weiterzirkuliert [@IMI2020; vgl. auch @Rudenko2022]. Auch mit an Bord ist der Medien- und Politikexperte Mykyta Porturajew, der als Berater sowohl für die Wahlakmpfkampagne und deren Programmatik als auch für Fragen der internationalen Politik zuständig ist, heute als _Diener des Volkes_-Abgeordneter in der Werchowna Rada sitzt und dort zum stellvertretenden Vorsitzenden für Humanitäres und Informationspolitik gewählt wurde [@OSCE2023]^[Zudem fungiert Porturajew auch als Berater der Kampagne "Sluga narodu" für die ukrainischen Parlamentswahlen [@OSCE2023]. Er machte am 23. Februar 2023 von sich Reden, als er in der Position des Leiters der ukrainischen Paralamentsdelegation bei einem OSZE-Meeting in Wien zur "Begrüßung den Hitlergruß in Richtung der Abgeordneten [zeigte]" [@Oys2023; vgl. auch @Rogacin2022, 133].] Darüber hinaus sind eine ganze Reihe von Mitwirkenden aus dem Studio Kwartal für den Wahlkampfstab Selenskyjs tätig [@Rogacin2022, 131], wobei hier die Datenlage etwas dürftig ausfällt. Sicher ist jedoch, dass die Co-Vorsitzenden des Studio Kwartal 95, d. h. die Gebrüder Shefir, in die Wahlkampfaktivitäten und -kampagne eingebunden waren [@Rudenko2022, 123; vgl. auch @Iwan2019]. Zudem ist anzunehmen, dass ein Großteil der 36 Personen [eigene Recherche auf der Grundlage der Angaben von @Rudenko2022, 97-99 und @IMI2020], die vor der Präsidentschaft nachweislich für Studio Kwartal 95 oder deren Tochtergesellschaften gearbeitet haben und nach der Präsidentschaftswahl mit Selenskyj bis in höchste Regierungskreise tranversal und aufsteigend zirkuliert sind, bereits mit bestimmten Tätigkeitsfeldern in Selenskyjs Wahlkampfstab betraut waren.^[Jene 36 Personen wurden laut Presserecherchen zu "Assistenten, Stellvertretern und Leitern des Präsidialamtes ernannt", zirkulierten in "Positionen in den Sicherheitsorganen der Ukraine und in zentralen Exekutivorganen" oder wurden "Mitglieder von Aufsichtsräten und Ausschüssen" sowie "zu Abgeordneten der Ukraine gewählt" [@IMI2020; vgl. für Näheres @IMI2020; @Rudenko2022, 97-99]. Die Besetzung wichtiger Regierungsposten durch Mitglieder des Wahlkampfstabs scheint allerdings eine durchaus gängige Praxis zu sein, wenngleich diese sich im Falle Selenskyjs aus den Kollegium des Studio Kwartal 95, also aus der Medienbranche, rekrutieren, was nicht zuletzt darauf zurückzuführen ist, dass Selenskyj aufgrund seines Kampfes gegen Korruption nur über wenig Rückhalt unter etablierten Politikprofis verfügt und zu einem gewissen Personalmangel geführt haben dürfte [@Iwan2019; vgl. auch @Zelenskyj2019 & @Ukraine2019]. Eingedenk dieser besonderen Situation mag der Vorwurf der Vetternwirtschaft [@IMI2020; @Rudenko2022, 97-99] zwar formal begründet sein, er wird allerdings durch die Tatsache relativiert, dass auch Schwarzenegger nach seiner Wahl gut 100 Posten zu besetzen hatte, wofür er ebenfalls vermehrt auf Mitglieder seines Wahlkampfstabs zurückgegriffen hat [@Schwarzenegger2023c].] Unter ihnen befinden sich bspw. Wolodymyr Woronow, "Parlamentsabgeordneter" von _Diener des Volkes_ und ehemals Mitarbeiter von Kwartal-Konzert, Andrij Jermak, "Leiter des Büros des Präsidenten" und ehemals Anwalt des Studio Kwartal 95, Jurij Korjawtschenkow, "Parlamentsabgeordneter" von _Diener des Volkes_ und ehemals "administrativer Leiter von Studio Kwartal 95", oder auch Maksym Tkatschenko, ebenfalls "Parlamentsabgeordneter" sowie "Berater des Nationalen Sicherheits- und Verteidigungsrats" und ehemals "Geschäftsführer" von Kwartal-Konzert, um nur einige zu nennen [@Rudenko2022, 97-92]. Diese These findet Unterstützung in einer Erzählung von Rudenko über den Besuch Selenskyjs in Begleitung dreier Mitarbeiter seines Wahlkampfteams -- namentlich Ruslan Rjaboschapka, Oleksandr Danyljuk und Iwan Bakanow -- bei Emmanuel Macron am 12. April 2019 in Paris [@Rudenko2022, 176f.]. Hierin wird auch beleuchtet, welche Positionen die drei Begleiter mit Amtsantritt Selenskyjs bekleiden. So zirkuliert Rjaboschapka, der zuvor auf Regierungsebene wie bei NGOs mit Korruptionsbekämpfung betraut war und von 2014 bis 2016 stellvertretender Justizminister war, in die Position des Generalstaatsanwalts, während Bakanow, vormals Anwalt, Mitgründer und Leiter des Studio Kwartal 95 [@IMI2020], ukrainischer Geheimdienstchef wird, und Danyljuk, ehemals Finanzminister [@Iwan2019], die Position des Sekretärs des Nationalen Sicherheits- und Verteidigungsrates erhält [@Rudenko2022, 178]. Zudem zeigt dieses Beispiel, dass Selenskyj durchaus auch erfahrene und seiner politischen Agenda folgende Politiker für sein Wahlkampfteam gewinnt. Zusammenfassend lässt sich also sagen, dass sich das Wahlkampfteam Selenskyjs zwar sowohl aus politisch erfahrenen Akteuren als auch aus Medienschaffenden speist, sich darin aber auch "viele junge Freiwillige" befunden haben sollen, die "mit digitalen Medien vertraut [waren]" [@Rogacin2022, 131], wodurch Selenskyjs Wahlkampfstab schließlich 500 Personen umfasst haben soll (ebd.).^[Laut Angabe Rogacins waren all diese Mitglieder des Wahlkampfstabs, wie auch im Falle Schwarzeneggers, unterschiedlichen Abteilungen zugeordnet, von denen die einen bspw. "für den Kontakt zu den ukrainischen und ausländischen Journalisten" zuständig waren, während andere sich bspw. um "die Betreuung der sozialen Medien" gekümmert haben [@Rogacin2022, 131]. Letztere Abteilung dürfte das größte und gleichsam wichtigste Ressort dargestellt haben, da eine der zentralen Wahlkampfstrategien darin zu erkennen ist, dass "ein großer Teil des Wahlkampfs [...] auf Social-Media-Plattformen" bestritten wird (ebd.; vgl. auch @Iwan2019; @Keller2019a; @Hassel2019).]

Wir sehen also, dass Schwarzenegger und Selenskyj keineswegs als Einzelkämpfer ihrer Resozialisation auf die Sequenz Attraktivität in der politischen Relationsstruktur zu betrachten sind, sondern umfangreich von eigens dafür zusammengestellten bzw. eingerichteten Vermittlungsinstanzen unterstützt wurden. Diese Vermittlungsinstanzen bilden einerseits die entsprechenden Parteien, unter deren Flagge die Kandidaturen unserer beiden Protagonisten offiziell und formal stehen. Andererseits fungieren aber auch die eigens für die Unterstützung des Wahlkampfs gebildeten Wahlkampfstäbe als Vermittlungsinstanzen, deren vorrangiges Ziel wiederum darin besteht, die Attraktivierung beider Kandidaten als politische Anführer mit Blick auf möglichst alle Wählergruppen zu fördern [vgl. @Iwan2019; @Schwarzenegger2014, 490, 497; @Martin2010]. Entsprechend arbeiten die Kandidaten selbst und mit ihnen ihre Wahlkampfstäbe während des Wahlkampfes, der bei Schwarzenegger knapp neun Wochen und bei Selenskyj 16 Wochen andauert, unermüdlich daran, in die Attraktivität Schwarzeneggers und Selenskyjs als charismatische Führungspolitiker zu investieren und diesen Investitionen zur Sichtbarkeit unter der Wählerschaft zu verhelfen, damit sich die Attraktivität der einstigen Film- und Serienhelden als Politiker-Neulinge bzw. als Nicht-Politiker abseits des "Establishments" verwirklicht [@PapilloudSchultze2022, 125; vgl. auch den Schmetterlingspfad in Abb. 3.7 in ebd., 102]. Gelingt dies, so hieße das, dass Schwarzenegger und Selenskyj gemeinsam mit ihren Wahlkampfstäben als Vermittlungsinstanzen nicht nur die doppelte Einschreibung in der Sequenz Attraktivität der politischen Relationsstruktur geglückt ist, was auch bedeutet, dass Teile der Wahlkampfstäbe entsprechende Positionen auf höchster politischer Ebene bekleiden. Es hieße auch, dass Schwarzenegger und Selenskyj aus ihrer Anwärterposition in der dritten Schicht der ersten Akteurkategorie, und zwar über den Wechsel der _Relation durch Position_, in die erste Schicht derselben Akteurkategorie weiterzirkulieren, von wo aus sie als Relationspuristen wiederum in die Sequenz Investition der politischen Relationsstruktur weiterzirkulieren könnten. Um dies zu realisieren, ist es jedoch zunächst erforderlich, aus Schwarzenegger und Selenskyj politische Anführer zu machen, weshalb wir uns nun ansehen, wie deren Wahlkampfstäbe in die Verwirklichung der Attraktivität beider Kandidaten investieren und auf welche Weise diese Investitionen der Öffentlichkeit vermittelt werden, wobei wir besonderen Wert auf die dabei verwendeten Medien legen werden.

### 3.3 Die Attraktivierung des  _Governator_ Schwarzenegger und des _Diener des Volkes_ Selenskyj und deren Mediationen 

Nachdem wir nun gezeigt haben, dass Schwarzenegger und Selenskyj Weiterzirkulation in der Politik nur durch die Unterstützung von eigens dafür gebildeten bzw. rekrutierten gesellschaftlichen Instanzen gelingen konnten, wollen wir uns nun deren kollektiver Wahlkampftätigkeit zuwenden, die sich schließlich im Wahlsieg beider Kandidaten manifestiert, zu deren Positionswechsel von der dritten in die erste Schicht der ersten Akteurkategorie in der Sequenz Attraktivität und mithin zur Stabilisierung von deren Zirkulation in der Politik geführt hat. Dabei konzentrieren wir uns vor allem auf die Frage, auf welche Register und Mediationen bei der Gestaltung des Wahlkampfes primär zurückgegriffen wurde, um Schwarzenegger und Selenskyj als politische Schwergewichte unter ihrer Wählerschaft zu attraktivieren. Wir beginnen mit dem Fall Selenskyjs, um im Kontrast hierzu die wesentlichen Merkmale des Wahlkampfes von Schwarzenegger in den Fokus zu rücken.

Für Selenskyjs gesamte Wahlkampfkampagne ist charakteristisch, dass er kaum _en persona_ in der Öffentlichkeit präsent ist [@Stewart2019] und infolgedessen sein Wahlkampfstab auf bewährte Register und Mediationen der politischen Relationsstruktur zur Entwicklung von Wahlkampftätigkeiten verzichtet. Das bedeutet, dass während des gesamten Wahlkampfes -- von wenigen Ausnahmen abgesehen -- nicht auf gängige Formate und Register, wie bspw. "floskelhafte Reden", "Besuche in Städten und an Arbeitsplätzen" [@Iwan2019], politische Diskussionen, kritische Interviews [@Keller2019a; vgl. auch @Nelles2019; @Gon2019a; @Stewart2019], Pressekonferenzen, Besuche bei Talk Shows oder gar kommerzielle Wahlkampfwerbespots oder eine Wahlkampftour zurückgegriffen wurde. Damit hebt sich Selenskyj nicht nur für die Wählerschaft erkennbar von Amtsinhaber Petro Poroschenko oder der Kandidatin Julija Tymoschenko ab. Er unterstreicht damit auch, dass er nicht zur politischen Klasse der Ukraine gehört, indem er die etablierten Tätigkeitsregister und Mediationen der politischen Repräsentation von Kollektiven und der Attraktivierung der Repräsentation der Ukrainer gekonnt umschifft. Stattdessen setzt Selenskyj mit seinem Team primär auf das Mediationsrepertoire der medialen Relationsstruktur, das er jedoch nicht, wie bei der Tätigkeitsentwicklung in der medialen Relationsstruktur typisch, zur Attraktion seiner selbst als Entertainer oder Kabarettist einsetzt, sondern vielmehr zur Attraktivierung seiner selbst als charismatischen Führungspersönlichkeit. Entsprechend wird zur Repräsentation der Investitionen in die Verwirklichung der Attraktivität Selenskyjs als politischer Anführer vorrangig von Medien wie Videobotschaften und Videoclips Gebrauch gemacht [@Keller2019a; @Keller2019b], die Selenskyj entweder selbst "mit dem Smartphone auf[nimmt]" [@Keller2019a] oder die in Begleitung eines Kamerateams entstehen [@Nelles2019; vgl. auch @Zelenskyj2019]. Auch die Verbreitungspraxis jener Videoclips und -botschaften ist eher typisch für die die mediale Relationsstruktur, wenn das Team um Selenskyj diese über den Social-Media-Kanal Instagram mit 2,6 Mio. Followern und den YouTube-Kanal von _Quartal95_ mit 2,3 Mio. Abonennten lanciert [vgl. @Nelles2019]. Daneben nutzt Selenskyjs Wahlkampfteam eine 550.000 userstarke offizielle Kampagnen-Webseite [@Zelenskyj2019], die zur Mediation von Interaktionsmöglichkeiten zwischen dem Kandidaten und dessen potentieller Wählerschaft ebenso Einsatz findet, wie zur Popularisierung der atypischen "Wahlwerbespots" (ebd.).^[Auch das rege Treiben in der Wahlkampfzentrale Selenskyjs konnte die Wählerschaft per Livestream bis Mitte Februar 2019 nachverfolgen [@Nelles2019].]. 

Den Videobotschaften und -clips verstanden als Bestandteil eines medialen Tätigkeitsreportoires kommt im Wahlkampf Selenskyjs -- in Kongruenz zur Zirkulationsdynamik und den Prinzipien in der medialen Relationsstruktur [vgl. dazu @PapilloudSchultze2022, 111-119] -- insgesamt die Eigenschaft zu, dass das Wahlkampfteam Selenskyjs über deren Einsatz die unzähligen Individualitäten der ukrainischen Wähler:innen besser adressieren kann (ebd., 291). Infolgedessen generieren die Medien selbst zu Instanzen der Vermittlung zwischen Selenskyj als Präsidentschaftskandidaten und den unzähligen Gruppen der Wählerschaft und tragen so maßgeblich zur Steigerung von Selenskyjs Chancen auf einen Wahlsieg, d. h. auf Reziprozität in der politisschen Relationsstruktur, bei (ebd., 116). Dies zeigt sich einerseits darin, dass es Selenskyj gelungen ist, "die sonst eher passiven jungen Ukrainer im Osten zu mobilisieren" [@Gon2019], indem er im Unterschied zu Poroschenko qua Medien ein "Modell des Patriotismus" zu verkörpern imstande war, das ungeachtet der Annexion der Halbinsel Krim und des Donbas durch Russland sowohl auf die "Ukranisierung des öffentlichen Raums" als auch eine "antirussische[n] Rhetorik" verzichtet [@Iwan2019; vgl. auch @Zelenskyj2019]. Andererseits gelingt es dem Wahlkampfteam aber ebenso, auf Basis der durch Videobotschaften verbreiteten Forderung der Korruptionsbekämpfung, der Anhebung des Lebensstandards und die Verurteilung der Aggression Russlands [vgl. @Zelenskyj2019], konservative Wählergruppen ebenso für sich zu gewinnen, wie junge Wähler:innen und gesellschaftliche Gruppen mittleren Alters, und zwar ungeachtet ihrer politischen Haltung (ebd.; vgl. auch @Gon2019). Damit ist sogleich angesprochen, dass der beinahe ausschließliche Rekurs auf Medien, die kaum Rückfragen gestatten, und das hohe Aufkommen an Medien, für das Selenskyj und sein Team sorgen, zwar für die mediale Relationsstruktur durchaus typisch ist, nicht aber in der politischen Relationsstruktur zur gängigen Praxis gehört. Entsprechend lässt sich festhalten, dass über Selenskyj und dessen Stab nicht nur Medien vermehrt Einzug in die politische Relationsstruktur halten und als politisches Werkzeug der Attraktivierung Selenskyjs als fähigen Staatsmann zweckentfremdet bzw. umfunktioniert werden, sondern gleichsam das Prinzip der Verführung, welches für die mediale Relationsstruktur elementar ist (ebd., 116f.), in die politische Relationsstruktur Einzug hält und das Prinzip der Vertretung diesem unterordnet. Entsprechend besteht eine wesentliche Wahlkampfstrategie Selenskyjs und dessen Quasiinstanz des Wahlkampfs darin, Selenskyjs Vertretungsmacht in der Politik durch dessen Verführungsmacht, in die stetig investiert wird, zu stärken (ebd., 291-292), um auf diesem Weg die Reziprozitätsmöglichkeiten von Selenskyj und dessen Stab in der politischen Relationsstruktur zu erhöhen und die Zirkulation Selenskyjs in der Politik zu stabilisieren. Es ist daher keineswegs Zufall, dass die Medienhäuser in ihrer Berichterstattung u.a. von einem "[s]kurilen Wahlkampf" [@Keller2019a] oder "einer ungewöhnlichen Kampagne" sprechen [Iwan2019].

Im Unterschied dazu, sorgt der aus Polit-Experten bestehende Wahlkampfstab Schwarzeneggers nicht nur dafür, dass ihr Kandidat während des gesamten Wahlkampfes in der Öffentlichkeit omipräsent ist. Er sorgt auch dafür, dass auf klassische Mediationsformate und Register der Tätigkeitsentwicklung in der politischen Relationsstruktur zurückgegriffen wird, diese Mediationen und Tätigkeitsregister jedoch gleichsam über das Mediationsrepertoire der medialen Relationsstruktur an Verbreitung gewinnen. Obgleich also die Verwendung vonehmlich politischer Mediationen und die Verwendung der Register streng dem sequentiellen Pfad der Tätigkeitsentwicklung in der Sequenz Attraktivität der politischen Relationsstruktur folgt, erfolgt dessen Verbreitung maßgeblich über die bewusste Indienstname der medialen Relationsstruktur, was sich in folgendem strategischen Kalkül ausdrückt: "Alles sollte im großen Stil durchgezogen werden. Es sollte um _politische Führung_ gehen, um _große Projekte_ und _grundlegende Reformen_ [...], die eine breite öffentliche Zustimmung erhalten würden" [@Schwarzenegger2014, 513f.; eig. Herv.].

Entsprechend dieser Wahlkampfstrategie wird im ersten Schritt jeder Wahlkampftätigkeit für und von Schwarzenegger immer zuerst in die Entwicklung von Wahlprogrammen und themenspezifischen Positionen, d. h. in die Erarbeitung einer politischen Agenda des Kandidaten, investitiert [@PailloudSchultze2022, 125; vgl. auch Abb. 3.7, ebd. 102]. Exemplarisch sei hier auf die Gründung eines _Rates zur wirtschaftlichen Erholung Kaliforniens_ [vgl. @Feldman2003], bestehend aus dem demokratisch-republikanischen Vorstandsduo Warren Buffett ^[Buffett wird wegen seiner Investmenterfolge weithin auch als "Orakel von Omaha" bezeichnete [@Gallagher2019] und übernimmt in Schwarzeneggers Wahlkampfteam die Rolle des leitenden Wirtschaftsberaters [@Feldman2003].] und George Schultz ^[Schultz "war unter Reagan Außenminister und unter Nixon Finanzminister" sowie "Fellow" an der Hoover Institution in Stanford [@Schwarzenegger2014, 527].] einerseits und einem hoch prominenten "23-köpfigen" Wirtschaftsgremium andererseits [@LATimes2003], verwiesen, der mit der Erstellung eines Wirtschafstsprogramms beauftragt wurde. Ebenfalls zu nennen wäre hier das Umweltprogramm Schwarzeneggers [vgl. bspw. @CNN2003b], wofür er ebenfalls eine Reihe von Umweltexperten mobilisiert wie rekrutiert [vgl. etwa @Bustillo2003]. Im zweiten Schritt sorgt der Wahlkampfstab Schwarzeneggers dann stets dafür, dass die Investitionen in das politische Profil Schwarzeneggers an politischer Repräsentation gewinnen. Um dies zu gewährleisten, wird zwar einerseits auf probate Mediationsformate politischer Repräsentation zurückgegriffen. Hervorzuheben wäre hier der vermehrte Gebrauch von Pressekonferenzen zur Vorstellung der wirtschafts- und umweltpolitischen Agenda Schwarzeneggers [@Feldman2003; @Spiegel2003; @CNN2003b], oder auch Formate wie Pressemitteilungen, Wahlwerbespots [@VoA2003], Radiointerviews -- bspw. bei der "landesweit ausgestrahlten Sean Hannity Show" [@CNN2003a]. Andererseits gehen diesen Formaten aber gleichzeitig auch entweder Aufsehen erregende, staatstragende Großveranstaltung, wie das Gipfeltreffen des _Rates zur wirtschaftlichen Erholung Kaliforniens_[@LATimes2003], voraus, oder sie werden einem Hollywood-Spektakel gleich so medienwirksam inszeniert, dass die freien Medienanstalten kaum umhinkommen, darüber zu berichten. Dabei kommt ihnen zudem stets auch der "Ronald-Reagan-Faktor" [@Schwarzenegger2014, 490], d. h. der Entertainment-Aspekt und Star-Appeal Schwarzeneggers, zugute, der verlässlich dafür sorgt, dass die Fernsehteams dahin kommen, wo der Action-Held in der Öffentlichkeit auftritt (ebd.).
 
So besteht also ein wesentliches Ziel der genannten Wahlkampfstrategie darin, die medienorientierte Relationsstruktur zum Zweck der Verbreitung der "»Schwarzenegger for Governator«-Kampagne" [@Schwarzenegger2014, 524], zur Demonstration der Führungsstärke und zur Inszenierung der Überparteilichkeit Schwarzeneggers in Dienst zu nehmen (@ebd., 524). Oder um es in den Worten des Chefstrategen des Wahlkampfs Mike Murphy auszudrücken: "Die Medien kommen, wenn man ihnen etwas bietet, das Klicks und Einschaltquoten bringt" [Murphy zit. nach @Schwarzenegger2023c]. Beispielhaft sei hier die Bus-Tour genannt, bei der es sich um eine Karawane aus sechs Bussen names "Arnold Express" [@Sullivan2003; vgl. auch @LA2003; @Guardian2003], handelt, wobei "[d]ie beiden Hauptbusse [...]  nach seinen Actionfilmen 'Running Man' und 'Total Recall' benannt [waren]", während die anderen vier Hollywood-Busse für 200, die Karawane begleitende Medienschaffende vorgesehen waren [@Sullivan2003]. Gemäß der Devise, dass die Medien kommen, so man ihnen etwas bietet, folgt zudem jede Kundgebung auf der Bus-Tour einem von Murphy festgelegtem Schema und Skript [@Sullivan2003]: "knackige Pointen, ein zwei witzige Sprüche [wie bspw. 'Hasta la vista Davis', 'I'll be back' und 'Hasta la vista car tax' [vgl. @Schwarzenegger2023c; @Megerian2003]; CP & EMS], kurze Attake, die Menge zum Kochen bringen, Geschenke werfen, nächster Termin" [Murphy zit. nach @Schwarzenegger2023c]. Ebenfalls zu nennen ist eine der letzten Wahlkampfveranstaltungen Schwarzeneggers. Hier verkündet er erst, dass seine Filmfiguren, wenn ihnen etwas nicht gefalle, es terminieren, und er die gleiche Taktik gegen die Kfz-Steuer von Davis anwenden werde [@Newman2003], woraufhin er "die Aufmerksamkeit der Menge auf einen Kran lenkt, der eine Abrissbirne auf einen Buick fallen ließ, der mit ,Davis Car Tax' besprüht war (ebd.; vgl. auch @Lopez2021). Im Anschluss an diese Action-Szene, bei der er bewusst mit dem "Killerinstinkt seiner Terminator-Rollte spiel[t]" [@Newman2003], erklärt Schwarzenegger: "Die Menschen haben genug von schmutzigem Geld, verschlossenen Türen, Hinterzimmergeschäften und Sonderinteressen. Ich werde zur Abwechslung mal das Volk vertreten" (Schwarzenegger zit. nach ebd.)! Und Schwarzenegger fährt im Terminator-Jargon, den er "oft [...] in seine Reden einfließen [lässt]" (ebd.), fort: "Gray Davis hat Arbeitsplätze terminiert, Unternehmen terminiert, Hoffnung terminiert und Chancen terminiert. Jetzt ist es an der Zeit, Gray Davis zu terminieren" (ebd.). 

Solche Medienspektakel verdeutlichen also, dass auch Schwarzeneggers Wahlkampfstab nicht nur in die politische Agenda und das überparteiliche Profil Schwarzeneggers investiert, sondern gleichsam das Prinzip der Verführung verwendet, um Schwarzeneggers Vertretungsmacht in der Politik durch dessen mediale Verführungsmacht zu stärken [@PapilloudSchultze2022, 291-292] und zur Verbreitung der Attraktivität von Schwarzenegger als charismatischen Staatsmann über die Indienstnahme freier Medienanstalten sicherzustellen. Dass diese Verbreitungsstrategie unter Ausnutzung des Star-Appeals Schwarzeneggers und auf Basis Hollywood gleicher Wahlkampfkampagnen überaus erfolgreich ist, lässt sich zum einen daran erkennen, dass die Abberufungs- und Neuwahl um das Gouverneursamt "im Fernsehen stärker beachtet [wird], als das Präsidentschaftsrennen" [@LA2003]. So widmen "die abendlichen Nachrichtensendungen auf NBC, ABC und CBS dem Rückruf [[v]om 1. August bis zum 25. September] insgesamt 127 Minuten" Sendezeit, während auf "die demokratischen Präsidentschaftskandidaten [im gleichen Zeitraum] 36 Minuten" entfallen (Tyndall Report zit. nach @LA2003). Zum anderen lässt er sich aber auch in Bezug auf kommerzielle Medieninstanzen erkennen, denen gegenüber sich Schwarzenegger gezielt als Nichtpolitiker inszeniert, indem er sich bspw. "in Stiefeln aus Krokodilleder [...] zur Schau stell[t]" [@Schwarzenegger2023c]. So haben einerseits die digitalen Medien, "die sich zwar kaum mit Wahlen befassen, [...] im Rennen um das Gouverneursamt in Kalifornien etwas gefunden, das sie wirklich schätzen: eine Reality-TV-Show mit einem bewährten Quotenbringer als Star" [@Nicholas2003]. Andererseits erstatten aber auch "Unterhaltungsnachrichtensendungen wie 'Access Hollywood' und 'Entertainment Tonight'" -- befreit vom Gebot der Chancengleichheit zwischen den Kandidaten -- einzig "auf der Grundlage ihres Nachrichtenwerts" über die Wahlkampagne des ,Governators' Bericht [@Nicholas2003]. Damit ist deutlich, dass der Actionheld Schwarzenegger eine enorme Anziehungskraft auf alle Medieninstanzen, ob seriös oder kommerziell, ausübt, die sein Wahlkampfteam durchaus für sich und ihren Kandidaten effektiv einzusetzen und auszunutzen weiß. Entsprechend transformiert der Wahlkampfstab Schwarzeneggers und mithin Schwarzenegger selbst "eine Abberufungswahl, die bereits ein nationales Spektakel" und "selbst für Hollywood-Verhältnisse bizarr war" [@CNN2003c], "in eine globale Mediengeschichte" [@Nicholas2003]; eine ,Mediengeschichte', die durchaus das Zeug hat, "als Vorlage für ein Hollywood-Drehbuch [zu; CP & EMS] dienen" [@Time2010] und aus der Sicht von Medienbeobachtern "alle alten Regeln über die Art und Weise, wie ein Rennen um ein Wahlamt geführt, wie ein politisches Amt gewonnen [wird]" und wie darüber zu berichten ist, in Frage stellt [vgl. @Nicholas2003]. 

Gleiches lässt sich auch für Selenskyj hervorheben, wenngleich die Indienstnahme von Medienanstalten zur Verbreitung der Attraktivität Selenskyjs als charismatischer Staatsmann nicht so sehr über die Mediatisierung von dessen digitaler Wahlkampfkampagne verläuft, sondern vielmehr auf der Grundlage seiner Attraktivität als Entertainer, Showmaster und Leinwand-Präsident der Ukraine erfolgt. So ist Selenskyj einerseits bis kurz vor der ersten Wahlrunde mit seiner Kabarettisten-Gruppe _Kwartal 95_ auf Tournee durch die Ukraine, wo er mit den Mitteln der politischen Satire Hohn und Spott über der Regierung, dem Amtsinhaber Poroschenko und nicht zuletzt seinem Publikum, demgegenüber er erklärt, es handele sich um eine vom Publikum bezahlte Wahlkampfveranstaltung, ausgießt [vgl. @Rogacin2022, 135; @Gon2019; @Keller2019b]. Andererseits betreibt aber auch der Oligarch Kolomojskyj mittelbar Wahlkampf für Selenskyj, indem vonseiten der Mediaholding 1+1 nicht nur "aus­schließ­lich positiv über Selen­skyj und seine Auf­tritte berich­tet [wird]" [@Nelles2019] und auf den Sendern "'1+1', '2+2', 'TET', 'PlusPlus' und 'Ukraine Today'" [@Ukraine2019] vermehrt Aufzeichnungen von politischen Satiresendungen mit Selenskyj ausgestrahlt werden. Ferner geht eine Woche vor der ersten Runde der Präsidentschaftswahl die dritte Staffel von _Diener des Volkes_ -- "der größte Erfolg in der Geschichte des ukrainischen Fernsehens" -- auf Sendung, in der Selenskyj in der Rolle des Staatspräsidents gegen "Oligarchen und korrupte Politiker" vorgeht, "um die Interessen der einfachen Leute zu verteidigen" [vgl. @Iwan2019].
  
Dies zeigt also, dass sowohl bei Selenskyjs als auch bei Schwarzeneggers Kampagne weniger die Frage im Zentrum steht, wie die Wahlversprechen (Investition in die Repräsentation der Ukrainer bzw. Kalifornier) in die Tat umgesetzt (Materialität) werden und ob diese Art der Realisierung mehrheitsfähig (Attraktivität) ist, sondern vielmehr die Frage, ob die Wahlversprechen (Investition) -- weitgehend unter Ausklammerung von deren Realisierungsmöglichkeiten (also: Materialität der Investition) -- medienwirksam bzw. spektakulär genug inszeniert, weit genug transportiert und von Selenskyj wie Schwarzenegger als charismatsche Anführer wählerwirksam genug in Szene gesetzt wurden (Repräsentation), um die Wählerschaft zu überzeugen (Materialität der Attraktivität vor Materialität der Investition). Diese Gegenüberstellung der Schmetterlingspfade einerseits der Kernsequenz Repräsentation der politischen Relationsstruktur und andererseits der Kernsequenz Attraktivität der medialen Relationsstruktur zeigt, dass wir es hier mit Verhältnissen zu tun haben, in denen die Achse Repräsentation -- Attraktivität nicht mehr von der Attraktivität zur Repräsentation verläuft, wie für die Politik und die Repräsentation von Kollektiven charakteristisch [vgl. Abb.3.5 in @PapilloudSchultze2022, 96], sondern umkehrt von der Repräsentation zur Attraktivität, wie für das Entertainment und das Spektakel typisch [vgl. Abb. 3.13 in ebd., 115]. Daran zeigt sich, dass es bei der Antwort auf die Frage, "wie viel Showbusiness die Politik enthält" [@Seeßlen2017], nicht damit getan ist, keine "große[n] Gräben" sehen zu wollen, oder die Verbindung zwischen Traumfabrik und Politik als einen "Brei aus Unterhaltung, Wirtschaft und Politik" darzustellen [Scheller zit. nach @Cicero2024]. Es zeigt sich vielmehr, dass die Sequenz Attraktivität -- verstanden als Ausgangspunkt repräsentativer Tätigkeitsentwicklung -- der wunde Punkt des Tätigkeitsspektrums der Politik ist, da sie das Verhältnis der Repräsentation zur Attraktivität umkehrt, indem die Verwirklichung bzw. die Materialisierung von individuellen Repräsentanten an die Stelle der Investitionen in die Repräsentation von Kollektiven tritt [@PapilloudSchultze2022, 125]. Oder anders formuliert, wenn -- wie im Falle Selenskyjs und Schwarzeneggers -- die Attraktivität als Ausgangspunkt der Tätigkeitsentwicklung die Repräsentation ersetzt, so entwickelt sich ein Verhältnis in der Politik, in dem nicht nur die Kerntätigkeit des Politikbetriebs -- die Repräsentation -- in den Dienst der Attraktivität gestellt wird, sondern sich auch das Verhältnis von Materialität und Investition umkehrt und ebenso der Attraktivität unterstellt wird. Im Ergebnis wird mit Elementen der Populärkultur Politik gemacht und Medienfiguren, die zuvor in der Kulturindustrie zu Ikonen stilisiert wurden, werden zu Repräsentanten, die gerade wegen des Rückgriffs auf Mediationen der Populärkultur, d. h. auf symbolische und formale Medien und Aktanten aus dem Bereich des Showbusiness, Wahlkampf betreiben.

Diese Umkehrung der Verhältnisse führt -- wie am Beispiel Schwarzeneggers und Selenskyjs demonstriert -- dazu, dass das austauschzentrierte Merkmal stärker und in atypischer Weise für repräsentative Tätigkeitsbereiche in den Hintergrund gedrängt wird und das akteurzentrierte Merkmal zusehends mit diesem konkurriertin den Vordergrund bei der Arbeit der Akteure und der Arbeit der entsprechenden gesellschaftlichen Instanzen rückt [vgl. @PapilloudSchultze2022, 96]. Dies hat Folgen für die Repräsentation von Kollektiven in der Politik, an sich, da 

 zu typischen Säulen eines Wahlkampfes, die Zeugnis davon ablegen, dass die Reprässentation von Kollektiven vom Standpunkt der Attraktivität von einzelnen Repräsentanten entwickelt und verbreitet wird. Zu diesen Säulen gehören folgende Tätigkeitsschwerpunkte, die einander ergänzen und gegenseitig stabilisieren: Erstens 
der ganzliche oder teilweise Verzicht auf das Tätigkeitsspektrum des Politikbetriebs, um die entsprechenden Kandidaten als politische Neulinge bzw. Nicht-Politiker abseits der etablierten politischen Klasse oder der Figur des Berufspolitikers zu inszenieren. Zweitens der Versuch der Monopolisierung der Repräsentation möglichst vieler Kollektive bzw. Wählergruppen. Drittens 

So geschehen bei Selenskyj über den Verzicht auf das politische Tätigkeitsregister und klassische Mediationen des Politikbetriebs und den erhöhten Einsatz von Medien zur Attraktivierung seiner selbst als Mann aus dem Volke, der . und bei um die Zweitens die Monopolisierung der Repräsentation möglichst vieler Kollektive bzw. Wählergruppen, was  der Versuch bzw. die Realisierung der M 

und der stetige oder verstärkte Rekurs auf Mediationen der medialen Relationsstruktur zum Zweck der Attraktivierung der Kandidaten als charismatisch-monopolistische Staatsmänner. Damit einhergehend zweitens, die bewusste Inszenierung der Kandidaten als politische Neuling bzw. Nicht-Politiker abseits der Figur des Berufspolitikers und drittens die Monopolisierung der Repräsentation möglichst aller vorhandenenen Kollektive bzw. aller möglichen Wählergruppen, was insb. über die Indienstnahme von Medien zur Adressierung aller Individualitäten dieser Kollektive gelingt.   



##Schlußwort



Dies zeigt also, dass sowohl bei Selenskyjs als auch bei Schwarzeneggers Kampagne weniger die Frage im Zentrum steht, wie die Wahlversprechen (Investition in die Repräsentation der Ukrainer bzw. Kalifornier) in die Tat umgesetzt (Materialität) werden und ob diese Art der Realisierung mehrheitsfähig (Attraktivität) ist, sondern vielmehr die Frage, ob die Wahlversprechen (Investition) -- weitgehend unter Ausklammerung von deren Realisierungsmöglichkeiten (also: Materialität der Investition) -- medienwirksam bzw. spektakulär genug inszeniert, weit genug transportiert und von Selenskyj wie Schwarzenegger als charismatsche Anführer wählerwirksam genug in Szene gesetzt wurden (Repräsentation), um die Wählerschaft zu überzeugen (Materialität der Attraktivität vor Materialität der Investition). Diese Gegenüberstellung der Schmetterlingspfade einerseits der Kernsequenz Repräsentation der politischen Relationsstruktur und andererseits der Kernsequenz Attraktivität der medialen Relationsstruktur zeigt, dass wir es hier mit Verhältnissen zu tun haben, in denen die Achse Repräsentation -- Attraktivität nicht mehr von der Attraktivität zur Repräsentation verläuft, wie für die Politik und die Repräsentation von Kollektiven charakteristisch [vgl. Abb.3.5 in @PapilloudSchultze2022, 96], sondern umkehrt von der Repräsentation zur Attraktivität, wie für das Entertainment und das Spektakel typisch [vgl. Abb. 3.13 in ebd., 115]. Daran zeigt sich, dass es bei der Antwort auf die Frage, "wie viel Showbusiness die Politik enthält" [Seeßlen2017], nicht damit getan ist, keine "große[n] Gräben" sehen zu wollen, oder die Verbindung zwischen Traumfabrik und Politik als einen "Brei aus Unterhaltung, Wirtschaft und Politik" darzustellen [Scheller zit. nach @Cicero2024]. Es zeigt sich vielmehr, dass die Sequenz Attraktivität -- verstanden als Ausgangspunkt repräsentativer Tätigkeitsentwicklung -- der wunde Punkt des Tätigkeitsspektrums der Politik ist, da sie das Verhältnis der Repräsentation zur Attraktivität umkehrt, indem die Verwirklichung bzw. die Materialisierung von individuellen Repräsentanten an die Stelle der Investitionen in die Repräsentation von Kollektiven tritt [@PapilloudSchultze2022, 125]. Oder anders formuliert, wenn -- wie im Falle Selenskyjs und Schwarzeneggers -- die Attraktivität als Ausgangspunkt der Tätigkeitsentwicklung die Repräsentation ersetzt, so entwickelt sich ein Verhältnis in der Politik, in dem nicht nur die Kerntätigkeit des Politikbetriebs -- die Repräsentation -- in den Dienst der Attraktivität gestellt wird, sondern sich auch das Verhältnis von Materialität und Investition umkehrt und ebenso der Attraktivität unterstellt wird. Im Ergebnis wird mit Elementen der Populärkultur Politik gemacht und Medienfiguren, die zuvor in der Kulturindustrie zu Ikonen stilisiert wurden, werden zu Repräsentanten, die gerade wegen des Rückgriffs auf Mediationen der Populärkultur, d. h. auf symbolische und formale Medien und Aktanten aus dem Bereich des Showbusiness, Wahlkampf betreiben.







##Literatur
