---
title: "Einführung. Ausgangslage der Theorie der Relation"
indent: true
output:
    html_document: default
csl: chicago-author-date.csl
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Wie wir in unserem Vorwort hervorgehoben haben, ist das Thema Relation in der Soziologie ein wiederkehrendes Thema, das stets, wenn auch in unterschiedlicher Coulour, aufgegriffen wird. Deshalb stellt sich die Frage, ob die soziologische Theorie eine Theorie der Relation bzw. eine Theorie, die vollständig durch die Relation strukturiert ist, eigentlich braucht. Diese Frage kann nicht einfach mit "Ja" beantwortet werden, sofern nicht die folgenden drei Bedingungen berücksichtigt werden, mit denen wir dieses Kapitel zur Ausgangslage der Theorie der Relation eröffnen und die wir nun näher erläutern möchten.

Die erste Bedingung betrifft den Begriff der Relation. Relation bezeichnet eine Reihe von sehr unterschiedlichen Phänomenen, die Menschen und Nicht-Menschen, d. h. lebendige oder nicht lebendige, materielle oder immaterielle Akteure, Symbole, Ideen, Repräsentationen und andere Medien zusammenbringen, miteinander verbinden und voneinander trennen. Die erste Aufgabe für eine Theorie, die durch die Relation vollständig strukturiert werden soll, besteht also darin, diese Breite und Multidimensionalität des Begriffs der Relation zu strukturieren. In der Theorie der Relation erfolgt eine solche Strukturierung auf drei grundlegenden Ebenen, die den Kern dieses Kapitels ausmachen: a) die Ebene der relationalen Ereignisse, die von einfachen Kontakten bis hin zu Handlungen, Interaktionen und anderen Verhältnissen reichen, b) die Ebene der Zirkulation, zu der die Entwicklung von relationalen Ereignissen führt, und c) die Ebene der Relationsstrukturen, die diese Zirkulation organisieren. Die Theorie der Relation erfasst entsprechend nicht nur die Vielfalt besonderer Verhältnisse. Sie strebt zudem danach, ihre Organisationsprinzipien zu erklären, die sich in Relationsstrukturen vergegenwärtigen und wie Ordnungsprinzipien von Zirkulationen und daher von Akteuren und gesellschaftlichen Instanzen in diesen Zirkulationen fungieren.

Aus dieser ersten Bedingung ergibt sich die zweite Bedingung, die die Ebene von Relationsstrukturen betrifft. Relationsstrukturen stellen keine homogenen oder stabilen Mengen von Zirkulationen und relationalen Ereignissen dar. Es sind vielmehr dynamische Strukturen, die verändert werden, wenn Verhältnisse und Zirkulationen verwirklicht werden. Solche Veränderungen von Relationsstrukturen passieren ständig, wenn auch mit variabler Intensität, weil stets sowohl innerhalb als auch zwischen Relationsstrukturen Verhältnisse und Zirkulationen entwickelt werden, die die Stabilität von einer Relationsstruktur beeinflussen. Deshalb entstehen innerhalb von Relationsstrukturen alternative Ordnungsprinzipien bzw. alternative Organisationen von Zirkulationsmöglichkeiten für menschliche und nicht-menschliche Akteure in Relationsstrukturen. Sie unterscheiden sich von der Hauptorganisation einer Relationsstruktur und setzen sich in einer Relationsstruktur mit mehr oder weniger Erfolg durch. Die Theorie der Relation zielt somit darauf ab, solche Veränderungen von Relationsstrukturen sowie ihre Folgen auf die Entwicklung von Verhältnissen und auf die Zirkulation von Akteuren innerhalb oder zwischen Relationsstrukturen zu erklären.

Unmittelbar aus dieser zweiten Bedingung folgt die dritte Bedingung, wonach jede Relationsstruktur einerseits als spezifisches Ordnungsprinzip bzw. als spezifische Organisation von Zirkulationen aufgrund der Entwicklung von Verhältnissen durch ihre eigene Dynamik, d. h. durch ihre eigene allgemeine Zirkulation, subvertiert wird, die sie als diese Relationsstruktur kennzeichnet. Andererseits wird jede Relationsstruktur aber auch von der Zirkulation der anderen Relationsstrukturen in ihrer eigenen Dynamik beeinflusst, weil alle Relationsstrukturen im Grunde auf derselben Eigenschaft beruhen, die sie lediglich unterschiedlich aufgreifen: die Zirkulation von Akteuren als das Ergebnis der Arbeit an relationalen Ereignissen. Dies ist entsprechend auch der Grund dafür, dass die Theorie der Relation zum einen nach einem Primat der Zirkulation argumentiert. Zum anderen versteht die Theorie der Relation Relationsstrukturen auf der Grundlage derselben Merkmale, die in den Sequenzen von Zirkulationen gegeben sind und die Relationsstrukturen folglich identisch strukturieren: Die Investition in die Arbeit an relationalen Ereignissen, die Repräsentation von dieser Investition, die Materialisierung von dieser Repräsentation und die Attraktivierung solcher Materialisierung zumZweck der Unterstützung weiterer Investitionen in die Arbeit an relationalen Ereignissen.

Die Folge daraus ist, dass alle Relationsstrukturen strukturell identisch sind bzw. von den gleichen vier Sequenzen -- Investition, Repräsentation, Materialität und Attraktivität -- strukturiert werden. Jedoch unterscheiden sich diese Sequenzen gleichsam dynamisch voneinander und zwar je nach dem, welche Sequenz in einer Relationsstruktur zentral ist und folglich die Identität einer Relationsstruktur bestimmt. Diese zentrale Sequenz -- die sogenannte Kernsequenz einer Relationsstruktur -- bestimmt zudem die Anordnung der anderen drei Sequenzen, deren Reihung dann die für eine bestimmte Relationsstruktur typische Zirkulation festschreibt. Diese spezifische Aneinanderreihung der Sequenzen in einer Relationsstruktur bildet damit das Prinzip der Zirkulation in einer Relationsstruktur ab und macht deren Zirkulation aus. Oder anders gesagt: Jede Relationsstruktur ist durch eine primäre Sequenz in ihrer allgemeinen Zirkulation gekennzeichnet, die nicht nur ihr Hauptmerkmal und ihre spezielle Dynamik bestimmt, sondern auch das Maß dafür bildet, wie ihre anderen drei Sequenzen der primären Sequenz folgend aufgegriffen werden bzw. die primäre Sequenz mehr oder weniger unterstützen. Je nachdem, wie sich das Hauptmerkmal von einer Relationsstruktur bzw. ihre Kernsequenz durchsetzt, gewinnt diese Relationsstruktur darüber hinaus an Bedeutung und an Macht über die anderen Relationsstrukturen, die sie dann auf der Ebene ihrer jeweiligen Zirkulationen beeinflusst. Im umgekehrten Fall bzw. im Fall der Destabilisierung der Kernsequenz von einer Relationsstruktur durch die Stärkung und Verbreitung von einer anderen Sequenz dieser Relationsstruktur verliert die Relationsstruktur an Bedeutung und Macht. Folglich kann sie die anderen Relationsstrukturen weniger beeinflussen.

Halten wir hier kurz an, um diese wesentlichen Bausteine der Theorie der Relation zu reflektieren, die wir gerade beschrieben haben. Die Relation -- sei sie ein kleines relationales Phänomen wie unsere täglichen Interaktionen, oder ein Makrophänomen wie die Entwicklung von internationalen Beziehungen zwischen Ländern -- bringt Akteure und Aktanten in Bewegung bzw. in Zirkulation. Dies ist das allgemeine Prinzip der Theorie der Relation, das Primat der Zirkulation. Je nachdem, wie an relationalen Phänomenen gearbeitet wird, wird diese Zirkulation weniger stark oder stärker strukturiert bzw. betrifft sie weniger oder mehr unterschiedliche Akteure und Aktanten. Deshalb sprechen wir von Sequenzen und Relationsstrukturen, damit diese zwei Stufen strukturierter Zirkulationen auf der Grundlage von weniger strukturierten Zirkulationen von Einzalakteuren und -aktanten erfasst werden können. Die Ebenen der Theorie der Relation spiegeln dann die drei Ebenen des Primats der Zirkulation als den dreifachen Ausdruck dessen wider, was Relation bedeuten kann -- also als relationale Phänomene, Sequenzen und Relationsstrukturen. Diese drei Ebenen sind relativ heterogen und unabhängig voneinander, was den Einfluss von einer Ebene auf die anderen mit dem Ziel zulässt, die Art der Zirkulation, die eine Ebene darstellt, auf die anderen Ebene zu verbreiten. Diese Kolonisierung bis zur Vereinnahmung von anderen Ordnungsprinzipien der Relation, also von anderen Arten der Zirkulation entspricht der Suche nach einer idealen Relation bzw. der Suche nach Verabsolutierung von einer idealen Vorstellung der Relation, die jede Ebene in sich trägt und legitimiert sehen will. Eine solche ideale Relation kann gleichsam eine einzigartige, singuläre, harmonische, allgegenwärtige, stabile, erfolgreiche, jenseits von Grenzen und Alterung, gewinnbringende oder noch glückliche Relation bedeuten. Das diese ideale Relation jedoch eine Utopie bleibt, attestiert der gegenseitigen Einfluss zwischen den drei Ebenen der Zirkulation bzw. zwichen den Relationsstrukturen, den Sequenzen in diesen Relationsstrukturen, den Akteure, Aktanten und gesellschaftlichen Instanzen in diesen Sequenzen, und zwar selbst wenn diese Ebenen als Zirkulationsordnungen die Verlockung einer solchen Utopie aufrechterhalten, die in Unterstützung der Zirkulationsdynamik in jeder Relationsstruktur vorkommt.

Diese Bausteine der Theorie der Relation gilt es im Folgenden zu vertiefen. In einem ersten Schritt greifen wir dabei auf die Aussage zurück, dass die Theorie der Relation mit dem Begriff der Zirkulation den dynamischen Charakter von Relationsstrukturen beschreibt. Ausgehend von diesem Primat der Zirkulation beschäftigen wir uns anschließend eingehender mit den vier Relationsstrukturen und ihren vier Sequenzen, die die Zirkulationen von Akteuren innerhalb und zwischen Relationsstrukturen stratifizieren. In einem zweiten Schritt fakussieren wir den Begriff der doppelten Einschreibung der Akteure und gesellschaftlichen Instanzen in Relationsstrukturen. In diesem Zusammenhang führen wir in die beiden Begriffe des Widerstands der Akteure einerseits und der Reziprozität andererseits ein. Wir erklären, warum diese drei Begriffe -- Einschreibung, Widerstand, Reziprozität -- in der Theorie der Relation eng miteinander verbunden sind und wie sie zur Verteilung und Differenzierung von Akteuren und sozialen Instanzen in den Relationsstrukturen beitragen. Die Variationen der Verteilung und Differenzierung von Akteuren und sozialen Instanzen führen entweder zur Verbreitung oder -- im Gegenteil -- zur Schrumpfung von Relationsstrukturen, die ihre Zirkulation, die Einschreibung von weiteren Akteuren und Instanzen sowie ihre Widerstandskraft entsprechend stärken oder schwächen. Im dritten Schritt ziehen wir schließlich die Folgen aus den beiden ersten Schritten. Dabei konzentrieren wir uns auf den Tatbestand, dass jede Relationsstruktur als eine sequentielle Ordnung von Zirkulationen die anderen Relationsstrukturen immer nach demselben Muster beeinflusst. Dieses Muster besteht darin, die Reziprozität, die eine Relationsstruktur repräsentiert und sie charakterisiert, allen anderen relationalen Strukturen aufzuzwingen, um ihre eigene Utopie der idealen Relation vollumfänglich zu implementieren, nach der jede Relationsstruktur strebt.

Wie wir schon hervorgehoben haben, existieren relationale Ansätze in der Soziologie und in den Sozialwissenschaften bereits. Diese haben sich etwa im Rahmen der relationalen Soziologien in den letzten zwei Jahrzehnten immer stärker und systematischer um die Relation als Kernfrage für die Untersuchung der Gesellschaften entwickelt. Deshalb wiederholen wir noch einmal unsere Eingangsfrage: Brauchen wir einen weiteren Ansatz wie denjenigen der Theorie der Relation?

## Wieso eine Theorie der Relation?

Das Ziel und das entsprechende konzeptuelle Instrumentarium, das die Theorie der Relation verwendet, um seine Untersuchungen durchzuführen, gehen über den Rahmen der existierenden relationalen Ansätzen in den zeitgenössischen Soziologien und Sozialwissenschaften hinaus. Dies bedeutet jedoch nicht, dass alles in der Theorie der Relation neu sei. Die Theorie der Relation verwendet Begriffe, von denen einige von anderen Theorien aufgegriffen werden, die nach einem relationalen Ansatz argumentieren. Deshalb ist es notwendig zu erklären, wie die Theorie der Relation solche Begriffe versteht und sie in Unterstützung eines strukturierten Rahmens verwendet, der vollständig durch die Relation strukturiert ist, statt Relation auf relationale Ereignisse zu reduzieren und somit den Theorierahmen zu verabschieden, wie in kritischen Auseinandersetzungen mit relationalen Ansätzen und relationalen Soziologien immer wieder bemängelt wird [@Trezzini1999, 515; @Scott1991, 38; @Granovetter1979, 501, 517; vgl. auch @Schultze2022, 4].

Vom Standpunkt der Theorie der Relation ist Relation ein Makrobegriff -- dies geht jedoch nicht ohne Schwierigkeiten, worauf auch Soziologen hinweisen, wenn sie allgemeiner über Prozessbegriffe und ähnliche Begriffe sprechen, wie etwa Wolfgang Knöbl in seinem Buch _Die Soziologie vor der Geschichte. Zur Kritik der Sozialtheorie_ [@Knoebl2022]. Darin sagt Knöbl, dass die Sozialwissenschaften und darunter besonders die Soziologie und die soziologische Theorie Defizite bei der Verwendung von Prozessbegriffen und von Begriffen zeigen, die auf eine solche Prozesshaftigkeit verweisen. Dabei geht es Knöbl "in der Hauptsache um die Frage, warum die modernen Sozialwissenschaften und hier insbesondere die Soziologie zwar einerseits von Anfang an robuste Prozessbegriffe benutzten, um ihre jeweilige Gegenwart zu erklären [...], aber andererseits genau diese Begriffe und die mit ihnen verbundenen Aussagen und Thesen periodisch immer wieder kritisierten, weil man sich offensichtlich dann doch nicht so ganz sicher war und ist, wie gut sich damit Vergangenheit und Gegenwart fassen lassen" [ebd., 12-13, vgl. auch @Hoebel2020].

Besonders in seinem siebten Kapitel zu Sozialwissenschaften und Geschichtsphilosophie macht Knöbl deutlich, dass Prozessbegriffe Erzählungsmuster voraussetzen, die Sozialwissenschaftler:innen nicht immer berücksichtigen, wenn sie solche Begriffe verwenden. Dies führt häufig dazu, dass die Sozialwissenschaften der Komplexität von (wie Knöbl hervorhebt: historischer) Realität, die anhand von solchen Begriffen beschrieben werden soll, nicht gerecht werden. Ist man sich sicher, dass die Beschreibung von breiten gesellschaftlichen Zusammenhängen in Zeit und Raum genau das erfasst, was sie zu beschreiben behauptet? Gibt es dabei nicht eine Tendenz in den Sozialwissenschaften, "sich allzu leichtgläubig auf die Erklärungskraft oder auch nur die Prägnanz und Trennschärfe dieser Begriffe" zu verlassen [@Knoebl2022, 271]? Der Punkt, den Knöbl mit seiner These unterstreichen will, ist weniger derjenige der Unbestimmtheit von Begriffen, worüber sich der Sozialwissenschaftler nicht bewußt wäre (ebd., 280). Sein Punkt betrifft vielmehr die Einbettung von Begriffen in sozio-politische Kontexte (ebd., 257, 269), von denen ihre Bedeutung maßgeblich abhängt, weshalb sie nicht ohne Weiteres zu Prozessbegriffen umgewandelt werden können.

Wenn wir uns eingedenk dieser Ausführungen Knöbls etwa den Begriff der Demokratie und seine prozesshaftige Erweiterung auf "Demokratisierung" ansehen, dann merken wir, dass eine solche Erweiterung viele Fragen mit sich bringt. Diese Fragen reichen von dem Verhältnis zwischen Wirtschaft und Politik, zwischen Bevölkerung und Staat, zwischen Gleichheit und Ungleichheit usw., die in den Sozialwissenschaften anhand von "Erzählungen" kontrovers diskutiert werden, ohne dass ein Schlußwort gesetzt werden könnte bzw. ohne dass die Sozialwissenschaften zu einem zufriedenstellenden und zu allen Zeiten allgemein gültigen Ergebnis kämen (vgl. Knöbls Diskussion von Charles Tillys Analyse der Demokratie und der Demokratisierung, ebd., 285-288). Diese Kritik von Knöbl an den Sozialwissenschaften betrifft auch die relationalen Soziologien insofern, als sie mit einem -- häufig dekonstruierten -- Prozessansatz argumentieren, der für diese Soziologien im Vordergrund der Untersuchung steht. Dieser Ansatz bildet nicht nur das Selbstverständnis aller relationalen Soziologien -- Hauptgegenstand der "relationalen" Sichtweise sind "Prozesse" einerseits und "dynamische, sich entfaltende Beziehungen" andererseits [@Selg2020, 15; vgl. auch in den unterschiedlichen Perspektivierungen @Elias1977, 131; @Crossley2020a; @Emirbayer1997, 1998; Dépelteau2008, 2013b; @Papilloud2017; @Donati1995, 2013; @Bottero2011]. Er markiert gleichzeitig auch den Punkt, ab dem sich die relationalen Soziologien voneinander unterscheiden [vgl. @Prandini2015; vgl. auch @Selg2020, 30-35]. In Anlehnung an den Vorschlag Knöbls, wonach es nicht darum gehe, die genannten Prozessbegriffe oder gar Prozessbegriffe allgemein zu verdammen, wohl aber darum, für eine reflektiertere Anwendung dieser Begriffe zu werben [@Knoebl2022, 296], soll es im Folgenden darum gehen, über diese Ausgangslage im speziellen Fall der Theorie der Relation zu reflektieren.

## Ausgangslage der Theorie der Relation

Die Theorie der Relation geht nicht von der Annahme aus, dass sie unmittelbar mit sozialen Beziehungen, sozialen Verhältnissen, Interaktionen und mit weiteren solcher relationalen Ereignisse zu tun habe [@Papilloud2017]. Wie wir unter Rekurs auf Knöbl in unserer Einleitung erwähnt haben, sind solche Begriffe sowohl historisch als auch disziplinär im Bereich der Soziologie keineswegs neutrale Begriffe. Sie sind mit bestimmten soziologischen Paradigmata und deren Prämissen ebenso verknüpft, wie mit bestimmten Theorietraditionen [am Beispiel des Terminus _relationale Soziologie_ bzw. _Relation_ vgl. @Prandini2015]. Aus früheren Arbeiten haben wir gelernt, dass Prozessbegriffe nicht unbedingt in jeder Soziologietradition im Vordergrund des Erkenntnisinteresses stehen [vgl. etwa @monoPapilloud2002; @monoPapilloud2012a; @monoPapilloudRol2019]. In der französischen Theorietradition stellen sie bspw. kein Kernelement dar, während ihre Bedeutung für die soziologische Untersuchung in der amerikanischen Soziologietradition umgekehrt stark ausgeprägt ist. In der deutschen Soziologietradition wird teilweise mit prozesshaften Begriffen argumentiert; so etwa in den Schriften Georg Simmels entlang der Begriffe Wechselwirkung, Vergesellschaftung und Tausch [@monoPapilloud2002], im Werk Max Webers zu den Formen der Rationalisierung in den abendländlichen Gesellschaften [@nprPapilloud2002b], in der Ontologie der Beziehungslehre Leopold von Wieses [@hgbuchPapilloud2006a], am Beispiel des Begriffes der Kommunikation und seiner inhaltlich unterschiedlichen Fassung und Verwendung im deutschen Pragmatismus, in Jürgen Habermas' Theorie der Moderne oder in der Systemtheorie Niklas Luhmanns [@kapitelPapilloud2005; @kapitelPapilloud2005b]. Jedoch unterstützen solche Begriffe meistens eine Theorie, die häufig als Heuristik zur Untersuchung eines anderen, bedeutenderen Gegenstandes wie etwa die Moderne, der Wandel von Soziabilitätsformen, die gesellschaftliche Homöostasie, die Werte, die Komplexität etc. verstanden wird. Anders gesagt, bleiben solche prozesshaften Begriffe Mittel zum Zweck und sind nicht (Selbst)Zweck der soziologischen Untersuchung.

Ähnlich wie in diesem letzten Fall, sieht man in den relationalen Soziologien eine Verwendung nicht primär eines einzigen Prozessbegriffes, sondern eher von prozessartigen Begriffen [@Selg2020, 30-35], die gezielt mit _Relation_ gleichgesetzt werden, um Gesellschaft _als_ Relation zu verstehen. Entsprechend wird die Quelle des Gesellschaftlichen typischerweise in der Zwischenmenschlichkeit _als Relation_ situiert und soll eine entsprechende soziologische Untersuchung von Gesellschaften _als Relation_ fördern. Ab diesem Punkt der Umformulierung oder Umformung von prozessartigen Begriffen in die Relation unterscheidet sich die Theorie der Relation von anderen relationalen Soziologien. Dass Prozesse und zwar im schwachen und nicht homogenen Sinn von relationalen Phänomenen zwischen den Menschen liegen, ist eine Annahme, die die Theorie der Relation nicht braucht, weil sie nicht vom Standpunkt eines Anthropozentrizmus argumentiert, der voraussetzt, dass relationale Phänomene spezifisch oder nur menschlich wären [@LatourStrum1986; @Pyyhtinen2010; @Kaufmann2011; @Abbott2016]. Deshalb verwendet sie den Begriff der Relation als Makrobegriff zur Kategorisierung von relationalen Phänomenen in ihrer Diversität und Pluralität. Dies verschafft ihr den Vorteil, gesellschaftliche Phänomene nicht auf Relation zu reduzieren bzw. sie _als Relation_ zu beschreiben, sondern sie, auch in Anlehnung an die soziologische Tradition, mittelbar und somit _durch Relation_ zu erklären. Diese Ausgangslage der Theorie der Relation macht entsprechend aus der Relation nicht die Antwort auf eine Vielzahl von Fragen, sondern die Frage selbst oder -- im Sinne der praktischen soziologischen Untersuchung -- das Problem, das eine solche Theorie zu beantworten versucht bzw. mit dem sie sich auseinandersetzt. Dieses Problem sieht die Theorie der Relation als die Grundfrage des gesellschaftlichen Lebens, mit dem sich jede Gesellschaft, jede informelle oder formelle Gruppe und jeder Akteur dieser Gesellschaften stets auseinanderzusetzen hat. Dass eine solche Auseinandersetzung sehr unterschiedlich erfolgt, werden wir in diesem Band anhand von Beispielen darstellen.

Die Entwicklung eines Makroverständnisses von Relation und damit auch eines makrosoziologischen Denkens über Relation ruht -- etwa im Unterschied zu Pierre Bourdieu, der in seinem makro-relationalen Theorieansatz hauptsächlich Relationen _zwischen Positionen_ im Blick hat [vgl. @Bourdieu1987; @Bourdieu2019] -- auf der Einsicht, dass die Erklärung des Sozialen _durch Relation_ einen positionellen und einen relationalen Ansatz symmetrisch berücksichtigt, insofern die Sozialität nach dem Primat der Zirkulation entwickelt und gedacht wird. Wie die Theorie der Relation nach einem Primat der Zirkulation argumentiert, erklären wir im Folgenden. Dazu führen wir den Begriff der Relationsstruktur ein, den wir in mehreren Schritten vertiefen.

## Primat der Zirkulation und Relationsstrukturen

Das Primat der Zirkulation bedeutet, dass die Arbeit an relationalen Ereignissen unterschiedlicher Art Akteure und Aktanten in Bewegung bringt. Oder anders formuliert: Sie zirkulieren innerhalb und zwischen Relationsstrukturen. Die Zirkulation entsteht dabei als die allgemeine Dynamik zwischen Position und Relation, die diese Relationsstrukturen generieren. Die Zirkulation ist daher kein Phänomen _sui generis_, d. h. sie entsteht nicht automatisch, sondern sie setzt die Arbeit von Akteuren an relationalen Ereignissen voraus, um über einfache Bewegungen hinaus entwickelt zu werden. In diesem Sinne ist die Zirkulation kein Prozess im Sinne Knöbels mit Anfang, Ende oder mit einer gegebenen Homogenität. Die Zirkulation variiert von einer Relationsstruktur zu einer anderen Relationsstruktur und überdies auch innerhalb von Relationsstrukturen. Diese Variationen ergeben sich daraus, dass die Zirkulationswege von Akteuren sowie von Aktanten und von symbolischen und formalen Medien sehr unterschiedlich ausfallen: unterschiedlich kurz oder lang, schnell oder langsam, stabil oder brüchig. Dies macht die unendliche Komplexität der Zirkulation von Akteuren einerseits und von Aktanten und Medien andererseits aus, die die Theorie der Relation anhand der Prinzipien solcher Zirkulationen bestimmt, wobei diese Prinzipien nichts anders als die Relationsstrukturen sind. Woraus aber entsteht eine solche Komplexität von Zirkulationen?

Sie entsteht zum einen daraus, dass Zirkulationen relationale Ereignisse voraussetzen, die deshalb Ereignisse sind, weil sie nicht und niemals vollends entwickelt werden. Folglich haben relationale Ereignisse keinen bestimmbaren Ursprung, kein vorhersehbares Ende, und sie zeigen unerwartete Mutationen. Hier unterscheidet sich die Theorie der Relation von Knöbls Sicht auf Prozesse. Knöbl versteht Prozesse ähnlich wie Bruno Latour als Arrangement von miteinander verketteten Ereignissen, die er ausnahmslos an einen klaren "Anfangs- und Endpunkt" gebunden sieht [@Knoebl2022, 258; vgl. auch @Latour2005]. Im Fall von Knöbl impliziert eine solche Auffassung von Prozessen nicht nur, dass Ereignisse prinzipiell über _einen_ klar zu bestimmenden Anfangs- und Endpunkt verfügen, sondern auch ihre (anfängliche) Form und Qualität durch die Zeit hindurch beibehalten und entsprechend in sich "(ab)geschlossen" wären [@Knoebl2022, 261]. Dagegen erfasst die Theorie der Relation Ereignisse in ihrer sozialen Eingebundeheit, in ihren mannigfachen Entwicklungs- und Anschlussmöglichkeiten, in ihrer stets präsenten Potentialität des Liegenlassens, der Wiederaufnahme und der (wiederholten) Einflussnahme, wodurch sowohl der heterogenen Struktur als auch der Unbestimmtheit von Ereignissen Rechnung getragen wird [vgl. @Seyfert2019].

Zum anderen entsteht die Komplexität von Zirkulationen aber auch daraus, dass relationale Ereignisse in Form von Interaktionen, sozialen Verhältnissen, Beziehungen, sozialen Handlungen usw. _per definitionem_ stets im Fluss sind und dementsprechend sowohl von einer gelungenen, idealen Relation mit einem Anfang, einem Ende, mit erkennbaren, klar situierten Akteuren, die sie miteinander verbänden, als auch von einer homogenen Entwicklung abweichen. Deshalb begreift die Theorie der Relation Relationsstrukturen als abweichende Zusammenstellungen von relationalen Ereignissen mit Akteuren, Aktanten, Instanzen, Symbolen, Zeichen und Medien, die von einer idealen Relation abweichen. Um die Lesart nicht allzu sehr mit solchen Ketten von Begriffen zu überladen, sprechen wir im Folgenden verkürzt von Akteuren und Aktanten. Da es uns im Rahmen dieses Kapitels zudem hauptsächlich um die Beschreibung der Ausgangslage der Theorie der Relation geht, sprechen wir auch nicht von den Medien, da die Theorie der Relation diese eher im Sinne von Mediationen versteht, die wir später in unseren Beispielen in diesem Band behandeln werden. Im Rahmen der Theorie der Relation sind die Medien sowohl mit der Behandlung von symbolischen Akteursoperationen als auch mit formalen Verfahren von Instanzen der Vermittlung von für Relationstrukturen spezifischen Zirkulationen verbunden. Sie erlauben, die Verbreitung/Schrumpfung von Relationsstrukturen und die Entwicklung alternativer Zirkulationswege in diesen Relationsstrukturen besser zu verstehen [mehr dazu vgl. @PapilloudSchultze2022, 313-370]. Aber kehren wir zur Grundlage der Theorie der Relation zurück.

Das abweichende Merkmal von Relationstrukturen beruht nicht allein auf der Zusammenstellung von relationalen Ereignissen mit Akteuren und Aktanten, sondern ergibt sich auch aus ihrer Dynamik. Relationsstrukturen werden entwickelt oder nicht entwickelt. Obgleich eine solche Entwicklung eine Arbeit an relationalen Ereignissen voraussetzt, findet eine solche Arbeit jedoch nicht zwangsläufig statt, eben weil Relationsstrukturen nicht an sich und unvermeidlich entwickelt werden. Sie können verbreitet werden, aber sie können ebenso sehr schrumpfen, weil Akteure und Aktanten bspw. nicht ständig an relationalen Ereignissen arbeiten oder weil sie nicht stetig zu einer solchen Arbeit beitragen. Der Grund dafür besteht in der Diversität von relationalen Ereignissen sowie von Akteuren und Aktanten, die bei einer solchen Arbeit mobilisiert werden können. An dieser Stelle begegnet uns ein weiteres wichtiges Merkmal der Theorie der Relation, das wie folgt hervorgehoben werden kann: Weil relationale Ereignisse divers sind, können sie sowohl von allen möglichen Akteuren beansprucht werden als auch alle möglichen Aktanten einbeziehen. Weil diese Akteure und Aktanten wiederum ebenfalls divers sind, können sie alle möglichen relationalen Ereignisse beanspruchen bzw. in alle möglichen relationalen Ereignisse einbezogen werden. Diese grundsätzliche Offenheit von relationalen Ereignissen auf Akteure und Aktanten und umgekehrt gewährleistet, dass die Arbeit an relationalen Ereignissen von relativer Bedeutung für eine Relationsstruktur bleibt. Gleichzeitig bildet diese Offenheit den Hauptgrund dafür, weshalb eine solche Arbeit stets und ständig passiert, weil sie, wenn sie nicht hier und jetzt von diesen oder jenen Akteuren mit diesen oder jenen Aktanten aufgenommen wird, früher oder später von anderen Akteuren mit anderen Aktanten anderswo stattfindet. Dies begründet einerseits die heterogene Form der Arbeit an relationalen Ereignissen, während dies andererseits zugleich die bedeutende Rolle dieser Arbeit für die Entstehung von Relationsstrukturen und die damit verbundenen Stufen dieser Arbeit hervorhebt. Dazu kommen wir im Folgenden.

## Arbeit an relationalen Ereignissen

Die Arbeit an relationalen Ereignissen unterstützt die Entwicklung von Relationsstrukturen, was konkret bedeutet, dass sie Zirkulationswege und Zirkulationsmöglichkeiten für Akteure fördert. Wegen der grundsätzlichen Offenheit von relationalen Ereignissen auf Akteure und Aktanten und _vice versa_ ist es unwahrscheinlich, dass nur ein Akteur mit nur einem Aktanten an nur einem relationalen Ereignis arbeitet, dessen Exklusivität er beanspruchen würde. Wahrscheinlich ist eher die Versammlung von unterschiedlichen Akteuren und Aktanten um unterschiedliche relationale Ereignisse bzw. eine heterogene Zusammenstellung von Akteuren, Aktanten und relationalen Ereignissen. Dabei lässt sich nicht ausschließen, dass eine solche Versammlung spontan Form annimmt, weil Akteure, Aktanten und relationale Ereignisse nie neu, sondern Geschichtsprodukte sind, deren Geschichte sie versammeln [vgl. empirisch dazu im Bereich der relationalen Soziologien etwa @Bidart2011]. Sie wird nur dann weiter entwickelt, wenn die Arbeit an relationalen Ereignissen weiter erfolgt. Wenn dies nicht passiert, dann gibt es keine Entwicklung von Relationsstrukturen und keine Unterstützung für die Zirkulation der Akteure. Diese Zirkulation erfolgt dann so, als ob Akteure Aktanten wären, selbst wenn im Fall von Akteuren solche Zirkulationen Spuren im Sinne der beschleunigten Alterung von Akteuren in eigenen Zirkulationswegen hinterlassen, bis jede Form von Zirkulationsmöglichkeit erschöpft ist. Findet diese Arbeit jedoch statt, dann kann sie zur Mobilisierung von (anwesenden wie abwesenden) Akteuren und Aktanten und zur Verkettung von relationalen Ereignissen in Unterstützung der Entstehung und Verbreitung von Relationsstrukturen führen [zur Bedeutung vom Kontaktbegriff als Begriff zur Beschreibung dieses Raumes zwischen Position und Relation, vgl. @Papilloud2017].

Wie Mark Granovetter am Beispiel von "weak ties" angemerkt hat, haben selbst schwach strukturierte Verhältnisse den Vorteil, dass Akteure von relationalen Ereignissen "getragen" oder "agiert" werden. Dabei erreichen sie Ziele, ohne sich aktiv der Arbeit an relationalen Ereignissen zu widmen [@Granovetter1973, 2005]. Diese Kraftersparnis, die jede Art von relationalem Ereignis mit sich bringt, wie schon Georg Simmel unterstrichen hatte [vgl. @Simmel1890, 280], muss jedoch perspektiviert werden. Eine mehr oder weniger gut strukturierte Relationsstruktur ist immer möglich, weil nicht auszuschließen ist, dass eine soziale Arbeit stattfindet. Sogenannte "weak ties" existieren also, weil sich einerseits jeder Akteur der Arbeit an sozialen Ereignissen -- weitere Akteure und Aktanten mobilisieren, relationale Ereignisse verketten und Zirkulationswege bahnen, woraus sich wiederum Zirkulationsmöglichkeiten ergeben -- nicht zwingend widmen muss. Dies bedeutet andererseits aber nicht, wie oben erwähnt, dass eine solche Arbeit nicht irgendwann, irgendwo und irgendwie stattgefunden hat oder bereits von irgendwem geleistet worden ist. An dieser Stelle unterscheidet sich die Theorie der Relation von anderen relationalen Ansätzen dadurch, dass sie nicht etwa davon ausgeht, dass relationale Ereignisse deshalb immer existieren, weil sie immer vorhanden bzw. transzendental wären. Eines ihrer Alleinstellungsmerkmale besteht vielmehr darin, dass sie nicht ausschließt, dass sie von Akteuren und Aktanten hier wie dort, gestern wie heute mobilisiert und verkettet worden sind. Dieser Kontrast zu einer ontologischen Perspektive, die die Relation substanziert, und der Übergang zu einer soziologischen Perspektive, die die Relation als ein kollektives Gut oder als _common_ versteht, wirft jedoch eine weitere Frage auf: Wie ist diese Unterscheidung zwischen Relationsstrukturen und Nicht-Relationsstrukturen einheitlich zu denken? Diese Frage findet ihre Antwort im Primat der Zirkulation.

Anders als die Theorien, die das Argument der Schließung in Unterstützung der oft substantialisierten, in der Theorie allein bzw. _in abstracto_ verankerten Trennschärfe von Unterschieden verwenden -- was nicht links ist, ist rechts, was nicht oben ist, ist unten, was nicht drinnen ist, ist draußen usw. [vgl. paradigmatisch dazu @Bourdieu1987] --, priorisiert die Theorie der Relation aufgrund der Frage der Arbeit an relationalen Ereignissen keine scharfen Unterscheidungen zwischen dem, was Relationsstrukturen sind, und dem, was sie nicht sind. Weil sie konsequent mit ihrem Primat der Zirkulation umgeht, gründet sie diese Unterscheidungen auf der Unterscheidung zwischen Zirkulationswegen innerhalb von Relationsstrukturen einerseits und zwischen Relationsstrukturen andererseits. Diese Unterscheidungen entsteht wiederum selbst aus der Unterscheidung zwischen Abweichungen von einer _idealen_ Relation und Abweichungen von Abweichungen bzw. von anderen Relationsstrukturen. Dabei zieht die Theorie der Relation die Konsequenzen ihres Grundsatzes, wonach es keine ideale Relation gibt bzw. wonach Relationsstrukturen von einer idealen Relation abweichen, wie Zirkulationen stets von einer idealen Zirkulation abweichen. Die Theorie der Relation bringt also dieses Argument auf den Punkt und sagt, dass Relationsstrukturen ebenfalls von anderen Relationsstrukturen abweichen.

In Bezug auf das Primat der Zirkulation bedeutet dies, dass sich Zirkulationswege innerhalb von Relationsstrukturen prinzipiell von Zirkulationswegen zwischen Relationsstrukturen bzw. von abweichenden Zirkulationswegen von einer bestimmten Relationsstruktur unterscheiden. Wenn wir diese Folge auf der Ebene von Relationsstrukturen zu Ende denken, dann können Abweichungen von Relationsstrukturen konstruktiv für die Theorie als Stratifikationsprinzip dieser Relationsstrukturen durch Zirkulationswege und Zirkulationsmöglichkeiten gedacht werden. Entsprechend können sie als Stratifikationsprinzip dieser Zirkulationen bzw. des Primats der Zirkulation selbst gedacht werden. Ähnlich wie Standing in Bezug auf die zahlreichen Deklinationen von unterschiedlichen mehr oder weniger "strong" oder "weak ties" anmerkt [@Standing2007], sagt die Theorie der Relation, dass es zahlreiche Deklinationen vom Primat der Zirkulation in der Form von diversen Zirkulationen innerhalb und zwischen Relationsstrukturen gibt. Um zu zeigen, wie diese Stratifikation von Zirkulationen und Relatiosstrukturen konkreter abgebildet werden kann, kommen wir zum Begriff der Sequenzen.

## Abweichende Realtionsstrukturen und Sequenzen

Warum sagen wir, dass die Relationsstrukturen von einer idealen oder perfekten Relation abweichen? Gehen wir zu der von John Levi Martin vorgeschlagenen Unterscheidung zwischen "relations" und "relationships", die einen innovativen Begriff der sozialen Struktur und ihrer Einverleibung auf der Ebene von einzelnen Akteure einführt [@Martin2009].

Martin unterscheidet zwischen "relations", die er auf dyadische zwischenmenschlichen Interaktionen bezieht, und "relationships", die das Handeln unterstützen und zu Strukturen führen bzw. die die Prinzipien zur Durchführung einer Handlung widerspiegeln (ebd., 336-337). Diese Unterscheidung ermöglicht, Phänomene zu verstehen, die sich zwar gegenseitig unterstützen, aber dennoch grundlegend verschieden sind. Nach Martin sind die Interaktionen zwischen Menschen keine "relationships", auch wenn sie in aggregierter Form zu solchen "relationships" führen können. Wenn solche "relationships" einmal entwickelt werden, gehen sie über die interagierenden Personen hinaus und unterscheiden sich von deren Interaktionen. Sie beschreiben eine andere Ebene, die Martin als Strukturen bezeichnet, d. h. als "wiederkehrende Muster sozialer Interaktion, wobei sich die Muster auf konkrete Personen (und nicht auf Rollen oder Klassen) beziehen" (ebd., 9). Diese Strukturen können zu umfassenderen Strukturen in Form von breiteren "relationships" führen, die von Individuen geknüpft werden (ebd., 12). Der wichtige Punkt, auf den Martin hinweist, ist, dass diese Strukturen handlungsleitende Prinzipien enthalten und "eine Person mit bestimmten anderen im Gegensatz zu Klassen von anderen verbinden" (ebd., 14). Mit anderen Worten: Diese Strukturen geben den Einzelakteuren Prinzipien, die sie in andere Interaktionskontexte mit anderen Akteuren übertragen können. Wenn diese Übertragung funktioniert -- und sie funktioniert nur mit _bestimmten_ anderen Akteuren, wie Martin hervorhebt (ebd.) --, dann führt sie zum Aufbau von Institutionen. Diese Institutionen spiegeln eine Reihe von Handlungsprinzipien wider, die von bestimmten Akteuren unterstützt werden und die erneut von anderen Akteuren genutzt und abermals in andere Interaktionskontexte übertragen werden können. Dies bedeutet jedoch nicht, dass diese Institutionen auf dieselbe Weise wie die "relationships" strukturiert sind, die zu ihrer Existenz geführt haben. Auch hier wird die Struktur beim Übergang von "relationships" zu Institutionen unterlaufen, ebenso wie beim Übergang von Interaktionen zu "relationships".

Martins Unterscheidung zwischen "relations" und "relationships" ähnelt unserer Unterscheidung zwischen relationalen Ereignissen und Relationsstrukturen. Auch wir stellen fest, dass der Aufbau von Institutionen in Relationsstrukturen auf dem Aufbau von Kollektiven und zwar auf den verschiedenen Ebenen einer Relationsstrukturen in ihren verschiedenen Sequenzen beruht. Vor allem aber beobachten wir keine formale und strukturelle Korrespondenz zwischen diesen drei verschiedenen Ebenen - relationale Ereignisse, Sequenzen/Relationsstrukturen und gesellschaftliche Instanzen in diesen Sequenzen und Realtionsstrukturen. Das eine kann mit dem anderen nicht vereinbart werden, auch wenn es für die Existenz des anderen unerlässlich ist. Mit anderen Worten: Wenn Interaktionen eine Voraussetzung für die Existenz von "relationships" sind, die wiederum für die Existenz von gesellschaftlichen Instanzen notwendig sind, weichen die "relationships" sowohl von Interaktionen als auch von gesellschaftlichen Instanzen ab. Wenn wir von Divergenz sprechen, verallgemeinern wir diese Überlegung auf alle möglichen Verhältnisse. Keine von ihnen kann also perfekt, selbstständig, selbsterhaltend, allgegenwärtig oder allmächtig sein. Darüber hinaus verankert die Theorie der Relation diese Überlegung in der Zirkulation als Subversion von Form und Struktur -- oder, um es in Martins Worten zu sagen, als eine Subversion durch Zirkulation der Prinzipien des Handelns zu anderen Interaktionskontexten oder durch die Zirkulation von Individuen zu anderen Interaktionskontexten, zu anderen "relationships" und zu anderen gesellschaftlichen Instanzen. Der Begriff der Sequenzen ermöglicht eine Unterscheidung der grundlegendsten Divergenzen und sie als unterschiedliche Relationsordnungen oder -- im Anschluss an Martin -- als unterschiedliche Relationsprinzipien zu begreifen. Dies ist die Bedeutung von Relationsstrukturen. Sie sind divergierende Relationsordnungen, die Einschreibemöglichkeiten für Akteure und gesellschaftliche Instanzen bieten und Zirkulationen erzeugen, die solche Prinzipien auf andere Ebenen einer Relationsstruktur, auf eine andere ihrer Sequenzen oder auf eine andere Relationsstruktur transportieren. Um diesen Punkt noch fester zu machen, können wir mittels einer Analogie vielleicht noch besser veranschaulichen, was die Theorie der Relation mit diesem Zusammenhang zwischen der Strukturierung von Zirkulationen in relationalen Ebenen und der Abweichung von einer idealen Relation meint. Denken wir etwa an das Bürgerliche Gesetzbuch oder an die Bibel der Psychologen und der Psychiater -- das DSM-Buch --, was merken wir? Wir merken, dass diese Werke nicht aus der Annahme heraus entstanden sind, Menschen in zwei gut getrennte Kategorien zuordnen zu können, als ob es normale und nicht normale bzw. nicht strafbare und strafbare oder gesunde und pathologische Menschen gäbe. Menschen sind sowohl das eine als auch das andere, was dazu beiträgt, dass das menschliche (auch soziale) Leben sehr unterschiedlich entwickelt werden kann, ohne jemals in einer dieser beiden Kategorien endgültig verabsolutiert zu werden. In der Theorie der Relation geht es bei dem Zusammenhang zwischen der Strukturierung von Zirkulationen in relationalen Ebenen und der Abweichung von einer idealen Relation um dieselbe Überlegung. Jetzt kommen wir zurück zu der Beschreibung der Relationsstrukturen als Abweichung von einer idealen Relation.

Die Theorie der Relation unterscheidet grundsätzlich vier Relationsstrukturen, die sie als Abweichungen von einer idealen Relation versteht. Um besser nachvollziehen zu können, wieso sie vier Relationsstrukturen und nicht weniger oder mehr erkennt, müssen wir zuerst danach fragen, was bei der Arbeit an relationalen Ereignissen im Fokus steht. Diese Frage können wir, vereinfacht gesprochen, wie folgt beantworten: So kann entweder a) die Arbeit an relationalen Ereignisse selbst bzw. -- verkürzt gesagt -- die Relation selbst als Interaktion, Handlung, Austausch usw. im Fokus stehen, oder es können b) die Menschen, die sich versammelt haben, um eine solche Arbeit durchzuführen, im Zentrum stehen, ebenso gut können aber auch c) die Einzelakteure oder d) die Mittel, die für diese Arbeit verwendet werden, im Fokus der Arbeit an relationalen Ereignissen stehen. Es gibt also vier mögliche Stützen für die Entstehung von einer bestimmten Ordnung von Verhältnissen, wenn es zur Entwicklung von Verhältnissen kommt, wobei diese Stützen a) die Verhältnisse selbst, b) die Gruppen, c) die Einzelmenschen oder d) die Mediationen, die sie verwenden, darstellen. Daraus ergibt sich in der Theorie der Relation die Auffassung von vier Relationsstrukturen einerseits und von den vier Sequenzen in jeder Relationsstruktur, die sie strukturieren. Dies können wir jetzt enger zur Begrifflichkeit der Theorie der Relation mit der folgenden Beschreibung der Abweichungen von einer idealen Relation verdichten.

Die erste Abweichung von einer idealen Relation entsteht aus der Idealisierung der Relation selbst, die die Dynamik einer ersten Relationsstruktur gestaltet bzw. die Grundmotivation der Investition in die Arbeit an relationalen Ereignissen darstellt. Von einer solchen Idealisierung weicht eine zweite Relationsstruktur ab, in der die Akteure ihre Repräsentation durch Kollektive hervorheben, ohne die keine Arbeit an relationalen Ereignissen möglich wäre. Von dieser zweiten Relationstruktur weicht eine dritte Relationsstruktur ab, in der die Materialität bzw. die Verwirklichung von Akteuren hervorgehoben wird, ohne die die Kollektive nicht existieren würden und eine Investition in die Arbeit an relationalen Ereignissen nicht denkbar wäre. Eine vierte Relationsstruktur weicht von dieser letzten Relationsstruktur ab, in der die Attraktivität von Medien bzw. von Mediationen hervorgehoben wird, die deshalb attraktiv sind, weil sich die Akteure ohne sie nicht verwirklichen könnten, keine Kollektive hervorbringen würden und daher die Arbeit an relationalen Ereignissen nicht bewältigen könnten. Diese vier Prinzipien der Relation entsprechen jeweils der Hauptsequenz, um die jede der vier Relationsstrukturen entwickelt wird -- die Relation zur Sequenz Investition in einer ersten Relationsstruktur, die Kollektive zur Sequenz Repräsentation in einer zweiten Relationsstruktur, die Einzelakteure zur Sequenz Materialität in einer dritten Relationsstruktur und die Mediationen zur Sequenz Attraktivität in der letzten Relationsstruktur. Die Gründe und die Dynamik, die diese Abweichungen bestimmen, können ebenfalls in Bezug auf die Unterscheidung zwischen Position und Relation dargestellt werden.

Die Unterscheidung zwischen Position und Relation kann als Unterscheidung zwischen akteurzentrierten und austauschzentrierten Relationsstrukturen aufgegriffen werden. Diese Unterscheidung bildet die erste Deklination des relationalen Hauptmerkmals von Relationsstrukturen und mündet gleichsam in den ersten zwei Abweichungen von einer _idealen_ Relation. Daraus ergeben sich die zwei Hauptmerkmale von zwei ersten Relationsstrukturen, die einer relations- und einer positionsorientierten Differenzierung bezüglich der Arbeit an relationalen Ereignissen entsprechen und daraufhin entwickelt werden. Aus dieser ersten Unterscheidung in eine austausch- und eine akteurzentrierte Relationsstruktur resultieren ferner zwei weitere Abweichungen. Sie verstehen sich als Abweichungen von einer ausschließlich austausch- und einer ausschließlich akteurzentrierten Relationsstruktur. Diese Abweichungen haben wir als "Abweichungen zweiter Ordnung von abweichenden Relationsstrukturen erster Ordnung" dargestellt [@PapilloudSchultze2022, 24]. Sie bringen zwei weitere Deklinationen des relationalen Hauptmerkmals für zwei weitere Relationsstrukturen hervor: Zum einen eine Relationsstruktur, in der ihrem relationalen Hauptmerkmal entsprechend die Uneingeschränktheit der Austauschzentriertheit durch akteurzentrierte Merkmale relativiert wird, und zum anderen eine Relationsstruktur, in der wiederum die Uneingeschränktheit der Akteurzentriertheit durch austauschzentrierte Merkmale gedämpft wird.

Sei es in Bezug auf die Arbeit an relationalen Ereignissen oder in Bezug auf die Unterscheidung zwischen Position und Relation; wir stellen fest, dass Relationsstrukturen sequentiell etabliert werden. Dies erklärt sich damit, dass sie Abweichungen sind, die weitere Abweichungen produzieren, bis diese Abweichungen erschöpft sind. An welcher Stelle eine Relationsstruktur von einer anderen Realtionsstruktur abweicht, haben wir oben mit der Erwähnung des Hauptmerkmals der jeweiligen Relationsstrukturen signalisiert. Dieses Hauptmerkmal ist der Punkt, der einer Relationsstruktur ihr Unterscheidungsmerkmal im Vergleich zu den anderen Relationsstrukturen gibt. Gleichzeitig ist das Hauptmerkmal von Relationsstrukturen aber auch der Punkt, an dem sich die Relationsstrukturen einerseits voneinander unterscheiden und andererseits intern diversifizieren. Bei diesem letzten Argument der internen Diverzifierzierung von Relationsstrukturen handelt es sich um eine weitreichende Folge aus dem Primat der Zirkulation -- Zirkulationen zirkulieren und sie zirkulieren unterschiedlich -- und gleichzeitig aus der sequentiellen Entstehung von Relationsstrukturen als Abweichungen von einer _idealen_ Relation. Das bedeutet wiederum, dass selbst innerhalb von Relationsstrukturen Abweichungen vom Hauptmerkmal dieser Relationsstrukturen entstehen können, und zwar genauso wie sie zwischen Relationsstrukturen entstehen können. Als wir die Unterscheidung von Relationsstrukturen in Bezug auf die Arbeit an relationalen Ereignissen formuliert haben, haben wir gesagt, dass bei dieser Arbeit entweder die Relation, oder die Gruppe, oder die Einzelakteure, oder die Mediationen fokussiert werden kann. Wenn jedoch eine solche Arbeit eines dieser Element im Besonderen fokussiert, so bedeutet dies nicht, dass die anderen Elemente nicht berücksichtigt werden. Sie werden auch berücksichtigt, und im Laufe der Arbeit an relationalen Ereignissen kann es dazu kommen, dass ein anderes Element eine wichtigere Rolle für die Entwicklung dieser Arbeit spielt, bis sich der Fokus verschiebt. Jede Relationsstruktur stellt in diesem Sinne also eine Zirkulationsordnung mit den Alternativen zu dieser Zirkulationsordnung dar, die, weil sie früher oder später von Akteuren aufgegriffen werden, die Zirkulationsordnung von einer Relationsstruktur und diese Relationsstruktur selbst destabilisieren. Alle Sequenzen in allen Relationsstrukturen sind deshalb gleichzeitig Produkte von solchen Abweichungen und Ausgangspunkte von solchen Abweichungen. Sie strukturieren und destrukturieren die Zirkulation innerhalb und zwischen Relationsstrukturen.

Wir haben also vier Relationsstrukturen, die von denselben vier Sequenzen strukturiert sind. Aus diesem Grund könnte gesagt werden, dass wir in der Theorie der Relation immer mit derselben Relationsstruktur zu tun haben. Eine solche Anmerkung bezieht sich jedoch nur auf eine dezidiert strukturalistische Betrachtung von Relationsstrukturen, die ihre Zirkulationsdynamik nicht berücksichtigt. Verstehen wir dagegen Relationsstrukturen dynamisch, dann sehen wir, dass, obwohl diese Relationsstrukturen nach denselben Sequenzen strukturiert werden, sich die Differenzierung von Zirkulationen nicht ab demselben Abweichungspunkt von einer Relationsstruktur entwickelt. Deshalb kann eine solche Differenzierung nicht demselben Muster in allen Relationsstrukturen gleichermaßen folgen. Obgleich also die Sequenzen Investition, Repräsentation, Materialität und Attraktivität bei jeder Zirkulation in und zwischen Relationsstrukturen anwesend und tragend sind, werden sie nicht in der gleichen Prioritätsordnung mobilisiert. Vielmehr werden sie sequentiell ab dem Punkt mobilisiert, der in einer Relationsstruktur ihr Hauptmerkmal darstellt. Deshalb unterscheidet die Theorie der Relation ab dem Primat der Zirkulation vier Relationsstrukturen, die sich nicht strukturell, sondern zirkulationsbedingt voneinander unterscheiden. Diese Zirkulationsordnung, die jede Relationsstruktur in unterschiedlicher Weise dynamisiert, kann wie folgt beschrieben werden.

Die Relationsstruktur, die ab der Sequenz Investition abweicht, zeigt eine interne Anordnung von Sequenzen, die von der Investition in die Arbeit an relationalen Ereignissen, zur Repräsentation dieser Investition, zur Materialität dieser Repräsentation und zur Attraktivität der Materialität von der Investition in die Arbeit an relationalen Ereignissen verläuft. Davon weicht eine zweite Relationsstruktur ab der Sequenz der Repräsentation ab, die eine interne Anordnung von Sequenzen bedingt, deren Hauptmerkmal die Repräsentation der Arbeit an relationalen Ereignissen durch Repräsentanten ist, die zur Materialität dieser Repräsentation, ihrer Attraktivität und der Investition in die Repräsentation von einer solchen Arbeit geht. Die Relationsstruktur, die von dieser letzten Relationsstruktur ab der Sequenz der Materialität abweicht, weist eine Anordnung von Sequenzen auf, die von der Materialität der Arbeit an relationalen Ereignissen zu ihrer Attraktivität, der Investition in diese Materialität und zur Repräsentation dieser Investition verläuft. Schließlich weist die letzte Relationsstruktur ab dem Punkt der Attraktivität der Arbeit an relationalen Ereignissen eine Abweichung auf, die zu einer Anordnung von Sequenzen führt, die zur Investition in eine solche Attraktivität, zu ihrer Repräsentation und zur Materialisierung ihrer Repräsentation geht. Anders formuliert, könnte gesagt werden, dass jede der vier Relationsstrukturen einen Standpunkt zur Relation darstellt und zwar nachgerade wie diese Relation wahrgenommen und in Form von Zirkulationen praktisiert wird, wovon in jeder Relationsstruktur unvermeidlich abgewichen wird. Zur ersten Relationsstruktur zählt die Relation an sich. In der zweiten Relationsstruktur zählt ihre Repräsentation durch Kollektive. In der dritten Relationsstruktur zählen die konkreten Akteure, die diese Kollektive bilden, und in der letzten Relationsstrukturen zählen die Mediationen der Relation selbst, die Kollektive und Akteure unvermeidlich in Unterstützung der Relation beziehen. Diese Bezeichnung der vier Relationsstrukturen ist gleichzeitig eine Bezeichnung der vier Sequenzen, die in jeder Relationsstruktur gleichermaßen anwesend sind. Daraus ergibt sich eine vollständige Beschreibung von Relationsstrukturen in jeder ihrer Sequenzen, die ihre formalen und strukturellen Eigenschaften vom Primat der Zirkulation subvertiert sieht und sich entsprechend in einem dynamischen Theorierahmen zur Untersuchung von gesellschaftlichen Phänomenen _durch Relation_ niederschlägt.

Jenseits von Position und Relation und jenseits von einer möglichen Arbeit an relationalen Ereignissen gibt es schließlich das, was Relationsstrukturen nicht sind. Weil Relationsstrukturen aufgrund ihrer Zirkulation voneinander abweichen, gibt es keine unmittelbare Verbindung zwischen Relationsstrukturen. Es gibt vielmehr Trennungen, die zwischen diesen Relationsstrukturen sowie zwischen Sequenzen von Relationsstrukturen innerhalb jeder Relationsstruktur auftauchen. Solche Trennungen bilden einen Orientierungsraum -- auch in Anlehnung an die Transaktionsräume, von denen François Dépelteau spricht [@Depelteau2013b] -- für Zirkulationen ausgehend von einer Relationsstruktur zu einer anderen Relationsstruktur bzw. von einer Sequenz in einer Relationsstruktur zur nächsten Sequenz in derselben Relationsstruktur. Das sind zusätzliche Abweichungen von abweichenden Zirkulationen, die jedoch nicht _ad infinitum_ wiederholt werden können. Weitere Abweichungen von Relationsstrukturen, die zu weiteren bzw. mehr Relationsstrukturen oder Sequenzen führen würden, existieren nicht. Oder anders gesagt: Weitere Abweichungen von Relationsstrukturen ergeben sich stets als eine Abweichung von diesen vier Relationsstrukturen für eine gegebene Relationsstruktur bzw. eine Abweichung von den vier Sequenzen für eine gegebene Sequenz von einer Relationsstruktur.

Bei Zirkulationen verhält es sich ähnlich wie bei Relationsstrukturen. Einzelakteure und Aktanten unterschiedlicher Natur (wie Zeichen, Symbole, Medien, Gegenstände, Bakterien) zirkulieren, selbst wenn sie unterschiedlich zirkulieren. Hier zieht die Theorie der Relation die Lehre der relationalen Auffassungen zur _agency_  [vgl. @Somers1994; @Emirbayer1998; @White2008; @Mische2011], nach der die Identität von Akteuren nicht zufriedenstellend anhand von Kategorien (gender, Alter, Beruf, Wohnort, Haltung) erfasst werden kann, ohne die Akteure zu stigmatisieren. Deshalb konvergieren die Unterstützer:innen der relationalen _agency_ zu einer Problematisierung von Akteuren als sequentielle Einbettungen von kulturellen, sozialen und persönlichen Merkmalen. Die Theorie der Relation dreht dieses Erklärungsmuster um. Statt von einer Einbettung dieser Dimensionen in Einzelakteure zu sprechen, wonach das Einzelmerkmal dieser Akteure als ihre spezifische Identität bzw. als _agency_ aufgefasst wird, spricht die Theorie der Relation von einer Einschreibung dieser Akteure in Zirkulationen, die ihre Identität singularisieren [@Thevenot1984; @Lahire2001]. Nicht die Einbettung von unterschiedlichen Dimensionen tragen zum Alleinstellungsmerkmal jedes Akteurs bei, sondern die Einschreibung dieser Akteure in unterschiedliche Zirkulationen, Sequenzen und Relationsstrukturen tragen zum Alleinstellungsmerkmal ihrer Identität als Akteur bei. Diese Identität von Akteuren, die als ihre relationale Identität verstanden werden kann, entsteht entsprechend als Besonderheit ihrer Zirkulation bzw. wird entsprechend als solche hervorgehoben. Eine solche Umformulierung der relationalen _agency_ unterstützt das Primat der Zirkulation insofern, als sie voraussetzt, dass Akteure und Aktanten mehr oder weniger gut in Zirkulationen eingeschrieben werden bzw. sie als mehr oder weniger gelungene _agency_ durch Relation als Zirkulation verwirklicht werden. Deshalb führt eben diese Umformulierung dazu, den Begriff der _agency_ nach Zirkulation bzw. nach zirkulierenden und nicht zirkulierenden Akteuren wie folgt zu differenzieren. Einzelakteure und Aktanten zirkulieren, selbst wenn ihre Zirkulation unterschiedlich verläuft, wie wir weiter unten erklären werden. Kollektivakteure und die daraus entstandenen gesellschaftlichen Instanzen der Vermittlung von Zirkulationswegen und -möglichkeiten zirkulieren dagegen nicht. Sie altern in Sequenzen und Relationsstrukturen, in denen sie aus- und abgebaut werden. Wie für Relationsstrukturen und Sequenzen von Relationsstrukturen ruht diese Unterscheidung zwischen zirkulierenden und nicht-zirkulierenden Akteuren auf dem Begriff der Einschreibung. Weil dieser Begriff eng mit den Begriffen des Widerstandes und der Reziprozität im Rahmen der Theorie der Relation verbunden ist, werden wir uns im Folgenden mit diesen drei Begriffen beschäftigen. Sie erlauben eine vollständige Beschreibung der relationalen Identität von Akteuren auf Basis ihrer Zirkulation bzw. an der Schnittstelle zwischen Position und Relation, zwischen Person, gesellschaftlichen Instanzen und Mediationen.

## Einschreibung

Die Begriffe der Einschreibung, des Widerstandes und der Reziprozität beschreiben das, was Zirkulationen konkret brauchen, um zu zirkulieren bzw. um Sequenzen von Relationsstrukturen und diese Relationsstrukturen zu strukturieren, woraus sich unterschiedliche Zirkulationen, entsprechende Tätigkeiten und Tätigkeitsbereiche sowie (Kollektiv)Akteure und der Einbezug von Aktanten ergeben. Weil Relationsstrukturen formal und strukturell auf denselben Grundprinzipien ruhen, sind sie grundsätzlich auf alle sozialen Tätigkeiten und Tätigkeitsbereiche offen. Da wir jedoch Formen und Strukturen der Relationsstruktur durch das Primat der Zirkulation subvertieren bzw. auf der Grundlage von Zirkulationen umdenken, ist es wahrscheinlich, dass Tätigkeiten und Tätigkeitsbereiche nicht beliebig aufgebaut werden, sondern sich der Aufbau dieser danach richtet, wie sie die Zirkulationen bzw. die sequentielle Organisation von solchen Zirkulationen in den entsprechenden Relationsstrukturen unterstützen. Eine solche Unterstützung ergibt sich aus der Einschreibung von Akteuren mit Aktanten und informellen oder formellen Kollektivakteuren wie Institutionen und Organisationen in solchen Zirkulationen von Relationsstrukturen.

Der Begriff der Einschreibung kann deshalb als die komplementäre Seite der Unterscheidung von Relationsstrukturen und von Sequenzen in Relationsstrukturen verstanden werden. Einerseits verdeutlicht die Einschreibung die Position von Akteuren in Relationsstrukturen, während sie andererseits und gleichzeitig über ihre geleistete und über ihre zu leistende Zirkulation informiert. Die Einschreibung setzt dann sowohl eine Verankerung in Relationsstrukturen bzw. in Sequenzen von Relationsstrukturen (Positionsansatz) als auch eine Verteilung auf Relationsstrukturen bzw. auf weitere Sequenzen von Relationsstrukturen (Relationsansatz) voraus. Sie differenziert also Zirkulationswege von Akteuren, die sie wiederum potenziert bzw. die sie auf weitere Zirkulationsmöglichkeiten eröffnet. Dies ist die allgemeine Bedeutung des Begriffes der Einschreibung, die wir jetzt vertiefend vom Standpunkt der Arbeit an relationalen Ereignissen weiter vertiefen.

Der Begriff der Einschreibung setzt voraus, dass eine soziale Arbeit an relationalen Ereignissen geleistet, aus- und durchgeführt wird. Dies bedeutet eine Involvierung von Akteuren mit anderen (Kollektiv)Akteuren und mit Aktanten in diese relationalen Ereignisse, wobei eine Involvierung allein nicht ausreicht, wenn sie nicht zugleich diese Akteure und Aktanten mobilisiert bzw. wenn sie nicht ihre, wenn auch schwache, Zusammenstellung leistet. Arbeiten, die kaum begeistern und von denen sich die Akteure früher oder später abwenden, gibt es genug, was belegt, dass Einschreibungsakte nicht ständig passieren müssen. Arbeiten, die verwirklicht werden müssen oder die man gerne verwirklichen möchte, Beschäftigungen, die einem die innere Ruhe rauben, gibt es jedoch auch in Hülle und Fülle, die verdeutlichen, dass Einschreibungsakte ebenso ständig passieren können. Eine solche Involvierung hinterlässt psychische und physische Spuren. Sie treibt die Akteure manchmal ein Leben lang an und um. Sie verändert sie im Laufe der Zeit, bis diese Einschreibung, so schlecht sie manchmal auch stattfinden mag, anerkannt wird und zur Legitimation der Akteure führt, die sich involviert haben, so bescheiden diese Legitimation manchmal auch ausfallen mag, wie etwa bei der Bestätigung von vorhandenen grundsätzlichen Rechten [@Thevenot2001; @Boltanski2007]. Mit dieser Grundbetrachtung der Einschreibung wird gleichzeitig gesagt, dass sie nicht für alle Akteure dieselbe Bedeutung hat.

Einzelakteure im Sinne von menschlichen Akteuren brauchen eine solche Einschreibung zur weiteren Unterstützung der Umstellung ihrer Position in Sequenzen und Relationsstrukturen bzw. für weitere Beschäftigungen mit relationalen Ereignissen. Kollektivakteure brauchen dagegen eine solche Einschreibung zur weiteren Konsolidierung ihrer Position. Wie Latour sagen würde, sind Kollektivakteure Gewährleistungen von _obligatory passage points_ für Akteure [@Latour2005], die die vorausgesetzte Arbeit von Akteuren verdeutlichen und (positiv oder negativ) sanktionieren. Aktanten brauchen dagegen an sich keine Einschreibungen, weil ihre Zirkulation nicht in bestimmten Sequenzen oder Relationsstrukturen, sondern überall in diesen Sequenzen und Relationsstrukturen entwickelt wird. Deshalb hängen Aktanten nicht von der Zirkulation von Akteuren oder von der Position von Vermittlungsinstanzen ab, um zu zirkulieren. Dies wiederum gewährleistet, dass sie in jeder Zirkulation von jedem Akteur und von jeder Art von Vermittlungsinstanz aufgegriffen und verwendet oder demgegenüber abgelehnt und verworfen werden können. Wenn also Aktanten entweder in Unterstützung oder als Förderung der Einschreibung von Akteuren und Vermittlungsinstanzen fungieren, tragen sie gleichzeitig auch zur Komplexität dieser Einschreibung und zu ihrer abweichenden Natur als eine Einschreibung bei, die nicht und niemals ideal erfolgen kann.

Eine Einschreibung ist also ein Akt der mehr oder weniger gut gelungenen Involvierung der Akteure bei ihrer Arbeit an relationalen Ereignissen mit Kollektivakteuren und Aktanten. Sie ist ein Relativierungsfaktor der Arbeit sowohl von Akteuren als auch von Vermittlungsinstanzen in dem Sinne, als die Einschreibung die Tätigkeiten von beiden Parteien in ein Verhältnis setzt bzw. sie in einer Relationstruktur und in einer ihrer Sequenz verankert. Aufgrund der abweichenden Natur von Relationsstrukturen, der Vielfalt von Zirkulationsmöglichkeiten und von Instanzen der Vermittlung von solchen Zirkulationen auf den unterschiedlichen sequentiellen Ebenen von Relationsstrukturen erfolgen Einschreibungsakte nie einseitig -- etwa als ob sie nur von den zirkulierenden Akteuren allein getätigt werden könnten. Einschreibungsakte setzen immer die Einschreibung von anerkennenden und legitimierenden Kollektivakteuren in die relationalen Ereignisse voraus, an denen die Akteure mit Aktanten arbeiten bzw. an denen sie gearbeitet haben. Diese Kollektivakteure, die die Theorie der Relation als die Grundlage von Vermittlungsinstanzen versteht, sind deshalb und wie bereits oben erwähnt grundsätzlich Instanzen der Vermittlung von Zirkulationswegen und Zirkulationsmöglichkeiten für Akteure in Relationsstrukturen und in deren Sequenzen [zu einer ähnlichen Auffassung von Kollektiven, siehe @Grossetti2018; @Grossetti2022]. Sie verdeutlichen das Primat der Zirkulation, wie es in jeder Sequenz einer Relationsstruktur verstanden wird, in denen wiederum diese Vermittlungsinstanzen aufgebaut wurden.

Oder anders formuliert: Instanzen der Zirkulationsvermittlung sozialisieren die Akteure auf ein Verständnis von Zirkulation, von Sequenzen, von Relationsstrukturen und fördern wie sanktionieren sie entsprechend. Deshalb spricht die Theorie der Relation von einer _doppelten Einschreibung_ der Akteure und der Vermittlungsinstanzen in die soziale Arbeit an relationalen Ereignissen. Akteure schreiben sich mit Vermittlungsinstanzen in die Arbeit an relationalen Ereignissen ein, woraus nicht nur eine Anerkennung und eine Legitimität für die Akteure resultiert, sondern auch für die Vermittlungsinstanzen.

Aus der abweichenden Natur von Sequenzen und Relationsstrukturen und den entsprechend mehr oder weniger gut gelungenen Einschreibungsakten ergibt sich, dass die doppelte Einschreibung nicht ein für alle Mal stattfindet. Sie muss wiederholt mit weiteren Vermittlungsinstanzen von Sequenzen und Relationsstrukturen im Laufe der Zirkulationen von Akteuren entwickelt werden. Dort erfindet die Theorie der Relation das Rad nicht neu. Einerseits unterstützt sie den weit verbreiteten soziologischen Ansatz wie etwa in den Sozialisations-, Rollen- und Konkflikttheorien, nach denen sich die Folgen von Zirkulationswegen aus wiederholten wie lebenslangen Einschreibungsakten von Akteuren mit gesellschaftlichen Vermittlungsinstanzen ergeben. Andererseits greift sie dieses Argument in Bezug auf das Primat der Zirkulation so auf, dass Einschreibungsakte zwar für die Zirkulationswege der Akteure bestimmend sind, sie ihre Bestimmungskraft jedoch unterschiedlich stark oder schwach je nachdem entwickeln, welche Akteure auf welche Vermittlungsinstanzen in welchem starken oder schwachen Zustand von einer Sequenz in einer Relationsstruktur angewiesen sind.

Etwa die Selektionsfunktion von gesellschaftlichen Bildungsinstanzen wie Schulen oder Hochschulen bleibt in der Zeit nicht unverändert. Sie variiert nicht nur in Bezug auf Schüler bzw. Studenten (Akteure) und auf ihre Ursprungsmilieus (Kollektivakteure), die sich mit solchen Vermittlungsinstanzen einschreiben. Sie variiert ebenso in Bezug auf die Anwesenheit oder Abwesenheit von konkurrierenden Bildungsinstanzen in anderen Sequenzen von einer Relationsstruktur wie in anderen Relationsstrukturen. Schließlich verändert sie sich auch in Bezug auf die gesellschaftliche Bedeutung von Bildung als symbolische Mediation in den Relationsstrukturen [dazu vgl. @Euriat1995; @Merle2002; @Albouy2003; @Lozach2020]. Diese Variationen der Bestimmungskraft von Einschreibungsakten schlagen sich in unterschiedlichen Zirkulationswegen und Zirkulationsmöglichkeiten für die Akteure nieder, die ihre Erwartungen und Erwartungen auf Erwartungen entlang der Entwicklung von solchen Zirkulationswegen und Zirkulationsmöglichkeiten bestimmen. Dies hat entsprechende Folgen für die Mobilität der Akteure innerhalb und zwischen Sequenzen von Relationsstrukturen sowie innerhalb und zwischen Relationsstrukturen. Es stratifiziert diese Sequenzen und Relationsstrukturen in unterschiedlicher Weise und lässt sie entsprechend wachsen oder schrumpfen. Diese zwei letzten Punkte werden wir im Rahmen dieses Kapitels nicht weiter ausführen. Sie haben jedoch ein Element gemein, das wir im Rahmen dieser Diskussion zur doppelten Einschreibung näher betrachten möchten. Es handelt sich um den Widerstand der Akteure.

## Widerstand

Der Widerstand der Akteure ist eine Folge der Ausgangslage der Theorie der Relation. Seine Bedeutung kann mit der folgenden Aussage zusammengefasst werden: Aufgrund der Arbeit an relationalen Ereignissen, der Mannigfaltigkeit dieser Ereignisse sowie der Vielfalt sowohl von Akteuren und Aktanten als auch von Vermittlungsinstanzen in Relationsstrukturen kann keine Position in den Relationsstrukturen und ihrer Sequenzen definitiv bezogen werden. Positionen werden früher oder später umgestellt. Deshalb ist etwa die Sozialisation von Akteuren keine Selbstverständlichkeit, sondern eine Zusammenarbeit von Akteuren mit Aktanten an dem Zirkulationsweg, der in einer bestimmten Situation gebahnt werden kann. Diese Zusammenarbeit gewährleistet, dass Akteure nicht auf Positionen reifiziert oder reduziert werden, die sie in ihrer Laufbahn beziehen können, und dass sie nicht mit relationalen Ereignissen gleichgesetzt und daher auf bloße Funktionen oder Träger von Relation reduziert werden. Das ist die Ausgangslage des Widerstandsbegriffes in der Theorie der Relation, zu dem wir jetzt kommen.

Dass Akteure weder auf Position noch auf Relation reduziert werden können bzw. dass sie Positionen und Relationsstrukturen bzw. Sequenzen von Relationsstrukturen und Zirkulationen wechseln können, ergibt sich aus dem Widerstand der Akteure _für_ und _gegen_ sowohl Positionen als auch Sequenzen, Relationsstrukturen und Zirkulationen. Wege, die die Akteure gebahnt haben, und Positionen, die die Akteure bezogen haben, führen nicht zur vollkommenen Zufriedenheit oder zur vollkommenen Enttäuschung der Akteure, sondern zum Erleben und zum Erfahren des abweichenden Merkmals der Relationsstrukturen als Bedingung ihrer Zirkulationen. Der Widerstand spiegelt diese Verkörperung der Umstellung als konstitutive Dualität jedes menschlichen Akteurs als Akteur wider, der durch Relation Positionen in Zirkulationen bezieht und Positionen durch Zirkulation in Relation wechselt. Diese Auffassung des Widerstandes von Akteuren bildet das Gravitationszentrum jener relationalen Identität, die wir im Folgenden vertiefen.

Der Widerstand ist immer ein Widerstand _für_ Zirkulationsmöglichkeiten, die das Alleinstellungsmerkmal jeder Individualität als veränderbares distinktives Glied zwischen Position und Relation ausmachen und daher die Einschreibung des entsprechenden Akteurs unterstützen. Er ist ebenfalls immer ein Widerstand _gegen_ andere Zirkulationsmöglichkeiten und daher andere Zirkulationswege von anderen Akteuren, die die Einschreibung des entsprechenden Akteurs weniger unterstützen bzw. schwieriger machen oder gar verhindern. Der Widerstand ist somit Ausdruck eines wie von Simmel thematisierten individuellen Gesetzes, d. h. einer Reserve, eines Zurückhaltens, eines Skrupels, einer Pudeur. Er bildet die erste Stufe in der Erfahrung vom Kontakt mit relationalen Ereignissen, weiteren (an- wie abwesenden) Akteuren und Aktanten auf der individuellen Ebene und die erste Stufe des Erlebnisses der eigenen Differenz, die sich während der Laufbahn eines jeden Akteurs in weiteren Zirkulationen ausdifferenziert [@Simmel1913]. Oder bildhaft formuliert: Wenn die Einschreibung über die Richtung der Akteurzirkulation informiert, bezeichnet der Widerstand derer Orientierung. Der Widerstand ist damit die Grundlage für die Ausübung der Reflexivität und der Affizierung. Er bereitet den Boden und bildet gleichsam die Ausgangslage für die Bildung von Erwartungen und Erwartungen auf Erwartungen, die zur Arbeit an relationalen Ereignissen führen. Er trägt entsprechend zur Unterstützung bzw. zur Destabilisierung der Einschreibung von Akteuren in Zirkulationen und daher in Relationsstrukturen bei. Weil der Widerstand das individuelle Gesetz zum Ausdruck bringt, und weil Akteure Geschichtsprodukte sind, sind sie sich ihres Widerstandes nicht vollständig bewußt. Deshalb ist der Widerstand in seiner konkreten alltäglichen Erscheinung vielfältig -- von der Erprobung von Tätigkeiten mit unterschiedlichen Akteuren, Aktanten, relationalen Ereignissen zur alltäglichen Entwicklung von Taktiken und Strategien, die die Arbeit an der Mobilisation von anderen Akteuren und an der Verkettung von relationalen Ereignissen begleiten und beeinflussen.

Das Verhältnis zwischen dem Widerstand _für_ und _gegen_ bzw. das Gewicht von beiden Widerstandsaspekten auf die Zirkulation zwischen Positionen durch Relation informiert nicht nur über die Haltung von Akteuren gegenüber ihrer Relationsstruktur und deren allgemeiner Zirkulation. Es entspricht auch den Zirkulationsmöglichkeiten der Akteure und deren Zirkulationswegen entweder innerhalb einer Sequenz von einer Relationsstruktur oder zu einer anderen Sequenz von derselben Relationsstruktur oder aber zu einer anderen Relationsstruktur. Diese letzte Anmerkung lässt sich in Kontrastierung zu Bourdieu besser verstehen, der mit seinem Kampfansatz die _feinen Unterschiede_ zwischen Akteuren mit dem Abhängigkeitspfad zwischen Habitus, Kapitalarten und Feld begründet, wobei jener Abhängigkeitspfad eine soziale Ordnung symbolisiert, die den Akteuren angesichts ihre "_relativen Positionen_ in einem Raum von Relationen" aufgesetzt wird [@Bourdieu2012a, 48]. Mit dem Widerstandsbegriff sagen wir dagegen, dass solche Unterschiede im Zuge der Arbeit der Akteure an relationalen Ereignissen je nachdem gebildet werden, wie stark bzw. schwach diese Arbeit unterstützt wird bzw. wie wahrscheinlich es ist, dass eine solche Unterstütung zu einer konkreten und möglichst bedeutsamen Zirkulation führt. Dies erklärt die Stratifikation von Sequenzen und von Relationsstrukturen nach Zirkulationsmöglichkeiten und Zirkulationswegen, die nicht ein für alle Mal -- etwa wie bei Bourdieu mit der sozialen Herkunft von Akteuren -- gegeben ist, sondern je nach Verbreitung und Schrumpfung von diesen Sequenzen und Relationsstrukturen neu verteilt wird. Die Singularität eines Akteurs besteht also nicht darin, dass er den Unterschied konkret und in Relation zu den anderen Akteuren macht, den er verkörpert. Sie besteht darin, dass ein Akteur diesen Unterschied, den ein Akteur als eine spezifische Auffassung von relationaler Identität verkörpert, in Zirkulationen bringt und daher weiter ausdifferenziert. Die Akteursidentität ist demnach nicht mit der stetigen Behautpung einer sozialen Position verbunden, als ob diese Identität jenseits des gesellschaftlichen Wandels stets abgebildet werden würde, sondern mit einer spezifischen Zirkulation von Position zu Position durch Relation.

Oder anders formuliert: Während die Fragestellung Bourdieus die Macht in Unterstützung der Herrschaft in der Gesellschaft zur Reproduktion der gesellschaftlichen Strukturen adressiert, zeigt die Theorie der Relation ab den Begriffen der Einschreibung und des Widerstandes, dass sich "Gesellschaft" in Zirkulationen durch Relation beweg und eine solche Bewegung zur Unterstützung von einer Relationsstruktur im Vergleich zu anderen Relationsstrukturen sowie zur Unterstützung einer Sequenz im Vergleich zu anderen Sequenzen beiträgt. Daher entsteht eine ungleiche Verteilung von Zirkulationsmöglichkeiten auf Sequenzen und Relationsstrukturen, die sich in entsprechenden Kategorien von Akteuren einerseits und entsprechenden distinktiven Akteuren in diesen Kategorien andererseits widerspiegelt. Dies bedeutet, dass soziale Ungleichheiten auf der individuellen und kollektiven Ebenen in Bezug auf einen gegebenen Zustand der allgemeinen Zirkulation in Sequenzen/in Relationsstrukturen und zwar als Ungleichheit von Zirkulationsmöglichkeiten gedacht werden, die deshalb auch zu ungleichen Zirkulationswegen führen und von Akteurkategorien symbolisiert werden. Soziale Ungleichheit ist in diesem Sinne kein gegebener Zustand von Positionen, sondern ein Merkmal der nach Sequenzen strukturierten und strukturierenden allgemeinen Zirkulation in einer Relationsstruktur, die, je nach Einschreibung und Widerstand in Bezug auf diese Zirkulation, gestärkt oder gedämpft wird. Einfacher gesagt: Ungleich sind vom Standpunkt der Theorie der Relation Akteure, die für vergleichbare Zirkulationswege ungleiche bis keine Zirkulationsmöglichkeiten aufgrund von Veränderungen der Zirkulationen in Sequenzen von einer Relationsstruktur und innerhalb dieser Relationsstruktur erhalten, was die Einschreibung solcher Akteure mit Instanzen von Sequenzen und Relationsstrukturen schwächt oder stört, so sie diese Instanzen überhaupt erreichen können. Dies führt zu vergleichbaren brüchigen, verlangsamten, oszillierenden Zirkulationen, die den Widerstand von Akteuren _gegen_ eine Sequenz oder eine Relationsstruktur, worin sie sich befinden, und _für_ andere Sequenzen oder Relationsstrukturen stärken.

Auf diese Auffassung von sozialer Ungleichheit vom Standpunkt der Theorie der Relation kommen wir in unserem Exkurs am Ende von diesem Band in Einzelheiten zurück. Im Moment wollen wir nur darauf aufmerksam machen, dass soziale Ungleichheiten nicht nur individuelle Akteure, sondern die ganze Breite der Elemente und darunter auch die Vermittlungsinstanzen betreffen, die eine relationale Identität ausmachen. Soziale Ungleichheiten haben dann Folgen nicht nur für Personen und Kategorien von Personen, sondern für die gesellschaftlichen Instanzen, die Mediationen, die Sequenzen und die Relationsstrukturen, die die relationale Identität von Personen dimensionieren und veranschaulichen. An dieser Stelle verwendet die Theorie der Relation den Begriff der Reziprozität.

## Reziprozität

Der Begriff der Reziprozität ist das letzte Glied der Triade Einschreibung-Widerstand-Reziprozität und vervollständigt das Grundgerüst der Theorie der Relation. Wenn die Einschreibung wie die Richtung von Zirkulationen und der Widerstand wie ihre Orientierung fungieren, bezeichnet die Reziprozität den Moment, an dem die Richtung und die Orientierung der Zirkulationen die Position von kollektiven Akteuren stärkt, die zu weiteren Differenzierungen von solchen Zirkulationen und zu weiteren Zirkulationen von Akteuren führen. Mit der Einschreibung, dem Widerstand und der Reziprozität haben wir drei Stufen der Differenzierung der Arbeit an relationalen Ereignissen, worin die nächste Stufe der Differnzierung der jeweils vorherigen Stufen dient. Wir kommen also jetzt, wie bereits zuvor für die Einschreibung und den Widerstand, zu den Merkmalen, die der Reziprozität eigen sind, und perspektivieren diese unter Rekurs auf die doppelte Einschreibung einerseits und den Widerstand der Akteure andererseits.

In jeder Variante der relationalen Soziologien wird davon ausgegangen, dass eine Untersuchung der Gesellschaft nach einem relationalen Ansatz notwendigerweise eine Auffassung von Reziprozität voraussetzt. Die Theorie der Relation ist keine Ausnahme, selbst wenn sie die Reziprozität wie folgt versteht. Statt ontologisch zu argumentieren und die Reziprozität in jeder Art von relationalen Ereignissen als zwischenmenschlichen Leistungszirkel [@Kondylis1999, 498; zur impliziten Reziprozitätsauffassung von Coleman und Bourdieu vgl. @Schultze2022] oder als Stiftungsprinzip einer sozialen Beziehung zwischen Alter und Ego zu sehen [dazu paradigmatisch vgl. @Gouldner1960], sagt die Theorie der Relation, dass eine Reziprozität nur dann gegeben ist, wenn eine doppelte Einschreibung stattfindet. Gibt es keine doppelte Einschreibung, dann gibt es auch keine Reziprozität. Diese scharfe Formulierung verwenden wir, damit verständlich wird, dass nach der Theorie der Relation die Reziprozität keine Hin- und Zurückdynamik ist, die den relationalen Ereignissen _sui generis_ immanent wäre. Dies erklärt sich wiederum -- wie bereits erwähnt -- damit, dass relationale Ereignisse nichts von selbst verbinden.

Ein erstes Merkmal der Reziprozität besteht darin, dass sie die Unterscheidungen zwischen Akteuren (in ihren Varianten als Menschen, Kollektive und Nicht-Menschen) und zwischen Akteuren und relationalen Ereignissen im Sinne ihres unterschiedlichen Beitrages zur Zirkulation in Sequenzen und Relationsstrukturen hervorhebt. Zweitens fördert die Reziprozität die Übersetzung von unterschiedlichen Zeiten und Räumen in -- schnelle/langsame oder kurze/lange -- Zirkulationen, die Tätigkeitbereiche in Sequenzen und in Relationsstrukturen verbreiten oder einschränken. Reziprozität ist deshalb sowohl kontextbezogen als auch vom Standpunkt der Stratifikation von Sequenzen und Relationsstrukturen zu verstehen. In Bezug auf die Kontextbezogenheit entwickelt sich die Reziprozität als Differenzierungsprinzip von Tätigkeitsbereichen, wohingegen sie sich vom Standpunkt der Stratifikation als Prinzip der (neuen) Verteilung von Akteuren auf Tätigkeitsbereiche entwickelt. Die Reziprozität legitimiert üsomit die Umstellungen von Positionen durch Relation, die die Tätigkeitsbereiche, die Sequenzen und die Relationsstrukturen strukturieren.

Anders gesagt: Das Reziprozitätkonzept der Theorie der Relation ist nicht unmittelbar mit Tausch und somit auch nicht unmittelbar mit interdependenten Tauschpraktiken verbunden. Sie entwickelt sich nicht von bipolaren zu multipolaren oder von linearen zu zirkulären Interaktionen _zwischen Menschen_ [vgl. @Lévi-Strauss1981, 642-643; vgl. auch @Mauss1989], weil Reziprozität unmittelbar mit der Einschreibung und mit dem Widerstand verbunden ist und aus dieser Verbindung verwirklicht wird. Reziprozität ist keine Norm, sondern das Ergebnis der Arbeit an relationalen Ereignissen auf der Grundlage der mehr oder weniger erfolgreichen Einschreibung in Sequenzen und Relationsstrukturen unter der Bedingung des Widerstands dieser Einschreibung an der Seite von Einzel- und Kollektivakteuren. Sofern diese Arbeit unterschiedlich ausfällt, weil unterschiedliche Widerstände aufseiten der Akteure entwickelt werden, dann ist die Einschreibung in Relationsstrukturen gestört oder geschwächt. Hieraus ergibt sich dann eine gestörte oder schwache Reziprozität, die die Zirkulation von Einzelkteuren und die Position von Kollektiven und Vermittlungsinstanzen gefährdet. In diesem Fall wird die Relationsstruktur in Teilen oder insgesamt geschwächt, weil Abweichungen von der doppelten Einschreibung die Unterschiede zwischen den Zirkulationen einer Relationsstruktur sowohl für die Akteure als auch für die Vermittlungsinstanzen verwischen. Dies veranlasst eine zahlenmäßige Schrumpfung der Akteure einer Relationsstruktur und zieht gleichsam eine zahlenmäßige Schrumpfung der Vermittlungsinstanzen einer Relationsstruktur nach sich. Akteure wechseln die Relationsstruktur und Vermittlungsinstanzen werden abgebaut. Für die übrig gebliebenen Akteure der so geschwächten Relationsstruktur bedeutet dies, dass sich ihre Zirkulationsmöglichkeiten stark minimieren. Wird allerdings die Einschreibung gestärkt, weil Widerstände in einer Relationsstruktur konvergieren, dann werden die Reziprozität, die Zirkulationswege und die Zirkulationsmöglichkeiten in dieser Relationsstruktur gestärkt, was schließlich diese Relationsstruktur in einer oder mehreren ihrer Sequenzen stärkt. Die Reziprozität kann also relationale Identitäten sowohl potenzieren als auch schwächen.

Dieses Verständnis von Reziprozität aus der Verbindung mit der doppelten Einschreibung und dem Widerstand vermeidet das Problem, dass eine Formulierung der Reziprozität als Zwischenmenschlichkeit zwischen Einzelakteuren oder Gruppen von Akteuren mit sich bringt: Akteure könnten die Rezprozität unmittelbar beeinflussen und ihre Bedeutung verändern bzw. sie stärken oder schwächen. Dies würde bedeuten, dass die Reziprozität sowohl in der Kontrolle der Akteure als auch der Vermittlungsinstanzen stehen würde, _als ob_ sie Einschreibungsakte, Zirkulationen, Sequenzen und Relationsstrukturen kontrollieren würden. Eine solche Vorstellung der Reziprozität vergäße dabei die Einbettung von Akteuren und Vermittlungsinstanzen in die Ebenen von Relationsstrukturen, deren Wechselspiel sowie deren Folgen im Sinne der Produktion von Abweichungen aus diesem Wechselspiel, die sie nicht nach Belieben oder unbesehen beherrschen, geschweige denn ausschalten können. Eine solche Auffassung von Reziprozität hätte zudem den Nachteil, zu einem Ansatz zu führen, der unintendierte Wirkungen der Reziprozität wie etwa das Pflichtgefühl gegenüber anderen Akteuren oder Kollektiven, die Identifikation mit einer Tätigkeit oder das Gefühl der Zugehörigkeit zu einem Kollektiv nicht adressieren könnte, ohne solche unintendierte Wirkungen der Reziprozität auf die bewusste bzw. intendierte Verwendung der Reziprozität zu reduzieren. Dabei würde die Reziprozität auf strategisches Handeln eingeschränkt und als aus interpersönlichen gewöhnlichen Alltagsverhältnissen entstanden verstanden werden, in denen jedoch nur ihre Spuren aus vergangenen Einschrebungsakten für Akteuren und Kollektiven wahrzunehmen seien. Ein solcher Glaube an eine Reziprozität, die aus der Zwischenmenschlichkeit entstehen und die ganze Gesellschaft strukturieren würde, belegt dagegen eindringlich, wie wichtig Einschreibungen für Akteure und Kollektiven sind, die deshalb nach einer solchen Reziprozität überall suchen, selbst wenn sie nur selten bzw. aus Einschreibungsakten entsteht und gleichsam mit ihnen vergeht.

Deshalb sagt die Theorie der Relation, dass die Akteure einen indirekten Einfluss auf die Reziprozität ihrer Relationsstruktur ausüben, den sie einerseits auf der Grundlage ihrer Arbeit an relationalen Ereignissen und andererseits über ihre darüber bewerkstelligte Einschreibung mit Vermittlungsinstanzen in dieser Relationsstruktur akquirieren. Über die Möglichkeit indirekter und zugleich dauerhafter Einflussnahme auf die Reziprozität in einer Relationsstruktur verfügen auch die Vermittlungsinstanzen. Anders als die Akteure generieren sie diesen Einfluss jedoch, indem sie -- vermittelt über ihre Vermittlungsarbeit -- die Zirkulation in ihrer Relationsstruktur regulieren, was es ihnen erlaubt, ihre Vermittlungsstruktur zu erhalten bzw. auszudehnen. Dies ist eine Konsequenz der Nicht-Zirkulation von Vermittlungsinstanzen. Wie oben erwähnt, zirkulieren Vermittlungsinstanzen -- im Unterschied zu Akteuren und Aktanten -- nicht innerhalb von Sequenzen einer Relationsstruktur oder zwischen Relationsstrukturen. Deshalb erschöpft sich ihre Vermittlungsstruktur jedoch keineswegs in der Sozialisation und Förderung von Akteuren, was wiederum bedeutet, dass Vermittlungsinstanzen nicht _per se_ darauf abzielen, eine unmittelbare Wirkung auf Akteure und Aktanten auszuüben, sondern ihre Vermittlungsstruktur idealerweise über die gesamte Relationsstruktur hinweg auszudehnen. Diese Verbreitung ihrer Vermittlungsstruktur erfolgt umso erfolgreicher, als durch ihren indirekten Einfluss auf die Reziprozität Vermittlungsinstanzen stets versuchen, langfristig ihre Position als Instanzen der Vermittlung einer Relationsstruktur für die Akteure derselben Relationsstruktur zu bewahren und mit dem idealen Ziel zu stärken, ihren Einfluss auf die ganze Relationsstruktur zu verbreiten, in der sie entstanden sind. In diesem Sinne sind Vermittlungsinstanzen nicht nur für die Zirkulation von Akteuren wichtig, sondern auch für die Verbreitung von Sequenzen und Relationsstrukturen auf andere Sequenzen und Relationsstrukturen.

Angefangen mit der Ausgangslage der Theorie der Relation und in Anlehnung an den Beitrag von Knöbl zur Kritik der Verwendung von Prozessbegriffen in den Sozialwissenschaften, zu denen durchaus auch der Begriff der Relation zählt, haben wir versucht, in der Herausforderung dieser Kritik die Grundlage der Theorie der Relation sowie ihr Verständnis von Relation im Lichte des Primats der Zirkulation zu erklären. Dies führt zur Botschaft der Theorie der Relation, womit wir nun dieses Kapitel zur Ausgangslage der Theorie der Relation schließen.

## Schlusswort

Die Theorie der Relation besagt, dass Relation als ideale, perfekte Relation die Grundmotivation des sozialen Lebens und die Grundlage der Rechtfertigung der vielfältigen Verhältnisse darstellt, die das gesellschaftliche Leben generiert und die Abweichungen von einer solchen idealen Relation in Form von Relationsstrukturen sequentiell dimensionieren. Die Theorie der Relation erklärt entsprechend, wie dieses Streben nach einer idealen Relation auf den unterschiedlichen Ebenen einer Gesellschaft ständig gestört wird, woraus bzw. wodurch wiederum Zirkulationen von Akteuren, Mobilisierungen von Kollektivakteuren, Einschreibungsakte, auf- und absteigende Mobilitäten, Veränderungen von Ungleichheiten, von Einflussstrategien und Machtkämpfen produziert werden.

In diesem Kapitel haben wir uns bemüht, die Ausgangslage der Theorie der Relation zu verdeutlichen -- angefangen bei dem Primat der Zirkulation, den relationalen Ereignissen, dem abweichenden Merkmal von Relationsstrukturen und deren Sequenzen über die soziale Arbeit zur Umstellung von Positionen, die Sequenzen von Relationsstrukturen und Relationsstrukturen, den Widerstand der Akteure bis hin zur Differenzierung dieser Arbeit und der entsprechenden Einschreibung mit Vermittlungsinstanzen in Zirkulationen. Auf Basis dieser Ausgangslage der Theorie der Relation ist es möglich, die Kernfrage zu formulieren, die diese Theorie stellt und die wie folgt zusammengefasst werden kann: Wie gehen unsere Gesellschaften in allen ihrer Komponenten und Dimensionen mit Umstellungen um, die zu Einschreibungen von Akteuren, Vermittlungsinstanzen mit Aktanten und Medien in Zirkulationen von Relationsstrukturen und schließlich in diesen Relationsstrukturen ab ihren Sequenzen münden? Diese Frage ist vielleicht diejenige, die die relationalen Soziologien und die Soziologien, die nach einem relationalen Ansatz argumentieren, strukturiert und in ihrer Diversität eint. Im Rahmen der Theorie der Relation bekommt diese Frage eine eindeutige Antwort, die sich auf den unterschiedlichen Ebenen dieser Theorie deklinieren und dimensionieren lässt: Nach Zirkulation durch Relation.

Im Unterschied zu anderen oder ehemaligen relationalen Ansätze, die in der Soziologie entwickelt wurden, um eine Erklärung der Gesellschaft auf der Grundlage von relationalen Ansätzen zu formulieren, zielt die Theorie der Relation darauf ab, ihren Relationsansatz nicht auf einer einzigen Bedeutung von Relation und daher Relation nicht auf einer spezifischen Interaktion sowie Relation nicht auf einer Auffassung der Gesellschaft _als_ Relation zu reduzieren. Deshalb dekonstruiert sie solche Formen von Relationismus zum Vorteil einer analytischen, diachron und synchron vergleichenden Betrachtung von Gesellschaften im Wandel, das heißt, in ihren unterschiedlichen Konfigurationen als veränderbare Zirkulationswege und Zirkulationsmöglichkeiten innerhalb und zwischen Relationsstrukturen, die diese Gesellschaften von ihren Instanzen bis zu ihren Akteuren charakterisieren. Damit ist die Theorie der Relation nicht nur in der Lage, den Relativismus von relationalen Ansätzen aufzugreifen, wonach soziale Phänomene in Relation gedacht werden sollten. Sie kann ebenfalls die Bedeutung und den Preis eines solchen Relativismus im Sinne der Stärkung oder Schwächung von Relationsstrukturen, deren Sequenzen und Zirkulationen bzw. in Bezug auf Mikro-, Meso- und Makroebenen problematisieren. Dabei schlägt sie eine neue Perspektivierung von bekannten Fragen der Soziologie, wie die Frage der sozialen Ungleichheit, der Entwicklung von Legitimationsprozessen, der damit verbundenen Soziabilitätsnetzwerke und deren Wirkung auf die Schließung oder die Eröffnung von alternativen Formen des gesellschaftlichen Lebens jenseits von etablierten Hierarchien, anerkannten Rechten und ausgeübten Formen des Zusammenhaltes vor.

## Literatur
