---
title: "Klappentext"
indent: true
output:
    html_document: default
csl: chicago-author-date.csl
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Was haben der Neffe von Emile Durkheim Marcel Mauss, eine Auswahl an internationalen Künstlern der digitalen Kunst, Arnold Schwarzenegger, der derzeit amtierende Präsident der Ukraine Wolodyrmyr Selenskyj, Kaiser und Päpste im (Hoch)Mittelalter und neue breite Sprachmodelle zur Herstellung von Transformern und zur Verbreitung der sogenannten künstlicher Intelligenz gemein? In diesem Buch argumentieren wir, dass sie innerhalb und zwischen Ordnungen von Verhältnissen zirkulieren und, indem sie Zirkulationen unterschiedlich strukturieren und Stratifizieren, solche Zirkulationen fördern. In der Folge entstehen hieraus  unterschiedliche Formen der Gesellschaft in vergangenen wie gegenwärtigen Zeiten und in den ihnen entsprechenden Räumen, die in Relationsstrukturen abgebildet werden können. Mit diesen Beispielen tragen wir grundsätzlicher dazu bei, das Grundgerüst der Theorie der Relation und dabei ihre wichtigsten Begriffe synchron wie diachron zu illustrieren. Wir vervollständigen diesen Überblick über den relationalen Ansatz der Theorie der Relation mit einem Exkurs zur sozialen Ungleichheit und zeigen, wie diese zentrale Fragestellung der Soziologie mit Hilfe der Theorie der Relation aufgegriffen, perspektiviert und untersucht werden kann.

Die Autorinnen

Dr. Christian Papilloud ist Professor für Soziologie an der Universität Halle-Wittenberg.

Dr. Eva-Maria Schultze ist wissenschaftliche Mitarbeiterin am Institut für Soziologie der Universität Halle-Wittenberg.
