---
title: "Exposé -- Postscriptum zur Theorie der Relation"
indent: true
output:
    odt_document: default
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

**Autoren**: Christian Papilloud, Martin-Luther-Universität Halle-Wittenberg, Emil-Abderhalden-Str. 26-27, D-06099 Halle (Saale), Tel.: +49 (0)345 55 24 250, Email: christian.papilloud@soziologie.uni-halle.de; Eva-Maria Schultze, Martin-Luther-Universität Halle-Wittenberg, Emil-Abderhalden-Str. 26-27, D-06099 Halle (Saale), Tel.: +49 (0)345 55 24 246, Email: eva-maria.schultze@soziologie.uni-halle.de

**Titel**: Postscriptum zur Theorie der Relation

**Genre und Bereich**: Monographie; soziologische Theorie, insb. relationale Soziologie

**Umfang**: Die geplante Monographie soll insgesamt zehn Kapitel zu je 10 bis 12 Seiten à 45-50.000 Zeichen inkl. Bibliographie umfassen, die von einem Prolog (Kap. 1) und einem Schlusswort (Kap. 10) angefangen resp. abgeschlossen wird.

**Vorgesehene Fertigstellung**: Frühling 2025

**Konkurrierende Veröffentlichungen**: Im Moment gibt es auf dem deutschen Markt und abgesehen von der von beiden Autoren verfassten Monographie _Skizze einer Theorie der Relation_ (2022) keine vergleichbare Veröffentlichungen.

### Zusammenfassung und Umfang der vorgeschlagenen Monographie

Ziel der geplanten Monographie ist es, der im letzten Jahr veröffentlichten _Skizze einer Theorie der Relation_ (2022) eine kompakte Nachschrift zur Seite zu stellen, die dem interessierten Publikum, insbesondere aber Sozialwissenschaftlern und Sozialwissenschaftlerinnen sowie Studierenden höherer Semester, den Einstieg in und den Zugang zur Theorie der Relation und ihren sie bildenden Theoriefiguren erleichtern soll. Dieses Ziel soll dadurch gewährleistet werden, dass für den Aufbau der geplanten Schrift eine Doppelstruktur tragend sein soll. Zum Beginn jedes der zehn angedachten Kapitel -- in thematischer Orientierung am Kapitel-Aufbau der vorangegangenen Monographie -- werden ein entsprechender Theoriebaustein mit den damit konvergierenden Konzepten in gebotener Kürze expliziert. Anschließend wird es darum gehen, die jedem Kapitel vorangestellte kompakte Einführung, d. h. die jeweilige Theoriefigur, sowohl anhand bestimmter Gegenstände als auch anhand klassischer wie nicht-klassischer soziologischer Themen exemplarisch zu konkretisieren. Auf Basis dieser für jedes Kapitel einzuhaltenden Doppelstruktur sollen einerseits Anwendungsfelder und die Bandbreite des Erklärungspotentials aufgezeigt werden. Andererseits soll ebenso eine pädagogische Anleitung zur Untersuchung gesellschaftlicher Phänomene _durch Relation_ sowie zur Reichweite und zum Geltungsbereich der Theorie der Relation vermittelt werden.

### Aufbau

Die Struktur der vorgeschlagenen Monographie besteht aus den folgenden Kapiteln.

#### Kapitel 1: Prolog. Ausgangslage der Theorie der Relation

<!--

In diesem Kapitel beschreiben wir die Ausgangslage der TR, also:

1. Primat der Zirkulation
2. Abweichungen von einer perfekten Relation
3. Vier Relationsstrukturen und vier Sequenzen = Rahmen der TR

-->

Braucht die Soziologie eine Theorie der Relation? Die Theorie der Relation ist ein Rahmen zur Deutung gesellschaftlicher Phänomene _durch_ Relation, was die Position präzisiert, die diese Theorie in der Soziologie und speziell in der Familie der relationalen Soziologien bezieht. Mit dem Ausdruck _durch Relation_ unterscheidet sich die Theorie der Relation von anderen relationalen Soziologien, die Gesellschaft als Relation bzw. als eine Zusammenstellung von sozialen Verhältnissen verstehen. Wenn die Theorie der Relation mit den anderen relationalen Soziologien darüber übereinstimmt, dass relationale Ereignisse der Ausgangspunkt der soziologischen Untersuchung bilden, so unterscheidet sie sich doch gleichzeitig von diesen relationalen Soziologien in Bezug auf ihre Grundannahme, die die Theorie der Relation nicht nur hinterfragt, sondern daraus sie die Motivation für die Gründung eines Theorierahmens zieht, mit dem den relationalen Ansatz in der Soziologie neu gedacht werden kann. In dieser Hinsicht repräsentiert die Theorie der Relation Tendenzen der soziologischen Tradition in deren Breite, die sich zentral mit einem relationalen Ansatz in dieser Disziplin auseinandergesetzt haben, auch wenn sie gleichzeitig ein Argument zur aktuellen Theoriedebatte in der Soziologie liefert, dessen Aufbau und Folgen sie von dieser Tradition emanzipiert und ihr ihren eigenen Weg bereitstellt. Dies zeigt sich typischerweise an dem Begriff der Relationsstruktur, dass als Abweichung von einer idealen bzw. perfekten Relation verstanden wird, davon die formale und strukturalistische Formulierung durch das Primat der Zirkulation subvertiert wird, nach dem die Theorie der Relation grundsätzlich argumentiert. Dem Argument der Abweichung folgend, unterscheidet die Theorie der Relation vier Relationsstrukturen, deren sequentielle Entstehung sowie die damit verbundenen Grundbegriffen in diesem Prolog veranschaulicht werden.

#### Kapitel 2: Was uns die Reziprozität der Gabe erzählt

<!--

Hier geht es eben um:

1. die doppelte Einschreibung
2. Widerstand
3. Reziprozität

Damit unterstreichen wir die Bedeutung der Zirkulationswege der Akteure und die Bedeutung der Kollektive als Beschleuniger, Bremse oder Korrekturinstanzen von solchen Zirkulationswege, daraus sich die Zirkulationsmöglichkeiten für die Akteure ergeben.

-->

Nachdem im Prolog gezeigt wurde, dass es im Bereich relationaler Soziologien notwendig ist, sich von einer rekonstruktiven Repräsentation der Gesellschaft als Relation zu distanzieren, um Gesellschaft durch Relation untersuchen zu können, soll in diesem Kapitel das Reziprozitätskonzept der Theorie der Relation im Zentrum stehen. Im Bereich der relationalen Soziologien gibt es eine Übereinstimmung, die die Theorie der Relation teilt, nach der relationale Ereignisse eine Idee von Reziprozität hervorrufen. Dennoch bleiben die relationalen Soziologie vage, wenn es präzisiert werden soll, was eine solche Reziprozität soziologisch bedeutet und wie sie mit relationalen Ereignissen in Verbindung kommen sollte. In diesem Kapitel heben wir in dieser Hinsicht insbesondere ein Manko der relationalen Soziologien hervor, das darin besteht, die Einbettung institutioneller Logiken bei der Einbettung von Akteuren in Mikrointeraktionen konsequent zu berücksichtigen. Um dieses Manko auszuräumen bricht die Theorie der Relation mit dem traditionellen Verständnis von Relation _als_ Zwischenmenschlichkeit, was es in der Folge erlaubt, Reziprozität nicht mehr _als_ ein reziprozierendes Hin und Zurück zwischen Akteuren aufzufassen, sondern Reziprozität vielmehr in Bezug auf Relationsstrukturen und Zirkulation auszubuchstabieren. Dazu gehört es nicht nur, die Reziprozität als Legitimationsmoment der Akteure und ihrer Tätigkeiten, die Reziprozität als Verteilungs- und Schließungsinstrument von Relationsstrukturen zu charakterisieren, sondern auch die Verbindung der Reziprozität zum Widerstand der Akteure kenntlich zu machen.

Das Paradebeispiel, das wir in diesem Rahmen verwenden, um über die Reziprozität im Sinne der Theorie der Relation zu sprechen, ist die Gabe in ihrer unterschiedlichen Formen in der Zeit und der unterschiedlichen Gesellschaften. Wenn Gaben eine starke Idee von Reziprozität mit sich bringen, ist diese Auffassung der Reziprozität ohne Berücksichtigung der Einschreibunsakte von Akteuren in Relationsstrukturen durch ihre Einschreibung mit den Instanzen der Vermittlung dieser Relationsstrukturen (z. B. Organisationen, Vereine, Verbände etc.) und der Einschreibung von Vermittlungsinstanzen in Relationsstrukturen durch ihre Einschreibung mit den Akteuren in diesen Relationsstrukturen nicht denkbar. In der Theorie der Relation führt diese Auffassung von Reziprozität zur Argument, dass einerseits Relationsstrukturen eine Pluralität an Lebenswegen und Lebensmöglichkeiten anbieten, die jedoch je nach Relationsstrukturen mit einem speziellen Verständnis von Reziprozität verbunden sind, die andere Relationsstrukturen nicht teilen bzw. genuin ablehnen, um ihre eigene pluralen Welten auf anderen Relationsstrukturen zu verbreiten. Dies beschreibt eine Tragik der Reziprozität, die aus Einschreibungsakten schöpft, um Verteilungen und Schließungen in Relationsstrukturen zu entwickeln, die auf der Ebene von Akteuren sowohl Widerstand als auch Umstellung von Positionen hervorrufen.

#### Kapitel 3: Zirkulation versus Selektionsdruck in der Kunst

Unter Rekurs auf die in Kapitel 1 und 2 thematisierten Grundbegriffe der Theorie der Relation soll die Grundlage der Konzeptualisierung von vier Relationsstrukturen vorgestellt werden. Dies unterstreicht abermals, dass für die Theorie der Relation keine ontologische Perspektive auf Relation, sondern vielmehr eine Analytik der Zirkulation tragend ist, die deshalb die vier Relationsstrukturen voneinander unterscheidet. Dass sich die vier Relationsstrukturen durch die Zirkulation voneinander abheben, erklärt sich damit, dass jede Relationsstruktur über eine ihr spezifische Kernsequenz verfügt, die nicht nur den Anfangs- und Endpunkt der Zirkulation einer jeden Relationsstruktur markiert, sondern auch die jeder Relationsstruktur eigene sequentielle Ordnung mitbestimmt. Eingedenk dieser Tatsache soll in diesem Kapitel gezeigt werden, wie die Zirkulation in den vier Relationsstrukturen verläuft. Dabei soll es auch darum gehen zu zeigen, dass zwar alle Relationsstrukturen prinzipiell auf alle Tätigkeiten und Tätigkeitsbereiche von Akteuren offen sind; die tatsächliche Entwicklung und Durchführung solcher Tätigkeiten und Tätigkeitsbereiche letztlich aber von der Zirkulation, d. h. der sequentiellen Ordnung der Zirkulation, in einer Relationsstruktur abhängt, durch die bestimmte Tätigkeiten und Tätigkeitsbereiche gefördert, andere dagegen behindert werden.

Zur Illustration der zirkulären Struktur von Relationsstrukturen, der internen Strukturierung von Tätigkeiten und Tätigkeitsprofilen und der damit verbundenen Zirkulation in diesen Relationsstrukturen soll die in der Wirtschaftswissenschaft und Wirtschaftssoziologie gängige organizistische Metapher des _Selektionsdrucks_ mit dem Gesellschaftsbereich der Kunst und des Kunstbetriebs konfrontiert werden. Ziel ist es, deren Erklärungsgehalt und Geltungshorizont in Bezug auf die sukzessive Expansion künstlerisch-kreativer Tätigkeiten und Tätigeitsbereiche in andere Relationsstrukturen und -- visa versa bzw. dem Primat der Zirkulation entsprechend -- die sukzessive Expansion bestimmter Medien orientierter, politisch orientierter sowie wirtschaftlich orientierter Tätigkeiten und Tätigkeitsbereiche in die sozio-kulturell-künstlerisch orientierte Relationsstruktur zu plausibilisieren und kritisch zu prüfen.

<!--
Hier würde ich die Beschreibung für Velbrück beenden -- ja, finde ich gut


Die Überlegung, die für eine solche Übertragung wirtschaftsnaher Erklärungsmodelle auf den Bereich der Kunst maßgebend ist, lässt sich einerseits anhand der wirtschaftlich orientierten Relationsstruktur (Rm) und andererseits anhand der sozio-kulturell-künstlerisch orientierten Relationsstruktur (Ri) exemplifizieren: Die gesellschaftliche Sphäre der Wirtschaft lässt sich soziologisch kaum in ihrer Vollständigkeit erfassen, so sie lediglich auf wirtschaftliche Tätigkeiten und Tätigkeitsbereiche reduziert wird, nicht zuletzt weil wirtschaftliche Tätigkeiten und Tätigkeitsbereiche nicht ausschließlich in materialisierender Arbeit aufgehen. Dies ist damit zu erklären, dass jedwede Materialisierung im Bereich der Wirtschaft -- wie schon Marx anhand seiner Kapitalzirkulation G -- W ... P ... W'-- G' darlegt -- eine über das Monetäre hinausgehende Investition verlangt, die auch auf kreativen, künstlerischen Tätigkeiten basiert und aufgrund der fortschreitenden Ausdifferenzierung der Konsum-, Innovations- und Güterwirtschaft nicht mehr ausschließlich von Ingenieuren und Technikern geleistet werden kann, wenngleich diese Berufsgruppen ebenfalls eine starke funktionale Differenzierung erfahren haben. Produktmaterialisierungen im Sinne der Verwirklichung von Ideen in serieller Produktion entstehen somit auch unter Mitwirkung von Designern und anderen Akteuren mit künstlerisch-industriellen Tätigkeitsprofilen (Rm-i), weshalb das Kreative zum festen Bestandteil der wirtschaftlich orientierten Relationsstruktur (Rm) generierte. Umgekehrt lässt sich sagen, dass auch künstlerische Tätigkeiten und Tätigkeitsbereiche in der Sphäre der Kunst und des Kunstbetriebs nicht allein aus kreativer Arbeit bestehen, sondern eben diese kreative Arbeit -- insb. vor dem Hintergrund der Liberalisierung, der Institutionalisierung, der Professionalisierung und der Formalisierung der Kultursphäre _Kunst_ -- ebenso repräsentative Tätigkeiten (Ri-r) und wirtschaftlich orientierte Aktivitäten (Ri-m) notwendigerweise mitumfassen [vgl. Abb. 3.1 @PapilloudSchultze2022, 82], die wiederum zur Attraktivität der Kunst bzw. des Kunstbetriebs (Ri-a) beitragen und schließlich neue Investitionen (Ri-i) in einen solchen Betrieb fördern.

Zur Vermittlung dieser Überlegung, die zum einen die Ausdifferenzierung von Relationsstrukturen veranschaulichen soll und zum anderen der Einführung in die Schmetterlingspfade von Relationsstrukturen im Sinne der Ausdifferenzierung von Sequenzen in Relationsstrukturen dient, werden wir mit der Metapher des _Selektionsdrucks_ arbeiten. Dieser Metapher folgend, sei das Überleben bestimmter Organisationen und Institutionen deshalb wahrscheinlicher, weil der Druck zur Selektion -- in Analogie zu den durch natürliche Selektion entstandenen Präferenzen/Spezialisierungen und den damit verbundenen günstigeren Überlebenschancen -- zu effizienten Strukturen der Organisationseinheit und effizienten Lösungen der Organisation führe, die dann ein bestimmtes Beharrungsvermögen erlangen und der Organisation günstigere Überlebenschancen bieten [vgl. bspw.@Williamson1981, 573ff.; @WilliamsonOuchi1981, 389; zur Kritik am Selektionsdruck @Granovetter2000, 199-201; vgl. zur Verwendung von Metaphern in den Sozialwissenschaft @Schmitt2017; @Lutter2016; McCloskey2015]. In diesem Zusammenhang ist zu fragen, welcher Erklärungswert dieser Metapher zukommt, wenn man sie mit der Ausdifferenzierung der sozio-kulturell-künstlerischen Relationsstruktur (Ri) im Sinne der Liberalisierung, Institutionalisierung und Professionalisierung der Kunstsphäre inkl. der Expansion von kreativen Tätigkeitsbereichen über die kulturell-künstlerisch orientierte Relationsstruktur (Ri) hinaus -- bspw. in Bezug auf Produkt- und Industriedesign als Teil des Kerntätigkeitsspektrums im Bereich der seriellen Produktion von Konsum- und sonstigen Innovationsgütern in der ökonomisch orientierten Relationsstruktur Rm)-- in Beziehung setzt. Ferner ist zu fragen, inwiefern diese Metapher in der Lage ist, die Breite der gesellschaftliche Professionalisierung im Bereich der Kunst -- angefangen bei den Veränderungen des Status von Künstlern und der Künstlerlaufbahn, der Schaffung und des Aufwuchses von (Bildungs- und Repräsentations)Institutionen der Kunst und der Liberalisierung der Kunst entlang der Schaffung eines Kunstmarktes bis hin zur Etablierung und Institutionalisierung von mit diesen Prozessen verbundenen Tätigkeitsfeldern (Galeristen, Sammler, Kuratoren etc.) und Vermittlungsinstanzen (Galerien, private Sammlungen, Kunsthochschulen etc.) -- abzubilden; ein vielgestaltiger und facettenreicher Wandel also, den die Theorie der Relation als Ausdifferenzierung von Sequenzen in Relationsstrukturen, namentlich der sozio-kulturell-künstlerischen Relationsstruktur Ri, theoretisch fasst und der aufs Engste erstens mit der Zirkulation von Akteuren zusammenhängt und zweitens mit der Bildung und Verbreitung ebenso zahlreicher wie diverser Vermittlungsinstanzen und Subvermittlungsinstanzen einhergeht.

Diese Perspektivierung der Kunst unter Rückgriff auf die Metapher des Selektionsdrucks zeigt, dass der Kunstbetrieb einem stetigen Wandel unterworfen ist, der nicht nur durch äußere Einflussnahme provoziert ist -- bspw. entlang der ökonomischen, sozialen und politischen Funktionalisierung" von Kunst [https://www.kunstgeschichte-ejournal.net/78/1/Tabor_Kunstindustrie.pdf] --, sondern mindestens ebenso sehr von Akteuren und Vermittlungsinstanzen der Kunst selbst initiiert und geleistet wird. Dies ist bspw. dann der Fall, wenn (informations)technologische, politische und wirtschaftliche Impulse auf Widerhall stoßen und Eingang in die künstlerisch-kreative Arbeit finden -- beispielhaft sei hier auf das Betätigungsfeld der digitalen Kunst oder auf die sogenannte "Industrialisierung" des Kunstbetriebs verwiesen, die zusehends von zwei Faktoren geprägt wird: "von globalen Netzwerken und von exponentiellen Zuwachsraten in allen involvierten Tätigkeitsbereichen", angefangen bei "der Kunstproduktion, den Kunstmärkten bis hin zu den verschiedenen Formen der Präsentation" und "der Kritik" (ebd.). Entsprechend soll abschließend darauf hingewiesen werden, dass die Übernahme bestimmter Tätigkeiten ebenso gut durch Akteure in Relationsstrukturen erfolgt, die mittelbar an der Ausdifferenzierung von Tätigkeitsfeldern bzw. Sequenzen in Relationsstrukturen mitwirken, indem sie solche Tätigkeiten entlang des entsprechenden Schmetterlingspfades ihrer Sequenz entwickeln; dass die Übernahme von Tätigkeiten aber ebenso gut über die soziale Mobilität von Akteuren zwischen Relationsstrukturen erfolgen kann, was in die Thematik von Kapitel 4 überleitet.

-->

#### Kapitel 4: Die Attraktivität der Repräsentation. Stars als Anführer.

<!--

Schmetterlingspfade von Relationsstrukturen unterstützen sowohl die Verbreitung, als auch die Schrumpfung von Akteurkategorien, Hierarchien und Erwartungsstrukturen, was einerseits zur Stärkung und Verbreitung von einer Relationsstruktur führen kann, wenn es andererseits auch zur Schwächung/Störung von Relationsstrukturen durch die Verfestigung und Verbreitung von anderen Akteurkategorien, Hierarchieprinzipien und Erwartungsstrukturen innerhalb sowie zwischen Relationsstrukturen.

Hier haben wir ein Beispiel zu aufsteigenden Zirkulationen innerhalb und zwischen Zirkulationsstrukturen.

-->


In diesem Kapitel werden die Folgen der in Kapitel 3 für die vier Relationsstrukturen vorgestellten Zirkulation behandelt. In den vier Relationsstrukturen entwickeln sich Zirkulationen auf der Grundlage von der jeweiligen Kernsequenzen dieser Relationsstrukturen sowohl innerhalb jeder Relationsstruktur und Sequenz dieser Relationsstrukturen als auch zwischen Relationsstrukturen. Diese Zirkulationswege bestimmen die Entwicklung der Erwartungen von Akteuren in Verbindung mit Kollektiven bzw. Instanzen der (positiven sowie negativen) Sanktionierung von solchen Erwartungsstrukturen. Sie tragen entsprechend zur Hierarchisierung der Akteuren in Akteurkategorien und zur Mobilität dieser Akteure unter Rekurs erstens auf diese Akteurkategorien, zweitens auf den für diese Akteurkategorien jeweils charakteristischen Widerstand _für_ die Relation/Position und _gegen_ die Position/Relation und drittens auf die Reziprozität als Voraussetzung jedweder Zirkulation von Akteuren in und zwischen Relationsstrukturen. Entlang dieser thematischen wie inhaltlichen Schwerpunkte gilt es übergeordnet zu zeigen, dass das Primat der Zirkulation nicht zwangsläufig eine theoriegeleitete wie symmetrische Unterbewertung der Position von Akteuren zur Folge haben muss, sondern das Wechselspiel zwischen Zirkulation und Position in systematischer Weise Berücksichtigung findet und einen nicht zu unterschätzenden Beitrag zur Neuperspektivierung von sozialer Mobilität leistet.

Um die Thematik der Akteurkategorien und der Hierarchien zwischen den Akteurkategorien auf der Grundlage von Zirkulationswege und Zirkulationsmöglichkeiten zu veranschaulichen, wenden wir uns vor allem dem Politischen bzw. der sozio-politisch orientierten Relationsstruktur vom Standpunkt der Puristen von Relationsstrukturen und von Sequenzen zu. Dabei berücksichtigen wir insbesondere Puristen der Sequenzen bzw. Akteure, für die die Sequenz, in der sie sich befinden, zum Gravitationszentrum ihrer Relationsstruktur werden sollte. Solche Akteure unternehmen deshalb alles, um die Zirkulation in ihrer Relationsstruktur vom Standpunkt ihrer Sequenz zu gestalten, was ihre eigene Zirkulation in die Richtung von einer anderen Relationsstruktur entwickelt, in der ihre Sequenz die Kernsequenz dieser Relationstruktur darstellt. Dieses Streben nach einer anderen Struktur der Zirkulation, wovon diese Puristen der Sequenz die Hauptvertreter sind, wird anhand von Fallbeispielen bzw. von Akteure wie Arnold Schwarzenegger, Wolodymyr Selenskyj, dem Künstler Albrecht Dürrer und anderen in den Blick genommen. Diese Akteure eint, dass sie alle einen Zirkulationsweg von der sozio-kulturell (konkret der künstlerisch und der wissenschaftlich) orientierten Relationsstruktur in die politisch orientierte Relationsstruktur zurückgelegt haben. Über die Auswahl dieser Akteure soll gleichsam demonstriert werden, dass sich die Theorie der Relation für die Perspektivierung sowohl gegenwärtiger als auch historischer Zirkulationswege im Sinne sozialer Mobilität eignet.

<!--
Hier könnte man auch die Beschreibung für Velbrück beenden -- ok


Für die _Gegenwartsperspektive_ von Akteurkategorien, deren Zirkulationsmöglichkeiten und deren sozialer Mobilität in und zwischen Relationsstrukturen, werden der ehemalige Gouverneur Kaliforniens _Arnold Schwarzenegger_, der ehemalige US-amerikanische Präsident _Ronald Reagan_ und der amtierende Präsident der Ukraine _Wolodymyr Selenskyj_ im Zentrum stehen. Alle drei Akteure eint, dass sie vor ihrem Wirken in der Politik in der Unterhaltungs- und Filmindustrie, d. h. in der kulturell-künstlerisch orientierten Relationsstruktur (Ri), tätig waren, dort relativ schnell aufgestiegen und in die Politik zirkuliert sind (aufsteigende Mobilität). Arnold Schwarzenegger begann seine Karriere als Bodybuilder mit kleinen Fernsehrollen, spielte dann zahlreiche Hauptrollen in Filmproduktionen und betätigt sich vor seinem Eintritt in die politisch orientierte Relationsstruktur auch als Produzent sowie Regisseur. Mit Beginn der 2000er Jahre wendet sich Schwarzenegger vornehmlich der Politik zu und wird von 2003 bis 2011 Gouverneur des US-amerikanischen Bundesstaates Kalifornien bis er schließlich ins Film-Business zurückkehrt. Ronald Reagon ist vor seinen zwei Amtszeiten als US-amerikanischer Präsident und Gouverneur von Kalifornien ebenfalls in der Radio- und Filmbranche tätig, spielt aber im Unterschied zu Schwarzenegger eher Nebenrollen und gibt den Fernsehmoderator. Über seine Präsidentschaft der Schauspielergewerkschaft _Screen Actors Guild_ (Sequenz Repräsentation in Ri) und seine Konzernrepräsentation bei General Electric (Sequenz Repräsentation in Rm) gelingt ihm der Sprung in die Politik bzw. die Zirkulation in die Sequenz Repräsentation der politisch orientierten Relationsstruktur Rr. Einen ähnlichen Zirkulationsweg zwischen Relationsstrukturen legte auch Wolodymyr Seleneskyj zurück, allerdings mit dem Unterschied, dass er über die Fernsehserie und den Film _Diener des Volkes_ so große Attraktivität erlangte, dass er aus dem Stand in das Präsidentschaftsamt der Ukraine gewählt wurde. Für eine historische Perspektivierung wird in Korrespondenz dazu auf die Künstlerpersönlichkeit _Albrecht Dürer_ rekurriert, der sich als gelernter Goldschmied und Künstler nicht nur der kommerziellen Vermarktung seiner Werke zugewendet hat, sondern auch aufgrund seiner gehobenen Position den Sprung in die Politik schaffte, indem er vom Inneren Rat der Stadt Nürnberg in das Ehrenamt eines Genannten berufen wurde und aufgrund dessen in den Größeren Rat der Stadt Nürnberg einzog [@Wensky2002, 21]. Neben diesem prominenten Beispiel soll die Besetzungspraxis des Bürgermeisteramtes der Stadt Köln in der Zeit von 1396 bis 1599 beleuchtet werden, da es in dieser Zeitspanne zu einer sowohl informellen als auch formellen Professionalisierung der politischen Führungsschichten der Stadt Köln -- vom Geburtsstand zum professionell, akademisch ausgebildeten Juristenstand -- kam und der neue Juristenstand eine bedeutende Zirkulation der Akteure verlangt, die nach und nach mit Erwartungsstrukturen und Rechtfertigungsordnungen verbunden wurde, was zur Stabilisierung dieser Zirkulationswege maßgeblich beitrug.

Anhand dieser Beispiele lässt sich darüber hinaus -- neben dem Zusammenhang zwischen dem Widerstand der Akteure, der mit diesem Widerstandsprofil korrespndierenden Position der Akteure in der Hierarchie von Akteurkategorien und den damit verbundenen Zirkulationsmöglichkeiten in und zwischen Relationsstrukturen -- plausibilisieren, welchen Blick die Theorie der Relation auf den Zusammenhang zwischen Zirkulation und sozialer Mobilität entfaltet und wodurch sich diese Perspektive von anderen theoretischen Ansätzen und Auffassungen unterscheidet. Dabei soll insbesondere hervorgehoben werden, dass es zu nahezu allen Zeiten immer wieder zu Zirkulationen von Akteuren zwischen Relationsstrukturen -- im Sinne von Klassentransfer als transversaler Mobilität zwischen sozialen Klassen -- kommt, die oftmals, wenn auch nicht zwangsläufig, mit Statusveränderungen der Akteure und der Erprobbung von (neuen) Zirkulationswegen einhergehen; eine Thematik, die in Kapitel 5 erneut aufgegriffen werden soll und sich explizit gegen die Annahme richtet, soziale Mobilität sei ein ausschließlich _modernes_ Phänomen [@Bonß2001; 181], das erst mit der ersten Moderne einsetze (ebd., 183). Dieser Punkt ist von besonderer Bedeutung, weil Zirkulationswege in der Regel von "Pionieren" gebahnt werden, bevor sie tatsächlich existieren, anderen Akteuren offenstehen und von diesen beansprucht werden und schließlich zum Bestandteil von formalen Verfahren der entsprechenden Instanzen generieren.

-->

#### Kapitel 5: Der Verlust der Gnade Gottes. Abstufung, Abwanderung und neue Macht der Päpste

<!--

Mobilität in und zwischen Relationsstrukturen sowie die Stratifikation von Relationsstrukturen | Hier fehlt uns immer noch ein gutes Beispiel -- nett wäre vielleicht ein Beispiel zur Religion/Gläubiger/Bischöfe (nach dem Motto Glaube als Berufung als möglicher Titelvorschlag für dieses Kapitel)

Kap. 5 unterscheidet sich vom Kap. 3 insofern, als es ein Beispiel zu absteigen Zirkulationen innerhalb und zwischen Relationsstrukturen durch eine Schwächung von Akteurkategorien liefert.

Idee hier mit Päpsten -- absteigende Mobilität von Rr zu Ri weil Widerstand _gegen_ den Staat einerseits und Widerstand _für_ die eigene Gemeinschaft als morale Macht mit Übersetzung dieser Mobilität durch die steigende Ernennung von Bischöfe, die Vernetzung von katholischen Kirchen und von Katholikern (Stabilisierung durch Materialisierung in Ri), die entsprechende Attraktivität durch die Unterstützung vom Progressismus bei sozialen Fragen (Zölibat der Pfarrer, Gender/Diversitätsfragen, Migration), die Erneuerung von theologischen Ansätzen mit Ansätzen aus anderen religiösen Traditionen (Vernetzung der Ansätze in der katholischen Kirche).


-->

Zirkulationswege und Zirkulationsmöglichkeiten werden nicht nur im Sinne ihrer Verbreitung entwickelt, sondern sie können auch schrumpfen, was zur Schrumpfung von Erwartungsstrukturen und zur Deklassierung von Akteuren in Relationsstrukturen führen kann. Dieser Fall, bei dem die Einschreibung von Akteuren und Instanzen in Relationsstrukturen immer schwieriger wird bzw. geschwächt und gestört wird, kann ebenfalls dazu führen, dass Akteure ihre Relationsstruktur für eine andere Relationsstruktur verlassen, in der sie weitere Zirkulationsmöglichkeiten entwickeln können und weitere Zirkulationswege bahnen können. In diesem Kapitel 5 stellen wir ein Beispiel von einer solchen absteigenden Zirkulation im Rahmen der katholischen Religion vor.

Dieses Kapitel zeigt im Kontrast zum Kapitel 4, dass absteigende Zirkulationen nur ein Moment von einem Zirkulationsweg darstellen, der nicht das Schicksal von einem solchen Zirkulationsweg für seine Akteure zwangsläufig bestimmt. Absteigende Zirkulationen, wie wir es insbesondere im Rahmen des Machtverlustes der katholischen Päpste zeigen werden, sind auch manchmal die Bedingung für die Repositionierung von Akteuren in anderen Relationsstrukturen und für die Entstehung von weiteren aufsteigende Zirkulationen entweder innerhalb dieser Relationsstruktur oder zwischen dieser und anderen Relationsstrukturen. Das eine solche neue Entwicklung von Zirkulationswegen von Akteuren Zeit braucht, zeigt das Beispiel der katholischen Relation ebenfalls. Sich neue Zirkulationswege und Zirkulationsmöglichkeiten zu erschaffen, braucht den Wiederaufbau der Arbeit an relationalen Ereignissen und an der Mobilisation von Akteuren, die Etablierung und Institutionalisierung von Kollektiven, die kaum innerhalb des Lebens von Einzelmenschen machbar ist. Dieser Generationsansatz, den die Theorie der Relation bei der Erklärung von langen und komplexen Zirkulationswegen unterstützt, verdeutlicht die Bedeutung der sozialen Geschichte in der _longue durée_ von Lebenswegen, um die Dimensionierung von Relationsstrukturen bzw. ihre Verbreitung und ihre Schrumpfung besser erklären zu können.

<!--

In Kapitel 5 wird die Einführung in das Mobilitätskonzept der Theorie der Relation fortgesetzt und theorieimmanent entlang unterschiedlicher Arten von Mobilität bzw. spezifischer Zirkulationsmöglichkeiten sowohl innerhalb von Relationsstrukturen, d. h. in und zwischen Sequenzen einer Relationsstruktur, als auch zwischen Relationsstrukturen systematisiert. Für diese Systematisierung ist es unerlässlich, stets die soziale Strukturierung der Akteure entlang der vier Akteurkategorien, die nicht nur für jede Sequenz von einer Relationsstruktur tragend ist, sondern auch das auf einen Akteur einwirkende Wechselspiel zwischen Zirkulation und Position bestimmt, mitzudenken, weil einerseits die Akteurkategorien entsprechend des auf sie einwirkenden Wechselspiels zwischen Zirkulation und Position mit bestimmten Zirkulationsmöglichkeiten ausgestattet sind und die Mobilität von Akteuren zwischen den Sequenzen einer Relationsstruktur oder zwischen Relationsstrukturen andererseits die Stratifikation der Akteurkategorien und die Hierarchie unter den Akteurkategorien sowohl mittelbar als auch unmittelbar affiziert. In diesem Zusammenhang wird auch das Widerstandskonzept der Theorie der Relation erneut aufgegriffen und weiter ausbuchstabiert, da das Wechselspiel zwischen Zirkulation und Position auf jede Akteurkategorie und weiterführend auf jede der drei Schichten von Akteuren einer Akteurkategorie in anderer Weise einwirkt und mit einem entsprechenden Widerstandsprinzip _für_ die Zirkulation bzw. die Position und _gegen_ die Position bzw. die Zirkulation korrespondiert.

**Beispiel(e): Zur Beförderungspraxis interner Arbeitsmärkte bzw. innerhalb von Relationsstrukturen und (Teil)Sequenzen**

Beförderung (als Zirkulation von Akteuren zwischen Sequenzen von Relationsstrukturen) wird in der Literatur oft bzw. immer noch als statitisch aufsteigende Mobilität verstanden bzw. herrscht zum Teil immer noch die Sichtweise vor, wonach interne Beförderung qua Leistung erfolgt [@Williamson1975, 78; vgl. auch @Williamson1973] und/oder vom Ausmaß sozialer Beziehungen bzw. vom "konkreten Muster sozialer Beziehungen" und der Einbettung in diese Muster abhänge [@Granovetter2000, 188], sowie von weiteren Faktoren determiniert wird [vgl. @Granovetter1986; @Granovetter1988]. Ähnlich wie Simmel, der Gesellschaft als Gewebe unterschiedlicher Vergesellschaftungsformen begreift, das wiederum aus stärker dynamischen und stärker stabilisierenden Elementen besteht [vgl. @Simmel1957, 1], versteht auch die Theorie der Relation die Mobilität bzw. die Beförderung von Akteuren als morphologisch wie strukturell determiniert, wobei die Konfiguration dieses Wechselspiels zwischen morphologischen und strukturellen Determinanten die Art der Zirkulation bestimmt.

<u>Perspektivierung sozialer Mobilität bspw. entlang verschiedener Theorieschulen (bspw. Chicagoer School etc.), vorherrschender Auffassungen von Mobilität und deren Wandel im Zeitverlauf sowie bzw. oder ausschließlich die Konzeptualisierung von Mobilität in der relationalen Soziologie:</u>
In den 70er Jahren wurde vielerorts angenommen, alle Beschäftigten hätten "identical transition probabilities", was zu der empirischen Unterscheidung von ständigen Mitarbeitern ("Stayers"), deren Wahrscheinlichkeit auf einen Arbeitsplatzwechsel gleich Null ist, und wechselwilligen Mitarbeitern ("Movers"), deren Wahrscheinlichkeit auf Arbeitsplatzwechsel ungleich Null ist, geführt hat [vgl. @Blumen1955; vgl. zur Kritik daran @Granovetter1986, 7]. Diese Unterscheidung sorgte dafür, dass sich das Forschungsinteresse auf die Heterogenität der mobilitätsgefährdeten Populationen richtete. Mobilität wurde also als Risiko eingestuft und statistisch operationalisiert [vgl. @Heckman 1978]. Die aus dieser Unterscheidung gewonnene zentrale Beobachtung lautete, dass Personen, die bereits ein Ereignis (wie Mobilität oder Arbeitslosigkeit) erlebt haben, mit größerer Wahrscheinlichkeit erneut davon betroffen sind als andere. Zur Erklärung (der Heterogenität bei der Arbeitsbereitschaft und einer gewissen Zustandsabhängigkeit) wurde zumeist auf individuelle Charakteristika und Unterschiede rekurriert, die für die Variation von Status-Gewinnen ausschlaggebend seien. Granovetter und andere konterkarieren diese vorherrschende Perspektive -- die sicherlich auch unter Berücksichtigung der Nachkriegssituation (_Mobilität als Risiko_) vollständig zu verstehen ist --, indem sie wiederum andere, zwischenmenschliche und netzwerktheoretische Faktoren für die Mobilität von Akteuren heranziehen und diese empirisch untersuchen [vgl. @Granovetter1986, @Granovetter1988]. Dass auch diese Perspektivierung teilweise zu kurz greift, soll unter Rekurs auf das Mobilitätskonzept der Theorie der Relation, d. h. die unterschiedlichen Arten sozialer Mobilität von Akteuren, veranschaulicht und plausibilisiert werden.

<u>Perspektive der Theorie der Relation:</u>
Beförderung eines Akteurs als Resultat erstens von gelungener doppelter Einschreibung auf Basis des Widerstands _für_ die Zirkulation/Relation und _gegen_ die Struktur/Position und zweitens des Erreichens entsprechender Vermittlungsinstanzen (VI des Schwerkraftzentrums oder VI destabilisierter Zirkulation) je nach Relationsstruktur, woraufhin es erst zur doppelten Einschreibung und in der Folge zu sozialer Mobilität bzw. zur Zirkulation von Akteuren kommt [vgl. @PapilloudSchultze2022]. Dabei bestimmen sowohl die entsprechenden Arten von Vermittlungsinstanzen (vgl. ebd., 253-297), die der Akteur erreicht und mit denen anschließend die Reziprozität durchgeführt wird, als auch das Wechselspiel zwischen Zirkulation und Relation, welches einen jeden Akteur in unterschiedlichem Maße determiniert, ob es um aufsteigende oder absteigende oder aber um transversale soziale Mobilität zwischen Sequenzen in oder zwischen Relationsstrukturen handelt, d. h. das Ausmaß der Zirkulationsmöglichkeiten (entsprechend der Arten von Zirkulationsmöglichkeiten) entweder eingeschränkt wird oder eine Erweiterung erfährt.

-->

#### Kapitel 6: Vermittlungsinstanzen sind nicht gleich Vermittlungsinstanzen. Noten, Emojis und Farben im Ausbildungssystem

<!--
Vermittlungsinstanzen bzw. die vier Arten von Vermittlungsinstanzen | Hier vielleicht am besten mit einem Beispiel aus der Bildungssoziologie -- etwa die Noten (möglicher Titelvorschlag: Vermitteln ist nicht gleich vermitteln)

Aus den Kap. 3, 4 und 5 zeigen wir, dass Transfer von Akteuren und Durchsetzung von alternativen Zirkulationswegen innerhalb und zwischen Relationsstrukturen keine Ausnahme, sondern die Regel sind. Wir zeigen aber gleichzeitig, dass solche Transfer und alternative Zirkulationswege zu Wechsel innerhalb von Relationsstrukturen oder zwischen Relationsstrukturen führen, wofür die Vermittlungsinstanzen verantworlich sind -- darunter spielen die umverteilende Vermittlungsinstanzen eine sehr wichtige Rolle.

Eine solche entscheidende Rolle von umverteilenden Vermittlungsinstanzen zeigt das Beispiel der Noten im Ausbildungssystem

-->

Zirkulationswege und Zirkulationsmöglichkeiten sind zahlreich, und sie tragen wesentlich zur Expansion und Schrumpfung von Relationsstrukturen, was wiederum Folgen für die Instanzen der Vermittlung von diesen Zirkulationswegen und Zirkulationsmöglichkeiten hat. In diesem Kapitel beschäftigen wir uns mit diesen Kollektivakteuren, die Vermittlungsinstanzen von Relationsstrukturen sind, und die im Kontrast zu anderen Akteuren und Aktanten innerhalb oder zwischen Relationsstrukturen nicht zirkulieren, sondern eine Position beziehen und halten, um Zirkulationswege und Zirkulationsmöglichkeiten für andere Akteure zu gewährleisten. In diesem Sinne sind Vermittlungsinstanzen einerseits Stütze von Relationsstrukturen, die ohne Vermittlungsinstanzen nicht existieren würden. Aber andererseits gibt es unterschiedliche Arten von Vermittlungsinstanzen je nach Akteurkategorien, Sequenzen und Relationsstrukturen, davon manche diesen Akteurkategorien, Sequenzen und Relationsstrukturen spezifisch sind, davon anderen in unterschiedlicher Form überall vorhanden sind. Gemein haben diese Vermittlungsinstanzen, dass sie ihre Vermittlungsstruktur und dabei asymmetrische Verhältnisse zu anderen Vermittlungsinstanzen mit der Absicht entwickeln, die Instanz zu werden, die die Einschreibung von Akteuren in Relationsstrukturen für alle Akteure in allen Sequenzen von Relationsstrukturen und allen Relationsstrukturen fördern. Dies führt unvermeidlich zu Einflussstrategie zwischen Vermittlungsinstanzen innerhalb von Sequenzen, Relationsstrukturen und zwischen Relationsstrukturen. Um diesen Punkt der Einflussstrategien von Vermittlungsinstanzen zu adressieren, beschäftigen wir uns in diesem Kapitel mit Evaluationsmaßnahmen im Ausbildungssystem.

Das Ausbildungssystem bietet einerseits eine Vielfalt an Vermittlungsinstanzen in den vier Relationsstrukturen. Andererseits zegen Vermittlungsinstanzen des Ausbildungssystems eine innerliche Diversität nicht nur je nach Relationsstrukturen, sondern auch innerhalb von jeder Relationsstruktur. Deshalb haben wir im Ausbildungssystem mit Instanzen zu tun, die hoch differenziert sind, und entsprechend hoch differenzierte Verfahren entwickeln, um ihre Einschreibung mit Akteuren in ihrer Relationsstruktur bzw. in eine Sequenz ihrer Relationsstruktur zu fördern. Ein Mittel dafür ist die Evaluation von Einschreibungen durch symbolische und formale Medien, die das Ausbildungssystem in der Form von Noten, Emojis und Farben entwickelt hat und manchmal immer noch entwickelt. In diesem Kapitel geht es darum, zu zeigen, wie die Entwicklung von solchen symbolischen und formalen Medien die Entwicklung der Vermittlungsstruktur von Instanzen des Ausbildungssystems unterstützt, die deshalb in Konkurrenz zur Entwicklung der Vermittlungsstruktur von anderen Instanzen des Ausbildungssystems tretet, was zu Kontroversen über die Evaluationspolitik und Selektivität von Vermittlungsinstanzen des Ausbildungssystems führt, die wir in diesem Kapitel darstellen werden.

<!--

Im Rahmen dieses Kapitels werden weiterhin die Folgen der Zirkulation für die in Kapitel 3 vorgestellten vier Relationsstrukturen Ri, Rr, Rm und Ra behandelt, allerdings unter besonderer  Berücksichtigung der Bedeutung von Kollektivakteuren für die Bewahrung, Verbreitung und Stabilität der Zirkulation in den Relationsstrukturen. Zu diesem Zweck wird in angemessener Kürze zunächst auf die vier Arten von Kollektivakteuren als Vermittlungsinstanzen, deren (strukturelle) Besonderheiten, deren Arbeit an der Vermittlung und deren Bedeutung hinsichtlich der Zirkulation von Akteuren einzugehen sein. Anschließend wird es darum gehen, die Prinzipien der Zirkulation für die Relationsstrukturen Ri, Rr, Rm und Ra entlang derjenigen Art von Vermittlungsinstanz zu präzisieren, die einerseits mit ihrer Arbeit an den formalen Strukturen und andererseits mit ihrer Sozialisations-, Förder- und Sanktionsarbeit maßgeblich zur Stabilität, Bewahrung und ggf. der Verbreitung der entsprechenden Relationsstruktur beiträgt. Die Art von Instanz, der diese Aufgaben in den jeweiligen Relationsstrukturen obliegen, wird als Schwerkraftzentrum von Relationsstrukturen fundiert.

**Beispiel(e): Vermittlungsinstanzen sind nicht gleich Vermittlungsinstanzen**


**Zur Bedeutung/Relevanz von Wirtschaftssektoren bzw. von Teilsequenzen in Rm**

- Arbeitsmarkt und Unternehmens- bzw. Betriebsgröße [vgl. @Granovetter 1984 und neuere Studien zu Beschäftigungszahlen und Unternehmesgröße sowie zum Anteil der Beschäftigten, die in kleinen und mittleren Unternehmen tätig sind, bspw. europaweit]
- in diesem Zusammenhang soll miterörtert werden, weshalb relationsstrukturspezifische Vermittlungsinstanzen in Rm, d. h. in der wirtschaftlich orientierten Relationsstruktur, ganz anders arbeiten, viel weniger Einfluss ausüben und leichter die Kontrolle über (Teil)Sequenzen verlieren als vergleichbare VI bspw. in Ri oder Rr

-->

#### Kapitel 7: Kunst und Tücken der Umverteilung. Das Doppelleben der Soziologinnen <!-- Frauen: Diesseits von Jounalismus und Literatur und jenseits der Wissenschaft -->

Auf der Grundlage der in Kapitel 6 eingeführten Arten von Vermittlungsinstanzen, ihren je spezifischen Besonderheiten und ihrer fluktuierenden Bedeutung für die vier Relationsstrukturen wird in Kapitel 7 eine weitere Ausdifferenzierung von Vermittlungsinstanzen in Relationsstrukturen vorgenommen. Zentral hierfür ist, dass die Differenzierung zwischen Vermittlungsinstanzen in vier Relationsstrukturen in der Theorie der Relation nicht allein auf dem Vergleich zwischen diesen Instanzen beruht, sondern darüber hinaus erstens auf Basis der Zirkulation der Akteure innerhalb einer Relationsstruktur und zwischen Relationsstrukturen sowie zweitens hinsichtlich der Anpassung der Zirkulation in Relationsstrukturen erfolgt. Vor diesem Hintergrund wird einerseits ersichtlich, dass die Stärkung oder Schwächung/Störung einer bestimmten Art von Vermittlungsinstanz mit der Stärkung oder Schwächung/Störung der Zirkulation in einer Relationsstruktur zusammenhängt und inwiefern demzufolge Vermittlungsinstanzen im Vergleich zu anderen Vermittlungsinstanzen derseleben Relationsstruktur durch etwaige Anpassungen der Zirkulation gestärkt oder geschwächt/gestört werden. Dieser Zusammenhang ist deshalb von besonderer Relevanz, weil über ihn erklärlich wird, dass die Destabilisierung der allgemeinen Zirkulation in den vier Relationsstrukturen mit der Schwächung der Schwerkraftzentren von diesen Relationsstrukturen zugunsten derjenigen Art von Vermittlungsinstanz einhergeht, die auf dem Weg der sukzessiv erfolgenden Anpassung der Zirkulation in den vier Relationsstrukturen jeweils gestärkt wird. Eine solch dynamische Perspektivierung von Vermittlungsinstanzen plausbilisiert ferner, dass auch die Zirkulation von Akteuren in und zwischen Relationsstrukturen unter bestimmten Bedingungen Veränderungen unterworfen ist und diese Veränderungen Einfluss auf die Reziprozität innerhalb einer Relationsstruktur ausüben. Sie wirken etwa reziprozitätserschwerend bzw. reziprozitätserleichternd, oder sie unterbrechen die Reziprozität. Dies vergegenwärtigt sich wiederum sowohl <!-- -- entsprechend des legitim gültigen Hierarchieprinzips (Eigenständigkeit und Verbindlichkeit), das mit einem bestimmten Zustand der Zirkulation in den vier Relationsstrukturen einhergeht -- --> in der Zu- und Abnahme von Mobilitäts- bzw. Zirkulationsmöglichkeiten in den vier Akteurkategorien einer Relationsstruktur als auch im Zu- oder Abstrom von Akteuren aus Relationsstrukturen, was sich wiederum im Wachstum oder in der Schrumpfung dieser Kategorien von Akteuren äußert.

Diese komplexen Zusammenhänge werden zum einen vornehmlich unter Bezugnahme auf den Bereich des Journalismus, d. h. auf die Medien orientierte Relationsstruktur, und zum anderen unter Rekurs auf fünf Soziologinnen -- Germaine de Staël-Holstein, Harriet Martineau, Jenny d'Héricourt, Beatrice Webb und Jane Addams -- plausbibilisiert. Diese Soziologinnen zeichnet aus, dass sie zwar alle im 19. und zu Beginn des 20. Jahrhunderts Soziologie betrieben haben und in engem Austausch zu ihren männlichen Kollegen standen, ihnen aber prinzipiell der legitime Zugang zur Wissenschaft verwehrt war. <!-- weshalb sie auch heute noch weitgehend aus dem Kanon der Klassiker der Soziologie ausgeschlossen sind. Aus diesem Mangel heraus schlugen diese ausgewählten --> Diese Frauen schlugen einen <!-- zu dieser Zeit durchaus häufigen --> Zirkulationsweg ein, der mit zahlreichen Wechseln zwischen bestimmten, immer gleichen Sequenzen entweder innerhalb einer Relationsstruktur oder zwischen zwei Relationsstrukturen -- dem Bereich der Wissenschaft und den Bereich des Journalismus -- verbunden war und ihnen somit zahlreiche Umstellungen zwischen Position und Relation abverlangte. <!-- Anders gesprochen, blieb diesen von der Wissenschaft ausgeschlossenen Frauen nichts anderes übrig, als sich neben ihrem ausgeprägten Engagement im Bereich der Wissenschaft auch im Bereich des Journalismus oder der Literatur zu betätigen, um überhaupt an der Sozialität teilhaben zu können, auch wenn das gleichzeitig bedeutete, eine Art Relationsstruktur-Hopping betreiben zu müssen. --> Solche Zirkulationswege lassen sich als Pseudozirkulationen verstehen, weil dabei lediglich stetige <!-- ellipsenförmige --> Hin- und Zurück-Bewegungen zwischen zwei Sequenzen in einer Relationsstruktur oder zwischen zwei Relationsstrukturen vollzogen werden, die stark von regulären Zirkulationsmöglichkeiten abweichen. Sie demonstrieren, was geschieht, wenn die Zirkulation einer Relationsstruktur und mithin die Relationsstruktur selbst geschwächt ist, die Anpassung der Zirkulation über die Umverteilung von Akteuren notwendig wird, wie viel Zeit eine solche Anpassung in Anspruch nehmen kann und inwiefern davon andere Relationsstrukturen und deren Vermittlungsinstanzen profitieren.

<!--

Dass die Schwäche einer bestimmten Art von Vermittlungsinstanz zur Stärke einer anderen Art von Vermittlungsinstanz generiert und aufgrund dessen die Zirkulation einer Relationsstruktur zugunsten einer anderen Zirkulation in einer anderen Relationsstruktur gefördert wird, soll im Rahmen dieses Kapitels anhand der Zirkulation besonderer weiblicher Persönlichkeiten des 19. und beginnenden 20. Jahrhunderts plausibilisiert werden. Diese Frauen -- Germaine de Staël-Holstein, Harriet Martineau, Jenny d'Héricourt, Beatrice Webb und Jane Addams -- haben gemeinsam, dass sie von akademischen Bildungseinrichtungen ausgeschlossen waren -- sie also in der sozio-kulturell bzw. wissenschaftlich orientierten Relationsstruktur (Ri) keine Vermittlungsinstanzen erreichten, infolge dessen von der Reziprozität ausgeschlossen waren und zeitlebens über keinerlei wissenschaftliche Legitimität als Soziologinnen verfügten. Aufgrund dieses Mangels an und der Schwäche von Vermittlungsinstanzen in der sozio-kulturell bzw. wissenschaftlich orientierten Relationsstruktur, der insb. auch auf eine relativ ausgeprägte Schwäche von umverteilenden Vermittlungsinstanzen in dieser Relationsstruktur hindeutet, schlugen all diese Frauen einen Zirkulationsweg ein, der ihnen zahlreiche Umstellungen zwischen Position und Relation abverlangt und entsprechend mit zahlreichen Wechseln entweder zwischen bestimmten Sequenzen innerhalb einer Relationsstruktur oder zwischen bestimmten, immer gleichen Sequenzen zwischen zwei Relationsstrukturen verbunden war. Konkret gesprochen, lässt sich bei diesen Frauen eine Zirkulation beobachten, bei der die Frauen permanent eine Art steige Hin- und Zurück-Bewegung zwischen erstens der sozio-kulturell bzw. wissenschaftlich orientierten Relationsstruktur (Ri) und zweitens der Medien orientierten Relationsstruktur (Ra) zurücklegten. Eine solche Zirkulation, die lediglich und hauptsächlich in einer Hin- und Zurück-Bewegung zwischen zwei Sequenzen einer Relationsstruktur bzw. zwischen zwei Relationsstrukturen besteht, kann als eine Art Pseudo-Zirkulation verstanden werden, die darauf beruht, dass bestimmte soziale Gruppen von der Reziprozität in einer Relationsstruktur unberücksichtigt bleiben und aufgrund dessen nicht nur von der allgemeinen Zirkulation in einer Relationsstruktur, sondern auch von damit verbundenen Zirkulationsmöglichkeiten ausgeschlossen sind und sich



Wenn umverteildende Vermittlungsinstanzen schwach sind, was voraussetzt, dass Vermittlungsinstanzen insgesamt in Relationsstrukturen schwach sind, dann führt es zu vielfachen Umstellungen von Position und Relation, und von entsprechenden mehreren Wechseln zwischen bestimmten Sequenzen von einer Relationsstrukturen bzw. zwischen bestimmten Relationsstrukturen in einer Art von Hin und Zurück Bewegung.

Beispiel von Doppelleben -- nicht nur Schriftsteller und Journalisten, sondern auch Wissenschaftler und Startupers
-->

#### Kapitel 8: Glanz und Misere des Plagiats. Zur Attraktivierung der Medien

In der Theorie der Relation kommt dem _Medien_-Begriff eine tragende und zugleich vielschichtige Rolle zu. <!-- Tragend und vielschichtig deshalb, weil --> Dies erklärt sich damit, dass die Einbeziehung von (symbolischen wie formalen) Medien durch Akteure in deren soziale Arbeit einerseits und die Eingliederung von (symbolischen) Medien durch die Vermittlungsinstanzen in deren Vermittlungs- und Formalisierungsarbeit andererseits <!-- ist dazu imstande, als --> aus diesen Medien die Mediationen der doppelten Einschreibung macht. <!-- zu fungieren -->. <!-- Dadurch gewährleisten --> Ferner unterstützt der Einsatz von Medien <!-- bei relationsstrukturadäquaten Ge- und Verbrauch nicht nur die stabile und stetige --> nicht nur die Zirkulation von Akteuren in und zwischen Sequenzen von Relationsstrukturen, nicht zuletzt weil die Unterschiede zwischen den Zirkulationen einer Relationsstruktur für die Akteure sichtbar bleiben. Medien bzw. die Rekurse auf und die Formalisierungen von Medien helfen auch dabei, die Position von Vermittlungsinstanzen in Relationsstrukturen strukturell zu stärken und zu bewahren sowie deren Verbreitung über die gesamte Relationsstruktur sicherzustellen. Dies trägt maßgeblich zur Stabilität der Zirkulation in einer Relationsstruktur bei, und es stärkt die entsprechende Relationsstruktur insgesamt gegenüber den anderen Relationsstrukturen. In diesem Sinne reduziert die Theorie der Relation Medien nicht allein auf Massenmedien (der öffentlichen Kommunikation), geschweige denn auf Print-, Rundfunk- oder Onlinemedien. Vielmehr versteht die Theorie der Relation unter symbolischen Medien immaterielle und materielle Mediationen, die <!-- im Unterschied zu Bourdieus Theorie symbolischen Kapitals --> von ausnahmslos allen Akteuren und Vermittlungsinstanzen unabhängig von der Relationsstruktur bezogen werden können. Über den Bezug durch Akteure werden sie zu Leitmedien dieser Akteure, davon sie die Umstellung von Positionen in und zwischen Relationsstrukturen und zwar kraft der Reziprozitätsmöglichkeiten untertützen, die sie je nach Relationsstruktur potentiell bereitstellen. Über den Rückgriff durch Instanzen von Relationsstrukturen werden sie in den Dienst von formalen Operationen dieser Vermittlungsinstanzen gestellt. Sie werden zu formalen Medien, die formale Verfahren von Instanzen unterstützen und als formale Träger von Hierarchieprinzipien in Relationsstrukturen fungieren, für deren Durchsetzung sich die Arten von Vermittlungsinstanzen in jeder Relationsstruktur einzusetzen versuchen.

Um die Bedeutung und gleichzeitig die Verwendung von Medien an der Seite von Akteuren und von Vermittlungsinstanzen zu illustrieren, verwenden wir ein Beispiel aus der Praxis der Wissensproduktion in Bezug auf die Frage der Legitimation von Wissen angefangen mit dem Plagiat. Das Plagiat setzt eine Verwendung von vorhandenem Wissen voraus, das aufgenommen und im Rahmen von einem neuen Wissenskontext mehr oder weniger neu gestaltet wird. Grundsätzlich setzt das Plagiat eine Praxis des Exzerpierens voraus, die eine lange Geschichte hat und im Kontrast zu zeitgenössischen Praktiken des Exzerpierens -- wie heutzutage im Kontext vom Plagiat oder der Verwendung von digitalen Sprachmodellen -- positiv konnotiert war bzw. als eine legitime Art und Weise galt, Wissen zu produzieren. Am Beispiel von solchen Praktiken wird gezeigt, wie Hierarchieprinzipien im Rahmen der Produktion von Wissen je nachdem entweder durchgesetzt oder geschwächt werden, wie solche Medien der Wissensproduktion zum einen von Akteuren als Symbole ihrer Tätigkeiten und zum anderen von Vermittlungsinstanzen in Unterstützung ihrer formalen Verfahren in Relationsstrukturen einbezogen werden. Dabei stellt sich die Frage danach, wie nicht nur andere Praktiken der Wissensproduktion, sondern auch andere Formen von Wissen und andere Wissenskulturen durch die Unterstützung von Zirkulationswegen anhand von Medien stabilisiert bzw. destabilisiert werden.

<!-- Aus diesen beiden Arten des Ge- und Verbrauchs von (symbolischen und/oder formalen) Medien zum einen durch die Akteure und zum anderen durch die Vermittlungsinstanzen sowie -- ausgehend von den eher austauschzentrierten zu den eher akteurzentrierten Relationsstrukturen -- die wachsende Relevanz von immateriellen und materiellen Mediationen bei der Durchführung der Reziprozität, ergibt sich ferner die doppelte Bedeutung von Medien in der Theorie der Relation: An der Seite der Akteure fungieren Medien als mannigfaltige Träger der Umstellung von Positionen in und zwischen Relationsstrukturen und zwar kraft der Reziprozitätsmöglichkeiten, die sie je nach Relationsstruktur potentiell bereitstellen, während sie an der Seite der Vermittlungsinstanzen als (formale) Träger von Hierarchieprinzipien (Eigenständigkeit und Verbindlichkeit) in Relationsstrukturen fungieren, für deren Durchsetzung sich die Arten von Vermittlungsinstanzen in jeder Relationsstruktur einzusetzen versuchen. -->

<!-- Um den Medienansatz der Theorie der Relation zu veranschaulichen, konzentrieren wir uns hauptsächlich auf den Bereich des Wissens und der (illegitimen) Wissensproduktion. Zu diesem Zweck wenden wir -- um es mit Georg Simmels zweiten Apriori der Rollentranszendenz auszudrücken -- einer besonderen Art des Nicht-Vergesellschaftet-Seins zu: dem Amateur- und dem Autodidaktentum als Negativfolie legitimer Formen der Wissensproduktion.

-->

<!--
Medien, deren Formalisierung und die Bedeutung der Hierarchieprinzipien von Relationsstrukturen | Eigentlich hier eher Plagiat als Formalisierung von Recycling Knowledge, angefangen mit einem Beispiel zu den Amateuren

Die Medien/Mediationen stärken oder schwächen die Verfahren von Vermittlungsinstanzen und entsprechend die Symbolisierungen von Akteuren/Akteurkategorien, was die Wirkungen, die wir im Kap. 6 und 7 hervorgehoben haben, entweder im Sinne der Schwächung oder im Sinne der Stärkung von Relationsstrukturen unterstützt. Hier ein Beispiel mit Exzerpieren und Plagiat.

Wieso werden Amateure und Autodidakten nicht gemocht? Weil sie immer davon verdächtigt sind, kein echtes Wissen zu produzieren bzw. eine Auffassung von Wissen zu produzieren, die für sie Sinn macht, die aber für Kollektiven keinen besonderen Sinn macht. Dabei operieren Amteuren jedoch auf der Grundlage von Praktiken der Akquisition von Wissen, die gängige Praktiken sind, die man sofort in der Geschichte und in der Wissenschaft wiederfindet, und die darin bestehen, das Wissen aus vorhandenem Wissen zu konstruieren. In dieser Hinsicht stellt sich ebenfalls die Frage des Plagiats, die auf der Grundlage der selben Praxis entsteht, und die jedoch als Täuschung verstanden wird. Solche Praktiken stellen die Frage der Verhältnisse zwischen Symbolisierungs- und Formalisierungsoperationen, die aufgrund der Entstehung und der Entwicklung von Medien sind und zur Entstehung und Entwicklung von Hierarichieprinzipien beitragen.

-->

<!--

Verhinderungs- und Satellisierungsstrategien von Relationsstrukturen | Eigentlich hier eher ChatGPT als Formalisierung von Plagiat, das Problem von Wissenschaftlern damit und von Bildungsinstanzen in allen Relationsstrukturen

Wenn Medien stärker als Vermittlungsinstanzen agieren können, dann kommt es zur Entwicklung von Meta-Relationsstrukturen. Hier ein Beispiel mit ChatGPT

Sprachmodelle einerseits als Verbreitung von Ra auf die anderen Relationsstrukturen (Subvertierung und Materialisierung der Ansage Geertz' "culture as text"), und andererseits als eine Arbeit an der Entstehung von einer Metarealtionsstruktur aus Ra durch Satellisierungsstrategien. Parallel Beispiel mit anderen Medien, wie etwa e-moneys und bitcoin.

-->

<!---
**Beispiel(e): ChatGPT des Unternehmens OpenAI und Umverteilung**

OpenAI ist ein Datenwirtschaftsunternehmen, das sich im Allgemeinen auf die Entwicklung und den Betrieb von Algorithmen bzw. von intelligenten Robotern spezialisiert hat und im November des letzten Jahres den Prototyp des Chatbots _ChatGPT_ (Generative Pre-trained Transformer) veröffentlicht hat. Bei ChatGPT handelt es sich um eine Künstliche Intelligenz (KI), die auf Basis von zwei reinforcement-lerning-Instrumenten des maschinellen Lernens trainiert wurde, was, einfach ausgedrückt, bedeutet, dass ein Software-Agent bzw. ein (quasi)eigendynamisches und (quasi)selbsttätiges Computerprogramm basierend auf dem Prinzip der Maximierung positiver wie negativer Sanktionen bzw. qua "menschlichen Feedback(s)" schrittweise eine hochkomplexes Verhalten, auch policy genannt, erlernt (vgl. \url{https://openai.com/blog/deep-reinforcement-learning-from-human-preferences/} \url{https://arxiv.org/abs/1706.03741}). Konkreter gesprochen handelt es sich bei ChatGPT um ein hochgradig leistungsfähiges Sprachmodell, das mit einer schier unglaublich großen Menge an Textdaten -- darunter "Bücher, Wikipedia, Unterhaltungen in Social Media, wissenschaftliche Publikationen" (\url{https://www.scientificamerican.com/article/we-asked-gpt-3-to-write-an-academic-paper-about-itself-mdash-then-we-tried-to-get-it-published/}) und Websites -- trainiert wurde, wodurch ChatGPT nicht nur in der Lage ist, lange Textsequenzen zu be- und verarbeiten, sondern auch selbsttätig auf Basis von 149 Millionen Parameter menschenähnliche Texte zu erzeugen. Anders gesagt, hat ChatGPT die Fähigkeit erlangt, auf eine natürlichsprachliche Eingaben (Fragen, Aussagen oder Befehle), die ausnahmslos durch bestimmte Beziehungen zwischen Wörtern und mehr oder weniger langen Ketten von Abhängigkeiten zwischen Wörtern gekennzeichnet sind, "einen kohärenten und kontextbezogenen Text" zu generieren und somit menschliche Anfragen _zu verstehen_ und -- im Sinne von Chat -- als nahezu allwissender Agent mit einer adäquat menschenähnlichen Antwort darauf _zu reagieren_ (vgl. \url{https://dev.to/abbhiishek/chatgpt-the-ultimate-tool-for-natural-language-processing-and-text-generation-40ag}). Darüber hinaus ist ChatGPT, aufgrund der immensen verarbeiteten Datenmenge, auch aus dem Bereich der Wissenschaft, dazu in der Lage, hochkomplexe und wissenschaftlichen Standards genügende Artikel zu verfassen, was ChatGPT im Rahmen dieses Kapitels so interessant macht.

So führte bspw. Almira Thunström von der Universität Göteborg im Juli des letzten Jahres mit GPT-3, der Vorgängerversion von ChatGPT, ein Experiment durch, bei dem Sie den KI-Algorithmus bat, eine wissenschaftliche Arbeiten über sich selbst mit "wissenschaftlichen Verweisen und Zitaten" -- untergliedert in die Abschnitte "Einleitung, Methoden, Ergebnisse und Diskussion" (url{https://www.scientificamerican.com/article/we-asked-gpt-3-to-write-an-academic-paper-about-itself-mdash-then-we-tried-to-get-it-published/}) -- zu schreiben (vgl. url{https://www.derstandard.de/story/2000137910856/kuenstliche-intelligenz-schreibt-wissenschaftliche-arbeit-ueber-sich-selbst}). Zur Ausführung dieses Befehls benötigte die KI insgesamt zwei Stunden. Das Ergebnis fasst Thunström folgendermaßen zusammen: "Da war neuer Inhalt, in akademischer Sprache, mit soliden Verweisen an der richtigen Stelle und passend zum Kontext [...] Es sah aus wie die Einführung zu einer ziemlich guten wissenschaftlichen Arbeit" (ebd.). Unter Einvernehmen von GPT-3 wurde der wissenschaftliche Artikel anschließend bei einer wissenschaftlichen Zeitschrift eingereicht; er ging zwar noch nicht durch das Peer-Begutachtungsverfahren durch, wurde aber -- zumindest informell -- auf dem "internationalen französischen Preprint-Server _HAL_ veröffentlicht" (vgl. \url{https://www.scientificamerican.com/article/we-asked-gpt-3-to-write-an-academic-paper-about-itself-mdash-then-we-tried-to-get-it-published/}). Mit Abschluss des Experiment resümiert Thunström, dass die Debatte, ob die Zahl der Publikationen wirklich entscheidend für Fördergelder ist, vielleicht neu zu führen sein werde, insb. wenn eine KI ein Paper pro Tag produzieren könne (vgl. url{https://www.derstandard.de/story/2000137910856/kuenstliche-intelligenz-schreibt-wissenschaftliche-arbeit-ueber-sich-selbst}). Derlei Beispiele, d. h. auf Basis von an den KI-Algorithmus gerichteten Prompts verfasste Texte und deren anschließende Veröffentlichung, gibt es mittlerweile viele (vgl. bspw. url{https://www.swr.de/wissen/chat-gpt-bot-co-autorschaft-studien-100.html}; url{https://www.derstandard.de/story/2000142138447/was-die-kuenstliche-intelligenz-chatgpt-ueber-die-zukunft-der-arbeit}; zur ersten nichtmenschlichen Kolumnistin bei der TAZ vgl. url{https://taz.de/Kolumne-einer-kuenstlichen-Intelligenz/!5898282/}).

In Kapitel 8 sollen vor allem die Veränderungen und Konsequenzen, die KI-Algorithmen wie ChatGPT auf die Wissenschaft [vgl. @Wilder2022; @Schmohl2023; @Weßels2021; @Weßels2022], ihre Akteure, ihre Instanzen und ihren jeweiligen Ge- und Verbrauch von Medien zeitigen, aus Sicht der Theorie der Relation problematisiert werden. Kernpunkt dieser Betrachtung wird es sein, die sozio-kulturelle, d. h. die wissenschaftlich orientierte, Relationsstruktur (Ri) im Kontrast und Vergleich zur Medien orientierten Relationsstruktur (Ra) zu perspektivieren. Dabei soll sowohl die Arbeit der Akteure an Ketten der Form Kollektiv -- Verkettungsarbeit -- Zirkulation und die dabei statthafte bzw. legitime Einbeziehung von Medien -- im Unterschied zu Ra -- behandelt werden als auch die Herausforderungen, die für Vermittlungsinstanzen mit derartigen Technologien und deren Vermittlungs- und Formalisierungsarbeit einhergehen. Ferner sollen die möglichen Folgen des Gebrauchs von ChatGPT durch die Akteure im Bereich der Wissenschaft auf die Durchführung der Reziprozität in Ri, die sich der Binarität der Reziprozität in Ra stark annähern könnte, untersucht werden. Dass ChatGPT durchaus einen Einfluss auf die legitimen, d. h. gültigen Operationen der doppelten Einschreibung und damit auf die Durchführung der Reziprozität in Ri -- qua Einschreibung der Verwendung von ChatGPT in die Zirkulation(en) in Ri -- auszuüben imstande ist [@Weßels2022], darüber wurde bereits des Öfteren berichtet (vgl. bspw. url{https://www.nature.com/articles/d41586-023-00107-z?utm_source=Nature+Briefing&utm_campaign=2fd6fa2583-briefing-dy-20230120&utm_medium=email&utm_term=0_c9dfd39373-2fd6fa2583-45994998}; url{https://www.swr.de/wissen/chat-gpt-bot-co-autorschaft-studien-100.html}; url{https://www.derstandard.de/story/2000142470111/studie-chat-gpt-kann-sogar-wissenschaftliche-gutachter-taeuschen}; url{https://www.medrxiv.org/content/10.1101/2022.12.19.22283643v2.full.pdf+html}). Inwiefern sich dieser Einfluss auf die Tätigkeiten und Tätigkeitsbereiche in der Wissenschaft auswirkt -- bspw. hinsichtlich der Bedeutung (a) des austauschzentrierten Hauptmerkmals im Bereich der Wissenschaft, (b) von Kollektiven, (c) von Investitionen in relationale Ereignisse und deren Verkettung vonseiten der Akteure oder auch (d) auf die Sozialisations- und Förderarbeit sowie (e) die formalen Verfahren unterschiedlicher Instanzen der Wissenschaft und (f) die Bedeutung von Medien als relationale Dispositive --, welche Auswirkungen auf die Zirkulation von Akteuren und deren Zirkulationsmöglichkeiten einerseits und die Sichtbarkeit der unterschiedlichen Zirkulationen innerhalb der sozio-kulturellen, d. h. der wissenschaftlichen Relationsstruktur andererseits zu erwarten sind und inwiefern damit letztendlich eine Destabilisierung bzw. Schwächung der gesamten wissenschaftlichen Relatonsstruktur einhergehen könnte, steht dabei besonders im Fokus. Anders und kompakter formuliert, wird in Kapitel 8 eruiert, wie sich ChatGPT _erstens_ als Träger der Umstellung von Positionen an der Seite der Akteure und _zweitens_ als Träger von Hierarchieprinzipien in der wissenschaftlichen Relaionsstruktur, deren Durchsetzung den unterschiedlichen Instanzen der Wissenschaft obliegt, plausibilisieren lässt und welche neuen Perspektiven und Befunde sich ergeben, wenn ChatGPT mit dem Medienkonzept der Theorie der Relation konfrontiert und analysiert wird.

**Beispiel(e): Verhinderungs- und Satellisierungsstrategien von Bildungseinrichtungen gegenüber dem dem Medium ChatGPT**

"Meine lieben Landsleute, ich stehe hier vor euch als großartiger Verehrer meines Kaisers Wilhelm II. Wir leben in einer Zeit des Wandels und der Herausforderungen, aber ich bin mir sicher, dass unser Kaiser uns durch diese schwierigen Zeiten führen wird" (ChatGPT 2023, vgl. url{https://www.swr.de/swraktuell/rheinland-pfalz/ludwigshafen/chatgpt-pfalz-schule-100.html}). Vorreiter: Karolinen-Gymnasium in Frankenthal, Rheinland-Pfalz integriert Chatbot in den Geschichtsunterricht: Lehrerin: Karin Reißer-Mahla

ChatGPT als Teil von Vermittlungsstrukturen bzw. die Integration in Vermittlungsstrukturen (Schulen und Lehrer, die dieses Medium in den Unterricht integrieren sowie die Sozialisation und Förderung des Umgangs mit diesem Instrument durch SchülerInnen unterstützen (Satellisierungsstrategie) VS Schulen bzw. Organisationen, die die Verwendung bzw. die Einbeziehung von ChatGPT in die soziale Arbeit von Akteuren unterbinden, verbieten, damit Täuschungen provoziert und auf lange Sicht an Reziprozitätsmacht und Legitimität einbüßen werden

-->

#### Kapitel 9: Die Verlockung von Meta-Relationsstrukturen. Verschmutzung teilen.

<!-- Im Kapitel 8 haben wir zuletzt darauf hingewiesen, dass sich aus den beiden Arten des Ge- bzw. Verbrauchs von (symbolischen und/oder formalen) Medien bzw. von Mediationen sowohl durch die Akteure als auch durch die Vermittlungsinstanzen in Relationsstrukturen die doppelte Bedeutung von Medien in der Theorie der Relation ergibt. Diese besteht zum einen an der Seite der Akteure darin, dass Medien als mannigfaltige Träger der Umstellung von Positionen in und zwischen Relationsstrukturen fungieren, während sie an der Seite der Vermittlungsinstanzen darin besteht, dass Medien (formale) Träger von Hierarchieprinzipien (Eigenständigkeit und Verbindlichkeit) in Relationsstrukturen sind, deren Durchsetzung und Aufrechterhaltung wiederum derjenigen Art von Vermittlungsinstanz obliegt, die das Schwerkraftzentrum der entsprechenden Relationsstruktur darstellt. -->

Das Kapitel 9 knüpft insofern auf das Kapitel 8 an, als zunächst darauf hingewiesen wird, dass sowohl der Stil, wie Akteure symbolische Medien in ihre Arbeit einbeziehen, als auch der Stil, wie Vermittlungsinstanzen erstens diese Einbeziehung durch die Akteure und zweitens die symbolischen Medien selbst (nach Form und Funktion, zu Medienkontexten oder relationalen Dispositiven) formalisieren, nicht nur die jeweilige Bedeutung der Reziprozitätsmacht innerhalb einer Relationsstruktur <!-- (multimodal in Ri, bimodal in Rr und Rm, unimodal in Ra) --> generiert [@PapilloudSchultze2022, 374], sondern auch die Stärke dieser Reziprozitätsmacht mitbestimmt, die wiederum zur Zirkulationsmacht einer jeden Relationsstruktur maßgeblich beiträgt (vgl. ebd., 372). Stellen wir nun ferner in Rechnung, dass die Stärke der Reziprozitätsmacht in einer Relationsstruktur sowohl die Zirkulationsmacht von Akteuren darin als auch die Machtposition von Instanzen dieser Relationsstruktur ausdrückt und abbildet, so setzt die Bewahrung der Reziprozitätsmacht einer Relationsstruktur die Sicherstellung sowohl solcher Zirkulationen als auch solcher Positionen voraus (vgl. ebd., 374). Eingedenk der Tatsache, dass die Instanzen einer Relationsstruktur im Unterschied zu Akteuren -- _unmittelbar_ zur Reziprozitätsmacht und deren Ausmaß beitragen und zwar indem sie am Ausbau, der Verbreitung und Effektivität ihrer Vermittlungsstruktur arbeiten, spielen die Instanzen bzw. Schwerkraftzentren einer Relationsstruktur eine besondere Rolle für die Bewahrung und Stärkung der Reziprozitätsmacht in einer Relationsstruktur. Um also einer möglichen Deprivation der Reziprozitätsmacht entgegenzuwirken, sind Vermittlungsinstanzen ständig versucht, an Einfluss in ihrer Relationsstruktur zu gewinnen und zwar entweder indem sie die Entstehung und Verbreitung anderer Vermittlungsinstanzen _verhindern_ oder indem sie bereits bestehende Instanzen innerhalb oder außerhalb ihrer Relatonsstruktur _satellisieren_ (vgl. ebd., 374f.).

Wenn Verhinderungsstrategien hohe Kosten für Relationsstrukturen haben, weil die Verhinderung von externen Einflüssen die Verbreitung von Relationsstrukturen schwächt und stört, haben dagegen Satellisierungsstrategien Vorteile für Relationsstrukturen. Bei solchen Strategien handelt es sich für Relationsstrukturen darum, Einflüsse auf die anderen Realtionsstrukturen über Allianzen zwischen Vermittlungsinstanzen der selben Art in den unterschiedlichen Relationsstrukturen zu üben. Eine solche Strategie zielt darauf ab, eine Meta-Relationsstruktur anhand von solchen Vermittlungsinstanzen zu etablieren, die deshalb als Meta-Relationsstruktur beschrieben werden kann, weil sie von Zirkulationen und Wirkungen dieser Zirkulationen auf die Relationsstruktur frei wäre, als ob sie eine ideale perfekte Relation wäre. Diesen Punkt werden wir im Kapitel 9 am Beispiel des _personal carbon trading_ (PCT) im Rahmen der Debatten zum Klimawandel behandeln. In der Folge von ähnlichen mehr oder weniger glücklichen Initiativen zwischen Ländern und zwischen Großindustrien, die darauf abzielen, ein gemeinsames Karbonbudget zu definieren und auf Länder bzw. Großindustrien aufzuteilen, um Karbonemissionen einzuschränken, macht das PCT ein Schritt weiter: Es erweitert das Prinzip des Karbonbudgets auf alle Einzelakteure in allen Tätigkeitsbereichen einer Gesellschaft. Das PCT zeigt somit, wie es versucht wird, Schwierigkeiten bei der Einschränkung von Karbonemissionen durch die Verbreitung vom PCT auf alle Relationsstrukturen zu lösen, die insbesondere der Satellisierungsstrategie der wirtschaftsorientierten Relationsstruktur zugute kommt. Für diese Relationsstruktur verspricht die Durchsetzung vom PCT neue Entwicklungsmöglichkeiten mit Entstehung von einem wirtschaftlichen Markt, auf dem es möglich wäre, Profite und neue Wertschöpfungsquellen anhand von der Karbonverschmutzung durch den Austausch von Karbonanteilen privater Akteure sowie Kollektivakteure zu generieren.

<!-- Anders gesagt, entwickeln Vermittlungsinstanzen entweder Verhinderungs- oder Satellisierungsstrategien, um auf ent- oder bestehende Vermittlungsinstanzen einzuwirken, wobei Verhinderungsstrategien ausschließlich innerhalb und Satellisierungsstrategien sowohl innerhalb als auch außerhalb der eigenen Relationsstruktur zur Anwendung kommen (ebd., 375). -->


<!--
Klima, Messung von Temperaturindikatoren, Formulierung von Maßnahmen(katalog), die an der Realität vorbeigehen, die unabhängig von Zirkulation in RS sind; Macht von Aggregaten bzw. aggregierten Daten/Zahlen; niemand weiß, wie man Klimaschutz in all seiner Breite in Zirkulation bringen soll

Natur als Rechtssubjekt __ Natur als Rechtssubjekt in der Verfassung Equadors und Boliviens (politische Ökologie -- Natur bzw. Ökologie als neue soziale Klasse vgl. Latour 2022)
Erste Grichtsverfahren: https://amerika21.de/2021/12/255888/ecuador-verfassungsgericht-rechte-natur
-->


#### Kapitel 10: Die Theorie der Relation als soziologische Theorie.

Die in dieser Monographie dargestellten Beispiele haben Kernelemente der Theorie der Relation illustriert, die in diesem Schlußwort in ihrer Bedeutung im Bereich der soziologischen Theoriebildung hervorgehoben werden. Diese Hervorhebung basiert auf Veränderungen, die die Theorie der Relation in die soziologische Theorie einführt und die wie folgt zusammengefasst werden können: Mit ihrem Primat der Zirkulation und ihrem Verständnis von Relation nach einem makrosoziologischen Ansatz will die Theorie der Relation den Relationismus vermeiden, der die Beschreibung von gesellschaftlichen Phänomenen als Relation mehrfach belastet. Der Relationismus beschreibt die eine Art der Substantialisierung von Relation, die davon ausgeht, das Relation in der Form von relationalen Ereignissen alles miteinander verbindet. Die Theorie der Relation macht einen entscheidenden Schritt jenseits des Relationismus ab ihrer Auffassung von Relationsstrukturen als Abweichungen von einer idealen Relation und ab ihrer Unterscheidung zwischen Relationsstrukturen, relationalen Ereignissen und Zirkulationen, was die Perspektive für die Analyse von nicht oder passiven relationalen Ereignissen und im Allgemeinen von nicht bzw. passiven handeln in ihrer Bedeutung für Zirkulationen zulässt. Ferner dekonstruiert die Theorie der Relation mit ihrem Verständnis von Reziprozität die optische Metapher von einem "Hin und Zurück" als feste Dynamik von relationalen Ereignissen sowie den damit verbundenen Glauben, dass Reziprozität genuin aus interpersönlichen Beziehungen entstehen würde. Auf diese Weise öffnet die Theorie der Relation die soziologische Analyse auf Legitimationsprozesse ab der Entwicklung von Zirkulationen, was zur Folge hat, dass Fragen, die mit Legitimationprozessen verbunden sind -- darunter traditionelle Fragen der Anerkennung, der sozialen Ungleichheit, der Herrschaft --, unmittelbar mit der sozialen Arbeit an Zirkulationsentwicklungen in und zwischen Relationsstrukturen problematisiert und reflektiert werden können, statt sie kategoriell bzw. auf Kategorien von Akteuren und Kollektivakteure zu reduzieren. Dies geht nicht ohne eine rekonstruktive Analyse von solchen Zirkulationsentwicklungen, was den Untersuchungen im Rahmen der Theorie der Relation eine geschichtliche Dimension verleiht, wie wir es in den in dieser Monographie erwähnten Beispielen hervorgehoben haben.

Daraus ergibt sich die Botschaft, die mit der Theorie der Relation verbunden ist. Sie besagt, dass Relation als ideale, perfekte Relation die Grundmotivation des sozialen Lebens und die Grundlage der Rechtfertigung der vielfältigen Verhältnisse darstellt, die das gesellschaftliche Leben generiert und die Abweichungen von einer solchen idealen Relation in der Form von Relationsstrukturen sequentiell dimensionieren. Die Theorie der Relation erklärt entsprechend, wie dieses Streben nach einer idealen Relation auf den unterschiedlichen Ebenen einer Gesellschaft ständig gestört wird, woraus bzw. wodurch wiederum Laufbahnen von Akteuren, Mobilisierungen von Kollektivakteuren, Einschreibungsakte, auf- und absteigende Mobilitäten, Veränderungen von Ungleichheiten, von Einflussstrategien und Machtkämpfen sowie gesellschaftliche Blasen als verwundbare Meta-Relationsstrukturen produziert werden.

<!-- Oder man kann den Text von EMS hiernach nehmen
Finde ich sehr gut, die zwei Absätze zu Kapitel 10

Im Schlusskapitel werden wir zunächst darauf eingehen, dass die Theorie der Relation im Bereich relationaler Soziologie eine Makroperspektive zur Relation anbietet, die sich von anderen relationalen Soziologien insofern unterscheidet, als sie das Relationale nicht auf soziale Beziehungen gegenseitigen Gebens und Nehmens, auf intersoziale Tauschtransaktionen oder das Subjektive reduziert, sondern auf ganz konkrete Makrodeterminanten fokussiert und deren Zusammenspiel in aller Komplexität rekonstruktiv zu erfassen in der Lage ist. Diese Makrodeterminanten besitzen eine gewisse geordnet-impermanente Permanenz im Gesellschaftlichen und eine relative Unabhängigkeit von der Zeit, weshalb unter Verweis auf die von uns thematisierten Beispiele ebenfalls betont werden soll, dass sich die Theorie der Relation sowohl für historische Analysen als auch für gegenwartsbezogene Untersuchungen eignet. Im Unterschied zu gängigen theoretischen Auffassungen im Bereich der relationalen Soziologie unterstreicht dieser Punkt zum einen die große Reichweite unseres Relationsansatzes, zum anderen demonstriert er aber auch, dass die Theorie der Relation einen umfassenden Geltungsbereich abdeckt, der sie für eine große Bandbreite von Gegenständen öffnet und sie für deren empirische Untersuchung prädestiniert. Solche und andere Untersuchungen haben den Vorteil, dass sie nicht in Unterstützung einer Ontologie der Relation entwickelt werden, wodurch der Forschungsgegenstand  zumeist _als_ Relation plausibilisiert wird, sondern vielmehr eine Soziologie _durch_ Relation betrieben werden kann, die das komplexe Mit-, Für-, Bei- und Gegeneinander von Akteuren, Kollektiven, Vermittlungsinstanzen, Medien, Akanten, Symbolen und Zeichen in ihrem Zusammenwirken abzubilden und _durch_ Relation zu verstehen erlaubt. Dies gilt umso mehr, als die Theorie der Relation eine pseudo-realistische und formal-neostrukturalistische Perspektive auf Gesellschaftliches offeriert, die der theoretischen Eindimensionalität entgeht, indem sie nicht nach Logiken von sozialen Systemen oder Feldern fragt, sondern im Gegenteil die Heterogenität von Tätigkeiten und Tätigkeitsbereichen der Akteure und deren Strukturierung anerkennt sowie die Verteilung heterogener Akteure auf diese heterogenen Tätigkeiten über das Primat der Zirkulation aufschließt. In diesem Sinne stellt die Theorie der Relation der empirischen Forschung ein Werkzeug zur Verfügung, mit dem eine Vielzahl von Gegenständen nicht nur in ihrer Dynamik als Zirkulation erfasst werden können, sondern auch in ihren gesellschaftlichen Ursachen rekonstruiert und in ihren soziale Konsequenzen erklärt werden können.

-->
