---
title: "Schlußwort"
indent: true
output:
    html_document: default
csl: chicago-author-date.csl
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Mit dem Grundgerüst der Theorie der Relation wird ein Instrumentarium geliefert, das die Strukturierung des Primat der Zirkulation in den verschiedensten Situationen und am Beispiel von verschiedenen (Kollektiv)Akteuren, Aktanten und gesellschaftlichen Instanzen systematisch in seinen drei allgemeinen Ebenen im Dienst der soziologischen Untersuchungen von relationalen Phänomenen rekonstruiert. Wie gut eine solche systematische Untersuchung funktioniert, lässt sich am besten prüfen, wenn dabei unterschiedliche Themen, Kontexte und Zeiten berücksichtigt werden, die jeweils eine unterschiedliche Lage in Bezug auf das Primat der Zirkulation darstellen. Mit den Beispielen, die in diesem Band behandelt wurden, haben wir eine solche Prüfung initiiert, woraus sich wiederum die folgenden Schlußfolgerungen für die Theorie der Relation im Speziellen und für die Soziologien im Allgemeinen ziehen lassen, die ihre Untersuchungen nach einem relationalen Ansatz entwickeln.

Am Beispiel vom Marcel Mauss' Gabe und Nation haben wir in unserem ersten Kapitel gesehen, dass die Frage der Reziprozität nicht als Anerkennungsmoment zwischen Akteuren, sondern als Legitmationsverfahren aus der Verteilung von Zirkulationschancen einerseits und der Schließung von Zirkulationswegen andererseits heraus neu problematisiert werden sollte, wobei sowohl die Legitimationsverfahren als auch deren Doppelcharakter auf den Grundfesten von Einschreibungsakten der Akteure und gesellschaftlichen Instanzen in Zirkulationen ruhen. Bei Mauss kommt eine solche neue Auffassung von Reziprozität deshalb zum Vorschein, weil er zum einen die relationalen Phänomene zwischen Akteuren und Aktanten, die er in der Gabe untersucht, unmittelbar in Verbindung mit deren Mediation durch gesellschaftliche Instanzen betrachtet. Zum anderen ist für Mauss die Mediationsarbeit selbst eine praktische Angelegenheit, die die Menschen mit ihren gesellschaftlichen Instanzen mittels der Verwendung von sehr unterschiedlichen symbolischen und formalen Medien zusammenbringt. Die Grundlage wie der Horizont von Herausforderungen und von Kämpfen zwischen Gruppen von Akteuren, die sich in den unterschiedlichen Formen der Gabe zu erkennen geben, besteht in der gegenseitigen Unterstützung zur Schließung der alten gesellschaftlichen Ordnung und zur Eröffnung einer neuen gesellschaftlichen Ordnung. Daraus ziehen die Akteure, ihre Gruppen, die gesellschaftlichen Instanzen und schließlich die ganze spirituelle sowie natürliche Umgebung solcher Gesellschaften ihre Legitimität, die ständig weiter unterstützt und weiterentwickelt wird, was wiederum zu neuen relationalen Phänomenen führt. Die modernen Nationen folgen denselben Regeln, allerdings mit dem Unterschied, dass die Totalität, die die Reziprozität der Gabe in den alten Gesellschaften symbolisierte, in der Zeit immer mehr fragmentiert wurde. Infolge dessen kam es in den zeitgenössischen Gesellschaften zu einer Ausdifferenzierung von Legitimationsordnungen, die einerseits zwar Zirkulationsmöglichkeiten vermehren, die aber andererseits Zirkulationswege stärker stratifizieren, was den Akteuren und gesellschaftlichen Instanzen mehr Arbeit abverlangt, um solche Wege zu entwickeln und sich in solchen Zirkulationen einzuschreiben.

Das solche Wege in unseren Gesellschaften zu bahnen nicht selbstverständlich ist, haben wir in unseren Kapiteln über das Doppelleben der Künstler und über Stars als politische Anführer deutlich gemacht. Dass jedoch die Entwcklung von Zirkulationen nicht nur in modernen Gesellschaften zu Schwierigkeiten führen kann, sondern auch in historischen Gesellschaften zu Schwierigkeiten führte, haben wir ferner mit unserem Kapitel über die Päpste im (Hoch)Mittelalter illustriert. In jedem der drei Kapitel sind die Gründe für solche Schwierigkeiten unterschiedlich. Bei den Künstlern, die ihr Leben zwischen dem eigenen Kunstprojekt und einer Erwerbstätigkeit in der Wirtschaft entwickeln müssen, besteht die Hürde bzgl. der Entwicklung von Zirkulationswegen darin, dass sie kaum geeignete gesellschaftliche Instanzen der Kunst erreichen, die ihnen Einschreibungsmöglichkeiten in der Kunst auf längere Sicht gewährleisten könnten. Deshalb müssen sich diese Künstler einer ganz anderen Tätigkeit widmen bzw. zu einer ganz anderen Relationsstruktur -- in unserem Beispiel in die Wirtschaft -- zirkulieren, um  überhaupt ein Künstlerleben führen bzw. sich dieses leisten zu können. Das Ziel für diese Künstler ist dabei nicht etwa, sich mit entsprechenden gesellschaftlichen Instanzen der Wirtschaft im Rahmen einer entsprechenden Beschäftigung auf dem üblichen Arbeitsmarkt einzuschreiben. Das Ziel für diese Künstler besteht vieleher darin, auf Basis einer Erwerbstätigkeit in der Wirtschaft ihr Künstlerleben weiter finanzieren zu können, die sie ansonsten längst hätten aufgegeben müssen. Diese oszillierende Zirkulation zwischen Kunst und Wirtschaft führt jedoch dazu, dass die erhoffte weitere Zirkulation in der Kunst regelmäßig unterbrochen werden muss, was ihre Entwicklung verlangsamt und diese Künstler im schlimmsten Falle so sehr an den Rand der Erschöpfung führt, dass sie aus der Zirkulation in der Kunst ausscheiden.

Am Beispiel von Arnold Schwarzenegger und Wolodyrmyr Selenskyj sehen wir eine andere Art von Schwierigkeit für die Akteure, Zirkulationswege zu bahnen und Zirkulationsmöglichkeiten zu generieren, insbesondere wenn diese Zirkulationen zwischen unterschiedlichen Relationsstrukturen entwickelt werden. Diese Schwierigkeiten beim Bahnen und Stabilisieren von Zirkulationswegen bestehen in diesen beiden Fällen darin, dass gesellschaftliche Instanzen, die Einschreibungsakte unterstützen könnten, nicht vorhanden sind. So genießen Schwarzenegger und Selenskyj zwar ein hohes Ansehen in ihren jeweiligen Tätigkeiten als Actionheldikone, Schauspieler, Diener des Volkes und Kabarettist. Aber im Unterschied zu den Künstlern unseres zweiten Kapitels möchten beide Stars nicht nur zu einer anderen Relationsstruktur zirkulieren -- in diesem Fall zur politisch orientierten Relationsstruktur --, sondern sie möchten sich auch dort einschreiben. Aber was tun, wenn die geeigneten gesellschaftlichen Instanzen, mit denen eine solche Einschreibung erfolgen könnte, nicht nur schwer zu erreichen sind, sondern gar nicht vorhanden sind? Dann muss man sie sukzessiv aufbauen. Am Beispiel von Schwarzenegger und Selenskyj gelingt dies nur durch die Mobilisation von anderen Akteuren -- in diesem Fall von Wahlkampfstrategen, Meinungsforschern, Politikberatern, Social-Media-Experten, Politikern etc. -- zum Zweck der Bildung von Kollektiven -- d. h. eines Wahlkampfstabs -- und der Ernennung von Vertretern dieser Kollektive, die dann damit beginnen können, als gesellschaftliche Instanzen in Unterstützung von Einschreibungsakten in Erscheinung zu treten. Zudem handelt es sich bei der von Schwarzenegger und Selenskyj angestrebten Zirkulation in die Politik keineswegs um eine unmittelbare Zirkulation, die vollständig umstandslos entwickelt werden könnte. Sowohl Schwarzenegger als auch Selenskyj bahnen sich zuerst einen Weg in die Medien, der darauf abzielt, ihre Attraktivität in der Öffentlichkeit zu verbreiten. Erst diese ikonenhafte Attraktivität als Entertainer, Actionheld und Star der US-amerikanischen und ukrainischen Traumfabrik gesattet es ihnen, ihre Attraktivität in den Dienst der Repräsentation der Öffentlichkeit bringen zu können. In den Termini der Theorie der Relation bedeutet dies Folgendes: Schwarzenegger und Selenskyj müssen erst unzählige Male die Zirkulation in der medialen Relationsstruktur durchlaufen, bevor ihnen der Sprung in die soziopolitische Relationsstruktur gelingt, sie sich sowohl mit ihren eigenen als auch mit vorhandenen gesellschaftlichen Instanzen dieser Relationsstruktur einschreiben und ihre Zirkulation in der Politik als Gouverneur von Kalifornien bzw. als Staatspräsident der Ukraine stabilisieren können.

An diesem Beispiel merken wir, dass trotz sehr unterschiedlicher geographischer, sozialer und kultureller Kontexte, Zirkulationswege und Einschreibungsakte nicht nur sehr ähnlich entwickelt und durchgeführt werden, sondern mindestens ebenso sehr vergleichbare Zirkulationsmöglichkeiten eröffnen. Gleichsam liefert uns Schwarzeneggers und Selenskyjs Zirkulation ein gutes Beispiel, um die Evidenz einer Aussage, die wir in diesem Band mehrmals hervorgehoben haben, zu unterstreichen. Einerseits gibt es keine ideale Zirkulation, sondern Zirkulationen werden immer von den strukturellen Eigenschaften einer Relationsstruktur, also ihrer Stratifikation in Akteurkategorien, Kategorien von gesellschaftlichen Instanzen und in Sequenzen, bestimmt. Werden jedoch Zirkulationen entwickelt, dann können sie solche strukturellen Eigenschaften von Relationsstrukturen subvertieren, was die Zirkulation von einer zu einer anderen Sequenz innerhalb einer Relationsstruktur oder -- wie im Falle Schwarzeneggers und Selenskyjs -- zwischen denselben Sequenzen zweier Relationsstrukturen gut abbildet. Dies sind die Dimensionen der spezifischen Agency, auf die die Theorie der Relation aufmerksam macht, wenn sie vom Primat der Zirkulation spricht. Gleichzeitig wird damit deutlich, dass diese Dimensionen analytisch stets in ihren Wechselbeziehungen betrachtet werden müssen, was zur Deutung von Gesellschaften _durch_ Relation führt. Prosaïscher formuliert, bedeutet dies, dass die Theorie der Relation nicht entweder den Akteur, oder die Gruppen von Akteuren, oder die Aktanten, oder die Medien, oder die gesellschaftlichen Instanzen usw. fokussiert. Sie fokussiert das Zusammenspiel zwischen all diese Einheiten, und sie erklärt, wie sich ein solches Zusammenspiel in Zirkulationen niederschlägt, die das gesellschaftliche Leben dimensionieren.

Diese letzten Formulierungen können wir in Anlehnung an Mauss und in Anlehnung an unsere Einleitung wie folgt konkretisieren: Auf relationale Phänomene kann man sich unterschiedlich je nachdem beziehen, ob wir die Relation, die Kollektive in dieser Relation, die Akteure in diesen Kollektiven oder die Welten der Mediationen innerhalb und außerhalb von solchen relationelen Phänomenen fokussieren. In ähnlicher Weise geht auch Mauss in seiner Untersuchung zur Gabe vor, wenn es bei der Gabe um den Austausch, um die Gruppen und gesellschaftlichen Instanzen, die in einem Austausch involviert sind, um die Akteure aus diesen Gruppen, die sich herausfordern, um die Welten der Götter und der Natur in ihrer Verbindung mit der Welt der Menschen geht. Dass diese vier Perspektiven auf Relation den Legitimationsordnungen entsprechen, die in der Theorie der Relation als vier Relationsstrukturen herausgearbeitet werden, tritt dagegen je nach Gesellschaften nicht unbedingt in einer solchen Deutlichkeit hervor. Unser Kapitel zum Legitimationskampf zwischen Kaisern und Päpsten im (Hoch)Mittelalter liefert jedoch ein gutes Beispiel für eben solche Legitimationsordnungen.

Wie Mauss mit seinem Begriff der Totalität bzw. der totalen sozialen Tatsachen behauptet, kann man in den Gesellschaften des ersten Deutschen Reiches die vier Relationsstrukturen erkennen, von denen die Theorie der Relation spricht. Allerdings sind sie im Vergleich zu unseren Gesellschaften weniger deutlich voneinander zu unterscheiden bzw. enger miteinander verbunden, sofern sie bis zu jenem Zeitraum überhaupt zu einer spezifischen Legitimationsordnung von gesellschaftlichen Verhältnissen entwickelt wurden. Eindrücklich veranschaulicht dies der Fall der Medien orientierten Relationsstruktur. Ebenfalls legt das Beispiel der päpstlichen Urkunden davon Zeugnis ab, in denen die Nachahmung von Formalien aus der imperialischen Kanzelei mit einer gewissen Improvisation bei der Verwendung der Schrift ab den Buchstabenformen zur Initiale des Papstnamens vermischt wird. Aber auch die wirtschaftlich orientierte Relationsstruktur ist in jener Zeit wenig entwickelt und wird sowohl vonseiten des Kaisers als auch vonseiten der adeligen Familien und des kirchlichen Personals stark beansprucht. Deshalb sind insbesondere Zirkulationen zur Entwicklung und Strukturierung der soziokulturellen und soziopolitischen Relationsstrukturen zu beobachten, die entsprechend einen Raum für Auseinandersetzung von gesellschaftlichen Instanzen dieser Gruppen bieten und darstellen. Im Vergleich zu den Kapiteln über das Doppelleben der Künstler und über die Stars Schwarzenegger und Selenskyj, die zu politischen Staatsmännern werden, haben wir es hier jedoch mit einem anderen Beispiel von Schwierigkeiten zu tun, die mit der Entwicklung von Zirkulationswegen im speziellen Fall des Investiturstreites zwischen gesellschaftlichen Instanzen der Macht und der Religion verbunden sind. Hinter diesem Streit verbirgt sich eine gegenseitige Satellisierung zwischen der politischen Macht und der Religion, die einerseits zeigt, wie Relationsstrukturen auf andere Relationsstrukturen verbreitet werden und anderen Relationsstrukturen ihr Verständnis von Reziprozität und Legitimation aufzuzwingen versuchen. Dabei verläuft diese gegenseitige Satellisierung ausgehend von der Zirkulation der Mitglieder adeliger Familien zu kirchlichen Instanzen, die sich dort einschreiben und mittelbar zur Stärkung der politischen Macht beitragen, zu den gregorianischen Reformen, die die Macht der Päpste gegenüber dem Kaiser stärken sollten, und weiter zu den internen Konflikten zwischen den krichlichen Instanzen, die sich mit Päpsten und Anti- oder Gegenpäpsten herausfordern: Diese Entwicklung von Satellisierungen stratifiziert die genannten zwei Relationsstrukturen, und in der Zeit trägt sie dazu bei, sie besser voneinander zu unterscheiden und in ihrer respektiven Stärke zu verdeutlichen.

Darin ist ferner die Basis zum Aufbau des Selbstverständnisses einer jeden Relationsstruktur zu erkennen, d. h. von den Vermittlungsinstanzen in ihr, von den Tätigkeitsbereichen, die dort entwickelt werden, und von den Akteuren und Kollektiven, die innerhalb von einer Relationsstruktur zirkulieren. Dieses Selbstverständnis ist niemals deutlicher als in der modernen Gesellschaft sichtbar, in der das Muster der sozialen Arbeit an relationalen Ereignissen und entsprechend das Muster der Zirkulation vollständig in all ihren vier Möglichkeiten entwickelt wurde. Zudem hat diese Entwicklung zur Bildung der vierten bzw. der letzten Relationsstruktur als einer eigenständigen Relationsstruktur geführt, in der die Zirkulation für die Zirkulation selbst bevorzugt wird, die am besten von Aktanten bzw. symbolischen sowie formalen Medien gewährleistet wird.

Eingedenk dieser Tatsache stellt sich die vierte Relationsstruktur als ein neues und gleichzeitig mächtiges Organisationsprinzip von Verhältnissen zu relationalen Ereignissen vor, das die soziale Arbeit und grundsätzlich die Verhältnisse zu relationalen Ereignissen von Akteuren und Kollektiven unmittelbar mit ihrem Beitrag zum ständigen Zirkulieren von Zirkulationen verbindet. Dies ist die spezifische Asymmetrie, die aus der Strukturierung von dieser vierten Relationsstruktur hervorgeht. Nach dem Selbstverständnis dieser Relationsstruktur muss ständig daran gearbeitet werden, dass in jedem Tätigkeitsbereich, d. h. in jeder Sequenz dieser Relationsstruktur unaufhörlich zirkuliert wird. Dies stellt die Akteure und Instanzen in dieser Relationsstruktur unter den besonderen Druck, kontinuierlich zu ihrer bzw. zur Zirkulation von Akteuren beizutragen. Die mittelbare Folge daraus ist die Delegation einer solchen Arbeit an Aktanten bzw. an symbolische und formale Medien. Diese Folge ergibt sich nicht zufällig, sondern daraus, dass im Unterschied zu Aktanten bzw. Medien und besonders in unserer Zeit mit hochtechnologisierten Medien Akteure, Kollektive und Vermittlungsinstanzen Zeit brauchen und einen hohen Aufwand betreiben, um eine Arbeit an relationalen Ereignissen und an den Einschreibungsakten zu leisten, die sie in Zirkulationen und entsprechend in Sequenzen und Relationsstrukturen einschreiben. Davon sind Aktanten und Medien befreit.

Am Beispiel der Transformer haben wir in diesem Band gesehen, wie die Entwicklung dieser Relationsstruktur, die wir als Medien orientierte Relationsstruktur bezeichnet haben, den Einsatz von Medien in allen Relationsstrukturen verallgemeinert. Diese Medien sind nicht nur die Hebel einer gesellschaftlichen Veränderung im Sinne von Werkzeugen der Veränderungen unserer Verhältnisse zu uns selbst, zu den anderen, zu Kollektiven, zu Aktanten und zu Medien. Sie sind auch und vor allem veränderte und -- in ihrer integriertesten Form von eingebetteten Kontexten von Medien, d. h. von relationalen Dispositiven -- Verhältnisse und Bündelungen von Verhältnissen, die sich selbst in Zeit und Raum sowie je nach Tätigkeiten umwandeln, verschieben und neu verwebt re-produzieren. Mit diesem Selbstbewusstsein hat dieses vierte Organsiationsprinzip von Verhältnissen zu relationalen Ereignissen eine Reihe von Akteuren gewonnen, die nach diesem Organisationsprinzip Tätigkeitsfelder und Vermittlungsinstanzen entwickelt haben. Sie haben dazu beigetragen, diese Relationsstruktur von den drei anderen Relationsstrukturen zu verselbständigen. Die Presse, der Aufbau und die Verbreitung von mächtigen Instanzen der Bildung, das Internet, die Konzerne hinter der Entwicklung von sozialen Medien und heutzutage hinter der künstlichen Intelligenz haben die Vision von unaufhörlichen zirkulierenden Zirkulationen konkretisiert. Auf der Grundlage der Delegation der Strukturierung von Relationsstrukturen greifen sie bis in die Akte der Einschreibung von Akteuren und Vermittlungsinstanzen zur Produktion von Zirkulationswegen und Zirkulationsmöglichkeiten in allen Relationsstrukturen ein. Mit der Stärkung dieser vierten Relationsstruktur werden entsprechend Formen bzw. Muster von gesellschaftlichen Ungleichheiten auf alle Relationsstrukturen verbreitet. Sie basieren darauf, dass Verhältnisse zu relationalen Ereignissen immer stärker in relationalen Dispositiven implementiert werden müssen, um als Verhältnisse gelten zu können, die tatsächlich zu Zirkulationswegen und -möglichkeiten und ferner zur Strukturierung von Relationsstrukturen beitragen. Dass davon die Legitimation von Akteuren und von gesellschaftlichen Instanzen und schließlich die Reziprozität in den anderen Relationsstrukturen betroffen ist, bildet eine unvermeidliche Folge aus dieser Implementierung. Sie betrifft sowohl die Einschreibung in Relationsstrukturen als auch die Satellisierung von Relationsstrukturen, als auch die Widerstandsformen auf jeder Ebenen von Relationsstrukturen _für_ und _gegen_ diese neue Bedeutung von Verhältnissen in den Gesellschaften.

Dass dabei die Bedeutung von gesellschaftlicher Ungleichheit immer mehr in Richtung ubiquitärer Verhältnisse bestimmt wird, dürfte somit eine mögliche Entwicklung aus der Verbreitung der Macht dieser vierten Relationsstruktur sein. Sie kann dazu führen, dass die Verbindung zwischen Zirkulationswegen und Zirkulationsmöglichkeiten mit sozialen Ressourcen der Akteure und der Gruppen von Akteuren durch die Implementierung in relationale Dispositive immer weiter geschwächt und gestört wird. Das Gewicht von sozialen Determinanten zum Vorteil der kontinuierlichen Beschäftigung mit Verhältnissen zur Entwicklung von Zirkulationen kann dabei zwar weniger entscheidend sein, weil diese Verhältnisse zur Entwicklung von Zirkulationen in den anderen Relationsstrukturen lediglich teilweise von Medien getragen werden. Gleichzeitig kann der zunehmende Einfluss von Medien bei der Entwicklung von Zirkulationswegen in allen anderen Relationastrukturen auch dem Eindruck bzw. der Illusion von einer perfekten gesellschaftlichen Demokratisierung bzw. von einer realisierten liberalen Gesellschaft Vorschub leisten und zwar durch die idealisierte Eröffnung der Zugänge zu den unterschiedlichen gesellschaftlichen Tätigkeitsbereichen, die die Medien weithin versprechen. Die kehrseite einer solchen möglichen Entwicklung ist jedoch die unvermeidliche Relativierung, wenn nicht gar die Abschaffung von kollektiven Stützen zum Erhalt von für die Akteure und sozialen Gruppen erprobten oder gewöhnlichen Verhältnissen zu relationalen Ereignissen.

Bei unserem Exkurs zur sozialen Ungleichheit ging es uns nicht darum, eine Deutung dieser für die Soziologie wichtigen Fragestellung vom Standpunkt der Theorie der Relation nur unter Berücksichtigung der Strukturierung und Verbreitung der Medien orientierten Relationsstruktur anzubieten. Demgegenüber soll dieses Kapitel zeigen, dass soziale Ungleichheiten das Produkt einer Geschichte von Zirkulationen sind. Deshalb betreffen sie nicht nur bestimmte Akteurkategorien auf der vertikalen Ebene, oder bestimmte Mitglieder aus denselben Akteurkategorien auf der horizontalen Ebene. Sie haben auch Querschnittsfolgen auf Akteurkategorien und Akteure in anderen Sequenzen von einer gegebenen Relationsstruktur sowie auf Akteurkategorien und Akteure in anderen Relationsstrukturen, die sie in Bezug auf die drei wichtigsten Momente ihrer Zirkulation -- den Eintritt in und den Austritt aus Zirkulationen, sowie den Wechsel von Zirkulationen -- bestimmen. Nichtsdestotrotz erlaubt der Blick auf die Verselbständigung der Medien orientierten Relationsstruktur in unseren zeitgenössischen Gesellschaft deshalb eine geschärfte relationale Betrachtung von sozialen Ungleichheiten, weil diese Relationsstruktur die Dynamik von sozialen Ungleichheiten besonders drastisch darstellt.

Tatsächlich merken wir vom Standpunkt der Theorie der Relation nicht nur, dass soziale Ungleichheit nicht abgeschafft werden kann, was konkret bedeutet, dass Zirkulationen, selbst wenn Zirkulationen die strukturellen Eigenschaften von Relationsstrukturen subvertieren, solche strukturellen Eigenschaften von Relationsstrukturen nicht einfach abschaffen können. Vielmehr tragen Zirkulationen dazu bei, die Wirkungen von sozialen Ungleichheiten in Zeit und Raum, von einer Akteurkategorie zu einer anderen, von einer Ebene von gesellschaftlichen Instanzen zu einer anderen, von einer Sequenzen und einer Relationsstruktur zu einer anderen zu verschieben. Oder anders gesagt: Zirkulationen tragen im Allgemeinen zwar dazu bei, dass soziale Ungleichheiten abgemildert werden. Können Zirkulationen jedoch nicht oder nur mit viel Zeit und Aufwand entwickelt werden, dann tragen sie zur Stärkung von sozialen Ungleichheiten bei, von denen in der Folge diejenigen Akteurkategorien und Akteure betroffen sind, die sich mit solchen Zirkulationen auseinandersetzen, wie wir etwa am Beispiel des Doppellebens der Künstler gesehen haben. Mit Zirkulationen verschieben sich allerdings auch die sozialen Ungleichheiten. Sie werden neu strukturiert und in ihren Wirkungen für die Akteurkategorien und Akteure neu bestimmt, die nicht nur solche Zirkulationen entwickeln, sondern die auch von solchen Zirkulationen mehr oder wengier mittelbar betroffen sind, weil sie sich in anderen Akteurkategorien, Sequenzen oder Relationsstrukturen befinden.

Wir sagten in unserem Exkurs zur sozialen Ungleichheit, dass die Theorie der Relation die Frage der sozialen Ungleichheit in ähnlicher Weise wie die Forschenden der Intersektionalität versteht, selbst wenn in der Theorie der Relation das Spektrum der Relationalität von sozialer Ungleichheit deutlich erweitert wird. Es handelt sich nicht nur darum, die kumulativen Wirkung der sozialen Ungleichheit an der Schnittstelle von Klassen- und Geschlechtsverhältnissen und den Verhältnisse zwischen Ethnien zu untersuchen. Es handelt sich vielmehr darum, diese Wirkung an der Schnittstelle der drei Ebenen des Primat der Zirkulation zu dimensionieren, um auf diesem Weg die Wirkung von sozialen Ungleichheiten in Teilbereichen von Relationsstrukturen -- etwa in ihren Sequenzen -- und in ihrer Reichweite für alle anderen Bereiche der anderen Sequenzen und Relationsstrukturen adressieren zu können. Dass solche Wirkungen nicht homogen sind und sich darüber hinaus translokal bzw. transregional und transnational erstrecken, ist vom Standpunkt der Theorie der Relation selbstverständlich, weshalb eben jene Selbstverständlichkeit auch ab der Frage verdeutlicht werden muss, wie die Entwicklung von Zirkulationen andere Zirkulationen beschleunigen kann und diese anderen Zirkulationen wieder andere Zirkulationen ausbremsen oder ganz und gar verhindern können.

In einer idealen Gesellschaft würden wir uns mit einer idealen, perfekt zufriedenstellenden Relation zwischen Menschen und mit unseren spirituellen und natürlichen Umgebungen beschäftigen. Mauss glaubte an die Konkretisierung von einer solchen idealen Gesellschaft, die er mit der genossenschaftlichen Organisation der Gesellchaft und des Staates verbindete. Weil Genossenschaften die verschiedensten Bereiche von einer Gesellschaft verkörpern -- nach Mauss vor allem die rechtlichen, wirtschaftlichen, politischen und kulturellen Bereiche -- und sie stets zugunsten von harmonischen Verhältnissen zwischen den Menschen entwickeln werden würden, stellten sie ein transversales Organisationsprinzip von Gesellschaften dar, das überall entwickelt werden sollte. Ein solches Prinzip sei nicht mit zeitgenössischen Gesellschaften entstanden, sondern es sei vielmehr eine historische Tendenz, die sich von den alten bis zu unseren Gesellschaften bewahrt habe. Deshalb obliege es den Menschen mit gutem Willen, dieses Prinzip in dessen historischer Tendenz aufzugreifen und es in all ihrer Potentialität zu realisieren. Aber wie Mauss schon in seinen jungen Jahren feststellte, wird die Relation als Legitimationsordnung der Gesellschaft in weitere Legitimationsordnungen ausdifferenziert, die versuchen, sich aufeinander zu verbreiten und sich gegenseitig zu beeinflussen. Die Entwicklung von Mediationen, die eigene Verhältnisse produzieren und gestalten können, und zwar auf der Ebene einer eigenen Legitimationsordnung, stellt eine weitere Stufe in dieser fortschreitenden Ausdifferenzierung dar, die es erforderlich macht, weitere Untersuchungen der Relation in ihren abweichenden Formen von Strukturen und Sequenzen, die unseren Gesellschaften auf der Grundlage der Einschreibung von Akteuren, Instanzen, Aktanten und Medien in Zirkulationen zu modellieren. Dies definiert den Horizont der Aufgaben, denen sich die Theorie der Relation widmet. Diese Aufgabe bleibt unmittelbar mit der Frage verbunden, wie bzw. unter welchen Bedingungen und zu welchem Preis Gesellschaften, die eine solche Relativierung von Relation als Entstehung von abweichenden Legitimationsordnungen bzw. abweichenden Relationsstrukturen und (Teil)Sequenzen erleben, erhalten bleiben.
