---
title: "Vorwort"
indent: true
output:
    html_document: default
bibliography: Rel-Bib.bib
lang: de-De
header-includes:
  - \usepackage[german=quotes]{csquotes}
---

Die Soziologie beschäftige sich mit Relation als Themenkomplex, darunter eine Vielfalt von relationalen Phänomenen verstanden werden würden, die die Existenz und die Entwicklung der Existenz von sowohl Menschen als auch Nicht-Menschen bestimmen und Gesellschaften in ihrer inneren synchronen sowie dyachronen Verflechtung ausmachen würden. Diese Botschaft ist nicht neu, sondern sie wird von der Entstehung der Soziologie als Universitätsfaches und wissenschaftliches Forschungbereiches bis in unsere Zeit immer wieder hervorgehoben. Gleichzeitig geht die Beschäftigung mit einem solchen Ansatz in der Soziologie häufig brüchig vor. Relationale Perspektiven gibt es einerseits zahlreiche. Andererseits sind sie mehr oder weniger stark strukturiert, manchmal mit der Verwendung von spezifischen Methoden oder auch mit bestimmten Arten von sozialen Verhältnissen verbunden, und dabei werden sie häufig wenn nicht mehrheitlich vom Standpunkt mikrosoziologischer Perspektiven herausgearbeitet. Vermehrte relationale Ansätze sind nicht nachteilhaft für die soziologische Untersuchung. Sie gewährleisten etwa die Auswahlmöglichkeiten von einem an einer bestimmten Untersuchung angepassten relationalen Ansatz. Vom Standpunkt der Arbeit an der Theoriebildung in der Soziologie stellt sich jedoch die Frage, ob es nicht sinnvoll und vielleicht auch erforderlich wäre, von der Stufe, die solche Ansätze darstellen, zur nächsten Stufe der Entwicklung eines Theorierahmen zu übergehen, der dem Gegenstand der Relation gewidmet und von der Relation vollständig strukturiert wäre.

Diesem Projekt sind wir in unserem Band _Skizze einer Theorie der Relation_ (2022) nachgegangen, den wir als Theorierahmen konzipiert haben, der vollständig durch Relation strukturiert ist und gleichzeitig zur Untersuchung gesellschaftlicher Phänomene durch Relation führen soll. Unsere Intention bei dieser Veröffentlichung war zuerst mit dem Anspruch verbunden, analytisch ins Detail der Begrifflichkeit und der unterschiedlichen Ebenen einer solchen Theorie vorzugehen, damit die Architektur der Theorie veranschaulicht wird. Dort hat uns die Arbeit an der Theorie im Vordergrund beschäftigt, die wir im Kontrast zum für die Theorie der Relation inspirierenden Theorieansatz der Soziologie Pierre Bourdieus gestaltet haben. Dieser Kontrast war nicht nur epistemologisch, sondern auch pädagogisch vorteilhaft. Damit kann besser verstanden werden, wie eine Theorie der Relation die Relation nicht auf einen anderen Gegenstand -- im Fall von Bourdieu auf Position als Hebel einer spezifischen Art von Relation bzw. als Hebel von Machtverälthnissen -- reduziert werden soll. Dagegen muss die Relation in ihrer Komplexität als transversale gesellschaftliche Dynamik verstanden werden muss, die konstruktiv und produktiv für die Entwicklung von einem Theorierahmen auf der Grundlage vom Primat der Zirkulation problematisiert wird.

In dieser Monographie verfolgen wir ein anderes Ziel bzw. wollen wir zur folgenden weiteren Stufe gehen, die den Einstieg in und den Zugang zur Theorie der Relation und ihren sie bildenden Theoriefiguren erleichtern soll. Dieses Ziel wollen wir durch Verwendung von einer Doppelstruktur erreichen, die für die folgenden Kapitel in diesem Band tragend ist. Zum Beginn jedes der Kapitel -- in thematischer Orientierung am Kapitel-Aufbau der vorangegangenen Monographie -- werden ein entsprechender Theoriebaustein mit den damit konvergierenden Konzepten in gebotener Kürze expliziert. Anschließend wird es darum gehen, die jedem Kapitel vorangestellte kompakte Einführung, d. h. die jeweilige Theoriefigur, sowohl anhand bestimmter Gegenstände als auch anhand klassischer wie nicht-klassischer soziologischer Themen exemplarisch zu konkretisieren. Auf Basis dieser für jedes Kapitel einzuhaltenden Doppelstruktur sollen einerseits Anwendungsfelder und die Bandbreite des Erklärungspotentials aufgezeigt werden.

Konkret starten wir in dieser Monographie mit einem Prolog zur Ausgangslage der Theorie der Relation mit der Frage, ob die Soziologie eine Theorie der Relation überhaupt braucht. Die Theorie der Relation ist ein Rahmen zur Deutung gesellschaftlicher Phänomene _durch_ Relation, was die Position präzisiert, die diese Theorie in der Soziologie und speziell in der Familie der relationalen Soziologien bezieht. Mit dem Ausdruck _durch Relation_ unterscheidet sich die Theorie der Relation von anderen relationalen Soziologien, die Gesellschaft als Relation bzw. als eine Zusammenstellung von sozialen Verhältnissen verstehen. Wenn die Theorie der Relation mit den anderen relationalen Soziologien darüber übereinstimmt, dass relationale Ereignisse der Ausgangspunkt der soziologischen Untersuchung bilden, so unterscheidet sie sich doch gleichzeitig von diesen relationalen Soziologien in Bezug auf ihre Grundannahme, die die Theorie der Relation nicht nur hinterfragt, sondern daraus sie die Motivation für die Gründung eines Theorierahmens zieht, mit dem den relationalen Ansatz in der Soziologie neu gedacht werden kann. In dieser Hinsicht repräsentiert die Theorie der Relation Tendenzen der soziologischen Tradition in deren Breite, die sich zentral mit einem relationalen Ansatz in dieser Disziplin auseinandergesetzt haben, auch wenn sie gleichzeitig ein Argument zur aktuellen Theoriedebatte in der Soziologie liefert, dessen Aufbau und Folgen sie von dieser Tradition emanzipiert und ihr ihren eigenen Weg bereitstellt. Dies zeigt sich typischerweise an dem Begriff der Relationsstruktur, dass als Abweichung von einer idealen bzw. perfekten Relation verstanden wird, davon die formale und strukturalistische Formulierung durch das Primat der Zirkulation subvertiert wird, nach dem die Theorie der Relation grundsätzlich argumentiert. Dem Argument der Abweichung folgend, unterscheidet die Theorie der Relation vier Relationsstrukturen, deren sequentielle Entstehung sowie die damit verbundenen Grundbegriffen in diesem Prolog veranschaulicht werden.

Nachdem im Prolog gezeigt wurde, dass es im Bereich relationaler Soziologien notwendig ist, sich von einer rekonstruktiven Repräsentation der Gesellschaft als Relation zu distanzieren, um Gesellschaft durch Relation untersuchen zu können, soll im Kapitel _Was uns die Reziprozität der Gabe erzählt_ das Reziprozitätskonzept der Theorie der Relation im Zentrum stehen. Im Bereich der relationalen Soziologien gibt es eine Übereinstimmung, die die Theorie der Relation teilt, nach der relationale Ereignisse eine Idee von Reziprozität hervorrufen. Dennoch bleiben die relationalen Soziologie vage, wenn es präzisiert werden soll, was eine solche Reziprozität soziologisch bedeutet und wie sie mit relationalen Ereignissen in Verbindung kommen sollte. In diesem Kapitel heben wir in dieser Hinsicht insbesondere ein Manko der relationalen Soziologien hervor, das darin besteht, die Einbettung institutioneller Logiken bei der Einbettung von Akteuren in Mikrointeraktionen konsequent zu berücksichtigen. Um dieses Manko auszuräumen bricht die Theorie der Relation mit dem traditionellen Verständnis von Relation _als_ Zwischenmenschlichkeit, was es in der Folge erlaubt, Reziprozität nicht mehr _als_ ein reziprozierendes Hin und Zurück zwischen Akteuren aufzufassen, sondern Reziprozität vielmehr in Bezug auf Relationsstrukturen und Zirkulation auszubuchstabieren. Dazu gehört es nicht nur, die Reziprozität als Legitimationsmoment der Akteure und ihrer Tätigkeiten, die Reziprozität als Verteilungs- und Schließungsinstrument von Relationsstrukturen zu charakterisieren, sondern auch die Verbindung der Reziprozität zum Widerstand der Akteure kenntlich zu machen.

Das Paradebeispiel, das wir in diesem Rahmen verwenden, um über die Reziprozität im Sinne der Theorie der Relation zu sprechen, ist die Gabe in ihrer unterschiedlichen Formen in der Zeit und der unterschiedlichen Gesellschaften. Wenn Gaben eine starke Idee von Reziprozität mit sich bringen, ist diese Auffassung der Reziprozität ohne Berücksichtigung der Einschreibunsakte von Akteuren in Relationsstrukturen durch ihre Einschreibung mit den Instanzen der Vermittlung dieser Relationsstrukturen (z. B. Organisationen, Vereine, Verbände etc.) und der Einschreibung von Vermittlungsinstanzen in Relationsstrukturen durch ihre Einschreibung mit den Akteuren in diesen Relationsstrukturen nicht denkbar. In der Theorie der Relation führt diese Auffassung von Reziprozität zur Argument, dass einerseits Relationsstrukturen eine Pluralität an Lebenswegen und Lebensmöglichkeiten anbieten, die jedoch je nach Relationsstrukturen mit einem speziellen Verständnis von Reziprozität verbunden sind, die andere Relationsstrukturen nicht teilen bzw. genuin ablehnen, um ihre eigene pluralen Welten auf anderen Relationsstrukturen zu verbreiten. Dies beschreibt eine Tragik der Reziprozität, die aus Einschreibungsakten schöpft, um Verteilungen und Schließungen in Relationsstrukturen zu entwickeln, die auf der Ebene von Akteuren sowohl Widerstand als auch Umstellung von Positionen hervorrufen.

Unter Rekurs auf die in den ersten und zweiten Kapiteln thematisierten Grundbegriffe der Theorie der Relation soll die Grundlage der Konzeptualisierung von vier Relationsstrukturen vorgestellt werden. Dies unterstreicht abermals, dass für die Theorie der Relation keine ontologische Perspektive auf Relation, sondern vielmehr eine Analytik der Zirkulation tragend ist, die deshalb die vier Relationsstrukturen voneinander unterscheidet. Dass sich die vier Relationsstrukturen durch die Zirkulation voneinander abheben, erklärt sich damit, dass jede Relationsstruktur über eine ihr spezifische Kernsequenz verfügt, die nicht nur den Anfangs- und Endpunkt der Zirkulation einer jeden Relationsstruktur markiert, sondern auch die jeder Relationsstruktur eigene sequentielle Ordnung mitbestimmt. Eingedenk dieser Tatsache soll in diesem Kapitel gezeigt werden, wie die Zirkulation in den vier Relationsstrukturen verläuft. Dabei soll es auch darum gehen zu zeigen, dass zwar alle Relationsstrukturen prinzipiell auf alle Tätigkeiten und Tätigkeitsbereiche von Akteuren offen sind; die tatsächliche Entwicklung und Durchführung solcher Tätigkeiten und Tätigkeitsbereiche letztlich aber von der Zirkulation, d. h. der sequentiellen Ordnung der Zirkulation, in einer Relationsstruktur abhängt, durch die bestimmte Tätigkeiten und Tätigkeitsbereiche gefördert, andere dagegen behindert werden.

Zur Illustration der zirkulären Struktur von Relationsstrukturen, der internen Strukturierung von Tätigkeiten und Tätigkeitsprofilen und der damit verbundenen Zirkulation in diesen Relationsstrukturen soll die in der Wirtschaftswissenschaft und Wirtschaftssoziologie gängige organizistische Metapher des _Selektionsdrucks_ mit dem Gesellschaftsbereich der Kunst und des Kunstbetriebs konfrontiert werden. Ziel ist es, deren Erklärungsgehalt und Geltungshorizont in Bezug auf die sukzessive Expansion künstlerisch-kreativer Tätigkeiten und Tätigeitsbereiche in andere Relationsstrukturen und -- visa versa bzw. dem Primat der Zirkulation entsprechend -- die sukzessive Expansion bestimmter Medien orientierter, politisch orientierter sowie wirtschaftlich orientierter Tätigkeiten und Tätigkeitsbereiche in die sozio-kulturell-künstlerisch orientierte Relationsstruktur zu plausibilisieren und kritisch zu prüfen.

Im nachfolgenden Kapitel _Die Attraktivität der Repräsentation. Stars als Anführer_  werden die Folgen der im dritten Kapitel für die vier Relationsstrukturen vorgestellten Zirkulation behandelt. In den vier Relationsstrukturen entwickeln sich Zirkulationen auf der Grundlage von der jeweiligen Kernsequenzen dieser Relationsstrukturen sowohl innerhalb jeder Relationsstruktur und Sequenz dieser Relationsstrukturen als auch zwischen Relationsstrukturen. Diese Zirkulationswege bestimmen die Entwicklung der Erwartungen von Akteuren in Verbindung mit Kollektiven bzw. Instanzen der (positiven sowie negativen) Sanktionierung von solchen Erwartungsstrukturen. Sie tragen entsprechend zur Hierarchisierung der Akteuren in Akteurkategorien und zur Mobilität dieser Akteure unter Rekurs erstens auf diese Akteurkategorien, zweitens auf den für diese Akteurkategorien jeweils charakteristischen Widerstand _für_ die Relation/Position und _gegen_ die Position/Relation und drittens auf die Reziprozität als Voraussetzung jedweder Zirkulation von Akteuren in und zwischen Relationsstrukturen. Entlang dieser thematischen wie inhaltlichen Schwerpunkte gilt es übergeordnet zu zeigen, dass das Primat der Zirkulation nicht zwangsläufig eine theoriegeleitete wie symmetrische Unterbewertung der Position von Akteuren zur Folge haben muss, sondern das Wechselspiel zwischen Zirkulation und Position in systematischer Weise Berücksichtigung findet und einen nicht zu unterschätzenden Beitrag zur Neuperspektivierung von sozialer Mobilität leistet.

Um die Thematik der Akteurkategorien und der Hierarchien zwischen den Akteurkategorien auf der Grundlage von Zirkulationswege und Zirkulationsmöglichkeiten zu veranschaulichen, wenden wir uns vor allem dem Politischen bzw. der sozio-politisch orientierten Relationsstruktur vom Standpunkt der Puristen von Relationsstrukturen und von Sequenzen zu. Dabei berücksichtigen wir insbesondere Puristen der Sequenzen bzw. Akteure, für die die Sequenz, in der sie sich befinden, zum Gravitationszentrum ihrer Relationsstruktur werden sollte. Solche Akteure unternehmen deshalb alles, um die Zirkulation in ihrer Relationsstruktur vom Standpunkt ihrer Sequenz zu gestalten, was ihre eigene Zirkulation in die Richtung von einer anderen Relationsstruktur entwickelt, in der ihre Sequenz die Kernsequenz dieser Relationstruktur darstellt. Dieses Streben nach einer anderen Struktur der Zirkulation, wovon diese Puristen der Sequenz die Hauptvertreter sind, wird anhand von Fallbeispielen bzw. von Akteure wie Arnold Schwarzenegger, Wolodymyr Selenskyj, dem Künstler Albrecht Dürrer und anderen in den Blick genommen. Diese Akteure eint, dass sie alle einen Zirkulationsweg von der sozio-kulturell (konkret der künstlerisch und der wissenschaftlich) orientierten Relationsstruktur in die politisch orientierte Relationsstruktur zurückgelegt haben. Über die Auswahl dieser Akteure soll gleichsam demonstriert werden, dass sich die Theorie der Relation für die Perspektivierung sowohl gegenwärtiger als auch historischer Zirkulationswege im Sinne sozialer Mobilität eignet.

Zirkulationswege und Zirkulationsmöglichkeiten werden nicht nur im Sinne ihrer Verbreitung entwickelt, sondern sie können auch schrumpfen, was zur Schrumpfung von Erwartungsstrukturen und zur Deklassierung von Akteuren in Relationsstrukturen führen kann. Dieser Fall, bei dem die Einschreibung von Akteuren und Instanzen in Relationsstrukturen immer schwieriger wird bzw. geschwächt und gestört wird, kann ebenfalls dazu führen, dass Akteure ihre Relationsstruktur für eine andere Relationsstruktur verlassen, in der sie weitere Zirkulationsmöglichkeiten entwickeln können und weitere Zirkulationswege bahnen können. Im Kapitel _Der Verlust der Gnade Gottes. Abstufung, Abwanderung und neue Macht der Päpste_ stellen wir ein Beispiel von einer solchen absteigenden Zirkulation im Rahmen der katholischen Religion vor.

Dieses Kapitel zeigt im Kontrast zum vierten Kapitel, dass absteigende Zirkulationen nur ein Moment von einem Zirkulationsweg darstellen, der nicht das Schicksal von einem solchen Zirkulationsweg für seine Akteure zwangsläufig bestimmt. Absteigende Zirkulationen, wie wir es insbesondere im Rahmen des Machtverlustes der katholischen Päpste zeigen werden, sind auch manchmal die Bedingung für die Repositionierung von Akteuren in anderen Relationsstrukturen und für die Entstehung von weiteren aufsteigende Zirkulationen entweder innerhalb dieser Relationsstruktur oder zwischen dieser und anderen Relationsstrukturen. Das eine solche neue Entwicklung von Zirkulationswegen von Akteuren Zeit braucht, zeigt das Beispiel der katholischen Relation ebenfalls. Sich neue Zirkulationswege und Zirkulationsmöglichkeiten zu erschaffen, braucht den Wiederaufbau der Arbeit an relationalen Ereignissen und an der Mobilisation von Akteuren, die Etablierung und Institutionalisierung von Kollektiven, die kaum innerhalb des Lebens von Einzelmenschen machbar ist. Dieser Generationsansatz, den die Theorie der Relation bei der Erklärung von langen und komplexen Zirkulationswegen unterstützt, verdeutlicht die Bedeutung der sozialen Geschichte in der _longue durée_ von Lebenswegen, um die Dimensionierung von Relationsstrukturen bzw. ihre Verbreitung und ihre Schrumpfung besser erklären zu können.

Zirkulationswege und Zirkulationsmöglichkeiten sind zahlreich, und sie tragen wesentlich zur Expansion und Schrumpfung von Relationsstrukturen, was wiederum Folgen für die Instanzen der Vermittlung von diesen Zirkulationswegen und Zirkulationsmöglichkeiten hat. In diesem Kapitel beschäftigen wir uns mit diesen Kollektivakteuren, die Vermittlungsinstanzen von Relationsstrukturen sind, und die im Kontrast zu anderen Akteuren und Aktanten innerhalb oder zwischen Relationsstrukturen nicht zirkulieren, sondern eine Position beziehen und halten, um Zirkulationswege und Zirkulationsmöglichkeiten für andere Akteure zu gewährleisten. In diesem Sinne sind Vermittlungsinstanzen einerseits Stütze von Relationsstrukturen, die ohne Vermittlungsinstanzen nicht existieren würden. Aber andererseits gibt es unterschiedliche Arten von Vermittlungsinstanzen je nach Akteurkategorien, Sequenzen und Relationsstrukturen, davon manche diesen Akteurkategorien, Sequenzen und Relationsstrukturen spezifisch sind, davon anderen in unterschiedlicher Form überall vorhanden sind. Gemein haben diese Vermittlungsinstanzen, dass sie ihre Vermittlungsstruktur und dabei asymmetrische Verhältnisse zu anderen Vermittlungsinstanzen mit der Absicht entwickeln, die Instanz zu werden, die die Einschreibung von Akteuren in Relationsstrukturen für alle Akteure in allen Sequenzen von Relationsstrukturen und allen Relationsstrukturen fördern. Dies führt unvermeidlich zu Einflussstrategie zwischen Vermittlungsinstanzen innerhalb von Sequenzen, Relationsstrukturen und zwischen Relationsstrukturen. Um diesen Punkt der Einflussstrategien von Vermittlungsinstanzen zu adressieren, beschäftigen wir uns im Kapitel _Vermittlungsinstanzen sind nicht gleich Vermittlungsinstanzen. Noten, Emojis und Farben im Ausbildungssystem_ mit Evaluationsmaßnahmen im Ausbildungssystem.

Das Ausbildungssystem bietet einerseits eine Vielfalt an Vermittlungsinstanzen in den vier Relationsstrukturen. Andererseits zegen Vermittlungsinstanzen des Ausbildungssystems eine innerliche Diversität nicht nur je nach Relationsstrukturen, sondern auch innerhalb von jeder Relationsstruktur. Deshalb haben wir im Ausbildungssystem mit Instanzen zu tun, die hoch differenziert sind, und entsprechend hoch differenzierte Verfahren entwickeln, um ihre Einschreibung mit Akteuren in ihrer Relationsstruktur bzw. in eine Sequenz ihrer Relationsstruktur zu fördern. Ein Mittel dafür ist die Evaluation von Einschreibungen durch symbolische und formale Medien, die das Ausbildungssystem in der Form von Noten, Emojis und Farben entwickelt hat und manchmal immer noch entwickelt. In diesem Kapitel geht es darum, zu zeigen, wie die Entwicklung von solchen symbolischen und formalen Medien die Entwicklung der Vermittlungsstruktur von Instanzen des Ausbildungssystems unterstützt, die deshalb in Konkurrenz zur Entwicklung der Vermittlungsstruktur von anderen Instanzen des Ausbildungssystems tretet, was zu Kontroversen über die Evaluationspolitik und Selektivität von Vermittlungsinstanzen des Ausbildungssystems führt, die wir in diesem Kapitel darstellen werden.

Auf der Grundlage der im vorherigen Kapitel sechs eingeführten Arten von Vermittlungsinstanzen, ihren je spezifischen Besonderheiten und ihrer fluktuierenden Bedeutung für die vier Relationsstrukturen wird im siebten Kapitel _Kunst und Tücken der Umverteilung. Das Doppelleben der Soziologinnen_ eine weitere Ausdifferenzierung von Vermittlungsinstanzen in Relationsstrukturen vorgenommen. Zentral hierfür ist, dass die Differenzierung zwischen Vermittlungsinstanzen in vier Relationsstrukturen in der Theorie der Relation nicht allein auf dem Vergleich zwischen diesen Instanzen beruht, sondern darüber hinaus erstens auf Basis der Zirkulation der Akteure innerhalb einer Relationsstruktur und zwischen Relationsstrukturen sowie zweitens hinsichtlich der Anpassung der Zirkulation in Relationsstrukturen erfolgt. Vor diesem Hintergrund wird einerseits ersichtlich, dass die Stärkung oder Schwächung/Störung einer bestimmten Art von Vermittlungsinstanz mit der Stärkung oder Schwächung/Störung der Zirkulation in einer Relationsstruktur zusammenhängt und inwiefern demzufolge Vermittlungsinstanzen im Vergleich zu anderen Vermittlungsinstanzen derseleben Relationsstruktur durch etwaige Anpassungen der Zirkulation gestärkt oder geschwächt/gestört werden. Dieser Zusammenhang ist deshalb von besonderer Relevanz, weil über ihn erklärlich wird, dass die Destabilisierung der allgemeinen Zirkulation in den vier Relationsstrukturen mit der Schwächung der Schwerkraftzentren von diesen Relationsstrukturen zugunsten derjenigen Art von Vermittlungsinstanz einhergeht, die auf dem Weg der sukzessiv erfolgenden Anpassung der Zirkulation in den vier Relationsstrukturen jeweils gestärkt wird. Eine solch dynamische Perspektivierung von Vermittlungsinstanzen plausbilisiert ferner, dass auch die Zirkulation von Akteuren in und zwischen Relationsstrukturen unter bestimmten Bedingungen Veränderungen unterworfen ist und diese Veränderungen Einfluss auf die Reziprozität innerhalb einer Relationsstruktur ausüben. Sie wirken etwa reziprozitätserschwerend bzw. reziprozitätserleichternd, oder sie unterbrechen die Reziprozität. Dies vergegenwärtigt sich wiederum sowohl <!-- -- entsprechend des legitim gültigen Hierarchieprinzips (Eigenständigkeit und Verbindlichkeit), das mit einem bestimmten Zustand der Zirkulation in den vier Relationsstrukturen einhergeht -- --> in der Zu- und Abnahme von Mobilitäts- bzw. Zirkulationsmöglichkeiten in den vier Akteurkategorien einer Relationsstruktur als auch im Zu- oder Abstrom von Akteuren aus Relationsstrukturen, was sich wiederum im Wachstum oder in der Schrumpfung dieser Kategorien von Akteuren äußert.

Diese komplexen Zusammenhänge werden zum einen vornehmlich unter Bezugnahme auf den Bereich des Journalismus, d. h. auf die Medien orientierte Relationsstruktur, und zum anderen unter Rekurs auf fünf Soziologinnen -- Germaine de Staël-Holstein, Harriet Martineau, Jenny d'Héricourt, Beatrice Webb und Jane Addams -- plausbibilisiert. Diese Soziologinnen zeichnet aus, dass sie zwar alle im 19. und zu Beginn des 20. Jahrhunderts Soziologie betrieben haben und in engem Austausch zu ihren männlichen Kollegen standen, ihnen aber prinzipiell der legitime Zugang zur Wissenschaft verwehrt war. <!-- weshalb sie auch heute noch weitgehend aus dem Kanon der Klassiker der Soziologie ausgeschlossen sind. Aus diesem Mangel heraus schlugen diese ausgewählten --> Diese Frauen schlugen einen <!-- zu dieser Zeit durchaus häufigen --> Zirkulationsweg ein, der mit zahlreichen Wechseln zwischen bestimmten, immer gleichen Sequenzen entweder innerhalb einer Relationsstruktur oder zwischen zwei Relationsstrukturen -- dem Bereich der Wissenschaft und den Bereich des Journalismus -- verbunden war und ihnen somit zahlreiche Umstellungen zwischen Position und Relation abverlangte. <!-- Anders gesprochen, blieb diesen von der Wissenschaft ausgeschlossenen Frauen nichts anderes übrig, als sich neben ihrem ausgeprägten Engagement im Bereich der Wissenschaft auch im Bereich des Journalismus oder der Literatur zu betätigen, um überhaupt an der Sozialität teilhaben zu können, auch wenn das gleichzeitig bedeutete, eine Art Relationsstruktur-Hopping betreiben zu müssen. --> Solche Zirkulationswege lassen sich als Pseudozirkulationen verstehen, weil dabei lediglich stetige <!-- ellipsenförmige --> Hin- und Zurück-Bewegungen zwischen zwei Sequenzen in einer Relationsstruktur oder zwischen zwei Relationsstrukturen vollzogen werden, die stark von regulären Zirkulationsmöglichkeiten abweichen. Sie demonstrieren, was geschieht, wenn die Zirkulation einer Relationsstruktur und mithin die Relationsstruktur selbst geschwächt ist, die Anpassung der Zirkulation über die Umverteilung von Akteuren notwendig wird, wie viel Zeit eine solche Anpassung in Anspruch nehmen kann und inwiefern davon andere Relationsstrukturen und deren Vermittlungsinstanzen profitieren.

In der Theorie der Relation kommt dem _Medien_-Begriff eine tragende und zugleich vielschichtige Rolle zu. <!-- Tragend und vielschichtig deshalb, weil --> Dies erklärt sich damit, dass die Einbeziehung von (symbolischen wie formalen) Medien durch Akteure in deren soziale Arbeit einerseits und die Eingliederung von (symbolischen) Medien durch die Vermittlungsinstanzen in deren Vermittlungs- und Formalisierungsarbeit andererseits <!-- ist dazu imstande, als --> aus diesen Medien die Mediationen der doppelten Einschreibung macht. <!-- zu fungieren -->. <!-- Dadurch gewährleisten --> Ferner unterstützt der Einsatz von Medien <!-- bei relationsstrukturadäquaten Ge- und Verbrauch nicht nur die stabile und stetige --> nicht nur die Zirkulation von Akteuren in und zwischen Sequenzen von Relationsstrukturen, nicht zuletzt weil die Unterschiede zwischen den Zirkulationen einer Relationsstruktur für die Akteure sichtbar bleiben. Medien bzw. die Rekurse auf und die Formalisierungen von Medien helfen auch dabei, die Position von Vermittlungsinstanzen in Relationsstrukturen strukturell zu stärken und zu bewahren sowie deren Verbreitung über die gesamte Relationsstruktur sicherzustellen. Dies trägt maßgeblich zur Stabilität der Zirkulation in einer Relationsstruktur bei, und es stärkt die entsprechende Relationsstruktur insgesamt gegenüber den anderen Relationsstrukturen. In diesem Sinne reduziert die Theorie der Relation Medien nicht allein auf Massenmedien (der öffentlichen Kommunikation), geschweige denn auf Print-, Rundfunk- oder Onlinemedien. Vielmehr versteht die Theorie der Relation unter symbolischen Medien immaterielle und materielle Mediationen, die <!-- im Unterschied zu Bourdieus Theorie symbolischen Kapitals --> von ausnahmslos allen Akteuren und Vermittlungsinstanzen unabhängig von der Relationsstruktur bezogen werden können. Über den Bezug durch Akteure werden sie zu Leitmedien dieser Akteure, davon sie die Umstellung von Positionen in und zwischen Relationsstrukturen und zwar kraft der Reziprozitätsmöglichkeiten untertützen, die sie je nach Relationsstruktur potentiell bereitstellen. Über den Rückgriff durch Instanzen von Relationsstrukturen werden sie in den Dienst von formalen Operationen dieser Vermittlungsinstanzen gestellt. Sie werden zu formalen Medien, die formale Verfahren von Instanzen unterstützen und als formale Träger von Hierarchieprinzipien in Relationsstrukturen fungieren, für deren Durchsetzung sich die Arten von Vermittlungsinstanzen in jeder Relationsstruktur einzusetzen versuchen.

Um die Bedeutung und gleichzeitig die Verwendung von Medien an der Seite von Akteuren und von Vermittlungsinstanzen zu illustrieren, verwenden wir im Kapitel _Glanz und Misere des Plagiats. Zur Attraktivierung der Medien_ ein Beispiel aus der Praxis der Wissensproduktion in Bezug auf die Frage der Legitimation von Wissen angefangen mit dem Plagiat. Das Plagiat setzt eine Verwendung von vorhandenem Wissen voraus, das aufgenommen und im Rahmen von einem neuen Wissenskontext mehr oder weniger neu gestaltet wird. Grundsätzlich setzt das Plagiat eine Praxis des Exzerpierens voraus, die eine lange Geschichte hat und im Kontrast zu zeitgenössischen Praktiken des Exzerpierens -- wie heutzutage im Kontext vom Plagiat oder der Verwendung von digitalen Sprachmodellen -- positiv konnotiert war bzw. als eine legitime Art und Weise galt, Wissen zu produzieren. Am Beispiel von solchen Praktiken wird gezeigt, wie Hierarchieprinzipien im Rahmen der Produktion von Wissen je nachdem entweder durchgesetzt oder geschwächt werden, wie solche Medien der Wissensproduktion zum einen von Akteuren als Symbole ihrer Tätigkeiten und zum anderen von Vermittlungsinstanzen in Unterstützung ihrer formalen Verfahren in Relationsstrukturen einbezogen werden. Dabei stellt sich die Frage danach, wie nicht nur andere Praktiken der Wissensproduktion, sondern auch andere Formen von Wissen und andere Wissenskulturen durch die Unterstützung von Zirkulationswegen anhand von Medien stabilisiert bzw. destabilisiert werden.

Das Kapitel neuen _Die Verlockung von Meta-Relationsstrukturen. Verschmutzung teilen_ knüpft insofern auf das Kapitel acht an, als zunächst darauf hingewiesen wird, dass sowohl der Stil, wie Akteure symbolische Medien in ihre Arbeit einbeziehen, als auch der Stil, wie Vermittlungsinstanzen erstens diese Einbeziehung durch die Akteure und zweitens die symbolischen Medien selbst (nach Form und Funktion, zu Medienkontexten oder relationalen Dispositiven) formalisieren, nicht nur die jeweilige Bedeutung der Reziprozitätsmacht innerhalb einer Relationsstruktur <!-- (multimodal in Ri, bimodal in Rr und Rm, unimodal in Ra) --> generiert [@PapilloudSchultze2022, 374], sondern auch die Stärke dieser Reziprozitätsmacht mitbestimmt, die wiederum zur Zirkulationsmacht einer jeden Relationsstruktur maßgeblich beiträgt (vgl. ebd., 372). Stellen wir nun ferner in Rechnung, dass die Stärke der Reziprozitätsmacht in einer Relationsstruktur sowohl die Zirkulationsmacht von Akteuren darin als auch die Machtposition von Instanzen dieser Relationsstruktur ausdrückt und abbildet, so setzt die Bewahrung der Reziprozitätsmacht einer Relationsstruktur die Sicherstellung sowohl solcher Zirkulationen als auch solcher Positionen voraus (vgl. ebd., 374). Eingedenk der Tatsache, dass die Instanzen einer Relationsstruktur im Unterschied zu Akteuren -- _unmittelbar_ zur Reziprozitätsmacht und deren Ausmaß beitragen und zwar indem sie am Ausbau, der Verbreitung und Effektivität ihrer Vermittlungsstruktur arbeiten, spielen die Instanzen bzw. Schwerkraftzentren einer Relationsstruktur eine besondere Rolle für die Bewahrung und Stärkung der Reziprozitätsmacht in einer Relationsstruktur. Um also einer möglichen Deprivation der Reziprozitätsmacht entgegenzuwirken, sind Vermittlungsinstanzen ständig versucht, an Einfluss in ihrer Relationsstruktur zu gewinnen und zwar entweder indem sie die Entstehung und Verbreitung anderer Vermittlungsinstanzen _verhindern_ oder indem sie bereits bestehende Instanzen innerhalb oder außerhalb ihrer Relatonsstruktur _satellisieren_ (vgl. ebd., 374f.).

Wenn Verhinderungsstrategien hohe Kosten für Relationsstrukturen haben, weil die Verhinderung von externen Einflüssen die Verbreitung von Relationsstrukturen schwächt und stört, haben dagegen Satellisierungsstrategien Vorteile für Relationsstrukturen. Bei solchen Strategien handelt es sich für Relationsstrukturen darum, Einflüsse auf die anderen Realtionsstrukturen über Allianzen zwischen Vermittlungsinstanzen der selben Art in den unterschiedlichen Relationsstrukturen zu üben. Eine solche Strategie zielt darauf ab, eine Meta-Relationsstruktur anhand von solchen Vermittlungsinstanzen zu etablieren, die deshalb als Meta-Relationsstruktur beschrieben werden kann, weil sie von Zirkulationen und Wirkungen dieser Zirkulationen auf die Relationsstruktur frei wäre, als ob sie eine ideale perfekte Relation wäre. Diesen Punkt werden wir im Kapitel 9 am Beispiel des _personal carbon trading_ (PCT) im Rahmen der Debatten zum Klimawandel behandeln. In der Folge von ähnlichen mehr oder weniger glücklichen Initiativen zwischen Ländern und zwischen Großindustrien, die darauf abzielen, ein gemeinsames Karbonbudget zu definieren und auf Länder bzw. Großindustrien aufzuteilen, um Karbonemissionen einzuschränken, macht das PCT ein Schritt weiter: Es erweitert das Prinzip des Karbonbudgets auf alle Einzelakteure in allen Tätigkeitsbereichen einer Gesellschaft. Das PCT zeigt somit, wie es versucht wird, Schwierigkeiten bei der Einschränkung von Karbonemissionen durch die Verbreitung vom PCT auf alle Relationsstrukturen zu lösen, die insbesondere der Satellisierungsstrategie der wirtschaftsorientierten Relationsstruktur zugute kommt. Für diese Relationsstruktur verspricht die Durchsetzung vom PCT neue Entwicklungsmöglichkeiten mit Entstehung von einem wirtschaftlichen Markt, auf dem es möglich wäre, Profite und neue Wertschöpfungsquellen anhand von der Karbonverschmutzung durch den Austausch von Karbonanteilen privater Akteure sowie Kollektivakteure zu generieren.

Die in dieser Monographie dargestellten Beispiele haben Kernelemente der Theorie der Relation illustriert, die im Schlußwort in ihrer Bedeutung im Bereich der soziologischen Theoriebildung hervorgehoben werden. Diese Hervorhebung basiert auf Veränderungen, die die Theorie der Relation in die soziologische Theorie einführt und die wie folgt zusammengefasst werden können: Mit ihrem Primat der Zirkulation und ihrem Verständnis von Relation nach einem makrosoziologischen Ansatz will die Theorie der Relation den Relationismus vermeiden, der die Beschreibung von gesellschaftlichen Phänomenen als Relation mehrfach belastet. Der Relationismus beschreibt die eine Art der Substantialisierung von Relation, die davon ausgeht, das Relation in der Form von relationalen Ereignissen alles miteinander verbindet. Die Theorie der Relation macht einen entscheidenden Schritt jenseits des Relationismus ab ihrer Auffassung von Relationsstrukturen als Abweichungen von einer idealen Relation und ab ihrer Unterscheidung zwischen Relationsstrukturen, relationalen Ereignissen und Zirkulationen, was die Perspektive für die Analyse von nicht oder passiven relationalen Ereignissen und im Allgemeinen von nicht bzw. passiven handeln in ihrer Bedeutung für Zirkulationen zulässt. Ferner dekonstruiert die Theorie der Relation mit ihrem Verständnis von Reziprozität die optische Metapher von einem "Hin und Zurück" als feste Dynamik von relationalen Ereignissen sowie den damit verbundenen Glauben, dass Reziprozität genuin aus interpersönlichen Beziehungen entstehen würde. Auf diese Weise öffnet die Theorie der Relation die soziologische Analyse auf Legitimationsprozesse ab der Entwicklung von Zirkulationen, was zur Folge hat, dass Fragen, die mit Legitimationprozessen verbunden sind -- darunter traditionelle Fragen der Anerkennung, der sozialen Ungleichheit, der Herrschaft --, unmittelbar mit der sozialen Arbeit an Zirkulationsentwicklungen in und zwischen Relationsstrukturen problematisiert und reflektiert werden können, statt sie kategoriell bzw. auf Kategorien von Akteuren und Kollektivakteure zu reduzieren. Dies geht nicht ohne eine rekonstruktive Analyse von solchen Zirkulationsentwicklungen, was den Untersuchungen im Rahmen der Theorie der Relation eine geschichtliche Dimension verleiht, wie wir es in den in dieser Monographie erwähnten Beispielen hervorgehoben haben.

Daraus ergibt sich die Botschaft, die mit der Theorie der Relation verbunden ist. Sie besagt, dass Relation als ideale, perfekte Relation die Grundmotivation des sozialen Lebens und die Grundlage der Rechtfertigung der vielfältigen Verhältnisse darstellt, die das gesellschaftliche Leben generiert und die Abweichungen von einer solchen idealen Relation in der Form von Relationsstrukturen sequentiell dimensionieren. Die Theorie der Relation erklärt entsprechend, wie dieses Streben nach einer idealen Relation auf den unterschiedlichen Ebenen einer Gesellschaft ständig gestört wird, woraus bzw. wodurch wiederum Laufbahnen von Akteuren, Mobilisierungen von Kollektivakteuren, Einschreibungsakte, auf- und absteigende Mobilitäten, Veränderungen von Ungleichheiten, von Einflussstrategien und Machtkämpfen sowie gesellschaftliche Blasen als verwundbare Meta-Relationsstrukturen produziert werden.
